### ISSUE TITLE
스크립트로 사이트지원 요청드립니다!

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1314]
안녕하세요 선생님. 
지난번 만들어주신 drupl 너무 너무 잘 사용중입니다.감동입니다..
혹시 아래의 사이트도 스크립트로 지원 가능할까요? 
https://www.zcool.com.cn/
 
선생님의 빛나는 능력에 많은 사람들이 매일 은혜를 입고 있다고 생각합니다. 
정말 감사드립니다. 감기조심하세요!

+내용추가+
만들어주신 drupl 사이트와 비슷한 구조일지도 모르겠네요.
사진의 리스트를 눌러서 쓰레드로 들어가면 작은 사진들이 쭉 뜹니다.
그리고 그 사진을 누르면 큰 사진이 뜹니다. 예시 url을 긁어봤습니다.

예시 쓰레드:
https://www.zcool.com.cn/work/ZNDAxNDc4Njg=.html

작은사진:
https://img.zcool.cn/community/0165485db03ed8a801209e1f45b242.jpg@1280w_1l_2o_100sh.jpg

큰사진:
https://img.zcool.cn/community/0165485db03ed8a801209e1f45b242.jpg@2o.jpg

**Comment by tdi2020** [comment]
안녕하세요 선생님! 
혹시 요 사이트는 이번 업데이트에 포함되어 있을까요?
그리고 새해 복 많이 받으세요!

**Comment by KurtBestor** [comment]
아직이요
tdi2020 님도 새해 복 많이 받으세요!
