### ISSUE TITLE
pornhub 다운로드 건의드립니다

### ISSUE THREAD

**Issue by lsggr1** [KurtBestor/Hitomi-Downloader#1320]
pornhub에서 특정 유저의 페이지 주소를 입력하면 그 유저가 업로드한 동영상을 전부 받게 하는 기능이 있었으면 좋겠습니다 (pixiv처럼요!)
항상 감사드립니다.

**Comment by tdi2020** [comment]
와 이거 지원되면 정말 좋겠네요!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
정말 엄청난 기능입니다.감사합니다!!

**Comment by tdi2020** [comment]
https://www.pornhub.com/channels/bang-bus

해당 채널같은 경우는 채널이지만 긁어지지가 않는것 같습니다.
Videos에 보면 137개로 카운트가 되고 있지만 긁히지 않아서 남겨두겠습니다.
실패시 출력 정보는 아래와 같습니다.




--------------------------------------------------------------------------------------





Invalid: [pornhub] https://www.pornhub.com / channels / bang-bus

version: 2.7d
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://www.pornhub.com/channels/bang-bus
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/channels/bang-bus
valid: False
done: True
range: None
range_p: None
single: True
time: 1573758207.6 (Nov 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
videos
fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "pornhub_downloader", line 342, in get_videos
Exception: Not supported url

stop
Traceback (most recent call last):
File "utils", line 790, in start
File "utils", line 837, in start_
File "pornhub_downloader", line 135, in read
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "pornhub_downloader", line 342, in get_videos
Exception: Not supported url


Invalid: fail=True
EOT: https://www.pornhub.com/channels/bang-bus

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lsggr1** [comment]
늘 수고하십니다. 몇개의 계정을 테스트 해본 바 제 컴퓨터에서는 정상적으로 잘 작동이 됩니다.  혹시.. 폰헙 업로드 유저마다 따로 폴더로 분류되는것까지는 힘들까요?
감사합니다!

**Comment by KurtBestor** [comment]
@lsggr1 필요한 이유가 있나요?

**Comment by tdi2020** [comment]
https://www.pornhub.com/pornstar/remy-lacroix

선생님 수정된 버전이 정상적으로 작동하는 것을 확인했습니다!
그런데 위와같은 페이지는 다운이 불가능할까요?
pornstar 페이지로 분류되어 있어서 그런지 크롤링이 안되는것 같아요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
https://www.pornhub.com/pornstar/emily-willis

선생님 테스트 해보았습니다!
그런데 위 주소를 예를 들면, 
Free Videos 에 3개는 받아지는데
Emily Willis's Videos 에 (이 배우가 출연한 비디오) 375개는 크롤링 추가가 안되는것 같습니다!

**Comment by KurtBestor** [comment]
@tdi2020 

해당 채널 유저가 직접 올린 동영상만 다운로드해요.

최근순으로 1 ~ 10 페이지 까지 다운로드 하는데 360 ~ 480 개 까지 다운로드해요. (채널 종류에 따라 다름)

**Comment by lsggr1** [comment]
@KurtBestor 

답장이 많이 늦었네요.. 죄송합니다. 딱히 이게 필요하다 싶은 이유는 없습니다. 그저 다운로더로 pixiv나 sankaku 모아받기에 제가 익숙해져서, 이러면 어떨까 했던 것 뿐입니다. 
 
지금의 버전으로도 매우 충분히 유용하게 사용가능합니다. 감사합니다!

**Comment by tdi2020** [comment]
선생님 혹시 최근순 360~480개가 맥시멈이라면 영상이 더 있는 경우 읽어오는 전체갯수를 더 읽어오는 방법이 있을까요?

**Comment by KurtBestor** [comment]
@tdi2020

페이지 지정하지 않고 그냥 다운로드하면 일괄적으로 가장 최근 500 개만 다운로드되게 했어요.
501 번째 부터 1000번째 까지 다운로드하려면 다음과 같이 하면 돼요:
- `주소바에 채널 주소 입력` - `다운로드 버튼 우클릭` - `페이지 지정 다운로드` - `501~1000` 입력

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
@lsggr1 

`옵션` - `설정` - `일반` - `플레이리스트 한 폴더에 다운로드` 에서 설정하실 수 있어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
