### ISSUE TITLE
픽시브 팬박스 다운로드 기능 추가 부탁드려요

### ISSUE THREAD

**Issue by univdev** [KurtBestor/Hitomi-Downloader#1323]
제가 유료로 지원하고 있는 일러스트레이터가 있는데 이 일러스트레이터가 올린 자료들 중 제가 열람이 가능한 자료들을 모두 다운받고 싶습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/457

**Comment by cocoman1111** [comment]
링크 타고 가니까 닫힌 문제라고만 나오는데... 지원이 안되는건가요??

**Comment by KurtBestor** [comment]
@cocoman1111 아직은요

**Comment by cocoman1111** [comment]
아 감사합니다~
