### ISSUE TITLE
기본데이터 다운로드 불가

### ISSUE THREAD

**Issue by wpfhfpr** [KurtBestor/Hitomi-Downloader#1362]
삭제된 데이터는 잘됩니다만 기본 데이터가 안되는 군요.
이전 2.7c로 다운받은 건 잘되서 복사해서 쓰고 있습니다. 서버문제는 아닌것같습니다.
언제나 잘 사용하고 있습니다.감사합니다.

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by wpfhfpr** [comment]
네 안되는 거로 확인되네요 이전버전은 정상작동하는 것으로 이번 패치되면서 잘못된 점이 있는 것으로 보입니다.

**Comment by KurtBestor** [comment]
이전 버전 다시 다운로드해서 되는지 확인했나요?

**Comment by wpfhfpr** [comment]
이전버전에선 잘 다운됩니다. 그래서 이전버전에서 다운로드해서 이번버전에 폴더를 복붙해서 사용하고 있습니다.

**Comment by KurtBestor** [comment]
이전 버전 실행파일 새 버전 경로에 덮어씌운 다음에 다운로드 해도 잘 되나요?

**Comment by wpfhfpr** [comment]
hitomi_data 폴더를 이동시키는 식으로 사용중입니다. 실행 파일을덮어씌우진 않구요.
2.7c 버전에서 기본데이터 다운로드 후 생성된 파일의 hitomi_data를 
2.7d(현재버전)의 실행파일이 있는 폴더에 붙여넣어서 사용하고 있습니다.
방금 전에도 확인해보니 현재버전은 다운이 되질 않구요. ㅠ

**Comment by KurtBestor** [comment]
이전 버전 실행파일 새 버전 경로에 덮어씌운 다음에 다운로드 해서 되는지 확인해주세요.

**Comment by wpfhfpr** [comment]
그렇게 되면 2.7c로 변경되서 업데이트할거냐고 물어봅니다.근데 해결은 했습니다.
경로에 한글이 들어가면 안되는 거였네요. 삭제된 데이터는 잘되는 데 기본데이터다운로드는 한글 경로에 영향을 받는 것 같습니다. 감사합니다

**Comment by KurtBestor** [comment]
업데이트 물어보면 취소하고 실행시키면 돼요.

**Comment by Hiddle00** [comment]
@KurtBestor 전 c버전 사용하다가 e버전으로 넘어왔고, 마찬가지로 경로에 한글빼주고 사용하고 있습니다.

실행파일 덮어씌워도 기본데이터는 다운이 안됩니다.
에러메세지는 안뜨는데 [0/20]상태에서 넘어가질 않습니다.
근데 또 삭제된 데이터는 다운로드 됩니다.

cmd에서 패킷 사이즈 조절해서 해결 봤다는 글을 보긴 했는데 자세한 방법은 모르겠네요.

프로그램 감사히 사용하고 있습니다. 도움이 되실까 싶어서 아는대로 적어봤습니다.
