### ISSUE TITLE
중복 이미지 찾기 관련 문의 

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#1391]
혹시 중복이미지 찾기 해서 나온 결과를 따로 저장햇다가 다시 불러올수 있는 기능을 추가 될수 있을까요 ?

제가 한번 사용할때마다 지금은 약 160만장의 이미지 나중에 더 추가 될 계획이긴하지만 .

한번 검색할때마다 대충 약 18시간 소요 되며 중복이미지가 약 3만8천장 넘게 나옵니다.

이러다보니 컴퓨터에 무리가 가다보니 나온결과를 저장햇다가 다시 불러오는 기능 추가가 될까요?

또한 중간에 저장한후에 다시 검색결과를 불러와서 거기서부터 이어서 검색을 이어 가던가요 ..

솔직히 하드가 맛탱이 가고 있는듯한 느낌으로 엄청 시끄러워서요 ;;;;

아 또 중복 이미지 찾기중에 삭제하는데 그경로에 파일이 없으면 오류뜨고 그냥 있더라고요 

이거 목록에서 삭제되게끔도 가능한가요 ?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/74651728-ce515580-51c7-11ea-82ad-870044b029ac.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
잘 작동 됩니다!

**Comment by kenasis428** [comment]
220만장 검색 결과 잘 작동됩니다 .

그리고 다른 파일 중복 검사하고 다시 220만장 검색 시도하니 

전에 저장된 캐쉬가 있어서 그런지 검색시간이 28시간에서 > 1시간으로 어마어마하게 시간이 단축되었습니다 .

그리고 파일추가 해서 다시 중복 검사 해본결과 

추가된 파일 포함은 추가한대로 중복결과가나오고
기존에 있던 파일들 또한 캐시가 저장한 결과인지 바로바로 시원스럽게 넘어가다군요.

매우 만족스러운 패치입니다. 

감사합니다.
