### ISSUE TITLE
하니메 다운로드 오류

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#1457]
하니메에서 어떤거 다운로드받을때 일부 영상이 15분짜린데 막 3분이나 몇십초처럼 짧게 나오거나 30시간 파일로 다운로드되면서 영상뒤쪽은 다 오류생기는 경우가있네요
그래서 여러번 재시도하다보니 빨간오류가 생기기도 하네요
(빨간오류는 제가 뭐 실수해서 그런걸수도있구)
짧거나 길게 다운로드 됬을때는 정보가 안뜨고
빨간오류생겼을때만 정보뜨네요
이건 빨간오류생겼을때 정보입니다
Invalid: [hanime] https://hanime.tv / videos / hentai / hotaruko-2

version: 2.7d
platform: Windows-10-10.0.18362
order: 11
group: False
gal_num: https://hanime.tv/videos/hentai/hotaruko-2
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/hotaruko-2
valid: False
done: True
range: None
range_p: None
single: False
time: 1575554934.52 (Dec 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "hanime_downloader", line 168, in get_video
File "hanime_downloader", line 43, in __init__
Exception: No segments

stop
Traceback (most recent call last):
File "utils", line 765, in start
File "utils", line 812, in start_
File "hanime_downloader", line 79, in read
File "constants", line 633, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 607, in wrapper
File "hanime_downloader", line 168, in get_video
File "hanime_downloader", line 43, in __init__
Exception: No segments

Invalid: fail=True
EOT: https://hanime.tv/videos/hentai/hotaruko-2

**Comment by ATGOS** [comment]
정보안뜰때 렉도 있었던거 같기도 하구

**Comment by KurtBestor** [comment]
잘못 다운로드 된 파일 보내주시면 분석해볼게요.

**Comment by ATGOS** [comment]
[[Discovery] Pigeon Blood 1.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4052170/Discovery.Pigeon.Blood.1.zip)
까맣게 잊고있다가 지금 보내 드리네요..
이 파일은 이번 2.7e 업데이트후 다운로드 파일입니다. 증상은 같은거같아요

**Comment by ATGOS** [comment]
위 파일의 정보입니다
전과는 달리 짧네요
[Discovery] Pigeon Blood 1

version: 2.7e
platform: Windows-10-10.0.18362
order: 2
group: False
gal_num: https://hanime.tv/videos/hentai/pigeon-blood-1
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/pigeon-blood-1
valid: True
done: True
range: None
range_p: None
single: True
time: 1578886597.59 (Jan 13)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_hanime\[Discovery] Pigeon Blood 1.mp4


[URLs]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by ATGOS** [comment]
이걸로 다운받으면 아에 재생이 안되요

**Comment by ATGOS** [comment]
원래버전에서 하나씩 천천히 다운받으면 오류가 안생기는듯하네요
그저 저의 네트워크문제인가 ㅡ3ㅡ

**Comment by KurtBestor** [comment]
어떤 동영상 플레이어 쓰시나요?

**Comment by ATGOS** [comment]
윈도우10에 영화및TV? 라고 기본설치되있던거 써요

**Comment by ATGOS** [comment]
이번 업데이트 이후 다시 시도해봤습니다.
우선 전과 달리 하나씩 천천히해도 이와 같은 증상이 생깁니다
1. 1월 15일에 다운받은 영상과 같이 맨 오른쪽에 길이가 떠야 하는데 안뜸.
2. 파일에 들어가면 오류가 발생했다면서 재생이 안됨
사진1 ![111](https://user-images.githubusercontent.com/56113395/73061086-ae868480-3edc-11ea-98d2-c5cde7f72e59.PNG)
사진2 ![222](https://user-images.githubusercontent.com/56113395/73061094-b1817500-3edc-11ea-9296-1e5745301bde.PNG)

오류난 파일중 하나
를 보내려했는데 압축해도 용량이너무크네요
정보입니다

[GOLD BEAR] Ryuudouji Shimon no Inbou 2

version: 2.7h
platform: Windows-10-10.0.18362
order: 10
group: False
gal_num: https://hanime.tv/videos/hentai/ryuudouji-shimon-no-inbou-2
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/ryuudouji-shimon-no-inbou-2
valid: True
done: True
range: None
range_p: None
single: True
time: 1579859413.99 (Jan 24)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_hanime\[GOLD BEAR] Ryuudouji Shimon no Inbou 2.mp4


[URLs]


+ 항상 감사합니다
   저때문에 너무 고생하시네요 
   그냥 시간조금날때 해주세요 감사합니다 ㅜㅜ

**Comment by KurtBestor** [comment]
TS 파일 지원하는 동영상 플레이어로 재생해주세요.
참고해주세요: https://answers.microsoft.com/en-us/windows/forum/windows_10-files/ts-files-on-windows-10/081f5264-1cf0-4743-b9a3-e67f92d71e7b
