### ISSUE TITLE
다운로드 대기화면 오류..? 

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#1485]
![image](https://user-images.githubusercontent.com/53850082/70884984-da2f6880-201a-11ea-9fdf-e8b95c5759dc.png)

픽시브 꺼 가끔 다운받다보면 그냥 흰색으로 만나오네요 ..

소거법으로 나오긴 나왓는데 .. 이런건 ..

아.. 다운은 완료뜨는데 저 대기화면 목록..?

저기에는 어느새 보면 흰색 바로 떠있네요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by kenasis428** [comment]
보여드리고 싶어도 아무 반응이 없습니다. 그냥 저렇게 뜨고 아무 것도 못해요. 제거만 가능해요.

**Comment by KurtBestor** [comment]
해당 작업 선택 후 `작업` - `선택된 작업들 내보내기...` 눌러서 만들어진 `*.hds` 파일 보내주시면 분석해볼게요.

**Comment by kenasis428** [comment]
[{"version": "0.3", "type": "HDT"}, {"t_retry": null, "subtitle": false, "version": "2.7d", "dones": [], "tags": [], "lock": false, "dir": "", "isGroup": false, "str_pixmap": "", "title0": null, "pbar": [0, 0, " %v / %m"], "done": false, "names": [], "range_p": null, "etc_button": null, "label_color": null, "paused": false, "msgs": [], "firstImg": "", "title": "", "url": "", "gal": null, "artist": null, "range": null, "pause_data": null, "name_zip": "", "icon_text": null, "valid": true, "anime": true, "urls": [], "time": null, "type": "", "gal_num": null, "filesize": 0}]

**Comment by kenasis428** [comment]
version: 2.7d
platform: Windows-10-10.0.17763
order: 291
group: False
gal_num: None
dir: 
zip: 
type: 
artist: None
url: 
valid: True
done: False
range: None
range_p: None
single: True
time: None (Dec 20)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False


[Gallery]
None


[File Names]



[URLs]

**Comment by kenasis428** [comment]
이번거는 ... 픽시브인지 겔부루인지 판단이 안되네요.
일단 또 다운중에 발견해서 올립니다 . 
다행히 이번에는 정보쪽 열려서 같이 올리고  
작업hds 파일이 안올라가서 메모장으로 열어서 올립니다.

**Comment by kenasis428** [comment]
이번건 픽시브 쪽입니다 . 

다운로드 등록 후 프로그램 종료 후 다시 실행하면 발생하는 현상같습니다 .

그것도 확률적으로요 .. 

version: 2.7d
platform: Windows-10-10.0.17763
order: 282
group: False
gal_num: None
dir: 
zip: 
type: 
artist: None
url: 
valid: True
done: False
range: None
range_p: None
single: True
time: None (Dec 22)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False


[Gallery]
None


[File Names]



[URLs]

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주세요.

**Comment by kenasis428** [comment]
Checking for updates... HitomiDownloader2

쥵핣썢싸괠뼿뾌몘똁폺꾄꺃뗚졂춼쿔뼚탦뗃뙚쿝륦첌릫꿁퇩싌텑뽹폧훆붯삤룅왌폻뼱걝살쉊냄뭄됕바솮왛먿궚톼럫햸싷깋컼뫆쐟빾휂얾쭟귿카햙눤싊쟇거냧쵔로콐썒착쳂괄곬쁡쨁읡욥턙뻋돼갂

4.8.6 / 4.11.2 / 4.16.3
Font: Gulim -> 맑은 고딕
Supported Image Formats: ['bmp', 'pbm', 'pgm', 'png', 'ppm', 'xbm', 'xpm']
v2.7d (latest: v2.7d)
Encodings: ['cp949', 'mbcs', 'ascii', 'utf-8', 'ascii']
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2940, in append_datas_
  File "customWidget", line 857, in setSerializedData
ValueError: Unmatched ''"' when when decoding 'string'

[append_datas] elapsed time: 22.6907621
GoodbyeDPI activated

Styles:
    Windows
    WindowsXP
    WindowsVista
    Motif
    CDE
    Plastique
    Cleanlooks

start GoodbyeDPI
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1456, in run
WindowsError: [Error 32] : u'hitomi_downloaded_pixiv\\\u30db\u30af\u30ed\u6d41\u661f\u7fa4\uff20\u30cb\u30fc\u30c8 (pixiv_14493467)\\70244876_p0 [\u7537\u306e\u5a18]\u843d\u66f8\u304d\uff17\uff19\uff12\u306e\u9854\u5c04.zip'

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1456, in run
WindowsError: [Error 32] : u'hitomi_downloaded_pixiv\\\u30db\u30af\u30ed\u6d41\u661f\u7fa4\uff20\u30cb\u30fc\u30c8 (pixiv_14493467)\\70244876_p0 [\u7537\u306e\u5a18]\u843d\u66f8\u304d\uff17\uff19\uff12\u306e\u9854\u5c04.zip'

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1456, in run
WindowsError: [Error 32] : u'hitomi_downloaded_pixiv\\\u30db\u30af\u30ed\u6d41\u661f\u7fa4\uff20\u30cb\u30fc\u30c8 (pixiv_14493467)\\70244876_p0 [\u7537\u306e\u5a18]\u843d\u66f8\u304d\uff17\uff19\uff12\u306e\u9854\u5c04.zip'

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1456, in run
WindowsError: [Error 32] : u'hitomi_downloaded_pixiv\\\u30db\u30af\u30ed\u6d41\u661f\u7fa4\uff20\u30cb\u30fc\u30c8 (pixiv_14493467)\\70244876_p0 [\u7537\u306e\u5a18]\u843d\u66f8\u304d\uff17\uff19\uff12\u306e\u9854\u5c04.zip'

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1456, in run
WindowsError: [Error 32] : u'hitomi_downloaded_pixiv\\\u30db\u30af\u30ed\u6d41\u661f\u7fa4\uff20\u30cb\u30fc\u30c8 (pixiv_14493467)\\70244876_p0 [\u7537\u306e\u5a18]\u843d\u66f8\u304d\uff17\uff19\uff12\u306e\u9854\u5c04.zip'

Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Traceback (most recent call last):
  File "downloader", line 264, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: http://twitpic.com/bm97m2

Traceback (most recent call last):
  File "downloader", line 264, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: http://twitpic.com/bm97m2

Traceback (most recent call last):
  File "downloader", line 264, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: http://twitpic.com/bm97m2

Traceback (most recent call last):
  File "downloader", line 264, in read_html
  File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: http://twitpic.com/bm97m2

Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted
Directory Deleted

**Comment by KurtBestor** [comment]
데이터가 잘못된 것 같은데 실행파일과 같은 폴더 있는 `<실행파일명>.ini` 보내주시면 분석해볼게요.

**Comment by kenasis428** [comment]
[hitomi_downloader_GUI_test.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/3998776/hitomi_downloader_GUI_test.zip)

**Comment by KurtBestor** [comment]
INI 파일 열 때 로그에 다음 내용 뜨면서 날아가는거라:
```
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 2940, in append_datas_
File "customWidget", line 857, in setSerializedData
ValueError: Unmatched ''"' when when decoding 'string'
```

<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 로그 열었을 때 위와 같은 오류 내역이 있으면 저장해서 덮어씌우지 말고 INI 파일 보내주시면 돼요.

이미 날아간 상태에서 저장한 거 주셔서 아무것도 할 수 없네요.
