### ISSUE TITLE
imgur 다운로드 방법 알려주세요

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#1498]
사진 전부 다운로드 하려는데 오류가 자꾸나와요

https://imgur.com/r/AngieVaronalegal/wOkbGhS

**Comment by KurtBestor** [comment]
다음과 같이 포스트 주소를 입력해주세요: https://imgur.com/r/anime/XvkndM9

**Comment by dkfle222** [comment]
https://imgur.com/r/AngieVaronalegal/wOkbGhS 사진 전부 다운로드 하려는 오류가 자꾸떠요 ㅜㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

사진 전부 다운로드하려면 다음과 같이 입력해주세요: https://imgur.com/r/AngieVaronalegal
