### ISSUE TITLE
요새 마나모아 다운로드에 오류가 나는 경우가 많아졌습니다

### ISSUE THREAD

**Issue by premium6weider** [KurtBestor/Hitomi-Downloader#1501]
만화 목록 페이지 주소를 입력하면 그 만화 전체가 다운로드되어서 그동안 편하게 이용했었는데

요즘 부쩍 군데군데 빠지고 다운로드가 안되는 현상이 잦습니다

보통 이런 경우는 마나모아 사이트 자체에 문제가 있어서 다운이 안되는거였는데

요즘은 그렇지가 않네요 마나모아 사이트에서는 잘 나오는데 다운로드만 오류가 납니다 (ex. 던전 밥 이라는 만화를 다운받는데 26화가 누락. 마나모아 사이트 들어가서 던전 밥 26화 클릭하면 거기서는 잘 나옴)

어떻게 해결이 안될까요? 부탁드립니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1386

**Comment by premium6weider** [comment]
잘 되네요 감사합니다!
