### ISSUE TITLE
제이마나 주소입력시 오류

### ISSUE THREAD

**Issue by Kilipie** [KurtBestor/Hitomi-Downloader#1502]
제이마나가 닷컴에서 닷넷으로 변경되고 다운로드할때 주소입력시 Cannot determine Type이 뜹니다.
수정 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1487

**Comment by Kilipie** [comment]
테스트 버전은 되네요. 감사합니다~
