### ISSUE TITLE
다음웹툰 리그 작품이 다운로드 되지 않는것 같습니다

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1505]
존경하는 선생님

http://webtoon.daum.net/league/view/20055

예시로 위의 다운을 시도하면
아래와 같이 뜹니다!

---------------
Invalid: [daumtoon] http://webtoon.daum.net / league / view / 20055

version: 2.7d
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: http://webtoon.daum.net/league/view/20055
dir: 
zip: 
type: daumtoon
artist: None
url: http://webtoon.daum.net/league/view/20055
valid: False
done: True
range: None
range_p: None
single: True
time: 1577129227.07 (Dec 24)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 665, in __init__
File "daumtoon_downloader", line 91, in init
File "daumtoon_downloader", line 47, in get_info
File "json\__init__", line 339, in loads
File "json\decoder", line 364, in decode
File "json\decoder", line 382, in raw_decode
ValueError: No JSON object could be decoded

Invalid: fail=True
stop
EOT: http://webtoon.daum.net/league/view/20055

--------------------

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
잘 동작하네요!! 감사합니다 선생님!
