### ISSUE TITLE
iwara 다운로드 문의해도 되겠습니까

### ISSUE THREAD

**Issue by qwesry** [KurtBestor/Hitomi-Downloader#1506]
히토미 작가나 서클처럼 [제작자이름] 동영상이름 으로 다운로드 안될까요?

한작가 모든 동영상을 드래그엔터로 다운로드 가능할까요?

This video is private 영상 다운로드 안되는데요 될까요?

여기는 후원 가능해요?

**Comment by KurtBestor** [comment]
- 나중에 추가할게요.
- 해당 주소 알려주세요.
- 해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
- 프로그램 하단 ❤️ 누르면 후원 가능해요
