### ISSUE TITLE
지난번에 한번 건의드렸던 건데

### ISSUE THREAD

**Issue by aperie** [KurtBestor/Hitomi-Downloader#1507]
마나모아 하위 항목(폴더) 삭제시 상위 폴더까지 한번에 삭제되는 부분
#1415 에서 수정해주셨는데 지금 테크니컬 프리뷰 버전 다시 받아보니 되돌아가 있는 것 같아요.

일부러 되돌리신건지 누락된 부분인지 궁금합니다.

**Comment by KurtBestor** [comment]
지금 테스트해봤는데 그대로네요.

**Comment by aperie** [comment]
지금 테크니컬 프리뷰 버전 다시 받아서 실행해봤는데 역시 개별 화수를 따로 삭제해도 상위 폴더가 모두 삭제됩니다. 괜찮다고 하시니 제 PC쪽에 뭔가 문제가 있는 건가 싶네요.

**Comment by KurtBestor** [comment]
`선택화 다운로드` 말고 개별 화 주소 입력해서 하는 건 생각 못 했네요. 고쳤어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by aperie** [comment]
아주 잘 작동합니다. 여러번 번거롭게 해 드렸는데도 빠른 피드백 감사합니다!
