### ISSUE TITLE
폰허브 다운로드에 관해 질문드립니다.

### ISSUE THREAD

**Issue by catarina38** [KurtBestor/Hitomi-Downloader#1508]
폰허브 다운로드 중 회선장애 등을 원인으로 도중에 주황색 글씨로 실패하는 경우

다운로드 하던 파일이 삭제되는 현상은 의도하신 부분인가요?

예전에는 다운로드 했던 부분까진 재생 가능하게 파일을 살려뒀었던걸로 기억합니다만...

혹시 설정 등으로 다운도중 실패한 파일을 삭제하지 않는 방법은 없을까요?

90~99퍼센트 쯤에서 실패하는 케이스가 너무 자주 발생해서요...

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by catarina38** [comment]
해당 작업내역 삭제해버려서 다음에 같은 현상 발생하면 다시 올리도록 하겠습니다
