### ISSUE TITLE
다운로드한 목록 초기화 문제

### ISSUE THREAD

**Issue by kise89** [KurtBestor/Hitomi-Downloader#1512]
가끔 이와같은 문제가 발생되어 문의드립니다.
컴퓨터나 프로그램이 비정상적으로 종료되는 경우에(프로그램오류나 블루스크린 등) 간헐적으로 목록이 초기화되는 경우가 있습니다.

그날 다운받은 목록이 초기화 되는것이아닌 전부터 다운받아져 있던 것들이 다운로드 폴더에는 
있으나 프로그램내의 목록에서 없어지는 경우입니다.

혹시 다운로드폴더에 있는 것들을 프로그램목록으로 다시 불러오는 기능은 없나요
다운받아놓은 작품들이 많아질수록 다시 다운받아서 정리하기가 매우 번거롭습니다.

**Comment by KurtBestor** [comment]
`<실행파일명>.ini` 파일에 설정과 작업 목록이 저장돼요.

백업파일을 만들어두고 저장하기 때문에 저장 중 프로그램 오류로 비정상 종료되는 경우 재실행 시 백업본으로 복구해요. 그래서 INI 파일 날아가는 경우는 컴퓨터 강제종료 또는 블루스크린에 의한 하드디스크 손상 정도일 거예요.
INI 파일 백업하거나 작업 목록 백업해주세요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/586

다운로드 폴더에 있는 것들을 모두 다시 다운로드하려면 `메뉴` - `저장 폴더에 있는 모든 갤러리 넘버 복사` 눌러서 복사한 다음 주소 바에 입력하고 다운로드 하면 돼요.
