### ISSUE TITLE
안녕하세요 단축키 관련건의 입니다^^

### ISSUE THREAD

**Issue by come00true** [KurtBestor/Hitomi-Downloader#1513]
우선 프로그램 매우 잘쓰고있습니다 감사합니다^^

건의할내용은 단축키 부분인데요
예를 들어 "다시 시작" 같은 경우에는
오른쪽 버튼을 누르고 "S" 키 혹은 마우스 클릭으로 누르는 방법인데요
이거를 전역 단축키로 어느 화면에서던지
컨트롤 + 쉬프트 + S
그리고 다운걸어놓은것전체를 다시 하고싶다면
"전체 다시 시작" 혹은 "몇분(시간)에 한번씩 전체 다시 시작"같은것이 있다면 훨씬 더 좋겠습니다^^
일종의 구독 같은 버튼이요ㅎ

저같은 경우에 인스타에서 사진을 다운받을때 요걸 이용하는데요 오늘 받고 내일 올라온 사진을 다시 받을려면 수동으로 일일이 다 해줘야하는게 귀찮아서요ㅠ

라이센스 판매나 dlc같이 돈 내야한다면 구매 의향도 있습니다ㅎ  제고부탁드립니다ㅎ

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>A</kbd> 눌러서 모두 선택한 다음 `다시 시작` 해주세요.
