### ISSUE TITLE
마나모아 다운로드 오류 질문글에 답변받았던 테스트 버전이 실행이 안됩니다

### ISSUE THREAD

**Issue by premium6weider** [KurtBestor/Hitomi-Downloader#1514]
#1501 질문했던 사람인데요 답변받았던 #1386 에 있던 테스트 버전으로 마나모아 다운로드를 이용하고있었는데

갑자기 실행이 안됩니다... [지정한 장치, 경로 또는 파일에 액세스할 수 없습니다. 이 항목에 액세스할 수 있는 권한이 없는 것 같습니다] 라는 창이 뜨면서 실행이 안되네요. 관리자 권한으로 실행해봐도 똑같습니다. (테스트 버전 말고 기존에 사용중이던 2.7d 버전은 잘 실행됩니다)

제가 오늘 자바 버전을 최신버전으로 업그레이드했는데 구버전을 삭제하겠냐는 물음이 뜨길래 '예' 버튼을 눌러서 구버전을 삭제했는데 혹시 그거와 연관이 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/530
