### ISSUE TITLE
티스토리 사이트 추가 가능한가요..?

### ISSUE THREAD

**Issue by qwertgb99** [KurtBestor/Hitomi-Downloader#1515]
4컷만화 한장짜리들 티스토리에 많이 있는데 카테고리별로
한번에 쭈욱 받을수 있는건 없을까요

네이버블로그도 카테고리 다운은 안되던데

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1280

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1280#issuecomment-692370898
