### ISSUE TITLE
마나모아 다운로드 관련 질문드립니다

### ISSUE THREAD

**Issue by sdd9334** [KurtBestor/Hitomi-Downloader#1519]
혹시 마나모아에서 만화를 다운받을때 1~100화 까지있다고치면
1~100화를 한폴더에 저장할 수 있는 기능은 없나요?
1화마다 폴더로 지정하니 넘겨서 보는게 불편하네여

**Comment by KurtBestor** [comment]
폴더 넘길 수 있는 뷰어를 쓰세요.

꿀뷰의 경우 <kbd>]</kbd> 키로 다음 폴더로 넘길 수 있어요.
