### ISSUE TITLE
네트워크 위치에 저장 시 버그

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader#1520]
안녕하세요 새해 복 많이 받으세요.

NAS를 이용해 내부 네트워크 위치를 다운로드 폴더 지정 시에 생기는 오류가 있습니다.

1 - NAS에서 내부 위치의 경우 \\192.168.0.230  과 같이 \\로 시작하는 위치를 많이 쓰는데
이러한 위치를 지정할 경우 제일 앞의 역슬래쉬 2개가 날아가면서 실행위치 폴더에 192.168.0.230 폴더를 만들고 거기에 파일을 저장해버립니다.

2 - 경로 설정 시 브라우징 버튼하지 이용하지 않고 경로 창에 직접 \\를 포함한 경로를 입력하면 파일 다운은 됩니다. 다만 유튜브를 받으면 받은 후 파일 변환 과정에서 경로가 \\를 빠진 경로로 바뀌면서 파일이 그냥 삭제되고 어디에도 남지 않게 됩니다.

**Comment by superrogin** [comment]
역슬래쉬라 쓰고 나니 제대로 표시가 안되네요, 이를테면 역슬래쉬 2개로 시작하는 위치들입니다.
역슬래쉬 대신 임시로 그냥 슬래쉬로 쓰면
//192.168.0.230
과 같은 위치들이요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
유튜브는 영상 + 소리를 합칠 때 FFmpeg를 사용하는데, 이게 UNC 경로를 지원하지 않아서 불가능해요. 로컬 디스크로 마운트해서 저장 폴더 경로 설정해주세요.

**Comment by mirusu400** [comment]
1. 탐색기로 네트워크 드라이브에 마운트(드라이브 문자 할당)
2. WebDav + RaiDrive
유튜브는 2번 방식으로밖에 테스트해보지 못했지만, 트위터와 웨이보 링크로 테스트 결과 두 케이스 다 잘 작동하는거 같습니다. 감사합니다.

실례가 안된다면 혹시 언제 업데이트 될지 여쭤봐도 될까요?

**Comment by superrogin** [comment]
안녕하세요 테스트가 약간 늦어졌습니다.

여전히 같은 증상입니다.

픽시브 아무거나 들어가서 테스트해 보았는데,

설정에서 '저장 폴더' 목록에서 pixiv를 선택후 '...' 버튼을 눌러 브라우징을 해서 경로를 선택하면 

(이하 역슬래시 대신 슬래시로 씀)
// 는 빠지고 192.168.0.14/test 와 같은 식으로 주소가 적힙니다.

저장폴더 텍스트 박스에 직접 //를 넣으면 정상적인 경로에 다운이 됩니다.


아래는 두 경우에 대한 작업 정보입니다. 
(dir 이하는 불필요해 보여서 뺐으며 역슬래쉬도 슬래쉬로 바꿨습니다.)

[ '...' 버튼으로 경로 직접 선택한 경우]
トコ@ガルパ垢 (pixiv_20646168)

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pixiv.net/users/20646168
dir: 192.168.0.14/test/トコ@ガルパ垢 (pixiv_20646168)

=> 실행파일이 있는 폴더에 192.168.0.14를 만들고 그 안에 저장함



[ 직접 경로 텍스트 박스에 // 를 입력한 경우 ]
トコ@ガルパ垢 (pixiv_20646168)

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pixiv.net/users/20646168
dir: //192.168.0.14/test/トコ@ガルパ垢 (pixiv_20646168)

=> 정상적으로 원하는 경로에 다운이 됨.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by superrogin** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

정상적으로 잘 됩니다 감사합니다 :)
