### ISSUE TITLE
사이트 추가 문의

### ISSUE THREAD

**Issue by godhen** [KurtBestor/Hitomi-Downloader#1521]
뉴토끼도 좋은 사이트지만
자료가없을때가 종종있어서

더 좋다고 생각되는 사이트들 인데
이중에 하나만이라도 추가해주실수있나요?

https://wfwf58.com/
https://www.buzztoon30.com/

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1210, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1286
