### ISSUE TITLE
산카쿠 다운로드 2000장 이상 않됩니다. 브라우저 로그인인도 소용없네요

### ISSUE THREAD

**Issue by qkskfka** [KurtBestor/Hitomi-Downloader#1524]
[chan] kazemaru_ichirouta

version: 2.7d
platform: Windows-10-10.0.16299
order: 1
group: False
gal_num: https://chan.sankakucomplex.com/?tags=kazemaru_ichirouta
dir: hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=kazemaru_ichirouta
valid: True
done: True
range: ~4834
range_p: None
single: False
time: 1577860226.04 (Jan 1)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta\19097213.jpg
[0002]~[1999] 같음
[2000] hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta\2639039.jpg

[URLs]
[0001] hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta\19097213.jpg
[0002]~[1998]같음
[1999] hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta\2639049.jpg
 hitomi_downloaded_sankaku\[chan] kazemaru_ichirouta\2639039.jpg

[Messages]
login... 0
types: img, gif, video
https://chan.sankakucomplex.com/?tags=kazemaru_ichirouta
https://chan.sankakucomplex.com/?next=7917241&tags=kazemaru_ichirouta&page=2
https://chan.sankakucomplex.com/?next=7806328&tags=kazemaru_ichirouta&page=3
https://chan.sankakucomplex.com/?next=7802067&tags=kazemaru_ichirouta&page=4
https://chan.sankakucomplex.com/?next=7652727&tags=kazemaru_ichirouta&page=5
https://chan.sankakucomplex.com/?next=7640644&tags=kazemaru_ichirouta&page=6
https://chan.sankakucomplex.com/?next=7628440&tags=kazemaru_ichirouta&page=7
https://chan.sankakucomplex.com/?next=7600920&tags=kazemaru_ichirouta&page=8
https://chan.sankakucomplex.com/?next=7565291&tags=kazemaru_ichirouta&page=9
https://chan.sankakucomplex.com/?next=7551903&tags=kazemaru_ichirouta&page=10
https://chan.sankakucomplex.com/?next=7546187&tags=kazemaru_ichirouta&page=11
https://chan.sankakucomplex.com/?next=7520868&tags=kazemaru_ichirouta&page=12
https://chan.sankakucomplex.com/?next=7506556&tags=kazemaru_ichirouta&page=13
https://chan.sankakucomplex.com/?next=7493090&tags=kazemaru_ichirouta&page=14
https://chan.sankakucomplex.com/?next=7437788&tags=kazemaru_ichirouta&page=15
https://chan.sankakucomplex.com/?next=7391145&tags=kazemaru_ichirouta&page=16
https://chan.sankakucomplex.com/?next=7380932&tags=kazemaru_ichirouta&page=17
https://chan.sankakucomplex.com/?next=7364991&tags=kazemaru_ichirouta&page=18
https://chan.sankakucomplex.com/?next=7317614&tags=kazemaru_ichirouta&page=19
https://chan.sankakucomplex.com/?next=7273557&tags=kazemaru_ichirouta&page=20
https://chan.sankakucomplex.com/?next=7247734&tags=kazemaru_ichirouta&page=21
https://chan.sankakucomplex.com/?next=7240378&tags=kazemaru_ichirouta&page=22
https://chan.sankakucomplex.com/?next=6812412&tags=kazemaru_ichirouta&page=23
https://chan.sankakucomplex.com/?next=6275437&tags=kazemaru_ichirouta&page=24
https://chan.sankakucomplex.com/?next=6148221&tags=kazemaru_ichirouta&page=25
https://chan.sankakucomplex.com/?next=6032231&tags=kazemaru_ichirouta&page=26
https://chan.sankakucomplex.com/?next=5868240&tags=kazemaru_ichirouta&page=27
https://chan.sankakucomplex.com/?next=5810816&tags=kazemaru_ichirouta&page=28
https://chan.sankakucomplex.com/?next=4986052&tags=kazemaru_ichirouta&page=29
https://chan.sankakucomplex.com/?next=4712418&tags=kazemaru_ichirouta&page=30
https://chan.sankakucomplex.com/?next=4675143&tags=kazemaru_ichirouta&page=31
https://chan.sankakucomplex.com/?next=4492704&tags=kazemaru_ichirouta&page=32
https://chan.sankakucomplex.com/?next=4403540&tags=kazemaru_ichirouta&page=33
https://chan.sankakucomplex.com/?next=4341661&tags=kazemaru_ichirouta&page=34
https://chan.sankakucomplex.com/?next=3976229&tags=kazemaru_ichirouta&page=35
https://chan.sankakucomplex.com/?next=3947748&tags=kazemaru_ichirouta&page=36
https://chan.sankakucomplex.com/?next=3835384&tags=kazemaru_ichirouta&page=37
https://chan.sankakucomplex.com/?next=3749061&tags=kazemaru_ichirouta&page=38
https://chan.sankakucomplex.com/?next=3688291&tags=kazemaru_ichirouta&page=39
https://chan.sankakucomplex.com/?next=3590893&tags=kazemaru_ichirouta&page=40
https://chan.sankakucomplex.com/?next=3571230&tags=kazemaru_ichirouta&page=41
https://chan.sankakucomplex.com/?next=3550732&tags=kazemaru_ichirouta&page=42
https://chan.sankakucomplex.com/?next=3514755&tags=kazemaru_ichirouta&page=43
https://chan.sankakucomplex.com/?next=3461899&tags=kazemaru_ichirouta&page=44
https://chan.sankakucomplex.com/?next=3441696&tags=kazemaru_ichirouta&page=45
https://chan.sankakucomplex.com/?next=3424699&tags=kazemaru_ichirouta&page=46
https://chan.sankakucomplex.com/?next=3418826&tags=kazemaru_ichirouta&page=47
https://chan.sankakucomplex.com/?next=3394709&tags=kazemaru_ichirouta&page=48
https://chan.sankakucomplex.com/?next=3370524&tags=kazemaru_ichirouta&page=49
https://chan.sankakucomplex.com/?next=3367351&tags=kazemaru_ichirouta&page=50
https://chan.sankakucomplex.com/?next=3354265&tags=kazemaru_ichirouta&page=51
https://chan.sankakucomplex.com/?next=3352512&tags=kazemaru_ichirouta&page=52
https://chan.sankakucomplex.com/?next=3347860&tags=kazemaru_ichirouta&page=53
https://chan.sankakucomplex.com/?next=3343286&tags=kazemaru_ichirouta&page=54
https://chan.sankakucomplex.com/?next=3341416&tags=kazemaru_ichirouta&page=55
https://chan.sankakucomplex.com/?next=3326596&tags=kazemaru_ichirouta&page=56
https://chan.sankakucomplex.com/?next=3323103&tags=kazemaru_ichirouta&page=57
https://chan.sankakucomplex.com/?next=3307221&tags=kazemaru_ichirouta&page=58
https://chan.sankakucomplex.com/?next=3286736&tags=kazemaru_ichirouta&page=59
https://chan.sankakucomplex.com/?next=3284734&tags=kazemaru_ichirouta&page=60
https://chan.sankakucomplex.com/?next=3282460&tags=kazemaru_ichirouta&page=61
https://chan.sankakucomplex.com/?next=3280273&tags=kazemaru_ichirouta&page=62
https://chan.sankakucomplex.com/?next=3280209&tags=kazemaru_ichirouta&page=63
https://chan.sankakucomplex.com/?next=3266588&tags=kazemaru_ichirouta&page=64
https://chan.sankakucomplex.com/?next=3265605&tags=kazemaru_ichirouta&page=65
https://chan.sankakucomplex.com/?next=3260919&tags=kazemaru_ichirouta&page=66
https://chan.sankakucomplex.com/?next=3247745&tags=kazemaru_ichirouta&page=67
https://chan.sankakucomplex.com/?next=3246622&tags=kazemaru_ichirouta&page=68
https://chan.sankakucomplex.com/?next=3245075&tags=kazemaru_ichirouta&page=69
https://chan.sankakucomplex.com/?next=3243396&tags=kazemaru_ichirouta&page=70
https://chan.sankakucomplex.com/?next=3239661&tags=kazemaru_ichirouta&page=71
https://chan.sankakucomplex.com/?next=3234469&tags=kazemaru_ichirouta&page=72
https://chan.sankakucomplex.com/?next=3001792&tags=kazemaru_ichirouta&page=73
https://chan.sankakucomplex.com/?next=2987995&tags=kazemaru_ichirouta&page=74
https://chan.sankakucomplex.com/?next=2951498&tags=kazemaru_ichirouta&page=75
https://chan.sankakucomplex.com/?next=2947214&tags=kazemaru_ichirouta&page=76
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=2947214&tags=kazemaru_ichirouta&page=76
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=2947214&tags=kazemaru_ichirouta&page=76
https://chan.sankakucomplex.com/?next=2938600&tags=kazemaru_ichirouta&page=77
https://chan.sankakucomplex.com/?next=2931532&tags=kazemaru_ichirouta&page=78
https://chan.sankakucomplex.com/?next=2915178&tags=kazemaru_ichirouta&page=79
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=2915178&tags=kazemaru_ichirouta&page=79
https://chan.sankakucomplex.com/?next=2901325&tags=kazemaru_ichirouta&page=80
https://chan.sankakucomplex.com/?next=2889062&tags=kazemaru_ichirouta&page=81
https://chan.sankakucomplex.com/?next=2859274&tags=kazemaru_ichirouta&page=82
https://chan.sankakucomplex.com/?next=2840099&tags=kazemaru_ichirouta&page=83
https://chan.sankakucomplex.com/?next=2831006&tags=kazemaru_ichirouta&page=84
https://chan.sankakucomplex.com/?next=2819594&tags=kazemaru_ichirouta&page=85
https://chan.sankakucomplex.com/?next=2805572&tags=kazemaru_ichirouta&page=86
https://chan.sankakucomplex.com/?next=2780496&tags=kazemaru_ichirouta&page=87
https://chan.sankakucomplex.com/?next=2770137&tags=kazemaru_ichirouta&page=88
https://chan.sankakucomplex.com/?next=2756193&tags=kazemaru_ichirouta&page=89
https://chan.sankakucomplex.com/?next=2749159&tags=kazemaru_ichirouta&page=90
https://chan.sankakucomplex.com/?next=2733462&tags=kazemaru_ichirouta&page=91
https://chan.sankakucomplex.com/?next=2723979&tags=kazemaru_ichirouta&page=92
https://chan.sankakucomplex.com/?next=2715206&tags=kazemaru_ichirouta&page=93
https://chan.sankakucomplex.com/?next=2705686&tags=kazemaru_ichirouta&page=94
https://chan.sankakucomplex.com/?next=2695373&tags=kazemaru_ichirouta&page=95
https://chan.sankakucomplex.com/?next=2684233&tags=kazemaru_ichirouta&page=96
https://chan.sankakucomplex.com/?next=2679397&tags=kazemaru_ichirouta&page=97
https://chan.sankakucomplex.com/?next=2668532&tags=kazemaru_ichirouta&page=98
https://chan.sankakucomplex.com/?next=2657710&tags=kazemaru_ichirouta&page=99
https://chan.sankakucomplex.com/?next=2644518&tags=kazemaru_ichirouta&page=100
https://chan.sankakucomplex.com/?next=2638411&tags=kazemaru_ichirouta&page=101
EOT: https://chan.sankakucomplex.com/?tags=kazemaru_ichirouta

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1185
