### ISSUE TITLE
마나모아 다운이 안됩니다.

### ISSUE THREAD

**Issue by xeoness** [KurtBestor/Hitomi-Downloader#1525]
단편들은 다운이 잘 되는데 화수가 많은 만화일수록 도중에 다운이 멈춰버립니다.

이게 어떻게 된 일인지, 어떻게 해결할 수 있는지 알려주실 수 있을까요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
