### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by choi9090177** [KurtBestor/Hitomi-Downloader#1527]
안녕하세요.

덕분에 유튜브 영상과 각종 만화등등 잘 받아 사용하고 있습니다.

https://yande.re

위 사이트도 자주 눈팅을 합니다만 

본 프로그램으로 다운이 가능하도록해주신다면 더욱 좋을것 같아서 

염치 불구하고 문의드립니다. 

새해 복 많이 받으시고 

좋은 한해 되시길 바랍니다 ^^

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1455

**Comment by choi9090177** [comment]
아직 추가 예정이 없으신건지 

참고 링크를 들어가봐도 답변이 없는 건의 뿐이라 잘 모르겠네요 :0
