### ISSUE TITLE
핀터레스트 특정보드 다운로드 안되는 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1528]
https://www.pinterest.co.kr/basquiat121212/sgc-%E3%82%BB%E3%83%BC%E3%83%A9%E3%83%BC%E6%9C%8D%E3%82%92%E8%84%B1%E3%81%8C%E3%81%95%E3%81%AA%E3%81%84%E3%81%A7~/

위 주소를 다운로드 할때 다운이 되지 않고 아래와 같이 출력됩니다.

-비슷하게 섹션이 나눠져있는 다른 보드는 다운이 되는 상태입니다!
-일본어로 된 제목이라서 그런지 확인해봤지만 다른건 잘 되는것 같습니다!

--------------------------------------------------------------
Invalid: [pinter] https://www.pinterest.co.kr / basquiat121212 / sgc-%E3%82%BB%E3%83%BC%E3%83%A9%E3%83%BC%E6%9C%8D%E3%82%92%E8%84%B1%E3%81%8C%E3%81%95%E3%81%AA%E3%81%84%E3%81%A7~ / 

version: 2.7e
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://www.pinterest.co.kr/basquiat121212/sgc-%E3%82%BB%E3%83%BC%E3%83%A9%E3%83%BC%E6%9C%8D%E3%82%92%E8%84%B1%E3%81%8C%E3%81%95%E3%81%AA%E3%81%84%E3%81%A7~/
dir: 
zip: 
type: pinter
artist: None
url: https://www.pinterest.co.kr/basquiat121212/sgc-%E3%82%BB%E3%83%BC%E3%83%A9%E3%83%BC%E6%9C%8D%E3%82%92%E8%84%B1%E3%81%8C%E3%81%95%E3%81%AA%E3%81%84%E3%81%A7~/
valid: False
done: True
range: None
range_p: None
single: True
time: 1577956227.34 (Jan 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
type: board
type: board
type: board
type: board
stop
Traceback (most recent call last):
File "utils", line 661, in __init__
File "constants", line 638, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 611, in wrapper
File "pinter_downloader", line 53, in init
File "pinter_downloader", line 32, in get_info
File "pinter_downloader", line 99, in board
File "pinter_downloader", line 134, in _call
Exception: API request failed

Invalid: fail=True
stop
EOT: https://www.pinterest.co.kr/basquiat121212/sgc-%E3%82%BB%E3%83%BC%E3%83%A9%E3%83%BC%E6%9C%8D%E3%82%92%E8%84%B1%E3%81%8C%E3%81%95%E3%81%AA%E3%81%84%E3%81%A7~/

**Comment by tdi2020** [comment]
https://www.pinterest.co.kr/a01023982594/%EC%95%84%EC%9D%B4%EA%B3%A0-%EC%A6%87%EC%95%84%EB%9D%BC-%ED%81%AC%EC%9C%BC%EC%9C%BD~~~~~~~~~~~~/

이것도 같은 증상입니다!

**Comment by tdi2020** [comment]
선생님 이번에 업데이트가 있어서 인스톨 해보았는데 혹시 이것은 이번 업데이트때 미해결된 항목인가요?

**Comment by KurtBestor** [comment]
아직 고쳐지진 않았어요. 의외로 좀 고쳐야할 게 많아서 나중에 할게요.

**Comment by KurtBestor** [comment]
아직 고쳐지진 않았어요. 의외로 좀 고쳐야할 게 많아서 좀  걸릴 것 같아요.
