### ISSUE TITLE
마나모아 다운로드시 화질열화가 있네요..

### ISSUE THREAD

**Issue by thankuverymuch** [KurtBestor/Hitomi-Downloader#1529]
https://manamoa.net/bbs/board.php?bo_table=manga&wr_id=362463

페이지의 마지막 이미지만 보면 확실히 알 수 있는데
히토미 다운로더로 다운로드 된것은 글씨 주변의 노이즈가 심한데 
마나모아에서 직접보면 깨끗하네요.
어쩔 수 없는건가요?

**Comment by KurtBestor** [comment]
구글 로그인하지 않으면 안 좋은 화질로 보이는 페이지가 있네요. 구글 로그인은 아직 지원하지 않아요.
