### ISSUE TITLE
[익헨] 제목 정렬이 제대로 안됩니다

### ISSUE THREAD

**Issue by ruinblack** [KurtBestor/Hitomi-Downloader#1531]
폴더명 형식은 
[artist] title (id)
입니다.

**익헨에서 직접 주소를 입력하면 
[Shindol] (C97) [DA HOOTCH (ShindoL)] Yoki Tsuma - The Good Wife ｜ 좋은 아내 [Korean] (1545159)
이렇게 작가명이 중복되어서 생성되고

**히토미 검색기에서 다운받으면
[Shindol] Yoki Tsuma - The Good Wife ｜ 좋은 아내 (1545159)
이렇게 깔끔하게 나오네요.

직접 주소 입력을 주로 이용하는데 이전에도 잠깐 중복되어 나온적이 있었습니다.
그런데 업데이트하고 나서 또 이러네요.

어떻게 해야 할까요?

**Comment by ruinblack** [comment]
문제를 해결했습니다.
업데이트 후에 tmp 폴더에 있는 실행 파일의 위치를 
업데이트 이전의 히토미 폴더에 옮겨서 생긴 문제였던 것 같습니다.
위치 복귀 시키니 파일 네임이 다시 깔끔하게 나오네요.

**Comment by KurtBestor** [comment]
히토미에 미러링 되기 전이라 그래요.

**Comment by ruinblack** [comment]
그건 아닐거라고 생각합니다.
 
신작 뿐 아니라 구작으로도 실험해 봤었거든요.
 
-----Original Message-----
