### ISSUE TITLE
MAC에서 패러럴즈 윈도우에서 아무것도 안됩니다

### ISSUE THREAD

**Issue by coriolis5** [KurtBestor/Hitomi-Downloader#1534]
패러럴즈로 가상 윈도우에서 업데이트나 기본 데이터 다운로드를 하면 
반응이 없고 멈춰버리거나 에러가 뜹니다

자동 업데이트하면 뻗어버리고

기본 데이터 다운로드시 한참있다가 에러창이 뜨며 에러창에 

Traceback (most recent call last):
  File "hitomi_searcher", line 214, in download_json
  File "hitomi_searcher", line 411, in download_json_
Exception: http://kurtbestorthonanywhere.com/static2/h_data/galleries0.zip
WTF

이렇ㄱㅔ 뜹니다.

**Comment by KurtBestor** [comment]
패러럴즈가 없어서 재현해볼 수 없네요.

**Comment by coriolis5** [comment]
이게 혹시 가장윈도우에서는 안되는 경우라도 있는지요??
