### ISSUE TITLE
nijie 가 지원이 되는군요

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1537]
공지나 지원 사이트 현황에 없기에 여전히 안 될거라 생각했는데 항상 감사합니다. 

새해 복 많이많이 받으십시오~!~!

**Comment by KurtBestor** [comment]
로그인을 하지 않으면 여러 이미지가 있는 포스트는 첫번째 이미지 밖에 못 보더라구요. 아직 완벽하게 구현은 되지 않았어요.
