### ISSUE TITLE
hiyobi에서 개인이 업로드한 작품들은 전부 다 다운로드가 안되는거 같아요

### ISSUE THREAD

**Issue by dh22659** [KurtBestor/Hitomi-Downloader#1539]
https://hiyobi.me/reader/10000075#1-

https://hiyobi.me/reader/10000074#1-

이런 사용자들이 직접 업로드한 작품들은 인식을 못해여

히토미에 없으니까요..

이것좀 고쳐주실 수 있을까요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
