### ISSUE TITLE
사이트 추가 건의드립니다

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#1540]
OnlyFans 사진이나 동영상 다운로더 추가해주실 수 있나요

**Comment by Fentanest** [comment]
Closed인데도 알람이 갈까요..? onlyfans 사이트 다운로드도 가능할까요?ㅠㅠ

**Comment by KurtBestor** [comment]
제가 OnlyFans 계정이 없어서 계정 주시면 한번 만들어볼게요

**Comment by KurtBestor** [comment]
제가 OnlyFans 계정이 없어서 계정 주시면 한번 만들어볼게요

**Comment by Fentanest** [comment]
계정을 어떻게 드려야 할까요? 비밀댓글 기능은 없는 거 같은데..

**Comment by KurtBestor** [comment]
디스코드 DM으로 주세요

**Comment by Fentanest** [comment]
디코 찾느라 한참 걸렸네요 =_=..ㅋㅋ 방금 보냈습니다. 감사합니다.
