### ISSUE TITLE
히토미 작가명 분류를 새로운 방식으로 건의합니다

### ISSUE THREAD

**Issue by JW1004** [KurtBestor/Hitomi-Downloader#1543]
히토미 Gui 잘쓰고 있습니다.
하지만 쓰면서 불편한점이 있어서 조심스럽게 건의 드립니다.

기존방식으론 한 폴더안에 *[작가명]작품명 식으로 나열되는데 수가 많아지면 보기 복잡합니다.

아예 경로에 @hitomi downloader@작가명@작품명.. 이런식으로 중간에 작가별로 새로운 폴더가 자동으로 생성되서 분류할수 있게 선택할 수 있으면 좋겠습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/13
