### ISSUE TITLE
사이트 추가 건의드립니다

### ISSUE THREAD

**Issue by DeV-EnCR** [KurtBestor/Hitomi-Downloader#1544]
https://kakuyomu.jp/

나로우나 녹턴 등은 다운이 되는데 카쿠요무는 지원하지 않네요...
부디 카쿠요무 일괄 다운로드도 언젠가 추가되었으면 좋겠네요!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
