### ISSUE TITLE
avgle 사이트에서 다운로드 할 수 있게 하는 기능 추가 가능할까요..?

### ISSUE THREAD

**Issue by dh22659** [KurtBestor/Hitomi-Downloader#1545]
제가 딱 원하는 영상이 avgle에서밖에 없는데....
ㅠㅠ 시드도 없어서 여기말고는 답이 없어요..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/607
