### ISSUE TITLE
마나모아에서 일부 만화가 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by kimch0612** [KurtBestor/Hitomi-Downloader#1547]
거의 9할 넘는 이미지는 잘 다운로드가 되는데 10~20장의 이미지를 다운로드하지 못하고 실패가 뜨는 만화들이 몇몇 있어서 에러코드와 함께 글을 남깁니다
제가 확인한 만화는 두 종류고 링크는 아래에 남길게요
https://manamoa23.net/bbs/page.php?hid=manga_detail&manga_id=1068, https://manamoa23.net/bbs/page.php?hid=manga_detail&manga_id=28

에러코드의 경우에는 깃허브의 글자 수 제한 때문에 다른 링크로 걸어두겠습니다
[https://chals.myqnapcloud.com/share.cgi?ssid=0SsSb1T](url)

감사합니다

**Comment by KurtBestor** [comment]
다음 두 화를 다운로드 실패하는데:
https://manamoa23.net/bbs/board.php?bo_table=manga&wr_id=24600
https://manamoa23.net/bbs/board.php?bo_table=manga&wr_id=2922

웹브라우저에서도 보이지 않네요.
