### ISSUE TITLE
픽시브 유저 페이지 다운 불가

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader#1550]
https://www.pixiv.net/users/1878082
주소

아래는 작업 정보입니다..

https://www.pixiv.net/member.php?id=xxxxx

였던 주소가

https://www.pixiv.net/users/xxxxx

로 바뀌면서 생긴 문제 같습니다.

https://www.pixiv.net/member.php?id=xxxxx

주소로 바꿔서 입력하면 다운이 되긴 하네요

[pixiv] Can not determine type: https://www.pixiv.net / users / 1878082

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pixiv.net/users/1878082
dir: 
zip: 
type: pixiv
artist: None
url: https://www.pixiv.net/users/1878082
valid: False
done: True
range: None
range_p: None
single: False
time: 1578468478.82 (Jan 8)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/users/1878082

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by superrogin** [comment]
잘 됩니다, 감사합니다.
