### ISSUE TITLE
[폰허브] 다운로드 중단시 해당 파일이 삭제되는 현상

### ISSUE THREAD

**Issue by catarina38** [KurtBestor/Hitomi-Downloader#1551]
안녕하세요 이전에 제보했던 현상에 관해 작업정보 첨부해서 다시 제보드립니다.

다운로드 도중 모종의 이유로 다운로드가 중단될시 해당 파일이 아예 삭제되는 현상입니다.

이전에는 다운로드 되었던 부분까지는 재생가능한 상태로 파일이 남아있던 것으로 기억하고 있습니다.

이하 작업정보 전문입니다.

【流出】女子大生ハメ撮り【japanese teen】

version: 2.7e
platform: Windows-10-10.0.17763
order: 101
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5c78ca83829f3
dir: E:\hitomi_downloaded_pornhub
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5c78ca83829f3
valid: False
done: True
range: None
range_p: None
single: True
time: 1578472222.94 (Jan 8)
tags: []
goodbyedpi: False
lock: False
color: invalid_done
paused: False

[Gallery]
None

[File Names]
[0001] E:\hitomi_downloaded_pornhub\【流出】女子大生ハメ撮り【japanese teen】.mp4

[URLs]
[0001] https://cv.phncdn.com/videos/201903/01/210539041/720P_1500K_210539041.mp4?WuFykmSOF8OR4no_DnPKDV-8sFV5K8lv11oQ1P_brKfC0PBtyoFUcBbbbvDMYiQ3EJrbgfRIa61SuAxjefTvoLbb7qKLsfiep3bNH80OpC7_CY_56WkzV-lEn0xS-eiDdPjZaTe1iywq1CVJGsX9MPUj4k0jbkvyMbGsyPn0xQ4Z98H46kuaglJqYbsVEd0QzoTPR-ZxRWCU

[Messages]
Video
[720p] 
[720p] 
[480p] 
[480p] 
[240p] 
[240p] 
[[720, 480, 240]p] 
decode
stop
valid=False 1
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5c78ca83829f3

p.s 
제 폰허브 다운로드 폴더 안에 이미 받은 파일이 꽤 많이 있기는 합니다.

혹시 다운받는 폴더 내에 파일이 지나치게 많은 것도 원인이 될수 있을까요?

**Comment by KurtBestor** [comment]
다운받는 도중에 실패하면 지워지는 건 의도된 동작이에요. 여러번 다시 시도해도 안 되는 영상이 있으면 알려주세요.

**Comment by catarina38** [comment]
답변 감사합니다!

으으 안지워지도록 설정하는 방법은 따로 없을까요?

99퍼센트에서 지워지면 되게 속쓰린데

**Comment by KurtBestor** [comment]
불완전한 파일을 그대로 두면 다시 시작할 때 이미 다운로드 된 걸로 인식해서 다운로드하지 않고 넘어가기 때문에 바꾸지 않을거예요.
