### ISSUE TITLE
일시중지 기능 수정 문의

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader#1554]
왼쪽 위 재생 모양 버튼을 누르면 전체 다운로드 일시 정지가 되는데

이 때에도 원래 진행중인 작업들은 계속 진행이 되고 이 작업들이 끝나야 비로소 

추가로 다운받지 않고 멈추게 됩니다. 

일시정지보단 추가 다운로드를 막는 버튼 같게 되네요..

다만 개별 작업들은 일시정지를 따로 할 수 있구요..

왼쪽 위 일시정지 버튼을 눌렀을 때 현재 진행중인 작업들도 모두 일시정지하게 하면 안될까요?

두가지를 분리한 다른 어떤 이유가 있으신건지 궁금합니다..

**Comment by KurtBestor** [comment]
다음과 같은 이유 때문에 분리했어요:
- 작업을 일시정지하려면 딜레이가 생김
- 전체 일시정지 했다가 다시 시작하면 다운로드 중 일시정지된 작업을 다시 시작할지 그대로 둘지 애매함
