### ISSUE TITLE
이미지 서처 사이트인 yandex의 결과 이미지들을 긁어모을 수 있게 하는 건 어떨까요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1557]
https://yandex.com/images/

아는 분들은 아실만한 이미지 서처 사이트인데 지원이 되면 유용할 것 같아서 건의드립니다.

 + 전에 건의드린적이 있는데 팔레트 등을 통해서

태그의 색깔 커스텀 및 범위를 확장할 수 있는 기능 같은 건 계획이 없으신가요?

태그가 많이 부족하네요 ';

**Comment by KurtBestor** [comment]
태그 갯수가 부족하면 코멘트 기능을 쓰세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1113

태그 갯수 확장은 계획에 있긴 한데 우선순위가 높지는 않아요.

**Comment by chbk256** [comment]
코멘트는 쓰고 있긴 한데 일단 필터에서 검색이 안 되서 한계가 있더군요. 어쨌든 계획이 있는 것 만으로도 감사합니다.

**Comment by KurtBestor** [comment]
코멘트도 검색 돼요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1113#issuecomment-524726943

**Comment by chbk256** [comment]
답변 감사합니다. 다만 한글 코멘트는 잘 검색이 되는데 영어로 된 코멘트의 경우 검색이 잘 안 먹히는 부분이 있어서 이후 시간나실 때 고려해주셨음 어떨까 합니다.

**Comment by KurtBestor** [comment]
검색이 안 되는 경우 있으면 알려주세요.

**Comment by chbk256** [comment]
다시 시험을 해봤는데 예를 들어 리스트 안에 같은 뜻의 한글과 영어가 있다고 치면 comment:한국어 는 되도 comment:Korean은 검색되지 않고 comment:백합은 되도 comment:Yuri 는 되지 않는 등 영어 코멘트는 인식을 못하는지 검색되지가 않습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by chbk256** [comment]
매우 잘 됩니다. 감사합니다.

**Comment by tdi2020** [comment]
헉 현재 yandex 검색결과를 다운받을 수 있는건가요?

**Comment by chbk256** [comment]
아뇨. 코멘트 문제만 수정해주신겁니다. ㅎㅎ얀덱스 언젠가 지원되기를 바래봅니다. '

**Comment by tdi2020** [comment]
그러게요 얀덱스가 근데 만약 된다면 ... 검색 결과 전체를 다운받을 시 용량이 엄청나지 않을까요? 가능한 것일까요ㄷㄷ

**Comment by chbk256** [comment]
어차피 픽시브도 페이지 제한 등으로 제한을 두시는터라 프로그램 허용 범위 내에선 가능하도록 하시지 않나 싶습니다. 근데 제작자분에게 도움 좀 드리려고 얀덱스나 구글 관련 이미지 다운로더는 찾아보니 안 보이더군요. 뭔가 구현에 한계가 있을수도 있고, 혹 가능하더라도 제작자분이 내키실때 추가하시는거라 일단 안 된다는 생각으로 내려놓는게 편할 것 같습니다.
