### ISSUE TITLE
1월 10일 이후로 추가된 작품들의 섬네일이 뜨지 않습니다.

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#1558]
Sensible tid reading emit against misc europe rised
한국어 검색 기준으로 위 작품부터 안뜨네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hp784951623** [comment]
잘되요 감사합니다

**Comment by psy6809** [comment]
늘 감사히 사용합니다 빠른 피드백 감사합니다!

**Comment by audemar5435** [comment]
v30가 바이러스? 위험한 프로그램? 으로 감지하는데 괜찮은건가요?
그 전에 쓰던 것은 괜찮았는데 저도 섬네일이 안보여서 다운받았는데 그런창이 떠서...

**Comment by KurtBestor** [comment]
@audemar5435 오진이에요. 시간 되시면 해당 백신에 오진이라고 리포트 부탁드려요.
