### ISSUE TITLE
어저께 썸네일 문제로 새로 다운받고 난 후의 겪는 증상입니다.

### ISSUE THREAD

**Issue by whgmlqja12** [KurtBestor/Hitomi-Downloader#1560]
썸네일 안보이는걸 테스트 버전 받아서 했고 잘 했는데 이게 저만 해당되는건지는 모르겠지만 히토미를 끄고 다시 키면 다운파일 경로가 초기화가 되버리네요. 

다른 세팅옵션이나 엔헨타이 경로설정은 아무이상이 없는데

히토미 다운경로가 무조건 바탕화면으로 초기화 되버립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by whgmlqja12** [comment]
잘 되네요. 감사합니다
