### ISSUE TITLE
검색 시 이미지가 나오지 않습니다.

### ISSUE THREAD

**Issue by stvking72** [KurtBestor/Hitomi-Downloader#1562]
1월 10일인가 이쯤 부터 검색하는 파일의 이미지가 나오질 않습니다.
근 전 파일들은 이미지가 나옵니다.
![이미지오류](https://user-images.githubusercontent.com/59783254/72213314-1c6f9b00-3530-11ea-84a5-92110c995e79.png)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1558
