### ISSUE TITLE
픽시브 다운로드에 문제가 생겼습니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1564]
Can not determine type: https://www.pixiv.net / users / 8189060

라고 뜨고

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/users/8189060

가 전부입니다.

한두개가 아니라 여러 픽시브에서 그러네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1550
