### ISSUE TITLE
사용법 등 건의

### ISSUE THREAD

**Issue by lardmaker** [KurtBestor/Hitomi-Downloader#1565]
안녕하세요, 프로그램 잘 쓰고 있습니다.

사용법 문서를 통해 이 프로그램이 어떤 사이트를 지원하는지, 그리고 저장 폴더명 형식에서 쓸 수 있는 매크로가 어떤 게 있는지 알 수 있었으면 합니다. artist나 title 같은 거 외에도 어떤 게 더 있는지... 그리고 e-hentai 등지에 달려있는 일본어 원제의 경우 그것도 경로명에 포함시킬 수 있는 매크로가 있는지, 없다면 그 부분을 추가해 보시는 것은 어떤지 여쭙고 싶습니다.

**Comment by KurtBestor** [comment]
참고해주세요:
- https://github.com/KurtBestor/Hitomi-Downloader-issues#supported-sites
- https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1059
- https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/855
