### ISSUE TITLE
기본데이터 다운로드가 안됩니다

### ISSUE THREAD

**Issue by beacry** [KurtBestor/Hitomi-Downloader#1567]
기본데이터 다운로드 해서 쓰려고 하면
예상치 못한 오류로 다운로드에 실패했습니다.
라고 뜹니다

**Comment by KurtBestor** [comment]
<kbd>자세한 정보 보기...</kbd> 눌러서 나온 내용 보여주세요.

**Comment by beacry** [comment]
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 2278, in dataDownload
  File "hitomi_searcher", line 312, in download_json
ValueError: Could not reserve memory block

**Comment by KurtBestor** [comment]
`hitomi_data` 폴더 지우고 다시 시도해보세요.

**Comment by beacry** [comment]
위 오류 그대로 나오면서 안됩니다...ㅠ

**Comment by beacry** [comment]
해결 방법 없는건가요..?

**Comment by KurtBestor** [comment]
`hitomi_data` 폴더에 있는 파일들 보내주시면 분석해볼게요.

**Comment by beacry** [comment]
이메일 주소좀 부탁드립니다..
아니면 어디에 써있는데 제가 못찾는걸까요?

**Comment by KurtBestor** [comment]
mangrovn@gmail.com 으로 보내주세요.

**Comment by beacry** [comment]
보냈습니다아아아...

**Comment by KurtBestor** [comment]
프로그램이 메모리 얼마나 쓰나요?

**Comment by beacry** [comment]
722.7mb 쓰네요

**Comment by KurtBestor** [comment]
다른 경로에 프로그램 새로 다운로드해서 시도하면 어떻게 되나요?

**Comment by beacry** [comment]
다른 경로에 다운받아서 해보니 정상 작동이 됩니다..
대체 원인이 뭐인걸까요..?

**Comment by KurtBestor** [comment]
원래 경로가 어떻게 되나요?

**Comment by beacry** [comment]
원래 경로는 E:\Downloads\hitomi_downloader_GUI 고
새로 만든건 D:\Download\hitomi_downloader_GUI 입니다
