### ISSUE TITLE
다운로드 오류 처리 문의 

### ISSUE THREAD

**Issue by korhentai** [KurtBestor/Hitomi-Downloader#1570]
안녕하세요 

마나모아가 다시 정상적으로 받아지고있습니다만... 궁금한점이있어서 글남깁니다. 

1 파일이 중간까지만 받아지고 깨짐
2 파일이 생성되나 용량이 0
3 파일이 아예생성되지 않음

3종류의 경우가 있는데요 

1번과 3 번은 정상적인 완료로 표기가 되네요 ?
2 번만 불완전 다운로드로 인식이되는게 맞나요 ? 

찾는게 더 어려워 졌습니다 ㅠ

**Comment by KurtBestor** [comment]
1, 2, 3 번 모두 오류로 처리돼요. 다만 화 파일 일부만 오류면 `다시 시작` 했을 때 해당 화는 모두 받아진 걸로 인식돼요.
