### ISSUE TITLE
웹 스토어의 이미지 다운로더 앱들

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1575]
https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

위의 이미지 다운로더의 경우 직접 이미지의 프리뷰가 있는 사이트에 들어가야 하지만

고해상도의 원본 링크의 이미지들을 받을 수 있는데  부루 시리즈나 팬박스, 개인 사이트 등 

많은 사이트에서 쓸 수 있더군요.

그리고

https://download-manager.online/welcome    다운로더 소개

https://chrome.google.com/webstore/detail/online-download-manager/opjjpmhoiojifppkkcdabiobhakljdgm

위의 다운로더 매니저는 원본 링크 연결은 안 되는 것 같지만 구글이나 얀덱스 등의

거대 이미지 검색 사이트에서 프리뷰 이미지들을 싹 받는데 도움되는 것 같고요.

혹 참고가 될 수 있다면 다운로더 기능 보완에 도움되실까 싶어서 말씀드려봅니다.

**Comment by KurtBestor** [comment]
브라우저 확장 프로그램은 이미 브라우저에서 리퀘스트 된 리소스 중에 찾는 방식이라 이 프로그램과는 좀 달라요.
