### ISSUE TITLE
싸이트 스크립트 업데이트 요청입니다

### ISSUE THREAD

**Issue by hokess5** [KurtBestor/Hitomi-Downloader#1576]
https://toonkor.bar/

기존에 등록되어있던 툰코 싸이트 스크립트가 작동이 되지않아 업데이트 요청을 부탁드립니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by hokess5** [comment]
> 
> 
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

1월 13일자로 업데이트된 히토미 다운로더 프로그램 최신버젼을 쓰니 해결되었습니다
