### ISSUE TITLE
마나모아 관련...

### ISSUE THREAD

**Issue by kimch0612** [KurtBestor/Hitomi-Downloader#1577]
안녕하세요 개발자님
항상 크롤링 하는 용도로 프로그램을 잘 사용하고 있습니다 감사합니다
한가지 건의 드릴 것이 있어서 글을 씁니다
이미지가 깨지거나 누락된 파일이 있는 만화라면 프로그램에서 오류를 내며 노란색 표시가 뜨잖습니까?
저는 만화를 pdf로 묶는 기능을 이용해서 뷰어로 보고 있는데, 위와 같은 상황에선 pdf로 묶는 기능이 실행되지 않더라고요
그래서 항상 에러 코드를 보면서 누락된 이미지가 있는 화를 수동으로 체크를 해재해서 다운로드를 받고 있는데, 이 작업을 프로그램에서 자동으로 해주면 어떨까 라는 생각이 들었고
또, 위의 방법으론 누락된 이미지가 있는 화는 pdf 생성 자체가 되지 않는게 좀 불편하더라고요
누락된 이미지가 있는건 자동으로 pdf 생성을 스킵하거나, 해당 이미지를 포함하지 않고 pdf를 만드는 방식으로 기능이 추가되면 좋지 않을까 싶어서 글을 쓰게 됐습니다

**Comment by KurtBestor** [comment]
일부 이미지만 깨진 화는 해당 이미지 지우고 `다시 시작` 하면 PDF 만들어요.
