### ISSUE TITLE
픽시브 움짤변환이 안됩니다

### ISSUE THREAD

**Issue by deain09** [KurtBestor/Hitomi-Downloader#1578]
최신버전으로 새로설치해도 안되내요
다른건 다 잘되고 움짤변환만 안되고 압축파일만 생성됩니다 기본설정에서 만진것은 따로 없습니다.

**Comment by deain09** [comment]
재설치 3번하니까 성공...

**Comment by KurtBestor** [comment]
`움짤 변환...` 이라고 뜨면 좀 기다려야해요.
