### ISSUE TITLE
트위치 다시보기를 받을 때 저작권 때문에 소리가 안 나오는 구간은 다운이 안됩니다.

### ISSUE THREAD

**Issue by rarubaka** [KurtBestor/Hitomi-Downloader#1585]
트위치 다시보기를 다운받을 때
밑 사진처럼 저작권 때문에 소리가 안 나오는 구간은 잘려서 다운됩니다.
예를 들어 받으려는 영상 시간이 총 5시간이고, 저작권 구간이 30분이면
다운받은 영상의 총 길이는 4시간 30분이 나옵니다.
그리고 받은 영상을 재생해보면 저작권 구간은 스킵됩니다.

예를 들어 원 영상의 4시간 20분부터 30분까지가 저작권 구간이면 
다운받은 영상의 04:19:59 부분에서 원 영상의 20~30분에 해당하는 분량은
다운이 되질 않았으니 스킵되고
04:20:00 부터 원 영상의 4시간 31분부터 나오는 영상이 재생됩니다.

![bandicam 2020-01-19 04-53-50-384](https://user-images.githubusercontent.com/56993081/72669630-b62ad100-3a77-11ea-9273-446b80b9edaa.jpg)

저작권 무음 구간은 받을 수 없는건가요?
또는 무음 구간을 소리가 나게끔, 
저작권 구간 없이 원래 영상 그대로 받을 수는 없을까요?

**Comment by rarubaka** [comment]
(One For All, All For One )

version: 2.7e
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.twitch.tv/videos/518247571?filter=archives&sort=time
dir: E:\hitomi_downloaded_twitch
zip: 
type: twitch
artist: None
url: https://www.twitch.tv/videos/518247571?filter=archives&sort=time
valid: True
done: False
range: None
range_p: None
single: True
time: 1579377035.2 (Jan 19)
tags: []
goodbyedpi: False
lock: False
color: downloading
paused: False


[Gallery]
None


[File Names]
[0001] E:\hitomi_downloaded_twitch\(One For All, All For One ).mp4


[URLs]
[0001] LazyUrl(https://www.twitch.tv/videos/518247571?filter=archives&sort=time) ---> M3u8_stream(https://vod-secure.twitch.tv/ae6f0345d78fbf59db8a_aram4519_36368178048_1341722578/chunked/index-muted-D442YZH9M7.m3u8)


[Messages]

Fail : None
Traceback (most recent call last):
File "downloader", line 821, in download
File "downloader", line 815, in Stream
File "socket", line 284, in read
File "httplib", line 597, in read
File "socket", line 284, in read
File "ssl", line 754, in recv
File "ssl", line 641, in read
error: [Errno 10054]

**Comment by KurtBestor** [comment]
테스트 해봤는데 잘 되네요. 혹시 예전 버전으로 다운로드 한 거면 최신버전으로 다시 다운로드 해주세요.

**Comment by rarubaka** [comment]
다시 받아보니 저작권 무음처리 구간도 받아져서
다운받은 영상 재생시간이 원 영상 재생시간이랑 똑같긴 한데
다운받은 영상에서는 원 영상의 저작권 무음 구간에서 소리가 안 나는데..
이건 어쩔 수 없는건가요?

**Comment by KurtBestor** [comment]
네, 원본 파일에서 소리가 안 나네요.

**Comment by rarubaka** [comment]
아.. 어쩔 수 없는거군요..
항상 감사한 마음으로 잘 쓰고 있습니다.
답변 감사합니다.

**Comment by KurtBestor** [comment]
파일 이름으로 유추하면 찾을 순 있네요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
