### ISSUE TITLE
중복 이미지 찾기 관련 궁금증이 있습니다.

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#1588]
알고 계실진 모르겟지만 .. 제가 중복이미지 찾기 할때 

이미지수 약 216만장에 28시간 걸려서 문득 든 생각인데요.

이 중복 이미지 찾을때 사용되는 부품이 무엇인가요 ?

CPU,GPU,RAM,아니면 하드인가 SSD인가 이런것도 관련이 있는지 궁금합니다.

부품을 교채한다면 28시간이라는 시간을 줄일 수 있을까요 ...?

아 그리고 시간이 시간이다보니깐 중간에 중복난 이미지들 삭제하는데 

가끔가다가 프로그램이 꼬이는지.. 중복 이미지 찾는중 이라고뜨는데

밑의 숫자가 안 움직일 때가 있습니다. 

이건 너무 양이 많아서 일까요 ...?

중복이미지 찾는 도중 메모리 사용량은 약 750MB~ 850MB 사이정도 뜹니다.

**Comment by KurtBestor** [comment]
대체로 CPU, 해당 드라이브 HDD(SSD) 가 성능에 영향을 미쳐요.

**Comment by kenasis428** [comment]
오.. 그렇군요 .. 감사합니다 .
