### ISSUE TITLE
사이트 스크립트 업데이트 요청입니다

### ISSUE THREAD

**Issue by hokess5** [KurtBestor/Hitomi-Downloader#1590]
싸이트 주소

https://toonkor.lat

툰코 싸이트 스크립트가 동작하지않아 문의드려봅니다

싸이트는 정상접속되는것으로 확인되었습니다

다운로더는 최신버젼으로 동작하였으며

저번에 문의드렸을땐 최신버젼으로 동작하였을시 작동하였으나

이번엔 아예 동작하지않아 스크립트 수정이 필요하다고 생각되어 문의남겨봅니다

스크립트 업데이트 부탁드립니다

상세오류정보 첨부하겠습니다

----------------------------------------------

목록 주소를 입력해주세요: https://toonkor.lat / %EC%83%81%EC%A4%91%ED%95%98

version: 2.7e
platform: Windows-7-6.1.7601-SP1
order: 3
group: False
gal_num: https://toonkor.lat/%EC%83%81%EC%A4%91%ED%95%98
dir: 
zip: 
type: toonkor
artist: None
url: https://toonkor.lat/%EC%83%81%EC%A4%91%ED%95%98
valid: False
done: True
range: None
range_p: None
single: False
time: 1579593439.21 (Jan 21)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://toonkor.lat/%EC%83%81%EC%A4%91%ED%95%98

stop
Invalid: fail=False
stop
EOT: https://toonkor.lat/%EC%83%81%EC%A4%91%ED%95%98

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회` 를 키세요.

**Comment by hokess5** [comment]
> 
> 
> `옵션` - `설정` - `고급 설정` - `DPI 우회` 를 키세요.

해결이 되었습니다 감사합니다
