### ISSUE TITLE
픽시브가 3700페이지 이상 다운이 안됩니다.

### ISSUE THREAD

**Issue by aabbccmart** [KurtBestor/Hitomi-Downloader#1591]
안녕하세요.

픽시브 북마크 해놓은걸 모두다 한번에 다운받으려고 다운로드를 실시했더니 2000개에서 끊겼습니다.

#382 (comment) 를 참고해, ~ 10000개 까지 늘려봤더니, 3674에서 무한로딩이 걸리더라구요.

그래서 정확하게 끊어봤더니 3730장 (페이지) 까지 다운로드가 작동해서,

이번에는 범위를 3731~ 10000으로 해봤더니

처음부터 올라가더니 역시 3674에서 멈춰버립니다.

ctrl + ALT + C 누르고 TOO_MANY = 9999 까지 입력해봤는데 해결되지않았습니다. 
(상관없는 해결법이었나봐요 ㅎㅎ ㅠ)

어떻게하면 뒤에 자료까지 한번에 다 다운받을 수 있을까요?

도와주세요! 감사합니다.

**Comment by Sn0w0wl** [comment]
사용법에 "메모리 관련 문제로 1000개 이상은 권장하지 않아요"
라 써있어요. ;;

**Comment by aabbccmart** [comment]
사용법은 물론 정독했고 1000개 이상 권장하지 않는다는 내용도 잘 알고있습니다.

그렇다면, 따로따로 받는 방법은 없는건가요?

픽시브에 약 1만장 이상의 북마크(좋아요) 사진이 있는데, 다운받을수가 없어요.

한번에 1만개까지 지정하는건 위에 썻듯이 안되는방법이라..

1 ~ 3000 까지 한번 받고, 그다음 3001~ 6000 이런방식으로 하면, 작동이 안된다는 말이에요.

3674에서 멈춰버려용.

10 단위로 쪼개서해봐도, 3720 ~ 3730 설정값이 최대였어요.

3731 ~3740로 설정하면, 앞에서말한대로 1부터 쭉 올라가더니 3674에서 멈춰버리고 무한로딩에 걸려요.

페이지를 받은 것 이후부터 설정해도, 1번부터 차례대로 훑어가기때문에 
뒤에 사진을 받을수가 없어요...

어떻게 방법이 없을까요?

**Comment by KurtBestor** [comment]
북마크 주소 알려주세요.
