### ISSUE TITLE
사진 빼먹은게 있어서, 같은곳에서 다시 다운하려는데 안되요

### ISSUE THREAD

**Issue by Sn0w0wl** [KurtBestor/Hitomi-Downloader#1593]
(같은곳에서) 못받은 사진 있어서, 원하는 사진 페이지 쓰고
다운하는데 안받아집니다.     (파일명이 겹쳐서 그런것 같아서요.)      *히토미.

세부:
1, 2, 3 ~ 5, 10  다운로드 ->    (*페이지 번호.  (총 6장)
잘 받아짐--

1 ~ 10  다운로드 ->
7,8,9,10 만 받아짐    (앞에서 6개가 다운안됨 + 중복사진 (10번사진) 이 다운됨)

그래서 건의(?)인데요
사진을 다운받을 때, 사진 이름을 '페이지 번호' 로 하면    ( 1, 4 ~ 7   ->      사진이름이 각각 1,  4,  7  )
어때요?

그럼 겹치지 않고, 다운 안되는것도 막고..

(쓰다가 문득..)
그런데, 설정 > 히토미 에서,  파일명 형식이  원본 / 숫자  인데,
(파일명 생기는게) 둘 다 똑같던데, 버그인가요?    (원본: 01  02  03..~   /  숫자: 0001   0002 ...~   )
                                  (페이지 번호 상관없이, 다운받은 사진 순으로 1,2,3~~)

 "원본"이, 위에서 말한  "페이지 번호" 로 하는건데
잘못되서 똑같이 숫자로 적용됬다거나..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1548
