### ISSUE TITLE
산카쿠에서 2000장 이상 다운로드 하려는데 어려움을 겪고있습니다

### ISSUE THREAD

**Issue by supermekadeathstalin** [KurtBestor/Hitomi-Downloader#1594]
총 3080장이라서 페이지 지정 다운로드로  - 1080해봤더니 읽는중 상태에서 빨간불 들어옵니다
2000 ~ 3080 했더니 딱 한장 다운로드 되고 끝났습니다.
~ 3080 했더니 기존에 다운로드한 2000장 되새김질 하고 끝나버렸습니다. 
설정을 도대체 어떻게 해야하는걸까요?

**Comment by KurtBestor** [comment]
참고해주세요: #1185

**Comment by supermekadeathstalin** [comment]
이런 원숭이가 개발한 사이트 같으니
