### ISSUE TITLE
픽시브 이미지 전체 저장

### ISSUE THREAD

**Issue by kofinandaing** [KurtBestor/Hitomi-Downloader#1596]
그 전 버전에서는 픽시브 https://www.pixiv.net/users/000000/artworks 이런 거 만 넣어도 전체 저장이 되었었는데 지금은 안돼나요? Can not determind type 뭐시기 뜨네요 전체 저장 하고싶은데...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1550
