### ISSUE TITLE
픽시브 관련질문인데 혹시 기능중에

### ISSUE THREAD

**Issue by hifatia** [KurtBestor/Hitomi-Downloader#1597]
등록된 팔로우 전체 일괄다운로드 기능은 없는걸로 아는데

그럼 이전에 일일이 받아서 저장했던 팔로우 폴더들을 읽어 들여서

갱신하는 기능은 있나요? 그 다운로드 목록 같은거라든가...말이죠

늘 감사히 잘 쓰고있습니다 좋은 설 보내시고 좋은 한해 되세요

**Comment by KurtBestor** [comment]
목록에 추가되어있다면 `마우스 우 클릭` - `다시 시작` 하시면 돼요.

**Comment by hifatia** [comment]
> 목록에 추가되어있다면 `마우스 우 클릭` - `다시 시작` 하시면 돼요.

그...워낙 목록이 많아서 저는 다운 다되면 목록 자동삭제 기능을 사용중이라 목록은 없는데 다운로드된 폴더에서 읽어오는 기능은 없는거죠?

**Comment by hifatia** [comment]
> 목록에 추가되어있다면 `마우스 우 클릭` - `다시 시작` 하시면 돼요.

하나만 더 문의드리고싶은게있는데 중복이미지 찾기 기능 써봣는데 찾아봐도 찾아낸 중복 파일 삭제하는 법을 잘 모르겠더라구요 이 기능도 원래 없는건가요? 아니면 기능을 쓰는법이 따로있나요?

**Comment by KurtBestor** [comment]
- 폴더 복사해서 주소창에 붙여넣으면 추가돼요.
- 지우고 싶은 파일 선택해서 <kbd>Delete</kbd> 누르면 지워져요.
