### ISSUE TITLE
이미지 안보이는버그

### ISSUE THREAD

**Issue by fdaga** [KurtBestor/Hitomi-Downloader#1598]
![1](https://user-images.githubusercontent.com/46779614/73050867-91de5280-3ec4-11ea-93bc-b0c1b8636801.PNG)

최근작품들이 이렇게 저장 종료 하고 다시켜보면 이렇게 계속안보이네요

**Comment by KurtBestor** [comment]
해당 INI 파일 보내주시면 분석해볼게요.

**Comment by fdaga** [comment]
이메일로 보내면될까요?

**Comment by KurtBestor** [comment]
넵

**Comment by fdaga** [comment]
이메일좀알려주실수있을까요?

**Comment by KurtBestor** [comment]
mangrovn@gmail.com

**Comment by fdaga** [comment]
보냈습니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/73123308-ff2bd980-3fd1-11ea-907d-3a62bbd2c0fd.png)

<kbd>Ctrl</kbd> + <kbd>L</kbd> 누르면 로그 뜨는데, 메모리가 부족해서 못 불러오네요. 

가로로 긴 썸네일들이 많아서 2000개가 되기 전에 메모리를 초과한 것 같아요.

**Comment by fdaga** [comment]
그럼 어떻게 해야 해결할수있나요?

**Comment by KurtBestor** [comment]
이미 날아간 건 어쩔 수 없고, 작업 목록이 많으면 HDT 파일로 저장해서 백업해주세요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1061#issuecomment-517935813

**Comment by fdaga** [comment]
빠른답변과 좋은답변 감사드립니다.
