### ISSUE TITLE
파이썬 공부하는 중인데 간단한 질문해도 될까요?

### ISSUE THREAD

**Issue by Lunartist** [KurtBestor/Hitomi-Downloader#1600]
마나모아같이 퍼즐로 쪼개서 캔버스로 쏘는 이미지 같은건 어떻게 다운로드 받으시는건가요?

렌더링이 끝난 이후의 캔버스를 받는 방법이 있나요?

정말 신기하고 대단하십니다!

**Comment by KurtBestor** [comment]
헤드리스 브라우저로 캔버스 이미지를 다운로드해요.
