### ISSUE TITLE
제이마나 다운로드가 안되요 

### ISSUE THREAD

**Issue by 1818181881** [KurtBestor/Hitomi-Downloader#1602]
https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8# 
몇달만에 ㅈ이마나 들어가서 다운로드 할려고 했더니 안되요 
![캡처](https://user-images.githubusercontent.com/60257088/73063180-8cdbcc00-3ee1-11ea-9f4e-2e066508e5d7.PNG)

제가 잘못 다운하는건지 제이마나 에서 다운이 안되네여 ㅠㅠ

**Comment by cancerogenic** [comment]
오른쪽클릭에서 정보 누르셔서 내용을 올려주세요

**Comment by 1818181881** [comment]
Invalid: [jmana] https://jmana2.net / book / %EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
dir: 
zip: 
type: jmana
artist: None
url: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8
valid: False
done: True
range: None
range_p: None
single: False
time: 1579916189.85 (Jan 25)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana2.net/book/%EB%A7%9B%EC%9D%98%EB%8B%AC%EC%9D%B8

빠른 답변 감사합니다
정보 란게 이게 맞나요??

**Comment by KurtBestor** [comment]
지금도 안 되나요?
