### ISSUE TITLE
유튜브 특정 영상들이 안받아집니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader#1604]
이번엔 유튜브에서 ip차단먹은것도 아니고 국가에서 차단되거나 프리미엄 동영상도 아닌데 안받아지네요
나머지는 잘 받아집니다

https://www.youtube.com/watch?v=rgb1r9-K3l8
해당 영상 주소고 몇번 재시도하고 껏다켜도 안받아지네요
확인부탁드려요

**Comment by superrogin** [comment]
저도 비슷한 증상으로 방금 #1605  글을 남겼는데 작업정보를 같이 포함해서 올렸으니 참고하시면 좋을 것 같습니다.

**Comment by lducjswo** [comment]
이게 해결하는데 도움이 되실지 모르겠는데 안받아지는 영상들의 공통점을 알아냈는데
하나같이 음악관련 컨텐츠(악기를 연주하든 노래를 부르든 remix를 하든 관련 모든 컨텐츠)에 한해서 전부 안받아집니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lducjswo** [comment]
정상적으로 잘 받아집니다
감사합니다
