### ISSUE TITLE
pornhub에서 플레이 리스트를 다운 할 순 없나요?

### ISSUE THREAD

**Issue by saleook** [KurtBestor/Hitomi-Downloader#1610]
pronhub에서 특정유저의 플레이리스트에 있는동영상을 모두 다운받는 방법은 없나요?

**Comment by tdi2020** [comment]
현재 유저나 채널에서 직접 업로드한 영상만 다운이 받아지구 Favorit 항목처럼 스크랩해둔 목록의 경우에는 다운이 불가능하다고 하신것 같아요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
