### ISSUE TITLE
DPI우회 설정이 안됩니다.

### ISSUE THREAD

**Issue by koozin741** [KurtBestor/Hitomi-Downloader#1611]
DPI우회설정이 안되서 검색시 미리보기 그림이 열리지 않습니다. 
우회설정을 눌러도 계속 되돌아가네요
![제목 없음](https://user-images.githubusercontent.com/60314547/73134145-7d41bc00-4076-11ea-85c3-0d401b8af4d1.jpg)

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by koozin741** [comment]
> 어떤 백신 쓰시나요?

v3 씁니다

**Comment by KurtBestor** [comment]
[이건](https://github.com/ValdikSS/GoodbyeDPI) 실행 되나요?
