### ISSUE TITLE
니코동은 일러스트 다운이 안 되는가요?

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1614]
아래와 같이 에러가 뜨는데 혹시 일러스트는 다운이 안 되는건가요?

혹 안 된다면 일러스트 다운 기능 추가 한번 건의드려봅니다!

Invalid: [nico] https://seiga.nicovideo.jp / user / illust / 49209023

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://seiga.nicovideo.jp/user/illust/49209023
dir: 
zip: 
type: nico
artist: None
url: https://seiga.nicovideo.jp/user/illust/49209023
valid: False
done: True
range: None
range_p: None
single: True
time: 1580126251.4 (Jan 27)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
nico retry...
nico retry...
404 Client Error: Not Found for url: https://www.nicovideo.jp/watch/https:/seiga.nicovideo.jp/user/illust/49209023
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "nico_downloader4", line 75, in read
File "nico_downloader4", line 95, in get_video
File "nndownload", line 365, in request_video
File "requests\models", line 939, in raise_for_status
HTTPError: 404 Client Error: Not Found for url: https://www.nicovideo.jp/watch/https:/seiga.nicovideo.jp/user/illust/49209023

Invalid: fail=True
EOT: https://seiga.nicovideo.jp/user/illust/49209023

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/287
