### ISSUE TITLE
대기열 리스트가 많을 수록 크래시가 잦아집니다.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader#1615]
항상 잘 사용하고 있습니다.
히토미 다운로더 메인 창을, 파일 리스트 겸용으로써 대기열을 삭제하지 않고 사용중입니다.
현재의 대기열이 약 1150개로 되어 있습니다만,
시작시에 느린 점은 이해가 가능하나
대기열 수가 늘어날수록 자잘한 렉이 증가하고
조금만 로드가 걸리면 이유 없이 꺼지는 상황이 잦아집니다.

종료시마다 기록되는 크래시 덤프 파일을 첨부합니다. 확인 부탁드립니다.

https://drive.google.com/open?id=1-rAvMFHrfIEGJTdkgO_urdZUUPkl1b9Z

**Comment by KurtBestor** [comment]
화면 DPI 가 어떻게 되나요?

**Comment by miraclehoshi** [comment]
2560*1440, 27인치, 윈도우즈 내 설정에서 100% 입니다.

**Comment by KurtBestor** [comment]
메모리 사용량이 얼마나 되나요?

**Comment by miraclehoshi** [comment]
환경은 라이젠 2700X에 램32GB 입니다.
초기 로드시 cpu 8%대, 메모리 400~800MB

로드 완료 후 idle 상태에서 메모리 462.3MB, cpu 0~0.1% 사용합니다.
