### ISSUE TITLE
pornhub 다운로드 에러

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1616]
다운로드 시도한 주소 : https://www.pornhub.com/pornstar/leolulu

출력 메세지는 아래와 같습니다.

-----------------------------------------------------------------------
Invalid: [pornhub] https://www.pornhub.com / pornstar / leolulu

version: 2.7h
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://www.pornhub.com/pornstar/leolulu
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/pornstar/leolulu
valid: False
done: True
range: None
range_p: None
single: True
time: 1580197577.53 (Jan 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
videos
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 385, in get_videos
UnboundLocalError: local variable 'session' referenced before assignment

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "pornhub_downloader", line 130, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 385, in get_videos
UnboundLocalError: local variable 'session' referenced before assignment

Invalid: fail=True
EOT: https://www.pornhub.com/pornstar/leolulu

**Comment by tdi2020** [comment]
아래도 동일한 증상입니다. 
다른 다수의  /channels 는 잘 되길래 /pornstar 요녀석만 문제인줄 알았는데 
요건 /channels 인데도 아래와 같이 출력되네요.

https://www.pornhub.com/channels/extremeteens

-------------------------------------------------------

Invalid: [pornhub] https://www.pornhub.com / channels / extremeteens

version: 2.7h
platform: Windows-10-10.0.17134
order: 0
group: False
gal_num: https://www.pornhub.com/channels/extremeteens
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/channels/extremeteens
valid: False
done: True
range: None
range_p: None
single: True
time: 1580214409.01 (Jan 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
videos
https://www.pornhub.com/channels/extremeteens/videos?page=1 (0)
https://www.pornhub.com/channels/extremeteens/videos?page=2 (36)
https://www.pornhub.com/channels/extremeteens/videos?page=3 (72)
https://www.pornhub.com/channels/extremeteens/videos?page=1 (0)
https://www.pornhub.com/channels/extremeteens/videos?page=2 (36)
https://www.pornhub.com/channels/extremeteens/videos?page=3 (72)
https://www.pornhub.com/channels/extremeteens/videos?page=1 (0)
https://www.pornhub.com/channels/extremeteens/videos?page=2 (36)
https://www.pornhub.com/channels/extremeteens/videos?page=3 (72)
https://www.pornhub.com/channels/extremeteens/videos?page=1 (0)
https://www.pornhub.com/channels/extremeteens/videos?page=2 (36)
https://www.pornhub.com/channels/extremeteens/videos?page=3 (72)
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 428, in get_videos
File "downloader", line 356, in read_html
Exception: 404

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "pornhub_downloader", line 130, in read
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "pornhub_downloader", line 428, in get_videos
File "downloader", line 356, in read_html
Exception: 404


Invalid: fail=True
EOT: https://www.pornhub.com/channels/extremeteens

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
잘 작동했어요 선생님! 감사합니다!
