### ISSUE TITLE
마나모아 다운이 멈춰요

### ISSUE THREAD

**Issue by newstarssu** [KurtBestor/Hitomi-Downloader#1618]
Invalid: [manamoa] https://manamoa26.net / bbs / page.php?hid=manga_detail&manga_id=463

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=463
dir: 
zip: 
type: manamoa
artist: 고토게 코요하루
url: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=463
valid: False
done: True
range: None
range_p: None
single: False
time: 1580313221.11 (Jan 30)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist][lang] title
[seed] 귀멸의 칼날 1화 0
[seed] 귀멸의 칼날 2화 0
[seed] 귀멸의 칼날 3화 0
[seed] 귀멸의 칼날 4화 0
[seed] 귀멸의 칼날 5화 0
[seed] 귀멸의 칼날 6화 0
[seed] 귀멸의 칼날 7화 0
[seed] 귀멸의 칼날 8화 0
[seed] 귀멸의 칼날 9화 0
[seed] 귀멸의 칼날 10화 0
[seed] 귀멸의 칼날 11화 0
[seed] 귀멸의 칼날 12화 0
[seed] 귀멸의 칼날 13화 0
[seed] 귀멸의 칼날 14화 0
[seed] 귀멸의 칼날 15화 0
[seed] 귀멸의 칼날 16화 0
[seed] 귀멸의 칼날 17화 0
[seed] 귀멸의 칼날 18화 0
[seed] 귀멸의 칼날 19화 0
[seed] 귀멸의 칼날 20화 0
[seed] 귀멸의 칼날 21화 0
[seed] 귀멸의 칼날 22화 0
[seed] 귀멸의 칼날 23화+번외 0
[seed] 귀멸의 칼날 24화 0
[seed] 귀멸의 칼날 25화 0
[seed] 귀멸의 칼날 26화 0
[seed] 귀멸의 칼날 27화 0
[seed] 귀멸의 칼날 28화 0
[seed] 귀멸의 칼날 29화 0
[seed] 귀멸의 칼날 30화 0
[seed] 귀멸의 칼날 31화 0
[seed] 귀멸의 칼날 32화 0
[seed] 귀멸의 칼날 33화 0
[seed] 귀멸의 칼날 34화 0
[seed] 귀멸의 칼날 35화 0
[seed] 귀멸의 칼날 36화 0
[seed] 귀멸의 칼날 37화 0
[seed] 귀멸의 칼날 38화 0
[seed] 귀멸의 칼날 39화 0
[seed] 귀멸의 칼날 40화 0
[seed] 귀멸의 칼날 41화 0
[seed] 귀멸의 칼날 42화 0
[seed] 귀멸의 칼날 43화 0
[seed] 귀멸의 칼날 44화 0
[seed] 귀멸의 칼날 45화 0
[seed] 귀멸의 칼날 46화 0
[seed] 귀멸의 칼날 47화 0
[seed] 귀멸의 칼날 48화 0
[seed] 귀멸의 칼날 49화 0
[seed] 귀멸의 칼날 50화 0
[seed] 귀멸의 칼날 51화 0
[seed] 귀멸의 칼날 52화 0
[seed] 귀멸의 칼날 53화 0
[seed] 귀멸의 칼날 54화 0
[seed] 귀멸의 칼날 55화 0
[seed] 귀멸의 칼날 56화 0
[seed] 귀멸의 칼날 57화 0
[seed] 귀멸의 칼날 58화 0
[seed] 귀멸의 칼날 59화 0
[seed] 귀멸의 칼날 번외편 0
[seed] 귀멸의 칼날 60화 0
[seed] 귀멸의 칼날 61화 0
[seed] 귀멸의 칼날 62화 0
[seed] 귀멸의 칼날 63화 0
[seed] 귀멸의 칼날 64화 0
[seed] 귀멸의 칼날 65화 0
[seed] 귀멸의 칼날 66화 0
[seed] 귀멸의 칼날 67화 0
[seed] 귀멸의 칼날 68화 0
[seed] 귀멸의 칼날 69화 0
[seed] 귀멸의 칼날 70화 0
[seed] 귀멸의 칼날 71화 0
[seed] 귀멸의 칼날 72화 0
[seed] 귀멸의 칼날 번외편3화 0
[seed] 귀멸의 칼날 73화 0
[seed] 귀멸의 칼날 74화 0
[seed] 귀멸의 칼날 75화 0
[seed] 귀멸의 칼날 76화 0
[seed] 귀멸의 칼날 77화 0
[seed] 귀멸의 칼날 78화 0
[seed] 귀멸의 칼날 79화 0
[seed] 귀멸의 칼날 80화 0
[seed] 귀멸의 칼날 81화 0
[seed] 귀멸의 칼날 82화 0
[seed] 귀멸의 칼날 83화 0
[seed] 귀멸의 칼날 84화 0
[seed] 귀멸의 칼날 85화 0
[seed] 귀멸의 칼날 86화 0
[seed] 귀멸의 칼날 87화 0
[seed] 귀멸의 칼날 88화 0
[seed] 귀멸의 칼날 89화 0
[seed] 귀멸의 칼날 90화 0
[seed] 귀멸의 칼날 91화 0
[seed] 귀멸의 칼날 92화 0
[seed] 귀멸의 칼날 93화 0
[seed] 귀멸의 칼날 94화 0
[seed] 귀멸의 칼날 95화 0
[seed] 귀멸의 칼날 96화 0
[seed] 귀멸의 칼날 97화 0
[seed] 귀멸의 칼날 98화 0
[seed] 귀멸의 칼날 99화 0
[seed] 귀멸의 칼날 100화 0
[seed] 귀멸의 칼날 101화 0
[seed] 귀멸의 칼날 102화 0
[seed] 귀멸의 칼날 103화 0
[seed] 귀멸의 칼날 104화 0
[seed] 귀멸의 칼날 105화 0
[seed] 귀멸의 칼날 106화 0
[seed] 귀멸의 칼날 107화 0
[seed] 귀멸의 칼날 108화 0
[seed] 귀멸의 칼날 109화 0
[seed] 귀멸의 칼날 110화 0
[seed] 귀멸의 칼날 111화 0
[seed] 귀멸의 칼날 112화 0
[seed] 귀멸의 칼날 113화 0
[seed] 귀멸의 칼날 114화 0
[seed] 귀멸의 칼날 115화 0
[seed] 귀멸의 칼날 116화 0
[seed] 귀멸의 칼날 117화 0
[seed] 귀멸의 칼날 118화 0
[seed] 귀멸의 칼날 119화 0
[seed] 귀멸의 칼날 120화 0
[seed] 귀멸의 칼날 121화 0
[seed] 귀멸의 칼날 122화 0
[seed] 귀멸의 칼날 123화 0
[seed] 귀멸의 칼날 124화 0
[seed] 귀멸의 칼날 125화 0
[seed] 귀멸의 칼날 126화 0
[seed] 귀멸의 칼날 127화 0
[seed] 귀멸의 칼날 128화 0
[seed] 귀멸의 칼날 129화 0
[seed] 귀멸의 칼날 130화 0
[seed] 귀멸의 칼날 131화 0
[seed] 귀멸의 칼날 132화 0
[seed] 귀멸의 칼날 133화 0
[seed] 귀멸의 칼날 134화 0
[seed] 귀멸의 칼날 135화 0
[seed] 귀멸의 칼날 136화 0
[seed] 귀멸의 칼날 137화 0
[seed] 귀멸의 칼날 138화 0
[seed] 귀멸의 칼날 139화 0
[seed] 귀멸의 칼날 140화 0
[seed] 귀멸의 칼날 141화 0
[seed] 귀멸의 칼날 142화 0
[seed] 귀멸의 칼날 143화 0
[seed] 귀멸의 칼날 144화 90020
wait... 귀멸의 칼날 144화
[seed] 귀멸의 칼날 145화 0
[seed] 귀멸의 칼날 146화 82030
wait... 귀멸의 칼날 146화
[seed] 귀멸의 칼날 147화 86140
wait... 귀멸의 칼날 147화
[seed] 귀멸의 칼날 148화 301170
wait... 귀멸의 칼날 148화
[seed] 귀멸의 칼날 149화 399230
wait... 귀멸의 칼날 149화
[seed] 귀멸의 칼날 150화 396500
wait... 귀멸의 칼날 150화
[seed] 귀멸의 칼날 151화 336500
wait... 귀멸의 칼날 151화
[seed] 귀멸의 칼날 152화 346320
wait... 귀멸의 칼날 152화
[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

[seed] 귀멸의 칼날 153화 373130
wait... 귀멸의 칼날 153화
Traceback (most recent call last):
File "capture", line 106, in capture
Exception: Timeout

fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 116, in capture
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 175, in read
File "manamoa_downloader", line 273, in get_imgs
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 298, in get_imgs_page
File "capture", line 116, in capture
Exception: Timeout

Invalid: fail=True
EOT: https://manamoa26.net/bbs/page.php?hid=manga_detail&manga_id=463

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
