### ISSUE TITLE
avgle.com 사이트 지원해주세요 ㅠㅠ

### ISSUE THREAD

**Issue by mnkycj** [KurtBestor/Hitomi-Downloader#1619]
제발..

**Comment by tdi2020** [comment]
저도 꼭 지원됐으면 하는 사이트로 요청해봅니다ㅠㅠ 
비슷한 다른 글에 답변을 보니 [ 참고해주세요: #607 ]  <- 요렇게 달아주셨어요. 
들어가보시면 이슈가 클로즈 되어 있는데... 
사이트 서포트 예정이신지 혹은 비슷한 프로그램이 있어서 캔슬?의 의미로 클로즈 된건지 궁금합니다

**Comment by KurtBestor** [comment]
오래돼서 닫혔어요.

시간 날 때 구현 중인데 사이트에서 보호 걸어 둔 게 많아서 좀 까다롭네요.

**Comment by KurtBestor** [comment]
오래돼서 닫혔어요.

시간 날 때 구현 중인데 사이트에서 보호 걸어 둔 게 많아서 좀 까다롭네요.

**Comment by tdi2020** [comment]
역시...ㄷㄷ 다운로더계의 봉준호 KurtBestor 선생님...

**Comment by tdi2020** [comment]
기다리다 생각나 응원글 한줄 남겨봅니다! KurtBestor선생님 코로나19 조심하시고 언제나 건강하시길 바라겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/607#issuecomment-585083518

**Comment by tdi2020** [comment]
그저 빛....
