### ISSUE TITLE
인터페이스는 장애를 가지고

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader#1621]
![image](https://user-images.githubusercontent.com/30548000/73346515-f2a0cd00-42c0-11ea-8346-d80b1c66d359.png)
오늘은 조금 혼란 된 새로운 검색 인터페이스로 업그레이드
그런데이 수정 될 수있다
덕분에 개발자

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4127338/tr_dic.txt)
 Discord  텍스트가 더 나은 변경되었습니다 참조

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
thank
