### ISSUE TITLE
니코동 영상을 다운로드를 하면 완료가 안됩니다.

### ISSUE THREAD

**Issue by caddinoob** [KurtBestor/Hitomi-Downloader#1623]
프리미엄을 사용 중 인데요

다운로드를 하다보면 어느순간 멈춰서 다운이 안되거나

다운로드 중 95%~98% 사이에 멈춰있다가 갑자기 완료로 표시되면서 파일이 자동으로 삭제되어있네요

제대로 다운이 안되고 대부분은 불완전한 작업으로 마무리가 되어서 자동으로 파일이 삭제가 

되버리던데

뭐가 문제인지 전혀 모르겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by caddinoob** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

다운로드 중 갑자기 멈추면서 불완전한 작업으로 완료된 파일입니다.

Aqoursソロ曲コレクション【ラブライブ!サンシャイン!!】

version: 2.7h
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://www.nicovideo.jp/watch/sm33568348
dir: hitomi_downloaded_nico
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/sm33568348
valid: False
done: True
range: None
range_p: None
single: True
time: 1580638467.11 (Feb 2)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_nico\Aqoursソロ曲コレクション【ラブライブ!サンシャイン!!】.mp4


[URLs]
[0001] http://pe033ab39d8.dmc.nico/vod/ht2_nicovideo/nicovideo-sm33568348_6f59a1431302f8d571c016e7ed2ed137b23ede3e3b71a785f433da407095522c?ht2_nicovideo=94250301.wok5gqxl1k_q52kg5_19a56rdncmfrw


[Messages]
stop
valid=False 1
EOT: https://www.nicovideo.jp/watch/sm33568348


다운로드가 거의 다됬을 쯤 95%~99% 쯤 멈춰서 불안정한 작업으로 완료된 파일입니다.

【第1弾】アイマスシリーズ・作曲家まとめ

version: 2.7h
platform: Windows-10-10.0.18362
order: 2
group: False
gal_num: https://www.nicovideo.jp/watch/sm34193203
dir: hitomi_downloaded_nico
zip: 
type: nico
artist: None
url: https://www.nicovideo.jp/watch/sm34193203
valid: True
done: False
range: None
range_p: None
single: True
time: 1580638460.49 (Feb 2)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_nico\【第1弾】アイマスシリーズ・作曲家まとめ.mp4


[URLs]
[0001] http://pa02859175e.dmc.nico/vod/ht2_nicovideo/nicovideo-sm34193203_356b7d6daed298335f23daed3689a5013d9c2a9ed95700997e28431156722c09?ht2_nicovideo=94250301.k3cbq1b1jj_q52kfz_9buqpjseivg1
