### ISSUE TITLE
폰허브 다운로드가 계속 읽어들이는 중으로 뜹니다.

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#1627]
계속 둥근 로딩 돌아가면서 다운로드가 시작되지 않습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by cshipa** [comment]
읽는 중... https://www.pornhub.com / view_video.php?viewkey=ph5dc2cc0cc4886

version: 2.7h
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5dc2cc0cc4886
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5dc2cc0cc4886
valid: True
done: False
range: None
range_p: None
single: True
time: 1580549539.85 (Feb 1)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5dc2cc0cc4886

**Comment by cshipa** [comment]
계속 기다리니까 방화벽 경고가 떴는데 히토미 다운로더, 팬텀JS가 차단되어 있었고 둘 다 허용하니까 다운로드가 되네요.
PhantomJS가 윈도우 방화벽 때문에 차단되어서 계속 로딩이 뜬 것 같습니다.
그리고 다운로드 실패 또는 취소 후 프로그램 종료 시 자동으로 종료되지 않고 작업 관리자에 계속 남아서 수동으로 종료를 해야 하는데, 이 문제는 조치가 가능한가요?

**Comment by KurtBestor** [comment]
원래대로면 자동으로 종료 되어야하는데요. 프로그램 강제 종료 등의 이유로 PhantomJS를 끄지 못하고 꺼지면 프로그램 다시 실행시키면 꺼져요.
