### ISSUE TITLE
웹툰 다운로드 시 기능 건의

### ISSUE THREAD

**Issue by Bangdes18** [KurtBestor/Hitomi-Downloader#1629]
네이버나 다음 웹툰 등등 낱개로 받아지는 이미지 파일의 경우
파일을 이어붙여서 하나로 만들 수 있는 기능을 넣어주실 수 있으실까요?

그리고 이렇게 좋은 프로그램 만들어주셔서 감사합니다!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/441

**Comment by Bangdes18** [comment]
> 참고해주세요: #441

감사합니다! 그런데 pdf파일로 생성 시 이미지 파일 사이사이에 공백이 생겨서요..
혹시 png? bmp? 확장자로 바꿔서 아예 공백 없이 이어붙일 수 있을까요?
