### ISSUE TITLE
유튜브 다운로드 관련 건의

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader#1630]
유튜브 컨텐츠 특성상 MP3/MP4 간 전환이 잦습니다. 
그래서 링크 끝에 mp3/mp4를 붙이는 방법으로도 파일 형식을 결정 할 수 있으면 편리할 것 같습니다.

![image](https://user-images.githubusercontent.com/36811336/73559438-5cbf9a80-4498-11ea-8005-10a1ea9e7089.png)

**Comment by KurtBestor** [comment]
직관적이지 않은데 좀 더 나은 방법 있을까요?

**Comment by wkd284** [comment]
> 
> 
> 직관적이지 않은데 좀 더 나은 방법 있을까요?

다운받은 후 필요한 것을 선택하고 오른쪽 클릭해서 일괄적으로 변환하는건 어떨까요?
음질은 옵션 유투브탭에 mp3 확장자 선택시 기본적으로 설정되있는 값을 따라가구요.

**Comment by Yoon0618** [comment]
> 직관적이지 않은데 좀 더 나은 방법 있을까요?

이친구를 활용하는건 어떨까요?

![20191210_224222435_edit](https://user-images.githubusercontent.com/36811336/73610188-011c1b00-4618-11ea-8260-c877004e8bde.png)

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/73657207-2327a300-46d5-11ea-9701-4ac5f083c9c5.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Yoon0618** [comment]
> ![image](https://user-images.githubusercontent.com/14768120/73657207-2327a300-46d5-11ea-9701-4ac5f083c9c5.png)
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 작동합니다!
