### ISSUE TITLE
뉴토끼 다운로드가 안됩니다..

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1636]
다운시작하면 뉴토끼 사이트에서 접속금지를 내려서 받지를 못해요..
이거 도와주시면 감사하겠습니다..

**Comment by kimch0612** [comment]
저같은 경우엔 20화씩 끊어서 받으면 괜찮더라고요
아무래도 크롤링 방지 기술이 들어간것 같습니다

**Comment by Sulwolhwa** [comment]
끊어받기 어떻게하나요

**Comment by IKKASSAN** [comment]
> 끊어받기 어떻게하나요

전 혹시몰라 설정에서 스레드1로하고 주소입력 옆에 파랑색 아이콘에있는 아래방향 화살표(제일 왼쪽 작은 칸) 누르고 선택화 다운로드해서 조금씩 받으니 되더라구요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1603#issuecomment-585943527
