### ISSUE TITLE
Youtube download not working

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader#1641]
Hello I tried too download a couple videos and it did not work, I also have the newest update.

This is the video I tried to download https://www.youtube.com/watch?v=zBmy9JWyCS4&t

**Comment by cancerogenic** [comment]
Right click on the program and copy and show the contents of the 'Information' window

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1604#issuecomment-578409207
