### ISSUE TITLE
네이버 및 다음 웹툰 성인 만화 다운로드 관련 문의

### ISSUE THREAD

**Issue by pico81** [KurtBestor/Hitomi-Downloader#1642]
성인 인증 관련 때문에 다운이 안되는것 같습니다.
이슈 계시판에 검색 했는데 다운로드 관련 이야기가 없어 문의 드립니다
다운을 받을 수있는 방법이 있으면 공유 부탁드립니다.

//작업 정보 내용//

Invalid: [navertoon] https://comic.naver.com / webtoon / list.nhn?titleId=670143

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://comic.naver.com/webtoon/list.nhn?titleId=670143
dir: 
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=670143
valid: False
done: True
range: None
range_p: None
single: True
time: 1580899551.93 (Feb 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 653, in __init__
File "navertoon_downloader", line 53, in init
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "navertoon_downloader", line 127, in get_pages
Exception: Age verification is required for service. Please sign in.

Invalid: fail=True
stop
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=670143

**Comment by rakukracha** [comment]
아무래도 인증까지 대신 해줄수는 없지 않을까요?
아마 성인인증은 우회가 안될겁니다.

다만 다운 방식에 따라서는
IE에서 로그인(성인인증된 계정으로) 했을경우
로그인한 쿠키나 세션이나 뭐 대충 그런게 공유되어서
다운 가능한 경우가 있는데
안타깝게도 히토미 다운로더는 그런거는 안되는 듯 하네요...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/840#issuecomment-492094360
