### ISSUE TITLE
마나모아 수정할 때 유의할점

### ISSUE THREAD

**Issue by rakukracha** [KurtBestor/Hitomi-Downloader#1649]
https://manamoa27.net/bbs/board.php?bo_table=manga&wr_id=2705603

위 링크를 비롯해서 일부 중간 엑박인 만화들이 있습니다.
제가 뭐 다 뒤져본게 아니라서 장담은 못하겠습니다만,
한 20~30%는 그렇지 않나 싶네요.

대강 관찰한 결과 2월6일 신규 업데이트 분부터는 아예 없어보이는데,
그 이전것들은 일부가 그런거 같습니다.

이 엑박은 사이트에 볼때부터 엑박인데요
주소를 보니 마나모아 박사장이 실수로 버그를 일으킨거 같습니다.

위에 제시한 링크에는 엑박이 2개 있습니다.
버그가 생겨 엑박이 되는 링크 중 하나를 보면,
https://s3.cdnscreen.cc//upload/89af8640ed2a4b6a67b561abe2a04e5e.jpg?quick
이 주소를 아래와 같이 변경하면 볼 수 있네요.(속도는 좀 느립니다만, 안보는거보단 낫죠.)
https://cdnscreen.cc/upload/89af8640ed2a4b6a67b561abe2a04e5e.jpg?quick
(앞의 s3가 빠지고 뒤쪽에 // 를 / 하나로 수정했습니다.)

수정하실때 이 트러블을 반영해주시면 감사하겠습니다. ^^

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rakukracha** [comment]
2020-02-07 오후 7:16 기준
10개 가량 다운받아봤는데(본문링크포함) 잘 되는거 같습니다.
정말 감사합니다.
