### ISSUE TITLE
유튜브 영상 1080p로 설정하고 다운시 화질이 낮게 다운되는 것 같습니다.

### ISSUE THREAD

**Issue by natjing465** [KurtBestor/Hitomi-Downloader#1654]
다운받은 영상이랑 유튜브 원본 영상이랑 나란히 놓고 비교하면 차이가 명확하게 납니다.
원래 다운받을면 화질이 낮게 다운되는 것이 맞나요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by natjing465** [comment]
답장이 늦어 죄송합니다.
화질은 설정에서 1080p로 설정했습니다.




200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: DaftTaengk
url: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s
valid: True
done: True
range: None
range_p: None
single: True
time: 1581351577.37 (Feb 11)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.mp4


[URLs]
[0001] https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581373175&ei=l4JBXpbiFK2ElQSN7pHIAQ&ip=175.114.216.221&id=o-AJtVVE7UideqqNhj6U4ERfIDsgJy0woE_wxQClVBfxCj&itag=299&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C272%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3b7kn7k&ms=au%2Conr&mv=m&mvi=0&pl=13&initcwndbps=1306250&vprv=1&mime=video%2Fmp4&gir=yes&clen=23397466&dur=102.602&lmt=1580821949086432&mt=1581351401&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5532432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANqgUusORBn9WohWjP8QBAJj2kEbCOiAgaB-lQ0fzpJaAiASjn4M8ka4vADfQH-kYoq-8mnpu0HcRIMX3OUu6m-CBg%3D%3D&sig=ALgxI2wwRAIgbucZgluahtCPR5kOkfDSli_w-zZHflVaK39xUHjkzEcCIEcggVEaehi9RCgm0WP3-Kf674ocM48cdTSSrBoNfwgw&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][0fps][None] mp4 None ─ 160 - 82x144 (144p)
[144p][0fps][None] webm None ─ 278 - 82x144 (144p)
[240p][0fps][None] mp4 None ─ 133 - 136x240 (144p)
[240p][0fps][None] webm None ─ 242 - 136x240 (144p)
[360p][0fps][None] webm None ─ 243 - 202x360 (240p)
[360p][0fps][None] mp4 None ─ 134 - 202x360 (240p)
[480p][0fps][None] webm None ─ 244 - 270x480 (240p)
[480p][0fps][None] mp4 None ─ 135 - 270x480 (240p)
[720p][0fps][None] webm None ─ 247 - 406x720 (360p)
[720p][0fps][None] mp4 None ─ 136 - 406x720 (360p)
[720p][60fps][None] webm None ─ 302 - 406x720 (360p60)
[1080p][0fps][None] webm None ─ 248 - 608x1080 (480p)
[720p][60fps][None] mp4 None ─ 298 - 406x720 (360p60)
[1080p][0fps][None] mp4 None ─ 137 - 608x1080 (480p)
[1080p][60fps][None] webm None ─ 303 - 608x1080 (480p60)
[1080p][60fps][None] mp4 None ─ 299 - 608x1080 (480p60)
[1440p][0fps][None] webm None ─ 271 - 810x1440 (720p)
[1440p][60fps][None] webm None ─ 308 - 810x1440 (720p60)
[2160p][0fps][None] webm None ─ 313 - 1216x2160 (1080p)
[3840p][60fps][None] webm None ─ 272 - 2160x3840 (2160p60)
[2160p][60fps][None] webm None ─ 315 - 1216x2160 (1080p60)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)


# stream_final <youtube_dl_test.Video object at 0x1B5D49D0> 248 - 608x1080 (480p) 1080p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x1B5D4F30> 137 - 608x1080 (480p) 1080p mp4 None 0fps
# stream_final <youtube_dl_test.Video object at 0x1B5D4930> 303 - 608x1080 (480p60) 1080p webm None 60fps
# stream_final <youtube_dl_test.Video object at 0x1B5D4650> 299 - 608x1080 (480p60) 1080p mp4 None 60fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

# stream_audio 128kbps m4a mp4a.40.2
https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581373175&ei=l4JBXpbiFK2ElQSN7pHIAQ&ip=175.114.216.221&id=o-AJtVVE7UideqqNhj6U4ERfIDsgJy0woE_wxQClVBfxCj&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3b7kn7k&ms=au%2Conr&mv=m&mvi=0&pl=13&initcwndbps=1306250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1663585&dur=102.725&lmt=1580821545793354&mt=1581351401&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANqgUusORBn9WohWjP8QBAJj2kEbCOiAgaB-lQ0fzpJaAiASjn4M8ka4vADfQH-kYoq-8mnpu0HcRIMX3OUu6m-CBg%3D%3D&sig=ALgxI2wwRgIhAMumGHcGWZ7gg8_IdR7y5w6VomCcQAzn55DIfGBdMJJ6AiEAuOifmmSxcsz6D3nS3YODSmhX92slnO0pbAYXbwiAXWk=&ratebypass=yes
Resolution: 1080p
Codec: avc1.640020 / None
Abr: None
Subtype: mp4
FPS: 60

stop
Download audio: https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581373175&ei=l4JBXpbiFK2ElQSN7pHIAQ&ip=175.114.216.221&id=o-AJtVVE7UideqqNhj6U4ERfIDsgJy0woE_wxQClVBfxCj&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3b7kn7k&ms=au%2Conr&mv=m&mvi=0&pl=13&initcwndbps=1306250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1663585&dur=102.725&lmt=1580821545793354&mt=1581351401&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANqgUusORBn9WohWjP8QBAJj2kEbCOiAgaB-lQ0fzpJaAiASjn4M8ka4vADfQH-kYoq-8mnpu0HcRIMX3OUu6m-CBg%3D%3D&sig=ALgxI2wwRgIhAMumGHcGWZ7gg8_IdR7y5w6VomCcQAzn55DIfGBdMJJ6AiEAuOifmmSxcsz6D3nS3YODSmhX92slnO0pbAYXbwiAXWk=&ratebypass=yes
Convert: C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.mp4
rename (1): hitomi_downloaded_youtube\967ED467_a.tmp -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp1624EB86_a.weba
rename (1): C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.mp4 -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp1624EB86_v.mp4
-i tmp1624EB86_v.mp4 -i tmp1624EB86_a.weba -c copy -strict experimental -preset ultrafast tmp1624EB86_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp1624EB86_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6avc1mp41
creation_time : 2020-02-04T13:06:15.000000Z
Duration: 00:01:42.60, start: 0.000000, bitrate: 1824 kb/s
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 608x1080 [SAR 1:1 DAR 76:135], 87 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 119.88 tbc (default)
Metadata:
creation_time : 2020-02-04T13:06:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp1624EB86_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-02-04T13:05:40.000000Z
Duration: 00:01:42.73, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 12 kb/s (default)
Metadata:
creation_time : 2020-02-04T13:05:40.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp1624EB86_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6avc1mp41
encoder : Lavf58.20.100
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 608x1080 [SAR 1:1 DAR 76:135], q=2-31, 87 kb/s, 59.94 fps, 59.94 tbr, 60k tbn, 60k tbc (default)
Metadata:
creation_time : 2020-02-04T13:06:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 12 kb/s (default)
Metadata:
creation_time : 2020-02-04T13:05:40.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 6150 fps=0.0 q=-1.0 Lsize= 24537kB time=00:01:42.70 bitrate=1957.2kbits/s speed=1.69e+03x 
video:22774kB audio:1605kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.647448%

Convert success: True
rename (1): C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp1624EB86_o.mp4 -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.mp4
EOT: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by natjing465** [comment]
테스트 했습니다.
이번에도 1080p로 설정하고 다운받았습니다. 
그런데 2k나 4k로 설정하고 다운받은 것 처럼 영상이 제대로 출력되지 않습니다.
저의 모니터는 2k나 4k의 영상을 출력하지 못합니다.
확인부탁드립니다.


200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: DaftTaengk
url: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s
valid: True
done: True
range: None
range_p: None
single: True
time: 1581441329.6 (Feb 12)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: mp4


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.mp4


[URLs]
[0001] https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581462925&ei=LeFCXtL6NYqXgAP-34u4CQ&ip=175.114.216.221&id=o-AFPAmCydA_DPXZhBvjf_C3o8fLwuvCTGDW9Yqfhz9jNQ&itag=315&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C272%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3belnl7&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=13&initcwndbps=1823750&vprv=1&mime=video%2Fwebm&gir=yes&clen=107412450&dur=102.602&lmt=1580822307419325&mt=1581441228&fvip=1&keepalive=yes&fexp=23842630%2C23860863&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANKLF2dAuvvH58ToAxr5wflmZ6NX9TXzf3dz_NZmnVWFAiA16y1yTRpSS3AHKa17KkJXJC5gul_0OfQVsUXgtTutIg%3D%3D&sig=ALgxI2wwRgIhAKx5gH0o20ZOdndls1lxXNYowo-qj-NtW13-GlbrG-vbAiEAz8salDywrhRE7eiYnQnofXrx5dUGcvNWTPErxshzJiI=&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 160 - 82x144 (144p)
[144p][30fps][None] webm None ─ 278 - 82x144 (144p)
[144p][30fps][None] mp4 None ─ 133 - 136x240 (144p)
[144p][30fps][None] webm None ─ 242 - 136x240 (144p)
[240p][30fps][None] webm None ─ 243 - 202x360 (240p)
[240p][30fps][None] mp4 None ─ 134 - 202x360 (240p)
[240p][30fps][None] webm None ─ 244 - 270x480 (240p)
[240p][30fps][None] mp4 None ─ 135 - 270x480 (240p)
[360p][30fps][None] webm None ─ 247 - 406x720 (360p)
[360p][30fps][None] mp4 None ─ 136 - 406x720 (360p)
[360p][60fps][None] webm None ─ 302 - 406x720 (360p60)
[480p][30fps][None] webm None ─ 248 - 608x1080 (480p)
[360p][60fps][None] mp4 None ─ 298 - 406x720 (360p60)
[480p][30fps][None] mp4 None ─ 137 - 608x1080 (480p)
[480p][60fps][None] webm None ─ 303 - 608x1080 (480p60)
[480p][60fps][None] mp4 None ─ 299 - 608x1080 (480p60)
[720p][30fps][None] webm None ─ 271 - 810x1440 (720p)
[720p][60fps][None] webm None ─ 308 - 810x1440 (720p60)
[1080p][30fps][None] webm None ─ 313 - 1216x2160 (1080p)
[2160p][60fps][None] webm None ─ 272 - 2160x3840 (2160p60)
[1080p][60fps][None] webm None ─ 315 - 1216x2160 (1080p60)
[240p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)


# stream_final <youtube_dl_test.Video object at 0x1F075D10> 313 - 1216x2160 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x1F075110> 315 - 1216x2160 (1080p60) 1080p webm None 60fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[240p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[240p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 202x360 (240p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

# stream_audio 128kbps m4a mp4a.40.2
https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581462925&ei=LeFCXtL6NYqXgAP-34u4CQ&ip=175.114.216.221&id=o-AFPAmCydA_DPXZhBvjf_C3o8fLwuvCTGDW9Yqfhz9jNQ&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3belnl7&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=13&initcwndbps=1823750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1663585&dur=102.725&lmt=1580821545793354&mt=1581441228&fvip=1&keepalive=yes&fexp=23842630%2C23860863&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANKLF2dAuvvH58ToAxr5wflmZ6NX9TXzf3dz_NZmnVWFAiA16y1yTRpSS3AHKa17KkJXJC5gul_0OfQVsUXgtTutIg%3D%3D&sig=ALgxI2wwRQIgCeeTUnFL5WYX-IK8jiMEJxaBhfq_Wks_du3IulnlrQYCIQCX__wHu-qlS6bK5RLIuxHOSv9r3zfrY16tTPtbqpjwJw==&ratebypass=yes
Resolution: 1080p
Codec: vp9 / None
Abr: None
Subtype: webm
FPS: 60

stop
Download audio: https://r1---sn-n3cgv5qc5oq-bh2se.googlevideo.com/videoplayback?expire=1581462925&ei=LeFCXtL6NYqXgAP-34u4CQ&ip=175.114.216.221&id=o-AFPAmCydA_DPXZhBvjf_C3o8fLwuvCTGDW9Yqfhz9jNQ&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2se%2Csn-i3belnl7&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=13&initcwndbps=1823750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=1663585&dur=102.725&lmt=1580821545793354&mt=1581441228&fvip=1&keepalive=yes&fexp=23842630%2C23860863&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhANKLF2dAuvvH58ToAxr5wflmZ6NX9TXzf3dz_NZmnVWFAiA16y1yTRpSS3AHKa17KkJXJC5gul_0OfQVsUXgtTutIg%3D%3D&sig=ALgxI2wwRQIgCeeTUnFL5WYX-IK8jiMEJxaBhfq_Wks_du3IulnlrQYCIQCX__wHu-qlS6bK5RLIuxHOSv9r3zfrY16tTPtbqpjwJw==&ratebypass=yes
Convert: C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.webm
rename (1): hitomi_downloaded_youtube\6F9D4B40_a.tmp -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5C818AA4_a.weba
rename (1): C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.webm -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5C818AA4_v.webm
-i tmp5C818AA4_v.webm -i tmp5C818AA4_a.weba -c copy -strict experimental -preset ultrafast tmp5C818AA4_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, matroska,webm, from 'tmp5C818AA4_v.webm':
Metadata:
encoder : google/video-file
Duration: 00:01:42.60, start: 0.000000, bitrate: 8374 kb/s
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1216x2160, SAR 1:1 DAR 76:135, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp5C818AA4_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-02-04T13:05:40.000000Z
Duration: 00:01:42.73, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 12 kb/s (default)
Metadata:
creation_time : 2020-02-04T13:05:40.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp5C818AA4_o.mp4':
Metadata:
encoder : Lavf58.20.100
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1216x2160 [SAR 1:1 DAR 76:135], q=2-31, 59.94 fps, 59.94 tbr, 16k tbn, 1k tbc (default)
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 12 kb/s (default)
Metadata:
creation_time : 2020-02-04T13:05:40.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 6150 fps=0.0 q=-1.0 Lsize= 106605kB time=00:01:42.70 bitrate=8503.4kbits/s speed= 602x 
video:104852kB audio:1605kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.139250%

Convert success: True
rename (1): C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\tmp5C818AA4_o.mp4 -> C:\Users\kji07\Desktop\김종인\hitomi_downloader_GUI\hitomi_downloader_GUI_test\hitomi_downloaded_youtube\200202 서영 SeoYoung 클락 Clock 'BABE(현아)' 4K 60P 직캠 @신촌 버스킹 by DaftTaengk.webm
rename ext .webm --> .mp4
EOT: https://www.youtube.com/watch?v=ohD_2zlZEu4&t=3s

**Comment by KurtBestor** [comment]
유튜브에서 1080p 라고 표기되어있지만 해상도는 1216x2160 이예요. 그래서 화질이 달라보였었어요.
