### ISSUE TITLE
sankaku에서 파일 유형 제외하고 다운로드 시 다운이 안됩니다.

### ISSUE THREAD

**Issue by superrogin** [KurtBestor/Hitomi-Downloader#1656]
sankaku에서 받는 중인데, 옵션 - 고급 - 파일 유형제외 - 동영상을 체크하고 다운받아보면 계속 실패합니다.

해당 옵션 해제하면 잘 됩니다.

다음은 작업 정보입니다.

대기 중... https://chan.sankakucomplex.com / ?tags=accidental_exposure

version: 2.7h
platform: Windows-10-10.0.18362
order: 381
group: False
gal_num: https://chan.sankakucomplex.com/?tags=accidental_exposure
dir: 
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=accidental_exposure
valid: True
done: False
range: None
range_p: None
single: False
time: 1581206986.48 (Feb 9)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
login... 7
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 1
types: img, gif
https://chan.sankakucomplex.com/?tags=accidental_exposure
https://chan.sankakucomplex.com/?next=19152913&tags=accidental_exposure&page=2
https://chan.sankakucomplex.com/?next=18290404&tags=accidental_exposure&page=3
https://chan.sankakucomplex.com/?next=17761319&tags=accidental_exposure&page=4
https://chan.sankakucomplex.com/?next=16847109&tags=accidental_exposure&page=5
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=16847109&tags=accidental_exposure&page=5
https://chan.sankakucomplex.com/?next=14157946&tags=accidental_exposure&page=6
https://chan.sankakucomplex.com/?next=11281109&tags=accidental_exposure&page=7
https://chan.sankakucomplex.com/?next=7775615&tags=accidental_exposure&page=8
https://chan.sankakucomplex.com/?next=7527623&tags=accidental_exposure&page=9
https://chan.sankakucomplex.com/?next=7347126&tags=accidental_exposure&page=10
https://chan.sankakucomplex.com/?next=7176641&tags=accidental_exposure&page=11
https://chan.sankakucomplex.com/?next=6963901&tags=accidental_exposure&page=12
https://chan.sankakucomplex.com/?next=6801663&tags=accidental_exposure&page=13
https://chan.sankakucomplex.com/?next=6650993&tags=accidental_exposure&page=14
https://chan.sankakucomplex.com/?next=6477063&tags=accidental_exposure&page=15
https://chan.sankakucomplex.com/?next=6330072&tags=accidental_exposure&page=16
https://chan.sankakucomplex.com/?next=6196360&tags=accidental_exposure&page=17
https://chan.sankakucomplex.com/?next=5903850&tags=accidental_exposure&page=18
https://chan.sankakucomplex.com/?next=5685546&tags=accidental_exposure&page=19
https://chan.sankakucomplex.com/?next=5464554&tags=accidental_exposure&page=20
https://chan.sankakucomplex.com/?next=5228194&tags=accidental_exposure&page=21
https://chan.sankakucomplex.com/?next=5067365&tags=accidental_exposure&page=22
https://chan.sankakucomplex.com/?next=4730683&tags=accidental_exposure&page=23
https://chan.sankakucomplex.com/?next=4120798&tags=accidental_exposure&page=24
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
https://chan.sankakucomplex.com/?next=1877828&tags=accidental_exposure&page=26
https://chan.sankakucomplex.com/?next=1035098&tags=accidental_exposure&page=27
https://chan.sankakucomplex.com/?next=463562&tags=accidental_exposure&page=28
https://chan.sankakucomplex.com/?next=76178&tags=accidental_exposure&page=29
Traceback (most recent call last):
File "sankaku_downloader", line 318, in get_imgs
KeyError: 'next-page-url'

local variable 'name' referenced before assignment
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 859, in start_
File "utils", line 1816, in Filter
UnboundLocalError: local variable 'name' referenced before assignment

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=accidental_exposure

login... 3
types: img, gif
https://chan.sankakucomplex.com/?tags=accidental_exposure
https://chan.sankakucomplex.com/?next=19152913&tags=accidental_exposure&page=2
https://chan.sankakucomplex.com/?next=18290404&tags=accidental_exposure&page=3
https://chan.sankakucomplex.com/?next=17761319&tags=accidental_exposure&page=4
https://chan.sankakucomplex.com/?next=16847109&tags=accidental_exposure&page=5
https://chan.sankakucomplex.com/?next=14157946&tags=accidental_exposure&page=6
https://chan.sankakucomplex.com/?next=11281109&tags=accidental_exposure&page=7
https://chan.sankakucomplex.com/?next=7775615&tags=accidental_exposure&page=8
https://chan.sankakucomplex.com/?next=7527623&tags=accidental_exposure&page=9
https://chan.sankakucomplex.com/?next=7347126&tags=accidental_exposure&page=10
https://chan.sankakucomplex.com/?next=7176641&tags=accidental_exposure&page=11
https://chan.sankakucomplex.com/?next=6963901&tags=accidental_exposure&page=12
https://chan.sankakucomplex.com/?next=6801663&tags=accidental_exposure&page=13
https://chan.sankakucomplex.com/?next=6650993&tags=accidental_exposure&page=14
https://chan.sankakucomplex.com/?next=6477063&tags=accidental_exposure&page=15
https://chan.sankakucomplex.com/?next=6330072&tags=accidental_exposure&page=16
https://chan.sankakucomplex.com/?next=6196360&tags=accidental_exposure&page=17
https://chan.sankakucomplex.com/?next=5903850&tags=accidental_exposure&page=18
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=5903850&tags=accidental_exposure&page=18
https://chan.sankakucomplex.com/?next=5685546&tags=accidental_exposure&page=19
https://chan.sankakucomplex.com/?next=5464554&tags=accidental_exposure&page=20
https://chan.sankakucomplex.com/?next=5228194&tags=accidental_exposure&page=21
https://chan.sankakucomplex.com/?next=5067365&tags=accidental_exposure&page=22
https://chan.sankakucomplex.com/?next=4730683&tags=accidental_exposure&page=23
https://chan.sankakucomplex.com/?next=4120798&tags=accidental_exposure&page=24
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=4120798&tags=accidental_exposure&page=24
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
<urllib3.connection.VerifiedHTTPSConnection object at 0x276A4FF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "sankaku_downloader", line 108, in read
File "sankaku_downloader", line 266, in get_imgs
File "sankaku_downloader", line 224, in read_html
File "downloader", line 286, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 344, in _make_request
File "urllib3\connectionpool", line 843, in _validate_conn
File "urllib3\connection", line 305, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x276A4FF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

Invalid: fail=True
Traceback (most recent call last):
File "utils", line 1088, in Invalid
File "downloader", line 286, in read_html
File "urllib3\poolmanager", line 326, in urlopen
File "urllib3\connectionpool", line 641, in urlopen
File "urllib3\util\retry", line 344, in increment
File "urllib3\connectionpool", line 603, in urlopen
File "urllib3\connectionpool", line 355, in _make_request
File "httplib", line 1042, in request
File "httplib", line 1082, in _send_request
File "httplib", line 1038, in endheaders
File "httplib", line 882, in _send_output
File "httplib", line 844, in send
File "urllib3\connection", line 183, in connect
File "urllib3\connection", line 169, in _new_conn
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1EF943F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

EOT: https://chan.sankakucomplex.com/?tags=accidental_exposure

login... 5
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 4
types: img, gif
https://chan.sankakucomplex.com/?tags=accidental_exposure
https://chan.sankakucomplex.com/?next=19152913&tags=accidental_exposure&page=2
https://chan.sankakucomplex.com/?next=18290404&tags=accidental_exposure&page=3
https://chan.sankakucomplex.com/?next=17761319&tags=accidental_exposure&page=4
https://chan.sankakucomplex.com/?next=16847109&tags=accidental_exposure&page=5
https://chan.sankakucomplex.com/?next=14157946&tags=accidental_exposure&page=6
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=14157946&tags=accidental_exposure&page=6
https://chan.sankakucomplex.com/?next=11281109&tags=accidental_exposure&page=7
https://chan.sankakucomplex.com/?next=7775615&tags=accidental_exposure&page=8
https://chan.sankakucomplex.com/?next=7527623&tags=accidental_exposure&page=9
https://chan.sankakucomplex.com/?next=7347126&tags=accidental_exposure&page=10
https://chan.sankakucomplex.com/?next=7176641&tags=accidental_exposure&page=11
https://chan.sankakucomplex.com/?next=6963901&tags=accidental_exposure&page=12
https://chan.sankakucomplex.com/?next=6801663&tags=accidental_exposure&page=13
https://chan.sankakucomplex.com/?next=6650993&tags=accidental_exposure&page=14
https://chan.sankakucomplex.com/?next=6477063&tags=accidental_exposure&page=15
https://chan.sankakucomplex.com/?next=6330072&tags=accidental_exposure&page=16
https://chan.sankakucomplex.com/?next=6196360&tags=accidental_exposure&page=17
https://chan.sankakucomplex.com/?next=5903850&tags=accidental_exposure&page=18
https://chan.sankakucomplex.com/?next=5685546&tags=accidental_exposure&page=19
https://chan.sankakucomplex.com/?next=5464554&tags=accidental_exposure&page=20
https://chan.sankakucomplex.com/?next=5228194&tags=accidental_exposure&page=21
https://chan.sankakucomplex.com/?next=5067365&tags=accidental_exposure&page=22
https://chan.sankakucomplex.com/?next=4730683&tags=accidental_exposure&page=23
https://chan.sankakucomplex.com/?next=4120798&tags=accidental_exposure&page=24
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
https://chan.sankakucomplex.com/?next=1877828&tags=accidental_exposure&page=26
https://chan.sankakucomplex.com/?next=1035098&tags=accidental_exposure&page=27
https://chan.sankakucomplex.com/?next=463562&tags=accidental_exposure&page=28
https://chan.sankakucomplex.com/?next=76178&tags=accidental_exposure&page=29
Traceback (most recent call last):
File "sankaku_downloader", line 318, in get_imgs
KeyError: 'next-page-url'

local variable 'name' referenced before assignment
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 859, in start_
File "utils", line 1816, in Filter
UnboundLocalError: local variable 'name' referenced before assignment

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=accidental_exposure

login... 6
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 6
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 4
types: img, gif
https://chan.sankakucomplex.com/?tags=accidental_exposure
https://chan.sankakucomplex.com/?next=19152913&tags=accidental_exposure&page=2
https://chan.sankakucomplex.com/?next=18290404&tags=accidental_exposure&page=3
https://chan.sankakucomplex.com/?next=17761319&tags=accidental_exposure&page=4
https://chan.sankakucomplex.com/?next=16847109&tags=accidental_exposure&page=5
https://chan.sankakucomplex.com/?next=14157946&tags=accidental_exposure&page=6
https://chan.sankakucomplex.com/?next=11281109&tags=accidental_exposure&page=7
https://chan.sankakucomplex.com/?next=7775615&tags=accidental_exposure&page=8
https://chan.sankakucomplex.com/?next=7527623&tags=accidental_exposure&page=9
https://chan.sankakucomplex.com/?next=7347126&tags=accidental_exposure&page=10
https://chan.sankakucomplex.com/?next=7176641&tags=accidental_exposure&page=11
https://chan.sankakucomplex.com/?next=6963901&tags=accidental_exposure&page=12
https://chan.sankakucomplex.com/?next=6801663&tags=accidental_exposure&page=13
https://chan.sankakucomplex.com/?next=6650993&tags=accidental_exposure&page=14
429 Too many requests... wait 120 secs
https://chan.sankakucomplex.com/?next=6650993&tags=accidental_exposure&page=14
https://chan.sankakucomplex.com/?next=6477063&tags=accidental_exposure&page=15
https://chan.sankakucomplex.com/?next=6330072&tags=accidental_exposure&page=16
https://chan.sankakucomplex.com/?next=6196360&tags=accidental_exposure&page=17
https://chan.sankakucomplex.com/?next=5903850&tags=accidental_exposure&page=18
https://chan.sankakucomplex.com/?next=5685546&tags=accidental_exposure&page=19
https://chan.sankakucomplex.com/?next=5464554&tags=accidental_exposure&page=20
https://chan.sankakucomplex.com/?next=5228194&tags=accidental_exposure&page=21
https://chan.sankakucomplex.com/?next=5067365&tags=accidental_exposure&page=22
https://chan.sankakucomplex.com/?next=4730683&tags=accidental_exposure&page=23
https://chan.sankakucomplex.com/?next=4120798&tags=accidental_exposure&page=24
https://chan.sankakucomplex.com/?next=3604086&tags=accidental_exposure&page=25
https://chan.sankakucomplex.com/?next=1877828&tags=accidental_exposure&page=26
https://chan.sankakucomplex.com/?next=1035098&tags=accidental_exposure&page=27
https://chan.sankakucomplex.com/?next=463562&tags=accidental_exposure&page=28
https://chan.sankakucomplex.com/?next=76178&tags=accidental_exposure&page=29
Traceback (most recent call last):
File "sankaku_downloader", line 318, in get_imgs
KeyError: 'next-page-url'

local variable 'name' referenced before assignment
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 859, in start_
File "utils", line 1816, in Filter
UnboundLocalError: local variable 'name' referenced before assignment

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=accidental_exposure

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by superrogin** [comment]
잘 됩니다, 감사합니다.
