### ISSUE TITLE
옵션 - 설정 - 픽시브에 있는 '포함 태그'는 어떤 용도인가요?

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader#1657]
F1을 눌러봐도 설명이 없어서 어떤건지 모르겠네요...
해단 태그만 포함하는건가 싶은데
용도랑 사용법을 알려주시면 감사하겠습니다!

**Comment by Dumbisted** [comment]
#961 을 참고해 주세요.

유저 페이지나 검색 결과를 받을때 만약 포함 태그 내에 등록해 놓은 특정 태그가 있다면 그 태그가 포함되어 있는 게시물만 전부 받는 기능입니다. 지정한 태그가 없는 게시물은 받지 않습니다.
