### ISSUE TITLE
트위치 클립이 중복되서 다운됩니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#1658]
https://www.twitch.tv/mogoon14/clip/SpookyHandsomeDumplingsFrankerZ?filter=clips&range=30d&sort=time

https://www.twitch.tv/mogoon14/clip/SecretiveVainRavenRalpherZ?filter=clips&range=30d&sort=time

https://www.twitch.tv/mogoon14/clip/PeppyShakingPrariedogFrankerZ?filter=clips&range=30d&sort=time

3개의 링크를 다운받았는데, 같은날짜의 방송에 대한 3개의 다른 클립입니다.

방송제목이 같아서 3개를 다운받았음에도 1개의 동영상만 다운받아집니다

재목이 같아서인거 같네요. 중복안되게 해주시면 안될까요?
![fdqq](https://user-images.githubusercontent.com/41049446/74162714-9183dc80-4c64-11ea-9ade-564b5a79d945.PNG)

**Comment by KurtBestor** [comment]
참고해주세요: #233
