### ISSUE TITLE
sankaku에서 특정 키워드는 안 받아지는 문제가 있는 것 같습니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1661]
이게 특정 키워드의 문제인지는 모르겠으나 다른 키워드 조합은 받아져도

Invalid: [sankaku] https://chan.sankakucomplex.com / ?tags=booty_calls

version: 2.7h
platform: Windows-10-10.0.17763
order: 924
group: False
gal_num: https://chan.sankakucomplex.com/?tags=booty_calls
dir: 
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=booty_calls
valid: False
done: True
range: None
range_p: None
single: False
time: 1581454246.98 (Feb 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
login... 2
types: img, gif, video
https://chan.sankakucomplex.com/?tags=booty_calls
no images
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "sankaku_downloader", line 108, in read
File "sankaku_downloader", line 330, in get_imgs
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=booty_calls

와 같이 invalid 에러가 뜨면서 안 받아지는 경우가 있어서 말씀드려봅니다.

**Comment by KurtBestor** [comment]
일반 계정에서 보이지 않는 이미지는 받아지지 않아요.
참고해주세요:
- https://forum.sankakucomplex.com/t/invisible-pictures/1548/3
- https://chan.sankakucomplex.com/wiki/show?title=help%3A_contributor_status
