### ISSUE TITLE
사이트 추가 건의드려봅니다.

### ISSUE THREAD

**Issue by chbk256** [KurtBestor/Hitomi-Downloader#1662]
https://rule34.xxx/ 구글링에 자주 뜨는 곳이고, 실제 이미지도 많이 존재하는데 한번 추가하면 어떨가 건의드려봅니다.

**Comment by chbk256** [comment]
https://github.com/LordOfPolls/Rule34-Downloader

다운로더입니다. 깃허브 들어가면 바로 받을 수 있고, 실행법도 콘솔에서

원하는 태그만 치면 되서 간단합니다.

계획이 있으시다면 참고해보시는 것도 괜찮을 것 같습니다.

**Comment by KurtBestor** [comment]
투표 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/issues/868#issuecomment-723650147
