### ISSUE TITLE
다운로더 실해이 느려요 

### ISSUE THREAD

**Issue by wlsgh5286** [KurtBestor/Hitomi-Downloader#1663]
다운로더 실해이 느려요  실행하면 실행창이 1 2분 후에 뜨고 또 다시 실행해도 3분뒤에 실행이되여 하드에 저장된 다운로더는 빠른데 외장하드에 다운로더는 느리네요 ... 왜 그런가요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
