### ISSUE TITLE
인스타그램 이미지 다운로드가 되지않습니다!

### ISSUE THREAD

**Issue by kimdoki** [KurtBestor/Hitomi-Downloader#1665]
Instagram: 개별 다운로드는 지원하지 않습니다 (https://www.instagram.com / p / B7ENBH-l5_j / )

version: 2.5d
platform: Windows-10-10.0.18362
gal_num: https://www.instagram.com/p/B7ENBH-l5_j/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/p/B7ENBH-l5_j/
valid: False
done: False
range: None
range_p: None
single: False
time: 1581449943.01 (Feb 12)
tags: []

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "hitomi_downloader_GUI", line 1199, in run
File "utils", line 195, in pop
IndexError

Fail: insta

stop
done : https://www.instagram.com/p/B7ENBH-l5_j/

요래 뜨면서 다운로드가 안되네요..어떻게 하면 해결될까요?

**Comment by KurtBestor** [comment]
개별 다운로드도 가능하게 고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
