### ISSUE TITLE
작가와 그룹의 글자수 제한을 풀어주실수 있으시나요?

### ISSUE THREAD

**Issue by 15cmd** [KurtBestor/Hitomi-Downloader#1669]
제가 알고있는 작가와 그룹을 제외시킨 작품을 보고싶은데
작가와 그룹에 글자수 제한이 있어서 원활한 검색이 안되네요.
작가와 그룹의 글자수를 무제한으로 요청드립니다.

**Comment by KurtBestor** [comment]
32767 자에서 16777215 자로 늘렸어요. 충분할거예요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by 15cmd** [comment]
정말로 감사합니다.
