### ISSUE TITLE
폰허브 다운로드 다시 무한로딩 뜨면서 안되네요...

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#1670]
이번에는 팬텀js 방화벽 경고도 뜨지 않습니다.
폰허브 쪽에서 다운로드 관련으로 손본걸까요?
아래는 정보 눌러서 나온 내용입니다.

읽는 중... https://jp.pornhub.com / view_video.php?viewkey=ph5de8d7e8352ae

version: 2.7h
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://jp.pornhub.com/view_video.php?viewkey=ph5de8d7e8352ae
dir: 
zip: 
type: pornhub
artist: None
url: https://jp.pornhub.com/view_video.php?viewkey=ph5de8d7e8352ae
valid: True
done: False
range: None
range_p: None
single: True
time: 1581686415.6 (Feb 14)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://jp.pornhub.com/view_video.php?viewkey=ph5de8d7e8352ae

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cshipa** [comment]
여전히 무한로딩 뜨네요...

읽는 중... https://www.pornhub.com / view_video.php?viewkey=ph5a0fff312ca86

version: 2.7h
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5a0fff312ca86
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5a0fff312ca86
valid: True
done: False
range: None
range_p: None
single: True
time: 1581838573.05 (Feb 16)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5a0fff312ca86

**Comment by cshipa** [comment]
시간이 한참 지나서야 방화벽 경고 뜨고 정상진행이 됩니다.
왜 매번 오류 수정 후에 방화벽 경고가 뜨는 걸까요...

**Comment by KurtBestor** [comment]
새로운 실행파일이라 방화벽에서 아직 허용되지 않아서요.
