### ISSUE TITLE
뉴토끼 다운이 안됩니다

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1676]
Invalid: [newtoki] https://newtoki45.com / bbs / / board.php?bo_table=webtoon&wr_id=46713

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://newtoki45.com/bbs//board.php?bo_table=webtoon&wr_id=46713
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki45.com/bbs//board.php?bo_table=webtoon&wr_id=46713
valid: False
done: True
range: None
range_p: None
single: False
time: 1581776378.82 (Feb 15)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Failed to get soup
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "dynamic_module_2", line 71, in read
File "dynamic_module_2", line 52, in soup
File "dynamic_module_2", line 111, in get_soup
Exception: Failed to get soup

Invalid: fail=True
EOT: https://newtoki45.com/bbs//board.php?bo_table=webtoon&wr_id=46713

새로운 스크립트를 썼는데도 다운이 안되네요 ㅠㅠ
vpn으로 우회해서 보는건 가능해도 다운은 안되는건가요..
2400시간 정지를 ip정지로 먹어서.. ㅠㅠ

**Comment by KurtBestor** [comment]
어떤 VPN 쓰시나요? 컴퓨터 전체 인터넷 연결에서 IP 변경되는 VPN 쓰셔야해요.

**Comment by Sulwolhwa** [comment]
> 어떤 VPN 쓰시나요? 컴퓨터 전체 인터넷 연결에서 IP 변경되는 VPN 쓰셔야 해요.

Touch vpn이라고 크롬확장프로그램을 사용하고 있습니다
