### ISSUE TITLE
마나모아 다운이 안되네요.. ㅇㅅㅇ

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1677]
다운되는듯이 작동되지만 전부다 0로 뜨네요
version: 2.7h
platform: Windows-10-10.0.17763
order: -11
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=5306
dir: 
zip: 
type: manamoa
artist: 마시마 히로
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=5306
valid: True
done: False
range: None
range_p: None
single: False
time: 1581776589.02 (Feb 15)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
[seed] 페어리 테일 -100년 퀘스트- 1화 0
[seed] 페어리 테일 -100년 퀘스트- 2화 0

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1647
