### ISSUE TITLE
마나모아가 막힌걸로 아는데 그럼 이제 영원히 다운로드할수없나요?

### ISSUE THREAD

**Issue by rlaruddnjs388** [KurtBestor/Hitomi-Downloader#1678]
마나모아가 방금전까지도 1~9화 까지는 다운이 되다가 안됬거든요.  그뒤로는 아무리 시도해도 안되네요.  이제 마나모아에서는 다운로드가 영원히 안되나요?

**Comment by tdi2020** [comment]
참고해주세요: #1647

*KurtBestor 선생님께서 동일한 질문 글에 남겨주신 답변입니다!
