### ISSUE TITLE
마나모아 다운로드가 안되요.

### ISSUE THREAD

**Issue by vldjs3561** [KurtBestor/Hitomi-Downloader#1679]
마나모아 다운로드가 안되요.

이 프로그램으로 잘쓰다가 어느순간부터 안되요..

크롬 으로 개발자 도구 열어서 일일이 하나씩 다운로드는 되는데 너무 번거롭고 수고가 많이들어서

**Comment by rlaruddnjs388** [comment]
크롬으로 개발자 도구 열어서  어떻게 해요? 혹시 방법 알려주실수있나요?

**Comment by STRESSSSS** [comment]
> 크롬으로 개발자 도구 열어서 어떻게 해요? 혹시 방법 알려주실수있나요?

크롬에서 다운할 페이지 띄워놓고, F12 누르고 우측상단에 세로로 점 3개 찍힌 메뉴있습니다.
거기서 세팅들어가서 밑으로 쭉 내려보면 Disable Java 어쩌고하는게 있을건데
거기에 체크하면 보통 우클릭 막힌 사이트는 대부분 뚫립니다.

**Comment by tdi2020** [comment]
참고해주세요: #1647

*KurtBestor 선생님께서 동일한 질문 글에 남겨주신 답변입니다!
