### ISSUE TITLE
유튜브 회원전용 다운도 가능할까요?

### ISSUE THREAD

**Issue by STRESSSSS** [KurtBestor/Hitomi-Downloader#1680]
지금 유튜브의경우 회원전용은 다운로드가 안되는걸로 알고있습니다.
혹시 이걸 가능하게 해주실수있는 방법이 있으시다면 추가가 가능할까요?
아니면 픽시브처럼 계정정보를 넣어서 로그인후 다운하는 방식으로라두요.
혹시 가능하시다면 부탁드립니다. 항상 좋은 프로그램 사용하게 해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
다음과 같이 쿠키 불러와서 로그인 할 수 있어요:
- `옵션` - `설정...` - `고급 설정` - `쿠키` - `불러오기...`

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by STRESSSSS** [comment]
> 다음과 같이 쿠키 불러와서 로그인 할 수 있어요:
> 
> * `옵션` - `설정...` - `고급 설정` - `쿠키` - `불러오기...`
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

쿠키파일을 어떻게 저장해서 불러오는지 잘몰라서 그것부터 검색해서 확인해봐야겠네요.
피드백 바로 받아주셔서 감사합니다. 테스트해보고 혹여나 문제있다면 다시 댓글 작성하겠습니다.
: )

**Comment by inchaos4315** [comment]
감사합니다.

**Comment by son1004007** [comment]
감사합니다. 
지금 회원전용 다운로드 완료했습니다.
유튜브 재생 목록으로 다운로드 진행했습니다.
감사합니다.
