### ISSUE TITLE
PhantomJs accesing network

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader#1683]
Hello I was downloading a video and then I got a phantomjs is trying to access my network popup, what is phantomjs and does hitomi use it? thank you for your time

**Comment by KurtBestor** [comment]
Hitomi Downloader uses [PhantomJS](https://en.wikipedia.org/wiki/PhantomJS) to extract dynamic content from the webpage.

You have to "Allow access" for PhantomJS to download videos.

**Comment by jessicachon** [comment]
oh, thank you for the reply! I canceled the request is there a way to make phantomjs pop up window come back up to re-enable it?

**Comment by KurtBestor** [comment]
You can change it in here:
![image](https://user-images.githubusercontent.com/14768120/81151998-7eab4a80-8fbc-11ea-8935-830fb4351a16.png)
