### ISSUE TITLE
마나모아 다운로드가 안됩니다

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader#1685]
![20200219_161544](https://user-images.githubusercontent.com/47558641/74810648-2d7fa900-5333-11ea-970f-fe0fa2cfdb11.png)

일부 되는게 있고 안되는게 있는데 왜 이런건지 모르겠네요ㅠㅠ;

**Comment by KurtBestor** [comment]
참고해주세요: #1647
