### ISSUE TITLE
새로 받은건 실행이 안됩니다 ..

### ISSUE THREAD

**Issue by aksghkqhrl** [KurtBestor/Hitomi-Downloader#1687]
윈도우10 최신업데이트인데

실행이 안되네요 ...

![20200220_151838](https://user-images.githubusercontent.com/47558641/74906424-603da600-53f4-11ea-98b3-0187aac43dce.png)

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by aksghkqhrl** [comment]
V3 사용합니다.

**Comment by aksghkqhrl** [comment]
> 어, 들려요?

V3 사용합니다.

**Comment by KurtBestor** [comment]
백신 예외 목록에 추가해서 실행해보세요.
