### ISSUE TITLE
유튜브 일부 동영상은 다운로드 후에 영상이 나오지 않고 소리만 나옵니다.

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#1689]
https://youtu.be/dmfNXOrqU4w 
위 링크 영상을 다운로드하면 제목처럼 되네요.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by cshipa** [comment]
Gundam Build Divers Re:RISE – #1: Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub)

version: 2.7h
platform: Windows-10-10.0.18362
order: 12
group: False
gal_num: https://youtu.be/dmfNXOrqU4w
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: GundamInfo
url: https://youtu.be/dmfNXOrqU4w
valid: True
done: True
range: None
range_p: None
single: True
time: 1582544116.18 (Feb 24)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: mp4


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\Gundam Build Divers Re：RISE - #1： Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub).mp4
[0002] hitomi_downloaded_youtube\Gundam Build Divers Re：RISE - #1： Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub).srt


[URLs]
[0001] https://r1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1582565716&ei=9LRTXvvfEsOMlQT-gaXQBg&ip=218.237.106.193&id=o-AEHENho2nN2zfpoYtdE9vK_tN-us-rzzIRs2aK45Gpbl&itag=398&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3b7knlk&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=19&gcr=kr&initcwndbps=1167500&vprv=1&mime=video%2Fmp4&gir=yes&clen=125655407&dur=1529.069&lmt=1571099339229258&mt=1582544021&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgO6OBvuHk6A_f_RftdhK1m8Nziw2QGrxPT7Co_d6zHDMCIC9y_cm1QrN1rDxHEyNBh796_cqbScMwVi6b8KZMYG1O&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhANjT8kg0pBkA1-j3xJrYeM7Bh4yDbgLEhCHuwDx2mSVUAiEA99Bvef2Jy5Oe46HtJmfkoQnFtRbcq5PtaFFYbPeF28c%3D&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][24fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][24fps][None] mp4 None ─ 160 - 256x144 (144p)
[144p][24fps][None] webm None ─ 278 - 256x144 (144p)
[240p][24fps][None] webm None ─ 242 - 426x240 (240p)
[240p][24fps][None] mp4 None ─ 395 - 426x240 (240p)
[240p][24fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][24fps][None] mp4 None ─ 396 - 640x360 (360p)
[360p][24fps][None] webm None ─ 243 - 640x360 (360p)
[360p][24fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][24fps][None] mp4 None ─ 397 - 854x480 (480p)
[480p][24fps][None] webm None ─ 244 - 854x480 (480p)
[480p][24fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][24fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][24fps][None] mp4 None ─ 398 - 1280x720 (720p)
[720p][24fps][None] mp4 None ─ 136 - 1280x720 (720p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)


# stream_final <youtube_dl_test.Video object at 0x1BEF5710> 247 - 1280x720 (720p) 720p webm None 24fps
# stream_final <youtube_dl_test.Video object at 0x1BEF5850> 398 - 1280x720 (720p) 720p mp4 None 24fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

# stream_audio 128kbps m4a mp4a.40.2
https://r1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1582565716&ei=9LRTXvvfEsOMlQT-gaXQBg&ip=218.237.106.193&id=o-AEHENho2nN2zfpoYtdE9vK_tN-us-rzzIRs2aK45Gpbl&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3b7knlk&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=19&gcr=kr&initcwndbps=1167500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=24747974&dur=1529.126&lmt=1571092307181673&mt=1582544021&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgcdtW5YvPeFxwmmzAKsRt9E3XR7ktg616sdRXLtA5ISICIQDhxUjwVbkrImGVK-Ne34nKeq14r68jsVFtnQvqCsP9Qw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhANjT8kg0pBkA1-j3xJrYeM7Bh4yDbgLEhCHuwDx2mSVUAiEA99Bvef2Jy5Oe46HtJmfkoQnFtRbcq5PtaFFYbPeF28c%3D&ratebypass=yes
Resolution: 720p
Codec: av01.0.05M.08 / None
Abr: None
Subtype: mp4
FPS: 24

stop
Download audio: https://r1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1582565716&ei=9LRTXvvfEsOMlQT-gaXQBg&ip=218.237.106.193&id=o-AEHENho2nN2zfpoYtdE9vK_tN-us-rzzIRs2aK45Gpbl&itag=140&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3b7knlk&ms=au%2Conr&mv=m&mvi=0&pcm2cms=yes&pl=19&gcr=kr&initcwndbps=1167500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=24747974&dur=1529.126&lmt=1571092307181673&mt=1582544021&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRQIgcdtW5YvPeFxwmmzAKsRt9E3XR7ktg616sdRXLtA5ISICIQDhxUjwVbkrImGVK-Ne34nKeq14r68jsVFtnQvqCsP9Qw%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhANjT8kg0pBkA1-j3xJrYeM7Bh4yDbgLEhCHuwDx2mSVUAiEA99Bvef2Jy5Oe46HtJmfkoQnFtRbcq5PtaFFYbPeF28c%3D&ratebypass=yes
Convert: D:\hitomi_downloaded_youtube\Gundam Build Divers Re：RISE - #1： Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub).mp4
rename (1): hitomi_downloaded_youtube\B18189CB_a.tmp -> D:\\hitomi_downloaded_youtube\tmp008CD49F_a.weba
rename (1): D:\hitomi_downloaded_youtube\Gundam Build Divers Re：RISE - #1： Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub).mp4 -> D:\hitomi_downloaded_youtube\tmp008CD49F_v.mp4
-i tmp008CD49F_v.mp4 -i tmp008CD49F_a.weba -c copy -strict experimental -preset ultrafast tmp008CD49F_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[libaom-av1 @ 05935240] 1.0.0-900-g7715ae1c7
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp008CD49F_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
creation_time : 2019-10-14T23:57:53.000000Z
Duration: 00:25:29.07, start: 0.000000, bitrate: 657 kb/s
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1280x720, 3 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
Metadata:
creation_time : 2019-10-14T23:57:53.000000Z
handler_name : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp008CD49F_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2019-10-14T22:31:00.000000Z
Duration: 00:25:29.13, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
Metadata:
creation_time : 2019-10-14T22:31:00.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp008CD49F_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
encoder : Lavf58.20.100
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1280x720, q=2-31, 3 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 24k tbc (default)
Metadata:
creation_time : 2019-10-14T23:57:53.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
Metadata:
creation_time : 2019-10-14T22:31:00.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 2079 fps=0.0 q=-1.0 size= 11008kB time=00:01:26.66 bitrate=1040.5kbits/s speed= 159x 
frame= 4387 fps=4166 q=-1.0 size= 20480kB time=00:03:02.93 bitrate= 917.1kbits/s speed= 174x 
frame= 9925 fps=5838 q=-1.0 size= 46592kB time=00:06:53.91 bitrate= 922.1kbits/s speed= 243x 
frame=16549 fps=6793 q=-1.0 size= 66816kB time=00:11:30.18 bitrate= 793.1kbits/s speed= 283x 
frame=23085 fps=7621 q=-1.0 size= 85504kB time=00:16:02.79 bitrate= 727.5kbits/s speed= 318x 
frame=24246 fps=6771 q=-1.0 size= 90112kB time=00:16:51.22 bitrate= 730.0kbits/s speed= 282x 
frame=24374 fps=5602 q=-1.0 size= 90624kB time=00:16:56.55 bitrate= 730.3kbits/s speed= 234x 
frame=24811 fps=5114 q=-1.0 size= 92672kB time=00:17:14.78 bitrate= 733.7kbits/s speed= 213x 
frame=25883 fps=4653 q=-1.0 size= 98048kB time=00:17:59.49 bitrate= 744.1kbits/s speed= 194x 
frame=27642 fps=4537 q=-1.0 size= 106496kB time=00:19:12.86 bitrate= 756.7kbits/s speed= 189x 
frame=28510 fps=4325 q=-1.0 size= 111104kB time=00:19:49.07 bitrate= 765.4kbits/s speed= 180x 
frame=29641 fps=4162 q=-1.0 size= 117504kB time=00:20:36.23 bitrate= 778.6kbits/s speed= 174x 
frame=33142 fps=4329 q=-1.0 size= 132096kB time=00:23:02.25 bitrate= 782.9kbits/s speed= 181x 
frame=36001 fps=4409 q=-1.0 size= 143360kB time=00:25:01.50 bitrate= 782.2kbits/s speed= 184x 
frame=36661 fps=4383 q=-1.0 Lsize= 147078kB time=00:25:29.10 bitrate= 788.0kbits/s speed= 183x 
video:122391kB audio:23893kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.543378%

Convert success: True
rename (1): D:\hitomi_downloaded_youtube\tmp008CD49F_o.mp4 -> D:\hitomi_downloaded_youtube\Gundam Build Divers Re：RISE - #1： Wandering Core Gundam (EN,HK,TW,KR,TH,FR,IT,VN sub).mp4
EOT: https://youtu.be/dmfNXOrqU4w

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1701#issuecomment-590234822
