### ISSUE TITLE
저장 내역을 500장 단위로 끊어서 페이징 부탁드립니다

### ISSUE THREAD

**Issue by univdev** [KurtBestor/Hitomi-Downloader#1690]
좋은 프로그램 정말 잘 쓰고 있습니다.

하지만 이용하는데 크게 불편한 사항이 한 가지 있는데, 로컬에 저장한 내역의 갯수가 1300개를 돌파한 시점부터 프로그램 부팅이나 동작 시 퍼포먼스 저하가 많이 발생합니다. 로컬 데이터가 너무 많이 축적 되었을 때의 대처가 필요할 것 같습니다.

**Comment by KurtBestor** [comment]
다운로드 중인 작업이 있다면 Serialization 에 문제가 있어서 페이징은 어려울 것 같아요.

다른 좋은 방법 있으면 알려주세요.
