### ISSUE TITLE
마나모나 다운이 안됩니다..

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader#1692]
읽는 중... https://manamoa28.net / bbs / board.php?bo_table=manga&wr_id=2800535

version: 2.7h
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://manamoa28.net/bbs/board.php?bo_table=manga&wr_id=2800535
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa28.net/bbs/page.php?hid=manga_detail&manga_id=13639
valid: True
done: False
range: None
range_p: None
single: False
time: 1582339270.69 (Feb 22)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
redirect: https://manamoa28.net/bbs/page.php?hid=manga_detail&manga_id=13639
Solve protection

-------------------

안녕하세요. 갑자기 그냥 계속 로딩만 되면서 크롬 새창이 뜨네요..
먼가 디도스 업데이트 하면서 바뀐거 같습니다.

**Comment by KurtBestor** [comment]
테스트 버전 다시 받아서 해도 안 되나요?

**Comment by xenohoya** [comment]
22일인가 23일엔가에 마나모아 하루 종일 접속 안됐었는데
그때 뭐 한거 같습니다  # 1647 안됩니다

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/75134008-48319380-5720-11ea-8d0b-7446052798e3.png)

재현할 수가 없네요.

**Comment by bewidu** [comment]
주소를
https://manamoa27.net/

으로 접속한후에 다운해 보세요. 잘 됩니다.
manamoa.net으로 접속하면 다운이 안되더군요.

**Comment by cocoman1111** [comment]
저 테스트버전이 어디에 잇는 테스트 버전인지 알 수 있을까요??
https://manamoa28.net/ 인경우 다운이 안되는데 https://manamoa27.net/인경우는 다운로드가 됩니다.
