### ISSUE TITLE
xvideo 계정 단위 다운로드 가능한가요??

### ISSUE THREAD

**Issue by khj871030** [KurtBestor/Hitomi-Downloader#1695]
히토미 다운로더 너무 잘 쓰고 있어서 항상 감사드리고있습니다.
폰허브 같은경우 계정 비디오 탭의 주소 넣으면 한번에 다운로드가 되던데
xvideo 같은 경우는 안되고 바로 빨간색으로 뜨더라구요. invalid  바로 뜨는데..
낱개 다운은 잘 됩니다. 계저단위만 안되는데...
혹시 계정 전체 동영상 한번에 다운로드 가능하게 해주실수 있는지요?

**Comment by tdi2020** [comment]
앗 저도 이 기능 있으면 너무 좋을것 같습니다!

**Comment by khj871030** [comment]
> _No description provided._
