### ISSUE TITLE
문의) 폰헙 플레이어 리스트 다운은 안되는 건가요?

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader#1699]
안녕하세요.

주소를 넣으니 플레이어 리스트를 읽기는 하는데

다운은 안되네요.

폰헙은 통합 다운이 안되는지 문의드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1610

**Comment by cocoman1111** [comment]
감사합니다
