### ISSUE TITLE
마나모아 안되내요 ..22일 이후 뭔 업뎃을 한듯;;

### ISSUE THREAD

**Issue by kara0111** [KurtBestor/Hitomi-Downloader#1703]

**Comment by bewidu** [comment]
주소를
https://manamoa27.net/

으로 접속한후에 다운해 보세요. 잘 됩니다.

**Comment by leewongu** [comment]
https://manamoa27.net/ 접속 안되는데 저만 그런가요? 
28은 다운이 안되고요

**Comment by leewongu** [comment]
asdf

**Comment by bewidu** [comment]
먼저 크롬으로 manamoa.net/…….   으로 접속한 후에 정상적으로 접속이 되면 그때 주소창에 27을 manamoa다음에 넣습니다.

그렇게 한 다음 다시 접속해 보세요. 정상적으로 접속이 되면 그 주소를 복사 해서 히토미 다운로더에 붙여넣기 한후 다운로드 해보세요

Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: leewongu<mailto:notifications@github.com>
보낸 날짜: 2020년 2월 25일 화요일 오전 9:29
받는 사람: KurtBestor/Hitomi-Downloader-issues<mailto:Hitomi-Downloader-issues@noreply.github.com>
참조: bewidu<mailto:bewidu@hotmail.com>; Comment<mailto:comment@noreply.github.com>
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 마나모아 안되내요 ..22일 이후 뭔 업뎃을 한듯;; (#1703)


https://manamoa27.net/ 접속 안되는데 저만 그런가요?
28은 다운이 안되고요

**Comment by puzdragon** [comment]
감사합니다. 지금 다시 manamoa28로  들어가서 해보니까 다운이 되요 
어제는 안됬었는데 ;;;; 
빠르고 자세한 리퀘스트 감사합니다

**Comment by kara0111** [comment]
아 진짜 뭐같내요 29되니깐 또 안됨 ㅋㅋㅋ 숫자하나하나 올라갈때마다 안되내 진짴ㅋㅋㅋ 개빡쳐
