### ISSUE TITLE
제이마나 다운로드 도중 멈춤 현상이 일어납니다

### ISSUE THREAD

**Issue by kong1110** [KurtBestor/Hitomi-Downloader#1704]
[information.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4243426/information.txt)
![asdf](https://user-images.githubusercontent.com/61405057/75134192-e4f43100-5720-11ea-9308-8d826a956307.JPG)

---------------------------------------------------------------------------------------------------------

안녕하십니까 형님. 항상 수고 많으십니다.
다름이 아니라 이렇게 제이마나 긁어오는 도중에 멈춤 현상이 나타나고 몇분을 기다려도 변화가 없는데 어떤 상황인지 여쭤봐도 되겠습니까?

**Comment by KurtBestor** [comment]
브라우저에서 구글 로그인 하고 `옵션` - `설정` - `고급 설정` - `쿠키` - `불러오기...` 눌러서 구글 쿠키 불러와주세요.

구글 드라이브에 올려져 있는 파일인데 접속이 많다보니 로그인하지 않으면 보이지 않게 돼있어요.

**Comment by kong1110** [comment]
답변 정말 감사드립니다. 그런데 말씀하신 옵션에 들어가서 설정하라는 건 다운로더를 말씀하시는 게 맞는지요?
옵션-설정-고급까지는 들어갔는데 쿠키 항목이 보이지 않아서요...

**Comment by KurtBestor** [comment]
아직 테스트 버전에만 구현되어있어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by kong1110** [comment]
와 시원하게 해결됐습니다. 감사합니다.
