### ISSUE TITLE
porncomic에서 다운로드가 안됩니다

### ISSUE THREAD

**Issue by pink0258** [KurtBestor/Hitomi-Downloader#1705]
![이게](https://user-images.githubusercontent.com/58359066/75135460-e7f12080-5724-11ea-82b1-79038118827d.JPG)
![아닌가](https://user-images.githubusercontent.com/58359066/75135463-eaec1100-5724-11ea-85c4-33a8abcb6ab2.JPG)
![왜안될까](https://user-images.githubusercontent.com/58359066/75135501-06efb280-5725-11ea-8fa0-0aaf8adf09ca.JPG)

스크립트링크에서 스크립트 파일 다운 받은 후 다운 받으려 하니까 저렇게 나오네요...
혹시 제가 스크립트 부분에서 실수한건가요?

**Comment by KurtBestor** [comment]
고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

**Comment by pink0258** [comment]
선생님 정말 감사합니다!
