### ISSUE TITLE
마나모아에서 다운시에.. "크롬" 이 뜹니다.

### ISSUE THREAD

**Issue by eizmdkzks** [KurtBestor/Hitomi-Downloader#1706]
마나모아에서 다운로드는 됩니다만..
문제는 크롬창이 새창으로 뜨면서 닫혔다, 다시 열렸다 하네요..

해결안이 잇을까요?

**Comment by Dumbisted** [comment]
그건 마나모아의 봇 방지 필터를 통과하기 위한 자동화 절차 중 하나인 걸로 알고있습니다. 사전 설명이 없다 보니 놀라기 쉬워서 문제죠.

**Comment by eizmdkzks** [comment]
어제께인가 그저께인가 크롬창은 원래 안떴던 문제였습니다.
그런데 갑자기 마나모아에서 다운로드를 할때 새창이 뜨는 현상 땜에 해결안을 구하는거죠.

**Comment by KurtBestor** [comment]
참고해주세요: #853
