### ISSUE TITLE
마나모아 혹은 제이마나 다운로드 문제

### ISSUE THREAD

**Issue by Kilipie** [KurtBestor/Hitomi-Downloader#1708]
둘다 다운로드가 전혀 되지않습니다.
목록을 불러들이고 나서 그이후에 다운로드가 시작될때 0.0kb/s에서 멈춰있습니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
