### ISSUE TITLE
For pixiv is there a way to download all your bookmarks?

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader#1710]
Hello! I wanted to know for pixiv is there a way to download all your favorited bookmarks only? And I want to say I really love your program it is the most beautifuly put together project I've seen yet!

**Comment by KurtBestor** [comment]
Pixiv's bookmark URL has changed. Try the test version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
