### ISSUE TITLE
트위터 안받아지는데 자동패치로 버전업을 해주세요

### ISSUE THREAD

**Issue by PCPLS** [KurtBestor/Hitomi-Downloader#1715]
이전에 누가 트위터 안받아진다고 해서 올린 글에 링크 있던데

그 경로로 가서 자료 다운받았는데 어떻게 패치해야하는지 모르겠어요

그냥 자동패치로 되게 버전업을 해주세요 부탁드립니다

**Comment by KurtBestor** [comment]
압축파일 안의 `hitomi_downlaoder_GUI.exe` 를 기존 실행파일에 덮어씌우시면 돼요.
