### ISSUE TITLE
히토미 다운로드 불가현상입니다.

### ISSUE THREAD

**Issue by cocoman1111** [KurtBestor/Hitomi-Downloader#1719]
Invalid: [manamoa] https://manamoa29.net / bbs / board.php?bo_table=manga&wr_id=2833903

version: 2.7h (20-02-27 06:31:03 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833903
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833903
valid: False
done: True
range: None
range_p: None
single: True
time: 1582811736.93 (Feb 27)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "manamoa_downloader", line 136, in init
File "manamoa_downloader", line 101, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
stop
EOT: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833903

-----
주소가 https://manamoa29.net/ 되고 나서 안되네요..

주소를 28로 변경해도 안됩니다 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cocoman1111** [comment]
감사합니다. 다운이 잘 됩니다.^^
