### ISSUE TITLE
마나모아에서 동작하지 않습니다.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader#1720]
#1647에서 받으라던 업데이트를 써서 받아도 마나모아에서 동작하지 않습니다.

Invalid: [manamoa] https://manamoa29.net / bbs / page.php?hid=manga_detail&manga_id=1891

version: 2.7h (20-02-27 06:31:03 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 92
group: False
gal_num: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=1891
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=1891
valid: False
done: True
range: None
range_p: None
single: False
time: 1582811520.77 (Feb 27)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 208, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 809, in start
File "utils", line 856, in start_
File "manamoa_downloader", line 180, in read
File "manamoa_downloader", line 167, in name
File "manamoa_downloader", line 153, in soup
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 208, in get_soup
Exception: No subject

Invalid: fail=True
EOT: https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=1891

**Comment by kara0111** [comment]
아 진짜 29되면서 안되더라구요 갑자기 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ저녁이후로 안되더군요 ㅋㅋㅋㅋㅋㅋ

**Comment by mita5549** [comment]
주소 바꾸면 가끔 이러더라구요.ㅋㅋㅋ
업데이트나 TEST를 기다려봅시다 :D 

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
 # 현재 테스트 버전도 안됨.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1719

**Comment by bewidu** [comment]
#1719 테스트 버전으로 안됩니다. 주소가 모두  https://manamoa29.net/..... 으로 변환되면서 다운 안됩니다.

**Comment by bewidu** [comment]
Invalid: [manamoa] https://manamoa29.net / bbs / board.php?bo_table=manga&wr_id=2833629

version: 2.7h (20-02-27 20:35:07 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833629
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833629
valid: False
done: True
range: None
range_p: None
single: True
time: 1582851506.13 (Feb 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
Solve protection
【chrome】 load...
【chrome】 loaded
【chrome】 load...
【chrome】 loaded
stop
Traceback (most recent call last):
File "utils", line 671, in __init__
File "manamoa_downloader", line 134, in init
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 210, in get_soup
File "manamoa_downloader", line 112, in solve_protection
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "clf", line 9, in wait
File "chrome", line 203, in start
File "chrome", line 129, in __init__
File "FUCK(5)\chrome\webdriver", line 26, in __init__
File "FUCK(5)\common\service", line 58, in start
WebDriverException: Message: The executable chromedriver.exe needs to be available in the path. Please see https://sites.google.com/a/chromium.org/chromedriver/home
'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)




Invalid: fail=True
stop
EOT: https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=2833629

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
__import__('tempfile').gettempdir()
```

**Comment by bewidu** [comment]
__import__('tempfile').gettempdir() 

'c:\\users\\\xc0\xcc\xba\xb4\xc0\xb2\\appdata\\local\\temp'

이렇게 나오는데 제가 맞게 한건지 모르겠네요......

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cancerogenic** [comment]
너무 잘됩니다 눈물이 납니다 만화를 다운 못받으니 하늘이 무너졌었는데 쿠로버스터님은 이세상 한줄기의 구세주님 이십니다 너무나 고맙습니다

**Comment by bewidu** [comment]
저도 이제 잘 됩니다. 너무나 감사드립니다.

**Comment by geniussjt** [comment]
위에 테스트 버전 받았는데..요 전 다운이 안되네요
아! 그리고  trl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용입니다
__import__('tempfile').gettempdir()
    
     import('tempfile').gettempdir()  

    Traceback (most recent call last):
      File "console\Console.pyo", line 157, in execSingle
      File "<string>", line 1
        import('tempfile').gettempdir()
              ^
    SyntaxError: invalid syntax
    
전 이렇게 나오는데요ㅠㅠ

**Comment by bewidu** [comment]
저도 프로그래밍에 대해서 전혀 몰라서 뭐라고 말씀드리기가 어렵네요.

단지 전 크롬을 사용합니다. 인터넷 익스플로어 냐 크롬이냐가 뭐가 중요하냐면

이번에 새롭게 나온 테스트용 히토미 다운로드가 수시로 크롬창을 띄었다 없앴다 합니다.

그리고 한가지 더 사용 방법을 알려드리자면 예전보다 10배 정도 시간이 더 걸립니다.

그냥 주소 넣고 한참 다른일 하면서 기다려야 다운이 완료되어 있습니다.

단순히 일이십초 기다려도 다운이 안된다고 해서 안되는 것이 아니고 계속 기다리면 결국에는 다운이 됩니다.

도움이 됬기를 바랍니다.

Windows 10용 메일<https://go.microsoft.com/fwlink/?LinkId=550986>에서 보냄

보낸 사람: geniussjt<mailto:notifications@github.com>
보낸 날짜: 2020년 2월 29일 토요일 오후 6:58
받는 사람: KurtBestor/Hitomi-Downloader-issues<mailto:Hitomi-Downloader-issues@noreply.github.com>
참조: bewidu<mailto:bewidu@hotmail.com>; Comment<mailto:comment@noreply.github.com>
제목: Re: [KurtBestor/Hitomi-Downloader-issues] 마나모아에서 동작하지 않습니다. (#1720)


위에 테스트 버전 받았는데..요 전 다운이 안되네요
아! 그리고 trl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용입니다
import('tempfile').gettempdir()

 import('tempfile').gettempdir()







Traceback (most recent call last):



  File "console\Console.pyo", line 157, in execSingle



  File "<string>", line 1



    import('tempfile').gettempdir()



          ^



SyntaxError: invalid syntax



전 이렇게 나오는데요ㅠㅠ

**Comment by KurtBestor** [comment]
@geniussjt 

`import('tempfile').gettempdir()` 말고 `__import__('tempfile').gettempdir()` 입력해주세요.

**Comment by geniussjt** [comment]
아 그렇군요
__import__('tempfile').gettempdir() 

'c:\\users\\admini~1\\appdata\\local\\temp'
이건가요...
암튼 매번 감사합니다^^

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
지금 해봤는데요... 
사이트이 디도스 공격 인가 뭔가 때문에 사이트이 망가졌다고 하네요
그래서 다운이 전혀 안됩니다..ㅜㅜ.
암튼 수고하셨습니다^^
감사해요^^(진심)

**Comment by pockylove** [comment]
흑흑 개발자님 당신은 천재입니다
감동받아서 댓글 남기려고 회원가입까지 했습니다
이런 프로그램을 몰랐다니 난 인생을 헛살았던거야

**Comment by cancerogenic** [comment]
개발자 선생님께서는 차후 반드시 국회나 내각에 들어가셔야 할 대한민국 최고의 인재입니다. 꼭 기억해 두겠습니다.
