### ISSUE TITLE
preview 사용 시 자꾸 브라우저 창이 열립니다.

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader#1723]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

마나모아 다운로드 이슈로 위의 버전을 받았는데, 다운로드 요청 시(혹은 우측의 선택 화 다운로드 눌러서 목록을 부를 시)  자꾸한 다운받고자 하는 작품이 작게 크롬 창으로 열립니다.
거기에 계속 포커스가 잡혀서 다운로드를 눌러놓고 pc를 제대로 사용할 수가 없네요... 다운로드는 되지만 상당히 불편합니다. 또 창을 끄게 되면 그 목록은 무한로딩됩니다.
부디 해결해주시면 감사하겠습니다.

아래와 같은 작은 창이 계속 좌상단에 뜹니다.
![캡처](https://user-images.githubusercontent.com/43954535/75566751-9a154900-5a93-11ea-88f2-bf07005e08a9.PNG)

항상 감사합니다.

**Comment by luku756** [comment]
그리고 같은 이유인지는 모르겠습니다만, 다운받을 때 '선택 화 다운로드' 기능을 자주 사용하는 편인데 이게 우선순위가 낮아진 건지 상당히 느려졌네요 ㅠㅠ
다운로드 중인 만화가 있을 때에는 분 단위로 기다려야만 목록이 뜹니다...(물론 크롬 창이 열렸다 닫힌 뒤에) 만화보다 먼저 목록을 볼 수 있게 해주시면 감사하겠습니다.

**Comment by Dumbisted** [comment]
브라우저 창이 열리는 문제는 #853 을 참고해주세요.

**Comment by KurtBestor** [comment]
추가된 순서대로 작동해서 만약 4개 작업 다운로드 중이라면 선택 화 다운로드는 4개 작업 모두 DDoS Protection 우회 한 다음 처리돼요.
