### ISSUE TITLE
저장실패 에러

### ISSUE THREAD

**Issue by inparibe** [KurtBestor/Hitomi-Downloader#1724]
Traceback (most recent call last):
 Flie "hitomi_downloader_GUI", line 391, in write_config_safe
 Flie "hitomi_downloader_GUI", line 631, in write_config
 Flie "customWidget", line 849, in serialize
OverflowError: Could not reserve memory block

**Comment by KurtBestor** [comment]
목록에 작업이 몇 개 있나요?
