### ISSUE TITLE
마나모아 특정작품 다운로드 오류

### ISSUE THREAD

**Issue by orangespoons** [KurtBestor/Hitomi-Downloader#1725]
https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=1148
https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=1402
https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=7736
https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=9213
https://manamoa29.net/bbs/page.php?hid=manga_detail&manga_id=9373
이틀째 받아보려고 시도하는데 안받아지거나 일부만 받아지고 멈추네요.

Technical Preview 버전 사용중입니다.

**Comment by mita5549** [comment]
https://manamoa29.net/bbs/board.php?bo_table=manga&wr_id=264776
일부 에피소드의 이미지 파일이 유실 된 경우 같습니다! 
이건 마나모아쪽에서 해결 안되면 어쩔 수 없는 것 같아요ㅠㅠ

**Comment by mita5549** [comment]
https://jmana.net/book/%EC%A2%85%EB%A7%90%EC%97%90%20%EB%AD%90%ED%95%98%EC%84%B8%EC%9A%94%20%20%EB%B0%94%EC%81%98%EC%84%B8%EC%9A%94%20%20%EA%B5%AC%ED%95%B4%EC%A3%BC%EC%8B%A4%20%EC%88%98%20%EC%9E%88%EB%82%98%EC%9A%94

'종말에~~' 작품은 제이마나 쪽에서 빠른 속도로, 100% 잘 받아지는 것 같네요.
나머지 것들도 확인 해보세요~ :D
