### ISSUE TITLE
사이트 추가 요청입니다.

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#1728]
https://manga1000.com/
https://manga1001.com/

만화 원서를 볼 수 있는 사이트입니다.
혹시 지원하실 의향이 있으신지 궁금합니다. 
감사합니다.

**Comment by kingsangsu** [comment]
호두코믹스 주소 https://yajasoo.net/
늑대닷컴 주소 https://yajasoo.net/

**Comment by negativee** [comment]
웹툰 사이트 링크 모음 (Webtoon Site Links Collection)
https://navy-apple.github.io/tips/internet-mobile/webtoon-site
