### ISSUE TITLE
괜찮은 사이트 공유합니다

### ISSUE THREAD

**Issue by kingsangsu** [KurtBestor/Hitomi-Downloader#1730]
https://yajasoo.net/ 무료웹툰 무료성인 사이트 정보를 가장빠르게 공유하는
Yajasoo 사이트 입니다

**Comment by mirusu400** [comment]
#1728 에서 코멘트 올린것도 그렇고, 가입날짜도 그렇고, 이게 첫 이슈로 올린걸로 봐서 그냥 광고로 보입니다만...

**Comment by kingsangsu** [comment]
불편하시면 지울까요>??

2020년 3월 2일 (월) 오전 2:55, mirusu400 <notifications@github.com>님이 작성:
