### ISSUE TITLE
트위터 다운로드 크기

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#1731]
그 동안 몰랐는데 트위터 다운로드를 하면 이미지 크기가 
직접 다운로드한 것보다 다운그레이드 되서 진행되더군요.

첫번째 파일이 다운로더로 받은 이미지고
두번째 파일이 제가 직접 받은 이미지입니다.

둘 모두 같은 이미지를 다운로드 받은 거에요.

![주석 2020-03-02 031317](https://user-images.githubusercontent.com/47098778/75631159-d384ba80-5c33-11ea-8088-24a3e15eb8ae.png)
![주석 2020-03-02 031330](https://user-images.githubusercontent.com/47098778/75631161-d5e71480-5c33-11ea-8998-a5ccb2be7c7f.png)

웹에서 이미지 확대한 후 오른쪽 클릭으로 이미지를 저장한 것처럼 (두번째의 경우처럼)
다운로드 받을 순 없을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

![주석 2020-03-03 013102](https://user-images.githubusercontent.com/47098778/75696372-d7c1de00-5cee-11ea-874c-391b726ff4dc.png)
![주석 2020-03-03 013132](https://user-images.githubusercontent.com/47098778/75696381-da243800-5cee-11ea-82ab-eeab99d27eaa.png)

잘 작동합니다! 감사합니다~
