### ISSUE TITLE
테크니컬 프리뷰 버전이 바이러스가 발견됐다며 다운완료가 되질 않습니다

### ISSUE THREAD

**Issue by chtlucia** [KurtBestor/Hitomi-Downloader#1732]
https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

마나모아가 다운이 안되어 이슈란에 들어와봤는데

저랑 똑같은 증상인 분들이 많은거같아 기존 질문에 달린 답변글에 있던 프리뷰 버전을 받아서 실행해보려 했는데

약 1년가량 히토미 다운로더를 이용해오면서 이런적이 한번도 없었는데 
![캡처30](https://user-images.githubusercontent.com/41534575/75639518-896ff900-5c74-11ea-8146-808f96bfc5d9.PNG)
갑자기 크롬 하단 다운로드결과창이 이렇게 뜨네요... 왜 이러는 걸까요? 사용중인 백신은 윈도우 디펜더입니다

**Comment by colorfr** [comment]
저도 그렇군요.
![x다운로더 웜](https://user-images.githubusercontent.com/61679285/75650837-7708b600-5c9a-11ea-9dad-ce297823f60e.png)

**Comment by Yoon0618** [comment]
크롬 설정에서 세이프 브라우징을 끄시면 다운로드 되실겁니다

**Comment by colorfr** [comment]
> 크롬 설정에서 세이프 브라우징을 끄시면 다운로드 되실겁니다

저는 엣지로 다운받았습니다. 그리고 제 스크린샷은 윈도우 디펜더 검사 결과구요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/817#issuecomment-592402055

**Comment by chtlucia** [comment]
별 문제없는거군요. 답변 감사합니다
