### ISSUE TITLE
다운을 받다가 뉴토끼에세 ip정지를 당했는데요

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1735]
Invalid: [newtoki] https://newtoki52.com / webtoon / 97045 / %EB%B2%BD%EC%9D%84-%EC%A0%81%EC%8B%A0-%EC%97%AC%EC%9E%90?toon=%EC%99%84%EA%B2%B0%EC%9B%B9%ED%88%B0

version: 2.7h
platform: Windows-10-10.0.17763
order: 0
group: False
gal_num: https://newtoki52.com/webtoon/97045/%EB%B2%BD%EC%9D%84-%EC%A0%81%EC%8B%A0-%EC%97%AC%EC%9E%90?toon=%EC%99%84%EA%B2%B0%EC%9B%B9%ED%88%B0
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki52.com/webtoon/97045/%EB%B2%BD%EC%9D%84-%EC%A0%81%EC%8B%A0-%EC%97%AC%EC%9E%90?toon=%EC%99%84%EA%B2%B0%EC%9B%B9%ED%88%B0
valid: False
done: True
range: None
range_p: None
single: False
time: 1583242627.86 (Mar 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Failed to get soup
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "dynamic_module_2", line 71, in read
File "dynamic_module_2", line 52, in soup
File "dynamic_module_2", line 111, in get_soup
Exception: Failed to get soup

Invalid: fail=True
EOT: https://newtoki52.com/webtoon/97045/%EB%B2%BD%EC%9D%84-%EC%A0%81%EC%8B%A0-%EC%97%AC%EC%9E%90?toon=%EC%99%84%EA%B2%B0%EC%9B%B9%ED%88%B0

vpn우회를 해도 다운이 안되는데
ip 차단 때문이죠?
제가 위의 영어들을 봐도 뭔소린지 모르겠어서;;;

**Comment by qwertgb99** [comment]
대체사이트 툰코 에서 받아보세요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1676#issuecomment-595234415
