### ISSUE TITLE
LHscan 다운로드 안됩니다#2

### ISSUE THREAD

**Issue by JJJu9952** [KurtBestor/Hitomi-Downloader#1739]
몇화 내용해서 로그인 필요합니다 
다운로드 완전 막혔어요..

https://loveheaven.net/manga-meikyuu-black-company-raw.html

[ Login to View List of Chapters! ]
[ Login to View List of Chapters! ]
[ Login to View List of Chapters! ]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

LHScan은 로그인 쿠키를 넣어야 작동해요.
