### ISSUE TITLE
[기능추가] 다운로드 목록 정렬기능

### ISSUE THREAD

**Issue by whatohyou** [KurtBestor/Hitomi-Downloader#1743]
다운로더로 쭉 주소를 입력하다 보면 목록이 중복되는 경우가 많습니다.
중복된 것들을 제거하고 싶은데 숫자가 수백개를 넘어가면 찾는데 오래 걸립니다.

정렬버튼을 누르면 abc,가나다 순으로 이름이 정렬되어서 중복되는 것을 찾기 쉽도록 하면 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/609

**Comment by whatohyou** [comment]
감사합니다
