### ISSUE TITLE
다운로드 실패 test버전

### ISSUE THREAD

**Issue by whatohyou** [KurtBestor/Hitomi-Downloader#1744]
Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=1748

version: 2.7h (20-03-05 19:32:32 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748
dir: 
zip: 
type: manamoa
artist: 하가 소우켄
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748
valid: False
done: True
range: None
range_p: None
single: False
time: 1583447613.29 (Mar 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
dirFormat: [artist] title
회복술사의 재시작 1-1화 chapter:38976 seed:0 domains:121
회복술사의 재시작 1-2화 chapter:38969 seed:0 domains:121
회복술사의 재시작 2화 chapter:38963 seed:0 domains:121
회복술사의 재시작 2-2화 chapter:38957 seed:0 domains:121
회복술사의 재시작 3화 chapter:38951 seed:0 domains:121
회복술사의 재시작 3-2화 chapter:38945 seed:0 domains:121
회복술사의 재시작 4화 chapter:38939 seed:0 domains:121
회복술사의 재시작 4-2화 chapter:38935 seed:0 domains:121
회복술사의 재시작 5화 chapter:38931 seed:0 domains:121
회복술사의 재시작 5-2화 chapter:38927 seed:0 domains:121
회복술사의 재시작 6화 chapter:38922 seed:0 domains:121
회복술사의 재시작 6-2화 chapter:38915 seed:0 domains:121
회복술사의 재시작 7화 chapter:38908 seed:0 domains:121
회복술사의 재시작 7-2화 chapter:38905 seed:0 domains:121
회복술사의 재시작 8화 chapter:38899 seed:0 domains:121
회복술사의 재시작 8-2화 chapter:38893 seed:0 domains:121
회복술사의 재시작 9화 chapter:38887 seed:0 domains:121
회복술사의 재시작 9-2화 chapter:38881 seed:0 domains:121
회복술사의 재시작 10-1화 chapter:38875 seed:0 domains:121
회복술사의 재시작 10-2화 chapter:38869 seed:0 domains:121
회복술사의 재시작 11화 chapter:38864 seed:0 domains:121
회복술사의 재시작 11-2화 chapter:38858 seed:0 domains:121
회복술사의 재시작 12화 chapter:38852 seed:0 domains:121
회복술사의 재시작 12-2화 chapter:87799 seed:0 domains:121
회복술사의 재시작 13화 chapter:87802 seed:0 domains:121
회복술사의 재시작 13-2화 chapter:286723 seed:0 domains:121
회복술사의 재시작 14화 chapter:420725 seed:0 domains:121
회복술사의 재시작 14-2화 chapter:463297 seed:0 domains:121
회복술사의 재시작 14-3화 chapter:525022 seed:0 domains:121
회복술사의 재시작 15-1화 chapter:629415 seed:36100 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 회복술사의 재시작 15-1화
회복술사의 재시작 15-2화 chapter:740565 seed:379090 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 회복술사의 재시작 15-2화
회복술사의 재시작 16화 chapter:795385 seed:340020 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 회복술사의 재시작 16화
회복술사의 재시작 16-2화 chapter:878150 seed:326720 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 회복술사의 재시작 16-2화
회복술사의 재시작 16-3화 chapter:950176 seed:0 domains:121
회복술사의 재시작 17화 chapter:1234419 seed:0 domains:121
회복술사의 재시작 17-2화 chapter:1243556 seed:0 domains:121
회복술사의 재시작 17-3화 chapter:1285072 seed:0 domains:121
회복술사의 재시작 18화 chapter:1459868 seed:0 domains:121
회복술사의 재시작 18-2화 chapter:1533601 seed:0 domains:121
회복술사의 재시작 18-3화 chapter:1583201 seed:0 domains:121
회복술사의 재시작 19화 chapter:1777280 seed:0 domains:121
회복술사의 재시작 19-2화 chapter:1987410 seed:0 domains:121
회복술사의 재시작 20-1화 chapter:1987157 seed:0 domains:121
회복술사의 재시작 20-2화 chapter:2072486 seed:364060 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 회복술사의 재시작 20-2화
회복술사의 재시작 21-1화 chapter:2186940 seed:0 domains:121
fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 316, in get_imgs_page
File "manamoa_downloader", line 369, in get_imgs_page_legacy
File "manamoa_downloader", line 472, in read_html
File "downloader", line 372, in read_html
Exception: 502

stop
Traceback (most recent call last):
File "utils", line 814, in start
File "utils", line 864, in start_
File "manamoa_downloader", line 191, in read
File "manamoa_downloader", line 299, in get_imgs
File "constants", line 660, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 633, in wrapper
File "manamoa_downloader", line 316, in get_imgs_page
File "manamoa_downloader", line 369, in get_imgs_page_legacy
File "manamoa_downloader", line 472, in read_html
File "downloader", line 372, in read_html
Exception: 502

Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748

브라우저로 들어가서 보면 만화가 뜨는데 다운로더로 다운로드가 안됩니다.
다운로드가 안되는 부분만 안받아지는 것이 아니라 하드디스크에 폴더가 안생기고 tmp파일만 잔뜩 생깁니다.

ctrl+alt+c 눌러서 __import__('tempfile').gettempdir()입력하면
'c:\\users\\1\\appdata\\local\\temp'
라고 뜹니다.

**Comment by whatohyou** [comment]
21-2화는 지금보니 제 크롬브라우저로는 보이는데요. 해외라서 그런지도 모르겠습니다.
다운로드가 안되는 파일이있으면 그 파일만 제외하고 다운로드 되어야 되는데
폴더 자체가 안생기고 메인폴더에
tmp8919EA18_0021
이런 파일들만 잔뜩 생깁니다.
다 지우고 다시 해봐도 똑같네요.

**Comment by KurtBestor** [comment]
지금은 정상으로 돌아왔네요. tmp 파일은 작업 삭제하거나 프로그램 끄면 지워져요.
