### ISSUE TITLE
지금 마나 다운 해결 할 방법이 없나요...

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#1745]
디도스 방지 덕분에 다운이 안됩니다
거의 2주가 지났는데 정말 해결 할 방법이 없나요...
진짜로 하루 빨리 해결책이 나왔으면 좋겠습니다
아! 항상 잘 쓰고 있습니다

**Comment by whatohyou** [comment]
저는 되는데 일부 자료가 안되네요.

**Comment by geniussjt** [comment]
부럽네요ㅠㅠ
현재 버전과 테스트 버전 둘 다 다운이 안되서...
일단 운영자님의 믿고 기다려봐야죠^^

**Comment by KurtBestor** [comment]
테스트 버전에서 다운로드 시도해서: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
실패한 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by geniussjt** [comment]
읽는 중... https://manamoa30.net / bbs / board.php?bo_table=manga&wr_id=2893468

version: 2.7h (20-03-07 15:22:56 GMT+0)
platform: Windows-10-10.0.17763
order: 2
group: False
gal_num: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2893468
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2893468
valid: True
done: False
range: None
range_p: None
single: True
time: 1583662549.54 (Mar 8)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Solve protection
【chrome】 load...

1시간째 읽는 중..입니다
그냥 무한 로딩이네요..ㅠㅠ

**Comment by geniussjt** [comment]
추가로 Ctrl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용입니다
__import__('tempfile').gettempdir() 

'c:\\users\\admini~1\\appdata\\local\\temp'

이렇게 나옵니다ㅠ_ㅠ죄송해요
