### ISSUE TITLE
DPI 우회가 안됩니다 

### ISSUE THREAD

**Issue by thumbszilla** [KurtBestor/Hitomi-Downloader#1746]
![1](https://user-images.githubusercontent.com/61881764/76103476-1d471980-6015-11ea-9a2c-98813173f5f0.jpg)

처음 사용하는데 dpi우회가 안됩니다 ...

**Comment by mita5549** [comment]
설정 고급탭 아래에 dpi 우회가 켜져 있나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/546#issuecomment-464473160
