### ISSUE TITLE
히요비 대기자료 다운로드 불가능 문제

### ISSUE THREAD

**Issue by korm2cg** [KurtBestor/Hitomi-Downloader#1748]
히요비 자료 중 천만번대 자료가 다운로드되지 않는 문제가 있습니다

저번에는 됐었는데 또 막혔나봐요

예시) https://hiyobi.me/reader/10000289

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by korm2cg** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

정상적으로 작동합니다.

항상 감사드립니다.

ps 그런데 실행 파일 용량이 늘어나서 그런가 실행하는 시간이 이전보다 많이 느려졌습니다. 정식 업데이트에서는 조금 빨라질까요?
