### ISSUE TITLE
마나모아 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by hjm79** [KurtBestor/Hitomi-Downloader#1750]
현재 버전과 테스트 버전 둘 다 다운로드가 진행이 안됩니다.

dpi 설정 켜져있는 상황입니다.

아래는 로그입니다.

Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=463

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=463
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=463
valid: False
done: True
range: None
range_p: None
single: False
time: 1583570309.54 (Mar 7)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 160, in name
File "manamoa_downloader", line 146, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=463

**Comment by whatohyou** [comment]
지금 해보니 전 받아지는데 3921장 중에 그림3장이 안받아가지네요

**Comment by hjm79** [comment]
> 지금 해보니 전 받아지는데 3921장 중에 그림3장이 안받아가지네요

전 테스트버전과 현버전 다운이 다 안되는 상황인데 어떤 버전 사용하시나요??

**Comment by KurtBestor** [comment]
테스트 버전에서 다운로드 시도해서: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
실패한 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by hjm79** [comment]
> 테스트 버전에서 다운로드 시도해서: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
> 실패한 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

로그입니다.



Invalid: [manamoa] https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=1047&__cf_chl_jschl_tk__=7e333e295746b98dee097888806ec3ab87a63620-1583665503-0-AYqIt914VJEhRCTv1i4EmcSMWtX_j6hAkREqvBkM5zl4lBubgDzucV_lpLKqoU8ZwK36_d9jwonKHUfHem_KTMyR42S_T-RjOgfn6ExB7gyXk9B1kHPjRwuclWEtcmbaElSLJDUtf3kwAM257VcWy8HNmwbNDHpQA5IPZjAy7QEcc1WKHiTlG7aJMe9CepN3st_Du8UPteOvgUTcYrho1bGZbuH1l7b6lurp1CgvOiHqYJFG_e2IoL1rISNIQtCZY3QweNtnuRDx1jdiw7sVtw-Xsil6BGXiebr-t5ioOotIsFKem9Dvaf_207cwmDWbDaYF1hsA1rs1io0Wl6AOfnQ

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1047&__cf_chl_jschl_tk__=7e333e295746b98dee097888806ec3ab87a63620-1583665503-0-AYqIt914VJEhRCTv1i4EmcSMWtX_j6hAkREqvBkM5zl4lBubgDzucV_lpLKqoU8ZwK36_d9jwonKHUfHem_KTMyR42S_T-RjOgfn6ExB7gyXk9B1kHPjRwuclWEtcmbaElSLJDUtf3kwAM257VcWy8HNmwbNDHpQA5IPZjAy7QEcc1WKHiTlG7aJMe9CepN3st_Du8UPteOvgUTcYrho1bGZbuH1l7b6lurp1CgvOiHqYJFG_e2IoL1rISNIQtCZY3QweNtnuRDx1jdiw7sVtw-Xsil6BGXiebr-t5ioOotIsFKem9Dvaf_207cwmDWbDaYF1hsA1rs1io0Wl6AOfnQ
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1047&__cf_chl_jschl_tk__=7e333e295746b98dee097888806ec3ab87a63620-1583665503-0-AYqIt914VJEhRCTv1i4EmcSMWtX_j6hAkREqvBkM5zl4lBubgDzucV_lpLKqoU8ZwK36_d9jwonKHUfHem_KTMyR42S_T-RjOgfn6ExB7gyXk9B1kHPjRwuclWEtcmbaElSLJDUtf3kwAM257VcWy8HNmwbNDHpQA5IPZjAy7QEcc1WKHiTlG7aJMe9CepN3st_Du8UPteOvgUTcYrho1bGZbuH1l7b6lurp1CgvOiHqYJFG_e2IoL1rISNIQtCZY3QweNtnuRDx1jdiw7sVtw-Xsil6BGXiebr-t5ioOotIsFKem9Dvaf_207cwmDWbDaYF1hsA1rs1io0Wl6AOfnQ
valid: False
done: True
range: None
range_p: None
single: False
time: 1583665514.05 (Mar 8)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 160, in name
File "manamoa_downloader", line 146, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject


Invalid: fail=True
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1047&__cf_chl_jschl_tk__=7e333e295746b98dee097888806ec3ab87a63620-1583665503-0-AYqIt914VJEhRCTv1i4EmcSMWtX_j6hAkREqvBkM5zl4lBubgDzucV_lpLKqoU8ZwK36_d9jwonKHUfHem_KTMyR42S_T-RjOgfn6ExB7gyXk9B1kHPjRwuclWEtcmbaElSLJDUtf3kwAM257VcWy8HNmwbNDHpQA5IPZjAy7QEcc1WKHiTlG7aJMe9CepN3st_Du8UPteOvgUTcYrho1bGZbuH1l7b6lurp1CgvOiHqYJFG_e2IoL1rISNIQtCZY3QweNtnuRDx1jdiw7sVtw-Xsil6BGXiebr-t5ioOotIsFKem9Dvaf_207cwmDWbDaYF1hsA1rs1io0Wl6AOfnQ

**Comment by KurtBestor** [comment]
테스트 버전으로 해주세요.

**Comment by hjm79** [comment]
> 테스트 버전으로 해주세요.

기존 테스트버전 가지고 있어 같은 버전인줄 알고 사용했는데 아니네요! 
주신 테스트 버전으로 다운 잘됩니다.

[이토 쇼타] 친애하는 나에게 살의를 담아

version: 2.7h (20-03-07 15:22:56 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=9754
dir: F:\util\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[이토 쇼타] 친애하는 나에게 살의를 담아
zip: F:\util\hitomi_downloader_GUI_test\hitomi_downloaded_manamoa\[이토 쇼타] 친애하는 나에게 살의를 담아.zip
type: manamoa
artist: 이토 쇼타
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=9754
valid: True
done: True
range: None
range_p: None
single: False
time: 1583666397.48 (Mar 8)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
중략
EOT: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=9754
