### ISSUE TITLE
마나모아만 읽는중에서 안넘어갑니다

### ISSUE THREAD

**Issue by STOMLOG** [KurtBestor/Hitomi-Downloader#1757]
아무리 기다려봐도 읽는중에서 안넘어가네요
다른 사이트들은 잘 다운됩니다
혹시나 싶어서 크롬도 재설치도 해보고 
다운로더 테스트버전도 다시 받아보고, dpi도 키고 끄고 둘다 해봤는데도 안되네요
마나모아 주소를 30으로 바꿔도 똑같구요
크롬으로 마나모아는 잘 들어가지는 상황입니다
아래는 우클릭 - 정보 눌러서 나온 내용입니다

읽는 중... https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=7565

version: 2.7h (20-03-07 15:22:56 GMT+0)
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=7565
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=7565
valid: True
done: False
range: None
range_p: None
single: False
time: 1583672974.44 (Mar 8)
tags: []
goodbyedpi: False
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded

**Comment by geniussjt** [comment]
저랑 똑같네요ㅠㅠ
화이팅입니다!

**Comment by KurtBestor** [comment]
10분 이상 기다렸나요?

**Comment by geniussjt** [comment]
> 10분 이상 기다렸나요?
네 10분 기다렸습니다 근데 계속 무한 로딩이...
어제 테스트 버전는 무한 로딩이 한 2시간까지 기다리면 오류가 나옵니다
제 경우에는...요

**Comment by STOMLOG** [comment]
> 10분 이상 기다렸나요?

네 하루종일 켜놔도 저 상태에서 아무런 변화가 없습니다

**Comment by KurtBestor** [comment]
다음 링크 다운로드 되나요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/chromedriver.exe

**Comment by geniussjt** [comment]
> 다음 링크 다운로드 되나요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/chromedriver.exe
링크에 있는 프로그램 다운 받았는데요 이게 뭐예요
어떻게 사용해야 하나요?ㅠㅠ

**Comment by STOMLOG** [comment]
> 다음 링크 다운로드 되나요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/download/Utils/chromedriver.exe

네 링크 다운로드 됩니다

**Comment by KurtBestor** [comment]
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
__import__('chrome').get_local_version()
```

**Comment by geniussjt** [comment]
> Ctrl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용 보여주세요:
> __import__('chrome').get_local_version()

__import__('chrome').get_local_version() 

[Error 2] 
['C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe', 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe']
    Traceback (most recent call last):
      File "console\Console.py", line 153, in execSingle
      File "<string>", line 1, in <module>
      File "chrome.py", line 57, in get_local_version
    Exception: No Chrome
    

__import__('tempfile').gettempdir() 

'c:\\users\\admini~1\\appdata\\local\\temp'

chromedriver  프로그램 어떻게 사용하는지 정말 모르겠습니다..ㅠㅠ
2시간 동안 사용법 찾고 있는데..요 진짜로 모르겠습니다ㅠㅠ

**Comment by STOMLOG** [comment]
> Ctrl + Alt + C 눌러서 콘솔창 열고 아래 내용 입력하고 Enter 눌러서 나오는 내용 보여주세요:
> 
> ```
> __import__('chrome').get_local_version()
> ```

(80, 0, 3987, 132)
이렇게 나왔습니다

**Comment by KurtBestor** [comment]
크롬 브라우저 재설치해주세요.

**Comment by STOMLOG** [comment]
> 크롬 브라우저 재설치해주세요.

재설치해도  똑같습니다..

**Comment by KurtBestor** [comment]
다운로드 시도하고 `done: False` 부분이 `done: True` 될 때까지 기다려서 나온 작업 정보 보여주세요.

**Comment by STOMLOG** [comment]
> 다운로드 시도하고 `done: False` 부분이 `done: True` 될 때까지 기다려서 나온 작업 정보 보여주세요.

아무리 기다려봐도 본문 내용에서 변화가 없네요...2시간 지나서 봐도 done: False입니다..

**Comment by KurtBestor** [comment]
작업이 빨간색으로 변하긴 하나요?

**Comment by STOMLOG** [comment]
> 작업이 빨간색으로 변하긴 하나요?

밤새 켜놨는데도 빨간색으로 바뀌지도 않고 아무 변화가 없습니다
다른 사이트들은 잘 되는데 마나모아만 이러네요....

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
