### ISSUE TITLE
마나모아 목록에서 중복된 화 스킵 관련 문의

### ISSUE THREAD

**Issue by myusgun** [KurtBestor/Hitomi-Downloader#1758]
제가 올렸던건 아니지만, #740 이 stale 로 close된거 같아 문의 드립니다.

아래와 같은 경우,
1화부터 조금씩 바뀐 내용으로 다시 올라오고 있습니다.

https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12771
https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=12111

혹시 개선 방안이 있을지 문의 드립니다.

항상 감사히 사용하고 있습니다
고맙습니다 (_ _)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by myusgun** [comment]
(2) 로 표시되어 다운로드할 수 있도록 되었네요
다운로드도 정상 완료된 것 확인했습니다.
감사합니다 (_ _)
