### ISSUE TITLE
Twitter Links

### ISSUE THREAD

**Issue by BatmanPerbert** [KurtBestor/Hitomi-Downloader#1759]
#1759  Hello, I'm having these issues from the last update and I don't know why. I'm put the links of the twitter accounts but it doesn't read anything. And the problems it's just with Twitter links.

And well, just to thank you for creating this awesome application. Thank you for all the good job!

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1626
