### ISSUE TITLE
마나모아 다운로드 오류

### ISSUE THREAD

**Issue by festiland0810** [KurtBestor/Hitomi-Downloader#1761]
기존 문의글과 안내해주신 내용 참고하여 test 버전으로 다운로드 시도하여 보았으나 계속 아래와 같은 형식의 에러 메시지가 뜹니다. 

Invalid: [manamoa] https://manamoa30.net / bbs / board.php?bo_table=manga&wr_id=2900855

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2900855
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2900855
valid: False
done: True
range: None
range_p: None
single: True
time: 1583738379.85 (Mar 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 666, in __init__
File "manamoa_downloader", line 136, in init
File "manamoa_downloader", line 101, in get_title_page
AttributeError: 'NoneType' object has no attribute 'findAll'

Invalid: fail=True
stop
EOT: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2900855

**Comment by KurtBestor** [comment]
작업 정보 보니 최신 테스트 버전이 아니네요.

**Comment by festiland0810** [comment]
그렇군요. 그럼 최신 테스트 버전은 어디서 받을 수 있을까요? 번거롭게 해드려 죄송하지만 링크를 첨부해 주실 수 있으신지요? 그럼 그 버전으로 다운로드 시도해 보겠습니다.

**Comment by KurtBestor** [comment]
테스트 버전 받았던 곳에서 다시 받으세요.
