### ISSUE TITLE
마나모아 다운로드 불가

### ISSUE THREAD

**Issue by bbtan81** [KurtBestor/Hitomi-Downloader#1767]
최신 테스트 버전으로 했습니다.
읽는 중... https://manamoa30.net / bbs / board.php?bo_table=manga&wr_id=2913059

version: 2.7h (20-03-09 14:11:41 GMT+0)
platform: Windows-10-10.0.18362
order: -4
group: False
gal_num: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2913059
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2913059
valid: True
done: False
range: None
range_p: None
single: True
time: 1583891367.19 (Mar 11)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection

------------------------------------
읽는 중... https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=490&__cf_chl_jschl_tk__=ae5ab3ac6d53a6fb1e6ee6245ab5ec3a8f06b7ba-1583888269-0-AamkHAKwlBpwtDBJLiRdQF5ZN35yX81fEDcywD6PjQSPqTTgG16ndlPrLjEvuBoOFPGtk-a1cPYm3GOuURCVQ4aMthdIezgpstu1KRNWoFm-Q42Tg7YdnFjJUMIgWjQIsXvdU-7F-FlecubjSTIBpfrXEsVVN5VGBlj8b8F8KIQdfoYF6cs4gr0r_LY2N6KeqbQr5TDeWJtRrjJN1rzax75Odm3cIxdgXPcI5DS0aJA039eodDf7Wy-BdBCtshyGUPh2WXdScclu6bc_m7dFmqkcGsZdVKd-kNJpUe0LeEZ43UBniU-51f8zQfbtnQ23JRa0dLDNdZQt9zN1ECDoVYo

version: 2.7h (20-03-09 14:11:41 GMT+0)
platform: Windows-10-10.0.18362
order: -3
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=490&__cf_chl_jschl_tk__=ae5ab3ac6d53a6fb1e6ee6245ab5ec3a8f06b7ba-1583888269-0-AamkHAKwlBpwtDBJLiRdQF5ZN35yX81fEDcywD6PjQSPqTTgG16ndlPrLjEvuBoOFPGtk-a1cPYm3GOuURCVQ4aMthdIezgpstu1KRNWoFm-Q42Tg7YdnFjJUMIgWjQIsXvdU-7F-FlecubjSTIBpfrXEsVVN5VGBlj8b8F8KIQdfoYF6cs4gr0r_LY2N6KeqbQr5TDeWJtRrjJN1rzax75Odm3cIxdgXPcI5DS0aJA039eodDf7Wy-BdBCtshyGUPh2WXdScclu6bc_m7dFmqkcGsZdVKd-kNJpUe0LeEZ43UBniU-51f8zQfbtnQ23JRa0dLDNdZQt9zN1ECDoVYo
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=490&__cf_chl_jschl_tk__=ae5ab3ac6d53a6fb1e6ee6245ab5ec3a8f06b7ba-1583888269-0-AamkHAKwlBpwtDBJLiRdQF5ZN35yX81fEDcywD6PjQSPqTTgG16ndlPrLjEvuBoOFPGtk-a1cPYm3GOuURCVQ4aMthdIezgpstu1KRNWoFm-Q42Tg7YdnFjJUMIgWjQIsXvdU-7F-FlecubjSTIBpfrXEsVVN5VGBlj8b8F8KIQdfoYF6cs4gr0r_LY2N6KeqbQr5TDeWJtRrjJN1rzax75Odm3cIxdgXPcI5DS0aJA039eodDf7Wy-BdBCtshyGUPh2WXdScclu6bc_m7dFmqkcGsZdVKd-kNJpUe0LeEZ43UBniU-51f8zQfbtnQ23JRa0dLDNdZQt9zN1ECDoVYo
valid: True
done: False
range: None
range_p: None
single: False
time: 1583891241.27 (Mar 11)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection

**Comment by moonhole0512** [comment]
저도 다운로드 안되네요.

Invalid: [manamoa] https://manamoa.net / bbs / page.php?hid=manga_detail&manga_id=10147

version: 2.7h
platform: Windows-10-10.0.18362
order: 31
group: False
gal_num: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10147
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10147
valid: False
done: True
range: None
range_p: None
single: False
time: 1584012660.31 (Mar 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject

stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "manamoa_downloader", line 173, in read
File "manamoa_downloader", line 160, in name
File "manamoa_downloader", line 146, in soup
File "constants", line 616, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 589, in wrapper
File "manamoa_downloader", line 201, in get_soup
Exception: No subject


Invalid: fail=True
EOT: https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=10147

**Comment by KurtBestor** [comment]
@bbtan81 
![image](https://user-images.githubusercontent.com/14768120/76757835-bde2c980-67cb-11ea-94ee-63615dc22981.png)
재현할 수가 없네요.

@moonhole0512 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1750
