### ISSUE TITLE
이용자분들 마나모아 다운로드 다들 잘 되시나요?

### ISSUE THREAD

**Issue by chtlucia** [KurtBestor/Hitomi-Downloader#1770]
최신 테스트 버전 받아서 해보는데도 계속 읽는 중... 만 뜨고 다운로드 단계로 넘어갈 생각을 않네요

아침부터 켜놨는데 10시간이 넘도록 이러는거면 안되는게 맞는거죠? 설마 더 기다려야 하는건 아닌거같은데...

정보 보니까 이렇게 뜹니다

읽는 중... https://manamoa30.net / bbs / page.php?hid=manga_detail&manga_id=5204

version: 2.7h (20-03-09 14:11:41 GMT+0)
platform: Windows-10-10.0.18362
order: -2
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=5204
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=5204
valid: True
done: False
range: None
range_p: None
single: False
time: 1583900159.06 (Mar 11)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded

마나모아 다운로드 대체 언제쯤 정상적으로 진행할수 있는걸까요

거기 운영자양반은 자기도 불법사이트 운영하며 돈버는주제에 자기 사이트 자료 퍼가는건 왜 그렇게 기를 쓰고 막는건지... 정말 짜증나네요

**Comment by lducjswo** [comment]
ddos공격을 하두 당해서 저렇게 한다고 들었어요
전 안되다가 지금은 잘되는데 크롬 버젼문제였던걸로 기억합니다
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1727
이거 참고해보세요

**Comment by FoxSays** [comment]
크롬이 깔려 있는게 전제되는 거였나요;;;;

크롬 무거워서 포터블 버전으로만 쓰고있는데 C에 깔아야 하는군요. 이거 귀찮게 됐네요

**Comment by STOMLOG** [comment]
전 크롬쓰는데도 저상태에서 진행이 안되더군여....

**Comment by chtlucia** [comment]
> ddos공격을 하두 당해서 저렇게 한다고 들었어요
> 전 안되다가 지금은 잘되는데 크롬 버젼문제였던걸로 기억합니다
> #1727
> 이거 참고해보세요

들어가서 읽어보니 크롬 베타 쓰시는분이 크롬 정식판으로 옮긴뒤 잘 된다라고 하는 내용이던데

저는 이미 정식판인데도 안되는거라... 여전히 답이 안보이네요. 그래도 코멘트 감사합니다

**Comment by FoxSays** [comment]
크롬 깔아도 증상은 전혀 변함이 없었습니다.

**Comment by LimGunz** [comment]
저는 테스트버전으로 잘되네요
정식버전은 다운 안됐는데

**Comment by mita5549** [comment]
크롬 버전 80.0.3987.132(공식 빌드) (64비트)
 다운로더는 일반판, 테스트판 양쪽 모두 새로 다운로드 해서 테스트 해봤습니다.
 정상 작동 확인 되었습니다.
![정상](https://user-images.githubusercontent.com/45882353/76618118-1d8e6a00-656b-11ea-950c-1624599f855a.png)

 참고 바랍니다. : )

**Comment by Tiyore** [comment]
저번주까지 잘되던 사람인데 윗분처럼 안됩니다. 
크롬  80.0.3987.132(공식 빌드) (64비트)이고 테스트 버전, 정식버전 갑자기 다 안되는데 뭔가 다른 이슈가 있는것 같습니다

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/76760928-eff72a00-67d1-11ea-9415-f840007346ed.png)

재현할 수가 없네요.
