### ISSUE TITLE
유튜브 hdr 다운로드는 안되나요?

### ISSUE THREAD

**Issue by kirakirasensation** [KurtBestor/Hitomi-Downloader#1771]
hdr 영상들이 있는데 이것들은 다운로드 할 수 있는 방법이 없을까요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by kirakirasensation** [comment]
FINAL FANTASY VII Remake - First 45 Minutes Gameplay 4K HDR (PS4 Pro)

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=DGvIpNGj1hs
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: Shirrako
url: https://www.youtube.com/watch?v=DGvIpNGj1hs
valid: True
done: True
range: None
range_p: None
single: True
time: 1584400907.77 (Mar 17)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_youtube\FINAL FANTASY VII Remake - First 45 Minutes Gameplay 4K HDR (PS4 Pro).mp4


[URLs]
[0001] https://r4---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1584422507&ei=CwpwXqLnLZi1gAPw8ougCA&ip=210.101.213.253&id=o-AOJwiUdyPHLiYu-gxFnpi2SSt3sDqYFIs7qfSYlaZaQs&itag=315&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C271%2C278%2C298%2C299%2C302%2C303%2C308%2C313%2C315%2C330%2C331%2C332%2C333%2C334%2C335%2C336%2C337&source=youtube&requiressl=yes&mh=Qj&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3beln7r&ms=au%2Conr&mv=m&mvi=3&pcm2cms=yes&pl=19&initcwndbps=1372500&vprv=1&mime=video%2Fwebm&gir=yes&clen=7770556257&dur=2616.280&lmt=1583336198080747&mt=1584400829&fvip=4&keepalive=yes&fexp=23842630&c=WEB&txp=5431232&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ADKhkGMwRQIhAOIA8_7f8lLP2LAkADGctJP849vZIca7oiWHS65ltZyOAiAvrIM1j4h7Jo44EQy0lXqYSB8jLPNvJ25N85CeecUPuQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAL9v9o5xxAfI290_6tYKOY7f-upso5OA6rBPdsa7-gylAiAjw4PlBgB22N5jsg50JDIpcYvhXRN-NbM2RUJZBqZVng%3D%3D&ratebypass=yes


[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][0fps][None] webm None ─ 278 - 256x144 (144p)
[144p][0fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][0fps][None] webm None ─ 242 - 426x240 (240p)
[240p][0fps][None] mp4 None ─ 133 - 426x240 (240p)
[144p][60fps][None] webm None ─ 330 - 256x144 (144p60 HDR)
[360p][0fps][None] webm None ─ 243 - 640x360 (360p)
[240p][60fps][None] webm None ─ 331 - 426x240 (240p60 HDR)
[360p][0fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][0fps][None] webm None ─ 244 - 854x480 (480p)
[360p][60fps][None] webm None ─ 332 - 640x360 (360p60 HDR)
[480p][0fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][0fps][None] webm None ─ 247 - 1280x720 (720p)
[480p][60fps][None] webm None ─ 333 - 854x480 (480p60 HDR)
[720p][0fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][60fps][None] webm None ─ 302 - 1280x720 (720p60)
[1080p][0fps][None] webm None ─ 248 - 1920x1080 (1080p)
[720p][60fps][None] mp4 None ─ 298 - 1280x720 (720p60)
[1080p][0fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[1080p][60fps][None] webm None ─ 303 - 1920x1080 (1080p60)
[720p][60fps][None] webm None ─ 334 - 1280x720 (720p60 HDR)
[1080p][60fps][None] mp4 None ─ 299 - 1920x1080 (1080p60)
[1080p][60fps][None] webm None ─ 335 - 1920x1080 (1080p60 HDR)
[1440p][0fps][None] webm None ─ 271 - 2560x1440 (1440p)
[1440p][60fps][None] webm None ─ 308 - 2560x1440 (1440p60)
[1440p][60fps][None] webm None ─ 336 - 2560x1440 (1440p60 HDR)
[2160p][0fps][None] webm None ─ 313 - 3840x2160 (2160p)
[2160p][60fps][None] webm None ─ 315 - 3840x2160 (2160p60)
[2160p][60fps][None] webm None ─ 337 - 3840x2160 (2160p60 HDR)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)


# stream_final <youtube_dl_test.Video object at 0x17E7F170> 313 - 3840x2160 (2160p) 2160p webm None 0fps
# stream_final <youtube_dl_test.Video object at 0x17E7F370> 315 - 3840x2160 (2160p60) 2160p webm None 60fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

# stream_audio 128kbps m4a mp4a.40.2
https://r4---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1584422507&ei=CwpwXqLnLZi1gAPw8ougCA&ip=210.101.213.253&id=o-AOJwiUdyPHLiYu-gxFnpi2SSt3sDqYFIs7qfSYlaZaQs&itag=140&source=youtube&requiressl=yes&mh=Qj&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3beln7r&ms=au%2Conr&mv=m&mvi=3&pcm2cms=yes&pl=19&initcwndbps=1372500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=42343181&dur=2616.331&lmt=1583296202866548&mt=1584400829&fvip=4&keepalive=yes&fexp=23842630&c=WEB&txp=5431232&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ADKhkGMwRQIgDvzO3WJoA4tvTrefCMSAW_UFtO2E1DU_yj0XB1qGxIcCIQCOcfB4jaCek0mQ4y8wecYA_rkTazj8BfhoMBS77V61gA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAL9v9o5xxAfI290_6tYKOY7f-upso5OA6rBPdsa7-gylAiAjw4PlBgB22N5jsg50JDIpcYvhXRN-NbM2RUJZBqZVng%3D%3D&ratebypass=yes
Resolution: 2160p
Codec: vp9 / None
Abr: None
Subtype: webm
FPS: 60

stop
Download audio: https://r4---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1584422507&ei=CwpwXqLnLZi1gAPw8ougCA&ip=210.101.213.253&id=o-AOJwiUdyPHLiYu-gxFnpi2SSt3sDqYFIs7qfSYlaZaQs&itag=140&source=youtube&requiressl=yes&mh=Qj&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-i3beln7r&ms=au%2Conr&mv=m&mvi=3&pcm2cms=yes&pl=19&initcwndbps=1372500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=42343181&dur=2616.331&lmt=1583296202866548&mt=1584400829&fvip=4&keepalive=yes&fexp=23842630&c=WEB&txp=5431232&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ADKhkGMwRQIgDvzO3WJoA4tvTrefCMSAW_UFtO2E1DU_yj0XB1qGxIcCIQCOcfB4jaCek0mQ4y8wecYA_rkTazj8BfhoMBS77V61gA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=ABSNjpQwRQIhAL9v9o5xxAfI290_6tYKOY7f-upso5OA6rBPdsa7-gylAiAjw4PlBgB22N5jsg50JDIpcYvhXRN-NbM2RUJZBqZVng%3D%3D&ratebypass=yes
Convert: C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\FINAL FANTASY VII Remake - First 45 Minutes Gameplay 4K HDR (PS4 Pro).webm
rename (1): hitomi_downloaded_youtube\B56D80B4_a.tmp -> C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp447C2D4C_a.weba
rename (1): C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\FINAL FANTASY VII Remake - First 45 Minutes Gameplay 4K HDR (PS4 Pro).webm -> C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp447C2D4C_v.webm
-i tmp447C2D4C_v.webm -i tmp447C2D4C_a.weba -c copy -strict experimental -preset ultrafast tmp447C2D4C_o.mp4
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
Input #0, matroska,webm, from 'tmp447C2D4C_v.webm':
Metadata:
encoder : google/video-file
Duration: 00:43:36.28, start: 0.000000, bitrate: 23760 kb/s
Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp447C2D4C_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-03-04T04:27:52.000000Z
Duration: 00:43:36.33, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
Metadata:
creation_time : 2020-03-04T04:27:52.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp447C2D4C_o.mp4':
Metadata:
encoder : Lavf58.20.100
Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 16k tbn, 1k tbc (default)
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 0 kb/s (default)
Metadata:
creation_time : 2020-03-04T04:27:52.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 3871 fps=0.0 q=-1.0 size= 133376kB time=00:01:04.56 bitrate=16922.7kbits/s speed= 128x 
frame= 4898 fps=4874 q=-1.0 size= 179456kB time=00:01:21.71 bitrate=17991.5kbits/s speed=81.3x 
frame= 5676 fps=3754 q=-1.0 size= 216320kB time=00:01:34.69 bitrate=18714.5kbits/s speed=62.6x 
frame= 6297 fps=3129 q=-1.0 size= 249600kB time=00:01:45.03 bitrate=19466.5kbits/s speed=52.2x 
frame= 7350 fps=2922 q=-1.0 size= 305920kB time=00:02:02.62 bitrate=20437.2kbits/s speed=48.7x 
frame= 7977 fps=2640 q=-1.0 size= 337408kB time=00:02:13.06 bitrate=20772.0kbits/s speed= 44x 
frame= 8562 fps=2428 q=-1.0 size= 367616kB time=00:02:22.84 bitrate=21081.8kbits/s speed=40.5x 
frame= 9435 fps=2343 q=-1.0 size= 409856kB time=00:02:37.39 bitrate=21332.6kbits/s speed=39.1x 
frame=11377 fps=2507 q=-1.0 size= 497664kB time=00:03:09.79 bitrate=21479.8kbits/s speed=41.8x 
frame=12326 fps=2445 q=-1.0 size= 539136kB time=00:03:25.63 bitrate=21477.8kbits/s speed=40.8x 
frame=13015 fps=2348 q=-1.0 size= 573440kB time=00:03:37.11 bitrate=21636.4kbits/s speed=39.2x 
frame=13567 fps=2245 q=-1.0 size= 606720kB time=00:03:46.34 bitrate=21958.4kbits/s speed=37.5x 
frame=14349 fps=2193 q=-1.0 size= 645376kB time=00:03:59.37 bitrate=22086.4kbits/s speed=36.6x 
frame=15749 fps=2236 q=-1.0 size= 718080kB time=00:04:22.73 bitrate=22389.6kbits/s speed=37.3x 
frame=16745 fps=2220 q=-1.0 size= 760576kB time=00:04:39.35 bitrate=22303.3kbits/s speed= 37x 
frame=17844 fps=2218 q=-1.0 size= 814592kB time=00:04:57.70 bitrate=22415.4kbits/s speed= 37x 
frame=19144 fps=2239 q=-1.0 size= 883200kB time=00:05:19.39 bitrate=22653.1kbits/s speed=37.4x 
frame=20142 fps=2225 q=-1.0 size= 937216kB time=00:05:36.03 bitrate=22847.6kbits/s speed=37.1x 
frame=22274 fps=2332 q=-1.0 size= 1003776kB time=00:06:11.58 bitrate=22129.1kbits/s speed=38.9x 
frame=23627 fps=2350 q=-1.0 size= 1056000kB time=00:06:34.18 bitrate=21946.1kbits/s speed=39.2x 
frame=24885 fps=2358 q=-1.0 size= 1093120kB time=00:06:55.14 bitrate=21570.2kbits/s speed=39.3x 
frame=26978 fps=2440 q=-1.0 size= 1172992kB time=00:07:30.06 bitrate=21350.5kbits/s speed=40.7x 
frame=27575 fps=2385 q=-1.0 size= 1206784kB time=00:07:40.03 bitrate=21489.7kbits/s speed=39.8x 
frame=28472 fps=2359 q=-1.0 size= 1253888kB time=00:07:55.01 bitrate=21624.5kbits/s speed=39.4x 
frame=30226 fps=2402 q=-1.0 size= 1340160kB time=00:08:24.26 bitrate=21771.4kbits/s speed=40.1x 
frame=31010 fps=2367 q=-1.0 size= 1381888kB time=00:08:37.33 bitrate=21882.2kbits/s speed=39.5x 
frame=31925 fps=2346 q=-1.0 size= 1429248kB time=00:08:52.61 bitrate=21982.7kbits/s speed=39.1x 
frame=33168 fps=2351 q=-1.0 size= 1495808kB time=00:09:13.35 bitrate=22144.3kbits/s speed=39.2x 
frame=34059 fps=2331 q=-1.0 size= 1543680kB time=00:09:28.21 bitrate=22255.3kbits/s speed=38.9x 
frame=35083 fps=2322 q=-1.0 size= 1599488kB time=00:09:45.28 bitrate=22387.4kbits/s speed=38.7x 
frame=36142 fps=2315 q=-1.0 size= 1651456kB time=00:10:02.95 bitrate=22437.5kbits/s speed=38.6x 
frame=37069 fps=2300 q=-1.0 size= 1697280kB time=00:10:18.44 bitrate=22482.6kbits/s speed=38.4x 
frame=38763 fps=2333 q=-1.0 size= 1774080kB time=00:10:46.69 bitrate=22473.0kbits/s speed=38.9x 
frame=39841 fps=2327 q=-1.0 size= 1826048kB time=00:11:04.67 bitrate=22505.8kbits/s speed=38.8x 
frame=40840 fps=2318 q=-1.0 size= 1870848kB time=00:11:21.34 bitrate=22493.8kbits/s speed=38.7x 
frame=42013 fps=2319 q=-1.0 size= 1932544kB time=00:11:40.91 bitrate=22586.7kbits/s speed=38.7x 
frame=42626 fps=2289 q=-1.0 size= 1965824kB time=00:11:51.12 bitrate=22645.8kbits/s speed=38.2x 
frame=44545 fps=2329 q=-1.0 size= 2056960kB time=00:12:23.15 bitrate=22674.4kbits/s speed=38.9x 
frame=45955 fps=2342 q=-1.0 size= 2108672kB time=00:12:46.67 bitrate=22531.3kbits/s speed=39.1x 
frame=47173 fps=2343 q=-1.0 size= 2155264kB time=00:13:06.99 bitrate=22434.6kbits/s speed=39.1x 
frame=49093 fps=2380 q=-1.0 size= 2237696kB time=00:13:39.01 bitrate=22381.9kbits/s speed=39.7x 
frame=50001 fps=2366 q=-1.0 size= 2273792kB time=00:13:54.17 bitrate=22329.7kbits/s speed=39.5x 
frame=51269 fps=2370 q=-1.0 size= 2319872kB time=00:14:15.33 bitrate=22218.8kbits/s speed=39.5x 
frame=53464 fps=2416 q=-1.0 size= 2403328kB time=00:14:51.94 bitrate=22073.1kbits/s speed=40.3x 
frame=54549 fps=2410 q=-1.0 size= 2449664kB time=00:15:10.04 bitrate=22051.3kbits/s speed=40.2x 
frame=55844 fps=2414 q=-1.0 size= 2497536kB time=00:15:31.64 bitrate=21960.9kbits/s speed=40.3x 
frame=57073 fps=2414 q=-1.0 size= 2560000kB time=00:15:52.15 bitrate=22025.3kbits/s speed=40.3x 
frame=57878 fps=2398 q=-1.0 size= 2603264kB time=00:16:05.60 bitrate=22085.6kbits/s speed= 40x 
frame=58999 fps=2394 q=-1.0 size= 2663424kB time=00:16:24.28 bitrate=22167.1kbits/s speed=39.9x 
frame=60123 fps=2391 q=-1.0 size= 2723584kB time=00:16:43.03 bitrate=22244.1kbits/s speed=39.9x 
frame=61130 fps=2384 q=-1.0 size= 2770432kB time=00:16:59.83 bitrate=22254.0kbits/s speed=39.8x 
frame=62655 fps=2397 q=-1.0 size= 2850816kB time=00:17:25.27 bitrate=22342.3kbits/s speed= 40x 
frame=63510 fps=2383 q=-1.0 size= 2896896kB time=00:17:39.54 bitrate=22397.8kbits/s speed=39.8x 
frame=64590 fps=2379 q=-1.0 size= 2954496kB time=00:17:57.56 bitrate=22461.1kbits/s speed=39.7x 
frame=65853 fps=2382 q=-1.0 size= 3021056kB time=00:18:18.65 bitrate=22526.2kbits/s speed=39.7x 
frame=66814 fps=2373 q=-1.0 size= 3073024kB time=00:18:34.67 bitrate=22584.4kbits/s speed=39.6x 
frame=68129 fps=2378 q=-1.0 size= 3142400kB time=00:18:56.61 bitrate=22648.4kbits/s speed=39.7x 
frame=69273 fps=2375 q=-1.0 size= 3205120kB time=00:19:15.70 bitrate=22718.9kbits/s speed=39.6x 
frame=70086 fps=2362 q=-1.0 size= 3249408kB time=00:19:29.26 bitrate=22765.7kbits/s speed=39.4x 
frame=71510 fps=2370 q=-1.0 size= 3318528kB time=00:19:53.00 bitrate=22787.3kbits/s speed=39.5x 
frame=72490 fps=2364 q=-1.0 size= 3371776kB time=00:20:09.35 bitrate=22839.9kbits/s speed=39.4x 
frame=73546 fps=2360 q=-1.0 size= 3423744kB time=00:20:26.98 bitrate=22858.7kbits/s speed=39.4x 
frame=74760 fps=2360 q=-1.0 size= 3488768kB time=00:20:47.23 bitrate=22914.6kbits/s speed=39.4x 
frame=75418 fps=2344 q=-1.0 size= 3524096kB time=00:20:58.20 bitrate=22944.9kbits/s speed=39.1x 
frame=77055 fps=2358 q=-1.0 size= 3611904kB time=00:21:25.51 bitrate=23017.0kbits/s speed=39.3x 
frame=77959 fps=2350 q=-1.0 size= 3657984kB time=00:21:40.59 bitrate=23040.3kbits/s speed=39.2x 
frame=78733 fps=2338 q=-1.0 size= 3701760kB time=00:21:53.51 bitrate=23086.8kbits/s speed= 39x 
frame=80568 fps=2357 q=-1.0 size= 3785216kB time=00:22:24.12 bitrate=23069.6kbits/s speed=39.3x 
frame=81751 fps=2357 q=-1.0 size= 3831040kB time=00:22:43.87 bitrate=23010.9kbits/s speed=39.3x 
frame=83144 fps=2363 q=-1.0 size= 3880192kB time=00:23:07.11 bitrate=22915.6kbits/s speed=39.4x 
frame=84540 fps=2369 q=-1.0 size= 3943424kB time=00:23:30.40 bitrate=22904.5kbits/s speed=39.5x 
frame=85914 fps=2374 q=-1.0 size= 4002048kB time=00:23:53.31 bitrate=22873.4kbits/s speed=39.6x 
frame=86804 fps=2366 q=-1.0 size= 4050688kB time=00:24:08.16 bitrate=22914.0kbits/s speed=39.5x 
frame=88081 fps=2368 q=-1.0 size= 4117248kB time=00:24:29.46 bitrate=22952.9kbits/s speed=39.5x 
frame=89012 fps=2361 q=-1.0 size= 4167424kB time=00:24:45.00 bitrate=22989.6kbits/s speed=39.4x 
frame=90163 fps=2360 q=-1.0 size= 4230656kB time=00:25:04.20 bitrate=23040.5kbits/s speed=39.4x 
frame=91254 fps=2358 q=-1.0 size= 4288256kB time=00:25:22.41 bitrate=23074.8kbits/s speed=39.3x 
frame=92181 fps=2351 q=-1.0 size= 4338688kB time=00:25:37.87 bitrate=23111.5kbits/s speed=39.2x 
frame=93446 fps=2353 q=-1.0 size= 4404480kB time=00:25:58.98 bitrate=23144.2kbits/s speed=39.3x 
frame=94257 fps=2344 q=-1.0 size= 4448256kB time=00:26:12.52 bitrate=23173.0kbits/s speed=39.1x 
frame=95322 fps=2341 q=-1.0 size= 4504064kB time=00:26:30.28 bitrate=23201.6kbits/s speed=39.1x 
frame=96983 fps=2353 q=-1.0 size= 4589824kB time=00:26:57.98 bitrate=23238.7kbits/s speed=39.3x 
frame=97738 fps=2343 q=-1.0 size= 4631296kB time=00:27:10.59 bitrate=23267.3kbits/s speed=39.1x 
frame=98909 fps=2342 q=-1.0 size= 4686592kB time=00:27:30.11 bitrate=23266.6kbits/s speed=39.1x 
frame=100197 fps=2345 q=-1.0 size= 4757248kB time=00:27:51.60 bitrate=23313.8kbits/s speed=39.1x 
frame=101043 fps=2338 q=-1.0 size= 4801024kB time=00:28:05.72 bitrate=23331.2kbits/s speed= 39x 
frame=102306 fps=2340 q=-1.0 size= 4868352kB time=00:28:26.80 bitrate=23366.2kbits/s speed= 39x 
frame=103317 fps=2335 q=-1.0 size= 4922112kB time=00:28:43.66 bitrate=23393.2kbits/s speed= 39x 
frame=104256 fps=2330 q=-1.0 size= 4971008kB time=00:28:59.32 bitrate=23412.9kbits/s speed=38.9x 
frame=105518 fps=2332 q=-1.0 size= 5039104kB time=00:29:20.39 bitrate=23449.4kbits/s speed=38.9x 
frame=106352 fps=2325 q=-1.0 size= 5083392kB time=00:29:34.30 bitrate=23470.1kbits/s speed=38.8x 
frame=107327 fps=2321 q=-1.0 size= 5136128kB time=00:29:50.56 bitrate=23498.3kbits/s speed=38.7x 
frame=108596 fps=2323 q=-1.0 size= 5202432kB time=00:30:11.72 bitrate=23523.6kbits/s speed=38.8x 
frame=109596 fps=2319 q=-1.0 size= 5253888kB time=00:30:28.43 bitrate=23539.2kbits/s speed=38.7x 
frame=110791 fps=2320 q=-1.0 size= 5318144kB time=00:30:48.35 bitrate=23570.3kbits/s speed=38.7x 
frame=111723 fps=2315 q=-1.0 size= 5368576kB time=00:31:03.91 bitrate=23595.2kbits/s speed=38.6x 
frame=112566 fps=2309 q=-1.0 size= 5414144kB time=00:31:17.96 bitrate=23617.5kbits/s speed=38.5x 
frame=113882 fps=2312 q=-1.0 size= 5484288kB time=00:31:39.91 bitrate=23647.0kbits/s speed=38.6x 
frame=114889 fps=2308 q=-1.0 size= 5538560kB time=00:31:56.73 bitrate=23671.4kbits/s speed=38.5x 
frame=115651 fps=2300 q=-1.0 size= 5579008kB time=00:32:09.42 bitrate=23687.5kbits/s speed=38.4x 
frame=117124 fps=2307 q=-1.0 size= 5658624kB time=00:32:34.00 bitrate=23723.3kbits/s speed=38.5x 
frame=117954 fps=2300 q=-1.0 size= 5704448kB time=00:32:47.86 bitrate=23746.9kbits/s speed=38.4x 
frame=118986 fps=2298 q=-1.0 size= 5758464kB time=00:33:05.06 bitrate=23764.1kbits/s speed=38.3x 
frame=120201 fps=2299 q=-1.0 size= 5824512kB time=00:33:25.33 bitrate=23793.7kbits/s speed=38.4x 
frame=121041 fps=2293 q=-1.0 size= 5870080kB time=00:33:39.36 bitrate=23813.2kbits/s speed=38.3x 
frame=122498 fps=2299 q=-1.0 size= 5944320kB time=00:34:03.65 bitrate=23827.8kbits/s speed=38.4x 
frame=123464 fps=2295 q=-1.0 size= 5997056kB time=00:34:19.79 bitrate=23850.9kbits/s speed=38.3x 
frame=124462 fps=2292 q=-1.0 size= 6049280kB time=00:34:36.44 bitrate=23865.7kbits/s speed=38.2x 
frame=125637 fps=2293 q=-1.0 size= 6114048kB time=00:34:56.04 bitrate=23895.6kbits/s speed=38.3x 
frame=126493 fps=2287 q=-1.0 size= 6156800kB time=00:35:10.32 bitrate=23899.9kbits/s speed=38.2x 
frame=127446 fps=2284 q=-1.0 size= 6204416kB time=00:35:26.22 bitrate=23904.6kbits/s speed=38.1x 
frame=128845 fps=2288 q=-1.0 size= 6279168kB time=00:35:49.54 bitrate=23930.1kbits/s speed=38.2x 
frame=129691 fps=2283 q=-1.0 size= 6323456kB time=00:36:03.68 bitrate=23941.5kbits/s speed=38.1x 
frame=131171 fps=2289 q=-1.0 size= 6404096kB time=00:36:28.35 bitrate=23973.4kbits/s speed=38.2x 
frame=131899 fps=2282 q=-1.0 size= 6443008kB time=00:36:40.50 bitrate=23985.9kbits/s speed=38.1x 
frame=132715 fps=2276 q=-1.0 size= 6488320kB time=00:36:54.11 bitrate=24006.1kbits/s speed= 38x 
frame=134054 fps=2279 q=-1.0 size= 6559488kB time=00:37:16.45 bitrate=24027.0kbits/s speed= 38x 
frame=135050 fps=2277 q=-1.0 size= 6614016kB time=00:37:33.07 bitrate=24048.0kbits/s speed= 38x 
frame=135843 fps=2271 q=-1.0 size= 6655744kB time=00:37:46.29 bitrate=24058.6kbits/s speed=37.9x 
frame=137128 fps=2273 q=-1.0 size= 6724864kB time=00:38:07.74 bitrate=24080.5kbits/s speed=37.9x 
frame=137985 fps=2269 q=-1.0 size= 6771712kB time=00:38:22.03 bitrate=24097.8kbits/s speed=37.9x 
frame=138931 fps=2266 q=-1.0 size= 6820352kB time=00:38:37.83 bitrate=24105.4kbits/s speed=37.8x 
frame=140090 fps=2266 q=-1.0 size= 6884352kB time=00:38:57.15 bitrate=24130.4kbits/s speed=37.8x 
frame=140987 fps=2262 q=-1.0 size= 6932992kB time=00:39:12.13 bitrate=24146.2kbits/s speed=37.7x 
frame=142161 fps=2263 q=-1.0 size= 6996224kB time=00:39:31.70 bitrate=24165.3kbits/s speed=37.8x 
frame=143193 fps=2261 q=-1.0 size= 7041024kB time=00:39:48.92 bitrate=24144.8kbits/s speed=37.7x 
frame=144575 fps=2265 q=-1.0 size= 7108096kB time=00:40:11.97 bitrate=24141.8kbits/s speed=37.8x 
frame=145854 fps=2267 q=-1.0 size= 7165696kB time=00:40:33.33 bitrate=24123.8kbits/s speed=37.8x 
frame=146797 fps=2264 q=-1.0 size= 7193856kB time=00:40:49.04 bitrate=24063.3kbits/s speed=37.8x 
frame=148340 fps=2270 q=-1.0 size= 7268352kB time=00:41:14.78 bitrate=24059.6kbits/s speed=37.9x 
frame=150144 fps=2280 q=-1.0 size= 7355392kB time=00:41:44.89 bitrate=24055.0kbits/s speed= 38x 
frame=151095 fps=2278 q=-1.0 size= 7398400kB time=00:42:00.75 bitrate=24043.5kbits/s speed= 38x 
frame=151948 fps=2273 q=-1.0 size= 7438592kB time=00:42:14.98 bitrate=24038.4kbits/s speed=37.9x 
frame=153572 fps=2280 q=-1.0 size= 7520000kB time=00:42:42.07 bitrate=24044.5kbits/s speed= 38x 
frame=154648 fps=2279 q=-1.0 size= 7559680kB time=00:43:00.02 bitrate=24003.2kbits/s speed= 38x 
frame=156820 fps=2295 q=-1.0 Lsize= 7632738kB time=00:43:36.30 bitrate=23899.1kbits/s speed=38.3x 
video:7587216kB audio:40880kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.060856%

Convert success: True
rename (1): C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp447C2D4C_o.mp4 -> C:\Users\user\Downloads\hitomi_downloader_GUI\hitomi_downloaded_youtube\FINAL FANTASY VII Remake - First 45 Minutes Gameplay 4K HDR (PS4 Pro).webm
rename ext .webm --> .mp4
EOT: https://www.youtube.com/watch?v=DGvIpNGj1hs

**Comment by KurtBestor** [comment]
다운로드 된 것 아닌가요?
