### ISSUE TITLE
중복항목 체크하는기능 부탁드려요,,,

### ISSUE THREAD

**Issue by raken86** [KurtBestor/Hitomi-Downloader#1775]
좋은 프로그램 잘쓰고잇습니다,

그런데, 기능하나 추가 건의드릴려구요,,

트윗,픽시브,등등의 자료 다운로드후

깜박하고 동일한거 추가하면 기존 자료에 잇는거인지

검색해서 중복처리 안되게 해주는 기능있으면 좋을거같습니다,

확인 부탁드립니다, 감사합니다,

**Comment by Yoon0618** [comment]
깔때기 아이콘 누르시고 dup: 입력하시면 됩니다

**Comment by raken86** [comment]
> 
> 
> 깔때기 아이콘 누르시고 dup: 입력하시면 됩니다

알려주신 필터기능으로 중복체크는 확인햇는데,

프로그램 자체에서 신규링크 추가시 중복일경우,

기존 다운목록?으로 옴겨주는? 그런기능 없을까요??
