### ISSUE TITLE
마나모아에서 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by chunyuhwa** [KurtBestor/Hitomi-Downloader#1778]
마나모아에 해당작품에 36-1화에서 다음으로 넘어가질 않습니다.

-------------------------------------------------------------------------------------------------------------

읽는 중... [N／A][Korean] 이상적인 기둥서방 생활 / 이상적인 기둥서방 생활 36-1화 (42 / 46)

version: 2.7h (20-02-28 06:02:32 GMT+0)
platform: Windows-10-10.0.18362
order: -25
group: False
gal_num: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1095
dir: 
zip: 
type: manamoa
artist: None
url: https://manamoa30.net/bbs/page.php?hid=manga_detail&manga_id=1095
valid: True
done: False
range: None
range_p: None
single: False
time: 1584191186.95 (Mar 14)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Solve protection
【chrome】 load...
【chrome】 loaded
dirFormat: [artist][lang] title
Skip: 이상적인 기둥서방 생활 1화
Skip: 이상적인 기둥서방 생활 2화
Skip: 이상적인 기둥서방 생활 3화
Skip: 이상적인 기둥서방 생활 4화
Skip: 이상적인 기둥서방 생활 5화
Skip: 이상적인 기둥서방 생활 6화
Skip: 이상적인 기둥서방 생활 7화
Skip: 이상적인 기둥서방 생활 8화
Skip: 이상적인 기둥서방 생활 9화
Skip: 이상적인 기둥서방 생활 10화
Skip: 이상적인 기둥서방 생활 11화
Skip: 이상적인 기둥서방 생활 12화
Skip: 이상적인 기둥서방 생활 13화
Skip: 이상적인 기둥서방 생활 14화
Skip: 이상적인 기둥서방 생활 15화
Skip: 이상적인 기둥서방 생활 16화
Skip: 이상적인 기둥서방 생활 17화
이상적인 기둥서방 생활 18화 chapter:25162 seed:0 domains:121
이상적인 기둥서방 생활 19화 chapter:25155 seed:0 domains:121
Skip: 이상적인 기둥서방 생활 20화
Skip: 이상적인 기둥서방 생활 21화
Skip: 이상적인 기둥서방 생활 22화
Skip: 이상적인 기둥서방 생활 23화
Skip: 이상적인 기둥서방 생활 24화
Skip: 이상적인 기둥서방 생활 25화
Skip: 이상적인 기둥서방 생활 26화
Skip: 이상적인 기둥서방 생활 27화
Skip: 이상적인 기둥서방 생활 28화
Skip: 이상적인 기둥서방 생활 29화
Skip: 이상적인 기둥서방 생활 29-2화
Skip: 이상적인 기둥서방 생활 30화
Skip: 이상적인 기둥서방 생활 30-2화
Skip: 이상적인 기둥서방 생활 31화
Skip: 이상적인 기둥서방 생활 31-2화
Skip: 이상적인 기둥서방 생활 32화
Skip: 이상적인 기둥서방 생활 33화
Skip: 이상적인 기둥서방 생활 33-2화
Skip: 이상적인 기둥서방 생활 34화
Skip: 이상적인 기둥서방 생활 34-2화
Skip: 이상적인 기둥서방 생활 35-1화
Skip: 이상적인 기둥서방 생활 35-2화
이상적인 기둥서방 생활 36-1화 chapter:2528576 seed:347020 domains:121
【phantomjs】 load...
【phantomjs】 loaded
wait... 이상적인 기둥서방 생활 36-1화

**Comment by mita5549** [comment]
https://manamoa30.net/bbs/board.php?bo_table=manga&wr_id=2528576

 지나가는 사용자 입니다.  
 해당 화수는 마나 모아 사이트에서 이미지 로딩 실패 문구가 출력되는 것 같습니다.
 프로그램 문제가 아닌 사이트의 문제인데, 프로그램에서 저런 것을 우회하고 작업을 하는 경우도 있었던 것으로 기억합니다만, 그게 작동되지 않은 것 같네요.
 제이마나에서 다시 시도 해 보시면 좋을 것 같습니다. : )

**Comment by KurtBestor** [comment]
36-1화에 오류가 있어서 안 되는데, `선택 화 다운로드`로 해당 화 빼고 다운로드 해주세요.
