### ISSUE TITLE
혹시 jav5most 사이트에서도 다운로드 기능 추가 가능하신가요?

### ISSUE THREAD

**Issue by dh22659** [KurtBestor/Hitomi-Downloader#1783]
avgle 기능 추가 여쭤봤던 사람인데, 염치없이 다시 한번 부탁드립니다.

avgle에는 안올라와 있는 영상들도 많고,

그런 영상들은 시드가 없는경우도 대다수라서요...

**Comment by Yoon0618** [comment]
javmost는 다른 사이트 영상을 띄워주기만 하는거라... 
대부분 javcl이나 javfinder 같은 곳에서 가져오는 거에요
