### ISSUE TITLE
won't let me load cookies

### ISSUE THREAD

**Issue by Rocneriano** [KurtBestor/Hitomi-Downloader#1784]
I used to load the cookies normally, but now they don't let me, I get this error every time, what can I do?

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 6978, in foo
  File "youtube_dl\utils", line 2762, in load
  File "_MozillaCookieJar", line 111, in _really_load
LoadError: invalid Netscape format cookies file u'C:/Users/EQ-hogar/Downloads/cookies (11).txt': u'.instagram.com\tTRUE\t/\tTRUE\t0\turlgen\t&quot;{\\&quot;179.58.51.60\\&quot;:\t28024\\054\t\\&quot;161.22.234.135\\&quot;:\t28024\\054\t\\&quot;179.58.62.151\\&quot;:\t28024\\054\t\\&quot;179.58.40.182\\&quot;:\t28024}:1jDsZY:FeW02fNLhU94I4YVrj79FJkCTEk&quot;'

**Comment by KurtBestor** [comment]
Try this version: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
