### ISSUE TITLE
마나모아 아예 안됩니다.

### ISSUE THREAD

**Issue by coroseng7829** [KurtBestor/Hitomi-Downloader#1785]
최근에 test것도 그렇고, 구글 크롬켜도 안되고... 그냥 아예 안됩니다. ctrl+alt+c하면 Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)] 이렇게 뜨고요...
그냥 안됩니다... 왜 그런지 모르겠네요.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by coroseng7829** [comment]
저번에 윈도우보안에서 Trojan:Win32/ 발견된 이후부터 안되는 거 같기도 해요. 지금 올려주신 것은 응답없음으로 계속 안됩니다 ㅠ... 이제 안되는 건가요...

**Comment by coroseng7829** [comment]
S2

**Comment by bewidu** [comment]
저 같은 경우에는 바로 전 버전(3월17일?)은 제대로 작동했는데 이번 것은 클릭해도 아무런 반응이 없습니다. 에러 메세지도 없고 더블 클릭후 아무런 반응이 없어서 앱을 del하면 그냥 지워집니다.

**Comment by KurtBestor** [comment]
@bewidu 어떤 OS 쓰시나요?

**Comment by bewidu** [comment]
윈도우10 버전 1909 
크롬은 버전 80.0.3987.132(공식 빌드) 
입니다

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bewidu** [comment]
역시나 동일하게 안됩니다.........

**Comment by coroseng7829** [comment]
박사님, 이상하게 응답없음. 멈추는 ㄱ



> 박사님, '응답없음'으로 멈출 때도 많은데 왜 이럴까요 ㅠㅠ

**Comment by KurtBestor** [comment]
@bewidu 실행되는 가장 최근 테스트 버전에서 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
sys._MEIPASS
```

**Comment by bewidu** [comment]
실행되는 가장 최근 테스트 버전은 'version: 2.7h (20-03-16 13:16:36 GMT+0)'입니다.

Python 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]

sys._MEIPASS 

'C:\\Users\\\xc0\xcc\xba\xb4\xc0\xb2\\AppData\\Local\\Temp\\_MEI10~1'

**Comment by KurtBestor** [comment]
@coroseng7829 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

@bewidu 실행되는 가장 최근 테스트 버전에서 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔창 열고 아래 내용 입력하고 <kbd>Enter</kbd> 눌러서 나오는 내용 보여주세요:
```
cefWindow, constants.cef_e_msg
```

**Comment by bewidu** [comment]
cefWindow, constants.cef_e_msg 

(None, None)


이렇게 나옵니다

**Comment by KurtBestor** [comment]
@bewidu 이건 실행 되나요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by bewidu** [comment]
아쉽게도 새롭게 올려주신 테스트버전도 안됩니다.

혹시 제가 사용중인 OS가 윈도우 10 프로가 아닌 10 홈인데 이게 문제가 될수도 있을까요?

**Comment by KurtBestor** [comment]
@bewidu <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>I</kbd> 눌러서 인터프리터 열고 쓰여져 있는 내용 모두 지운 후 아래 내용 입력하고 <kbd>Exec</kbd> 눌러서 나오는 내용 보여주세요:
```
paths = ['c:/windows/system32', 'c:/windows/syswow64']
x = []

for path in paths:
    x.append('    [ {} ]'.format(path))
    if os.path.exists(path):
        x.append('\n'.join(sorted(os.listdir(path))))
    x.append('\n'*8)

with open('test.txt', 'w') as f:
    f.write('\n'.join(x))
os.startfile('test.txt')
```

**Comment by bewidu** [comment]
[test.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4354849/test.txt)

**Comment by esulbitea** [comment]
개발자님 가장 위에 링크 해주신 
version: 2.7h (20-03-18 20:34:57 GMT+0) 버그가 있습니다.
마나모아에서 몇가지 받아보았는데
예를 들어 1화, 2화를 받는데 1화 폴더에 2화 이미지가 들어가 있고
2화 폴더에 1화 이미지가 들어가 있다거나
같은 1화를 두번 받아보았는데 폴더 안 이미지 장 수가 다릅니다.
그리고 또 만화를 받는데 다른 작가의 폴더안에 다운이 된다던지
조금 이상합니다.

**Comment by bewidu** [comment]
아무리 생각해도 제 노트북이 이상한거 같아서 오늘 싹 밀어버리고 OS를 새로 설치 했습니다.

그랬더니 가장 18일자와 19일자 최신 테스트 버전 모두 정상적으로 작동합니다.

제 PC 잘못이였는데 그동안 물의를  일으키고 KurtBestor님을 귀찮게 해드려서 정말

죄송합니다..........

**Comment by KurtBestor** [comment]
@esulbitea 해당 작업들 선택해서 `작업` - `선택된 작업들 내보내기...` 해서 저장한 파일 보내주시면 분석해볼게요.

**Comment by esulbitea** [comment]
KurtBestor님
작업들 선택해서 작업 - 선택된 작업들 내보내기 하니까 확장자가 hdt입니다.
hdt파일 올리기가 안되어서 확장자를 txt로 바꿔서 올렸습니다.
이렇게 파일을 올리는게 맞는지 모르겠습니다.
테스트틑 version: 2.7h (20-03-20 04:57:09 GMT+0)이 버젼으로 했습니다.
아래 버그1이 가브릴이라는 만화인데 마왕군 폴더에 들어가 있고
버그2의 만화는 마왕군이라는 만화인데 반대로 가브릴 폴더에 들어가 있습니다.
이거 말고도 다른 작가의 폴더에 다른 만화폴더가 다운 된다는지
1화 폴더에 2화 내용이 다운이 된다던지 하는 버그가 있는데 실험을 더 해봐야 될것 같습니다.

[버그1.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4360088/1.txt)
[버그2.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4360090/2.txt)

**Comment by KurtBestor** [comment]
@esulbitea 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by esulbitea** [comment]
KurtBestor님 늦어서 죄송합니다.
지금까지 여러번 테스트 해봤는데 버그 없이 잘 되고 있습니다.
진행 속도도 상당히 빠르고 좋습니다.
신경 써 주셔서 정말 감사합니다. 그리고 고생하셨습니다.
