### ISSUE TITLE
hitomi searcher 궁금한게있어서 게시글 남깁니다.

### ISSUE THREAD

**Issue by ckdwhrudwp0005** [KurtBestor/Hitomi-Downloader#1788]
검색 유형에

기본 데이터

삭제된 데이터 두가지가 있는것 같던데

삭제된 데이터는 게시글이 완전히 삭제되거나 expunged한 게시글만 나오는줄 알았는데

hitomi나 exhentai 에 보면  삭제되거나 expunged 하지 않은것도

삭제된 데이터에 있는거 같아서

정확한 기준을 잘모르겠어서 게시글 쓰게 됬습니다

답변해주시면 감사합니다.

**Comment by KurtBestor** [comment]
Hitomi.la 검색에선 찾을 수 없지만 서버에 데이터가 남아있는 경우나 Hiyobi.me 에 남아있는 경우에 삭제된 데이터에 추가돼요.

**Comment by ckdwhrudwp0005** [comment]
친절한 답변 감사합니다!
