### ISSUE TITLE
중복이미지 정확도

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#1790]
최근에 중복 이미지 정확도를 손보셨다는걸 알게 되서 저도 한번 시도해봤는데 
완전히 동일한 이미지지만 크기나 해상도 차이로 인해 구별하지 못하는 경우가 발생해서 이렇게 문의 드리게 되었습니다.

아래는 해당되는 샘플 이미지구요, 19금짤 입니다..ㅎㅎ
분할 압축파일 업로드가 안되서 확장자만 추가했습니다. 
받아보실땐 jpg 확장자만 제거하시면 될 거 같긴 한데 문제있을시 피드백 주시면 다른 방식으로 업로드 해보겠습니다!

![새 압축 z01](https://user-images.githubusercontent.com/47098778/76975310-ba8b4180-6975-11ea-80cb-b67f83af5b78.jpg)
![새 압축 z02](https://user-images.githubusercontent.com/47098778/76975314-bc550500-6975-11ea-9594-28e3290b4312.jpg)
![새 압축 z03](https://user-images.githubusercontent.com/47098778/76975324-bd863200-6975-11ea-8b33-48a8c129ea30.jpg)
[새 압축.zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4349681/default.zip)

[비슷한 이미지도 포함] 기능을 켜면 결과창에 나타나긴 하는데
그렇게 되면 중복되지 않는, 서로 다른 이미지들까지 모두 결과창에 나타나서 불편합니다.ㅠㅠ

크기와 해상도는 다르지만 육안으로 보면 동일한 이미지를 구별할 순 없을까요?
혹시나 다른 샘플도 필요하시다면 말씀해주세요! 
해상도나 픽셀차이만 나는 동일한 사진들이 꽤 나오네요..ㅎㅎ;

**Comment by KurtBestor** [comment]
`비슷한 이미지 포함` 을 켜지 않으면 비트 단위로 데이터가 완전히 동일한 파일만을 찾아요.
`비슷한 이미지 포함` 은 말씀하신 것 같은 문제를 해결하기 위해 추가된 기능이에요. 민감도를 좀 더 높이면 "동일한" 이미지만 골라지겠지만 화질이 다르거나 조그맣게 워터마크가 있는 경우, 가장자리가 조금 잘려나간 경우 등을 인식하지 못해요. 여기에 맞춰서 현재 민감도는 적당히 설정되어있어요.

**Comment by Rounlet** [comment]
@KurtBestor 
앗.. 잘 알겠습니다. 저도 혹시나 해봤네요. 

그럼 이 기능을 추가해보시는건 어떨까요?
자동선택 기능을 강화하는건데

예를 들어서 [비슷한 이미지 포함]을 켜고 검색을 했을 때
1번 중복 그룹부터 130번 중복 그룹까지는 비슷하기만한 이미지라 자동선택할 필요가 없는데
그 이후 그룹부터는 제가 말씀드린 것처럼 육안으론 동일하지만 크기가 다른 이미지라고 가정하면
130번 이후 그룹들만 자동선택되게끔, 자동선택의 범위를 설정하는 기능을 추가하면 어떤가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Rounlet** [comment]
@KurtBestor
세상에..

너무 많이 요구드려서 건너뛰신줄 알고 확인해볼 생각조차 못했네요.. 죄송합니다..
일단 테스트해봤는데 전반적으로 제 요청사항이 다 반영되있어서 놀랐습니다.ㅠㅠ

범위 지정은 그룹 번호를 기입할줄 알았는데 드래그 방식으로 반영하셨더군요.

파일 삭제 후엔 그 자리를 유지하는 것도 잘 반영되었고
범위지정도 드래그 방식으로 반영되었으며
자동선택과 일반클릭을 별도로 하신 것까지 모두 반영되어 만족스럽습니다.

다만,
![주석 2020-04-15 032732](https://user-images.githubusercontent.com/47098778/79260341-18ee0600-7ec9-11ea-8e62-7dfe7cdd4423.png)

자동선택 기능을 100퍼센트 활용하기 위해선

자동선택이 된 것을 특정 그룹에선 해제하는 기능도 필요하다고 봅니다.

예를 들어 
첨부드린 이미지와 같이 범위 선택을 하고
62번 그룹의 자동선택이 잘 안되서 위 이미지가 선택되야하는 상황인데
자동선택을 해제할 수도, 위 이미지를 자동선택된 이미지에 포함시킬 수도 없는 상황입니다.

그래서 제가 체크박스 형태로 자동선택이 잘 안됐을 경우에 사용자가 임의로 체크박스를 수정해서 지워져야할 이미지가 선택되도록 해야 한다고 제안드렸었죠. 

구지 체크박스가 아니더라도 사용자가 수정할 수 있는 자동선택이 되었으면 합니다.

이 기능만 추가적으로 달성한다면
제가 생각했던 검색기의 모습이 완성될 것 같습니다!

**Comment by KurtBestor** [comment]
빨간색은 마지막으로 자동 선택한 걸 표시하는 기능이에요.

선택 된 게 아니에요.
