### ISSUE TITLE
폰허브 다운로드가 정상적으로 진행되지않습니다

### ISSUE THREAD

**Issue by hokess5** [KurtBestor/Hitomi-Downloader#1791]
일반 폰허브가 아닌 폰허브 프리미엄 싸이트에서 다운받는것이 안됩니다

https://www.pornhubpremium.com 

프리미엄영상을 볼수 있는 권한을 가지고있는 계정으로 로그인을 하고

크롬확장프로그램으로 쿠키를 저장한다음 불러오기를 하여 적용시킨후 다운로드를 해보았지만 

정상적으로 다운로드가 되지않는것이 확인되었습니다

해결해주시면 감사하겠습니다

오류내용입니다

Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5e1a1f683648a

version: 2.7h (20-03-18 08:04:05 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
valid: False
done: True
range: None
range_p: None
single: True
time: 1584529856.67 (Mar 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 671, in wrapper
File "pornhub_downloader", line 233, in get_video
File "pornhub_downloader", line 164, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 815, in start
File "utils", line 865, in start_
File "pornhub_downloader", line 119, in read
File "constants", line 698, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 671, in wrapper
File "pornhub_downloader", line 233, in get_video
File "pornhub_downloader", line 164, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e1a1f683648a

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by hokess5** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

실행해보니 작동이 잘되더군요 패치해주셔서 감사합니다
