### ISSUE TITLE
기능 추가 건의입니다.

### ISSUE THREAD

**Issue by JANGOON-No89** [KurtBestor/Hitomi-Downloader#1793]
이미 다운로드 했던 파일에 대해선 로그를 남겨서 파일을 이동하더라도 중복파일이 다운로드 되지 않게 해주셨으면 합니다.

저는 주로 마나모아에서 만화를 다운로드 하는 용도로 이 프로그램을 쓰는데요,
만화를 볼 때 한 화 마다 다음 폴더로 넘어가는게 너무 귀찮다보니 만화를 다운받으면 다른 폴더로 옮긴 후 각 화별 폴더로 나눠진 파일을 하나의 폴더에 통합시킵니다.

그런데 이렇게 하면 다운로드 폴더에는 파일이 남아있지 않으니 추가로 업데이트된 것을 다운로드 하려면... 
1. 다운로드 폴더의 파일을 이동하지 않고, 복사해서 통합 (쓸데없이 용량차지)
2. 전체목록에서 다운로드 하지 않고, 한 화씩 따로따로 다운로드 (밀린게 많으면 번거로움)
3. 선택 화 다운로드 (링크 추가할 때 마다 일일이 지정해야하고, 로딩이 김)
이 세가지 중 하나를 선택해야 합니다. 
불편합니다......

해서, 만화 다운로드시 각 타이틀마다 몇화를 다운받았는지 ini등의 파일로 로그를 남겨서 차후에 전체목록을 다시 다운로드 하더라도 로그에 남아있는 화는 제외하고 다운로드 할 수 있도록 해 주셨으면 합니다.
그리고 이러한 기능은 설정에 마나모아 설정을 넣고, [로그 남기기] 와 [로그에 남은 파일을 제외하고 다운로드] 두 항목을 추가하여 사용자가 선택하여 사용할 수 있게 해 주셨으면 합니다.

**Comment by KurtBestor** [comment]
오히려 너무 불편해지는 것 같네요. 다음 폴더로 바로 넘어갈 수 있는 이미지 뷰어를 쓰세요.
