### ISSUE TITLE
사이트 추가 가능할까요?

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#1797]
판도라tv와 Moeni 사이트 추가 가능하시면 부탁드리고싶습니다

**Comment by KurtBestor** [comment]
Moeni는 이미 지원해요: https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1532#issuecomment-672104727
