### ISSUE TITLE
Luscious 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by Jin-Soo-Choi** [KurtBestor/Hitomi-Downloader#1798]
Invalid: [luscious] https://www.luscious.net / albums / c86-wireframe-yuuki-hagure-erichi-no-tobira-love-live_229155 / 

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.luscious.net/albums/c86-wireframe-yuuki-hagure-erichi-no-tobira-love-live_229155/
dir: 
zip: 
type: luscious
artist: None
url: https://www.luscious.net/albums/c86-wireframe-yuuki-hagure-erichi-no-tobira-love-live_229155/
valid: False
done: True
range: None
range_p: None
single: False
time: 1584599151.65 (Mar 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'a'
stop
Traceback (most recent call last):
File "utils", line 791, in start
File "utils", line 838, in start_
File "luscious_downloader", line 62, in read
File "luscious_downloader", line 168, in get_title
AttributeError: 'NoneType' object has no attribute 'a'

Invalid: fail=True
EOT: https://www.luscious.net/albums/c86-wireframe-yuuki-hagure-erichi-no-tobira-love-live_229155/

어떻게 해결할 수 있나요?

감사합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Jin-Soo-Choi** [comment]
잘됩니다 
감사드려요
