### ISSUE TITLE
제이마나/개별 화 다운로드 건의

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#1799]
안녕하세요.
 요즘 마나모아의 클라우드 플레어로 인해 다운로드의 속도가 너무 더뎌서 건의 드립니다..ㅠㅠ
 제이마나쪽 링크도 마나모아처럼 다운로드가 가능하게 업데이트 해 주실 수 있으신가요?

 구체적으로는 기존의 [전편 보기]의 링크에서 [선택 화 다운로드]를 통해 개별의 에피소드를 지정하여 다운로드 받는 것이 아니라,

 홈페이지 메인화면의 업데이트 목록(https://jmana.net/comic_recent)에서 복사 한 개별 에피소드의 링크를 입력해도 다운로드가 되었으면 합니다. 
![image](https://user-images.githubusercontent.com/45882353/77088516-e840bb00-6a47-11ea-8988-b97daa0024d4.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
오오오오오! 한참을 건의 드렸던 것이 이제야 순번이 왔군요!

지만..... 가는 날이 장날이라고 지금 작업중인게 cpu 점유율 90%대라 바로는 테스트 할 수 없겠네요.ㅠㅠ
북마크 해두고 테스트 후 답변 달겠습니다! 감사합니다.

**Comment by mita5549** [comment]
![image](https://user-images.githubusercontent.com/45882353/94039097-3d4bf800-fe02-11ea-890b-f858b7d2ba75.png)

제이마나/업데이트 페이지에서 개별 다운로드를 확인했습니다.
감사합니다!ㅜㅜ
