### ISSUE TITLE
트위터에서 영상파일이 다운되지 않습니다.

### ISSUE THREAD

**Issue by rlarkakstp** [KurtBestor/Hitomi-Downloader#1801]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1626
글 참조하여 트위터 다운은 가능해졌는데 이미지만 다운되고 영상이 다운되지 않습니다.
오류메세지도 뜨지 않고 다운로더상에서는 정상처리된것 처럼 보입니다.
공개계정과 비공개계정 동일합니다.

**Comment by rlarkakstp** [comment]
완료후 자동삭제옵션을 꺼보니 영상을 받을 차레가 되었을시 10분뒤 다시시작이라는 노랑 글자가 뜨네요

**Comment by rlarkakstp** [comment]
고급 옵션에서 불안정한항목 X시간 후 다시받기 항목을 끄니까 항목이 황색으로 변하고 정지됩니다. 고로 에러리포트도 안나오네요..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rlarkakstp** [comment]
파일이 실행되지 않습니다 ㅜㅜ
hitomi_downloader_GUI_test.zip 를 풀어서 실행하면

Error creating child process!
CreateProcessW:엑세스가 거부되었습니다.

라고 뜹니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by rlarkakstp** [comment]
실행은 되었으나 전과 같았기에 포기상태였는데 이것저것 건드리다가 dpi우회를 키니 영상이 다운받아지는군요.
dpi우회가 영상파일 다운에 관여하는지는 몰랐네요;;
신경써주신것 감사드립니다.
