### ISSUE TITLE
트위터 파일명 형식 옵션

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#1802]
현재 트위터 파일명이 날짜-링크넘버-p0 이런식으로 되어있는것 같은데 원본 파일명도 옵션으로 추가 가능하면 좋을것 같습니다. 예전에 다른 분이 [https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1389](url) 여기서 건의해주셨는데 깃헙 봇이 자동으로 닫아부렀네요...

**Comment by KurtBestor** [comment]
현재 필요한 트윗만 빠르게 다운로드 하기 위해서 파일명을 사용하기 때문에 바꾸는 건 힘들 것 같네요.

**Comment by githitoman** [comment]
현재 형식에서 원본파일명만 추가하는 방식 (예를 들면 [20-03-28] 93847576847_p0_DwjgiJDgksl.jpg) 이런식으로도 불가능할까요? 아무래도 트위터에서 직접 다운받는 경우 이미지가 원본 파일명으로 저장되다 보니 가능하면 이미지 정리할때 참고할만한 파일명이 있으면 좋을것 같아서요. 물론 기술적으로 불가능한거라면 아쉽지만...
