### ISSUE TITLE
비리비리 영상이 다운로드 되지 않습니다

### ISSUE THREAD

**Issue by BV1wb411t7EJ** [KurtBestor/Hitomi-Downloader#1804]
뚫렸다 하면 바로 막아버리는 사이트이긴 한데, 오늘 시도해보니 다운로드가 되지 않네요. 다시 막아놓은 것 같습니다. 방법이 없을까요? 테스트 링크와 테스크 인포를 아래에 남겨놓습니다.
https://www.bilibili.com/video/BV13E411L7Er

Invalid: [bili] https://www.bilibili.com / video / BV13E411L7Er

version: 2.7h
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.bilibili.com/video/BV13E411L7Er
dir: 
zip: 
type: bili
artist: None
url: https://www.bilibili.com/video/BV13E411L7Er
valid: False
done: True
range: None
range_p: None
single: False
time: 1584950415.79 (Mar 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 669, in __init__
File "bili_downloader2", line 50, in id
AttributeError: 'NoneType' object has no attribute 'group'

Invalid: fail=True
stop
EOT: https://www.bilibili.com/video/BV13E411L7Er

**Comment by fromind** [comment]
제가 혹시나 해서 VSO Downloader 로 다운해봤는데 됩니다
다만 영상과 소리가 따로 다운이 되긴합니다.

**Comment by BV1wb411t7EJ** [comment]
알려주신 대로 VSO로 시도해봤지만 안 된다고 하네요. 링크 자체에 아예 암호를 걸어놔서, 링크를 인식을 못 하게 막아놓은 것 같습니다. 가능할진 모르겠지만, 다음 히토미 업데이트 땐 다시 다운로드가 가능했으면 좋겠네요. 그래도 답변 감사드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by BV1wb411t7EJ** [comment]
방금 테스트해봤는데 정상적으로 작동합니다. 정말 감사드립니다! 비리비리 쪽에서 막아놨던 건가요? 아무튼, 다시 한 번 감사드립니다.
