### ISSUE TITLE
Hitomi Searcher 질문

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader#1805]
검색기에서 작가 이름 옆의 숫자는 작품의 수를 뜻하는것 같은데, 가끔 맞지 않는 경우가 있는것 같아요

![image](https://user-images.githubusercontent.com/36811336/77340361-872f2500-6d70-11ea-93a1-53d067bff2f0.png)

![20200324_013840](https://user-images.githubusercontent.com/36811336/77340504-be9dd180-6d70-11ea-8311-5a5099868515.png)

![20200324_013919](https://user-images.githubusercontent.com/36811336/77340509-bfcefe80-6d70-11ea-878e-1cfcc278460e.png)

![image](https://user-images.githubusercontent.com/36811336/77340456-a9c13e00-6d70-11ea-819c-661276f6d68c.png)

**Comment by KurtBestor** [comment]
정확한 수치는 아니고, 검색에 도움을 주기 위한 대략적인 수치예요.
