### ISSUE TITLE
기능건의 문의드립니다.

### ISSUE THREAD

**Issue by iskt1212** [KurtBestor/Hitomi-Downloader#1806]
"브라우저로 보기" "폴더열기''파일삭제"등이 편해서 히토미 다운로더 목록에 넣어 이미지 뷰어처럼 사용하고있습니다.

지금까지 히토미 다운로더 목록에 다운로드한 폴더를 추가할때
"저장폴더에있는 모든 갤러리 넘버 복사"를 이용해서 추가하고있는데
한번에 일괄로만 추가 해야만 하는 불편한점이 있습니다.
혹시 폴더를 드래그 한후 갖다넣기로 목록을 추가 할 수는 없을까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1863#issuecomment-628519784
