### ISSUE TITLE
호환이 ..되지않습니다..

### ISSUE THREAD

**Issue by kara0111** [KurtBestor/Hitomi-Downloader#1809]
이 파일의 버전이 실행중인 윈도우 버전과 호환되지않습니다
컴퓨터의 스스템정보를 확인하여 프로그램의 x86[32비트] 또는 x64[64비트] 버전이 필요한지 확인한 다음 소프트웨어 게시자에게 문의하십시오

가 ..뜨내요.................
똥컴인증 죄송합니다 ...

흑흑

**Comment by KurtBestor** [comment]
어떤 OS 쓰시나요?
