### ISSUE TITLE
사이트 추가 건의 외...

### ISSUE THREAD

**Issue by als0001** [KurtBestor/Hitomi-Downloader#1811]
1 . 이 사이트 추가가 가능할까요? 업로드도 활발하고 이상한 기믹이 없어서 깔끔하네요

https://mangahua.com/

2. https://e-hentai.org/lofi/?f_search=korea&f_apply=Search

여기 사이트가 원래 주소만 복사하면 자동다운로드가 되더니 갑자기 안되네요?

잘 부탁드립니다.

**Comment by KurtBestor** [comment]
`옵션` - `클립보드에서 자동 추가` 체크해주세요.

**Comment by als0001** [comment]
> `옵션` - `클립보드에서 자동 추가` 체크해주세요.

물론 켜놨지요. 다른 사이트 다 잘되는데 유독 여기만 안되어서 질문드린겁니다

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/77819864-7e986f00-7121-11ea-8aad-14060f4bad94.png)

이 부분 어떻게 되어있는지 스크린샷 찍어서 보여주세요.

**Comment by als0001** [comment]
아... 저 제크가 전부 다 풀려있네요. 도로 다 켜주니 잘됩니다.
에구 번거롭게 해드려서 죄송합니다.

> ![image](https://user-images.githubusercontent.com/14768120/77819864-7e986f00-7121-11ea-8aad-14060f4bad94.png)
> 
> 이 부분 어떻게 되어있는지 스크린샷 찍어서 보여주세요.

아... 저 제크가 전부 다 풀려있네요. 도로 다 켜주니 잘됩니다.
에구 번거롭게 해드려서 죄송합니다.
