### ISSUE TITLE
아이디 비밀번호를 잘못입력했을때 어디서 수정할수 있나요?

### ISSUE THREAD

**Issue by ckdwhrudwp0005** [KurtBestor/Hitomi-Downloader#1812]
pornhub 다운로드를 할때
pornhub sign 이떠서 
다운로더에서 아이디 비밀번호를 입력했는데

잘못입력을 하였습니다
어떻게 수정할 수 있을까요?

**Comment by KurtBestor** [comment]
쿠키 넣는 방식으로 업데이트 될 예정이에요.
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1791
