### ISSUE TITLE
저도 업뎃 이후 호환이 되지 않는다고 실행이 안되네요

### ISSUE THREAD

**Issue by skstjgml** [KurtBestor/Hitomi-Downloader#1815]
이 파일의 버전이 실행중인 윈도우 버전과 호환되지않습니다
컴퓨터의 스스템정보를 확인하여 프로그램의 x86[32비트] 또는 x64[64비트] 버전이 필요한지 확인한 다음 소프트웨어 게시자에게 문의하십시오

노트북 윈도우7인데 이전버전까진 잘 됐다가

이번업뎃 이후로 안돼요

**Comment by CHOMAN777** [comment]
저도 호환이 되지 않습니다.아무래도 윈도우즈10 32비트 버젼을 사용중이라 그런것 같습니다.이전버젼으로 돌리기라도 하고 싶은데 ..ㅠㅠ 이제 32비트 버젼 지원은 영영 없는건가요..!

**Comment by KurtBestor** [comment]
32비트 지원하는 마지막 버전은 여기서 다운로드할 수 있어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.7h

**Comment by skstjgml** [comment]
감사합니다 이걸로 업뎃 안하고 쓰는법밖엔 없나보군요

**Comment by thankuverymuch** [comment]
32비트 지원좀 해주세요

**Comment by sili078** [comment]
궁금한점 AI 에게 질문하기
https://newtoki.iwinv.net/ https://ruliweb.iwinv.net/ https://instiz.iwinv.net/ https://gmarket.iwinv.net/ https://aliexpress.iwinv.net/ https://theqoo.iwinv.net/ https://linkkf.iwinv.net/ https://facebook.iwinv.net/ https://paypay.iwinv.net/ https://etoland.iwinv.net/ https://auction.iwinv.net/ https://trends.iwinv.net/ https://asdasd.iwinv.net/ https://kangkas.iwinv.net/ https://lavikit.iwinv.net/ https://maplegg.iwinv.net/ https://kemono.iwinv.net/ https://redgifs.iwinv.net/ https://wikikr.iwinv.net/ https://yourgg.iwinv.net/ https://koreakr.iwinv.net/ https://capcut.iwinv.net/ https://snp500.iwinv.net/ https://shopee.iwinv.net/ https://namuwiki.iwinv.net/ https://novelpia.iwinv.net/ https://popcat.iwinv.net/ https://fiveguys.iwinv.net/ https://compose.iwinv.net/ https://jjang0u.iwinv.net/ https://anilife.iwinv.net/ https://mmtcld.iwinv.net/ https://tdgall.iwinv.net/ https://yakored.iwinv.net/ https://postype.iwinv.net/ https://manatoki.iwinv.net/ https://dctribe.iwinv.net/ https://blacktoon.iwinv.net/ https://munpia.iwinv.net/ https://snpetf.iwinv.net/ https://hygall.iwinv.net/ https://mingky.iwinv.net/ https://fanbox.iwinv.net/ https://skyscanner.iwinv.net/ https://flightaware.iwinv.net/ https://interpals.iwinv.net/ https://fconline.iwinv.net/ https://flextv.iwinv.net/ https://dcinside.iwinv.net/ https://mlbpark.iwinv.net/ https://eomisae.iwinv.net/ https://ecount.iwinv.net/ https://hiworks.iwinv.net/ https://laftel.iwinv.net/ https://toomics.iwinv.net/ https://mercari.iwinv.net/ https://iptime.iwinv.net/ https://mixamo.iwinv.net/ https://yandex.iwinv.net/ https://gsshop.iwinv.net/ https://toptoon.iwinv.net/ https://slrclub.iwinv.net/ https://dmitory.iwinv.net/ https://kmcert.iwinv.net/ https://lolchess.iwinv.net/ https://curseforge.iwinv.net/ https://hsreplay.iwinv.net/ https://mapleinven.iwinv.net/ https://c19670.iwinv.net/ https://a12893.iwinv.net/ https://b82893.iwinv.net/
