### ISSUE TITLE
업데이트후 바뀐것중에

### ISSUE THREAD

**Issue by legnalegna** [KurtBestor/Hitomi-Downloader#1818]
이전버전까지는 다운로드가 완료되면 작업표시줄 아이콘이 노란색으로 바뀌었었는데 이젠 안그러네요?

설정에도 없는거 같고 일부러 빼신건가요??

**Comment by ExNaGNe** [comment]
저도 다운완료되면 초록색으로 차고
다 완료되면 노란색으로 바뀌는거 편리하게 썼었는데
없어져서 좀 아쉽네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
