### ISSUE TITLE
업데이트 후 클립보드 자동추가 기능이 안됩니다

### ISSUE THREAD

**Issue by img596** [KurtBestor/Hitomi-Downloader#1820]
방금막 업데이트 하니 평상시에 다운중에 초록색~ 완료되면 노란색 표시되는것도 사라졌고

클립보드 기능은 앱을 껐다키고 기능을 on/off 해봐도 안되네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1818, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1811
