### ISSUE TITLE
잘못된 인터페이스

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader#1823]
안녕하세요, 한자 업데이트가 깨졌습니다.

시스템에서 글꼴이 누락 되었습니까?

방금 1909 승리 시스템을 업데이트했습니다.
![hitomi_downloader_GUI_B6OTQyNFKG](https://user-images.githubusercontent.com/30548000/77825107-26259980-7142-11ea-93e4-441268772a19.png)

**Comment by lhj5426** [comment]
많은 문자가 깨졌습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
[tr_dic.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4408791/tr_dic.txt)

인터페이스 왜곡 문제가 수정되었습니다.

 약간 고정 된 번역

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lhj5426** [comment]
늦어서 죄송합니다

이번에는 문제 없습니다

 감사합니다 개발자
