### ISSUE TITLE
화질 조절 옵션

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader#1825]
이미지 포맷 변환 기능 중에 화질을 조절하는 옵션이 jpg로 변환 될 때에만 작동하는 것 같은데, jpg to jpg에서도 작동하게 개선할 수 있나요?

**Comment by KurtBestor** [comment]
이미 JPG 이면 포맷이 변환되지 않아요. 화질 조절 옵션은 포맷 변환하는데 필요해서 넣은 것 뿐이에요.

파일 크기가 너무 커서 줄이고 싶다면 크기 조절 옵션을 쓰세요.
