### ISSUE TITLE
업데이트 후 트위터 영상 다운불가

### ISSUE THREAD

**Issue by Revena** [KurtBestor/Hitomi-Downloader#1826]
안녕하세요.
영상의 트위터 주소를 입력하면 다운로드가 진행됩니다만
해당 동영상주소를 입력하면 다운로드가 안됩니다.

예시)
https://twitter.com/SpursOfficial/status/1243623477065777155
다운가능

https://twitter.com/i/status/1243623477065777155
다운불가능

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by Revena** [comment]
잘 되는것을 확인했습니다. 감사합니다. ( _ _)
