### ISSUE TITLE
[2.8] E-hentai 사이트 ZIP압축 및 원본삭제 불가

### ISSUE THREAD

**Issue by KorCustom** [KurtBestor/Hitomi-Downloader#1827]
E-hentai사이트에서 주소 긁어와서 사용중입니다.

설정-히토미-서버를 수동 및 E-Hentai/ExHentai Server
설정-압축에선 Hitomi를 ZIP/원본 파일 삭제
으로 설정해서 사용중입니다.

2.8로 업뎃 후, E-Hentai의 주소를 복붙하면 다운은 되지만 ZIP압축 및 원본 파일 삭제가 되질 않습니다.

수정 부탁드립니다.

**Comment by sagadako2312** [comment]
전 e헨 속도가 100~200kb/s에서 멈췄다 다운됐다 하던데 원래 이런건가요? 사용한지 얼마 안되서..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KorCustom** [comment]
> 전 e헨 속도가 100~200kb/s에서 멈췄다 다운됐다 하던데 원래 이런건가요? 사용한지 얼마 안되서..



> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 됩니다

> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

기능 정상작동합니다. 감사합니다.

**Comment by KorCustom** [comment]
저도 정확한 원리는 모르지만 경험에 따르면
1. 많은 자료를 다운받을 경우 속도가 느려지거나 일정시간 벤을 먹습니다.
이건 기다리시거나 VPN사용하시면 해결가능합니다.
2. 오래된 자료를 다운받을 경우 속도가 매우 느린 경우가 있습니다. 그냥 다운될 때 까지 기다려야합니다.

**Comment by KorCustom** [comment]
> 전 e헨 속도가 100~200kb/s에서 멈췄다 다운됐다 하던데 원래 이런건가요? 사용한지 얼마 안되서..

말씀하신 증상은 정상작동하는 겁니다. 너무 많은 자료를 다운받으면  e헨 서버에서 일정시간동안 벤을 먹이긴합니다.
