### ISSUE TITLE
2.8 업데이트 이후 익헨 클립보드 다운로드 설정 풀림 및 쿠키 원본 다운로드 파일깨짐

### ISSUE THREAD

**Issue by A2Ring** [KurtBestor/Hitomi-Downloader#1828]
프로그램을 재실행하거나 부팅 후 켜졌을 때 익헨과 히토미 클럽보드 다운로드 설정이 계속해서 해제되고 있으며, 원본 다운로드를 활성화 해두면 다운로드가 안되는 경우가 자주 발생중입니다.
예를들면
https://exhentai.org/g/1194424/4ba016d623/
![image](https://user-images.githubusercontent.com/28779061/77842445-2cad2300-71cd-11ea-8daf-583b349433e9.png)
이렇게 파일이 깨진체 받아집니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1827

깨진 파일들 보내주시면 분석해볼게요.

**Comment by A2Ring** [comment]
> 참고해주세요:
> 
> 깨진 파일들 보내주시면 분석해볼게요.

하나빼고 다 깨져있네요 링크에 있는 애 올립니당.
[[Nanao] (C89) [Kodoku intelligence (Nanao)] the book of narmare (Granblue Fantasy) [Korean] (1194424).zip](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4427553/Nanao.C89.Kodoku.intelligence.Nanao.the.book.of.narmare.Granblue.Fantasy.Korean.1194424.zip)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by A2Ring** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

아예 새로운 폴더에 실행시키면 정상작동되는데
기존에 있던 폴더에 덮어씌우면 똑같은 상황이 발생하네요.
오류 일으키는 폴더입니다.
https://drive.google.com/open?id=1ug9xCw4K8bfIFOVrvEmhLdw5HpliDmRM

**Comment by KurtBestor** [comment]
이거 실행시켜서 쿠키 다시 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by A2Ring** [comment]
> 이거 실행시켜서 쿠키 다시 불러와주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

오류일으키는 폴더에서요? 아니면 저 테스트용 따로 쿠키를 불러와야하는건가요?
