### ISSUE TITLE
instagram 한번에 다운로드하기가 되지않습니다.

### ISSUE THREAD

**Issue by HukoOo** [KurtBestor/Hitomi-Downloader#1829]
안녕하세요. 덕분에 좋은 프로그램 잘사용하고 있습니다. 
감사드립니다.

프로그램을 이용해서 instagram 게시물을 개별적으로 받으면 문제없이 받아지는데
예전에 잘되던게 지금 2.8v에서 게시물 한번에 받기가 되지않더라구요.

다운도르 메시지는 다음과 같습니다.
Invalid: [insta] https://www.instagram.com / homin_joo / 

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.instagram.com/homin_joo/
dir: 
zip: 
type: insta
artist: None
url: https://www.instagram.com/homin_joo/
valid: False
done: True
range: None
range_p: None
single: True
time: 1585469131.44 (Mar 29)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "insta_downloader", line 33, in init
File "insta_downloader", line 38, in id
File "insta_downloader", line 109, in get_id
KeyError: 'ProfilePage'

Invalid: fail=True
stop
EOT: https://www.instagram.com/homin_joo/

확인 요청드리고싶습니다.
감사합니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/78001924-5e5eef00-7371-11ea-854f-3014bb06d019.png)
재현할 수가 없네요.
다시 시도해도 안 되나요?
