### ISSUE TITLE
트레이 아이콘 클릭 기능 추가 건의

### ISSUE THREAD

**Issue by lemonemo** [KurtBestor/Hitomi-Downloader#1830]
제가 히토미 다운로더를 유용하게 사용하고 있는데 그중 편한 것이 주소를 복사만 하면 

자동으로 다운로드 대기열을 추가해주는 기능이 편하고 좋더라구요

그런데 항상 이 기능이 편리해서 켜놓다보니 다운로드 받을 생각 없이 링크를 복사만 해보려던 파일이 받아지는 경우가 자주 있네요 

요즘은 익숙해져서 링크 복사를 하기 전에 자동추가 기능을 끄고 복사를 하곤 하는데

이렇게 하면 기능을 끄고 다시  켜는데 

아이콘 더블클릭 -> 다운로드 일시정지 -> 끄기 -> (복사) -> 아이콘 더블클릭 -> 다운로드 재개 -> 끄기 

이렇게 6번 마우스 이동이 필요해서 약간 번거롭기도 하네요

그래서 트레이 아이콘을 클릭해서 클립보드에서 자동추가 기능을 ON/OFF를 할 수 있게 되면 좋을 것 같아요

AIMP라는 음악 재생 프로그램도 재생 일시정지를 이런 식으로 컨트롤할 수 있는데 편하더라구요

아니면 트레이 아이콘을 우클릭하면 나오는 컨텍스트 메뉴에 이 기능을 ON/OFF 하는 버튼이 추가되면 좋을 것 같아요.

이런 식으로 기능을 능동적으로 켜고 끄는 방식으로 지원이 되면 기능을 껐을때 복사해둔 주소가 기능을 켰을 때 자동으로 추가되는 것이 막아지게 설정을 할 수 있으면 좋을 것 같아요 

프리웨어에 유지보수까지 바라는 게 많아서 죄송합니다 ㅠ; 괜찮아 보인다면 고려해주세요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by lemonemo** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

시험해봤습니다! 컨텍스트 메뉴에 자동추가 항목 생긴거 작동 잘되고 좋습니다!

그런데 지금으로는 이 기능을 켤 때 자동으로 가장 클립보드에 복사된 링크가 있으면 그걸 읽고 다운로드를 시작하는데 이런건 의도되지 않은 다운로드일 확률이 더 높을 것 같아서 기능을 켜고나서 새로 복사한 링크에만 자동추가가 적용되면 좋을 것 같다는 생각이 듭니다

그리고 컨텍스트 메뉴에서 켤 때도 자동 추가 적용 사이트 목록을 고르는 팝업이 뜨는데 가볍게 기능을 켜고 끄려는 목적에서는 다소 무겁다는 생각이 듭니다 팝업 없이 전에 체크해뒀던 목록 그대로만 지원했으면 좋겠어요.

그런데 이런거 트윅하는건 쓸데없이 손이 많이 갈 것 같다는 생각이 드네요 지금 추가해주신 것만으로도 충분히 잘 쓸 것 같습니다 감사합니다!
