### ISSUE TITLE
폰허브 프리미엄 다운로드가 안됩니다

### ISSUE THREAD

**Issue by goxkswo** [KurtBestor/Hitomi-Downloader#1836]
그제까지만 해도 잘 됐는데
링크붙여넣고 다운로드하면 로그인창 뜨면서 다운로드가 가능했는데
로그인창이 더이상 안뜨고 로딩만 계속 되다가 실패합니다
어떻게 해야할까요 ㅠ

Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5d5efae98533b

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
valid: False
done: True
range: None
range_p: None
single: True
time: 1585606009.2 (Mar 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5d5efae98533b

**Comment by KurtBestor** [comment]
참고해주세요: #1812

**Comment by goxkswo** [comment]
저거 이미 사용해 봤는데로그인창이 안뜨던데요 ㅠㅠ삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------발신: Kurt Bestor <notifications@github.com> 날짜: 20/3/31  오후 5:00  (GMT+09:00) 받은 사람: KurtBestor/Hitomi-Downloader-issues <Hitomi-Downloader-issues@noreply.github.com> 참조: goxkswo <goxkswo@gmail.com>, Author <author@noreply.github.com> 제목: Re: [KurtBestor/Hitomi-Downloader-issues] 폰허브 프리미엄 다운로드가 안됩니다 (#1836) 

참고해주세요: #1812



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1836#issuecomment-606465473",

"url": "https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1836#issuecomment-606465473",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
