### ISSUE TITLE
토렌트 파일을 못읽어요

### ISSUE THREAD

**Issue by qwertgb99** [KurtBestor/Hitomi-Downloader#1837]
Faild to read metadata: torrent_D: / [MagicStar] Yuru Camp EP12 END [WEBDL] [720p].mkv.torrent

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: D:/[MagicStar] Yuru Camp EP12 END [WEBDL] [720p].mkv.torrent
dir: 
zip: 
type: torrent
artist: None
url: D:/[MagicStar] Yuru Camp EP12 END [WEBDL] [720p].mkv.torrent
valid: False
done: True
range: None
range_p: None
single: True
time: 1585613217.47 (Mar 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Traceback (most recent call last):
File "utils", line 730, in __init__
File "torrent_downloader", line 29, in init
File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers", line 687, in load_module
File "torrentx", line 4, in init torrent
ImportError: No module named libtorrent

Invalid: fail=True
stop
Traceback (most recent call last):
File "torrent_downloader", line 46, in read
AttributeError: 'NoneType' object has no attribute 'get_info'

Invalid: fail=True
EOT: D:/[MagicStar] Yuru Camp EP12 END [WEBDL] [720p].mkv.torrent

ㅜㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by qwertgb99** [comment]
됩니다! 감사합니다!
