### ISSUE TITLE
숨김 키 버그

### ISSUE THREAD

**Issue by Yoon0618** [KurtBestor/Hitomi-Downloader#1840]
숨김 키를 지정하고 사용하면 숨겨졌다가 몇초뒤 다시 나옵니다

또 꾹 누르면 여러번 누른것으로 인식하네요

**Comment by KurtBestor** [comment]
숨김 키를 어떤 걸로 설정했나요?

**Comment by Yoon0618** [comment]
> 숨김 키를 어떤 걸로 설정했나요?

컨트롤 + H 였습니다
다른 키 조합에서도 동일한 증상이었고요

지금 재현해 보려니 한번 입력으로 숨겨졌다 다시 나오는 현상은 보이지 않네요
그때 디버그에서 플루이드?창이랑 그 근처 몇개를 열어보고 렉이 계속 걸리던 상태였어서 그런 것 같기도 합니다

단 꾹 누르면 여러번 누른 것으로 인식하고 숨김/표시가 여러번 되는것은 계속 나타나네요
