### ISSUE TITLE
일반 폰허브에서 다운로드가 진행되지 않습니다

### ISSUE THREAD

**Issue by what316** [KurtBestor/Hitomi-Downloader#1842]
*프로그램을 개발해주셔서 감사합니다

2020 - 3월 31일 정상작동

2020 - 4월 1일 오전 5시 30분 정상작동

2020 - 4월 1일 오후 1:36분 동영상 다운로드 불가

1. 링크 복사

2. 읽는중 ... 반복됨

3. 다운로드가 안됩니다.

-개인적으로 느낀점 
폰허브 게시물 클릭 후 자동재생이 되었는데 오후에 와서는 자동재상이 되지 않습니다

Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph57f0556101088

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
valid: False
done: True
range: None
range_p: None
single: True
time: 1585720981.78 (Apr 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph57f0556101088

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by what316** [comment]
빠른 피드백 감사합니다

정상작동됩니다.
