### ISSUE TITLE
instagram 다운로드 시 계정의 스토리 포스트도 다운로드 가능할까요?

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1844]
요즘은 인스타그램 스토리를 피드보다 더 많이 사용하기때문에
다운할 당시 올라와있는 스토리까지 함께 다운받는게 가능하다면 더욱 좋을것 같아 건의해봅니다!

**Comment by tdi2020** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1489  

위 이슈로 이미 건의된 바가 있었네요..확인하지 못해 죄송합니다ㅠ 
해당 글만 봐서는 어떻게 진행되었는지는 잘 모르겠으나.. 중복이었습니다!

**Comment by tdi2020** [comment]
선생님 아무 말씀이 없으셔서..ㅠㅠ 기다리다 한번 슬쩍 남겨봅니다. 혹시 구현은 불가능한 이슈일까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1489#issuecomment-612099533
