### ISSUE TITLE
폰허브 Login Cookie required 에러 문의 드립니다.

### ISSUE THREAD

**Issue by ijs4230** [KurtBestor/Hitomi-Downloader#1846]
3일전?까지는 폰허브에서 로그인해도 영상다운이 잘 됬는데 그저께인가 어제부터
로그인한 상태로는 영상다운로드가 안됩니다.

여기에 문의 올렸고 그래서 test? 달린걸로 해봤는데 로그인 안한 상태에서는 영상다운로드가 정상적으로작동하는데 로그인한 상태(프리미엄 사용중)에서는 로딩 돌아가다가 빨간색으로
Login Cookie required
라고 뜹니다. 그래서 또 Export cookie.txt 확장프로그램을 받아서 로그인 되있는 폰허브 사이트의 
쿠키를 받은다음 그걸 다운로더의 옵션-고급에서 쿠키쪽에서 쿠키-불러오기를 로 TXT파일을 넣어서
했는데 그래도 
Login Cookie required
에러가 뜹니다.
해결방법이 있습니까?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1845

**Comment by ijs4230** [comment]
> 참고해주세요: #1845

오 정상적으로 되네요. 감사합니다.
