### ISSUE TITLE
32비트도 지원해주세요 ㅠㅠ

### ISSUE THREAD

**Issue by kara0111** [KurtBestor/Hitomi-Downloader#1847]
32비트 ...정말로 종료하신건가요 ㅠㅠ

32비트 지원되는 2.7버전에 마나모아에서 먹통이내요 ㅠㅠ흑

컴을 바꾸는수밖에없나요 ㅠㅠ 32비트도 지원해주세요 ㅠㅠ

**Comment by KurtBestor** [comment]
[여기](https://microsoft.com/software-download/windows10) 에서 Windows 10 x64 로 업데이트하세요.
