### ISSUE TITLE
pornhub 프리미엄 다운 시 login cookies required 문제

### ISSUE THREAD

**Issue by beck1202** [KurtBestor/Hitomi-Downloader#1850]
안녕하세요

이전 글에 답글 달리신 test 붙어있는 버전으로

pornhub 프리미엄 다운시 login cookies required 가 뜨면서 다운이 되지 않습니다

pornhub 프리미엄으로 로그인 후, export cookies.txt로

현재 탭의 쿠키를 다운 후, 옵션에서 등록했는데도

다운이 되지 않는데 어떡하면 되나요?

혹시 pornhub premium에서 자체적으로 다운 금지된 영상은 다운이 안되는 건가요?

[Pornhub] Login cookies required

version: 2.8 (20-04-01 09:09:14 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0
valid: False
done: True
range: None
range_p: None
single: True
time: 1585829544.46 (Apr 2)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0

stop
Invalid: fail=False
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0

stop
Invalid: fail=False
stop
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5c8a9596441e0

**Comment by KurtBestor** [comment]
참고해주세요: #1845

**Comment by darkking9** [comment]
#1845 확인했는데 저도 역시 안되네요...

**Comment by chunyuhwa** [comment]
> 참고해주세요: #1845

#1845 가 지워졌는지, 확인을 할 수 없습니다.
