### ISSUE TITLE
클립보드에서 자동추가 활성화 관련 문의

### ISSUE THREAD

**Issue by eshbain** [KurtBestor/Hitomi-Downloader#1851]
"클립보드에서 자동추가" 기능을 활성화 시킬시
팝업되는 체크리스트에서 한개라도 체크되어 있지 않은 항목이 있는경우 
실제 기능이 활성화 되지 않습니다.

한마디로 모두 선택되어 있어야만 해당 기능이 동작합니다.

아래 버전에서 확인했습니다.

https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by eshbain** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

정상적으로 잘 동작 합니다. 감사합니다.
