### ISSUE TITLE
그.. 픽시브 소설 다운 관련 이야기는 꺼내면 안 되나요 ㅠㅠ?

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#1852]
1.그.. 픽시브 소설 다운 관련 이슈는 금기사항인지요?

2.제 이슈도 그렇고 다른 분 이슈도 그렇고 딱히 답변이 없으신지라...ㄷㄷ

**Comment by KurtBestor** [comment]
중복인데 답변 달기 귀찮아서 안 달았어요. 질문하기 전에 검색해주세요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/882

**Comment by q2343454** [comment]
어...제작자 님께서 문제를 인지 하시고 
1년 가까이 추가를 못 하셨다는 건가요?
아니면 대체 무슨 소리인지 제가 이해가 안 됩니다 ㅠㅠ

**Comment by KurtBestor** [comment]
아이고.. 문제는 아니고 나중에 시간 나면 추가 할거예요.

개발자가 저 하나라 개발하는데 한계가 있어요.

**Comment by q2343454** [comment]
!!!
현존하는 다운로더 중에 
제일 방대한 사이트를 지원한다고 생각했는데...

아니 이걸 혼자서 개발하신단 말입니까???
이 많은 다운로드 기능이 있는걸 혼자서???

전 한 8명쯤 같이 하시는 줄 알았는데 ㄷㄷ

존경스럽습니다..ㄷㄷ

이슈가 뜨면 바로바로 업데이트가 되길레
왠일로 1년 가까이 추가가 안 된거지? 신기하네?
이렇게 느릴 분들이 아닌데???
하고 있었는데 혼자서 하고 계셨군요 ㅠㅠ
