### ISSUE TITLE
다운로드 가 빠 르 지 않 아 계속 읽 고 있 습 니 다.

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader#1853]
![hitomi_downloader_GUI_treP7Tq07D](https://user-images.githubusercontent.com/30548000/78333091-c7d23e00-75bb-11ea-8a7a-21b8098853bb.png)

 hitomi 

속도 가 없 거나 다운로드 가 안 되 거나...

계속 읽 고 있 거나.

아무튼 안 깔 아 요.

웹 페이지 를 찾 아 보면 웹 페이지 를 찾 을 수 있 습 니 다.

그냥 어 플 에 다 운 받 을 수가 없어 요. 속도 가 없어 요.
![chrome_Att3l02Phw](https://user-images.githubusercontent.com/30548000/78333019-aa04d900-75bb-11ea-984a-d7b1cf003b38.png)

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
