### ISSUE TITLE
Iwara private 영상 다운로드 문제

### ISSUE THREAD

**Issue by garrysout** [KurtBestor/Hitomi-Downloader#1854]
Iwara에서 private 마크된 영상들은 로그인이 되어 있고 영상 업로더와 friend 되어 private 영상을 볼수 있는 상태임에도 다운로드가 invalid라고 나옵니다.

Invalid: [iwara] https://ecchi.iwara.tv / videos / 4zejmfdwjhyag826

version: 2.8 (20-04-01 17:48:18 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://ecchi.iwara.tv/videos/4zejmfdwjhyag826
dir: 
zip: 
type: iwara
artist: None
url: https://ecchi.iwara.tv/videos/4zejmfdwjhyag826
valid: False
done: True
range: None
range_p: None
single: True
time: 1585918613.43 (Apr 3)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'parent'
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "iwara_downloader", line 52, in read
File "iwara_downloader", line 73, in get_files
AttributeError: 'NoneType' object has no attribute 'parent'

Invalid: fail=True
EOT: https://ecchi.iwara.tv/videos/4zejmfdwjhyag826

**Comment by KurtBestor** [comment]
쿠키 집어넣어도 안 되나요?
