### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by versk1** [KurtBestor/Hitomi-Downloader#1858]
안녕하세요

언제나 사용 잘 하고 있어서 너무 감사할 따름입니다.

다름아니라 혹시 가능하다면 http://www.mangahere.cc/ 사이트를 추가하면 어떨까요.

영문번역 만화 위주의 사이트인데 저는 즐겨찾는 편입니다ㅎ

다들 코로나 바이러스 조심하시고 언제나 건강하시면 좋겠습니다.

좋은 주말 되세요~

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/660
