### ISSUE TITLE
미답변으로 enhancement 처리된 질문이 궁금합니다ㅠ

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#1859]
안녕하세요 존경하는 KurtBestor선생님!
다른 비슷한 글을 읽어보니 선생님께서 바쁘셔서 그럴거라고 예상은 하였습니다만
아무 말씀이 없으셔서..ㅠ 기다리다 한번 슬쩍 남겨봅니다. 

https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1489
검색해보니 제가 남긴 질문은 위 1489번 이슈와 같은 질문이었는데요
1489번 이슈는 enhancement로 넘어가있는 상태였습니다.
그래서..  제가 영알못이라 1489번 번역을 해보니

'이 문제는 최근 활동이 없었기 때문에 자동으로 오래된 것으로 표시되었습니다. 더 이상 활동이 없으면 30 일 후에 닫히지 만 필요한 경우 닫힌 문제를 다시 열 수 있습니다.'

이렇게 되어있구 아무 답변은 없었던것 같았습니다ㅠ

요렇게 미답변으로 enhancement인 경우 혹시 구현이 불가능하거나 미뤄진 이슈인가요?
알려주시면 앞으로 질문 쓰거나 할때도 참고해서 최대한 중복을 방지해보겠습니다!
*(제가 쓴 글은 https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1844 이었습니다.)

**Comment by Yoon0618** [comment]
좀 다른 의견이긴 한데... 크롬 확장앱 중에 인스타그램 스토리 다운이 가능한 게 있습니다
https://chrome.google.com/webstore/detail/downalbum/cgjnhhjpfcdhbhlcmmjppicjmgfkppok

**Comment by tdi2020** [comment]
의견 감사합니다.. 확장앱은 저도 사용해보았는데 아무래도 불안정하더군요ㅠㅠ 정상 작동이 안될 때가 자주 발생해 거의 랜덤입니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1489#issuecomment-612099533
