### ISSUE TITLE
유튜브에서 1시간 이상 길이의 동영상 다운로드

### ISSUE THREAD

**Issue by sigsg550** [KurtBestor/Hitomi-Downloader#1861]
유튜브 동영상 중 재생시간이 1시간이 넘어가는 경우 다운이 잘 되지 않는 것 같습니다.  특히 단일항목 다운보다 플레이리스트 다운 시 플레이리스트 안에 1시간 넘는 동영상이 포함되는 경우의 다운 실패확률이 더 높은 느낌입니다.
어떻게 하면 이용할 수 있을까요 ?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
