### ISSUE TITLE
다운받은파일을 작업목록에 추가할 수는 없을까요?

### ISSUE THREAD

**Issue by iskt1212** [KurtBestor/Hitomi-Downloader#1863]
작업목록 내보내기/불러오기가 아니라
다운받은 폴더를 드래그하거나 선택하는걸로해서 추가할 수는 없을까요?
그렇게 하면 당연히 링크까지연결하는것은 불가능하겠지만 
단순히 폴더제목으로만해서 연동할수는 없을까요 ?
히토미같은경우에는 저장폴더번호복사로 할수있지만
마나모아나 뉴토끼이런거는 추가할려면 
다운받은주소를 일일이 하나하나씩 추가하는 방법 말고는 없더라구요

아무튼 항상 감사한마음으로 사용하고있습니다 ㅜㅜ
+그리고 개인적으로 궁금한 게
후원사이트에 올리시는 그림에 댓글을 달려는데 안되더라구요.
코멘트 쓰는란은있는데 확인 버튼이없네요.ㅎ
댓글을 달 수 없는건가요? 제가 댓글을 달 줄 모르 는건가요?

**Comment by KurtBestor** [comment]
내용 입력하고 <kbd>Enter</kbd> 누르면 댓글 달려요.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/81918796-ed6a5280-9611-11ea-972c-6a3502758f05.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
