### ISSUE TITLE
Request metadata Comicinfo.xml to Hitomi.la

### ISSUE THREAD

**Issue by chubits** [KurtBestor/Hitomi-Downloader#1867]
Please add support for Comicinfo.xml to Hitomi.la

Thanx!

**Comment by KurtBestor** [comment]
Is `Comicinfo.xml` a metadata for [ComicRack](http://comicrack.cyolito.com/)? Then you should ask ComicRack for help.

This app can create gallery info file (info.txt). Please see: `Options` - `Preferences` - `Hitomi.la / E(x)Hentai / Hiyobi.me Preferences` - `Create gallery info file (info.txt)`

**Comment by chubits** [comment]
> Это `Comicinfo.xml`метаданные для [ComicRack](http://comicrack.cyolito.com/) ? Тогда вам следует обратиться за помощью к ComicRack.
> 
> Это приложение может создать файл информации галереи (info.txt). Пожалуйста, смотрите: `Options`- `Preferences`- `Hitomi.la / E(x)Hentai / Hiyobi.me Preferences`-`Create gallery info file (info.txt)`

Yes, this is a file for "ComicRack". Unfortunately "Comicrack" forums are currently unavailable. I can't ask for help there.

I use "Comicrack" to edit metadata. I use "Ubooquity" for reading and it works well with "Comicinfo.xml". 

And manually entering a lot of metadata takes a lot of time. It would be great if "Hitomi Downloader" could save metadata in the format "Comicinfo.xml" automatically.

There are two other very interesting projects that support the format "Comicinfo.xml"

Such as:
Komga - (Media server for comics/mangas/BDs with API and OPDS support)
Comixed - (The ComiXed Digital Comic Management System)

Sorry for my English (Google translator)
