### ISSUE TITLE
gui 파일을 읽는데 실패했다고 뜹니다.

### ISSUE THREAD

**Issue by gimanan** [KurtBestor/Hitomi-Downloader#1870]
페이탈 에러가 뜨면서

gui 스크립트를 읽는데 실패했다면서 실행이 안됩니다....

도와주세용 ㅠ.ㅠ 목록을 잃고싶지 않아요!

**Comment by gimanan** [comment]
gui 스크립트에 없는 파일이 들어가 있을경우 (ex : 픽시브 폴더, 챈 폴더 등) 읽지 못하는 것 같은데요 --;

**Comment by KurtBestor** [comment]
gui 스크립트가 뭔가요?
