### ISSUE TITLE
다운로드 기능 관련 추가 건의.

### ISSUE THREAD

**Issue by hentai-redcat** [KurtBestor/Hitomi-Downloader#1872]
안녕하세요, 만들어주신 프로그램 정말 유용하게 잘 사용하고 있습니다.
사용도중 필요하다 생각하는 기능이 몇가지 있어 건의드립니다.

1. 다운로드시 그룹 폴더 별도 지정
[group] [artist] [series] title (id)
현재 다운로드시 위와 같은 형태로 파일을 저장하고 있습니다. 기능상 문제는 없으나 파일 다운로드시에 그룹이 같은 것들은 같은 그룹명의 디렉터리로 별도 저장을 원합니다.

ex)
[acerola] [abab] [시리즈1] [타이틀1] (32423)
[acerola] [dfdfd] [시리즈53] [타이틀35] (23532)
위 두 파일을 받을경우 메인 폴더인 'hitomi' 가 아닌 'hitomi/acerola' 에 저장

2. 다운로드시 저장디렉터리 별도 지정
현재 다운로드시에는 메인 설정에따라 'hitomi'혹은 'hitomi_pixiv' 에 저장되게 되는데 url을 입력하는 곳 하단에 체크박스를 두어 '커스텀 디렉터리 지정' 을 체크 후 저장시에 저장을 원하는 디렉터리 위치가 표시되었으면 합니다.

ex)
1. url 아래 체크박스 클릭
2. url 에 hitomi url 입력
3. 다운로드
4. 다운로드 폴더 지정
5. 다운로드 진행

늘 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/252#issuecomment-425791039

![image](https://user-images.githubusercontent.com/14768120/79209150-fda9d900-7e7d-11ea-95ff-5231a96ddaa8.png)

**Comment by hentai-redcat** [comment]
안녕하세요, 참고해달라고 하신 것을 확인해보니 제가 건의하고자 하는 기능과 조금 다른부분이 있습니다.

현재 저장폴더의 저장형식을 [group] 으로 할시 A그룹에 대한 자료를 다운받았을 경우.
A 디렉터리 아래에 모든 컨텐츠들이 분류되지않고 난잡하게 저장됩니다.

제가 건의드리는 기능은
A 디렉터리 하단에 컨텐츠들이 정렬되는 것입니다.
as-is) A/*
to-be) A/작품1/*, A/작품2/*, A/작품3/*

**Comment by KurtBestor** [comment]
`group/title (id)` 같은 식으로 적어주세요

**Comment by hentai-redcat** [comment]
아 unix 형태의 디렉터리 형식으로 설정하는 것이었군요. 감사합니다!
