### ISSUE TITLE
픽시브 코믹이 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#1876]
Invalid: [pixiv_comic] https://comic.pixiv.net / works / 5879

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://comic.pixiv.net/works/5879
dir: 
zip: 
type: pixiv_comic
artist: None
url: https://comic.pixiv.net/works/5879
valid: False
done: True
range: None
range_p: None
single: False
time: 1586339363.64 (Apr 8)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pixiv_comic_downloader", line 76, in read
File "pixiv_comic_downloader", line 62, in name
File "pixiv_comic_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://comic.pixiv.net/works/5879

개별로 다운받으려 해도 되지 않더군요
부탁드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
