### ISSUE TITLE
#1845가 보이질 않아서 문제 해결을 할수가 없습니다.

### ISSUE THREAD

**Issue by rocl200** [KurtBestor/Hitomi-Downloader#1880]
폰허브 login cookies required 오류가 발생하였고 #1845를 확인하라 하셨지만 #1845가 사라져 확인이 안됩니다. 해결법을 다시한번 알려주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1855
