### ISSUE TITLE
실행 에러

### ISSUE THREAD

**Issue by dkdl2** [KurtBestor/Hitomi-Downloader#1884]
zip 파일을 다운 받고 다운로더를 실행시키면 'Fail to execute script hitomi_downloader_gui' 이렇게 뜨면서 에러가 나는데 어떻게 해야 하나요? 백신 검사 제외도 해봤고 사양도 맞는데 왜 이러는 건가요...ㅠㅠ

**Comment by KurtBestor** [comment]
어떤 OS 쓰시나요?

**Comment by dkdl2** [comment]
윈도우 10이요

**Comment by KurtBestor** [comment]
64비트 맞나요?

**Comment by dkdl2** [comment]
네네 64비트

**Comment by elfmawang** [comment]
저도 컴 3개에서 테스트 중인데 일반 컴은 괜찮고 서피스 프로에서 실행한것은 문제가 같은 문제가 발생하네요. 
Windows 사양 남겨봅니다.
에디션: Windows 10 Home
버전: 1909
OS빌드: 18363.778

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.0b

**Comment by elfmawang** [comment]
네, 다음과 같은 사양의 서피스 프로에서 잘 실행되고 있습니다.
윈도우 사양
에디션: Windows 10 Home
버전: 1909
OS 빌드:  18363.1016
