### ISSUE TITLE
툰코 다운이 안됩니다

### ISSUE THREAD

**Issue by su11094** [KurtBestor/Hitomi-Downloader#1885]
툰코 주소가 바뀌어서 다운이 안됩니다
tkor.vip 여기로 바뀌었어요

**Comment by rmadud8** [comment]
툰코 스크립트를 메모장으로 열어서 스크립트에 있는toonkor => tkor 으로 전부다 바꾸시면 다운됩니다

**Comment by ourload** [comment]
> 툰코 확장 버튼을 클릭하시면됩니다.

확장버튼이요? 그게 어디있나요?
