### ISSUE TITLE
산카쿠에 플러스라는 유료회원 기능이 생겼는데요.

### ISSUE THREAD

**Issue by vaderxx2** [KurtBestor/Hitomi-Downloader#1886]
-픽시브처럼 로그인할 수 있는 기능 좀 건의해드려도 될까요 ?

**Comment by vaderxx2** [comment]
추가로 지금  429 too many requests 가 너무 자주뜨네요.
사이트 측에서 조치를 취한 것 같은데  기존 ~500까지 다운 설정해 놓으면
아예 안될 때가 있고 많아봐야 ~300까지 되네요.
바쁘실텐데 건의사항 드립니다.

**Comment by vaderxx2** [comment]
그리고 다운시작이 안되고 계속 빨간색으로 변하네요.

Invalid: [sankaku] https://chan.sankakucomplex.com / ?tags=red_eyes%20order%3Apopular

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 23
group: False
gal_num: https://chan.sankakucomplex.com/?tags=red_eyes%20order%3Apopular
dir: 
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=red_eyes+order%3Apopular
valid: False
done: True
range: ~300
range_p: None
single: False
time: 1586692359.4 (Apr 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
login... 7
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 6
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 5
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 5
Failed to login Traceback (most recent call last):
File "sankaku_login", line 71, in login_
Exception: https://chan.sankakucomplex.com/user/login

login... 4
types: img, gif, video
https://chan.sankakucomplex.com/?tags=red_eyes+order%3Apopular
no images
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "sankaku_downloader", line 108, in read
File "sankaku_downloader", line 330, in get_imgs
Exception: no images

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/?tags=red_eyes%20order%3Apopular

**Comment by KurtBestor** [comment]
지금도 그런가요?

**Comment by vaderxx2** [comment]
네 지금도 이러네요 
그리고 ~300까지 받게 설정했는데  어쩔때는 ~280 , ~20 ,~40 왔다갔다 하네요.
