### ISSUE TITLE
폰허브 다운실패

### ISSUE THREAD

**Issue by y2k2and4** [KurtBestor/Hitomi-Downloader#1890]
Invalid: [pornhub] https://www.pornhubpremium.com / view_video.php?viewkey=ph5e87418cb550d

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
valid: False
done: True
range: None
range_p: None
single: True
time: 1586773322.36 (Apr 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhubpremium.com/view_video.php?viewkey=ph5e87418cb550d

일~이주전까지 잘 작동하다 먹통이네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1791#issuecomment-601967185
