### ISSUE TITLE
툰코 주소가 바뀌면서 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by iluzde** [KurtBestor/Hitomi-Downloader#1892]
https://tkor.care

보안떄문인지 주소가 자주 변경되는것 같네요.
다운로드 받으면 아래 내용처럼 에러가 납니다..... 바쁘시겠지만 확인부탁드립니다.

Can not determine type: https://tkor.care / %EB%AA%A8%EB%AA%A8%EC%84%B8-%ED%97%AC%ED%94%84

version: 2.7d
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://tkor.care/%EB%AA%A8%EB%AA%A8%EC%84%B8-%ED%97%AC%ED%94%84
dir: 
zip: 
type: 
artist: None
url: https://tkor.care/%EB%AA%A8%EB%AA%A8%EC%84%B8-%ED%97%AC%ED%94%84
valid: False
done: True
range: None
range_p: None
single: True
time: 1586788634.06 (Apr 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid: fail=False
EOT: https://tkor.care/%EB%AA%A8%EB%AA%A8%EC%84%B8-%ED%97%AC%ED%94%84

**Comment by jjunleegood** [comment]
https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts
에서 'Replace URLs' 스크립트 다운 받으신 뒤에 적용하셔서 주소 변경하시면 됩니다.

**Comment by arnast** [comment]
원 주소를 어떤거로 해야 하나요?

**Comment by rmadud8** [comment]
툰코 스크립트를 메모장으로 열고 열린 메모장에 코드가 적혀있는데 적혀있는 코드에서  toonkor라고 적혀있는것들 전부 tkor로 바꾸고 다운로더 껏다 다시 키면 다운로드 됩니다

**Comment by arnast** [comment]
ㅎ

> 툰코 스크립트를 메모장으로 열고 열린 메모장에 코드가 적혀있는데 적혀있는 코드에서 toonkor라고 적혀있는것들 전부 tkor로 바꾸고 다운로더 껏다 다시 키면 다운로드 됩니다

헐 감사합니다. ;;;;

**Comment by ourload** [comment]
> ㅎ
> 
> > 툰코 패널을 메모장로 열고 열린 메모장에서 코드가 적혀 있지 적혀 있지 않습니다.
> 
> 헐 감사합니다. ;;;;

해결하셨나요?? 저도 좀 알려주세요...

**Comment by rmadud8** [comment]
ourload님 툰코 스크립트가 hds파일로 되어있잖아요 그거를 메모장으로열면 영어로된 코드가 나와요
그 코드에 적혀있는 모든 toonkor을 tkor로 바꾸세요
toonkor라고 적혀있는게 8개 정도있는데 그8개 전부 tkor로 바꾸세요

**Comment by kosako421** [comment]
스크립트를 고쳐놓긴했는데 이걸 어디다가 옴겨야되요?
