### ISSUE TITLE
제이마나 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#1893]
Can not determine type: https://aboutdron.net / book / 코미%20양은,%20커뮤증이에요

version: 2.8 (20-04-01 09:09:14 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://aboutdron.net/book/코미%20양은,%20커뮤증이에요
dir: 
zip: 
type: 
artist: None
url: https://aboutdron.net/book/코미%20양은,%20커뮤증이에요
valid: False
done: True
range: None
range_p: None
single: True
time: 1586788822.38 (Apr 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid: fail=False
EOT: https://aboutdron.net/book/코미%20양은,%20커뮤증이에요
사이트 이름 바껴서 다운 안됩니다 여기로 https://aboutdron.net/

**Comment by KurtBestor** [comment]
다음과 같은 주소로 다운로드해주세요: https://jmana1.net/book/코미%20양은,%20커뮤증이에요

**Comment by geniussjt** [comment]
정말 감사합니다ㅠㅠ
