### ISSUE TITLE
다운로드 폴더 안의 하위 폴더 또한 스캔이 필요합니다.

### ISSUE THREAD

**Issue by sun121212** [KurtBestor/Hitomi-Downloader#1898]
안녕하세요. 훌륭한 프로그램 정말 잘 쓰고 있습니다.

후원 방법을 알고 싶었는데 패트리온 주소가 있었네요. 구독했습니다.

하위 폴더 또한 다운로더에서 인식하는 기능이 필요합니다.

다운로드한 작품들이 많아지면서 별점 등의 기능 요청을 했었던 기억이 있습니다.
현재는 원활한 감상을 위해 다운로드 폴더 내에 카테고리별로 폴더링을 해서 관리 중인데, 다운로드 폴더 바로 아래가 아닌 트리 구조에서 관리할 때 이것이 다운로드되었던 작품인지 아닌지 확인이 불가능한 문제가 있습니다.

감사합니다.

**Comment by KurtBestor** [comment]
하위 폴더 문제가 아니라 기존 경로와 달라지면 인식할 방법이 없기 때문이에요. 다운로드 폴더를 스캔해서 인식하는 방식이 아니에요. 불가능해요.

**Comment by sun121212** [comment]
@KurtBestor 

앗.. 그렇군요. 메타 데이터 등으로 식별하나요?
파일명에 해당 사이트의 작품 일련 번호가 적혀있는 경우에도 불가능할까 생각해 보았는데, 다른 사이트들도 있으니 불가능하겠네요. 아쉽습니다 ㅠㅠ

폴더링으로 해결할 수 없다면 다운로드받은 파일이 많아질 때 작품들을 구별할 수 있는 근본적인 해결책이 필요합니다. 태그나 카테고라이징이라도 가능하면 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/286, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1113

**Comment by KurtBestor** [comment]
해당 경로에 같은 이름의 폴더가 있는지 확인해서 인식해요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/286, https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1113

**Comment by sun121212** [comment]
@KurtBestor 

안녕하세요.

오늘 탐색하다 보니 작가 추천에서는 임의로 생성한 폴더 안의 작품도 모두 찾는 것을 볼 수 있었습니다.
그와 같은 방식으로 검색기에서 이 작품이 중복인지 아닌지 정도만 알 수 있는 방법은 없을까요?

**Comment by sun121212** [comment]
@KurtBestor 

안녕하세요. 더운 날씨에 잘 지내고 계신지요?

다시 한 번 문의드립니다.

**Comment by KurtBestor** [comment]
하위 폴더를 모두 읽기엔 시간이 많이 걸려서 작가 추천 등 일부 기능에만 구현되어있어요. 그리고 다운로드 한 후에 폴더 위치를 바꾸는 건 드문 행동이기 때문에 넣지 않을 예정이에요.
