### ISSUE TITLE
유튜브 채널 동영상 음악파일 전환에 대한 버그?

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#1908]
유튜브 채널과 플레이 리스트를 영상및 음악 파일로 전환하여 다운받을시에

진행순서가 그 해당 주소의 영상을 1차적으로 다운을 받고 

2차적으로 음악 파일로 변환 하는거같은데 

예를 들어 50/150 진행상태에서 다시 시작할때 

가끔가다가 종료후 다시실행시 진행이 안되는 현상도 있으며

오류 포함하여 150의 파일을 진행되고 

다시 미완료 파일이니 다시 진행이 시작되는데 

이미 받아서 완료된 파일도 일단 영상을 다시 처음부터 받고 다시 음악파일로 변환하는거 같습니다 .

다시 시작할시에 파일을 완료된 파일인지 미완료된 파일인지 없는 파일인지 확인하는 그런 루트는 없는건가요?

**Comment by KurtBestor** [comment]
동영상 파일이든 음악 파일이든 후처리가 필요한데 후처리가 완료된 파일인지 아닌지 판단할 수 없어서 그래요. 51 번째 영상부터 다운로드하려면 `페이지 지정 다운로드` 에서 `51 ~` 입력해서 다운로드 해주세요.
