### ISSUE TITLE
네이버 블로그 동영상/서로 이웃 관련 글도 

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#1910]
https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1838
 글을 먼저 읽었습니다. 

 나중에 이 기능의 스크립트가 개발 될 쯤에, 서로이웃을 통해 공개 된 글의 동영상도 로그인을 통해서라던가... 다운로드 할 수 있게 해주실 수 있나요? 
 어린 시절 보던 동영상을 간신히 찾았는데, 기존에 사용하던 idm은 먹통이고...
 다른 확장 프로그램을 사용하고 있긴 해도 속도가 너무 답답하네요...ㅠ.ㅠ

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1838#issuecomment-665798999
