### ISSUE TITLE
baraag.net 사이트를 추가 해 주실수 있나요??

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#1911]
pawoo는 지원되는데 비슷한 사이트인 baraag.net는 지원이 안되더라구요. 추가해 주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by cocokakao** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

잘 작동됩니다 정말 감사드립니다.
