### ISSUE TITLE
사용중 멜웨어로 검열됬습니다.

### ISSUE THREAD

**Issue by godknowswho** [KurtBestor/Hitomi-Downloader#1914]
여태까지 쭉 사용해오다가 오늘 처음 격는 일이라서 바이러스 프로그램 오류인가 싶기도 합니다만,
혹시나 해서 확인 부탁드립니다. 사용하던 버전은 아마 2.7d였던것 같습니다. 바이러스 프로그램도, 히토미 다운로더도 사용한지 오래 됬는데 갑자기 프로그램을 거르니까 저도 당황스럽네요.

혹 도움이 되실까 로그는 첨부했습니다.

[간단로그.txt](https://github.com/KurtBestor/Hitomi-Downloader-issues/files/4502115/default.txt)

**Comment by KurtBestor** [comment]
일단 릴리즈 하기 전에 항상 바이러스 검사 하고 올리기 때문에, 실행 파일엔 바이러스가 들어있지 않아요.

v2.7d 파일 SHA-256 해시는 `b58a059c588a497512dfd4eb7821909b31294c74e50ef888d7d5b381b45eda9a` 이고, 만약 달라졌다면 컴퓨터 내의 다른 바이러스에 의해서 감염된거니 전체 바이러스 검사 해보세요.

해시가 동일한데 멀웨어라고 진단한다면 해당 AV에 오진으로 보고 부탁드려요.

참고해주세요: [VirusTotal 검사 결과](https://www.virustotal.com/gui/file/b58a059c588a497512dfd4eb7821909b31294c74e50ef888d7d5b381b45eda9a/detection)
