### ISSUE TITLE
유튜브 연령제한 영상이 다시 않받아집니다.(쿠키 불러오기도 성공했는데 말이죠)

### ISSUE THREAD

**Issue by qkskfka** [KurtBestor/Hitomi-Downloader#1915]
Invalid: [youtube] https://www.youtube.com / watch?v=w4kLVKQ_FAw

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.16299
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=w4kLVKQ_FAw
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=w4kLVKQ_FAw
valid: False
done: True
range: None
range_p: None
single: True
time: 1587389778.57 (Apr 20)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[720p][59fps][None] webm None ─ 302 - 1280x720 (720p60)
[720p][59fps][None] mp4 None ─ 298 - 1280x720 (720p60)
[1080p][59fps][None] webm None ─ 303 - 1920x1080 (1080p60)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[1080p][59fps][None] mp4 None ─ 299 - 1920x1080 (1080p60)
[1440p][30fps][None] webm None ─ 271 - 2560x1440 (1440p)
[1440p][59fps][None] webm None ─ 308 - 2560x1440 (1440p60)
[2160p][30fps][None] webm None ─ 313 - 3840x2160 (2160p)
[2160p][59fps][None] webm None ─ 315 - 3840x2160 (2160p60)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][0fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000001420D11B2C8> 248 - 1920x1080 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BC88> 303 - 1920x1080 (1080p60) 1080p webm None 59fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BD08> 299 - 1920x1080 (1080p60) 1080p mp4 None 59fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B2C8> 248 - 1920x1080 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BC88> 303 - 1920x1080 (1080p60) 1080p webm None 59fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B2C8> 248 - 1920x1080 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BCC8> 137 - 1920x1080 (1080p) 1080p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B2C8> 248 - 1920x1080 (1080p) 1080p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB08> 247 - 1280x720 (720p) 720p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB88> 136 - 1280x720 (720p) 720p mp4 None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BC08> 302 - 1280x720 (720p60) 720p webm None 59fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BC48> 298 - 1280x720 (720p60) 720p mp4 None 59fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB08> 247 - 1280x720 (720p) 720p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB88> 136 - 1280x720 (720p) 720p mp4 None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BC08> 302 - 1280x720 (720p60) 720p webm None 59fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB08> 247 - 1280x720 (720p) 720p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB88> 136 - 1280x720 (720p) 720p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB08> 247 - 1280x720 (720p) 720p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BE88> 22 - 1280x720 (720p) 720p mp4 mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB48> 244 - 854x480 (480p) 480p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BA08> 135 - 854x480 (480p) 480p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BB48> 244 - 854x480 (480p) 480p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B948> 243 - 640x360 (360p) 360p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BAC8> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B948> 243 - 640x360 (360p) 360p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BE48> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B988> 242 - 426x240 (240p) 240p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11B488> 133 - 426x240 (240p) 240p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11B988> 242 - 426x240 (240p) 240p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BA88> 278 - 256x144 (144p) 144p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x000001420D11BA48> 160 - 256x144 (144p) 144p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x000001420D11BA88> 278 - 256x144 (144p) 144p webm None 30fps
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=w4kLVKQ_FAw

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1909#issuecomment-617673408

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1909#issuecomment-622356037
