### ISSUE TITLE
내용을 읽다가 중간에 멈추는데요.

### ISSUE THREAD

**Issue by young029** [KurtBestor/Hitomi-Downloader#1916]
항상 도움을 얻어 감사하게 생각하고 있습니다. 

버저는 2.8 사용 중이고, DPI 우회는 켜 놓았습니다.  589화에서 더 이상 읽지 못하고 계속 읽기만 반복하는 것 같은데 어떻게 해야 할까요?

혹시 100화 단위로 받을 수도 있나요?

 (중간에 문제가 없어 보이는 부분은 삭제하였습니다.)

읽는 중... 킹덤 by 하라 야스히사 / 킹덤 589화 (589 / 639)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 9
group: False
gal_num: https://manamoa34.net/bbs/page.php?hid=manga_detail&manga_id=4805
dir: 
zip: 
type: manamoa
artist: 하라 야스히사
url: https://manamoa34.net/bbs/page.php?hid=manga_detail&manga_id=4805
valid: True
done: False
range: None
range_p: None
single: False
time: 1587371273.75 (Apr 20)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
clf solved
dirFormat: title by artist
킹덤 1화 chapter:312277 seed:0 domains:121
킹덤 2화 chapter:312831 seed:0 domains:121
킹덤 588화 chapter:570662 seed:0 domains:121
킹덤 589화 chapter:602277 seed:96870 domains:121

**Comment by KurtBestor** [comment]
10분 이상 기다렸나요?

**Comment by young029** [comment]
> 10분 이상 기다렸나요?

제가 해외에 있어 답변이 늦었습니다. 오래 켜 놓고 기다리니 읽는 것은 진행이 계속 되었습니다. 답변 감사하고 close 시키셔도 될 것 같습니다.
