### ISSUE TITLE
사운드클라우드에서 음악 다운받을 때 음질 선택 기능이 있었으면 좋겠습니다.

### ISSUE THREAD

**Issue by PangDolLee** [KurtBestor/Hitomi-Downloader#1917]
안녕하세요, Hitomi Downloader을 꾸준히, 그리고 매우 유용하게 사용하고 있는 사용자입니다.

요즘 사운드클라우드에서 각종 노래를 다운받는데, 어째 모든 음악이 192kbps, 44.1khz로 받아지는 것 같더군요.

기분 탓일 수도 있겠지만 어째 평소 듣던 것보다 음질이 안 좋은 것 같기도 합니다.

따라서 사운드클라우드에서 음악을 다운받을 때 음질을 선택할 수 있게끔 설정을 추가해주셨으면 하는 마음에 건의해봅니다.

**Comment by KurtBestor** [comment]
몇 개 살펴봤는데 사이트에서 재생되는 음질이 모두 MP3 / 128kbps 네요.
음질 안 좋게 다운로드되는 음악 주소 주시면 분석해볼게요.

**Comment by PangDolLee** [comment]
확인이 늦어 죄송합니다.

제가 다운받았던 음악들 전부 저음질로 다운되었던 것으로 기억해 그 중 무작위로 3개를 골라 왔습니다.

Listen to Canta Bille & Peno - Daydream by Blossoms 🌸 Asia on #SoundCloud
https://soundcloud.com/blossoms-asia/blossoms008

Listen to Atef - Synergy by The Diverse on #SoundCloud
https://soundcloud.com/the-diversemusic/dvs033

Listen to Alan Walker - All Falls Down (Wild Cards Remix) by Aux Paris on #SoundCloud
https://soundcloud.com/auxparis/wildcards

**Comment by KurtBestor** [comment]
3개 모두 사이트에서 재생되는 음질 MP3 / 128kbps 네요.

**Comment by PangDolLee** [comment]
그럼 저음질로 다운되는 건 어떻게 할 수 없는 문제인 건가요?

**Comment by KurtBestor** [comment]
넵. 파일 리스트를 봐도 MP3 / 128kbps 또는 OPUS / 64kbps 밖에 없네요. 사이트에서 듣는 것과 동일한 파일로 다운로드돼요.

다음 테스트 버전으로 실행하면 작업 정보에서 모든 파일 리스트를 보실 수 있어요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

![image](https://user-images.githubusercontent.com/14768120/80272435-3f4f4500-8704-11ea-9df2-ea447e7bb824.png)

**Comment by PangDolLee** [comment]
확인했습니다. 알려주셔서 감사합니다 :)
