### ISSUE TITLE
툰코나 호두 같은 사이트 스크립트 주소 바꾸는 법좀 알려주세요

### ISSUE THREAD

**Issue by ourload** [KurtBestor/Hitomi-Downloader#1918]
여기서 검색해서 replace 스크립트로 이것저것 알아봤는데
바꾸는게 좀 어렵네요;; 
replace 스크립트 열어서 위에 이전주소 아래에 새주소 입력하는거 같은데
예전 주소 알아내는게 어렵네요
어떤 댓글 보니 예를 들어  toonkor 패널을 메모장으로 열어서 코드를 보면 된다고 하셨는데
어느건지... toonkor 이라고 적힌 부분을 새주소로 다 바꿨는데도 안되는거 같네요
아예 잘못 접근한거 같아요

**Comment by KurtBestor** [comment]
스크립트 수정했어요. 다시 다운로드해서 적용해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
