### ISSUE TITLE
https://www.v2ph.com/  사이트 추가 건의 드립니다 

### ISSUE THREAD

**Issue by mju00rian** [KurtBestor/Hitomi-Downloader#1920]
이미 제공해주신 http://www.itmtu.net/ 사이트보다 자료량이 더 방대한 듯 하여 한 번 부탁드려봅니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
