### ISSUE TITLE
기능 추가 건의

### ISSUE THREAD

**Issue by jjunleegood** [KurtBestor/Hitomi-Downloader#1921]
'Hitomi Downloader' 를 사용하는 한 명의 유저로서
추가해주셨으면 하는 것을 적어봤습니다.

1. 프로그램의 램 할당량을 사용자가 자유롭게 조절 하는 것
- 리스트가 길어질수록 메모리 점유율이 늘어남

2. 초반 부팅 과정에서 PIN 같은 걸 이용해서 비밀번호를 설정하는 것
- 가족컴을 사용하시던지 기타 등의 이유로 보안에 민감하신 분들도 계심

3. 리스트 정렬기능 추가 ex) 날짜순, 크기순, 이름순
- 파일 관리하시는 분에게는 도움이 될만한 기능

**Comment by KurtBestor** [comment]
1. 메모리 사용량은 작업 갯수에 비례해서 늘어나게 되어있어요.

1. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

   ![image](https://user-images.githubusercontent.com/14768120/80304456-e6a9a600-87f0-11ea-9901-8fafffa82a5c.png)

1. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1015#issuecomment-514908741
