### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by rarbs** [KurtBestor/Hitomi-Downloader#1923]
Hey, thanks for the work. I had a question about file names since the current options seems to be "original file name" or "Number" and when you select original file name, the files with same name seems to be overwritten/skipped. Is there a way to use "original file name" but make it so that files with duplicate names will be renamed something like file and file (1) and not being skipped/overwritten? Thanks.

**Comment by KurtBestor** [comment]
Added since v3.0
