### ISSUE TITLE
다운로드 시 변환이 뜨는건

### ISSUE THREAD

**Issue by 2GEasy** [KurtBestor/Hitomi-Downloader#1925]
화질 설정 때문인가요?

**Comment by KurtBestor** [comment]
어떤 걸 다운로드할 때 변환이 뜨나요?

**Comment by 2GEasy** [comment]
> 어떤 걸 다운로드할 때 변환이 뜨나요?

유튜브 영상을 다운받을 때 뜹니다. 늦어서 죄송합니다.

**Comment by 2GEasy** [comment]
> 어떤 걸 다운로드할 때 변환이 뜨나요?

그리고 채널 영상을 한번에 한번 받은 후에 이후에 또 채널 영상을 한번에 받을 경우 중복된 영상은 건너뛰고 받는건지 다시 처음부터 받는건지 궁금합니다.

**Comment by KurtBestor** [comment]
유튜브 고화질은 영상과 음성이 나누어져있어서 합치는 중에 변환이 떠요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1908
