### ISSUE TITLE
히요비 다운로드시 이름/압축 문제 질문

### ISSUE THREAD

**Issue by giggle1092** [KurtBestor/Hitomi-Downloader#1926]
히요비에서 직접 다운받거나, 다운로드 서버를 히요비로 두고 히토미 링크를 통해서 받을때

갤러리 정보를 auto로 두면 모든 파일이 [N / A] hiyobi (갤러리 번호) 로 표시되네요

갤러리 정보를 E(x)hentai로 바꾸면 이름이 나오기는 합니다만 기존에 쓰던 [artist] title (id)와는 조금 다르게 나와 불편함이 있습니다.

그리고 히요비를 통해 받으면 히토미 압축을 켜놔도 압축이 되지 않고, 압축란에 따로 히요비는 보이지 않습니다.

언제나 좋은 유틸 감사드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1827

**Comment by giggle1092** [comment]
상기 문제는 잘 해결됬습니다 감사합니다!

그런데 이번 버전에는 바탕화면으로 바로 경로 지정이 안되는 거 같네요

저장 폴더 설정에 들어가서 폴더를 선택하세요 창에서 왼쪽에서 바탕화면을 설정해도, C:\users\계정명\desktop를 들어가도

desktop로 경로 지정이 되지 않고 무조건 hitomi_downloaded폴더를 만드는거같습니다

감사합니다.

**Comment by KurtBestor** [comment]
재현할 수가 없네요.

**Comment by giggle1092** [comment]
다시 확인해보니 히토미 다운로더와 설정파일이 바탕화면에 바로 있을때만 일어나는것 같습니다

**Comment by KurtBestor** [comment]
다운로드 폴더를 실행파일이 있는 폴더로 설정할 순 없어요.

**Comment by giggle1092** [comment]
그렇군요 감사합니다!
