### ISSUE TITLE
익헨 쿠키 입력은 어떻게 하나요?

### ISSUE THREAD

**Issue by systembest** [KurtBestor/Hitomi-Downloader#1929]
히토미 설정에 익헨에 맞추고 원본 다운로드 옵션을 키려고하니
로그인 쿠키가 필요하다고 하는데 이 쿠키 입력은 어디서 하는지 알고 싶습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/817
