### ISSUE TITLE
기능건의입니다.

### ISSUE THREAD

**Issue by SolidElixir** [KurtBestor/Hitomi-Downloader#1932]
우선 언제나 신세지고 있습니다.

땡큐 썰.

다른게 아니라 트위터나 일부 SNS의 계정에서 그림을 다운받을때,
개인 계정이다 보니 내가 원하지 않았던 (ex. 음식 사진, 경치 사진, TV보던 중 찍은 사진 등) 이미지 파일도 가져옵니다.

그래서 그러한 짜투리들을 직접 일일히 삭제해고 다음에 '다시 주소를 추가하면' 제거했던 그림들도 다시 받아버립니다.

'이미 완료된 항목을 다시 시작으로 받으면' 이미 삭제한 사진은 다시 다운 받지 않고 새로 등록된 이미지들만 다운받게 되는데
이 부분이 언제나 가능했으면 좋겠습니다.

마지막으로 언제나 수고 많으시며
Also I 시공조아

**Comment by KurtBestor** [comment]
새로 추가하면 인식할 수 없어요. 작업 지우지 말고 남겨둬야해요.
필요 없는 파일 지우고 나서 해당 작업 우클릭 하고 `다시 시작` 해주세요.

**Comment by SolidElixir** [comment]
다시시작 기능이 본 건의를 대체하기위한 기능이었군요.

감사합니다. 썰.
