### ISSUE TITLE
유튜브 다운로드가 안되는 현상

### ISSUE THREAD

**Issue by ntspaceowl** [KurtBestor/Hitomi-Downloader#1936]
로그인 한 상태로 오늘의 첫 다운로드를 시도했는데 다운로드가 되지 않습니다.
도움 부탁 드립니다.

Invalid: [youtube] https://www.youtube.com / watch?v=ileNrPYSt4g

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://www.youtube.com/watch?v=ileNrPYSt4g
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=ileNrPYSt4g
valid: False
done: True
range: None
range_p: None
single: True
time: 1588171939.85 (Apr 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBCC08> 248 - 1920x1080 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBC6C8> 137 - 1920x1080 (1080p) 1080p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBCC08> 248 - 1920x1080 (1080p) 1080p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBCE88> 136 - 1280x720 (720p) 720p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBC108> 247 - 1280x720 (720p) 720p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBC808> 244 - 854x480 (480p) 480p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBCA48> 135 - 854x480 (480p) 480p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBC808> 244 - 854x480 (480p) 480p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0AD88> 243 - 640x360 (360p) 360p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0AE08> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0AD88> 243 - 640x360 (360p) 360p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BDFBBC0C8> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0A908> 242 - 426x240 (240p) 240p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0A888> 133 - 426x240 (240p) 240p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0A908> 242 - 426x240 (240p) 240p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0AB08> 278 - 256x144 (144p) 144p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0ACC8> 160 - 256x144 (144p) 144p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5E0AB08> 278 - 256x144 (144p) 144p webm None 30fps
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=ileNrPYSt4g

[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][0fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000022BD5D80208> 248 - 1920x1080 (1080p) 1080p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD5D80C48> 137 - 1920x1080 (1080p) 1080p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5D80208> 248 - 1920x1080 (1080p) 1080p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5CCF1C8> 136 - 1280x720 (720p) 720p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD61EE988> 247 - 1280x720 (720p) 720p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5CCFD08> 244 - 854x480 (480p) 480p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD5CCF9C8> 135 - 854x480 (480p) 480p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5CCFD08> 244 - 854x480 (480p) 480p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BE7961348> 243 - 640x360 (360p) 360p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BE7961208> 134 - 640x360 (360p) 360p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BE7961348> 243 - 640x360 (360p) 360p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD5D80D08> 18 - 640x360 (360p) 360p mp4 mp4a.40.2 0fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD60F8308> 242 - 426x240 (240p) 240p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD60F8B08> 133 - 426x240 (240p) 240p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BD60F8308> 242 - 426x240 (240p) 240p webm None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BE8DD0FC8> 278 - 256x144 (144p) 144p webm None 30fps
# stream_final <youtube_dl_test.Video object at 0x0000022BD60F8D08> 160 - 256x144 (144p) 144p mp4 None 30fps
stream is not valid
# stream_final <youtube_dl_test.Video object at 0x0000022BE8DD0FC8> 278 - 256x144 (144p) 144p webm None 30fps
stream is not valid
No videos
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "youtube_downloader", line 390, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=ileNrPYSt4g

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
다시 시도해도 안 되나요?

**Comment by ntspaceowl** [comment]
> 다시 시도해도 안 되나요?

네 동일하게.. 재시도해봐도 안됩니다. 아래 링크로 시도했습니다.
https://youtu.be/r7XS1zCtttM

링크 주신 테크니컬프리뷰 버전으로 시도해도 안되었습니다. ㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1909#issuecomment-622356037

**Comment by ntspaceowl** [comment]
> 참고해주세요: [#1909 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/1909#issuecomment-622356037)

이걸로 됩니다!! 감사합니다
