### ISSUE TITLE
Vimeo 화질 설정 기능 부탁드립니다

### ISSUE THREAD

**Issue by pb29** [KurtBestor/Hitomi-Downloader#1938]
전부 최저화질로 받아지는데 화질 설정 기능이 필요할것같아요

https://vimeo.com/39483020
https://vimeo.com/49091270
테스트해본 링크에요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by pb29** [comment]
잘 작동하네요 감사합니다
