### ISSUE TITLE
썸내일 사진만 바로 내려받을수있는 방법 없을까요?

### ISSUE THREAD

**Issue by Picachip** [KurtBestor/Hitomi-Downloader#1940]
예)를 'ABC' 라는 자료를 내려받을때. 
ABC.zip 파일로 바로 압축돼어 받으면, 그 파일이 뭔지 알아보기 힘듭니다.
그래서 저는 썸내일.jpg 사진 한장씩 일일히 만들어 주는데요.

다운로더를 사용할때마다 '썸내일 사진도 따로 받아졌으면 좋겠다~' 란 생각이 매번 듭니다.
혹시 가능하시다면, 
다운로더에 '썸내일(첫번째 파일).jpg' 사진을 클릭하면 바로 내려받거나, 
자료를 내려 받을때 .zip,썸내일.jpg 로 나눠서 받을수 있는 기능을 만들어주실순 없을까요?

p.s) 덕분에 항상 편히 다운받습니다 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1252

**Comment by Picachip** [comment]
저랑 비슷한 분이 계셨군요.
첨부해주신 링크에서 좋은 정보 얻었네요. 
감사합니다. ^^
