### ISSUE TITLE
J만화 다운로드 오류

### ISSUE THREAD

**Issue by eva3357** [KurtBestor/Hitomi-Downloader#1945]
Invalid: [jmana] https://jmana1.net / book / %EB%A7%88%EC%99%95%EB%8B%98%EC%9D%98+%EB%A7%88%EC%9D%84+%EB%A7%8C%EB%93%A4%EA%B8%B0%21+%7E%EC%B5%9C%EA%B0%95+%EB%8D%98%EC%A0%84%EC%9D%80+%EA%B7%BC%EB%8C%80%EB%8F%84%EC%8B%9C%7E

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://jmana1.net/book/%EB%A7%88%EC%99%95%EB%8B%98%EC%9D%98+%EB%A7%88%EC%9D%84+%EB%A7%8C%EB%93%A4%EA%B8%B0%21+%7E%EC%B5%9C%EA%B0%95+%EB%8D%98%EC%A0%84%EC%9D%80+%EA%B7%BC%EB%8C%80%EB%8F%84%EC%8B%9C%7E
dir: 
zip: 
type: jmana
artist: None
url: https://jmana1.net/book/%EB%A7%88%EC%99%95%EB%8B%98%EC%9D%98+%EB%A7%88%EC%9D%84+%EB%A7%8C%EB%93%A4%EA%B8%B0!+~%EC%B5%9C%EA%B0%95+%EB%8D%98%EC%A0%84%EC%9D%80+%EA%B7%BC%EB%8C%80%EB%8F%84%EC%8B%9C~
valid: False
done: True
range: None
range_p: None
single: False
time: 1588322777.74 (May 1)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
No title
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "jmana_downloader", line 85, in read
File "jmana_downloader", line 78, in name
File "jmana_downloader", line 108, in get_title
Exception: No title

Invalid: fail=True
EOT: https://jmana1.net/book/%EB%A7%88%EC%99%95%EB%8B%98%EC%9D%98+%EB%A7%88%EC%9D%84+%EB%A7%8C%EB%93%A4%EA%B8%B0%21+%7E%EC%B5%9C%EA%B0%95+%EB%8D%98%EC%A0%84%EC%9D%80+%EA%B7%BC%EB%8C%80%EB%8F%84%EC%8B%9C%7E

해당 만화는 마왕님의 마을 만들기! ~최강 던전은 근대도시~
입니다 19일 전 올라온 같은 이슈의 글에 게시물로 해보았으나 
같은 반응을 보이고 있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by eva3357** [comment]
정상적으로 읽어오며 다운도 정상적으로 되고 있습니다.
감사합니다.
