### ISSUE TITLE
히토미 페이지수 필터링 오류

### ISSUE THREAD

**Issue by cluxioric** [KurtBestor/Hitomi-Downloader#1946]
페이지수 필터링 오류가 납니다. 아무반응이없네요 ex)p<100, p>100

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1139

**Comment by cluxioric** [comment]
검색기에서 검색한 결과입니다. 아무반응이 없습니다

**Comment by KurtBestor** [comment]
어떻게 안 되는지 스크린샷 찍어서 보여주세요.

**Comment by cluxioric** [comment]
![dd](https://user-images.githubusercontent.com/64643162/80861395-4698c480-8ca9-11ea-8125-894bd5ced9d6.PNG)
이렇게 아무 작품도 안나옵니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/178

**Comment by cluxioric** [comment]
감사합니다
