### ISSUE TITLE
트위터 이미지 파일명

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#1949]
트위터에서 다운받은 이미지 파일명이 현재 날짜-링크넘버-p0.jpg 이렇게 다운받아지는데 날짜-링크넘버-p0-원본파일이름.jpg 이렇게 변경가능할까요? (예를 들면 [20-03-28] 93847576847_p0_DwjgiJDgksl.jpg 이런식으로) 지난번에 여쭤봤을때는 필요한 트윗만 빠르게 다운로드 하기 위해서 파일명을 사용하기 때문에 원본파일명으로 다운받는건 힘들다고 하셨는데, 그게 원본파일명으로 다운받는게 불가능한건지 아니면 위에 예시처럼 날짜-링크넘버-p0-원본파일이름.jpg 이렇게 다운받는것도 불가능한건지 몰라서 질문드려봅니다. (히토미 다운로더를 사용하지 않고 다운받았던 이미지들이랑 중복되는 이미지를 체크할때 필요할것 같아 건의드려요)

**Comment by KurtBestor** [comment]
중복 이미지 체크를 위해서라면 `메뉴` - `중복 이미지 찾기...` 로 검색하세요.
