### ISSUE TITLE
phantomjs issue

### ISSUE THREAD

**Issue by LoveBlonde** [KurtBestor/Hitomi-Downloader#1950]
동영상 다운할려고보면

phantomjs 에 대한 권한부여 달라고하는데

괜찮은건가요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1683

**Comment by LoveBlonde** [comment]
다시 re-access 하게 하는법 없나요 한번 거절하니까 쭉 안뜨는데 그냥 재설치하면될까요?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1683#issuecomment-624506217

**Comment by LoveBlonde** [comment]
감사합니다 !!
