### ISSUE TITLE
삭제된 계정 링크에 대해서' 다시시작'을 사용하면 기존 파일도 지우는 문제 

### ISSUE THREAD

**Issue by imjh11** [KurtBestor/Hitomi-Downloader#1953]
트위터나 픽시브는 히토미나 판다랑 다르게 갱신을 필요로 하는데 이때 다시 시작을 사용하고 있습니다. 문제는 계정이 삭제되었을대 이를 모르고 다시 시작을 해버리면 기존에 받은 파일도 지우는 문제가 있는 것으로 보입니다. 
따라서 다시시작시 계정이 삭제되었더라도 기존파일을 지우지 않게 하거나, 트위터, 픽시브 등을 위해 새로운 미디어 파일만 다운로드 하는 '업데이트','갱신' 기능이 필요할 것으로 생각됩니다.

**Comment by KurtBestor** [comment]
작업만 빨간색으로 될텐데, 파일 지워진 것 맞나요?

**Comment by imjh11** [comment]
안 지워진게 맞는것 같습니다 . 감사합니다.
