### ISSUE TITLE
invalid 라면서 폰허브 영상 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by Water-Sleep** [KurtBestor/Hitomi-Downloader#1954]
#1855 참고해서 테스트 파일 받아서 거기서 입력하면 거기선 정상적으로 다운로드가 됩니다.
이 경우엔 테스트 파일 그냥 그대로 쓰면 되나요?

정보보면 이렇게 뜨구요.

Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5e6e369640c27

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 4
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
valid: False
done: True
range: None
range_p: None
single: True
time: 1588604647.84 (May 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27
【phantomjs】 load...
【phantomjs】 loaded
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "pornhub_downloader", line 133, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "pornhub_downloader", line 247, in get_video
File "pornhub_downloader", line 178, in loadScript
Exception: Timeout

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5e6e369640c27

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1855

**Comment by KurtBestor** [comment]
테스트 파일 그대로 쓰시면 돼요
