### ISSUE TITLE
luscious가 계속 invaild라고만뜸니다

### ISSUE THREAD

**Issue by aaas1234** [KurtBestor/Hitomi-Downloader#1958]
프로그래머님께서 알려주신 Technical Preview 다운받아 썻는데도 똑같습니다 여기에 제가다운받지안은자료도 있어서 좀다를줄알았는데 똑같네요
Invalid: [luscious] https://members.luscious.net / albums / minha-colecao_372143 / 

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 6
group: False
gal_num: https://members.luscious.net/albums/minha-colecao_372143/
dir: 
zip: 
type: luscious
artist: None
url: https://members.luscious.net/albums/minha-colecao_372143/
valid: False
done: True
range: None
range_p: None
single: False
time: 1588663836.15 (May 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "luscious_downloader", line 62, in read
File "luscious_downloader", line 148, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://members.luscious.net/albums/minha-colecao_372143/

Invalid: [luscious] https://members.luscious.net

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 8
group: False
gal_num: https://members.luscious.net
dir: 
zip: 
type: luscious
artist: None
url: https://members.luscious.net
valid: False
done: True
range: None
range_p: None
single: False
time: 1588663836.09 (May 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "luscious_downloader", line 128, in get_imgs_p
TypeError: 'NoneType' object has no attribute '__getitem__'

stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "luscious_downloader", line 71, in read
File "luscious_downloader", line 113, in get_imgs
File "<decorator-gen-41>", line 2, in get_imgs_p
File "constants", line 711, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 684, in wrapper
File "luscious_downloader", line 128, in get_imgs_p
TypeError: 'NoneType' object has no attribute '__getitem__'

Invalid: fail=True
EOT: https://members.luscious.net

Invalid: [luscious] https://members.luscious.net / albums / minha-colecao_372143 / 

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
gal_num: https://members.luscious.net/albums/minha-colecao_372143/
dir: 
zip: 
type: luscious
artist: None
url: https://members.luscious.net/albums/minha-colecao_372143/
valid: False
done: True
range: None
range_p: None
single: False
time: 1588663836.37 (May 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "luscious_downloader", line 62, in read
File "luscious_downloader", line 148, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://members.luscious.net/albums/minha-colecao_372143/
 좀도와주세요

**Comment by aaas1234** [comment]
저기 제가 저기서 뭘어떡게 잘못을한건지, 아님 프로그램의 문제인지좀 알려주세요
맨처음올린것 다른것 보신것처럼 보셨을텐데 댓이없으셔서 좀 답답하네요 그리고 소스코드를 써야하는거면 어떡게 쓰는건지 알려주세요 저는 다른사이트는 되는데 이사이트만 안되니 프로그램문제인지 제문제인지 도통 모를겠습니다

**Comment by KurtBestor** [comment]
프로그램 문제인데 나중에 고치려구요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
