### ISSUE TITLE
산카쿠 컴플렉스의 다운방식에 대한 질문

### ISSUE THREAD

**Issue by Pseudo-Ray** [KurtBestor/Hitomi-Downloader#1959]
다른 사이트(예 : 픽시브 등)는 포스트를 링크하면 포스트 내부의 그림만 다운받아 오는 듯 한데,

산카쿠는 포스트 링크를 복사하면 주변 파일 (child post등 )가 다운로드 되더라구요. 
막상 그 목표 그림은 저장이 되지 않을 때도 있구요.

주변 그림을 다운받고 싶지 않은데, 혹시 해결 방안(?)이 있나요? 파일 유형 막는건 한계가 있더라구요 ㅠㅜ

예 : https://chan.sankakucomplex.com/ja/post/show/20670704 이런 링크를 복사하면, 그 링크를 클릭했을 때 메인 그림이 다운되지 않고, 주변 그림이 저장됨.

**Comment by KurtBestor** [comment]
단일 포스트는 직접 저장하면 되니까 지원하지 않아요.
