### ISSUE TITLE
pornhub 의 다운로드가 안됩니다

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader#1963]
계속 읽는중 이라고만 뜨고 다운로드는 안되네요.

로그는 이런 식입니다.

[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5d7db3a02cf4d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5d7db3a02cf4d
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5d7db3a02cf4d
【phantomjs】 load...
【phantomjs】 loaded

**Comment by KurtBestor** [comment]
참고해주세요: #1855
