### ISSUE TITLE
의심스러운 웹페이지 차단

### ISSUE THREAD

**Issue by yojiland** [KurtBestor/Hitomi-Downloader#1964]
![Blade_20200507_20_003](https://user-images.githubusercontent.com/46139267/81356551-71b35780-909f-11ea-9f74-782bd337d1f7.png)
![Blade_20200507_20_002](https://user-images.githubusercontent.com/46139267/81356553-724bee00-909f-11ea-8bf3-1bba19a84121.png)
![Blade_20200507_20_001](https://user-images.githubusercontent.com/46139267/81356554-72e48480-909f-11ea-84a2-418f9aa61492.png)
![Blade_20200507_20_004](https://user-images.githubusercontent.com/46139267/81356555-72e48480-909f-11ea-9137-3107ba52568f.png)
안녕하세요.
히토미 다운로더로 마나모아 만화를 다운받는데 비트디펜더에서 '의심스러운 웹페이지가 탐지되었습니다'라고 뜨면서 사용 프로세스로 히토미 다운로더.exe 파일이 뜹니다.
엄청나게 많이 팝업이 떴는데, 그중 몇개만 스크린샷을 찍어 올려봅니다. 주소는 cdncomplete.xyz cdnbecause.xyz등 여러가지가 떴습니다. 처음에는 phantomjs.exe로 떠서 제가 모르는 사이에 바이러스에라도 감염된것인가 싶었는데, 쭉 보다보니 어느순간부터 히토미다운로더가 사용했다고 뜨네요.
왜 이런 현상이 발생했는지 알고 싶습니다.
감사합니다.

**Comment by KurtBestor** [comment]
마나모아의 DDoS Protection 우회를 위해서 직접 페이지를 읽는데, 해당 페이지에서 읽는 웹페이지들이에요.
