### ISSUE TITLE
건의사항 유튜브라이브 아프리카 라이브가 녹화 될수있으면 좋겠습니다

### ISSUE THREAD

**Issue by sonofagold** [KurtBestor/Hitomi-Downloader#1966]
유튜브라이브 아프리카 라이브가 녹화되는 기능이 생기면 좋겠네요 ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
