### ISSUE TITLE
I can not download pictures from hitomi.la

### ISSUE THREAD

**Issue by railannad** [KurtBestor/Hitomi-Downloader#1969]
I live in China and I have read #1935  and #1031. 
I use Clash to access to hitomi.la  
The socks5 proxy port is 7891 and I have set it up

![image](https://user-images.githubusercontent.com/36919867/81501143-37e58980-9309-11ea-8598-11b9680c6db7.png)

![image](https://user-images.githubusercontent.com/36919867/81501106-1389ad00-9309-11ea-90c4-c129c6e4e560.png)

here is  Info...:

Reading... https://hitomi.la / doujinshi / lilispa---lilith-spa!-%E6%97%A5%E6%9C%AC%E8%AA%9E-1549920.html

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://hitomi.la/doujinshi/lilispa---lilith-spa!-%E6%97%A5%E6%9C%AC%E8%AA%9E-1549920.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/doujinshi/lilispa---lilith-spa!-%E6%97%A5%E6%9C%AC%E8%AA%9E-1549920.html
valid: True
done: False
range: None
range_p: None
single: False
time: 1589118618.81 (May 10)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi

**Comment by lhj5426** [comment]
原来不是我一个人哈哈  我之前也发帖说 了这个问题

**Comment by Mangel1986** [comment]
没用过SOCKS5 代理 平时用的是V2ray+vpn 用的全局代理  还是不能下载 V2ray应该也算SOCKS5？

**Comment by KurtBestor** [comment]
How about this?: 
![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)

**Comment by railannad** [comment]
> 没用过SOCKS5 代理 平时用的是V2ray+vpn 用的全局代理 还是不能下载 V2ray应该也算SOCKS5？

VPN分好多种，具体我也不太懂，先不提。 
V2ray支持HTTP也支持socks5，在窗口下方有显示端口地址，如果没有的话你可以换一家机场的v2ray客户端（我确实遇到过有的家没有显示）
![image](https://user-images.githubusercontent.com/36919867/81632800-b93e3880-943d-11ea-968e-b8fbe15cb894.png)

**Comment by railannad** [comment]
> How about this?:
> ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)

7890 is HTTP proxy port and it worked successfully,thank you 

![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)

**Comment by Mangel1986** [comment]
原来是走http代理 就可以了 我一直以为非要socks5 现在切换到http代理ok了

**Comment by Mangel1986** [comment]
[毛玉牛乳(玉之けだま)

**Comment by railannad** [comment]
> 原来是走http代理 就可以了 我一直以为非要socks5 现在切换到http代理ok了

恭喜
（炼）

**Comment by xiandi957** [comment]
> > How about this?:
> > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> 
> 7890 is HTTP proxy port and it worked successfully,thank you
> 
> ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)

老铁你怎么弄好的，能指点一下吗，用的机场是啥啊

**Comment by railannad** [comment]
> > > How about this?:
> > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > 
> > 
> > 7890 is HTTP proxy port and it worked successfully,thank you
> > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> 
> 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊

这跟你用啥机场没关系，影响端口的是软件。
我用的是clash，端口是7890。
查看端口的方法是：  左下角开始→设置→网络和internet→代理。
如图，这个东西就是端口号
![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)

**Comment by xiandi957** [comment]
> > > > How about this?:
> > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > 
> > > 
> > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > 
> > 
> > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> 
> 这跟你用啥机场没关系，影响端口的是软件。
> 我用的是clash，端口是7890。
> 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> 如图，这个东西就是端口号
> ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a

> > > > How about this?:
> > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > 
> > > 
> > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > 
> > 
> > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> 
> 这跟你用啥机场没关系，影响端口的是软件。
> 我用的是clash，端口是7890。
> 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> 如图，这个东西就是端口号
> ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)

我的不是，改成7890可以不，有没有别的联系方式啊老铁

**Comment by railannad** [comment]
> > > > > How about this?:
> > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > 
> > > > 
> > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > 
> > > 
> > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > 
> > 
> > 这跟你用啥机场没关系，影响端口的是软件。
> > 我用的是clash，端口是7890。
> > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > 如图，这个东西就是端口号
> > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> 
> > > > > How about this?:
> > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > 
> > > > 
> > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > 
> > > 
> > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > 
> > 
> > 这跟你用啥机场没关系，影响端口的是软件。
> > 我用的是clash，端口是7890。
> > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > 如图，这个东西就是端口号
> > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> 
> 我的不是，改成7890可以不，有没有别的联系方式啊老铁

我靠...你应该把下载器的端口改成Windows设置里的端口。  Windows的端口不要动，那是翻墙软件自己生成的

**Comment by xiandi957** [comment]
> > > > > > How about this?:
> > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > 
> > > > > 
> > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > 
> > > > 
> > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > 
> > > 
> > > 这跟你用啥机场没关系，影响端口的是软件。
> > > 我用的是clash，端口是7890。
> > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > 如图，这个东西就是端口号
> > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > 
> > 
> > > > > > How about this?:
> > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > 
> > > > > 
> > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > 
> > > > 
> > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > 
> > > 
> > > 这跟你用啥机场没关系，影响端口的是软件。
> > > 我用的是clash，端口是7890。
> > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > 如图，这个东西就是端口号
> > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > 
> > 
> > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> 
> 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的

老哥请问有qq没有，这说不清楚

**Comment by railannad** [comment]
> > > > > > > How about this?:
> > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > 
> > > > > > 
> > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > 
> > > > > 
> > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > 
> > > > 
> > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > 我用的是clash，端口是7890。
> > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > 如图，这个东西就是端口号
> > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > > 
> > > 
> > > > > > > How about this?:
> > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > 
> > > > > > 
> > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > 
> > > > > 
> > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > 
> > > > 
> > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > 我用的是clash，端口是7890。
> > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > 如图，这个东西就是端口号
> > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > > 
> > > 
> > > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> > 
> > 
> > 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的
> 
> 老哥请问有qq没有，这说不清楚

你设置里的端口显示是2233，你就在下载器里填2233

**Comment by xiandi957** [comment]
![image](https://user-images.githubusercontent.com/71581507/93711849-21d3b980-fb84-11ea-835a-ab48750e8b41.png)
我也用的clash，这个设置图没找到

**Comment by xiandi957** [comment]
我也用的clash，
![image](https://user-images.githubusercontent.com/71581507/93711870-5b0c2980-fb84-11ea-82b8-d4cce7368b74.png)
没找到这个

**Comment by xiandi957** [comment]
> > > > > > > > How about this?:
> > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > 
> > > > > > 
> > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > 
> > > > > 
> > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > 我用的是clash，端口是7890。
> > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > 如图，这个东西就是端口号
> > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > > > 
> > > > 
> > > > > > > > How about this?:
> > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > 
> > > > > > 
> > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > 
> > > > > 
> > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > 我用的是clash，端口是7890。
> > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > 如图，这个东西就是端口号
> > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > > > 
> > > > 
> > > > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> > > 
> > > 
> > > 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的
> > 
> > 
> > 老哥请问有qq没有，这说不清楚
> 
> 你设置里的端口显示是2233，你就在下载器里填2233

我也用的clash,
![image](https://user-images.githubusercontent.com/71581507/93711897-724b1700-fb84-11ea-9fdf-1d978acb1f05.png)
没找到这个设置

**Comment by xiandi957** [comment]
> > > > > > > > > How about this?:
> > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > 
> > > > > > 
> > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > 我用的是clash，端口是7890。
> > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > 如图，这个东西就是端口号
> > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > > > > 
> > > > > 
> > > > > > > > > How about this?:
> > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > 
> > > > > > > 
> > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > 
> > > > > > 
> > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > 我用的是clash，端口是7890。
> > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > 如图，这个东西就是端口号
> > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > > > > 
> > > > > 
> > > > > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> > > > 
> > > > 
> > > > 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的
> > > 
> > > 
> > > 老哥请问有qq没有，这说不清楚
> > 
> > 
> > 你设置里的端口显示是2233，你就在下载器里填2233
> 
> 我也用的clash,
> ![image](https://user-images.githubusercontent.com/71581507/93711897-724b1700-fb84-11ea-9fdf-1d978acb1f05.png)
> 没找到这个设置

能不能加个QQ请教下，大佬

**Comment by railannad** [comment]
> > > > > > > > > > How about this?:
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > > 
> > > > > > > 
> > > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > > 我用的是clash，端口是7890。
> > > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > > 如图，这个东西就是端口号
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > > > > > 
> > > > > > 
> > > > > > > > > > How about this?:
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > > 
> > > > > > > 
> > > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > > 我用的是clash，端口是7890。
> > > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > > 如图，这个东西就是端口号
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > > > > > 
> > > > > > 
> > > > > > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> > > > > 
> > > > > 
> > > > > 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的
> > > > 
> > > > 
> > > > 老哥请问有qq没有，这说不清楚
> > > 
> > > 
> > > 你设置里的端口显示是2233，你就在下载器里填2233
> > 
> > 
> > 我也用的clash,
> > ![image](https://user-images.githubusercontent.com/71581507/93711897-724b1700-fb84-11ea-9fdf-1d978acb1f05.png)
> > 没找到这个设置
> 
> 能不能加个QQ请教下，大佬

那个页面是Hitomi-Downloader里的，不要去clash里面找。

你需要做的事
1. 开始→设置→网络和internet→代理→查看并记住端口号

2.打开Hitomi-Downloader，把代理地址填127.0.0.1，端口填成你的端口，完毕。

这个软件做了GUI，已经很友好了，我很难想象会上github找软件的人会被这个东西难到。

如果你还是找不到，我建议你告别这个软件。

**Comment by railannad** [comment]
> > > > > > > > > > How about this?:
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > > 
> > > > > > > 
> > > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > > 我用的是clash，端口是7890。
> > > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > > 如图，这个东西就是端口号
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897a
> > > > > > 
> > > > > > 
> > > > > > > > > > How about this?:
> > > > > > > > > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 7890 is HTTP proxy port and it worked successfully,thank you
> > > > > > > > > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 老铁你怎么弄好的，能指点一下吗，用的机场是啥啊
> > > > > > > 
> > > > > > > 
> > > > > > > 这跟你用啥机场没关系，影响端口的是软件。
> > > > > > > 我用的是clash，端口是7890。
> > > > > > > 查看端口的方法是： 左下角开始→设置→网络和internet→代理。
> > > > > > > 如图，这个东西就是端口号
> > > > > > > ![image](https://user-images.githubusercontent.com/36919867/93709143-753b0d00-fb6e-11ea-9706-9bb01aa897ab.png)
> > > > > > 
> > > > > > 
> > > > > > 我的不是，改成7890可以不，有没有别的联系方式啊老铁
> > > > > 
> > > > > 
> > > > > 我靠...你应该把下载器的端口改成Windows设置里的端口。 Windows的端口不要动，那是翻墙软件自己生成的
> > > > 
> > > > 
> > > > 老哥请问有qq没有，这说不清楚
> > > 
> > > 
> > > 你设置里的端口显示是2233，你就在下载器里填2233
> > 
> > 
> > 我也用的clash,
> > ![image](https://user-images.githubusercontent.com/71581507/93711897-724b1700-fb84-11ea-9fdf-1d978acb1f05.png)
> > 没找到这个设置
> 
> 能不能加个QQ请教下，大佬

我不是大佬，没什么加的必要

**Comment by xiandi957** [comment]
好的，谢谢了

**Comment by xiandi957** [comment]
非常感谢，终于可以用了，但是YouTube好像下不了

**Comment by keshuibiliantian** [comment]
> > How about this?:
> > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> 
> 7890 is HTTP proxy port and it worked successfully,thank you
> 
> ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)

电脑版这样设置，openclash如何设置，YouTube一直转圈

**Comment by yedexiaohao** [comment]
> > > How about this?:
> > > ![image](https://user-images.githubusercontent.com/14768120/81625167-08cb3700-9433-11ea-91b1-764e285c96c2.png)
> > 
> > 
> > 7890 is HTTP proxy port and it worked successfully,thank you
> > ![image](https://user-images.githubusercontent.com/36919867/81633192-c3ad0200-943e-11ea-91df-053d84fa22a6.png)
> 
> 电脑版这样设置，openclash如何设置，YouTube一直转圈

openclash是什么   没听过

**Comment by Kautonomical** [comment]
家人们 牛笔  nice

**Comment by railannad** [comment]
> 家人们 牛笔 nice

为什么你能翻到20年的issue阿
