### ISSUE TITLE
hanime 다운로드 오류

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#1970]
최근 하니메를 다운로드 받으면 약3초 짜리 검은 화면만 나오는 영상이 다운로드 됩니다
이 영상은 어떤 플레이어로 플레이하던 3초정도의 의 검은 화면만 나오며 크기는 모두 68 KB정도 였습니다 또한 5월 11일에 다운했음에도 이 파일들의 수정된 날짜가 모두 2016년 10월 19일 오전 1시 44분으로 설정되기도 합니다.
![캡처](https://user-images.githubusercontent.com/56113395/81514701-8c215580-936b-11ea-8749-6311a8d68ea0.PNG)
( 위 4개 파일은 정상 아래 4개 파일은 비정상 )

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by ATGOS** [comment]
[Mary Jane] Venus Blood： BRAVE 3

version: 2.7h (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 301
group: False
gal_num: https://hanime.tv/videos/hentai/venus-blood-brave-3
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/venus-blood-brave-3
valid: True
done: True
range: None
range_p: None
single: True
time: 1589929639.26 (May 20)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_hanime\[Mary Jane] Venus Blood： BRAVE 3 (2410).mp4


[URLs]
[0001] https://deprecated.bitpix.top/black_screen_hd.mp4


[Messages]
stop
EOT: https://hanime.tv/videos/hentai/venus-blood-brave-3

stop
EOT: https://hanime.tv/videos/hentai/venus-blood-brave-3

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ATGOS** [comment]
항상 감사합니다!
