### ISSUE TITLE
jmana 다운이 안됩니다..

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#1972]
Can not determine type: https://jmana1.net / book?bookname=%EB%92%A4%EC%97%90+%EC%9E%88%EB%8A%94+%EC%B9%B4%EB%AC%B4%EC%9D%B4+%EC%94%A8

version: 2.8 (20-05-01 11:35:50 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://jmana1.net/book?bookname=%EB%92%A4%EC%97%90+%EC%9E%88%EB%8A%94+%EC%B9%B4%EB%AC%B4%EC%9D%B4+%EC%94%A8
dir: 
zip: 
type: 
artist: None
url: https://jmana1.net/book?bookname=%EB%92%A4%EC%97%90+%EC%9E%88%EB%8A%94+%EC%B9%B4%EB%AC%B4%EC%9D%B4+%EC%94%A8
valid: False
done: True
range: None
range_p: None
single: True
time: 1589290684.19 (May 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
Invalid: fail=False
EOT: https://jmana1.net/book?bookname=%EB%92%A4%EC%97%90+%EC%9E%88%EB%8A%94+%EC%B9%B4%EB%AC%B4%EC%9D%B4+%EC%94%A8

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by geniussjt** [comment]
네 지금도 안됩니다ㅠㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1487

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
안됩니다 
그리고 이렇게 나옵니다

Can not determine type: https://jmanatrans.com / book?bookname=2.5%EC%B0%A8%EC%9B%90%EC%9D%98+%EC%9C%A0%ED%98%B9

version: 2.8 (20-05-16 00:53:52 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://jmanatrans.com/book?bookname=2.5%EC%B0%A8%EC%9B%90%EC%9D%98+%EC%9C%A0%ED%98%B9
dir: 
zip: 
type: 
artist: None
url: https://jmanatrans.com/book?bookname=2.5%EC%B0%A8%EC%9B%90%EC%9D%98+%EC%9C%A0%ED%98%B9
valid: False
done: True
range: None
range_p: None
single: False
time: 1589726853.85 (May 17)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: https://jmanatrans.com/book?bookname=2.5%EC%B0%A8%EC%9B%90%EC%9D%98+%EC%9C%A0%ED%98%B9

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
정말 감사합니다ㅜㅜ
정말 잘 됩니다
