### ISSUE TITLE
폴더이동기능 추가건의

### ISSUE THREAD

**Issue by imjh11** [KurtBestor/Hitomi-Downloader#1973]
사용 중 다운로드 폴더를 이동시키고 싶은 경우가 있습니다.
예) SSD에 받았는데 외장하드로 이동 
이때 윈도우 탐색기에서 옮길 경우에 다운로더에서는 기존 경로에 접근하려고 하는데,
이를 수정 할 수 있게 하거나 스팀의 게임경로 변경처럼 다운로더 자체에서 파일을 이동&경로수정하는 기능이 추가 되면 편할것 같습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

이동하고 싶은 작업에서 `마우스 우 클릭` - `작업 수정... (F2)` 누른 후 폴더를 바꿔주세요:
![image](https://user-images.githubusercontent.com/14768120/81920419-21df0e00-9614-11ea-83c9-b60e8093575d.png)

**Comment by imjh11** [comment]
잘 작동합니다.
