### ISSUE TITLE
히토미 다운로드 폴더에 있는 파일 중복 체크 가능한가요?

### ISSUE THREAD

**Issue by chikurima** [KurtBestor/Hitomi-Downloader#1979]
다운로드 폴더에 AAA라는 제목의 파일이 있을때,

검색에서 AAA라는 제목이 검색되면  녹색V 표시가 되거나, 다운로드가 스킵될 수 있나요?

가능하다면 저장폴더 내부의 하위폴더도 스캔하여 스킵 가능한지요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1898
