### ISSUE TITLE
특정사이트만 느린거는 사이트 문제인가요?

### ISSUE THREAD

**Issue by ijs4230** [KurtBestor/Hitomi-Downloader#1981]
요 며칠 히토미랑 폰허브만 엄청 느려서(사이트속도+다운로드속도) 이용이 불가능한 수준인데
사이트 속도가 느린건 트래픽이 많다거나 그런거 같은데
다운로드 속도도 느린게 사이트 트래픽량?이랑 관련이 있나요?

**Comment by KurtBestor** [comment]
어떤 ISP 쓰시나요?

**Comment by ijs4230** [comment]
SK 브로드밴드쓰고있어요 시간대 따라서 오락가락하네요

**Comment by KurtBestor** [comment]
SK 문제 같아요. 해외망 문제는 전부 SK 네요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1340, https://github.com/KurtBestor/Hitomi-Downloader/issues/1385, https://github.com/KurtBestor/Hitomi-Downloader/issues/1475
