### ISSUE TITLE
니코동의 만화는 다운이 안되나요?

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#1982]
항상 프로그램 잘 쓰고 있습니다 
새삼 감사드립니다
니코동이 영상은 잘 되는데 만화는 다운이 안되는건가요?
혹시 추가하실 계획은 없으신지요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/287

시간 나면 추가하려구요.
