### ISSUE TITLE
Can't load cookies

### ISSUE THREAD

**Issue by VanTuz5** [KurtBestor/Hitomi-Downloader#1986]
When I tried to load cookies, the program wrote this
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 6959, in foo
  File "youtube_dl\utils", line 2762, in load
  File "_MozillaCookieJar", line 55, in _really_load
LoadError: u'C:/Users/mamam/Desktop/cookies.txt' does not look like a Netscape format cookies file

**Comment by KurtBestor** [comment]
Can i see the content of the cookies.txt?

**Comment by KurtBestor** [comment]
Can I see the content of the `cookies.txt`?

**Comment by VanTuz5** [comment]
![image](https://user-images.githubusercontent.com/39066280/82910440-5091a880-9f73-11ea-9367-e7b558511818.png)

**Comment by KurtBestor** [comment]
See: https://github.com/ytdl-org/youtube-dl/issues/4539
