### ISSUE TITLE
검색기에서 다운 안되는 현상.

### ISSUE THREAD

**Issue by 4w97euiosha** [KurtBestor/Hitomi-Downloader#1987]
어떤 거는 되고 어떤거는 안됩니다.
대체로 안되는게 많은거 같습니다.

히토미 서버 자동
프록시는 꺼짐
dpi 우회 켜짐

안되서 직접 주소 복사해서 들어가니
잘 들어가지고

https://hitomi.la / galleries / 1621986.html
에서
https://hitomi.la/manga/himitsu-no-amayadori-%E6%97%A5%E6%9C%AC%E8%AA%9E-1621986.html
주소명이 바뀌네요.

안되는거 예 입니다.

Invalid: [hitomi] https://hitomi.la / galleries / 1621986.html

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 11
group: False
gal_num: https://hitomi.la/galleries/1621986.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/galleries/1621986.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1589704174.75 (May 17)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:False)
Find in HK...
not found in HK
max_page = 24684
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3.1
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.2
Brute-force search: 9.3
Brute-force search: 10.8
Brute-force search: 12.1
Brute-force search: 13.9
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:True)
Find in HK...
not found in HK
max_page = 35921
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7
Brute-force search: 8
Brute-force search: 9
Brute-force search: 10.3
Brute-force search: 11.6
Brute-force search: 14.1
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/galleries/1621986.html

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:False)
Find in HK...
not found in HK
max_page = 24684
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.7
Brute-force search: 9.9
Brute-force search: 11.6
Brute-force search: 12.8
Brute-force search: 14.2
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:True)
Find in HK...
not found in HK
max_page = 35921
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6.2
Brute-force search: 7.3
Brute-force search: 8.4
Brute-force search: 9.7
Brute-force search: 11.0
Brute-force search: 13.7
Brute-force search: 17.4
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/galleries/1621986.html

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:False)
Find in HK...
not found in HK
max_page = 24736
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7
Brute-force search: 8
Brute-force search: 9.4
Brute-force search: 10.4
Brute-force search: 11.4
Brute-force search: 12.4
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/galleries/1621986.html

get_imgs server: hitomi
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:False)
Find in HK...
not found in HK
max_page = 24897
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7.1
Brute-force search: 8.1
Brute-force search: 9.1
Brute-force search: 10.1
Brute-force search: 11.1
Brute-force search: 12.1
Brute-force search: 13.1
Brute-force search: 14.1
Brute-force search: 15.1
Brute-force search: 16.1
Brute-force search: 17.2
Brute-force search: 18.2
Brute-force search: 19.5
Brute-force search: 21.0
Brute-force search: 22.0
Brute-force search: 26.2
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/galleries/1621986.html)
Find_ehen(id:1621986, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/galleries/1621986.html

**Comment by KurtBestor** [comment]
설정에서 서버를 바꾸세요.

**Comment by 4w97euiosha** [comment]
> 
> 
> 설정에서 서버를 바꾸세요.

고맙습니다.

**Comment by 4w97euiosha** [comment]
> 
> 
> 설정에서 서버를 바꾸세요.

되는 것도 있었는데 여전히 안되는 것은 여전히 invalid 입니다.
이헨쪽은 파일 크기가 작게 나와서 가능하면 히토미로 받고 싶습니다.

참고로 인터넷 skb 쓰고 있는데, 요즘 해외망 속도 엄청 안 좋거든요. 혹시 이거 때문인가요?
그냥 웹으로는 들어가지는걸로 봐서 아닌거 같기도 하고..
날짜별로 되는 날 안되는 날 있는거 같기도 하고요..
위에 조건과 같고, 아래에 있는 글인 wgcf 이거도 해봤는데 소용없었습니다.
시간 나실 때 봐주시면 감사드리겠습니다.

설정 - 히토미 탭 - 서버
수동 서버1, 서버2, 서버3, 이헨, 히요비
각각 사례입니다.

----
서버1
----
Invalid: [hitomi] https://hitomi.la / gamecg / big-breast-party-ntr-1639511.html

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: https://hitomi.la/gamecg/big-breast-party-ntr-1639511.html
dir: 
zip: 
type: hitomi
artist: None
url: https://hitomi.la/gamecg/big-breast-party-ntr-1639511.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1590183280.14 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi:la
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:https://hitomi.la/gamecg/big-breast-party-ntr-1639511.html)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.2
Brute-force search: 9.2
Brute-force search: 11.2
Brute-force search: 14.8
Brute-force search: 15.8
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:https://hitomi.la/gamecg/big-breast-party-ntr-1639511.html)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
max_page = 36313
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.7
Brute-force search: 10.2
Brute-force search: 11.4
Brute-force search: 12.4
Brute-force search: 13.4
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

stop
Invalid: fail=False
stop
EOT: https://hitomi.la/gamecg/big-breast-party-ntr-1639511.html

----
서버2
----

Invalid: [hitomi] #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: [Takeda Hiromitsu] Big Breast Party NTR (1639511)
dir: 
zip: 
type: hitomi
artist: None
url: 1639511
valid: False
done: True
range: None
range_p: None
single: False
time: 1590183406.31 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
갤러리 넘버: 1639511

제목: Big Breast Party NTR

작가: takeda hiromitsu

그룹: N/A

타입: gamecg

시리즈: N/A

캐릭터: N/A

태그: sample, female:big breasts, female:lingerie, female:milf, female:mind break, female:mind control, female:nun, female:ponytail, female:stockings, female:teacher, male:bbm

언어: N/A


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi:aa
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7.1
Brute-force search: 8.3
Brute-force search: 9.4
Brute-force search: 10.6
Brute-force search: 13.9
Brute-force search: 15.0
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=False
stop
EOT: #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)


----
서버3
----
Invalid: [hitomi] #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: [Takeda Hiromitsu] Big Breast Party NTR (1639511)
dir: 
zip: 
type: hitomi
artist: None
url: 1639511
valid: False
done: True
range: None
range_p: None
single: False
time: 1590183640.88 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
갤러리 넘버: 1639511

제목: Big Breast Party NTR

작가: takeda hiromitsu

그룹: N/A

타입: gamecg

시리즈: N/A

캐릭터: N/A

태그: sample, female:big breasts, female:lingerie, female:milf, female:mind break, female:mind control, female:nun, female:ponytail, female:stockings, female:teacher, male:bbm

언어: N/A


[File Names]



[URLs]



[Messages]
get_imgs server: hitomi:ba
FINAL SERVER: hitomi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.3
Brute-force search: 9.4
Brute-force search: 10.6
Brute-force search: 11.6
Brute-force search: 16.7
can not founded in 100 attempts
get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
max_page = 36313
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6.1
Brute-force search: 7.1
Brute-force search: 8.1
Brute-force search: 9.2
Brute-force search: 10.5
Brute-force search: 11.8
Brute-force search: 12.9
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

stop
Invalid: fail=False
stop
EOT: #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)


----
이헨
----
Invalid: [hitomi] #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: [Takeda Hiromitsu] Big Breast Party NTR (1639511)
dir: 
zip: 
type: hitomi
artist: takeda hiromitsu
url: 1639511
valid: False
done: True
range: None
range_p: None
single: False
time: 1590183798.52 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
갤러리 넘버: 1639511

제목: Big Breast Party NTR

작가: takeda hiromitsu

그룹: N/A

타입: gamecg

시리즈: N/A

캐릭터: N/A

태그: sample, female:big breasts, female:lingerie, female:milf, female:mind break, female:mind control, female:nun, female:ponytail, female:stockings, female:teacher, male:bbm

언어: N/A


[File Names]



[URLs]



[Messages]
get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5.1
Brute-force search: 6.3
Brute-force search: 7.3
Brute-force search: 8.4
Brute-force search: 9.4
Brute-force search: 10.4
Brute-force search: 12.1
Brute-force search: 14.5
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
max_page = 36313
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7.1
Brute-force search: 8.2
Brute-force search: 9.2
Brute-force search: 10.6
Brute-force search: 12.1
Brute-force search: 14.4
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5
Brute-force search: 6
Brute-force search: 7
Brute-force search: 8
Brute-force search: 9.5
Brute-force search: 10.6
Brute-force search: 11.7
Brute-force search: 13.6
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
max_page = 36313
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4.3
Brute-force search: 5.6
Brute-force search: 6.6
Brute-force search: 7.7
Brute-force search: 8.7
Brute-force search: 9.7
Brute-force search: 10.8
Brute-force search: 12.5
Brute-force search: 13.8
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3.1
Brute-force search: 4.1
Brute-force search: 5.1
Brute-force search: 6.1
Brute-force search: 7.1
Brute-force search: 8.2
Brute-force search: 10.2
Brute-force search: 11.2
Brute-force search: 12.7
Brute-force search: 14.7
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24960
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5.1
Brute-force search: 6.2
Brute-force search: 7.3
Brute-force search: 8.4
Brute-force search: 9.5
Brute-force search: 10.7
Brute-force search: 11.7
Brute-force search: 13.1
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
max_page = 36313
Brute-force search: 1
Brute-force search: 2
Brute-force search: 3
Brute-force search: 4
Brute-force search: 5.2
Brute-force search: 6.2
Brute-force search: 7.2
Brute-force search: 8.4
Brute-force search: 9.7
Brute-force search: 11.0
Brute-force search: 12.8
Brute-force search: 14.5
can not founded in 100 attempts
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1025, in ehen_imgs
TypeError: 'NoneType' object is not iterable

FINAL SERVER: ehen
ehen_url: None
imgs: 0
cannot concatenate 'str' and 'NoneType' objects
stop
Traceback (most recent call last):
File "utils", line 868, in start
File "utils", line 918, in start_
File "hitomi_downloader", line 768, in read
TypeError: cannot concatenate 'str' and 'NoneType' objects

Invalid: fail=False
EOT: #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

----
히요비
----

Invalid: [hitomi] #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
gal_num: [Takeda Hiromitsu] Big Breast Party NTR (1639511)
dir: 
zip: 
type: hitomi
artist: None
url: 1639511
valid: False
done: True
range: None
range_p: None
single: False
time: 1590184070.6 (May 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
갤러리 넘버: 1639511

제목: Big Breast Party NTR

작가: takeda hiromitsu

그룹: N/A

타입: gamecg

시리즈: N/A

캐릭터: N/A

태그: sample, female:big breasts, female:lingerie, female:milf, female:mind break, female:mind control, female:nun, female:ponytail, female:stockings, female:teacher, male:bbm

언어: N/A


[File Names]



[URLs]



[Messages]
get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

get_imgs server: hiyobi
Traceback (most recent call last):
File "hitomi_downloader", line 696, in read
File "hitomi_downloader", line 561, in get_imgs
File "hiyobi_downloader", line 23, in pop_img_hiyobi
File "downloader", line 385, in read_html
Exception: 404

FINAL SERVER: hiyobi
always use ehen
get_imgs server: ehen
ehen_imgs(ex:False, url:1639511)
Find_ehen(id:1639511, ex:False)
Find in HK...
not found in HK
max_page = 24961
get_imgs server: ehen
ehen_imgs(ex:True, url:1639511)
Find_ehen(id:1639511, ex:True)
Find in HK...
not found in HK
Traceback (most recent call last):
File "hitomi_downloader", line 734, in read
File "hitomi_downloader", line 563, in get_imgs
File "hitomi_downloader", line 1028, in ehen_imgs
Exception: URL not found

stop
Invalid: fail=False
stop
EOT: #-*- [Takeda Hiromitsu] Big Breast Party NTR (1639511)

**Comment by KurtBestor** [comment]
갤러리 정보를 `Auto` 로 바꾸세요.

**Comment by 4w97euiosha** [comment]
> 
> 
> 갤러리 정보를 `Auto` 로 바꾸세요.

물어본게 부끄러울 정도로 그냥 돼버리네요.. ㅡㅡ;;
죄송하고 감사합니다.
