### ISSUE TITLE
토렌트 다운방식이 궁금합니다.

### ISSUE THREAD

**Issue by dusqhd** [KurtBestor/Hitomi-Downloader#1988]
우연찮게 마그넷 주소로 다운된다는 사실을 알았습니다.

편하다 싶었지만 한편으론 토렌트의 특성상 업로드나 시드공유가 되고있는건 아닌지 걱정되더군요

히토미 다운로더로 토렌트를 다운했을때 시드공유나 업로드는 어떻게 되는 건가요 ?

다운로더가 완료되고 난 후에는 시더가 삭제되거나 공유가 자동적으로 종료되는것인지 

다운로더 중에는 보통의 토렌트와같이 업로드되면서 다운되는것인지 궁금합니다.

다운로드 원리좀 알려주세요.

항상 프로그램 잘 사용하고 있습니다.

감사합니다

**Comment by KurtBestor** [comment]
업로드를 하지 않으면 상대편에서 공유를 해주지 않기 때문에 다운로드 하는 중엔 업로드를 하고, 다운로드가 완료되면 업로드를 하지 않아요.
