### ISSUE TITLE
단축키 추가 건의

### ISSUE THREAD

**Issue by ZetabS** [KurtBestor/Hitomi-Downloader#1989]
우클릭했을 때 나오는
![20200517_231200](https://user-images.githubusercontent.com/55911793/82151691-b6a56e00-9897-11ea-8a42-dbe0196eadf7.png)
이 태그 각각의 단축키가 추가되면 좋겠습니다.

태그 하나하나 우클릭하고 선택하기 귀찮은데
링크 주소 복사는 Ctrl+C, 잠금은 Ctrl+Q, 코멘트 수정은 C 같은 단축키처럼
Ctrl+1하면 빨간색, Ctrl+2하면 주황색 이런 식으로 단축키를 만들어주셨으면 좋겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ZetabS** [comment]
Ctrl+1~7 모두 테스트해봤고 정상적으로 작동합니다.
추가해주셔서 감사합니다.
