### ISSUE TITLE
hanime 다운받으면 3초짜리 영상만 다운되네요

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#1990]
정보 눌러서 나온 내역입니다.

[BOMB! CUTE! BOMB!] Melty's Quest 2

version: 2.8 (20-04-04 05:35:08 GMT+0)
platform: Windows-10-10.0.18362
order: 5
group: False
gal_num: https://hanime.tv/videos/hentai/melty-s-quest-2
dir: hitomi_downloaded_hanime
zip: 
type: hanime
artist: None
url: https://hanime.tv/videos/hentai/melty-s-quest-2
valid: True
done: True
range: None
range_p: None
single: True
time: 1589727329.87 (May 17)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_hanime\[BOMB! CUTE! BOMB!] Melty's Quest 2.mp4

[URLs]
[0001] https://deprecated.bitpix.top/black_screen_hd.mp4

[Messages]
stop
EOT: https://hanime.tv/videos/hentai/melty-s-quest-2

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1970

**Comment by cshipa** [comment]
감사합니다.
