### ISSUE TITLE
클립보드로 복사되는 URL 모으기, 새로운 일러스트만 받는 기능에 건의 해봅니다.

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader#1993]
고생하시는 개발자님
히토미로 검색할 땐 다 괜찮은데
자료가 없는 경우에는 익헨으로 찾아보면 있습니다.
그럴 땐 링크 복사해서 넣어야하는데 그건 정말 귀찮은 일이잖아요?
게다가 일러스트 사이트(픽시브, sankaku)  작가나 태그 넣어서 다운받는건 좀 그렇고
그렇다고 마음에 드는 일러스트를 계속 복사해서 넣기에는 힘든 일이고요.

https://blog.naver.com/tipsware/220968054220
https://blog.naver.com/tipsware/221901703319

이걸로 히토미 프로그램에도 넣으면 어떨까 해서 건의합니다.

물론 저 프로그램을 써도 되지만 한 프로그램으로 합치는게 더 좋을테니까요.

첨언- 단축키나 링크 복사 클릭 할 필요 없이 오른쪽 마우스 버튼으로 이미지, 링크를 누르기만 해도 복사하는 것도 추가해야할 것 같아요~
ㅡㅡㅡㅡㅡㅡㅡㅡ
추가로 건의 더 해보자면.
픽시브 작가 폴더에 마음에 안드는 자료들 지웠는데 거기서 몇개월 후에 새로운 자료를 다시 다운받으면 삭제했던 것도 다시 복구 되잖아요. 그래서 픽시브 id를 참고해서 받기 전에 받았던 자료에 높은 id가 있으면 낮은 id는 다운 받지않고 그보다 높은 id를 다운 받는 기능을 추가하면 어떨까요?

대부분 일러스트 사이트들(sankaku, gelbooru)도 id를 쓰고 있고요.

그럼 개발자님 보람찬 하루를 보내세요~

**Comment by KurtBestor** [comment]
`옵션` - `클립보드에서 자동 추가` 체크해주세요.
