### ISSUE TITLE
특정 imgur.com의 주소가 되다 안되다 합니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#1995]
수정 완료

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
정상 작동 합니다~!
고칠 수 있으면 스스로 고쳐보겠는데, 배우질 못해서 늘 신세를 지네요.
