### ISSUE TITLE
site-support-request

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#1997]
https://regbu.net/

혹시 추가해주실 수 있으신가요?

그리고 Kurt Bestor님 그림 그리신 것들은 트위터나 픽시브 말고 다른 곳에도 올리시나요? 

그림 잘 그리시는데 너무 드문드문 올리셔서 여쭤봅니다.

다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
Pixiv 는 거의 안 쓰고, [Patreon](https://www.patreon.com/KurtBestor) 에도 올려요.

**Comment by yuchan39** [comment]
아, 그렇군요. 답변해주셔서 감사합니다.
