### ISSUE TITLE
추정입니다만 히토미 다운로더가 먼저 실행중일 시 SecretDNS의 기능을 사용할 수 없습니다.

### ISSUE THREAD

**Issue by vkrnlrmrak1** [KurtBestor/Hitomi-Downloader#1998]
히토미 다운로더를 종료하고 해당 프로그램의 기능을 실행시키니 제대로 뜨는 걸 보니
확실한거 같긴한데 (5회 동일 테스트 시행) 한번 확인해 주셨으면 합니다.

**Comment by wooeorbs** [comment]
굿바이 DPI 우회를 켜서 그런거에요 끄세요

**Comment by wooeorbs** [comment]
https://namu.wiki/w/GoodbyeDPI 참고하세요

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `DPI 우회` 를 끄세요.
