### ISSUE TITLE
여기 포럼에서 페이지 이미지 다운 방법을 읽어서 해보고 다운로더에 적힌 설명대로 해도 오류나네요.

### ISSUE THREAD

**Issue by xhfh1092** [KurtBestor/Hitomi-Downloader#2000]
https://gelbooru.com/index.php?page=post&s=list&tags=fumihiko_%28pixiv2658856%29

분명 url에 적어서 했는데 계속 안되서 혹시나 기호가 제대로 안 적혀서 그런가 싶어서 20번 이상을 시도했는데 안되서 이렇게 물어봅니다..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/62

**Comment by xhfh1092** [comment]
감사합니다. 덕분에 해결되었어요.

**Comment by xhfh1092** [comment]
> 참고해주세요: #62
감사합니다. 덕분에 해결되었어요
