### ISSUE TITLE
2.8 업데이트 이후 프로그램 구동 속도가 느려졌습니다

### ISSUE THREAD

**Issue by cokasss** [KurtBestor/Hitomi-Downloader#2005]
처음 프로그램을 실행할 때 약 6초 정도 뒤에 관리자 권한 실행 여부를 묻고, 예를 누르면 다시 6초 정도가 흘러야 프로그램이 구동됩니다.
혹시나 해서 다른 경로에 새로 다운로드 받아서 실행해봐도 역시나 같은 증상이었습니다.

실험삼아 2.7h 버전을 받아보았는데 해당 버전은 빠르게 실행이 되었습니다.

혹시 프로그램 용량이 2.7버전 당시 20메가바이트정도였다가 이번 2.8에서 70메가바이트로 올라간 게 영향을 주는 건가요?

**Comment by KurtBestor** [comment]
여러가지 이유로 패커를 [py2exe](https://www.py2exe.org/) 에서 [PyInstaller](https://www.pyinstaller.org/) 로 바꿨는데, 구동 원리 상 PyInstaller 가 더 느려서 그래요.
