### ISSUE TITLE
the program downloads corrupted files

### ISSUE THREAD

**Issue by VanTuz5** [KurtBestor/Hitomi-Downloader#2006]
I loaded cookies into the program, set it to download the original files, but after that all the downloaded files were corrupted

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by VanTuz5** [comment]
[info.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/4701751/info.txt)

**Comment by KurtBestor** [comment]
How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by VanTuz5** [comment]
Doesn’t download anything at all. In addition, recently, the Exhentai recently updated something, because many such programs stopped working normally.

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by VanTuz5** [comment]
[info.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/4703468/info.txt)

**Comment by KurtBestor** [comment]
It seems like your cookies are expired. Reload cookies and try again.

**Comment by VanTuz5** [comment]
It worked on test version, but new version still downloads corrupted files.

**Comment by KurtBestor** [comment]
You can pause the task by clicking the pause button before closing the program: 
![image](https://user-images.githubusercontent.com/14768120/83295187-865fb700-a229-11ea-81eb-87ffb86834c2.png)

Does the test version create damaged files also?

**Comment by VanTuz5** [comment]
I know, but after changing the ip address, the download did not continue. I had to change it due to an exhantai limit. And now nothing is downloading again.

**Comment by KurtBestor** [comment]
For large galleries, One of the following options are recommended:
- Uncheck `Download original images`
- Archive Download
- Torrent Download

It also supports torrent. Paste the following torrent link into the downloader and it should work:
```
https://ehtracker.org/get/1410140/dc5e7142af5997b61379ff204a180b6e247b6650.torrent
```
