### ISSUE TITLE
다운로드 방식 업데이트 필요

### ISSUE THREAD

**Issue by nadesion** [KurtBestor/Hitomi-Downloader#2007]
pornhub에서 영상이 다운로드 되지 않습니다. 

아마도 영상 출력이 .ts 파일 여러개를 쪼개서 보내는 것으로 변경된 것으로 보입니다. 

다른 플러그인으로 받아보면 정상적으로 받아지는 것으로 봐서는 뭔가 방법이 있는 것 같습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by honeybear134hnom** [comment]
읽는 중... https://www.pornhub.com / view_video.php?viewkey=ph5b96404177500

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: -78
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
valid: True
done: False
range: None
range_p: None
single: True
time: 1590819156.79 (May 30)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
【phantomjs】 load...
【phantomjs】 loaded

**Comment by honeybear134hnom** [comment]
저도 pornhub에서 영상을 다운로드해봤지만 무한 로딩상태에서 풀리지 않았습니다.

읽는 중... https://www.pornhub.com / view_video.php?viewkey=ph5b96404177500

version: 2.8 (20-03-27 19:50:23 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: -78
group: False
gal_num: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
valid: True
done: False
range: None
range_p: None
single: True
time: 1590819156.79 (May 30)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
【phantomjs】 load...
【phantomjs】 loaded
Video
loadScript: https://www.pornhub.com/view_video.php?viewkey=ph5b96404177500
【phantomjs】 load...
【phantomjs】 loaded

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1842
