### ISSUE TITLE
마나모아 등 다수 폴더 압축 방식 건의 

### ISSUE THREAD

**Issue by totle91** [KurtBestor/Hitomi-Downloader#2008]
안녕하세요 개발자님, 프로그램 잘 쓰고 있습니다. 감사합니다!

지금의 프로그램은 마나모아 등의 사이트에서 다운받을때 많은 폴더가 생성될 경우 통으로 한 폴더에 압축이 되는데 각각 폴더를 압축하는 기능을 만드는게 가능할까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/154
