### ISSUE TITLE
이미 다운로드 리스트에 있는 주소는 추가가 아닌 '다시시작(S)'가 되었으면 좋겠어요.

### ISSUE THREAD

**Issue by SolidElixir** [KurtBestor/Hitomi-Downloader#2010]
또다시 건의사항 하나 올려드립니다, 센세.

이미 다운로드 리스트에 추가되어있는 주소에 대해서 똑같이 추가할 시에 링크가 또 한번 '추가'되는 것이 아닌 '다시시작'이 되면서 '리스트의 제일 상단'으로 올라갔으면 좋겠습니다.

'클립보드에서 자동 추가'도 똑같이 말이죠.

리스트가 쌓이다 보니까 하나하나 찾는데 시간이 너무 오래 걸리더라구요.

![잘쓰고있어요](https://user-images.githubusercontent.com/64474625/83249802-1a0d9500-a1e2-11ea-8eb2-dca067bf0c65.png)

다시 한번 매번 잘쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

이미 있는 걸 추가하면 리스트에서 해당 작업 선택하고 스크롤 이동하도록 했어요.

**Comment by SolidElixir** [comment]
빠른 피드백 감사합니다. 선생님.

만수무강하시길.
