### ISSUE TITLE
사이트 추가 요청드립니다.

### ISSUE THREAD

**Issue by playground-SCC-kms** [KurtBestor/Hitomi-Downloader#2011]
https://yande.re/post 와 https://konachan.net/post 이 두 사이트 페이지 다운로드 방식으로 원본 이미지 받게 지원해주실 수 있나요?
항상 잘 쓰고 있습니다. 감사합니다.

**Comment by playground-SCC-kms** [comment]
오랫동안 답장을 못드려 죄송합니다.
아프리카 영상 다운로드 문제는 영상을 끝까지 비교해보니 플레이어의 시간만 다르게 나타날 뿐 큰 이상은 없었습니다.

그리고 이번에 yande.re 사이트 추가해 주셔서 감사합니다.
그런데 막상 사용을 해보려 하니 어떤식으로 검색을 넣어야 다운로드가 되는지 잘 모르겠습니다.

혹시 가능하시다면 예시를 하나 작성해 주실 수 있나요?
(사이트 페이지 범위를 통해 이미지 다운로드를 받고 싶습니다.)

프로그램 개선하시고 개발하시는데 고생이 많으실텐데, 항상 감사히 잘 쓰고 있습니다.
답변 잘 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
다음과 같이 태그 검색 결과나 풀 주소를 입력해주세요:
- https://yande.re/post?tags=majo_no_tabitabi
- https://yande.re/pool/show/97502

**Comment by playground-SCC-kms** [comment]
예시를 알려주셔서 감사합니다.

혹시 죄송하지만 풀 주소가 아닌 포스트 주소(https://yande.re/post)로
페이지 범위 다운로드를 지원해주실 수 있을까요?

예시로 얀데레 포스트 주소 2페이지부터 100페이지까지 https://yande.re/post?page=2 ~ 100 << 이런 형식으로 해당 페이지에 있는 이미지들을 원본 화질로 다운받을 수 있게끔 가능하신지 여쭙고 싶습니다.
