### ISSUE TITLE
2.8 업데이트 이후로 실행이 되지 않습니다.

### ISSUE THREAD

**Issue by Rainybreeze** [KurtBestor/Hitomi-Downloader#2018]
![주석 2020-05-31 162426](https://user-images.githubusercontent.com/60471759/83346890-7d6f0280-a35b-11ea-9ab6-5d435a699ee8.png)
2.8 업데이트 후 파일을 실행하면 1분 정도 컴퓨터 프리징이 일어난 다음 fatal error와 함께 실행이 되지 않습니다.
처음에 나스에도 넣어놨나 해서 c드라이브에 넣어놔도 안되서 2.7h버전으로 다시 받아 실행하니 다시 정상적으로 실행됩니다.

선생님 혹시 오류에 대한 해결방법을 알고 계시나요?

로그파일 자체가 생성이 안되서 오류창 스크린샷을 남깁니다

**Comment by KurtBestor** [comment]
관리자 권한으로 실행하면 어떻게 되나요?

**Comment by Rainybreeze** [comment]
방금 관리자권한으로 실행해봤는데 똑같네요
일주일전에 산 노트북으로 돌려봐도 같은 에러가 나네요

**Comment by KurtBestor** [comment]
v2.8a 는 어떤가요?

**Comment by Rainybreeze** [comment]
카스퍼스키 보안레벨 제일 낮은걸로 맞춰서 쓰고 있어요

**Comment by KurtBestor** [comment]
음 저도 카스퍼스키 쓰는데 재현할 수가 없네요. 임시폴더 (`%temp%`) 쓰기 금지되어있나요?

**Comment by Rainybreeze** [comment]
아뇨 금지되어있지는 않아요

**Comment by KurtBestor** [comment]
[v3.0](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.0) 은 어떤가요?

**Comment by Rainybreeze** [comment]
오 이제 되네요
잘쓰겠습니다 충성충성^^7
