### ISSUE TITLE
기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by hentai-redcat** [KurtBestor/Hitomi-Downloader#2019]
안녕하세요. 히토미 다운로더를 매우 유용하게 사용중인 한 사용자입니다.
앞서 먼저 감사인사를 드리며, 기능추가 건의드립니다.

https://www.xvideos.com 에서 

https://www.xvideos.com/profiles/{ID}#_tabVideos
와 같은 특정 업로더에 대한 url 다운로드 시 영상 전체 다운로드 기능과

https://www.xvideos.com/?k={키워드}
와 같은 특정 키워드에 대한 url 다운로드 시 영상 전체 다운로드 기능 요청드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
