### ISSUE TITLE
[Pixiv] Retrieve original data

### ISSUE THREAD

**Issue by FenixRevival** [KurtBestor/Hitomi-Downloader#2021]
Hitomi Downloader when downloading picture give the _current_ date & hour value to :
- Creation date
- Modified on

PixivUtil2 retrieve the original "modified on" and put it in the retrieved picture.

Could it be possible to retrieve that original date in HitomiDL too?

**Comment by KurtBestor** [comment]
What do you use it for?

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Now it keeps the original "modified on".

**Comment by FenixRevival** [comment]
Perfect!! Thank you!
