### ISSUE TITLE
픽시브 gif파일 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by tsi03136** [KurtBestor/Hitomi-Downloader#2022]
픽시브측에서 막아두게끔 패치했나요?

예전에는 히토미 다운로더로 움짤 받아졌던걸로 기억하는데 이제는 홈페이지에서 손으로 받기도 안되고
히토미 다운로더로도 받아지지 않습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
