### ISSUE TITLE
기능 추가 건의 드립니다.

### ISSUE THREAD

**Issue by flclrhfem66** [KurtBestor/Hitomi-Downloader#2027]
안녕하세요. 너무나 편리한 다운로더 덕분에 언제나 감사드립니다.

혹시 다운받은 기록만을 표시할 수는 없을지 조심스럽게 건의드립니다.
현재 다운로더 검색기에서 검색 시 소장 중인 파일들이 표시되고 있기는 한데
파일을 다른 곳으로 옮길 경우 해당 기록이 사라지는 탓에
동일한 파일을 무심코 다시 받게 되는 경우가 자주 발생하여 건의드리고 싶습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/998#issuecomment-514904211
