### ISSUE TITLE
웹툰 다운로드시 기능 추가 건의

### ISSUE THREAD

**Issue by Tzuyuman** [KurtBestor/Hitomi-Downloader#2029]
안녕하세요, 덕분에 좋은 프로그램 정말 잘 쓰고있습니다.
다름이 아니라 웹툰을 다운받아 소장할 때 png파일로 한번에 합쳐서 저장하는 기능이 구현 가능할까 하여 건의드려봅니다.

다른분이 만드셨던 웹툰 다운로더에서 사용하던 기능인데 코드만 남기시고 더이상의 업데이트를 하지 않으셔서 히토미 다운로더에 추가 가능한 기능인지 여쭙고 싶습니다.

https://github.com/liush79/naver-webtoon

항상 감사하고 힘든 요즘 잘 이겨내시길 바라겠습니다. 화이팅!

**Comment by KurtBestor** [comment]
PNG 하나로 합치면 장점이 있나요?

**Comment by Tzuyuman** [comment]
아 제가 잘 몰라서 그러는데 합치면 단점이 더 많은가요..? 소장하기 편하고 보기 편하지 않을까 생각했었는데...

2020년 6월 10일 (수) 오후 2:29, Kurt Bestor <notifications@github.com>님이 작성:

**Comment by KurtBestor** [comment]
PNG 는 용량이 JPEG 에 비해서 크고, 하나로 합치는 거라면 이미 PDF 로 합치는 걸 지원해요.

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/399#issuecomment-457890198, https://github.com/KurtBestor/Hitomi-Downloader/issues/441#issuecomment-457890302

**Comment by Tzuyuman** [comment]
좋은 프로그램에 피드백까지 정말 감사드립니다. 코로나때문에 힘든 요즘 덥기까지 하네요.. 건강 유의하시고 행복한 하루 되세요!!

2020년 6월 10일 (수) 오후 2:46, Kurt Bestor <notifications@github.com>님이 작성:
