### ISSUE TITLE
네이버 블로그 영상은 다운로드가 되지않나요?

### ISSUE THREAD

**Issue by hp784951623** [KurtBestor/Hitomi-Downloader#2032]
한 블로그에 있는 영상 모두를 다운받아 소장하고 싶은데

영상 각각 주소를 넣어도 블로그주소를 넣어도 다운로드가 되질않아요

**Comment by woghkstod** [comment]
저도 기능 추가 건의드리고 싶었던 내용이에요
네이버TV와 달리 블로그나 카페는 네이버 플레이어가 고화질일 경우와 일반화질일 경우 스트리밍하는 방식이 다른 것 같아서, 지금까지는 일반화질은 크롬 개발자도구로, 고화질은 FLV로 받아서 변환하고 있었는데, 다른 동영상 받는것과 원리만 비슷하다면 기능이 추가되면 좋을 것 같네요!

**Comment by mita5549** [comment]
추가로, 파일 또는 폴더명을 게시글 이름으로 저장하고 싶은데... 추가 개발하시기 어려우신가봐요.ㅠㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1838, https://github.com/KurtBestor/Hitomi-Downloader/issues/928

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/1838#issuecomment-665798999
