### ISSUE TITLE
안녕하세요 픽시브 북마크 다운로드 문의드립니다.

### ISSUE THREAD

**Issue by ererar** [KurtBestor/Hitomi-Downloader#2042]
픽시브 북마크 전체를 다운로드하려고 하는데요. 읽는 과정에서 1763번에서 멈춘 채로 무한 로딩만 되더라구요. 오른쪽 클릭하고 나오는 정보 복사해서 왔습니다. 1764번부터 다운로드하려해도 여전히 1763번에서 무한로딩만 걸리네요..

읽는 중... ererar (pixiv_bmk_4519935) (1763)

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: -7
group: False
input: https://www.pixiv.net/bookmark.php?rest=show
dir: 
zip: 
type: pixiv
artist: ererar
url: https://www.pixiv.net/bookmark.php?id=4519935
valid: True
done: False
range: None
range_p: None
single: False
time: 1591369852.77 (Jun 6)
tags: []
goodbyedpi: True
lock: False
color: None
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
PIXIV_TYPE: bookmark
Type: all
info: None
ererar (pixiv_bmk_4519935)
tags: []
tags_ex: []
read ugoira... 81749706
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81749706_p0 拷問・洗脳されるブレマートン.webp
read ugoira... 81740159
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81740159_p0 フォーミフォーミ.webp
read ugoira... 81703188
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81703188_p0 Negev shower.webp
read ugoira... 70572374
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\70572374_p0 その後めっちゃくちゃ....webp
read ugoira... 80941730
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\80941730_p0 えちえち♥トレーニング♪(健全版GIF).webp
read ugoira... 80057057
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\80057057_p0 ドスケベ曙光姫(GIF).webp
read ugoira... 74870193
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\74870193_p0 えっちなカフェ店員さん.webp
read ugoira... 81604358
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81604358_p0 えちえち♥メンテナンス(健全版GIF).webp
read ugoira... 81355462
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81355462_p0 HonKai 3rd Durandal H.webp
read ugoira... 79784924
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\79784924_p0 セントルイス4.webp
read ugoira... 79259532
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...

**Comment by ererar** [comment]
계속 놔둬보니 이런 오류가 뜨면서 중단됐습니다.

PixivError: {'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.pixiv.net/bookmark.php?rest=show
dir: 
zip: 
type: pixiv
artist: ererar
url: https://www.pixiv.net/bookmark.php?id=4519935
valid: False
done: True
range: None
range_p: None
single: False
time: 1591369852.77 (Jun 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: bookmark
Type: all
info: None
ererar (pixiv_bmk_4519935)
tags: []
tags_ex: []
read ugoira... 81749706
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81749706_p0 拷問・洗脳されるブレマートン.webp
read ugoira... 81740159
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81740159_p0 フォーミフォーミ.webp
read ugoira... 81703188
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81703188_p0 Negev shower.webp
read ugoira... 70572374
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\70572374_p0 その後めっちゃくちゃ....webp
read ugoira... 80941730
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\80941730_p0 えちえち♥トレーニング♪(健全版GIF).webp
read ugoira... 80057057
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\80057057_p0 ドスケベ曙光姫(GIF).webp
read ugoira... 74870193
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\74870193_p0 えっちなカフェ店員さん.webp
read ugoira... 81604358
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81604358_p0 えちえち♥メンテナンス(健全版GIF).webp
read ugoira... 81355462
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\81355462_p0 HonKai 3rd Durandal H.webp
read ugoira... 79784924
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_bmk_4519935)\79784924_p0 セントルイス4.webp
read ugoira... 79259532
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/bookmark.php?rest=show

**Comment by jjunleegood** [comment]
마지막에서 오류 난 ID를 픽시브에서 검색해보니 **존재하지 않는 작품**이라고 나오네요.
아마 존재하지 않는 파일을 강제로 불러오기를 하려고 해서 일어난 문제인 것 같습니다.

**Comment by KurtBestor** [comment]
지금도 안 되나요?

**Comment by ererar** [comment]
넵. 방금 다시 해보니까 이번엔 2985번에서 멈추는 오류가 발생합니다. 문제가 되는 파일을 건너뛰는 방법은 없을까요? 페이지 지정 다운로드를 하려고 해도 읽는 과정에서 문제가 발생해서 방법이 없네요.. 이미 삭제된 일러스트라 북마크 해제도 할 수가 없고요..

 일단 정보창에 떠있는 오류메시지 복사해 왔습니다.
PixivError: {'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://www.pixiv.net/users/4519935/bookmarks/artworks
dir: 
zip: 
type: pixiv
artist: ererar
url: https://www.pixiv.net/users/4519935/bookmarks/artworks
valid: False
done: True
range: ~ 5000
range_p: None
single: False
time: 1592238251.9 (Jun 16)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
PIXIV_TYPE: bookmark
Type: all
info: None
ererar (pixiv_4519935)
tags: []
tags_ex: []
read ugoira... 58657447
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_4519935)\58657447_p0 【R-18うごイラ】凛ちゃんに夜這い.gif
read ugoira... 80681708
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_4519935)\80681708_p0 腋コキ.gif
read ugoira... 68146023
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_4519935)\68146023_p0 Wake Up, Anti Rain..gif
read ugoira... 81749706
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_4519935)\81749706_p0 拷問・洗脳されるブレマートン.gif
read ugoira... 81740159
skip ugoira: hitomi_downloaded_pixiv\ererar (pixiv_4519935)\81740159_p0 フォーミフォーミ.gif
read ugoira... 81703188
read ugoira... 70572374
read ugoira... 80941730
read ugoira... 80057057
read ugoira... 74870193
read ugoira... 81604358
read ugoira... 81355462
read ugoira... 79784924
read ugoira... 79259532
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
retry...
read ugoira... 76325083
{'user_message_details': {}, 'reason': u'', 'message': u'', 'user_message': u'\u8a72\u5f53\u4f5c\u54c1\u306e\u516c\u958b\u30ec\u30d9\u30eb\u306b\u3088\u308a\u95b2\u89a7\u3067\u304d\u307e\u305b\u3093\u3002'}
stop
Invalid: fail=False
stop
EOT: https://www.pixiv.net/users/4519935/bookmarks/artworks

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
