### ISSUE TITLE
VPN 키고 다운받으면 이것도 추적하기 힘든가요?

### ISSUE THREAD

**Issue by xlxlzl123** [KurtBestor/Hitomi-Downloader#2043]
보는건 그냥 VPN 키고 보는데 다운로더 돌리는 것도 마찬가지고 잡기 힘들까요?

**Comment by jjunleegood** [comment]
솔직하게 VPN을 써도 추적을 완벽하게 막을 수는 없습니다. 그래도 사용을 하실거면 유료 VPN 쓰시는 걸 추천드립니다.

**Comment by KurtBestor** [comment]
누가 뭘 추적하나요?
