### ISSUE TITLE
Youtube 일부 다운로드 오류

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#2047]
최근 유튜브 영상을 다운로드중 파일에 문제를 발견했습니다.
특정 영상을 다운로드 받을때 파일을 열면 누락된 코덱이라며
이 항목은 지원되지 않는 형식으로 인코딩 되어 있습니다 0xc00d5212
라는 오류문구가뜹니다 (윈도우 기본 플레이어)
오류문구에서 닫기를 누르면 화면은 검은색이고 소리만 나옵니다.
그래서 확장자를 mp3로 바꿔봐도 소리는 잘나오더군요 
Km플레이어로 틀때는 아에 렉이 먹어버리구요

오류 영상중 하나의 정보입니다.
//파일 위치중에서 E:\E\Linux Setting\a2idj20ot33\agg\htm는 제 개인정보를 
위해 폴더를 꼬아놓ㅇ..
고길동 - 종로스타

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 18
group: False
input: https://www.youtube.com/watch?v=20xni0vPXxM
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: 여유만만
url: https://www.youtube.com/watch?v=20xni0vPXxM
valid: True
done: True
range: None
range_p: None
single: True
time: 1591537385.31 (Jun 7)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=20xni0vPXxM) ---> https://r3---sn-ab02a0nfpgxapox-bh2sd.googlevideo.com/videoplayback?expire=1591558989&ei=7e7cXo3eDteZ4AKr2Jm4Dw&ip=116.36.43.142&id=o-AI8yUVUY6hSnTDJD-O37PHryGjtuDMVUre3ei6Bx3Ypy&itag=399&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=4V&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2sd%2Csn-npoe7ne6&ms=au%2Conr&mv=m&mvi=2&pl=19&usequic=no&pcm2=no&initcwndbps=1657500&vprv=1&mime=video%2Fmp4&gir=yes&clen=12012586&dur=60.660&lmt=1589303762264884&mt=1591537359&fvip=3&keepalive=yes&fexp=23882514&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgAewGS1kiLs3563BHWlwplFoOfrT6k9wA1j_h-RBRiy8CIDv_fOJJnNfa5J94M7x3AEPkiafTPkOxEinll9jJ0HJd&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKdhGcWEmebBQ325BvnZNmgztMEoZbeQOGaFL1qd3XChAiEApKgLxdq82cp9hrhqy49RO5y_s0Bj7Z_Ol3cpqmZF3eU%3D&ratebypass=yes

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] mp4 None ─ 395 - 426x240 (240p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] mp4 None ─ 396 - 640x360 (360p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] mp4 None ─ 397 - 854x480 (480p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 398 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[1080p][30fps][None] mp4 None ─ 399 - 1920x1080 (1080p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000002886CBAFB88> 399 - 1920x1080 (1080p) 1080p mp4 None 30fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

Download audio: https://r3---sn-ab02a0nfpgxapox-bh2sd.googlevideo.com/videoplayback?expire=1591556137&ei=yePcXqTBJf-A1d8P5siUiAw&ip=116.36.43.142&id=o-ABGmzBmI4vBmtpDVzRE1EJHF0Uecgoraim5YChZanr85&itag=140&source=youtube&requiressl=yes&mh=4V&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2sd%2Csn-npoeene6&ms=au%2Conr&mv=m&mvi=2&pcm2cms=yes&pl=19&usequic=no&initcwndbps=1723750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=983458&dur=60.720&lmt=1586042660108873&mt=1591534415&fvip=3&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIzHVO5jc1Wngi2IQKw9XQ35lAiW5eC4Lh7lhCsfu8j4AiAU0b_a1UGVtZRgod0zrfuuOkRuo3cRsx26cLnM_MlB0A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cusequic%2Cinitcwndbps&lsig=AG3C_xAwRQIhANxKpUGBOAs80e_i3it7m8MI1_HuKcXzwnuCUtWc6UEaAiBWABKKTejKgzR1hU9vEirRokPiJHLHYz7b26mHZQbzkQ%3D%3D&ratebypass=yes
use just download
Convert: E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
rename (1): hitomi_downloaded_youtube\57B6FFA4_a.tmp -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp9FE2E75C_a.weba
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp9FE2E75C_v.mp4
-i tmp9FE2E75C_v.mp4 -i tmp9FE2E75C_a.weba -c copy -strict experimental -preset ultrafast tmp9FE2E75C_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[libaom-av1 @ 03fc5580] 1.0.0-900-g7715ae1c7
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp9FE2E75C_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
creation_time : 2020-05-12T16:25:49.000000Z
Duration: 00:01:00.66, start: 0.000000, bitrate: 1584 kb/s
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmp9FE2E75C_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-04-04T23:24:15.000000Z
Duration: 00:01:00.72, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmp9FE2E75C_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
encoder : Lavf58.20.100
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, q=2-31, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1818 fps=0.0 q=-1.0 Lsize= 12712kB time=00:01:00.69 bitrate=1715.6kbits/s speed= 815x 
video:11715kB audio:949kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.380035%

Convert success: True
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmp9FE2E75C_o.mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
stop
EOT: https://www.youtube.com/watch?v=20xni0vPXxM

[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] mp4 None ─ 395 - 426x240 (240p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] mp4 None ─ 396 - 640x360 (360p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] mp4 None ─ 397 - 854x480 (480p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 398 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[1080p][30fps][None] mp4 None ─ 399 - 1920x1080 (1080p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000002886B870E08> 399 - 1920x1080 (1080p) 1080p mp4 None 30fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

Download audio: https://r3---sn-ab02a0nfpgxapox-bh2sd.googlevideo.com/videoplayback?expire=1591558906&ei=mu7cXuCHN-mFs8IPyNOW2AQ&ip=116.36.43.142&id=o-AFzNwhxXmyXDRWH9FH8277bXL-Spdqkj9wvmy-sVmHcL&itag=140&source=youtube&requiressl=yes&mh=4V&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2sd%2Csn-npoeene6&ms=au%2Conr&mv=m&mvi=2&pl=19&usequic=no&pcm2=no&initcwndbps=1663750&vprv=1&mime=audio%2Fmp4&gir=yes&clen=983458&dur=60.720&lmt=1586042660108873&mt=1591537176&fvip=3&keepalive=yes&fexp=23882514&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNoo9BakQfHAot-6Ng8jzqKeenrrwgv5z68e4XxQibt8CIQC3g-uzHlBWJmcMyT2mr6-qGrYOfl1hN2-phCyZA7LcOw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2Cinitcwndbps&lsig=AG3C_xAwRQIhAP0sU38nMxMc7UqEjk6XLa_2S3Cd_4k7d_keOVW9UJ9bAiAqVLyvp8oxmiDYGd9A8gqcBohPHHdZqRnTNd_wksSrPw%3D%3D&ratebypass=yes
use just download
Convert: E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
rename (1): hitomi_downloaded_youtube\1735D557_a.tmp -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpE4FE1223_a.weba
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpE4FE1223_v.mp4
-i tmpE4FE1223_v.mp4 -i tmpE4FE1223_a.weba -c copy -strict experimental -preset ultrafast tmpE4FE1223_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[libaom-av1 @ 064f5580] 1.0.0-900-g7715ae1c7
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpE4FE1223_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
creation_time : 2020-05-12T16:25:49.000000Z
Duration: 00:01:00.66, start: 0.000000, bitrate: 1584 kb/s
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpE4FE1223_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-04-04T23:24:15.000000Z
Duration: 00:01:00.72, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmpE4FE1223_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
encoder : Lavf58.20.100
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, q=2-31, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1818 fps=0.0 q=-1.0 Lsize= 12712kB time=00:01:00.69 bitrate=1715.6kbits/s speed= 529x 
video:11715kB audio:949kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.380035%

Convert success: True
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpE4FE1223_o.mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
stop
EOT: https://www.youtube.com/watch?v=20xni0vPXxM

[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[144p][30fps][None] mp4 None ─ 394 - 256x144 (144p)
[144p][30fps][None] webm None ─ 278 - 256x144 (144p)
[144p][30fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][30fps][None] mp4 None ─ 395 - 426x240 (240p)
[240p][30fps][None] webm None ─ 242 - 426x240 (240p)
[240p][30fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][30fps][None] mp4 None ─ 396 - 640x360 (360p)
[360p][30fps][None] webm None ─ 243 - 640x360 (360p)
[360p][30fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][30fps][None] mp4 None ─ 397 - 854x480 (480p)
[480p][30fps][None] webm None ─ 244 - 854x480 (480p)
[480p][30fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][30fps][None] mp4 None ─ 398 - 1280x720 (720p)
[720p][30fps][None] mp4 None ─ 136 - 1280x720 (720p)
[720p][30fps][None] webm None ─ 247 - 1280x720 (720p)
[1080p][30fps][None] mp4 None ─ 399 - 1920x1080 (1080p)
[1080p][30fps][None] webm None ─ 248 - 1920x1080 (1080p)
[1080p][30fps][None] mp4 None ─ 137 - 1920x1080 (1080p)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

# stream_final <youtube_dl_test.Video object at 0x000002886D725B88> 399 - 1920x1080 (1080p) 1080p mp4 None 30fps
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[360p][30fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)
[720p][30fps][192kbps] mp4 mp4a.40.2 ─ 22 - 1280x720 (720p)

[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)

Resolution: None
Codec: None / mp4a.40.2
Abr: 128kbps
Subtype: m4a
FPS: 0

Download audio: https://r3---sn-ab02a0nfpgxapox-bh2sd.googlevideo.com/videoplayback?expire=1591558989&ei=7e7cXo3eDteZ4AKr2Jm4Dw&ip=116.36.43.142&id=o-AI8yUVUY6hSnTDJD-O37PHryGjtuDMVUre3ei6Bx3Ypy&itag=140&source=youtube&requiressl=yes&mh=4V&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2sd%2Csn-npoe7ne6&ms=au%2Conr&mv=m&mvi=2&pl=19&usequic=no&pcm2=no&initcwndbps=1657500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=983458&dur=60.720&lmt=1586042660108873&mt=1591537359&fvip=3&keepalive=yes&fexp=23882514&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgU0VjryFypJs_h__nJkWKEXFCQ-8KC2Ndu_rnctwzSgcCIAtJ0hMV8OgHz5TuRu7k0udGEzYGKZIUp5XOPYWU6TrW&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cusequic%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKdhGcWEmebBQ325BvnZNmgztMEoZbeQOGaFL1qd3XChAiEApKgLxdq82cp9hrhqy49RO5y_s0Bj7Z_Ol3cpqmZF3eU%3D&ratebypass=yes
use just download
Convert: E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
rename (1): hitomi_downloaded_youtube\8E72F43E_a.tmp -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpBE49CAE2_a.weba
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpBE49CAE2_v.mp4
-i tmpBE49CAE2_v.mp4 -i tmpBE49CAE2_a.weba -c copy -strict experimental -preset ultrafast tmpBE49CAE2_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
libavutil 56. 22.100 / 56. 22.100
libavcodec 58. 35.100 / 58. 35.100
libavformat 58. 20.100 / 58. 20.100
libavdevice 58. 5.100 / 58. 5.100
libavfilter 7. 40.101 / 7. 40.101
libswscale 5. 3.100 / 5. 3.100
libswresample 3. 3.100 / 3. 3.100
libpostproc 55. 3.100 / 55. 3.100
[libaom-av1 @ 06725580] 1.0.0-900-g7715ae1c7
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpBE49CAE2_v.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
creation_time : 2020-05-12T16:25:49.000000Z
Duration: 00:01:00.66, start: 0.000000, bitrate: 1584 kb/s
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'tmpBE49CAE2_a.weba':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6mp41
creation_time : 2020-04-04T23:24:15.000000Z
Duration: 00:01:00.72, start: 0.000000, bitrate: 129 kb/s
Stream #1:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Output #0, mp4, to 'tmpBE49CAE2_o.mp4':
Metadata:
major_brand : dash
minor_version : 0
compatible_brands: iso6av01mp41
encoder : Lavf58.20.100
Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 1920x1080, q=2-31, 148 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
Metadata:
creation_time : 2020-05-12T16:25:49.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 21 kb/s (default)
Metadata:
creation_time : 2020-04-04T23:24:15.000000Z
handler_name : ISO Media file produced by Google Inc.
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame= 1818 fps=0.0 q=-1.0 Lsize= 12712kB time=00:01:00.69 bitrate=1715.6kbits/s speed= 822x 
video:11715kB audio:949kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.380035%

Convert success: True
rename (1): E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\tmpBE49CAE2_o.mp4 -> E:\E\Linux Setting\a2idj20ot33\agg\htm\hitomi_downloader_GUI\hitomi_downloaded_youtube\고길동 - 종로스타 (20xni0vPXxM).mp4
stop
EOT: https://www.youtube.com/watch?v=20xni0vPXxM

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/1701#issuecomment-590234822
