### ISSUE TITLE
사이트 추가 요청드려요

### ISSUE THREAD

**Issue by mmel-q** [KurtBestor/Hitomi-Downloader#2048]
https://www.creativeuncut.com/

여기 사이트 추가가능할까요?항상 감사합니다

**Comment by tdi2020** [comment]
https://www.creativeuncut.com/

아직 업데이트가 계류중인 것 같아서 혹시나하고 한번 요청드려봅니다!

감사합니다.

(중복글은 자삭하였습니다!)
