### ISSUE TITLE
토렌트 파일 대기열에 있으면 자동으로 다운로드 안넘어가는 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2049]
존경하는 선생님께.

컴퓨터가 별로 안좋아서 최대 동시작업을 1로 놓고 쓰는 중인데 토렌트 파일을 1개이상 대기열에 추가해두면 한개를 다운로드 완료해도 다음 것을 자동으로 다운받지 않는 상태 같습니다. (대기중 상태로 그냥 가만히? 있음)
그리고 이럴땐 우클릭 메뉴에서 [다시시작]을 눌러도 다운받아지지 않는것을 확인하였습니다.
버전은 2.8a 최신 버전입니다.

최대 동시작업 2개일땐 되는지 확인하고 올리고 싶었는데 시간이 안돼서 아직 테스트 못해봤습니다ㅠ 만약 2개일때 다음 다운로드로 넘어간다면 저녁에 테스트 후 댓 달아놓도록 하겠습니다.

**Comment by tdi2020** [comment]
동시작업 갯수와 관계없이 안되는 것으로 확인하였습니다.
(동시작업을 1로 해도 그 다음것 안받아짐+동시작업이 2일때도 마찬가지)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
