### ISSUE TITLE
v2.8a 버전으로 올라오고나서 인스타 다운이 제대로 되지않는듯합니다

### ISSUE THREAD

**Issue by qpcnddl1** [KurtBestor/Hitomi-Downloader#2051]
v2.8a 버전으로 올라오고나서 인스타 다운이 제대로 되지않는듯합니다

바로 이전버전까진 제대로된 완료가 되었는데 2.8a 버전에선 뭔가 인스타 스토리까지 새로 추가되면서 충돌이 일어나는건가 동영상 같은게 빠진채로 다운이 되는듯합니다 

긁어오는 목록에 스토리가 이제 막 추가되면서 정말 제대로된 다운로더같은데 다음 업뎃에서 오류 한번 이상있나 확인 부탁드려도될까요~?

증상은
동영상이 많이 올라가있는 인스타는 다운이 완료가 되긴하나 불러읽은 갯수에 비해서 다운 갯수가 적고 노란색으로 미완 처리가 됩니다~ 주로 누락은 동영상인걸로 확인했습니다.

ps. 아 그리고 중복 주소 잡아서 등록되지않게 업데이트된것도 정말 만족합니다 ㅋㅋㅋ 트위터 중복 주소 모르고 등록했더니 이미 목록에 있는걸로 넘어가서 재다운이 시작되네요 ㅎㅎ

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
