### ISSUE TITLE
익헨/이헨 다운로드 오류

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#2055]
안녕하세요, 오랜만에 뵙습니다.
이헨 다운로드를 진행하는데 왠 히토미로 다운로드되는 현상이 있어 제보차 문의드리게 됐습니다.

이해가 안되는게 이헨의 이미지 크기와 히토미의 이미지 크기가 달라서 완전히 별개의 갤러리인데도
이헨 갤러리를 히토미로 인식하는게 있나봅니다.

![주석 2020-06-10 094410](https://user-images.githubusercontent.com/47098778/84214731-36bd9d00-aaff-11ea-9219-fc0400c2f9d0.png)
이게 해당 사진입니다. 링크는 분명 이헨으로 인식하는데 정작 다운로드는 히토미인..

만약에 이게 이헨 설정 때문에 히토미 파일이랑 크기가 같아서 그냥 히토미를 다운로드하는 것이면 모르겠는데 그건 또 아닌 상황이거든요.
이헨은 원본으로 나오게끔 설정해놨고 다운로더에 있는 쿠키 또한

【.e-hentai.org】
  star = 
  event = 
  sk =
  ipb_pass_hash = 
  ipb_member_id = 
  hath_perks =
  __cfduid = 

항목값은 개인정보라서 지웁니다만 이헨 Id와 Pass hash 모두 맞습니다.
익헨도 확인해보니 같은 증상이군요.

다음은 해당하는 갤러리입니다.
e-hentai.org/g/814861/ad48f1b568/
exhentai.org/g/810185/6b0ed51e1c/

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `히토미 / E(x)Hentai / 히요비 설정` - `서버` 를 바꾸세요.
