### ISSUE TITLE
쏘걸 싸이트도 추가해주시면안될까요..?

### ISSUE THREAD

**Issue by google4999** [KurtBestor/Hitomi-Downloader#2058]
https://kr16.sogirl.co/ 주소입니다..
 제가직접 하고있엇으나.. 프로그래밍을 할줄을몰라 아쉽네요,,, 영잘못이라 수식어도 어렵네요

부탁드리겠습니다..

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2034

**Comment by google499** [comment]
..

**Comment by google499** [comment]
게시글 삭제해주세요.
