### ISSUE TITLE
rule34.xxx 스크립트 추가, rule34.paheal.net 요청

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader#2060]
깃허브사이트자체를 안써봐서 어따 올려야 할지를 몰라서 여따가 스크립트 내용 씁니다.
https://rule34.xxx/ 사이트 자체가 gelbooru랑 똑같길래, 올려두신 gelbooru_downloader.py를 살짝만 바꿔서 hds확장자로 저장해서 썼는데 잘 동작했습니다.

근데
https://rule34.paheal.net/
이 사이트는 rule34.xxx랑 이름은 비슷한데 업로드 된 자료의 수가 완전히 다르더라구요.
하지만 제가 코딩은 젬병이라 별짓을 다해봐도 저 사이트 스크립트는 못만들겠습니다ㅠㅠ
"위대하신" Kurt Bestor님, 제발 저 사이트 스크립트를 추가해주실 수 있나요ㅠㅠ

#coding: utf-8
import downloader
import re
import os
from utils import Downloader, urljoin, query_url, Soup, get_max_range
from fucking_encoding import clean_title
from translator import tr_
import urllib
import sys
from time import sleep
from constants import clean_url
LIMIT = 100

def get_tags(url):
    url = clean_url(url)
    qs = query_url(url)
    if 'page=favorites' in url:
        id = qs.get('id', ['N/A'])[0]
        id = u'fav_{}'.format(id)
    else:
        tags = qs.get('tags', [])
        tags.sort()
        id = u' '.join(tags)
    if not id:
        id = u'N/A'
    return id

@Downloader.register
class Downloader_rule34(Downloader):
    type = 'rule34'
    URLS = ['rule34.xxx']
    _id = None
    
    def init(self):
        self.url = self.url.replace('rule34_', '')
        if 'rule34.xxx' in self.url.lower():
            self.url = self.url.replace('http://', 'https://')
        else:
            url = self.url
            url = url.replace(' ', '+')
            while '++' in url:
                url = url.replace('++', '+')
            url = urllib.quote(url)
            url = url.replace('%2B', '+')
            self.url = u'https://rule34.xxx/index.php?page=post&s=list&tags={}'.format(url)

    @property
    def id(self):
        if self._id is None:
            tags = get_tags(self.url)
            self._id = tags
        return self._id

    @property
    def name(self):
        return clean_title(self.id)

    def read(self):
        self.title = self.name

        imgs = get_imgs(self.url, self.name, customWidget=self.customWidget)

        for img in imgs:
            self.urls.append(img.url)
            self.filenames[img.url] = img.filename

        sleep(.5)
        self.title = self.name

class Image(object):
    def __init__(self, id, url):
        self.id = id
        self.url = url
        ext = os.path.splitext(url)[1]
        self.filename = u'{}{}'.format(id, ext)

def setPage(url, page):
    # Always use HTTPS
    url = url.replace('http://', 'https://')

    # Change the page
    if 'pid=' in url:
        url = re.sub('pid=[0-9]*', 'pid={}'.format(page), url)
    else:
        url += '&pid={}'.format(page)

    return url

def get_imgs(url, title=None, customWidget=None):
    url = clean_url(url)
    if 's=view' in url and 'page=favorites' not in url:
        raise NotImplementedError('Not Implemented')

    if 'page=dapi' not in url.lower():
        tags = get_tags(url)
        tags = urllib.quote(tags, safe='/')
        tags = tags.replace('%20', '+')
        url = "https://rule34.xxx/index.php?page=dapi&s=post&q=index&tags={}&pid={}&limit={}".format(tags, 0, LIMIT)

    if customWidget is not None:
        print_ = customWidget.print_
    else:
        def print_(*values):
            sys.stdout.writelines(values + ('\n',))

    # Range
    max_pid = get_max_range(customWidget, 2000)

    imgs = []
    url_imgs = set()
    for p in range(500): #1017
        url = setPage(url, p)
        print_(url)
        html = downloader.read_html(url)

        soup = Soup(html)
        posts = soup.findAll('post')
        if not posts:
            break
        for post in posts:
            url_img = post.attrs['file_url']
            if url_img in url_imgs:
                print 'already exists', url_img
            else:
                url_imgs.add(url_img)
                id = post.attrs['id']
                img = Image(id, url_img)
                imgs.append(img)
        if len(imgs) >= max_pid:
            break

        if customWidget is not None:
            if not customWidget.alive:
                break
            customWidget.setTitle(u'{}  {} - {}'.format(tr_(u'읽는 중...'), title, len(imgs)))
    return imgs

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/868, https://github.com/KurtBestor/Hitomi-Downloader/issues/1120

**Comment by KurtBestor** [comment]
투표 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/issues/868#issuecomment-723650147
