### ISSUE TITLE
수고하십니다 porn hub paid video다운로드 문의좀 드릴려고합니다..

### ISSUE THREAD

**Issue by sksdhtjdals** [KurtBestor/Hitomi-Downloader#2062]
Invalid: [pornhub] https://www.pornhub.com / view_video.php?viewkey=ph5ec9c5ccaafd8

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
input: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
dir: 
zip: 
type: pornhub
artist: None
url: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
valid: False
done: True
range: None
range_p: None
single: True
time: 1591956687.16 (Jun 12)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
no html
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
invalid soup: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 210, in get_video
File "pornhub_downloader", line 194, in fix_soup
File "clf2", line 58, in solve
Exception: clf Timeout

stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "pornhub_downloader", line 159, in read
File "<decorator-gen-25>", line 2, in get_video
File "constants", line 781, in wrapper
Exception: fuckkk...
Traceback (most recent call last):
File "constants", line 754, in wrapper
File "pornhub_downloader", line 210, in get_video
File "pornhub_downloader", line 194, in fix_soup
File "clf2", line 58, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph5ec9c5ccaafd8

전에 말씀하신대로 따라하니까 프리미엄 유료영상전부 다운이 다 받아졌습니다
정말 감사합니다.
궁금한건 사이트에서 재생을 막은 동영상은 다운이 가능할지... 궁금해서 문의드립니다

**Comment by KurtBestor** [comment]
구매해야 볼 수 있는 컨텐츠는 구매하지 않으면 다운로드 할 수 없어요.
