### ISSUE TITLE
lhscan에서 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by wlskekrk** [KurtBestor/Hitomi-Downloader#2064]
Invalid: [lhscan] https://loveheaven.net / manga-the-rise-of-the-unemployed-wise-man-manga-raw.html

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://loveheaven.net/manga-the-rise-of-the-unemployed-wise-man-manga-raw.html
dir: 
zip: 
type: lhscan
artist: None
url: https://loveheaven.net/manga-the-rise-of-the-unemployed-wise-man-manga-raw.html
valid: False
done: True
range: None
range_p: None
single: False
time: 1592118053.55 (Jun 14)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'h1'
stop
Traceback (most recent call last):
File "utils", line 900, in start
File "utils", line 960, in start_
File "lhscan_downloader", line 66, in read
File "lhscan_downloader", line 62, in name
AttributeError: 'NoneType' object has no attribute 'h1'

Invalid: fail=True
EOT: https://loveheaven.net/manga-the-rise-of-the-unemployed-wise-man-manga-raw.html

정보는 이렇게 뜨구요
로그인하고 쿠키불러오기까지 했습니다
그런데 갑자기 되질않네요
잘부탁드립니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
테스트로 해보니 전체 다운로드는 잘되네요 그런데 선택 화 다운로드는 되질않습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by wlskekrk** [comment]
다 잘되네요 빠른 피드백 정말 감사드립니다
언제나 감사히 잘 이용하고 있습니다
