### ISSUE TITLE
afreecaTV 다시보기 다운로드 오류건입니다.

### ISSUE THREAD

**Issue by playground-SCC-kms** [KurtBestor/Hitomi-Downloader#2065]
afreecaTV 다시보기 다운로드 오류건입니다.
다시보기 다운 받을때 5시간이 넘는 영상은 정상적으로 받아지지 않는 건이 있습니다.
보니까 다시보기 영상이 5시간 이상이 되면 영상 파일이 2개로 나눠지는 것으로 추측(보니까 5시간마다 영상이 분할되는 것 같습니다.)되는데 1개만 받아지고 나머지 한개는 다운이 안되는 것 같습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by playground-SCC-kms** [comment]
[생]자리비움]애니음악노래.JPOP

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/54200887
dir: hitomi_downloaded_afreeca
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/54200887
valid: True
done: True
range: None
range_p: None
single: True
time: 1592219010.28 (Jun 15)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_afreeca\[생]자리비움]애니음악노래.JPOP.mp4


[URLs]




----------------------------
이렇게 나옵니다.

**Comment by playground-SCC-kms** [comment]
작업도중을 확인해보니

[생]자리비움]애니음악노래.JPOP

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/54433492
dir: hitomi_downloaded_afreeca
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/54433492
valid: True
done: False
range: None
range_p: None
single: True
time: 1592613784.17 (Jun 20)
tags: []
goodbyedpi: True
lock: False
color: downloading
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_afreeca\[생]자리비움]애니음악노래.JPOP.mp4


[URLs]
[0001] LazyUrl(http://vod.afreecatv.com/PLAYER/STATION/54433492) ---> M3u8_stream(http://vod-archive-kr-cdn-z01.afreecatv.com/v1/mapped-vod/20200321/277/222085277/REGL_DBA4FC80_222085277_3.php/live/0/index-f1-v1-a1.m3u8)

좀 다르게 나오네요 죄송합니다.
URLs 보니 저게 하나뿐인것으로 확인이 되네요.
