### ISSUE TITLE
이 프로그램을 이용하여 다운로드 시

### ISSUE THREAD

**Issue by massiveguy** [KurtBestor/Hitomi-Downloader#2066]
폰헙이든, 히토미에서 다운로드 시 외부에서 다운로드 기록을 추적 할 수 있나요?

**Comment by KurtBestor** [comment]
ISP 같은 곳에서 추적할 순 있는데, 다운로드인지 그냥 웹브라우저에서 접속하는 건지 구분은 할 수 없어요.
