### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by hunsuk1546** [KurtBestor/Hitomi-Downloader#2067]
javmec.com
추가 가능하실까요

**Comment by KurtBestor** [comment]
다음 링크에서 `JAVmec.hds` 다운로드해서 스크립트 적용해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by hunsuk1546** [comment]
잘 됩니다. 감사합니다.
