### ISSUE TITLE
히토미 작가 차단이 있었으면 합니다

### ISSUE THREAD

**Issue by spiral1315** [KurtBestor/Hitomi-Downloader#2070]
현재 태그차단만 가능한걸로 알고있는데 작가 차단도 생겼으면 합니다

**Comment by KurtBestor** [comment]
도움말 - 사용법 (F1) 에 나와있어요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1242#issuecomment-536936027
