### ISSUE TITLE
뉴토끼 웹툰 다운로드가 안되네요.

### ISSUE THREAD

**Issue by kamogun** [KurtBestor/Hitomi-Downloader#2071]
[N／A] 옥탑방 소드마스터

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://newtoki65.com/webtoon/2221543/%EC%98%A5%ED%83%91%EB%B0%A9-%EC%86%8C%EB%93%9C%EB%A7%88%EC%8A%A4%ED%84%B0?page=2&toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
dir: hitomi_downloaded_newtoki\[N／A] 옥탑방 소드마스터
zip: 
type: newtoki
artist: None
url: https://newtoki65.com/webtoon/2221543/%EC%98%A5%ED%83%91%EB%B0%A9-%EC%86%8C%EB%93%9C%EB%A7%88%EC%8A%A4%ED%84%B0?page=2&toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0
valid: True
done: True
range: None
range_p: None
single: False
time: 1592362805.45 (Jun 17)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 1화 (1 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 2화 (2 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 3화 (3 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 4화 (4 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 5화 (5 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 6화 (6 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 7화 (7 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 8화 (8 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 9화 (9 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 10화 (10 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 11화 (11 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 12화 (12 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 13화 (13 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 14화 (14 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 15화 (15 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 16화 (16 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 17화 (17 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 18화 (18 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 19화 (19 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 20화 (20 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 21화 (21 / 22)
읽는 중... [N／A] 옥탑방 소드마스터 / 옥탑방 소드마스터 22화 (22 / 22)
stop
EOT: https://newtoki65.com/webtoon/2221543/%EC%98%A5%ED%83%91%EB%B0%A9-%EC%86%8C%EB%93%9C%EB%A7%88%EC%8A%A4%ED%84%B0?page=2&toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0

**Comment by KurtBestor** [comment]
고쳤어요. 스크립트 다시 다운로드해 주세요 : https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
