### ISSUE TITLE
프로그램을 쓰면서 건의사항 몇가지..

### ISSUE THREAD

**Issue by Chiyac** [KurtBestor/Hitomi-Downloader#2073]
이런 혼란한 시국에 한 줄기 빛같은 프로그램 굉장히 감사합니다.

다만, 쓰면서 불편한점이 몇가지 있어 건의드립니다.

로컬 파일에도 TAG기능을 추가해주셨으면 합니다. INFO파일을 활용하면 될 것 같습니다만, 혹시 구현이 되어있다면 관련 주소를 부탁드립니다.
덧붙여서, 로컬 파일들도 리스트형, 타일형으로 보기를 전환해주는 옵션이 있을까요? 리스트형은 썸네일 보기가 약간 번거롭네요.

한번씩 노트북이 블스가 뜨는데 포맷하는 관계로,  (다른 드라이브에)저장된 자료를 다시 읽어와야 합니다.
이때, 읽은 날짜가 찍혀 나오는데, 추가한 날짜가 아닌 저장한 날짜가 나왔으면 합니다.
ex)  1월 1일에 다운받아도 6월 18일에 읽어들이면 6월 18일날짜로 나오게 됩니다.

개발자 사이트에 이런 건의사항을 쓰려고 가입했나 자괴감 들고 괴로워..
앞으로도 많은 발전 부탁드립니다.

**Comment by KurtBestor** [comment]
`도움말` - `사용법` - `다운로더 작업 목록 필터링` 참고해주세요.
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1413#issuecomment-556035818
HDS 파일로 저장하고 다시 불러들이거나 설정파일 (*.INI) 을 옮기면 저장한 날짜가 바뀌지 않아요.
