### ISSUE TITLE
사이트 추가 건의!!

### ISSUE THREAD

**Issue by qjqjqj123** [KurtBestor/Hitomi-Downloader#2074]
안녕하세요, 좋은 프로그램 감사합니다.

사이트 추가 건의를 하고 싶어여...

겔부루를 다운로드하다가 보니까,
미러링이 이상해서요..

이미지들이 몇 개 누락되구 있어요 ㅠㅜ

겔부루
https://gelbooru.com/index.php?page=post&s=list&tags=nudtawut_thongmai

단부루
https://danbooru.donmai.us/posts?tags=nudtawut_thongmai

최근 이미지 중에 라푼젤(보라색 옷) 보면
단부루는 3장, 겔부루는 2장...

이 일러스트레이터 뿐만 아니라 다른 것도 그렇더라구요.

단부루랑 겔부루 둘 다 다운로드해서
서로 모자란 거 보충하고 싶은데 혹시..

단부루도 추가 가능할까요..? ㅠㅠ

**Comment by KurtBestor** [comment]
모두 두 장 씩으로 보이는데 누락된 이미지 주소 주실 수 있나요?

**Comment by qjqjqj123** [comment]
> 주실 수 있나요?
https://danbooru.donmai.us/posts/3945813
겔부루에 없는 라푼젤 누드 이미지 링크입니다.



다른 예시
https://danbooru.donmai.us/posts/3945815
엔젤우몬 누드 이미지입니다.
단부루에는 옷 이미지만 올라와 있어요.



겔부루가 그...
최신 이미지나, 누드 이미지 등이 종종 누락되는 경향이 좀 있더라구요..

이미지 검색 사이트  https://saucenao.com/
로 누락 확인했습니다. 진짜루 누락되구 있어욧..!!

**Comment by yuchan39** [comment]
검색 태그를 another_kung_fu_girl 로 했을 때도

https://gelbooru.com/index.php?page=post&s=list&tags=another_kung_fu_girl

https://danbooru.donmai.us/posts?page=1&tags=another_kung_fu_girl

gelbooru와 danbooru의 검색되는 이미지의 갯수가 다릅니다.

danbooru쪽이 gelbooru보다 이미지 수가 조금 더 많이 검색됩니다.

다운로더 잘 쓰고 있습니다. 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by yuchan39** [comment]
정상적으로 작동됩니다. 감사합니다.

**Comment by qjqjqj123** [comment]
오 아주 잘 댐다 감사합니다 정말 ㅠㅠㅠ
