### ISSUE TITLE
실행시 dpi가 꺼져있다는데 이게 뭔가요?

### ISSUE THREAD

**Issue by gitHbpd** [KurtBestor/Hitomi-Downloader#2075]
vpn 켜서 다운로드받고있는데 실행시 dpi 우회가 꺼져있다고 나와요
이렇게 나오면 vpn 우회가 안되는건가요?

**Comment by KurtBestor** [comment]
DPI 우회는 프로그램 기능이고, VPN 과는 관련 없어요.
