### ISSUE TITLE
기본 데이터, 삭제된 데이터에도 없는 번호 (hitomi redirection으로 인한 문제?)

### ISSUE THREAD

**Issue by hongged001** [KurtBestor/Hitomi-Downloader#2077]
앞에 있던 이슈는 확인했습니다.
"4월이후 히토미 갤러리중 일부 검색이 안되는 갤러리가 있습니다. #752"

그런데 이 이슈에 적혀있는 1377997이 아직도 삭제된 데이터에도 나오지 않더라고요..
히토미 직접 들어가서 확인해보니까 내용물이 살아있지만 1381776으로 자동 redirect 되더군요.

그래서인지 주소를 직접 입력해서 받으면 제대로 1377997(39p 짜리)의 내용물이 받아지는데
표기는 1381776(원본 111p짜리, 표기는 39p)으로 나옵니다. 내용물이 다른데도요..
이 경우는 그나마 상위호환(?)인 1381776이 살아있어서 검색이 되니 다행인 경우입니다.

히토미에서 1330663도 1418497로 redirect되고 있습니다.
1330663의 내용물은 살아있지만 1418497의 내용물은 삭제됐습니다.
내용물이 없는 게시물은 검색이 안되기에 1418497의 검색은 불가능합니다.
(내용물이 없기에 검색이 될 필요가 없습니다. 이 부분은 문제 없음)
그런데 위의 경우와 마찬가지로 redirect 전 게시물은 어디에서도 검색이 되지 않기에,
내용물이 살아있는 1330663조차 검색이 불가능하게 되어버렸습니다..
(내용물이 있는데 검색이 되지 않습니다. 이 부분이 문제)
그리고 이 작품은 redirect 후 게시물이 죽어버려서 그런지 주소를 직접 입력하면,
로딩을 한참 한 뒤에 1330663 표기로 게시물이 다운로드됩니다.

혹시 이런 문제를 해결해 주실 수 있을까요?

요약
1. 히토미에는 **A -> B로 redirect**되는 게시물이 있다.
2. 이 경우, **A는 내용물이 살아있더라도 기본 데이터와 삭제된 데이터 어느 쪽에서도 검색하지 못한다.**
3. 주소 입력시 A가 내용물만 살아있고, B가 살아있을 경우, 이름은 B이지만 내용물은 A로 받아진다.
4. 주소 입력시 A가 내용물만 살아있고, B가 완전히 죽었을 경우, 로딩을 한참 하다가 A가 받아진다.

추가확인이 필요한 상황: A가 내용물만 살아있으면서 B도 내용물만 살아있을 때
(A가 완전히 죽은 경우는 의미가 없음. 검색되지 않는 것이 맞기 때문)
(A가 살아있을 순 없음, A->B로 redirect되는 것이 전제이기 때문)

**Comment by KurtBestor** [comment]
다음과 같이 수정했어요:


- [x] 리다이렉트된 내용물 (111장) 과 원본 내용물 (39장) 이 모두 살아있는 경우:
  1377997 -> 1381776 로 리다이렉트, 111장

- [x] 리다이렉트된 내용물이 죽어있지만 원본 내용물이 살아있는 경우:
  1330663 -> 60 장

- [x] 내용물이 죽어있는 경우:
  1418497 -> ExHentai 로 다운로드

- [x] 내용물만 살아있는 경우:
  1567653 -> 39장

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

삭제된 데이터는 요새 업데이트를 못 하고 있는데 나중에 손볼게요.

**Comment by hongged001** [comment]
네 1~4번 동작 확인했습니다!
그런데 2~4번은 뭔가 "읽는 중..." 표시가 오래 돌긴 하네요

그리고 혹시 삭제된 데이터에 2번 경우의 원본 내용물도 포함되는건가요?

언제나 감사합니다

**Comment by KurtBestor** [comment]
2 ~ 4 번은 오래 걸리는 게 맞아요.

나중에 삭제된 데이터 업데이트 하면서 포함할지 여부 결정할게요.
