### ISSUE TITLE
저장폴더 네트워크 위치 지원

### ISSUE THREAD

**Issue by hentai-redcat** [KurtBestor/Hitomi-Downloader#2078]
안녕하세요, 만들어주신 프로그램 정말 유용하게 잘 사용하고 있습니다.
다만 저장시에 용량의 문제로 PC가 아닌 NAS 저장을 원하는데

'네트워크 드라이브 연결' 로 드라이브 문자를 부여해줘도 설정에서 인식이 되지 않는 것으로 보입니다.

SMB) Y => \\192.168.0.10\hitomi
Downloader config)  => Y:\hitomi_downloaded

위와 같이 사용을 하더라도 기본경로에 자료가 저장되더군요.

가능하다면 SMB, SFTP, FTP와 같은 프로토콜이 지원되면 좋을 것 같습니다.

감사합니다.

**Comment by KurtBestor** [comment]
기본경로가 뭔가요?

**Comment by hentai-redcat** [comment]
> 기본경로가 뭔가요?

저장되는 기본경로는 hitomi_downloaded 입니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by hentai-redcat** [comment]
> 해당 작업 마우스 우 클릭 - 정보... (I) 눌러서 나온 내용 보여주세요.

아 죄송합니다. 저장폴더가 사이트별로 각각 동작하는거였군요. 이슈 재현을 시도하다보니 알게되었습니다. 감사합니다.
