### ISSUE TITLE
안녕하세요 질문이 있습니다

### ISSUE THREAD

**Issue by goodbyekorea** [KurtBestor/Hitomi-Downloader#2080]
이 프로그램써서 다운받아도 별 문제없을까요?? 유로vpn 쓴다는 가정하에요

시국이 시국인지라 ㅜㅜ 너무 무섭네요

**Comment by KurtBestor** [comment]
VPN 을 굳이 쓰는 이유는 모르겠지만 딱히 없을 것 같네요.
