### ISSUE TITLE
nozomi.la 사이트 추가 안될까요?

### ISSUE THREAD

**Issue by wooeorbs** [KurtBestor/Hitomi-Downloader#2083]
검색해봤더니 개발자님이 추가할 마음이 있어야 한다고 그러던데
안되면 스크립트 제작 해봐야하는데
봐도 봐도 어떻게 코드를 써야할 지 감이 안잡혀요...
파이썬은 문외한이고 어떻게 만드는지 이슈에 검색해도 없고
주석도 없으니 맨땅에 헤딩하는 꼴인데
목 마른자가 우물 파야하는게 맞는데
개발 능력도 없으니 힘드네요...

추가할 마음이 없으면 직접 해볼게요...
답이 안보여서 일단 추가해달라고 요청하는거라...

**Comment by KurtBestor** [comment]
이미 Gelbooru 랑 Sankaku 지원하는데 nozomi.la 는 이 둘보다 자료가 더 적은 것 같아서 추가하지 않으려고 해요.
