### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by sopo9880** [KurtBestor/Hitomi-Downloader#2086]
https://yaani24.net/
ani24의 또다른 사이트인 만큼 고개 숙여 부탁드립니다

**Comment by KurtBestor** [comment]
yaani24 도 되게 수정했어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
script 실행 후 파일을 받아보니 파일이 4월은 너의 거짓말로 다운받아집니다. 
파일 이름은 다른데 내용물은 똑같네요. 다른 것들도 4월은 너의 거짓말로만 다운 받아집니다. 

컴퓨터 속의 그녀

version: 2.8a (20-06-21 06:18:53 GMT+0)
platform: Windows-10-10.0.18362
order: -379
group: False
input: https://yaani24.net/ani_list/759.html
dir: hitomi_downloaded_ani24\컴퓨터 속의 그녀
zip: 
type: ani24
artist: None
url: https://yaani24.net/ani_list/759.html
valid: True
done: True
range: ~9999999
range_p: None
single: False
time: 1593480644.66 (Jun 30)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_ani24\컴퓨터 속의 그녀\컴퓨터 속의 그녀.mp4


[URLs]
[0001] LazyUrl(https://yaani24.net/ani_view/2092.html) ---> https://new2.filegroupa.com/redirect.php?path=%2Ffiles%2F0%2F1%7E4000%2Fid_6.mp4


[Messages]
pages: 1
buttons: 7 (컴퓨터 속의 그녀)
stop
EOT: https://yaani24.net/ani_list/759.html


그리고 version: 2.8a (20-06-30 08:11:04 GMT+0)은 ani24 script가 인식이 안됩니다. 
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4520, in exec_script
  File "dynamic_module_0", line 92
    print e
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?

항상 감사합니다.

**Comment by KurtBestor** [comment]
고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
정상적으로 작동됩니다. 감사합니다.
