### ISSUE TITLE
https://xhamster13.com/photos 사진다운방법뭐 없을까요 ?

### ISSUE THREAD

**Issue by dny042** [KurtBestor/Hitomi-Downloader#2087]
https://xhamster13.com/photos/gallery/novinhas-de-biquini-safadinho-14517491 다운받을려고 하는데 포토사진은 다운받기 힘드네요 .. 방법없을까요 ?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1135
