### ISSUE TITLE
'마지막으로 다운받은 날짜 이전 파일은 다운받지 않기' 옵션

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#2088]
이미지들 다운받다보면 필요없는 파일들도 쌓이기 시작해서 삭제를 해야하는데, (특히 트위터)

파일 다운로드를 갱신하려면 필요없어서 지운 파일들도 다시 다운을 받기 때문에

'마지막으로 다운받은 날짜 이전 파일은 다운받지 않기' 옵션 같은게 있으면 유용할것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1932
