### ISSUE TITLE
32비트 / arm 지원 가능할까요?

### ISSUE THREAD

**Issue by franticck** [KurtBestor/Hitomi-Downloader#2089]
서피스 프로 x 를 메인으로 사용하고 있는데 32비트 또는 arm 지원이 가능할까요?

**Comment by KurtBestor** [comment]
32비트 지원 계획은 없어요.

32비트 지원하는 마지막 버전은 여기서 다운로드할 수 있어요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/v2.7h
