### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by Kimyj9** [KurtBestor/Hitomi-Downloader#2090]
네이버 포스트: https://post.naver.com/navigator.nhn
네이버 카페: https://section.cafe.naver.com/

네이버 블로그는 잘 이용하고 있는데 해당 카페하고 포스트도 다운로드 되게 하는건 힘드려나요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
