### ISSUE TITLE
기능 추가 건의 [제목이 동일한 영상 저장시 덮어써지는 문제]

### ISSUE THREAD

**Issue by hentai-redcat** [KurtBestor/Hitomi-Downloader#2094]
안녕하세요 프로그램 정말 잘 사용하고 있습니다.
추가로 유용할 것 같은 기능추가 건의드립니다.

현재 hitomi의 경우 폴더명 형식을 커스텀하여 사용하고 있습니다.
다만 xvideo, pornhub의 경우 간혹 영상제목이 겹칠시 이미 다운된 영상을 덮어쓰는 문제가 있습니다.

이러한 문제로 2가지 건의드립니다.

1. 영상저장시 제목이 겹치는 영상이 있을경우 '타이틀_video번호' 로 저장
=> https://www.xvideos.com/video56582941/japanese_amateur_leak 해당 영상의 경우 'japanese_amateur_leak_56582941' 로 저장
(영상제목과 id모두 겹칠경우는 덮어써도 됨)

2. 영상저장시 제목이 겹치는 영상이 있을경우 '덮어쓰기 혹은 이름변경하여 저장' 이라는 팝업창 띄우기

감사합니다.

**Comment by yuchan39** [comment]
https://www.youtube.com/watch?v=6GWhUKUGPmg

https://www.youtube.com/watch?v=TDVs93c3TXw

위 주소같은 youtube 영상도 주소는 서로  다르지만 생성되는 파일명이 같아서 늦게 받은 것으로
덮어쓰기가 됩니다. 서로 구분되게끔 영상 제목에 조치를 취해야할 것 같습니다.

다운로더 잘 쓰고 있습니다. 항상 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/233
