### ISSUE TITLE
nhentai관련 질문드립니다

### ISSUE THREAD

**Issue by ETRADUN** [KurtBestor/Hitomi-Downloader#2095]
혹시 이제 nhentai 사이트 다운로드는 불가능한건가요?
https://nhentai.com/en/comic/(제목).digital 이주소로도 안되고(can not determine)
https://nhentai.com/g/번호  (can not determine) 
프로그램에서 nhentai_번호 이것도 invailid 뜨네요

**Comment by KurtBestor** [comment]
현재 지원하는 nhentai 사이트는 다음 사이트예요: https://nhentai.net

참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2053
