### ISSUE TITLE
Auto rename options

### ISSUE THREAD

**Issue by tranlamnhatnam** [KurtBestor/Hitomi-Downloader#2096]
Please add an option for the download file to be automatically renamed according to a rule like {filename} + {randomid}, I encountered the situation of downloading multiple files at once but accidentally duplicated and overwritten.

**Comment by KurtBestor** [comment]
It seems like a bad idea.

Maybe it would be helpful: https://github.com/KurtBestor/Hitomi-Downloader/issues/1094

**Comment by tranlamnhatnam** [comment]
Yes, that's the kind of option I want, but do they only support certain services like Hitomi, Pixiv, Youtube? I was download from another service (vimeo) and overwritten.

**Comment by KurtBestor** [comment]
`Filename format` for Youtube is applied to Viemo also.
