### ISSUE TITLE
다운로드를 나스로 바로 받을 순 없을까요?

### ISSUE THREAD

**Issue by 12344353** [KurtBestor/Hitomi-Downloader#2097]
다름이 아니라, 파일을 다운로드 받을때 나스로는 바로 받아지지 않아 다운받은 후 나스로 옮긴다는 번거로운 과정을 거쳐야 하는데, 혹시 바로 나스로 받을 수 있는 방법은 없을까요? ftp로 컴퓨터와 연결해놨습니다.

**Comment by KurtBestor** [comment]
네트워크 드라이브로 연결하고 저장 폴더 지정하세요.

**Comment by cromwellamn** [comment]
> 네트워크 드라이브로 연결하고 저장 폴더 지정하세요.

폴더 지정 창에 네트워크 드라이브가 안 보여요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/539
