### ISSUE TITLE
삭제된 데이터 갱신이 멈춰있습니다.

### ISSUE THREAD

**Issue by cshipa** [KurtBestor/Hitomi-Downloader#2099]
삭제된 데이터 다운로드를 해도 nekomimi mahou shoujo mia 이후로 삭제된 작품들이 표시되지 않습니다.
히토미에서 아예 사라진 작품은 표시되지 않나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2077#issuecomment-648384463
표시 여부는 Hitomi.la 나 Hiyobi.me 에 남아있는 것 기준이에요.
