### ISSUE TITLE
히토미 다운로더가 갑자기 없어지는 현상?

### ISSUE THREAD

**Issue by neuroring** [KurtBestor/Hitomi-Downloader#2101]
한번은 그냥 이상하다고 생각하면서 다시 켰는데 몇일 뒤에 또 이러네요. 그냥 아무런 전조 없이 갑자기 사라집니다... 프로세스에도 안 나오고 CPU  디스크 등등 아무것도 안 쓰고 있는거 같습니다. 정말로 이상한거는 다시 키려고 하면 hitomi downloader is already running이라면서 다시 키는 것조차 할수 없다는겁니다 ㅎㄷㄷㄷ. 난해한 문제이기는한데 혹시나 해결책이 있나 해서 글 올려 봅니다.

**Comment by KurtBestor** [comment]
한번 더 실행해도 안 되나요?

**Comment by neuroring** [comment]
네, 로그아웃하거나 컴퓨터를 다시시작하기 전에는 절대 안 켜집니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1164

**Comment by yuliah6** [comment]
비슷한 문제가 있었네요. 감사합니다.

**Comment by neuroring** [comment]
비슷한 문제가 있었네요. 감사합니다.
