### ISSUE TITLE
마리망 다운이 이루어지지않는 현상

### ISSUE THREAD

**Issue by racikon448** [KurtBestor/Hitomi-Downloader#2103]
마리망(myreadingmanga)에서 다운시 잠깐 다운이 되는듯 돌아가다가 실제로 다운이 되지않고,
표시되는 다운한 페이지숫자도 0p로 뜨며, 폴더에 살펴보아도 파일이 받아져있지않습니다.

예전 관련 이슈들을 검색해서
ctrl+alt+C 를 눌러서 나오는 창에 
__import__('chrome').get_local_version() 
를 입력해보니
다음과 같이 뜹니다.

---

    Traceback (most recent call last):
      File "console\Console.py", line 151, in execSingle
      File "<string>", line 1, in <module>
    ImportError: No module named chrome
    
---
크롬은 한번 삭제했다가 재설치해본후에도 안되서 살펴보니 저런 메시지가 뜹니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by racikon448** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

링크하신 것으로 해보니 제대로 다운이되며 작동합니다. 감사합니다.
