### ISSUE TITLE
Xhamster 다운로드 문제

### ISSUE THREAD

**Issue by melong1001** [KurtBestor/Hitomi-Downloader#2104]
현재 xhamster 사이트의 주소 형식이 변경되면서

예전 https://xhamster13.com/videos/숫자
현재 https://xhamster13.com/videos/영문조합

다운로드가 정상적으로 진행되지 않는 영상들이 있습니다

수정 부탁드립니다

그리고, 항상 최상위 해상도로만 다운로드가 되는것 같은데

혹시 가능하다면
720p나 480p등 선택이 가능하게끔 개선이 되었으면 좋겠습니다

**Comment by melong1001** [comment]
Info 로그 첨부합니다

Invalid: [xhamster] https://xhamster13.com / videos / actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc

version: 2.8a (20-06-26 11:33:53 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://xhamster13.com/videos/actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc
dir: 
zip: 
type: xhamster
artist: None
url: https://xhamster.com/videos/actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc
valid: False
done: True
range: None
range_p: None
single: True
time: 1593846302.26 (Jul 4)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
ERROR: no suitable InfoExtractor for URL https://xhamster.com/videos/x-actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc
stop
Traceback (most recent call last):
File "utils", line 909, in start
File "utils", line 941, in start_
File "xhamster_downloader", line 92, in read
File "xhamster_downloader", line 121, in get_imgs
File "youtube_dl\YoutubeDL", line 831, in extract_info
File "youtube_dl_test", line 15, in report_error
DownloadError: ERROR: no suitable InfoExtractor for URL https://xhamster.com/videos/x-actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc

Invalid: fail=True
EOT: https://xhamster13.com/videos/actual-real-affair-with-my-boss-wife-bound-in-their-bed-hot-xh6wlyc

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by melong1001** [comment]
정상 작동하는것 확인하였습니다. 감사합니다!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by melong1001** [comment]
정상 동작 확인하였습니다. 바쁘실텐데 빠른 처리 감사합니다!!
