### ISSUE TITLE
bestjavporn다운로드가 잘안되네요.

### ISSUE THREAD

**Issue by Yhseo1109** [KurtBestor/Hitomi-Downloader#2111]
[English Subbed] JAV Zukkon / Bakkon AVOP-107 The Young Housewife And The Entire Family Was Perverted So I Ended Up Making Babies With Them

version: 2.8a (20-07-01 07:14:02 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://bestjavporn.com/video/jav-zukkon-bakkon-avop-107-the-young-housewife-and-the-entire-family-was-perverted-so-i-ended-up-making-babies-with-them/?asgtbndr=1
dir: hitomi_downloaded_bestjavporn
zip: 
type: bestjavporn
artist: None
url: https://bestjavporn.com/video/jav-zukkon-bakkon-avop-107-the-young-housewife-and-the-entire-family-was-perverted-so-i-ended-up-making-babies-with-them/?asgtbndr=1
valid: True
done: True
range: None
range_p: None
single: True
time: 1593935065.991419 (Jul 5)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_bestjavporn\[English Subbed] JAV Zukkon ／ Bakkon AVOP-107 The Young Housewife And The Entire Family Was Perverted So I Ended Up Making Babies With Them.mp4

[URLs]
[0001] LazyUrl(None) ---> https://f6940e-deeper.ssl-cdn.com/1111/1563401932972/DEEPER-KENZIE-REEVES-300x250.mp4

[Messages]
stop
EOT: https://bestjavporn.com/video/jav-zukkon-bakkon-avop-107-the-young-housewife-and-the-entire-family-was-perverted-so-i-ended-up-making-babies-with-them/?asgtbndr=1
그냥 사진만 다운로드 되네요!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2105

**Comment by Yhseo1109** [comment]
감사합니다^^

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2105#issuecomment-659819068

**Comment by Yhseo1109** [comment]
아.. 그게 또 그렇게 돼네요. 그 사이트가 좋았는데 아쉽네요.. 감사합니다. 수고하세요^^!!
