### ISSUE TITLE
afreecaTV 문제되는 영상 공통점을 찾아내서 말씀드립니다.

### ISSUE THREAD

**Issue by playground-SCC-kms** [KurtBestor/Hitomi-Downloader#2115]
[생]자리비움]애니음악노래.JPOP

version: 2.8a (20-07-03 04:40:55 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 2
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/55386137
dir: hitomi_downloaded_afreeca
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/55386137
valid: True
done: True
range: None
range_p: None
single: True
time: 1594084718.433814 (Jul 7)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_afreeca\[생]자리비움]애니음악노래.JPOP.mp4

[URLs]
[0001] LazyUrl(http://vod.afreecatv.com/PLAYER/STATION/55386137) ---> M3u8_stream(http://vod-archive-kr-cdn-z01.afreecatv.com/v1/mapped-vod/20200415/596/222860596/REGL_B768300A_222860596_3.php/live/0/index-f2-v1-a1.m3u8)

[Messages]
stop
EOT: http://vod.afreecatv.com/PLAYER/STATION/55386137

------------------------------------------------------------------------------------
매번 같은 문제 때문에 말씀드려서 죄송합니다.
다른 곳 쓸땐 문제없는데 유독 아프리카 티비 다시보기 다운로드만 문제가 좀 있네요^^;;
넘어가서, 제가 문제가 있는 영상과 없는 영상의 차이점을 찾아보니 
맨 아래 

[Messages]
stop
EOT: http://vod.afreecatv.com/PLAYER/STATION/55386137

이 메시지가 나오면 영상 파일의 길이가 달라지고 싱크도 밀리는 현상이 발생하는 것을 확인했습니다.
혹시 저 메시지가 의미하는게 뭔지 알 수 있을까요?
EOT에 대해서 찾아보니 위키피디아에서 전송 끝 문자라고 나오는데 이것과 관련이 있는지 궁금합니다.
(사용했던 프로그램 버전은 현재 올라와있는 2.8a 정식버전과 지금 올라와 있는 테크니컬 프리뷰 모두 해봤습니다.)

항상 잘 쓰고 있습니다. 감사합니다. 좋은 하루 되세요!!

**Comment by KurtBestor** [comment]
모든 작업은 끝나면 EOT (End Of Task) 라고 나와요.

테스트 해봤는데 이상 없네요. 어떤 동영상 플레이어 쓰시나요?

**Comment by playground-SCC-kms** [comment]
동영상 플레이어는 팟플레이어를 씁니다. 버전은 가장 최신 버전인 1.7.21239 입니다.
영상 길이가 이전처럼 많이 잘리는것도 플레이어와 관련이 있단 말씀이신가요?

**Comment by KurtBestor** [comment]
제가 테스트 해 본 바로는 영상 길이나 싱크 모두 문제 없네요. 테스트해본 건 다음 버전이에요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

그래도 문제 발생하면 해당 파일 보내주세요.
