### ISSUE TITLE
"로컬 파일로부터 새작업 만들기"에서 폴더를 여러개 선택할수는 없나요?

### ISSUE THREAD

**Issue by iskt1212** [KurtBestor/Hitomi-Downloader#2116]
모든파일이 다들어있는 폴더째로 선택하면 폴더하나에 모든사진이 다들어가고
폴더를 하나하나선택하기에는 너무 힘들어서요 ㅜ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by iskt1212** [comment]
감사합니다 작동 잘됩니다. ㅜㅜ 충성충성
