### ISSUE TITLE
검색기에서 안 잡히는 경우를 하나 찾았습니다.(히토미)

### ISSUE THREAD

**Issue by ptptptpong** [KurtBestor/Hitomi-Downloader#2118]
https://hitomi.la/doujinshi/closers_tuberose_dl-%ED%95%9C%EA%B5%AD%EC%96%B4-1634676.html

위 링크의 만화는 검색기에서 나오지 않습니다.

그리고 하나 더 말씀드리고 싶은 건 각 만화들의 태그가 누락되는 경우가 자주 발생합니다.
(혹시 특정 태그가 들어가면 태그 자체가 안 나오는 건가 해서 확인해봤는데 그건 아닌 듯합니다.)

**Comment by KurtBestor** [comment]
검색 데이터를 업데이트하세요.

**Comment by ptptptpong** [comment]
기본 데이터와 삭제된 데이터를 모두 다운로드 해 보고,
혹시나 해서 프로그램 삭제 후 재설치를 해 보았으나 같은 문제가 발생했습니다...

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/87008679-16b4f280-c1ff-11ea-9835-67db8eaea647.png)

되는데요..?

**Comment by ptptptpong** [comment]
![K-20200709-663230](https://user-images.githubusercontent.com/67952199/87022840-01958f00-c212-11ea-900c-3b2bc30bf2f4.png)

고급검색에서 제목을 치면 안 나와요...

**Comment by ptptptpong** [comment]
![K-20200709-664458](https://user-images.githubusercontent.com/67952199/87022970-2853c580-c212-11ea-98ac-3bf8d47aa0ac.png)

그리고 이렇게 키워드 안 넣고 다 읽어들이는 방식으로 했을 때(최근 업로드된 만화들만 확인하는 목적), 위에 올린 만화는 빨간망토하고 남편에게 말할 수 없는... 만화 사이에 위치에 있어야 해요. 히토미 사이트에서도 확인했어요.

거짓말하는 게 아니라 되게 좋은 프로그램이라 이거 빠져있다고 알려드리고 싶어서 올리는 거에요ㅠㅠ

**Comment by KurtBestor** [comment]
번호 순으로 정렬이라서, 1634676 은 한참 내려가야 있어요. 그리고 `_` 는 내부적으로 ` `(공백) 으로 변환하고 한 단어로 검색해요.
예) `sole_female` → `"sole female"`

그래서 다음과 같이 검색해서 못 찾는 거에요:
`Closers_Tuberose_DL` → `"Closers Tuberose DL"`

`Closers Tuberose DL` 로 검색하면 나올거예요.

**Comment by ptptptpong** [comment]
제가 프로그램에 대한 이해가 부족해서 제기한 의문이었네요.
바쁘실 텐데 그 와중에 친절한 답변 감사합니다.
