### ISSUE TITLE
스크립트 수정방법에대해 알려주세요

### ISSUE THREAD

**Issue by Sulwolhwa** [KurtBestor/Hitomi-Downloader#2119]
다른 사이트의 웹툰들도 다운받고싶어서 뉴토끼와 툰코와 비슷하게 고쳐보았지만 작동이 잘 되지 않네요;;

우선적으로 호두코믹스를 해보고싶어서 hoduco.com - hodu56.net  으로도 변경해봐도 실행이 안되네요..

수정하는 방법에대해서 자세히 알려주신다면 감사하겠습니다

**Comment by KurtBestor** [comment]
프로그래밍이나 웹 잘 모르면 작성할 수 없을 거예요.

**Comment by Sulwolhwa** [comment]
우선 코딩을 공부해야겠네요
