### ISSUE TITLE
목록에 작업이 2000개가 넘어가니 버벅이네요

### ISSUE THREAD

**Issue by zjaaodRhddl** [KurtBestor/Hitomi-Downloader#2120]
제 컴퓨터 문제인가요? 

느려졌다고 해야하나 클릭을 해도 반응이 늦네요

해결방법이  있을까요?

**Comment by Sulwolhwa** [comment]
완료된 목록을 삭제하시면서 사용하시면 괜찮을것같습니다

만약 못지우시겠다면 ini파일만 다른데로 옮겨놓고 다시 실행시키면 새로운 ini이 생성되니까 그대로 사용하시면 되지않을까요...?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1061
