### ISSUE TITLE
커스텀 스크립트가 잠재적으로 윈도우 파일 경로 버그를 일으킬 가능성이 있습니다

### ISSUE THREAD

**Issue by affinityDrops** [KurtBestor/Hitomi-Downloader#2121]
커스텀 스크립트에 대한 메뉴얼이 전혀 없어서 위키에 올라온 스크립트를 읽으면서 작성을 했습니다

### dot `0x2E`
`Downloader` instance의 `self.title`의 끝에 dot `0x2E`가 들어가면 다운로드 작업이 끝나기 직전 (progress bar가 꽉 채워진 직후)
```
[Messages]
stop
valid=False 2
EOT: cdnhiyo_10000170
```
이런 오류 메시지와 함께 작업이 중지됩니다. 보통 stack traceback 내용이 뜨는데 이 에러는 그것 조차도 없습니다.

다운로드 결과가 있는 위치에 가보면 일단 `self.title`의 이름을 가진 폴더가 보이긴 하는데 폴더를 열어보거나 삭제하려는 시도를 하면 "Location not available"이라는 오류메시지를 띄웁니다. 
그리고 압축파일도 생성이 안됩니다. (압축설정 ZIP 으로 함)

### space `0x20`
`self.title`의 끝에 dot `0x2E` 가 아닌  space `0x20`가 들어가면 오류 메시지 없이 작업이 정상 종료되고 압축파일도 정상적으로 생성됩니다. 하지만 다운로드 결과가 있는 위치에 가보면 `self.title`의 이름을 가진 폴더가 삭제가 되지 않고 남아있으며 삭제하려는 시도를 하면 "Item not found"라는 오류메시지를 띄웁니다. (폴더 내의 파일들은 삭제가 됩니다)

어떻게 구글링을 해서 저 삭제 안되는 골칫덩이들은 삭제하는데에는 성공했습니다.

### 그 외
`self.title`에 `<>:"/\|?*` 가 들어가면 progress bar 자체가 안움직이고 작업이 중지됩니다. 저 문자들은 윈도우 파일명에 쓸 수 없는 문자들입니다.

## 제안
끝 공백문자의 경우에는 trim 해주고 나머지 dot와 `<>:"/\|?*` 문자들에 대해서는 전각문자화 시켜주는 과정이 내부적으로 필요할 것 같습니다. 사실 커스텀 스크립트 만들어서 쓰는 사람이 별로 없어서 그냥 제가 스크립트에 넣으면 그만이지만요

추가적으로 히토미 갤러리 중에서 끝이 dot 로 끝나거나 제목 중간에 `<>:"/\|?*`가 들어간 갤러리 다운로드로 테스트 해보니
전자의 경우 dot를 삭제해버리고 후자의 경우 그냥 제목이 `[123123] [N / A] 정보없음` 이렇게 됩니다.
저렇게 처리하는 것보다는 제가 위에서 말한 전각화  과정을 거쳐주는게 더 좋지 않을까 싶습니다.

**Comment by affinityDrops** [comment]
반각->전각 변환을 추가했는데도 이미지가 저장되는 폴더 이름은 다시 반각으로 바뀌어있네요. 이건 수정이 반드시 필요할 듯 싶습니다.

**Comment by KurtBestor** [comment]
`fucking_encoding` 모듈의 `clean_title` 함수를 쓰세요. 예제 `HDS` 파일에도 씌여지고있어요.
폴더명 길이 제한에 맞춰서 자르거나 잘못된 문자를 고치는 등 윈도 폴더명 생성 규칙에 맞게 바꿔줘요.

**Comment by affinityDrops** [comment]
직접 다 해결했습니다만 `clean_title` 세부 구현을 알 수 있을까요

**Comment by KurtBestor** [comment]
직접 해결했다는 게 어떤 의미인가요? `clean_title` 없이 해결했나요?

**Comment by affinityDrops** [comment]
네

**Comment by KurtBestor** [comment]
```python
def clean_title(title, mode='hard', allow_dot=False, n=None):
    if title is None:
        return title

    if n is None:
        n = MAX_TITLE
    if n <= 0:
        n += MAX_TITLE
    
    try:
        title = title.decode('utf-8')
    except:
        pass

    for remove in removes:
        title = title.replace(remove, '')

    title = parser.unescape(title).strip()
    for r1, r2 in replaces:
        title = title.replace(r1, r2)
    try:
        title = unquote(title)
    except Exception as e:
        print(e)
    
    title = unicodedata.normalize('NFC', title)

    encoding = encodings[0]
    
    if mode == 'hard':
        if title != title.encode(encoding, 'ignore').decode(encoding):
            try:
                test_title = os.path.join(TMPDIR, '{:08X}'.format(randrange(1<<4*8)) + title)
                os.mkdir(test_title)
            except Exception as e:
                print(e)
                title = title.encode(encoding, 'ignore').decode(encoding)
            finally:
                try:
                    os.removedirs(test_title)
                except Exception as e:
                    print(e)
    elif mode == 'safe':
        title = title.encode(encoding, 'ignore').decode(encoding)

    title = title.strip()

    if not allow_dot:
        while title[-1:] == '.':
            title = title[:-1].strip()

    if not title:
        title = '　'

    return crop_text(title, n)
```

**Comment by affinityDrops** [comment]
감사합니다. 이슈 닫을게요
