### ISSUE TITLE
avgle 영상을 다운받으려는데 안되네요...

### ISSUE THREAD

**Issue by staywithme-oops** [KurtBestor/Hitomi-Downloader#2122]
2.8a버전 GUI 파일 다운받았어요
그리고 프로그램켜서 링크넣은다음 다운로드버튼 클릭했더니
빨간색 폰트로
No data;see:https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension

이런 문구가 뜨더니
확장 프로그램을 다운받으라는 창이 뜨네요..
그래서 확장프로그램 다운 후 개발자모드에 들어가서 확장프로그램 업로드 하고
확장프로그램으로 영상 다운로드 버튼 눌렀더니
띠링 하는 소리와 함께 계속 그 확장프로그램 설치법 설명창이 자꾸 떠요...ㅠㅠ
https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension

이 링크창이요...
이것만 나타나고 다운로드가 안되네요ㅠㅠ
센세 방법이 없을까요?

**Comment by staywithme-oops** [comment]
근데 다른분들 문의글보니까 무슨 코딩한거 같은
영어 연산자들 적어놓으셨던데 그거 해야하나요??
해야한다면 어디서 구할수있죠...?

**Comment by staywithme-oops** [comment]
No data; See: https://github.com / KurtBestor / Hitomi-Downloader / wiki / Chrome-Extension

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 1
group: False
input: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704
dir: 
zip: 
type: avgle
artist: None
url: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704
valid: False
done: True
range: None
range_p: None
single: True
time: 1594219414.41 (Jul 8)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

stop
Invalid: fail=False
EOT: https://avgle.com/video/nFTUjUIXAU8/kbj-korean-bj2019012704

**Comment by staywithme-oops** [comment]
그런데 이게 프로그램을 끈 채로 어플다운로드 버튼을 누르면 
Copied! 머시기머시기 라고 뜨면서 다운로드 버튼 누르라는 문구가 나오네요

**Comment by staywithme-oops** [comment]
아 어떻게 하다보니 방법 찾았습니다ㅋㅋㅋ죄송합니다ㅎㅎ

**Comment by staywithme-oops** [comment]
혹시나 잘모르는 분들을 위해 설명드리자면

**Comment by staywithme-oops** [comment]
혹시나 잘모르는 분들을 위해 설명드리자면
저는 프로그램 켜놓은 상태에서 확장앱의 다운로드 버튼을 눌러댔었어요
그런데 알고보니 프로그램 끈 상태에서 확장앱의 버튼을 눌러야 링크가 복사가 되는거고
그리고나서 프로그램을 켜고 다운로드 버튼만 누르면 다운로드가 되네요ㅋㅋㅋ 

감사합니다~~

**Comment by staywithme-oops** [comment]
혼자서 그냥 해결된 고민인데
이거 글 어떻게 삭제하는지 몰겠어서....일단 Close 이거만 눌러놓을게요..

**Comment by KurtBestor** [comment]
프로그램 켠 상태에서 다운로드 누르는 거 맞아요. 이미 동일한 주소의 작업이 추가되어있어서 그게 재시작 된거예요. 지우고 다시 추가해주세요.
