### ISSUE TITLE
압축 방식 문의드립니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2125]
예전에 제가 썼을 때는, 히토미 다운로더로 다운로드 후 자동압축 시, 동일한 이름의 압축 파일이 이미 존재할 경우

기존 압축 파일에  새로 다운받은 파일의 내용이 추가되는 형태였던걸로 기억을 하는데요. (정확하진 않습니다)

지금 다시 사용을 해보니, 동일한 압축 파일이 존재할 경우 기존 압축 내용이 전부 사라지고 새로 다운받은 압축 파일만 남게 되더라구요.

픽시브나 웹툰 등을 다운로드 받을 때, 작가가 비공개나 유료로 전환해서 이미지 수가 오히려 줄어드는 경우가 있는데

현재 압축 방식이 동일한 이름의 압축파일이 있을 경우 기존 파일이 삭제되고 새로 받은 파일만 남는 방식이다 보니,

비공개나 유료 전환된 부분을 미처 확인하지 못하고 다운로드 할 경우 오히려 기존에 있던 파일들이 날아가버리더라구요.

혹시 새로 다운받은 파일과 동일한 이름의 압축 파일이 이미 존재할 경우, 기존 압축 파일 내용을 유지하면서 새로 다운받은 파일만 추가할 수는 없을까요??

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bhfaker** [comment]
완벽하게 해결됐습니다! 정말 감사드립니다 ㅠㅠㅠㅠ
