### ISSUE TITLE
연령제한 걸린 유튜브 영상이 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by chunyuhwa** [KurtBestor/Hitomi-Downloader#2126]
연령제한이 걸린 유튜브 영상이 다운로드가 되지 않습니다.
아래는 다운로드 되지 않는 파일에 작업정보입니다.

Invalid: [youtube] https://www.youtube.com / watch?v=av60pP3Ntaw

version: 2.8a (20-07-09 07:28:24 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.youtube.com/watch?v=av60pP3Ntaw
dir: 
zip: 
type: youtube
artist: None
url: https://www.youtube.com/watch?v=av60pP3Ntaw
valid: False
done: True
range: None
range_p: None
single: True
time: 1594294552.153564 (Jul 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: mp4
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 91 - 256x144 (HLS)
[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 92 - 426x240 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 93 - 640x360 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 94 - 854x480 (HLS)
[None][30.0fps][256kbps] mp4 mp4a.40.2 ─ 95 - 1280x720 (HLS)

No videos
stop
Traceback (most recent call last):
File "utils", line 902, in start
File "utils", line 934, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=av60pP3Ntaw

[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 91 - 256x144 (HLS)
[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 92 - 426x240 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 93 - 640x360 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 94 - 854x480 (HLS)
[None][30.0fps][256kbps] mp4 mp4a.40.2 ─ 95 - 1280x720 (HLS)

No videos
stop
Traceback (most recent call last):
File "utils", line 902, in start
File "utils", line 934, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=av60pP3Ntaw

[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 91 - 256x144 (HLS)
[None][30.0fps][48kbps] mp4 mp4a.40.5 ─ 92 - 426x240 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 93 - 640x360 (HLS)
[None][30.0fps][128kbps] mp4 mp4a.40.2 ─ 94 - 854x480 (HLS)
[None][30.0fps][256kbps] mp4 mp4a.40.2 ─ 95 - 1280x720 (HLS)

No videos
stop
Traceback (most recent call last):
File "utils", line 902, in start
File "utils", line 934, in start_
File "extractor\youtube_downloader", line 382, in read
Exception: No videos

Invalid: fail=True
EOT: https://www.youtube.com/watch?v=av60pP3Ntaw

**Comment by tdi2020** [comment]
유튜브 로그인정보 있는 쿠키를 불러오기 하시면 잘 되실거에요!(옵션->설정->고급->쿠키[불러오기])
쿠키 넣고 테스트 해보니 다운로드 잘 되는 것을 확인하였습니당
