### ISSUE TITLE
파일명에 소수점이 있을때 크기 조절과 포맷 변환 기능이 작동하지 않습니다

### ISSUE THREAD

**Issue by Drillmurata** [KurtBestor/Hitomi-Downloader#2127]
예를들어 218_bonus_01_1007.41_KB.png 이런 식의 파일을 다운로드 하면 위의 기능들이 작동하지 않고 있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Drillmurata** [comment]
기능들이 정상적으로 작동합니다. 감사합니다.
