### ISSUE TITLE
hitomi-data json파일을 다른 프로젝트에서 사용해도 될까요?

### ISSUE THREAD

**Issue by 0x185468** [KurtBestor/Hitomi-Downloader#2129]
안녕하세요

좋은 프로그램 만들어주신 덕분에 잘 사용하고 있습니다.

저는 서버에서 자동으로 만화 다운해주는 프로그램 만들고 있습니다.

KurtBestor님의 데이터가 사용하기 편하게 만들어져있어서

실례가 안되면 제 프로젝트에도 사용해도 되는지, 

만약 된다면 다운받은 파일 자체만 사용해도 되는지 아니면 개발자님이 웹에 올려두신 url그대로 사용해도 되는지 궁금합니다.

감사합니다.

**Comment by KurtBestor** [comment]
저도 허락 받고 데이터 긁은 게 아니라서요. 마음대로 쓰세요.
