### ISSUE TITLE
이미 대기열에 등록되어있는 상태에서 페이지 지정을 수정해서 등록할순없나요?

### ISSUE THREAD

**Issue by qpcnddl1** [KurtBestor/Hitomi-Downloader#2131]
안녕하세요 정말 정말 매일 감사하며 쓰고있는 다운로더입니다.

한가지 여쭤볼게있어서 문의드려요

이미 대기열에 등록되어있는 상태에서 페이지 지정을 수정해서 등록할순없나요?

제가 방법을 못 찾는건지 아니면 원래 등록되어있는 상태에선 수정이 불가능하고
기존 등록된 주소 삭제후 다시 페이지 지정하고 등록을 해야만 하는것인지 문의드려봅니다 ㅎㅎ

만약 삭제후 등록이 맞는거라면 추후에라도 이미 대기열에 등록되어있는 상태에서 수정이 가능한 기능이 업데이트되었으면 좋겠습니다 ㅎㅎ

개발자님 정말 감사합니다!

**Comment by KurtBestor** [comment]
수정해야할 상황이 있나요?
