### ISSUE TITLE
특정 백신에서 내장된 DPI의 사용이 제한되어 버립니다

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader#2132]
이렇게 좋은 툴을 계속 유지보수 해주시느라 수고가 많으십니다.

최근 Bitdefender Total Security라는 유료 백신 프로그램을 사용하기 시작했는데,
Hitomi Downloader GUI을 작동 시, 해당 백신에서 아래 1번째 사진과 같은 경고와 함께 다운로더의 DPI가 2번째 사진처럼 에러를 뿜으며 사용할 수 없게 되어 버리더군요...
![캡처_LI](https://user-images.githubusercontent.com/53351465/87234770-6e29ad00-c40f-11ea-8b76-73eea5287ff0.jpg)
![1](https://user-images.githubusercontent.com/53351465/87234772-7681e800-c40f-11ea-9019-d8299fb7ba03.PNG)
해당 백신의 실시간 보호 기능을 완전히 꺼버리거나, WinDivert64.sys 드라이버 파일을 안타 바이러스 예외 설정으로 해 둘 경우, 에러창의 내용이 다음과 같이 달리 나타나면서 동일하게 DPI 작동이 제한됩니다.
![3](https://user-images.githubusercontent.com/53351465/87234787-8a2d4e80-c40f-11ea-85a4-eaefd3208c26.PNG)

백신 내에서 다운로더 프로그램을 안티 바이러스 기능에서 예외설정해 보아도 별다른 영향은 주지 않을 뿐더러,
실시간 보호 기능이 작동하는 한 저 Application.WinDivert.B라는 코드의 작동 자체를 제한시켜 버리고,
나아가 다운로더의 DPI 우회 기능 자체를 사용하지 못하게 만들어 버립니다
![2](https://user-images.githubusercontent.com/53351465/87234923-d1680f00-c410-11ea-9e1a-221a6af84f58.PNG)

저 코드가 히토미 다운로더 내 DPI 우회 작동에 중요한 요소인 것 같은데...
일단 비트디펜더 측에도 Application.WinDivert.B에 대해 예외 설정을 할 수 있는 지 문의해보고자 합니다만,
혹시 이에 관련해 도움 주시거나 프로그램 개선을 해주실 만한 여지가 있는 지 여쭈어 보고자 이슈 작성해봅니다

**Comment by KurtBestor** [comment]
이건 실행 되나요?: https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.6

**Comment by In-Bound** [comment]
저도 이 문제로 서칭하다가 이 타래를 발견하고 확인해 보았습니다.

알려주신 링크의 goodbyedpi를 내려받으려 하였으나, 마찬가지로 비트디펜더에서 바이러스로 감지하여 다운로드 자체를 막아버립니다.

![deny](https://user-images.githubusercontent.com/68278023/87416681-012e3700-c60a-11ea-9413-cf94d356c549.png)

**Comment by nikin78** [comment]
답변이 늦어 죄송합니다.
 
![보고](https://user-images.githubusercontent.com/53351465/87418719-21132a00-c60d-11ea-80ef-96e32870bcbb.PNG)
일단 해당 백신에서 기본적으로 ON 설정되어 있는 '잠재적으로 원하지 않는 프로그램 검사' 옵션을 OFF 하니 Hitomi Downloader GUI의 DPI 우회 기능은 정상적으로 작동했습니다.
그러나 OFF하는 순간 마찬가지로 DPI 우회 기능이 작동하지 않았고, 이 상태에서 다시 ON 하여도 아래와 같이 에러창이 뜨면서 DPI 우회가 작동하지 않았습니다.

![87234787-8a2d4e80-c40f-11ea-85a4-eaefd3208c26](https://user-images.githubusercontent.com/53351465/87418850-6d5e6a00-c60d-11ea-9cbb-5134663daa80.png)
이 경우, 
C:\Users\신홍권\AppData\Local\Temp
경로의 
WinDivert.dll
WinDivert64.sys
위 두 가지 파일을 삭제한 뒤, 백신의 해당 옵션을 OFF한 상태에서 Hitomi Downloader GUI를 작동시키면 DPI 우회 기능이 정상적으로 실행되었습니다. (WinDivert32.sys는 없었음) 


링크 주신 Goodbye DPI의 경우, 구글 크롬과 비트디펜더 측에서 막아버리기에, 인터넷 익스플로러로 다운 받아 실행해보았습니다.
테스트용 웹사이트로 히토미 (hitomi.la 및 일부 갤러리)와 DLsite (메인 페이지 및 일부 R-18 게임 페이지)를 들어가봤고, ISP는 KT입니다.
처음 몇 분 동안은 백엔드 에러를 겪어서 테스트용 웹사이트로 접속이 불가능했으나, 이 때도 Hitomi Downloader GUI와 다르게 비트디펜더 백신에서 실행을 방해하거나 차단하는 일은 없었습니다.
이후 Goodbye DPI의 옵션을 -1과 -2 두 가지로 번갈아가면서 테스트한 결과, 비트디펜더에서 차단하거나 테스트용 웹사이트들로 접근을 못하는 일 없이 정상적으로 작동되는 것을 확인 했습니다.

![보고2](https://user-images.githubusercontent.com/53351465/87419239-1efd9b00-c60e-11ea-9f78-752faa04887c.PNG)

혹시 참고하는데 필요하시다면 비트디펜더 계정을 잠시 빌려드릴 수 있을 것 같습니다.
아래 주소로 이메일 한 통 보내주시면 초대 링크를 보내드리겠습니다.
ksk070807@gmail.com

**Comment by nikin78** [comment]
답변이 늦어 죄송합니다.

![보고](https://user-images.githubusercontent.com/53351465/87419462-7f8cd800-c60e-11ea-9cc9-909c69e1f4ce.PNG)
일단 해당 백신에서 기본적으로 ON 설정되어 있는 '잠재적으로 원하지 않는 프로그램 검사' 옵션을 OFF 하니 Hitomi Downloader GUI의 DPI 우회 기능은 정상적으로 작동했습니다.
그러나 OFF하는 순간 마찬가지로 DPI 우회 기능이 작동하지 않았고, 이 상태에서 다시 ON 하여도 아래와 같이 에러창이 뜨면서 DPI 우회가 작동하지 않았습니다.

![87234787-8a2d4e80-c40f-11ea-85a4-eaefd3208c26](https://user-images.githubusercontent.com/53351465/87419512-916e7b00-c60e-11ea-8179-677af686ae24.png)
이 경우,
C:\Users\user\AppData\Local\Temp
경로의
WinDivert.dll
WinDivert64.sys
위 두 가지 파일을 삭제한 뒤, 백신의 해당 옵션을 OFF한 상태에서 Hitomi Downloader GUI를 작동시키면 DPI 우회 기능이 정상적으로 실행되었습니다. (WinDivert32.sys는 없었음)

링크 주신 Goodbye DPI의 경우, 구글 크롬과 비트디펜더 측에서 막아버리기에, 인터넷 익스플로러로 다운 받아 실행해보았습니다.
테스트용 웹사이트로 히토미 (hitomi.la 및 일부 갤러리)와 DLsite (메인 페이지 및 일부 R-18 게임 페이지)를 들어가봤고, ISP는 KT입니다.
처음 몇 분 동안은 백엔드 에러를 겪어서 테스트용 웹사이트로 접속이 불가능했으나, 이 때도 Hitomi Downloader GUI와 다르게 비트디펜더 백신에서 실행을 방해하거나 차단하는 일은 없었습니다.
이후 Goodbye DPI의 옵션을 -1과 -2 두 가지로 번갈아가면서 테스트한 결과, 비트디펜더에서 차단하거나 테스트용 웹사이트들로 접근을 못하는 일 없이 정상적으로 작동되는 것을 확인 했습니다.
![보고2](https://user-images.githubusercontent.com/53351465/87419530-98958900-c60e-11ea-8bc3-8237da342c38.PNG)


혹시 참고하는데 필요하시다면 비트디펜더 계정을 잠시 빌려드릴 수 있을 것 같습니다.
아래 주소로 이메일 한 통 보내주시면, 보내신 이메일 주소로 다운로드 링크를 보내드리겠습니다.
ksk070807@gmail.com

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/ValdikSS/GoodbyeDPI/releases/tag/0.1.5

**Comment by nikin78** [comment]
지금 링크 주신 0.1.5는 다운로드 과정에서 비트디펜더나 크롬이 제한하는 일도 없네요.
정상적으로 작동 잘 되고, 비트디펜더에서도 별 다르게 경고 막는 일은 없었습니다.
![문제 없음](https://user-images.githubusercontent.com/53351465/87421519-05f6e900-c612-11ea-959e-83334cf191e4.PNG)

다만 참고하셨으면 하는 점은, 현재 비트디펜더에 
C:\Users\user\AppData\Local\Temp 경로 상의
WinDivert.dll
WinDivert64.sys
두 파일을 검사 예외 처리해 놓은 상태입니다.
처음 문의글 작성 이후 여러 테스트 했을 당시 모두 두 파일을 검사 예외 항목에 넣어두었었네요.
![예외 사항](https://user-images.githubusercontent.com/53351465/87421662-49e9ee00-c612-11ea-93e4-323b654b1a4a.PNG)

**Comment by In-Bound** [comment]
저도 테스트 해봤습니다.

다시 올려주신 goodbyedpi 0.1.5 링크 또한 백신 단에서 차단합니다.

원 타래 작성자 분과는 달리, 백신 자체의 설정은 일절 변경하지 않았습니다.



![re-deny](https://user-images.githubusercontent.com/68278023/87422144-12c80c80-c613-11ea-9c53-73d937a6dc6c.png)

**Comment by KurtBestor** [comment]
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) 또는 [WinDivert](https://www.reqrypt.org/windivert.html) 를 Bitdefender에 False positive 로 보고해주셔야할 것 같아요.
다음 링크에서 보고할 수 있어요: https://www.bitdefender.com/submit/

**Comment by nikin78** [comment]
Goodbye DPI 1.6 과 WinDivert.dll, WinDivert64.sys 파일들을 말씀해주신대로 False positive로 방금 막 보고 했습니다.
다만 비트디펜더가 이러한 보고를 무시하는 경향이 있다 해서, 그 부분이 좀 걱정이긴 하네요;;;
