### ISSUE TITLE
올바르지 않은 형식의 스크립트 문제

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2135]
안녕하세요. 다운로더 잘 쓰고 있습니다.

스크립트 사용을 하려고 하니 

dc와 ruliweb의 스크립트에서 

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4525, in exec_script
  File "dynamic_module_0", line 80
    print 'read_page', url
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('read_page', url)?

같은 메세지가 뜨며 인식이 안되는 현상이 발생합니다.

다운로더는 version: 2.8a (20-07-13 04:30:50 GMT+0)와
version: 2.8a (20-07-07 04:10:18 GMT+0)입니다.

감사합니다.

**Comment by KurtBestor** [comment]
수정했어요. 다시 다운로드해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
정상작동 확인했습니다. 감사합니다.
