### ISSUE TITLE
뉴토끼 다운 안됩니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2139]
[N／A] 잘 자 내 꿈 꿔

version: 2.8a (20-06-10 11:17:37 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://newtoki68.com/webtoon/458123
dir: hitomi_downloaded_newtoki\[N／A] 잘 자 내 꿈 꿔
zip: 
type: newtoki
artist: None
url: https://newtoki68.com/webtoon/458123
valid: True
done: True
range: None
range_p: [55]
single: False
time: 1594714457.09 (Jul 14)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_newtoki\[N／A] 잘 자 내 꿈 꿔\잘 자 내 꿈 꿔 57화\0000.gif

[URLs]
[0001] https://newtoki3.org/img/blank.gif

[Messages]
읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123

읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123

읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123

읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123

읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123

invalid; revert
Dead or Done
EOT: https://newtoki68.com/webtoon/458123

읽는 중... [N／A] 잘 자 내 꿈 꿔 / 잘 자 내 꿈 꿔 57화 (1 / 1)
stop
EOT: https://newtoki68.com/webtoon/458123
이렇게 나옵니다ㅠㅠ

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by KurtBestor** [comment]
테스트 버전으로 실행해주세요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
해봤는데요 안됩니다
x 올바르지 않은 형식의 스크립트입니다 라고 나옵니다...

**Comment by geniussjt** [comment]
자세한 정보 보기에는
 Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4306, in exec_script
  File "dynamic_module_1", line 11, in <module>
ImportError: No module named page_selector

**Comment by geniussjt** [comment]
[N／A] 잘 자 내 꿈 꿔

version: 2.8a (20-07-27 10:16:44 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://newtoki69.com/webtoon/458123
dir: hitomi_downloaded_newtoki\[N／A] 잘 자 내 꿈 꿔
zip: 
type: newtoki
artist: None
url: https://newtoki69.com/webtoon/458123
valid: True
done: True
range: None
range_p: [57]
single: False
time: 1595871901.564197 (Jul 28)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_newtoki\[N／A] 잘 자 내 꿈 꿔\잘 자 내 꿈 꿔 59화\0000.jpg


[URLs]
[0001] https://newtoki3.org/img/cang1.jpg


[Messages]
잘 자 내 꿈 꿔 59화 1
stop
EOT: https://newtoki69.com/webtoon/458123

똑같네요...^^ㅎㅎ

**Comment by KurtBestor** [comment]
작업 정보 보면 잘 된 것 같네요.

**Comment by geniussjt** [comment]
지금 해봤지만 역시나 이상한 이미지 1장만 받아집니다

**Comment by KurtBestor** [comment]
고쳤어요. 다시 다운로드해서 넣어주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by geniussjt** [comment]
와! 정말 잘 됩니다T^T
정말로 감사합니다ㅠㅠ
