### ISSUE TITLE
(테스트버전 클라이언트) 뉴토끼 스크립트 불러오기 오류 제보

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2140]
존경하는 KurtBestor 선생님
테스트버전 (다크모드지원 및 UI 변경버전) 실행하니 뉴토끼 스크립트가 읽어지지 않는 오류가 발생합니다!
오류메세지는 아래와 같습니다.

------------------------------------------------------------------------
[X 올바르지 않은 형식의 스크립트입니다]
[자세한 정보 보기]
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4525, in exec_script
  File "dynamic_module_3", line 162
    print u'read page... {}    ({})'.format(page.url, len(imgs))
                                   ^
SyntaxError: invalid syntax

------------------------------------------------------------------------

이상입니다!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2139
