### ISSUE TITLE
아프리카 다시보기 영상 이름이 같을 경우 덮어쓰기 되는 문제

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2141]
**1.다시보기 이름 동일할때 덮어쓰기 되는 문제**

아마도 현재 다운로드 방식이 그러하여서 방송 이름이 같으면 덮어쓰기 되는 것 같습니다.

**2. 다시보기 영상 날짜 포함 표기 의견**

보통 아프리카 방송 이름은 거의 동일하게 유지하는 경우가 많다보니..

혹시 방송일자를 파일명에 함께 포함해서 중첩되지 않도록 받을 방법이 없을까요?

(다운받은 파일이 언제 방송한건지 날짜가 표기되지 않아 현재는 직접 입력중입니다ㅠㅠ)

예를들어 13일 방송과 14일 방송 제목이  **[생]선생님**  으로 같다면,

[생]선생님-20200713.mp4  
[생]선생님-20200714.mp4  

이렇게 날짜와 함께 따로 저장된다면 중첩되지 않고 받을 수 있을것 같아서요..

항상 감사드립니다!

**Comment by tdi2020** [comment]
적고나서 생각해보니 생성날짜를 추가할 수 있다면.. 
날짜가 앞으로 가는 옵션도 현재 이름방식 지정하듯이 선택할 수 있음 좋을거 같아요.

[생]선생님-20200713.mp4
[생]선생님-20200714.mp4

20200713 [생]선생님.mp4
20200714 [생]선생님.mp4

이런식으루요!

**Comment by tdi2020** [comment]
트위치 클립도 마찬가지로 덮어쓰기 되네요! 트위치 클립도 이름이 같은경우가 많습니다ㅠㅠ
트위치 클립 역시 동일하게 해결하면 좋지 않을까 생각해보았습니다!

**Comment by KurtBestor** [comment]
참고해주세요: #233
