### ISSUE TITLE
사이트 추가 건의

### ISSUE THREAD

**Issue by pico81** [KurtBestor/Hitomi-Downloader#2149]
카카오 페이지 부탁 드립니다.
https://page.kakao.com/main?categoryUid=10&subCategoryUid=1000

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by pico81** [comment]
추가 감사합니다.
쿠기 입력 전에는 다운이 잘되나 쿠키를 입력하니깐
아래와 같이 에러가 발생합니다.

Invalid: [kakaopage] https://page.kakao.com / home?seriesId=54189843

version: 2.8a (20-07-22 17:36:19 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://page.kakao.com/home?seriesId=54189843
dir: 
zip: 
type: kakaopage
artist: None
url: https://page.kakao.com/home?seriesId=54189843
valid: False
done: True
range: None
range_p: None
single: False
time: 1595496568.8127015 (Jul 23)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Invalid header value b'CN10=1595495746623\r; TIARA=pa2xx.eaeAvu_IqgFU-n.QofVhsHiPHZWRKmF3kD5PGnd6Qnnic9UUtOROr.HyqMVbZhz6p3f6aCDY6jGtDxsXBAXE4zvucY; _TI_NID=iok9mjEFfnWoNqMjDA5hhRaRk/XKL01K2m1JpAZ4nSSxAH5swniBByMPgUSrrTBxo2D/vJ4LkfgdLUqAo1X/4w==\r; _fbp=fb.1.1589601107470.1251572213\r; _kadu=9I0TfXjiYb4YiBVn_1580899463329\r; _karmt=fClDPjBMm5aQskprHCIlwsdlEWRINiVzqcuL8XUc60E1FjHyeDaJa9sa4HvGnS_4\r; _karmtea=1598098670\r; _kawlp=TPRze-Upq8onZ0iedCejLT-ff9eaJyg-Rzt569-mfXvuHQlukHSmmyyp1MjFABu5MfLwclL-DuWYauDo2tYUwUrcYyRwBbnRnMPBlmU4k_bulrx_G3l9FPKds9YmBKai\r; _kawlptea=1595495871100\r; _kawlt=Bf7uKCflxdiSy1l3xYk_X9N8r10pyr8ols3Z_tqSd0yGXbKdkYRQdgO0eOR9Iu9CrlI8gDIbUu4R3YuinM1PshvSkd-N0-Mt2-afK0CWjWQLmleXgDpHpwtxhj6M_scL\r; _kawltea=1595571470\r; _kptid=3f1bad31ebfd49cb97316d7cf66ddd3d\r; kd_lang=ko\r; webid=7c53d2c02d6011ea8894000af759e640\r; JSESSIONID=D8B91A7943405E28460B29414B450C1B\r'
stop
Traceback (most recent call last):
File "utils", line 916, in start
File "utils", line 948, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 126, in get_info
File "extractor\kakaopage_downloader", line 80, in get_pages
File "requests\sessions", line 578, in post
File "downloader", line 97, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 449, in send
File "site-packages\urllib3\connectionpool", line 677, in urlopen
File "site-packages\urllib3\connectionpool", line 392, in _make_request
File "http\client", line 1252, in request
File "http\client", line 1293, in _send_request
File "http\client", line 1230, in putheader
ValueError: Invalid header value b'CN10=1595495746623\r; TIARA=pa2xx.eaeAvu_IqgFU-n.QofVhsHiPHZWRKmF3kD5PGnd6Qnnic9UUtOROr.HyqMVbZhz6p3f6aCDY6jGtDxsXBAXE4zvucY; _TI_NID=iok9mjEFfnWoNqMjDA5hhRaRk/XKL01K2m1JpAZ4nSSxAH5swniBByMPgUSrrTBxo2D/vJ4LkfgdLUqAo1X/4w==\r; _fbp=fb.1.1589601107470.1251572213\r; _kadu=9I0TfXjiYb4YiBVn_1580899463329\r; _karmt=fClDPjBMm5aQskprHCIlwsdlEWRINiVzqcuL8XUc60E1FjHyeDaJa9sa4HvGnS_4\r; _karmtea=1598098670\r; _kawlp=TPRze-Upq8onZ0iedCejLT-ff9eaJyg-Rzt569-mfXvuHQlukHSmmyyp1MjFABu5MfLwclL-DuWYauDo2tYUwUrcYyRwBbnRnMPBlmU4k_bulrx_G3l9FPKds9YmBKai\r; _kawlptea=1595495871100\r; _kawlt=Bf7uKCflxdiSy1l3xYk_X9N8r10pyr8ols3Z_tqSd0yGXbKdkYRQdgO0eOR9Iu9CrlI8gDIbUu4R3YuinM1PshvSkd-N0-Mt2-afK0CWjWQLmleXgDpHpwtxhj6M_scL\r; _kawltea=1595571470\r; _kptid=3f1bad31ebfd49cb97316d7cf66ddd3d\r; kd_lang=ko\r; webid=7c53d2c02d6011ea8894000af759e640\r; JSESSIONID=D8B91A7943405E28460B29414B450C1B\r'

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=54189843
