### ISSUE TITLE
히토미 다운로더 기능 관련 문의드립니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2150]
안녕하세요 개발자님! 항상 수고가 많으십니다. 만들어주신 프로그램은 항상 잘 이용하고 있습니다.

다름이 아니라, 프로그램을 이용하는 도중 잘 모르겠는 부분이 몇 가지 있어 여쭤보려 합니다.

1. 원본 이미지 다운로드 기능은 익헨 서버로 받는 경우에만 적용되나요?
https://e-hentai.org/g/1642030/a3b3029620/
위 링크가 실험에 사용한 링크입니다.
익헨 아카이브 기준 원본 이미지 용량이 59mb, 리샘플링 이미지 용량이 1.31mb입니다.
히토미 서버로 다운받을 경우엔 3.1mb가 나옵니다.
히토미 서버로 다운받는 경우, '원본 이미지 다운로드' 옵션 체크 여부와 상관없이 동일한 용량이 나오더군요.
아무래도 원본 이미지 다운로드 기능은 익헨 서버로 다운받는 경우에만 적용되는 듯한데,
익헨 서버의 문제인지 다운로드 속도가 너무 처참하네요... 0kb에서 아예 멈춰버리는 경우도 많구요.
이런 경우엔 어쩔 수 없는건가요?

2. 쿠키를 등록하고 저장을 해도, 프로그램 종료 후 다시 실행하면 쿠키가 사라져서 매번 다시 등록을 해야 하는데요.
원래 그렇게 설계가 된건지, 아니면 제가 뭔가를 놓쳐서 저장이 안되는건지 궁금합니다. 가능하다면 등록한 쿠키가 쭉 유지됐으면 좋겠어요. (기술적으로 여력이 되신다면...)

3. 약간의 수정 요청인데요. 설정 > 고급 > 다운로드 완료 후 자동 제거 기능을 활성화 할 경우 다운로드가 끝난 파일이 자동으로 삭제되는데, 이때 다운로드가 불완전한 파일(노란색으로 뜨는 파일)까지 제거가 돼버려서 오히려 불편한 것 같습니다.
다운로드가 불완전한 파일은 자동 제거에서 제외되면 좋을 듯합니다.

**Comment by KurtBestor** [comment]
1. E(x)Hentai 서버로 받는 경우만 적용돼요.
2. 테스트 버전에서 쿠키 저장 안 되는 버그 있었는데 고쳤어요.
3. 그런 경우에는 `완료된 작업 모두 제거` 기능을 써주세요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bhfaker** [comment]
최신버전은 쿠키 저장 잘 되네요 ㅎㅎ 감사합니다!

**Comment by jaejunghan** [comment]
테스트 버전 다운받아 봤는데 "완료된 작업 모두 제거" 기능은 어디에 있나요? 혹시 자동으로 제거하는 버튼은 없나요?  설정 > 고급 > 다운로드 완료 후 자동 제거 기능 은 불완전하게 작업한 리스트도 제거해서 불편합니다

**Comment by KurtBestor** [comment]
불완전하게 완료된 작업은 자동으로 제거하지 않는 게 나은 것 같아서 고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

`완료된 작업 모두 제거`는 작업 목록에서 마우스 우클릭 하면 보여요.

**Comment by jaejunghan** [comment]
불완전 작업은 삭제되지 않네요 감사합니다.
