### ISSUE TITLE
munpia.com - 문피아

### ISSUE THREAD

**Issue by penismonsters** [KurtBestor/Hitomi-Downloader#2153]
munpia.com에 대한 지원을 추가하십시오. 이 웹 소설은 웹 소설을 호스팅하는 웹 사이트로, 한국어 버전의 Qidian 또는 Syosetu와 같습니다. 현재 여기에서 다운로드하는 것이 거의 불가능하므로 지원을 추가 할 수 있으면 감사하겠습니다.

https://www.munpia.com/

**Comment by s25jin** [comment]
ㅋㅋ 이건 되면 심각해질지 모름.

**Comment by penismonsters** [comment]
이건 심각해

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1439

**Comment by penismonsters** [comment]
> 참고해주세요: #1439

예, 문제가 종결 된 것으로 보입니다.
