### ISSUE TITLE
yaani24.in 스크립트 작동 문제

### ISSUE THREAD

**Issue by yuchan39** [KurtBestor/Hitomi-Downloader#2157]
안녕하세요. 다운로더 잘쓰고 있습니다.

최근 추가해주신 https://yaani24.com 의 주소가 

https://yaani24.in 로 바뀌어서 ani24의 스크립트를 

추가해도 주소가 인식이 되지 않습니다.

다운로더에 https://yaani24.in 의 in을 com으로 

바꾸어서 주소를 입력했을 때와 메모장으로 스크립트의 com을 

전부 in으로 바꾸었을 때는 정상적으로 작동을 합니다.

감사합니다.

**Comment by KurtBestor** [comment]
수정했어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by yuchan39** [comment]
정상작동 확인했습니다. 감사합니다.
