### ISSUE TITLE
뉴토끼 다운로드가 않되고 스크립트가 않읽힙니다.

### ISSUE THREAD

**Issue by qkskfka** [KurtBestor/Hitomi-Downloader#2163]
히토미 다운로더 메뉴-스크립트로 불러왔는데
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4301, in exec_script
  File "dynamic_module_1", line 11, in <module>
ImportError: No module named page_selector
라고 뜨네요 다운창에 주소를 넣어도
Can not determine type: https://newtoki68.com / webtoon / 446371?toon=%EC%84%B1%EC%9D%B8%EC%9B%B9%ED%88%B0

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.16299
order: 0
group: False
input: https://newtoki68.com/webtoon/446371?toon=%EC%84%B1%EC%9D%B8%EC%9B%B9%ED%88%B0
dir: 
zip: 
type: 
artist: None
url: https://newtoki68.com/webtoon/446371?toon=%EC%84%B1%EC%9D%B8%EC%9B%B9%ED%88%B0
valid: False
done: True
range: None
range_p: None
single: False
time: 1595317295.28 (Jul 21)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://newtoki68.com/webtoon/446371?toon=%EC%84%B1%EC%9D%B8%EC%9B%B9%ED%88%B0

로 뜹니다.

**Comment by KurtBestor** [comment]
참고해주세요: #2139
