### ISSUE TITLE
Request for site addition ( Furaffinity )

### ISSUE THREAD

**Issue by BatmanPerbert** [KurtBestor/Hitomi-Downloader#2164]
Hello, First to thank you for a this amazing program!.

I want to make a site request, I want to know if it's possible to add https://www.furaffinity.net/ to the list of supporter sites
I really don't have any idea about programming and well, I just want to know what is needed to add a site to the program
And well thanks again for all the great job!!!

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/1965
