### ISSUE TITLE
toonkor 스크립트 page_selector 에러

### ISSUE THREAD

**Issue by CoderStone** [KurtBestor/Hitomi-Downloader#2165]
모듈이  파이썬에 없는것 같은데요..

![image](https://user-images.githubusercontent.com/34324909/88157263-7f5f8e80-cc45-11ea-85a7-c48df6e0076b.png)

**Comment by KurtBestor** [comment]
테스트 버전을 쓰세요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
