### ISSUE TITLE
다운로더 프로그램 실행 할때 의 시간 문의

### ISSUE THREAD

**Issue by eva3357** [KurtBestor/Hitomi-Downloader#2166]
장마철과 무더운 여름에 고생이 많으십니다.
한가지 문의점이 있어서 글을 남깁니다.
현 버전 업데이트 이전버전은 아이콘 클릭 후 프로그램이 구동 할때 까지 보통 10초 이내로 구동이 완료 되는데
이번 버전으로 업데이트 이후 구동하는데 30초 이상이 걸리고 있습니다.

버전업 하면서 옳바르게 구동 되는 시간인지 아니면 새로 다운 받아야 하는지 문의 드립니다.

아무쪼록 비 피해 없기를 기원 합니다.

감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2005
