### ISSUE TITLE
산카쿠 다운로드에서 페이지 지정이 2000을 넘어가는 영역 부터는 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by MONJYA** [KurtBestor/Hitomi-Downloader#2167]
1000장씩 밖에 다운로드가 되지 않는다고 들어서 0~999 1000~1999식으로 다운로드를 하려고 했는데
2000을 넘어가니 다운로드가 되지 않는것 같습니다.

혹시 이를 고쳐주실 수 있으신가요?? 언제나 감사드립니다.

[chan] uncensored

version: 2.8a (20-05-30 05:37:42 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://chan.sankakucomplex.com/?tags=uncensored
dir: hitomi_downloaded_sankaku\[chan] uncensored
zip: 
type: sankaku
artist: None
url: https://chan.sankakucomplex.com/?tags=uncensored
valid: True
done: True
range: 2000 ~ 2999
range_p: None
single: False
time: 1595485754.99 (Jul 23)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
login... 1
types: img, gif, video
https://chan.sankakucomplex.com/?tags=uncensored
https://chan.sankakucomplex.com/?next=21126542&tags=uncensored&page=2
https://chan.sankakucomplex.com/?next=21125406&tags=uncensored&page=3

(생략)

https://chan.sankakucomplex.com/?next=21087877&tags=uncensored&page=73
https://chan.sankakucomplex.com/?next=21087206&tags=uncensored&page=74
stop
EOT: https://chan.sankakucomplex.com/?tags=uncensored

**Comment by KurtBestor** [comment]
참고해주세요: #1185
