### ISSUE TITLE
뉴토끼 웹툰 스크립트 오류가 발생합니다.

### ISSUE THREAD

**Issue by itmuji** [KurtBestor/Hitomi-Downloader#2171]
다운로드 받은 스크립트를 실행하면 아래와 같이 오류가 발생합니다.

Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4301, in exec_script
  File "dynamic_module_1", line 11, in <module>
ImportError: No module named page_selector

**Comment by STOMLOG** [comment]
저도 똑같은 오류가 발생하네요

**Comment by KurtBestor** [comment]
참고해주세요: #2139

**Comment by KurtBestor** [comment]
테스트 버전으로 실행해주세요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
