### ISSUE TITLE
아바스트에서 랜섬웨어로 인식합니다

### ISSUE THREAD

**Issue by mokingmuffler** [KurtBestor/Hitomi-Downloader#2173]
현재 최신버전이구요,
프로그램을 실행한 상태에서는 아바스트(백신)에서 따로 인식하지 않는데
다운로드를 시작하려고 하면 랜섬웨어로 의심된다고 하네요.

![pppp](https://user-images.githubusercontent.com/68735133/88382169-de0e3f00-cde2-11ea-974d-f9827fd14913.png)

**Comment by KurtBestor** [comment]
예외 규칙에 추가하거나 Avast 에 오진으로 보고해주세요.
