### ISSUE TITLE
압축파일 연결 프로그램 기능 질문드립니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2174]
1. 현재 페이지 수가 많은 파일을 압축할 경우 렉이 굉장히 심해집니다. 왜그런가 하고 봤더니, 작업관리자-성능 부분에 하드디스크 사용량이 100%까지 치솟더라구요. 압축파일 연결 프로그램을 등록하면 이런 현상이 완화될까요?

2. 압축파일 연결 프로그램은 어떻게 등록하는건가요? [...] 버튼을 눌러서 반디집 exe 파일을 선택해도 아무런 반응이 없네요.

3. 혹시 어떤 프로그램을 연결했을 때 압축이 가장 안정적이면서 빠르게 됐는지, 테스트하신 내용같은게 있으시면 알려주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/489

**Comment by KurtBestor** [comment]
렉 걸리는 작업 정보 보여주시면 분석해볼게요.

**Comment by bhfaker** [comment]
아 연결 프로그램이라는게 압축을 하는 프로그램이 아니라 압축된 걸 보여주는 프로그램이었군요
렉이 걸린다는게 특정 작업에 대해서 그런게 아니라 그냥 페이지수가 많고 용량이 크면 렉이 걸린다는 소리였습니다
수천, 수만장 짜리 사진 폴더를 압축 시도하면 하드가 못견디는 것 같더라구요 (반디집으로 압축하면 렉이 훨씬 덜합니다)
