### ISSUE TITLE
픽시브 최대 다운로드 개수 관련

### ISSUE THREAD

**Issue by Aero765** [KurtBestor/Hitomi-Downloader#2176]
픽시브 다운로드 최대 수가 2000인 것 같은데 더 다운로드 할 수 있게 설정할 수 있으면 좋겠습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/91

**Comment by Aero765** [comment]
그게 작동을 하지 않는데 혹시 확인해주실 수 있나요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/88809219-d4277a00-d1ee-11ea-9ced-1d5b9afe7091.png)

잘 되네요

**Comment by Aero765** [comment]
2000개 제한으로 다운받았던 걸 리스트에서 지우고 다시 하니 잘 되네요. 감사합니다.
