### ISSUE TITLE
유튜브 목록 2000개 이상 불러오기 강제해제 안되는 현상

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2177]
Ctrl + Alt + C 눌러서 콘솔창 띄워서 다음 내용 입력하고 Enter 누르면 강제로 풀 수 있어요:

TOO_MANY = 9999

--------------------------------------------------

안녕하세요 존경하는 KurtBestor선생님! 
현재 위 내용대로 입력을 했는데 저는 2천개 까지만 불러와지네요ㅠㅠ 
현재 올려주신 2.8a 최신테스트버전 사용중이며 엔터쳐도 별다른 메세지는 없는 상태라..
혹시 해제하는 방법이 사라지거나 바뀌었나요?

**Comment by KurtBestor** [comment]
참고해주세요: #91

**Comment by KurtBestor** [comment]
또는 `옵션` - `설정` - `고급 설정` - `페이지 지정 다운로드 기본값` 을 켜고 `~3000` 같이 고쳐주세요.

**Comment by tdi2020** [comment]
감사합니다 선생님! 우선 4000으로 바꾸어봤는데 다운로드도 잘 걸리는지 테스트 해보겠습니다!

**Comment by tdi2020** [comment]
다운로드 테스트 해보는 중 보고드립니다!
우선 테스트는 3500개 정도 되는 채널을 받을때 기준이구요
알려주신 방법 두가지를 다 해봤습니다.(다운로드 페이지를 ~4000 으로 시도 1회, 옵션에서 4000으로 설정후 시도 1회)
그랬는데 우선 프로그램 UI 상에서는 1/2000 으로 뜨고, 우클릭해서 정보를 보면 range: ~4000 라고 표기가 되어있습니다!
2000개를 돌파해서도 받아지는지는 완료후 다시 댓을 달아두겠습니다.

**Comment by tdi2020** [comment]
선생님 테스트를 완료하였습니다.
옵션에서 4000으로 되어있고 정보창에서 range: ~4000 으로 되어있는 것 확인 -> 3000개 넘는 영상이 있는 채널 다운시도
이렇게 시도했을때 UI에는 1/2000 으로 표기 후 다운로드 시작하여서, 결국 그 이상으로는 다운로드 되지 않는 현상을 확인하였습니다!
어떻게 해결할 수 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
