### ISSUE TITLE
웹툰 다운로드 누락

### ISSUE THREAD

**Issue by kh0xff** [KurtBestor/Hitomi-Downloader#2178]
안녕하세요
좋은 프로그램 개발해주셔서 감사합니다.
네이버 웹툰을 다운받고 있는데 몇몇화에 이미지 누락현상이 발생합니다.
예를들면 아무개웹툰  221화는 0000번부터 0037까지 총 38개의 jpg파일이 다운되어야하나
폴더에들어가보면 0024부터 0030까지 비어있어 총 31개가 다운되어있습니다.
한화만 이런것이 아닌 몇몇화가 이렇고 몇백화를 하나하나 체크하기가 좀 벅찹니다.
목록에서 제거하고 프로그램을 다시켜고, 주소를 다시입력하고,  다시 다운받아도 누락된 파일이 보충되지는 않고
아무 오류도 없습니다.
누락된 파일만 찾아서 다시 다운받을수 있는 방법이 있을까요?
감사합니다.!

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by kh0xff** [comment]
[new 1.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/4984295/new.1.txt)

이게 제가 여러번 목록에서 제거하고 다시 다운하고 여러번해서
제대로 정보가 남아있을려나 모르겠네요 ㅠ

**Comment by kh0xff** [comment]
notepad++ 로 작성한 txt입니다

**Comment by KurtBestor** [comment]
예전에 다운로드하다가 끄신 것 같은데 삭제하고 다시 다운로드 해주세요.

**Comment by kh0xff** [comment]
넵 다시 해볼께요~ 감사합니다
