### ISSUE TITLE
아프리카는 19딱지붙은게 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by v5598** [KurtBestor/Hitomi-Downloader#2179]

**Comment by tdi2020** [comment]
저도 동일한 증상입니다 선생님!
쿠키는 제대로 넣고 확인하였는데 안되네요.

로그는 아래와 같습니다.
-------------------------------------------------------------------------------------------------
Invalid: [afreeca] http://vod.afreecatv.com / PLAYER / STATION / 59571979

version: 2.8a (20-07-22 17:36:19 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/59571979
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/59571979
valid: False
done: True
range: None
range_p: None
single: True
time: 1595935455.6384094 (Jul 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Invalid header value b'ChatArea=on\r; AbroadChk=FAIL\r; PdboxBbs=tdi2020\r; PdboxTicket=.A32.7bbT56vyHM9fKZk.NfJGFwz1EdZ5ZJx4GK7y_DdK2LVqK6ZLzdj98DqYg3097aovtcqmj2NXj1bEVF6DqmKTWNjyGN9zKaCRciuHW84_YsP1VcQmAKlmZVys6aGYS2EyAuX0r8o3hu_uQmnkspdtW48TuaD04Vlp2Zd4uKxMvQ3ZnfmsyFd3kl-M3DOMAvBnQYK--7H3zKTOTzP5QVbI58hwumOW8Npnw8HJg-XCbn_iIefao2URHAktXiCVbAtp3RfGz_GE79t0OfQTH1LZB50V8zEOO2ljb41AdLqa1hngPWyjXrTA99iXsh_WTbcEC3oPlRMeMWRSXePRdHnROviPI0EsZeC609JjW3CALE4120o4ILQv7NF-cNruN6mE9n_yJyz-I_CnMJqotsOkOyo7sz2jhBm5CYgUuvMJaIlvPekHkDVZjUKI3i5SCgrUS59EtJIdvtGDYotJiAwy8AD1_xuu0Fsyb8_F9QjXk02WyCxY5HwiUp4CqJvnxZaVtngnOdfj9nbKCyt3; PdboxUser=uid%3Dtdi2020%26uno%3D42097045%26age%3D33%26sex%3DA%26A%3DAAE%26B%3DBADD%26unick%3Dtdi2020%26apply_date%3D1590736865%26name_chk%3D1%26sess_adult_chk%3D1%26broad_name_chk%3D1%26change_password%3D\r; RDB=c80300000000004b520000000000000000000000000000000100000021210000000000000001\r; _au=c2cac0cfb4a473d0ad6f91630733be8b\r; _ga=GA1.2.1996992824.1594283117\r; bjStationHistory=%0221532772%0220599082\r; isBbs=1\r'
stop
Traceback (most recent call last):
File "downloader", line 266, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 916, in start
File "utils", line 948, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 58, in get_video
File "downloader", line 409, in read_html
File "downloader", line 307, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 97, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 449, in send
File "site-packages\urllib3\connectionpool", line 677, in urlopen
File "site-packages\urllib3\connectionpool", line 392, in _make_request
File "http\client", line 1252, in request
File "http\client", line 1293, in _send_request
File "http\client", line 1230, in putheader
ValueError: Invalid header value b'ChatArea=on\r; AbroadChk=FAIL\r; PdboxBbs=tdi2020\r; PdboxTicket=.A32.7bbT56vyHM9fKZk.NfJGFwz1EdZ5ZJx4GK7y_DdK2LVqK6ZLzdj98DqYg3097aovtcqmj2NXj1bEVF6DqmKTWNjyGN9zKaCRciuHW84_YsP1VcQmAKlmZVys6aGYS2EyAuX0r8o3hu_uQmnkspdtW48TuaD04Vlp2Zd4uKxMvQ3ZnfmsyFd3kl-M3DOMAvBnQYK--7H3zKTOTzP5QVbI58hwumOW8Npnw8HJg-XCbn_iIefao2URHAktXiCVbAtp3RfGz_GE79t0OfQTH1LZB50V8zEOO2ljb41AdLqa1hngPWyjXrTA99iXsh_WTbcEC3oPlRMeMWRSXePRdHnROviPI0EsZeC609JjW3CALE4120o4ILQv7NF-cNruN6mE9n_yJyz-I_CnMJqotsOkOyo7sz2jhBm5CYgUuvMJaIlvPekHkDVZjUKI3i5SCgrUS59EtJIdvtGDYotJiAwy8AD1_xuu0Fsyb8_F9QjXk02WyCxY5HwiUp4CqJvnxZaVtngnOdfj9nbKCyt3; PdboxUser=uid%3Dtdi2020%26uno%3D42097045%26age%3D33%26sex%3DA%26A%3DAAE%26B%3DBADD%26unick%3Dtdi2020%26apply_date%3D1590736865%26name_chk%3D1%26sess_adult_chk%3D1%26broad_name_chk%3D1%26change_password%3D\r; RDB=c80300000000004b520000000000000000000000000000000100000021210000000000000001\r; _au=c2cac0cfb4a473d0ad6f91630733be8b\r; _ga=GA1.2.1996992824.1594283117\r; bjStationHistory=%0221532772%0220599082\r; isBbs=1\r'

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/59571979

**Comment by KurtBestor** [comment]
쿠키 파일 메모장으로 열어서 오른쪽 아래 보면 이렇게 되어있나요?

![image](https://user-images.githubusercontent.com/14768120/88663880-3614b080-d117-11ea-93dc-ce495efcd56f.png)

**Comment by tdi2020** [comment]
네! UTF-8로 되어있습니다.

그런데 이상한건, 테스트 해보니 잘 받아지던 것도 안받아지네요.

기존에 받았던 것도 안받아져서 그 로그도 함께 남겨보겠습니다.

이 현상으로 봐서는 아프리카에서 뭔가 변경한걸까 싶기도 하고 그러네요.

로그는 아래와 같습니다.

----------------------------------------------------------------------------------
Invalid: [afreeca] http://vod.afreecatv.com / PLAYER / STATION / 59491119

version: 2.8a (20-07-22 17:36:19 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: http://vod.afreecatv.com/PLAYER/STATION/59491119
dir: 
zip: 
type: afreeca
artist: None
url: http://vod.afreecatv.com/PLAYER/STATION/59491119
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1595938799.9184313 (Jul 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
Invalid header value b'ChatArea=on\r; AbroadChk=FAIL\r; PdboxBbs=tdi2020\r; PdboxTicket=.A32.7bbT56vyHM9fKZk.NfJGFwz1EdZ5ZJx4GK7y_DdK2LVqK6ZLzdj98DqYg3097aovtcqmj2NXj1bEVF6DqmKTWNjyGN9zKaCRciuHW84_YsP1VcQmAKlmZVys6aGYS2EyAuX0r8o3hu_uQmnkspdtW48TuaD04Vlp2Zd4uKxMvQ3ZnfmsyFd3kl-M3DOMAvBnQYK--7H3zKTOTzP5QVbI58hwumOW8Npnw8HJg-XCbn_iIefao2URHAktXiCVbAtp3RfGz_GE79t0OfQTH1LZB50V8zEOO2ljb41AdLqa1hngPWyjXrTA99iXsh_WTbcEC3oPlRMeMWRSXePRdHnROviPI0EsZeC609JjW3CALE4120o4ILQv7NF-cNruN6mE9n_yJyz-I_CnMJqotsOkOyo7sz2jhBm5CYgUuvMJaIlvPekHkDVZjUKI3i5SCgrUS59EtJIdvtGDYotJiAwy8AD1_xuu0Fsyb8_F9QjXk02WyCxY5HwiUp4CqJvnxZaVtngnOdfj9nbKCyt3; PdboxUser=uid%3Dtdi2020%26uno%3D42097045%26age%3D33%26sex%3DA%26A%3DAAE%26B%3DBADD%26unick%3Dtdi2020%26apply_date%3D1590736865%26name_chk%3D1%26sess_adult_chk%3D1%26broad_name_chk%3D1%26change_password%3D\r; RDB=c80300000000004b520000000000000000000000000000000100000021210000000000000001\r; _au=c2cac0cfb4a473d0ad6f91630733be8b\r; _ga=GA1.2.1996992824.1594283117\r; bjStationHistory=%0221532772%0220599082\r; isBbs=1\r'
stop
Traceback (most recent call last):
File "downloader", line 266, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 916, in start
File "utils", line 948, in start_
File "extractor\afreeca_downloader", line 46, in read
File "extractor\afreeca_downloader", line 58, in get_video
File "downloader", line 409, in read_html
File "downloader", line 307, in read_html
File "requests\sessions", line 543, in get
File "downloader", line 97, in session_request
File "requests\sessions", line 530, in request
File "requests\sessions", line 643, in send
File "requests\adapters", line 449, in send
File "site-packages\urllib3\connectionpool", line 677, in urlopen
File "site-packages\urllib3\connectionpool", line 392, in _make_request
File "http\client", line 1252, in request
File "http\client", line 1293, in _send_request
File "http\client", line 1230, in putheader
ValueError: Invalid header value b'ChatArea=on\r; AbroadChk=FAIL\r; PdboxBbs=tdi2020\r; PdboxTicket=.A32.7bbT56vyHM9fKZk.NfJGFwz1EdZ5ZJx4GK7y_DdK2LVqK6ZLzdj98DqYg3097aovtcqmj2NXj1bEVF6DqmKTWNjyGN9zKaCRciuHW84_YsP1VcQmAKlmZVys6aGYS2EyAuX0r8o3hu_uQmnkspdtW48TuaD04Vlp2Zd4uKxMvQ3ZnfmsyFd3kl-M3DOMAvBnQYK--7H3zKTOTzP5QVbI58hwumOW8Npnw8HJg-XCbn_iIefao2URHAktXiCVbAtp3RfGz_GE79t0OfQTH1LZB50V8zEOO2ljb41AdLqa1hngPWyjXrTA99iXsh_WTbcEC3oPlRMeMWRSXePRdHnROviPI0EsZeC609JjW3CALE4120o4ILQv7NF-cNruN6mE9n_yJyz-I_CnMJqotsOkOyo7sz2jhBm5CYgUuvMJaIlvPekHkDVZjUKI3i5SCgrUS59EtJIdvtGDYotJiAwy8AD1_xuu0Fsyb8_F9QjXk02WyCxY5HwiUp4CqJvnxZaVtngnOdfj9nbKCyt3; PdboxUser=uid%3Dtdi2020%26uno%3D42097045%26age%3D33%26sex%3DA%26A%3DAAE%26B%3DBADD%26unick%3Dtdi2020%26apply_date%3D1590736865%26name_chk%3D1%26sess_adult_chk%3D1%26broad_name_chk%3D1%26change_password%3D\r; RDB=c80300000000004b520000000000000000000000000000000100000021210000000000000001\r; _au=c2cac0cfb4a473d0ad6f91630733be8b\r; _ga=GA1.2.1996992824.1594283117\r; bjStationHistory=%0221532772%0220599082\r; isBbs=1\r'

Invalid: fail=True
EOT: http://vod.afreecatv.com/PLAYER/STATION/59491119

**Comment by KurtBestor** [comment]
`Unix (LF)` 로 되어있나요?

**Comment by tdi2020** [comment]
헉 아니요! Windows (CRLF) 라고 되어있습니다. Unix (LF)로 되어있어야 하나요?ㄷㄷ

**Comment by KurtBestor** [comment]
CRLF 도 되게 고쳤어요. 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
