### ISSUE TITLE
(수정) 쿠키 Unix (LF) 문제인것 같습니다ㅠㅠ

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2181]
ㅠㅠ 여태 쿠키를 불러오면 Success! 문구가 떠서 쿠키 문제라곤 아예 상상도 못했네요..
만약 Unix (LF)로 되어있지 않은 쿠키는 안내문구가 있으면 알수 있을것 같습니다!..라고 본문 수정하는 중에
두가지 다 되게 수정해주셨네요ㄷㄷ
테스트 후 아래 이슈로 달아두겠습니다 감사합니다!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2179#issuecomment-665016846
