### ISSUE TITLE
Bilibili video download

### ISSUE THREAD

**Issue by blaziken911** [KurtBestor/Hitomi-Downloader#2184]
Hi. Is there anyway to only download 720p video on Bilibili? The downloader always chooses the highest resolution to download (1080p) but I don't need that. Please help me if possible. Thanks.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

You can change it in here: `Options` - `Preferences` - `YouTube` - `Resolution`

**Comment by blaziken911** [comment]
Thanks. It's worked. But another problem is it can only download the first video on list. The others can't.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
