### ISSUE TITLE
히토미 다운로더 검색기능관련 궁금한점 질문드립니다.

### ISSUE THREAD

**Issue by hgd2827** [KurtBestor/Hitomi-Downloader#2188]
안녕하세요 개발자님, 좋은 프로그램 만들어주셔서 감사합니다.
다운로드 검색기 관련해서 모르는 부분이 있어 질문드립니다.

1.  작가나 아티스트가 2명 이상인 경우 원하는 작가를 검색하는 필터링을 어떻게 해야할지 모르겠습니다.
검색으로 "artist:takayaki" 라는 작가만 보고싶은데 결과로 [https://hitomi.la/galleries/1350546.html](https://hitomi.la/galleries/1350546.html) 같이 여러 작가들이 작업한 결과가 나옵니다. 필터를 어떻게 적용해야 할지 해결방법을 모르겠습니다. 

2. 작품을 제작한 작가나 아티스트의 수를 제한하는 필터가 있는지 궁금합니다..
1번 질문과 달리 2명이나 3명이 작업한 작품의 경우 위와같은 검색이 안될것 같아, 페이지와 같이 작가의 숫자를 필터링할 수 있는 기능이 있는지  질문드려 봅니다.

**Comment by KurtBestor** [comment]
작가 1명은 다음과 같이:
![image](https://user-images.githubusercontent.com/14768120/89051574-70888280-d38f-11ea-8b69-cf76f157eac8.png)

작가 4명 미만은 다음과 같이 검색할 수 있어요:
![image](https://user-images.githubusercontent.com/14768120/89051556-68304780-d38f-11ea-90c4-017f75c4f3a1.png)

**Comment by hgd2827** [comment]
> 작가 1명은 다음과 같이:
> ![image](https://user-images.githubusercontent.com/14768120/89051574-70888280-d38f-11ea-8b69-cf76f157eac8.png)
> 
> 작가 4명 미만은 다음과 같이 검색할 수 있어요:
> ![image](https://user-images.githubusercontent.com/14768120/89051556-68304780-d38f-11ea-90c4-017f75c4f3a1.png)

**Comment by hgd2827** [comment]
고급검색으로 검색 하는법  질문하려다 이슈 닫고 열고 했네요;
고급검색도 잘되고 프로그램 잘 사용하고 있습니다. 정말 감사합니다!
