### ISSUE TITLE
폴더명형식처럼 파일명형식도 설정만들어주세요

### ISSUE THREAD

**Issue by mudvayne2** [KurtBestor/Hitomi-Downloader#2189]
지금은 다운받은 이미지들을 한 폴더에 몰아넣기가 어렵네요.

**Comment by KurtBestor** [comment]
YouTube, Vimeo 와 같은 동영상 사이트나 Pixiv 의 경우엔 설정에서 파일명 형식 바꿀 수 있어요.

**Comment by mudvayne2** [comment]
마나모아에서도 파일명설정 만들어주세요 ㅠㅠ
