### ISSUE TITLE
중복 파일 다운로드에 대하여 건의드리고싶은 것이 있습니다.

### ISSUE THREAD

**Issue by lsggr1** [KurtBestor/Hitomi-Downloader#2190]
매번 업데이트 해주셔서 감사합니다. 매우 매우 유용하게 사용하고 있습니다.

눈동자든 엑-헨이든 url을 입력하여 다운로드를 받을 때. 
다운로드 받은 목록에 이미 동일한 url이 있으면 이전 목록의 해당 위치(스크롤)에서 다시 다운로드를 받는 기능을 최근에 업데이트해주신 것 같습니다.

이것이 굉장히 의미있는 기능이기는 하나, 수십 수백개씩 다운로드를 하다 보면,  방금 받았던것같은데 어디갔지? 하면서 스크롤을 내리며 하나하나 뒤져보는 일이 심심찮게 일어나더라구요.

혹시 가능하시다면
다운로드를 받을 때 동일 url이 이미 목록에 있으면, 이전의 항목을 다시 스크롤의 맨 위로 올릴 수 있을까요?

매번 관리 감사드립니다.

**Comment by KurtBestor** [comment]
프로그램 좌측 하단 `정렬 기준`을 `날짜` 로 하면 최근에 다운로드한 순으로 보여요.

**Comment by lsggr1** [comment]
오.. 정말 감사드립니다. 여태 모르고있었네요 !
