### ISSUE TITLE
다운로드 중 렉 현상 (속도저하X)

### ISSUE THREAD

**Issue by fujl1** [KurtBestor/Hitomi-Downloader#2191]
다운로드 중에 그 목록들을 클릭하거나, 스크롤을 내리거나 혹은 옵션 메뉴를 클릭하는 등 다운로더를 건드는 행위 일체가 뚝뚝 끊기네요. 

다운로드 중 인터넷이나 다른 프로그램에는 별문제가 없었는데 

혹시 뭐가 문제인지 아시나요?

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
