### ISSUE TITLE
hitomi 다운오류

### ISSUE THREAD

**Issue by vpdlswprnr** [KurtBestor/Hitomi-Downloader#2192]
2일전부터 갑자기 다운로드가 안되는데 이유가 뭘까요

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 29

Fail : \\?\M:\hitomi2\hitomi_downloaded\[Tokiwa Midori] Sasoware Master ｜ 유혹당한 마스터 (1696096)\011.jpg
Traceback (most recent call last):
File "downloader", line 833, in download
IOError: [Errno 13] Permission denied: u'\\\\?\\M:\\hitomi2\\hitomi_downloaded\\[Tokiwa Midori] Sasoware Master \uff5c \uc720\ud639\ub2f9\ud55c \ub9c8\uc2a4\ud130 (1696096)\\011.jpg'

Fail : \\?\M:\hitomi2\hitomi_downloaded\[Tokiwa Midori] Sasoware Master ｜ 유혹당한 마스터 (1696096)\013.jpg
Traceback (most recent call last):
File "downloader", line 833, in download
IOError: [Errno 13] Permission denied: u'\\\\?\\M:\\hitomi2\\hitomi_downloaded\\[Tokiwa Midori] Sasoware Master \uff5c \uc720\ud639\ub2f9\ud55c \ub9c8\uc2a4\ud130 (1696096)\\013.jpg'

**Comment by KurtBestor** [comment]
백신 설정이나 폴더 권한 설정을 확인해보세요.
