### ISSUE TITLE
pixiv_search 기능이 작동하지 않습니다

### ISSUE THREAD

**Issue by 15789gg** [KurtBestor/Hitomi-Downloader#2195]
다른 기능은 잘되는데 이것만 그러네요.
어떤 태그를 넣어도 Invalid: [pixiv] pixiv_search_ 이렇게만 뜹니다.

[Messages]
PIXIV_TYPE: search
Type: all
info: {'order': 'date_d', 'scd': None, 'ecd': None, 'blt': None, 'bgt': None, 'type': None}
仙狐さん (pixiv_search_仙狐さん)
tags: []
tags_ex: []
'AppPixivAPI' object has no attribute 'no_auth_requests_call'
stop
Traceback (most recent call last):
File "utils", line 927, in start
File "utils", line 960, in start_
File "extractor\pixiv_downloader", line 215, in read
File "extractor\pixiv_downloader", line 381, in get_imgs
AttributeError: 'AppPixivAPI' object has no attribute 'no_auth_requests_call'

Invalid: fail=True
EOT: pixiv_search_仙狐さん

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 15789gg** [comment]
잘 되네요. 감사합니다!
