### ISSUE TITLE
트위치 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by kimchiman1318** [KurtBestor/Hitomi-Downloader#2197]
https://www.twitch.tv/videos/693219357?filter=archives&sort=time

https://www.twitch.tv/videos/693219357?filter=archives&sort=time

Invalid 오류만 나오고 다운로드가 안됩니다.

버전은 최신버전 사용 중 입니다.

**Comment by KurtBestor** [comment]
참고해주세요: #2050
