### ISSUE TITLE
[REQ] Script/hooks documentation

### ISSUE THREAD

**Issue by PBXg33k** [KurtBestor/Hitomi-Downloader#2198]
I'd like to write some scripts to add support for extra sites and move files to my storage server when downloads finishes. I noticed there is support for scripts, but i couldn't find any documentation on it.

Are there any events/hooks i can use to run extra scripts/code whenever a download is finished?

**Comment by KurtBestor** [comment]
I wrote a brief document: https://github.com/KurtBestor/Hitomi-Downloader/wiki/How-to-write-a-script

You can change the download folder at `Options` - `Preferences` - `General` - `Download folder`.

**Comment by PBXg33k** [comment]
Thanks for the link to the howto.

The download folder target isn't the problem. I'm downloading to my local 1TB SSD, but move it to my NAS afterwards manually. I would like to automate this and was hoping i could hook into the app and trigger the move action when Hitomi finishes the download.

**Comment by KurtBestor** [comment]
I added the hook function: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Here is example scripts: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts#hooks
