### ISSUE TITLE
#2073의 추가질문과 건의사항.

### ISSUE THREAD

**Issue by Chiyac** [KurtBestor/Hitomi-Downloader#2200]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2073 의 추가 질문입니다.

히토미 다운로더 내 HDS파일을 이용하면 다시 불러와도 날짜 정보가 살아있다고 하셨는데요.
이미 날짜정보가 다 날라갔으니 ini파일을 빼내는건 할 수가 없을 듯 하고요...
내보내기를 선택하면 hdt확장자밖에 보이지 않아서요.
말씀하신 HDS파일로 내보내기가 어떤 경로로 할 수 있는지 궁금합니다.
![image](https://user-images.githubusercontent.com/67083011/89211793-476d2980-d5fd-11ea-93aa-ebac180ea35b.png)

추가 건의사항입니다.

1. 환경설정에 보면 사용자 지정 태그 설정이 있는데요, 이 태그목록을 저장하거나 불러올 수 있는 기능을 추가해주셨으면 좋겠습니다. 새로 설치시 태그가 날라가있더라고요.

2.랜덤으로 하나 선택(Ctrl+R)키를 눌렀을 때 랜덤선택은 좋은 기능이라고 생각합니다. 다만 랜덤으로 선택된 작품이 항상 같은 자리에 표출되면 좋겠습니다. 누를때마다 한번은 상단에 떠있고 한번은 하단에 떠 있어서 마우스 이동이 번거롭습니다.

앞으로도 히토미 다운로드를 잘 부탁드립니다. 감사합니다.

**Comment by KurtBestor** [comment]
1. 오타예요. HDT 가 맞아요.

1. `사용자 지정 태그` 가 뭔가요? 모든 설정은 `<실행파일명>.ini` 에 들어있어요.

1. <kbd>Enter</kbd> 누르면 파일 열 수 있어요.
