### ISSUE TITLE
추가 기능 건의합니다.

### ISSUE THREAD

**Issue by unnonplayer** [KurtBestor/Hitomi-Downloader#2202]
저 같은 경우에는 내장브라우저로 검색을 하는 경우가 많습니다. 그러나 내장 브라우저의 경우 새탭과 같은 기능이나 우클릭을 통해서 주소 복사와 같은 기능, 그리고 백스페이스를 통해서 뒤로 가기 등의 부수적인 기능이 없어 여러모로 불편함을 가지고 있습니다. 지금도 충분히 이용하고 있지만 약간의 기능을 추가해주신다면 보다 편리하게 사용할 수 있을 것 같습니다. 그러므로 내장 브라우저에서 크롬과 같이 우클릭을 통한 부수적인 기능을 추가해주시면 좋겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by unnonplayer** [comment]
감사합니다.

**Comment by unnonplayer** [comment]
죄송하지만, 파일이 실행되지않습니다.처음에는 트레이로 최소화된 줄알았지만 화면상에 보이지 않습니다. 작업관리자를 통해서 확인은 되지만 정상적으로 작동하지 않는 것같습니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by unnonplayer** [comment]
ㅎㅎ변함이 없네요;;; 테스트버전만 안되네요. 작업관리자에서 프로그램이 보이다가 사라지네요.이게 도움이 될지는 모르겠만 exe파일을 여러번 클릭하면 이미 실행중이라는 창은 보입니다. 하지만 그래도 gui자체가 안보이네요

**Comment by KurtBestor** [comment]
[이것](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview) cmd에서 다음과 같이 실행하면:
```
hitomi_downloader_GUI.exe --debug
```

`debug.txt` 파일이 생길텐데 주시면 분석해볼게요.

**Comment by unnonplayer** [comment]
현재 윈도우10을 사용중인데 cmd에서 디버깅이 실행되나요?
