### ISSUE TITLE
뉴토끼 스크립트를 적용하면 올바르지 않은 형식이라며 추가되지 않는 오류가 발생합니다.

### ISSUE THREAD

**Issue by inspection96** [KurtBestor/Hitomi-Downloader#2203]
현재 올라와있는 최신의 뉴토끼 스크립트를 다운받아 추가하려 하면 오류가 발생합니다.

1. goodbyedpi는 시스템상에서 켜 놓은 상태입니다.
2. 가장 최신 test 버젼과 스크립트를 적용한 상태입니다.

Traceback (most recent call last):
 File "hitomi_downloader_gui", line 4301, in exec_script
 File "dynamic_module_0", line 11, in <module>
ImportError: No module named
page_selector

현재 다운로더의 버전은 2.8a 최신버전입니다.

다른 글에서는 테스트 버전을 받으면 해결된다고 적혀있는데 저 2.8a버전 말고는 찾을 수 없어 글 남깁니다.

**Comment by yuchan39** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

개발자님이 test버전 올리시는 주소입니다.

**Comment by KurtBestor** [comment]
여기요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
