### ISSUE TITLE
마나모아 썸내일은 다운로드가 안되나요?

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#2204]
![06f6337bf66ddcb540382a405de4ae82](https://user-images.githubusercontent.com/41049446/89284922-72ea2580-d68a-11ea-9bab-e47c1b2b7d86.jpg)

해당 페이지의 썸내일이 다운되지 않습니다.

https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748

![afdsfdwv](https://user-images.githubusercontent.com/41049446/89284927-741b5280-d68a-11ea-9d43-1c109b4f0e97.png)
https://manamoa.net/bbs/page.php?hid=manga_detail&manga_id=1748

**Comment by KurtBestor** [comment]
표지와 썸네일은 다운로드하지 않아요.
