### ISSUE TITLE
뉴토끼 스크립트 또 안됩니다..^^

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2206]
[N／A] 허세로 레벨업 하기!

version: 2.8a (20-07-28 14:54:22 GMT+0)
platform: Windows-10-10.0.18362
order: 0
group: False
input: https://newtoki69.com/webtoon/292093
dir: hitomi_downloaded_newtoki\[N／A] 허세로 레벨업 하기!
zip: 
type: newtoki
artist: None
url: https://newtoki69.com/webtoon/292093
valid: True
done: True
range: None
range_p: [173]
single: False
time: 1596637231.9801297 (Aug 5)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
허세로 레벨업 하기! 173화 0 https://newtoki69.com/webtoon/3861750/허세로-레벨업-하기-173화?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0&spage=1
stop
EOT: https://newtoki69.com/webtoon/292093
다운이 완료인데..요 이미지가 아예 안 받아집니다
아무리 몇번을 해도 똑같습니다
암튼 굿 밤되세요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2183

**Comment by geniussjt** [comment]
와 정말 감사합니다
정말 잘됩니다ㅠㅠb척
