### ISSUE TITLE
Not working with SoundCloud 

### ISSUE THREAD

**Issue by Gangmen** [KurtBestor/Hitomi-Downloader#2207]
Try to download, but he says "invalid"
![Screenshot_1](https://user-images.githubusercontent.com/69270685/89460047-575a4a00-d772-11ea-8b02-868f350907be.png)

**Comment by KurtBestor** [comment]
Right click on the task and press <kbd>Info... (I)</kbd>. Can you show me the info?

**Comment by Gangmen** [comment]
> Right click on the task and press Info... (I). Can you show me the info?

Yeah, sure, here for both
![Screenshot_1](https://user-images.githubusercontent.com/69270685/89494753-89de6400-d7bf-11ea-8dbd-4d3e02a7b128.png)
![Screenshot_2](https://user-images.githubusercontent.com/69270685/89494755-8b0f9100-d7bf-11ea-969b-992cf2c7a3e3.png)
![Screenshot_3](https://user-images.githubusercontent.com/69270685/89494756-8b0f9100-d7bf-11ea-9b5d-9ecdb9df5eb6.png)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Gangmen** [comment]
> Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Yeah, it work, thanks! Here is info, maybe this will be usefull
![image](https://user-images.githubusercontent.com/69270685/89531203-87e4c700-d7f8-11ea-8466-a9888a04f612.png)
![image](https://user-images.githubusercontent.com/69270685/89531281-a480ff00-d7f8-11ea-8667-c2fcb40aeb09.png)
For other one is too big, but i think there's nothing special in it
