### ISSUE TITLE
x hamster 오류.. 이유가 뭘까요?

### ISSUE THREAD

**Issue by zifm** [KurtBestor/Hitomi-Downloader#2208]
Invalid: [xhamster] https://xhamster13.com / videos / korean-guy-xhFZkfu

version: 2.8a (20-08-05 17:29:41 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://xhamster13.com/videos/korean-guy-xhFZkfu
dir: 
zip: 
type: xhamster
artist: None
url: https://xhamster.com/videos/korean-guy-xhFZkfu
valid: False
done: True
range: None
range_p: None
single: True
time: 1596673866.1913612 (Aug 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}

[Gallery]
None

[File Names]

[URLs]

[Messages]
ERROR: no suitable InfoExtractor for URL https://xhamster.com/videos/x-korean-guy-xhFZkfu
stop
Traceback (most recent call last):
File "extractor\xhamster_downloader", line 117, in get_imgs
File "youtube_dl\YoutubeDL", line 831, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: no suitable InfoExtractor for URL https://xhamster.com/videos/korean-guy-xhFZkfu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1017, in start_
File "extractor\xhamster_downloader", line 92, in read
File "extractor\xhamster_downloader", line 121, in get_imgs
File "youtube_dl\YoutubeDL", line 831, in extract_info
File "youtube_dl_test", line 16, in report_error
youtube_dl.utils.DownloadError: ERROR: no suitable InfoExtractor for URL https://xhamster.com/videos/x-korean-guy-xhFZkfu

Invalid: fail=True
EOT: https://xhamster13.com/videos/korean-guy-xhFZkfu

으로 나옵니다 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by zifm** [comment]
잘됩니다! 근데 영상 하나하나씩은 잘되는데 채널로 저장하면 0kb에서 멈춰있네요 원래 채널은 저장 안되는건가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by zifm** [comment]
잘됩니다! 정말 감사합니다!!
