### ISSUE TITLE
프로그램 패스워드 오류

### ISSUE THREAD

**Issue by jjunleegood** [KurtBestor/Hitomi-Downloader#2210]
분명 설정 -> 고급 -> 프로그램 패스워드 키고
비밀번호를 입력하고 **저장** 했는데도 다시 켜보니까 적용이 안됩니다

**Comment by jjunleegood** [comment]
영상은 여기있습니다

(영상은 2개로 나누었습니다)

https://drive.google.com/file/d/1uti4KGmwTL8oKGNSpYux57PvqoQSzoj0/view?usp=sharing
https://drive.google.com/file/d/1xYCd-ABwcMqQfmIDZ-qJiknMzzpNcSyf/view?usp=sharing

**Comment by KurtBestor** [comment]
영상을 볼 수 없네요.

**Comment by jjunleegood** [comment]
이제 제대로 보이실 겁니다.
오류때문인지 권한 설정을 해뒀는데 적용이 안된 것 같네요

**Comment by KurtBestor** [comment]
아무 작업이나 선택해서 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by jjunleegood** [comment]
며칠 전에 v3.0 으로 업데이트하고 나니까 괜찮아졌네요
