### ISSUE TITLE
yand.re는 지원 안하시나요?

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#2211]
https://yande.re/post

갤부로나 단보루에 없는 이미지들이 꽤있어서.. 문의드립니다.

**Comment by KurtBestor** [comment]
어떤 이미지들이 갤부루나 단보루에 없는지 알려주세요.

**Comment by jaejunghan** [comment]
https://yande.re/post/show/576412

해당이미지처럼, 양지작품 특전이미지나, 만화표지같은게 덜올라와있고

무엇보다, 일러스트북같은경우 pool형태로 묶여있어습니다.

https://yande.re/pool/show/97360

이렇게요. 특히 앤솔로지나 합동일러집 같은경우, 단보루는 작가 한명씩 찾아야하지만 , 여긴pool형태라서 매우 편합니다

**Comment by jaejunghan** [comment]
또한 화질도 다릅니다. 
https://danbooru.donmai.us/posts/2514347

https://yande.re/post/show/669761

둘다 같은 이미지이지만, 보시면, 스캔질이 다릅니다. 단보루는 색변화도 있고요.

위이미지는 동인지 오마케본이라고, 특전같은 건데, 흑백이라 단보루는 저런 흑백이미지를 잘 취급안합니다, 취급해도 화질이 좋지않고요. 그래서 yand.re도 지원하시는지 해서 문의드립니다.

https://yande.re/post/show/582619

https://yande.re/post/show/582620

https://yande.re/post/show/582621

위 3이미지 처럼 저렇게 흑백은 단보루나 갤보루에서 취급을 안합니다.
