### ISSUE TITLE
히토미 다운로드가 10% 정도 남았을 때 더이상 진행되지가 않습니다

### ISSUE THREAD

**Issue by joyouseoung** [KurtBestor/Hitomi-Downloader#2219]
200페이지를 예로들면 한 180페이지까지만 다운받고 주황색 뜨면서 더이상 다운을 하지 않네요
몇몇 파일이 아니라 그냥 전부 이러는데 무슨 문제인지 알 수 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
