### ISSUE TITLE
다운로드시 일정구간에서 진행이 멈추는 현상

### ISSUE THREAD

**Issue by dktbdh** [KurtBestor/Hitomi-Downloader#2220]
![주석 2020-08-08 195502](https://user-images.githubusercontent.com/22033069/89708324-14d28080-d9b1-11ea-96e2-edb275bbee58.png)

언제나 고생하십니다

**Comment by iskt1212** [comment]
저도 같은증상이네용

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
