### ISSUE TITLE
어제부터 눈동자 다운로드가  안됩니다.

### ISSUE THREAD

**Issue by Noname9984** [KurtBestor/Hitomi-Downloader#2222]
8일 부터 다운로드가 안먹혔는데 기존에는 너무 많이 받아서 서버쪽에 블락이 걸렸을때 이런경우가 발생했었는데
이번에는 VPN 으로 우회해도 다운이 안되네요. 
설정된 서버를 자동에서 수동으로 지정해도 안되는군요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
