### ISSUE TITLE
히토미에서 다운받을 시 이미지 파일이 항상 서너개 이상 받아지질 않습니다

### ISSUE THREAD

**Issue by 213134** [KurtBestor/Hitomi-Downloader#2223]
예를 들어 40페이지라치면 거기서 36페이지까지만 받아지고 나머지는 쭉 계속 멈춥니다. 이러한 경우는 어떤건가요?

**Comment by gkdlqkfk** [comment]
> 예를 들어 40페이지라치면 거기서 36페이지까지만 받아지고 나머지는 쭉 계속 멈춥니다. 이러한 경우는 어떤건가요?

동일증상이 있군요.  저또한 그렇습니다. v2.8a입니다.

**Comment by ThisismyUsesrname** [comment]
저도 어제부터 갑자기 그렇네요 v2.8a 입니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
