### ISSUE TITLE
익헨/히토미 다운 시 완료가 되지 않습니다.

### ISSUE THREAD

**Issue by ExhenHiyoHito** [KurtBestor/Hitomi-Downloader#2224]
나머지 10퍼가 계속 완성되지 않습니다.

삶의 목적이 사라졌습니다.

여유 또한 사라졌습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
