### ISSUE TITLE
다운로드가 중간에서 계속 멈춰버리네요

### ISSUE THREAD

**Issue by zmgpghgh** [KurtBestor/Hitomi-Downloader#2225]
10% 남기고 다운로드가 계속 중단되는 현상이 발생합니다. 설정을 이리저리 바꿔봐도 수정되지 않습니다.

**Comment by Water-Sleep** [comment]
저도 같은 증상입니다.
2일 전까진 잘 받아지던 게 어제부터 갑작스럽게 이런 증상이네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
