### ISSUE TITLE
어디서 소스코드를 볼 수 있나요? Where can I get the full source code?

### ISSUE THREAD

**Issue by 2af09110d6** [KurtBestor/Hitomi-Downloader#2226]
어디에서도 소스코드를 찾을 수 없어서 문의드립니다.

This program is based on the gpl 3.0 license, 
but I cannot find the source code anywhere.

**Comment by Yoon0618** [comment]
https://discordapp.com/channels/625231858912985099/628635968370638857/713966851289251941
Check this message

**Comment by kairan7** [comment]
> 
> 
> https://discordapp.com/channels/625231858912985099/628635968370638857/713966851289251941
> Check this message

Can't open link

**Comment by 2af09110d6** [comment]
This program seems to link pyqt4
Since pyqt4 is under licensed gpl license, so developers need to make all the origin of source code and build tools to public
Aside from this problem, please open the repository for others to contribute to this

**Comment by KurtBestor** [comment]
It uses PyInstaller. It just freezes (packages) Python scripts into stand-alone executable. You can use [PyInstaller Extractor](https://sourceforge.net/projects/pyinstallerextractor/) to extract the source code.

Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/46#issuecomment-666637870

**Comment by 2af09110d6** [comment]
pyc file?

**Comment by KurtBestor** [comment]
Yup.

**Comment by 2af09110d6** [comment]
i'll try that thx
