### ISSUE TITLE
ani24스크립트 추가가 안됩니다

### ISSUE THREAD

**Issue by doslWKdzz** [KurtBestor/Hitomi-Downloader#2228]
개발자님
항상 잘 이용하고 있습니다

애니 24 스크립트가 있다고 해서 추가를 하려고 했는데 
올바르지 않은 형식이라는군요

내용은
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4301, in exec_script
  File "dynamic_module_1", line 14, in <module>
ImportError: No module named page_selector

어떻게 해야 하나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2165#issuecomment-662711161

**Comment by Psychopath7** [comment]
https://github.com/Psychopath7/ohli24_script
