### ISSUE TITLE
히토미에서 다운시에 파일몇개가 사라지는 이슈가 있네요

### ISSUE THREAD

**Issue by DANIELTHELEE** [KurtBestor/Hitomi-Downloader#2229]
8월 7일까지는 정상이였는데 8월 8일부터는 다운도중에 중간에 파일몇개가 사라집니다.

어제는 2.8a 써봤는데 파일 몇개가 날라갔구요.

예전에 받은 2.7h 버젼으로 오늘 실행해보니까 여전히 파일이 날라갑니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217

**Comment by DANIELTHELEE** [comment]
감사합니다
