### ISSUE TITLE
아카라이브 게시글 이미지/동영상 다운로드 스크립트 공유

### ISSUE THREAD

**Issue by meloncafe** [KurtBestor/Hitomi-Downloader#2231]
[arcalive.zip](https://github.com/KurtBestor/Hitomi-Downloader/files/5047473/arcalive.zip)

덕분에 문제 해결됐습니다.
감사합니다.

**Comment by KurtBestor** [comment]
감사해요. 다음 버전에서 호환 안 되는 부분이랑 애매한 부분 조금 고쳐서 위키에 올렸어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
