### ISSUE TITLE
히토미 다운로드파일 자동압축-원본파일 삭제가 안됩니다.

### ISSUE THREAD

**Issue by Evenoah** [KurtBestor/Hitomi-Downloader#2232]
8월 8일쯤부터 옵션-설정-압축에 hitomi zip 원본파일삭제 옵션이 켜져있는데도 압축과 삭제가 동작하지 않습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214, https://github.com/KurtBestor/Hitomi-Downloader/issues/2150#issuecomment-666947730
