### ISSUE TITLE
#2214과 동일한 오류

### ISSUE THREAD

**Issue by adeline1225** [KurtBestor/Hitomi-Downloader#2235]
기기 문제로 32비트만 사용이 가능해서 2.7h 버전을 쓰고 있는데 동일한 문제가 발생합니다. 
2.7 버전(32비트 버전)의 픽스를 지원해 주실 수 없나요...? 선생님...?

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `히토미 설정` - `서버` - `자동` 에 체크하고 `우선순위` 를 눌러서 `Hitomi.la` 를 체크 해제하세요.

**Comment by adeline1225** [comment]
해결됐습니다. 감사합니다.

**Comment by renesmee1307** [comment]
위의 방법대로하니까
새로운 파일을 다운바지 못하고 있습니다.
일단 다시 체크하고 90%다운한다음 다시 체크를 풀고 100%다운을 완료하려고 합니다만
어떻게 해야할까요?
