### ISSUE TITLE
#2214 테스트 프로그램 사용하니까 다운 완료가 되긴 되는데

### ISSUE THREAD

**Issue by jskdlfjdslkf** [KurtBestor/Hitomi-Downloader#2238]
좋은 유틸리티 감사히 사용하고 있습니다.

저도 다른 분들처럼 눈동자 파일이 전체 다 받아지지 않는 오류를 겪고 있는 상황인데.

#2214 에 올리신 테스트 프로그램 자체로 실행해서 다운 받아보면 3장~5장 정도 남겨두고 0.0KB에서 한참 있다가 힘겹게

다운로드가 완료 되긴 되는데

본 프로그램 업뎃 하시기 전까진 이 테스트 프로그램 사용하면 되는건가요?

**Comment by KurtBestor** [comment]
네
