### ISSUE TITLE
불완전한 작업

### ISSUE THREAD

**Issue by ARTEMISdkfmxpalem** [KurtBestor/Hitomi-Downloader#2239]
검색으로 새 작품 찾아보다 다운로드 했는데 다운로드 받은것들이 노란색으로 뜨더라고요 평소에는 잘되다가 갑자기 다운로드가 제대로 안되니 당황스럽네요 왜이러는걸까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2214#issuecomment-671043217
