### ISSUE TITLE
폴더에 있는 작가 이름 불러오기 오류

### ISSUE THREAD

**Issue by howguy** [KurtBestor/Hitomi-Downloader#2247]
searching 0/1상태로 지속되고 동작하지 않습니다.

**Comment by pcjnao** [comment]
아예 없으면 0/1 상태, 하나라도 있으면
Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4455, in foo
TypeError: object of type 'map' has no len()

이런 오류메세지가 납니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
