### ISSUE TITLE
업데이트 하고 부터 v3가 멀웨어로 잡네요

### ISSUE THREAD

**Issue by ejfosejfi** [KurtBestor/Hitomi-Downloader#2252]
그전에는 한번도 그런적 없었는데 업데이트 되고부터 실행하면 멀웨어로 인식하고 프로세스 차단하는데 확인 부탁드립니다

**Comment by ejfosejfi** [comment]
기존에는 안그래서 질문 드리는겁니다 실시간 검사 끄고 하면 작동도 문제는 없어요!

**Comment by KurtBestor** [comment]
[V3](https://www.ahnlab.com/kr/site/support/virus/virus.do) 에 오진으로 보고 부탁드려요.
