### ISSUE TITLE
설정에 booru 설정 건의

### ISSUE THREAD

**Issue by ys7726** [KurtBestor/Hitomi-Downloader#2253]
설정에 히토미,픽시브 등 태그를 추가,제거 할수있는 기능이 있습니다만 booru계열 사이트(gelbooru, danbooru 등)는 설정이 없어서 태그를 입력할수가 없어 불필요한 파일까지 다운받고 있습니다
설정에 booru계열 사이트도 설정할수있게해주세요

**Comment by KurtBestor** [comment]
검색할 때 빼서 검색하면 되지 않나요?

**Comment by ys7726** [comment]
> 검색 할 때 빼서 검색하면되지나요?

빼야할 태그가 너무 많고 검색 할 때마다 빼야할 태그 입력하는것도 불편합니다
픽시브 설정처럼 포함 태그에 -furry,-yaoi 등 입력하면 제외되서 편했으면 좋겠습니다
메뉴-검색기는 히토미만 되지 않나요?
