### ISSUE TITLE
Browser viewer 스크립트는 사용하지 못 하는 건가요?

### ISSUE THREAD

**Issue by ImSejin** [KurtBestor/Hitomi-Downloader#2255]
v2.8 -> v3.0으로 업그레이드하니 wiki에서 제공하던 모든 스크립트가
올바르지 않은 형식이라며 오류가 납니다.
`Browser viewer` 스크립트를 불러왔을 때의 에러 로그입니다.

> Traceback (most recent call last):
  File "hitomi_downloader_gui", line 4615, in exec_script
  File "dynamic_module_3", line 80, in <module>
NameError: name 'unicode' is not defined

현재 wiki에서 다운로드를 시도해도 받을 수 없네요.
지원 중단인 건가요?

**Comment by KurtBestor** [comment]
이유는 모르겠는데 파일 깨져서 다시 업로드했어요. 다시 다운로드해서 적용해주세요.

**Comment by ImSejin** [comment]
문제 없이 보여집니다. 감사합니다
