### ISSUE TITLE
작업폴더 변경 시도시 에러 

### ISSUE THREAD

**Issue by imjh11** [KurtBestor/Hitomi-Downloader#2256]
![주석 2020-08-13 101218](https://user-images.githubusercontent.com/8489222/90083455-857cf280-dd4d-11ea-83ad-2fd2572b357c.png)

작업폴더 이동 시도시 상위폴더만 생성되고 에러발생하고 이동이 되지 않습니다

**Comment by KurtBestor** [comment]
이걸로 시도해서 어떤 에러메시지 나오는지 알려주세요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by imjh11** [comment]
![image](https://user-images.githubusercontent.com/8489222/90306468-7d1ce700-df08-11ea-8ed4-3bb6e5434773.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
