### ISSUE TITLE
불완전한 작업 다시 시작시 압축이 정상적으로 되지 않습니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2257]
히토미 사이트에서 [다운로드 완료 후 자동 압축] 기능과 [자동 압축 시 폴더 삭제] 옵션 활성화 기준입니다.

'불완전한 작업'을 '다시 시작'할 경우, 불완전한 상태로 압축이 됩니다.

제가 테스트 목적으로 여러가지 시험을 해봤는데요.

이미 완료된 작업에 대해, 다운 받은 폴더 내에 'info.txt 파일을 포함하여' 일부 파일을 삭제한 뒤 작업을 '다시 시작'할 경우, 불완전한 부분을 다시 다운로드받은 뒤 정상적으로 압축이 진행됩니다.
하지만 'info.txt 파일이 남아 있는 상태'에서 '다시 시작'을 할 경우, 재다운로드 없이 그냥 그상태 그대로 압축이 진행됩니다.

제 추측으로는, 'info.txt' 파일의 유무로 다운로드 완료 여부를 판단하여 info.txt 파일만 존재하면 다운로드 상태가 불완전하더라도 완전하다고 판단해버리고 그냥 그상태 그대로 압축해버리는 듯합니다.

해당 부분 수정해주시면 정말 감사하겠습니다.

.
.
.

그리고 위의 내용과 어느정도 연관이 있을 듯한데, 한가지 문제가 더 있습니다.

'다운로드 하려는 작업의 폴더와 같은 이름의 폴더가 이미 존재할 경우' 발생하는 문제인데요. (히토미 뿐만 아니라 다른 사이트들에서도 공통적으로 발생)

1. '자동 압축 기능' 비활성화시, 아무것도 다운로드 되지 않고 작업이 끝나버림
> 기존 폴더의 파일은 그대로 유지하면서, 다운로드하고자 하는 파일이 추가로 다운로드 되도록 바뀌면 좋을 것 같습니다.

2. '자동 압축 기능' 활성화시, 기존에 있던 폴더 안의 파일을 전부 삭제하고 새로 다운받은 파일로만 압축파일이 생성됨
>이 문제에 대해서는 이전에 https://github.com/KurtBestor/Hitomi-Downloader/issues/2125 여기서 제가 같은 내용의 문의를 드렸었습니다.
'기존에 있던 폴더 안의 파일을 전부 삭제하고 새로 다운받은 파일로만 압축파일을 생성'하는 방식이 아닌,
'기존에 있던 폴더 안의 파일 + 새로 다운받은 파일 모두 합쳐서 압축'하는 방식으로 변경해달라는 요청이었는데요.
직후 업데이트된 테크니컬 프리뷰 버전에서는 제가 요청드렸던대로 합쳐서 압축하는 방식으로 바뀌었었는데
최신 버전은 다시 기존 파일을 삭제하고 압축하는 방식으로 돌아가 버렸네요.
다시 합쳐서 압축하는 방식으로 돌려주시거나, 압축 방식을 사용자가 선택할 수 있게 해주시면 정말 감사하겠습니다.

**Comment by KurtBestor** [comment]
불완전한 작업은 압축하지 않아요. #2125 에서 수정된 것 그대로예요.

**Comment by bhfaker** [comment]
아.. 불완전한 작업은 일부러 압축을 패스하는거군요.
그런데 같은 이름의 폴더가 있는 경우엔, 제가 아무리 테스트해봐도 #2125 이전으로 돌아가버린 것 같은데 혹시 한번만 더 테스트 해주실 수 있나요?
https://www.pixiv.net/users/41646715 제가 테스트에 사용한 링크입니다
같은 이름의 폴더가 이미 존재 + 자동압축 기능 비활성화 상태에선 아예 다운로드가 안돼구요
같은 이름의 폴더가 이미 존재 + 자동압축 기능 활성화 상태에선 기존에 있던 파일을 제외하고 압축이 진행됩니다

**Comment by KurtBestor** [comment]
테스트 해봤는데 그대로네요.

**Comment by bhfaker** [comment]
아 테스트 몇번 더 하면서 뭐가 문제인지 알았네요.

1번의 [같은 이름의 폴더가 이미 존재 + 자동압축 기능 비활성화 상태] 에서
[해당 작업 우클릭 > 다시 시작] 이렇게 하면 다운로드가 안되고
해당 작업을 삭제하고 다시 추가하는 경우엔 정상적으로 다운로드가 됩니다

2번의 [같은 이름의 폴더가 이미 존재 + 자동압축 기능 활성화 상태] 에서는
같은 이름의 '폴더'만 있는 상태에서 다운로드를 받으면 폴더 내에 파일이 사라지고 새로 받은 내용으로만 압축이 되고
같은 이름의 '압축파일'이 있는 상태에서 다운로드를 받으면 기존 압축파일의 내용 + 새로 다운로드받은 내용이 합쳐진 새로운 압축파일이 만들어집니다

내용 전달하는 과정에서 착오가 있었던 것 같네요. 조건만 정확하게 이해하고 있으면 지금 상태로도 사용하는데 문제 없을듯합니다. 번거롭게 해드려 죄송합니다
