### ISSUE TITLE
지난 버전에서 익헨 쿠키 입력했습니다

### ISSUE THREAD

**Issue by jin00101** [KurtBestor/Hitomi-Downloader#2261]
다운 받을 때 마다 10퍼씩 모자르길래 포럼좀 둘러보니 익헨서버로 받는 방법이 있다길래 찾아서 해봤습니다

쿠키 입력하라고 하길래 쿠키 받아서 넣었는데

그 이후로 익헨에서 벤이라도 먹었는지 연결 거부당하고 있는데

쿠키를 입력하게 되면 이런 경우도 생기나요?

**Comment by KurtBestor** [comment]
새 버전에서 해결됐어요.
