### ISSUE TITLE
2.7버전에서 다운로드가 되지 않습니다

### ISSUE THREAD

**Issue by renesmee1307** [KurtBestor/Hitomi-Downloader#2267]
기기 사정상 32bit를 지원하는 2.7z?버전을 사용하고있습니다
저번업데이트 이후 약 90%에서 다운로드가 멈추어 검색해보니
옵션 > 설정 > 히토미 > 우선 순위 란에서Hitomi.la 를 체크 해제하라는 것을 확인하여 그대로 진행했습니다만
다운로드가 완료가 되는것이 있고 안되는 것이 있어 문의 드립니다

아래 스샷에서 젤 위에껀 완료가 되었지만 나머지것들은 0p 로 표시되면서 다운이 완료되지 않고
히토미 체크 해제 전의 90%완료 상태로 다운로드 폴더 안에 있습니다.

![1212](https://user-images.githubusercontent.com/40549950/90231877-c4e33600-de56-11ea-99d5-839d4222fce1.png)

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
