### ISSUE TITLE
Newgrounds site-request

### ISSUE THREAD

**Issue by Rounlet** [KurtBestor/Hitomi-Downloader#2268]
요전 번에 트위터 원본 이미지 고쳐주신 건 아주 잘 쓰고 있습니다!
점점 완벽에 가까워지는 다운로더가 되는 것 같아 제가 다 뿌듯합니다.

이번엔 사이트 추가 건의인데..
좀 조심스럽긴 합니다.

#995 1년 전에 한번 건의드린 적이 있었는데
저만 건의드리고 있는 상황이기도 하고
얻어다 쓰는 애가 요구사항만 많고 재촉한다는 느낌을 드릴까봐

그간 조용히 Newgrounds 사이트를 존버하고 있었습니다.
사이트만 도메인만 저장하고 있었는데

얼마 전에 또 완벽하게 문제를 해결하신 걸 보고
왠지 불가능은 없으실 거 같다는 느낌을 받았습니다.

그래서 다시 한번 더 요청드릴 수 있는 때가 아닌가해서
요렇게 건의드립니다. 죄송합니다ㅠㅠ

그래도 한국에서 우후죽순 생겼다가 갑자기 없어지는 사이트들은 아니고
일본의 Pixiv보다 더 나은 갤러리 사이트인데
hentai-Foundry 처럼 모자이크를 하지 않아도 되는 특징이 있습니다.

다른 갤러리 사이트들은 거의 다 다운로더에 있는 반면에
Newgrounds는 좀 주목받지 못하는 것 같아 요청드리게 됐는데 

다운로더가 작동하기 힘든 사이트인지 만이라도 알려주셨으면 합니다.
만약 그렇다고 하시면 희망 접고 수작업하겠습니다..ㅋㅋ

**Comment by KurtBestor** [comment]
사이트가 다루는 게 좀 다양해서 (게임 / 음악 / 영상 / 그림 등) 엄두가 안 나네요. 하나 하나 다 구현해야 하니까요.

**Comment by Rounlet** [comment]
ㅠㅠ 그렇군요. 
여러 탭으로 분리되있다보니 하나하나 다 구현해야한다는걸 깜빡했네요.

가짓수가 적은 영상이나 게임 등은 수동으로 받아도 상관없지만
ART 탭에 있는 이미지들은 100장이 넘어가는 경우가 상당히 많아서

url을 https://아티스트.newgrounds.com/art <- 이런 식으로 끝에 art가 들어가야 진행되는 경우는 안될까요?
이미지만이라도 다운로더로 가능한지 여쭤보고 싶습니다.ㅠㅠ

질척대서 죄송해유..
