### ISSUE TITLE
다크모드 했을때 Maximum download speed가 안보임

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#2270]
숫자가 안보여요
![캡처](https://user-images.githubusercontent.com/56113395/90312841-c427ce00-df42-11ea-97c4-44427deb6ec2.PNG)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ATGOS** [comment]
언제나 사랑합니다 보스
