### ISSUE TITLE
웨이보 앨범이 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#2271]
지난번 테스트 버젼?도 안되고 패치된 버젼에서도 동작이 되지 않습니다.

확인 부탁드립니다. 감사합니다.

**Comment by KurtBestor** [comment]
원래 제 계정으로 로그인하게 해 뒀는데 막혔네요.
로그인 쿠키 입력하는 방식으로 바꿨어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by cocokakao** [comment]
정상 작동됩니다 정말 감사합니다 ㅎㅎ
