### ISSUE TITLE
중복 이미지 찾기 실행시 메모리 사용량이 12gb 가까이 찍네요 ..

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#2274]
![image](https://user-images.githubusercontent.com/53850082/90317704-2940eb00-df66-11ea-87e5-b7f7d0e99d46.png)

메모리 사용량이 아무리 최대치찍어도 2기가는 안넘는데.. 왜 갑자기이럴까요 ...?

11만장 찾는중이고 

외장하드에서 실행중입니다 .

이글쓰는도중에 6기가로 떨어지네요 .. 

![image](https://user-images.githubusercontent.com/53850082/90317676-07dfff00-df66-11ea-822b-fc133ba29e81.png)

**Comment by KurtBestor** [comment]
Python2 에서 Python3 로 올렸는데 일부 빌트인함수가 달라져서 해시가 너무 커져서 생긴 문제예요.
`비슷한 이미지 포함` 을 껐을 때 발생해요.
`cache_imgs.db` 도 되게 커졌을텐데 지우고 다시 써주세요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
답변 보고 cache_imgs.db  확인해보니 22.4GB 더군요 ;; 

테스트 결과 500MB 미만입니다 .!
