### ISSUE TITLE
유튜브 MP3 다운로드 오류입니다.

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2275]
MP4로는 다운로드가 되는데, MP3로 다운받으려고 하면 변환 도중에 에러가 뜹니다.
저와 비슷한 문제로 이슈 올리신 분들이 계셔서 확인해봤는데, ffmpeg를 다운받으라고 하시던데 어떻게 사용하는건가요? 더블클릭해도 아무 반응이 없어서요.

아래는 작업 정보입니다.

【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】

version: 3.0 (20-08-14 04:14:21 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://www.youtube.com/watch?v=kkuGToIXQwI
dir: hitomi_downloaded_youtube
zip: 
type: youtube
artist: Alice Margatroid
url: https://www.youtube.com/watch?v=kkuGToIXQwI
valid: False
done: True
range: ~100000
range_p: None
single: True
time: 1597547019.4505565 (Aug 16)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: mp3
p2f: None
segment: {'chunk': 1048576, 'n_threads': 4, 'overwrite': True}

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_youtube\【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】.mp3

[URLs]
[0001] LazyUrl(https://www.youtube.com/watch?v=kkuGToIXQwI) ---> https://r5---sn-n3cgv5qc5oq-bh2lz.googlevideo.com/videoplayback?expire=1597568619&ei=C6I4X_fcLYiQqQGalbqoDg&ip=211.215.135.202&id=o-APdTZKQII8O3qbk4d7k-zbJEWoghDDFXUYaPsXHTCHWJ&itag=251&source=youtube&requiressl=yes&mh=ur&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2lz%2Csn-i3b7knsl&ms=au%2Conr&mv=m&mvi=5&pcm2cms=yes&pl=14&gcr=kr&initcwndbps=946250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3941929&dur=246.061&lmt=1540548575388800&mt=1597546897&fvip=5&keepalive=yes&fexp=23883098&c=WEB&txp=5411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALvm9ShTmuwqxRY3WJUTBLvUtRyXlNQF0dP2omOkI1z0AiEA_IoTVpVMFWMIdFYXL4mYzOofbYog31MpoVr5-TzaNEQ%3D&sig=AOq0QJ8wRQIgV8eK2PaPitP7TH8mIlWBiJM82XVic7sGanqE-XuGTDICIQDYZNTunjDQAM8uy_xMI1Yhq4BbSg2nD0iMhjNR3rkH7g==&ratebypass=yes

[Messages]
[None][0fps][50kbps] webm opus ─ 249 - audio only (tiny)
[None][0fps][70kbps] webm opus ─ 250 - audio only (tiny)
[None][0fps][128kbps] m4a mp4a.40.2 ─ 140 - audio only (tiny)
[None][0fps][160kbps] webm opus ─ 251 - audio only (tiny)
[144p][6fps][None] webm None ─ 278 - 256x144 (144p)
[144p][6fps][None] mp4 None ─ 160 - 256x144 (144p)
[240p][6fps][None] webm None ─ 242 - 426x240 (240p)
[240p][6fps][None] mp4 None ─ 133 - 426x240 (240p)
[360p][6fps][None] webm None ─ 243 - 640x360 (360p)
[360p][6fps][None] mp4 None ─ 134 - 640x360 (360p)
[480p][6fps][None] webm None ─ 244 - 854x480 (480p)
[480p][6fps][None] mp4 None ─ 135 - 854x480 (480p)
[720p][6fps][None] webm None ─ 247 - 1280x720 (720p)
[720p][6fps][None] mp4 None ─ 136 - 1280x720 (720p)
[360p][6fps][96kbps] mp4 mp4a.40.2 ─ 18 - 640x360 (360p)

# stream_final <youtube_dl_test.Video object at 0x0000023C22346408> 251 - audio only (tiny) None webm opus 0fps
Resolution: None
Codec: None / opus
Abr: 160kbps
Subtype: webm
FPS: 0

Convert: D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】.webm
rename (1): D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】.webm -> D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\tmpf9803722d50143fa82a0d7e4ae76f374_i.webm
-i tmpf9803722d50143fa82a0d7e4ae76f374_i.webm -shortest -preset ultrafast -b:a 320k tmpf9803722d50143fa82a0d7e4ae76f374_o.mp3
【ffmpeg】 load...
【ffmpeg】 loaded
[code]
0
[out]
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers 
built with gcc 8.2.1 (GCC) 20181017 
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth 
libavutil 56. 22.100 / 56. 22.100 
libavcodec 58. 35.100 / 58. 35.100 
libavformat 58. 20.100 / 58. 20.100 
libavdevice 58. 5.100 / 58. 5.100 
libavfilter 7. 40.101 / 7. 40.101 
libswscale 5. 3.100 / 5. 3.100 
libswresample 3. 3.100 / 3. 3.100 
libpostproc 55. 3.100 / 55. 3.100 
Input #0, matroska,webm, from 'tmpf9803722d50143fa82a0d7e4ae76f374_i.webm': 
Metadata: 
encoder : google/video-file 
Duration: 00:04:06.06, start: -0.007000, bitrate: 128 kb/s 
Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default) 
Codec AVOption preset (Configuration preset) specified for output file #0 (tmpf9803722d50143fa82a0d7e4ae76f374_o.mp3) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream. 
Stream mapping: 
Stream #0:0 -> #0:0 (opus (native) -> mp3 (libmp3lame)) 
Press [q] to stop, [?] for help 
Output #0, mp3, to 'tmpf9803722d50143fa82a0d7e4ae76f374_o.mp3': 
Metadata: 
TSSE : Lavf58.20.100 
Stream #0:0(eng): Audio: mp3 (libmp3lame), 48000 Hz, stereo, fltp, 320 kb/s (default) 
Metadata: 
encoder : Lavc58.35.100 libmp3lame 
size= 256kB time=00:00:12.04 bitrate= 174.0kbits/s speed=24.1x size= 768kB time=00:00:24.28 bitrate= 259.0kbits/s speed=24.3x size= 1280kB time=00:00:36.04 bitrate= 290.9kbits/s speed= 24x size= 1792kB time=00:00:47.49 bitrate= 309.1kbits/s speed=23.7x size= 2304kB time=00:00:59.52 bitrate= 317.1kbits/s speed=23.8x size= 2560kB time=00:01:11.40 bitrate= 293.7kbits/s speed=23.8x size= 3072kB time=00:01:23.44 bitrate= 301.6kbits/s speed=23.8x size= 3584kB time=00:01:33.62 bitrate= 313.6kbits/s speed=23.4x size= 3840kB time=00:01:44.71 bitrate= 300.4kbits/s speed=23.3x size= 4352kB time=00:01:56.64 bitrate= 305.7kbits/s speed=23.3x size= 4864kB time=00:02:08.73 bitrate= 309.5kbits/s speed=23.4x size= 5376kB time=00:02:20.66 bitrate= 313.1kbits/s speed=23.4x size= 5888kB time=00:02:32.68 bitrate= 315.9kbits/s speed=23.5x size= 6400kB time=00:02:44.56 bitrate= 318.6kbits/s speed=23.5x size= 6656kB time=00:02:56.20 bitrate= 309.4kbits/s speed=23.5x size= 7168kB time=00:03:07.00 bitrate= 314.0kbits/s speed=23.4x size= 7680kB time=00:03:18.84 bitrate= 316.4kbits/s speed=23.4x size= 8192kB time=00:03:30.84 bitrate= 318.3kbits/s speed=23.4x size= 8704kB time=00:03:42.96 bitrate= 319.8kbits/s speed=23.4x size= 8960kB time=00:03:53.90 bitrate= 313.8kbits/s speed=23.4x size= 9472kB time=00:04:05.54 bitrate= 316.0kbits/s speed=23.4x size= 9613kB time=00:04:06.04 bitrate= 320.1kbits/s speed=23.4x 
video:0kB audio:9612kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.010210% 

rename (1): D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\tmpf9803722d50143fa82a0d7e4ae76f374_o.mp3 -> hitomi_downloaded_youtube\【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】.mp3
rename (1): D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\【東方ボーカル】 「シンデレラアバター」 【幽閉サテライト】【Subbed】.mp3 -> D:\(01) File\Kurt Bestor\hitomi_downloaded_youtube\tmp60768fe41230455aab187b55bb174a9a_i.mp3
Traceback (most recent call last):
File "site-packages\FUCK\JpegImagePlugin", line 612, in _save
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "extractor\youtube_downloader", line 312, in _pp
File "ffmpeg", line 448, in add_cover
File "site-packages\FUCK\Image", line 2134, in save
File "site-packages\FUCK\JpegImagePlugin", line 614, in _save
OSError: cannot write mode RGBA as JPEG

stop
valid=False 2
EOT: https://www.youtube.com/watch?v=kkuGToIXQwI

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bhfaker** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

정상적으로 잘 작동합니다. 감사합니다!
