### ISSUE TITLE
히토미 다운로드시 리더에서 클립보드 추가가 안되는 문제

### ISSUE THREAD

**Issue by giggle1092** [KurtBestor/Hitomi-Downloader#2277]
https://hitomi.la/manga/~ 로 시작하는 링크에서는 클립보드 자동 추가시 추가가 되는데

https://hitomi.la/reader/~ 로 시작하는 링크에서는 클립보드 자동 추가가 안되네요

3.0b버전입니다

언제나 좋은 프로그램 개발에 감사드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by giggle1092** [comment]
잘 작동합니다.

감사합니다.
