### ISSUE TITLE
중복 이미지 찾기 중 중복이미지 에 특수문자? 같은거 포함된 이미지 오류로 삭제 불가

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#2278]
![image](https://user-images.githubusercontent.com/53850082/90332712-432c0d80-dffa-11ea-9c59-2173d12ea198.png)

사진에 있다싶이 저 색이 있는 특수문자(?) 같은것이 삭제가 안됩니다.

오류라고뜨면서요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
![image](https://user-images.githubusercontent.com/53850082/90427143-1f9dbb80-e0fd-11ea-9e44-3d86615084cd.png)

오류가 나오네요 ;;;

**Comment by kenasis428** [comment]
![image](https://user-images.githubusercontent.com/53850082/90427785-faf61380-e0fd-11ea-98da-1957c4782311.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
![image](https://user-images.githubusercontent.com/53850082/90468415-759c4e80-e151-11ea-80b9-2ea51c1fe815.png)

오류창이 더 길어졋습니다 ..

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
잘 작동 됩니다!
