### ISSUE TITLE
뉴토끼 다운이 안돼요

### ISSUE THREAD

**Issue by Psychopath7** [KurtBestor/Hitomi-Downloader#2280]
뉴토끼 다운이 안될뿐더러 기존의 URL도 몰라 Replace URLs 을 해도 바꾸지 못하겠어요 ㅠㅠ
해결해주세요!! 이미 뉴토끼 스크립트 추가는 했어요! 이런 앱 만들어주셔서 항상 감사드리고 있고 사랑합니다!!ㅎㅎ
게다가 들어가는 방법에 따라 URL도 달라지는데 괜찮은 건가요?
https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711 이거랑
https://newtoki72.com/webtoon/46711/%EB%82%98-%ED%98%BC%EC%9E%90%EB%A7%8C-%EB%A0%88%EB%B2%A8%EC%97%85?toon=%EC%9D%BC%EB%B0%98%EC%9B%B9%ED%88%B0 이거랑
https://newtoki72.com/webtoon/46711 등 더 있을 수도 있는데 일단 이거 3개는 전부 같은 거에요! 혹시몰라서 제보합니당^^

Invalid: [newtoki] https://newtoki72.com / bbs / / board.php?bo_table=webtoon&wr_id=46711

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711
dir: 
zip: 
type: newtoki
artist: None
url: https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711
valid: False
done: True
range: None
range_p: None
single: False
time: 1597579895.2042193 (Aug 16)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
name 'get_soup' is not defined
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "<string>", line 71, in read
File "<string>", line 52, in soup
NameError: name 'get_soup' is not defined

Invalid: fail=True
EOT: https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711

name 'get_soup' is not defined
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "<string>", line 71, in read
File "<string>", line 52, in soup
NameError: name 'get_soup' is not defined

Invalid: fail=True
EOT: https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711

name 'get_soup' is not defined
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "<string>", line 71, in read
File "<string>", line 52, in soup
NameError: name 'get_soup' is not defined

Invalid: fail=True
EOT: https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711

**Comment by KurtBestor** [comment]
스크립트 어떻게 넣었나요?

**Comment by Psychopath7** [comment]
제가 이거 한지 얼마안돼서 잘못했을 수도 있어요;; ㅠㅠ 일단 Ctrl+Alt+C 했더니 오른쪽에 뭐가 떠서 History 왼쪽 칸에 붙여넣고 Enter키 눌렀더니 '사이트가 추가되었습니다! Newtoki' 였나..? 이런식으로 떴었어요! 제가 뭔가 잘못해서 안되는건가요? 알려주세요! ㅜㅜ

**Comment by Psychopath7** [comment]
이렇게 한 후에 링크 주소 창에다가 https://newtoki72.com/bbs//board.php?bo_table=webtoon&wr_id=46711 를 붙여넣었는데 Invalid 뭐라뭐라 빨간글씨로 떠서 다운을 받을 수 없어요 ㅠㅠ

**Comment by Psychopath7** [comment]
도우말 스크립트 사용법 확인 후 그대로 해보니깐 됐어요! 감사합니당!!ㅎ
