### ISSUE TITLE
익헨 전체내려받기는 안되는건가요?

### ISSUE THREAD

**Issue by sksktl85** [KurtBestor/Hitomi-Downloader#2289]
Can not determine type: https://exhentai.org / tag / artist:nanoless

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://exhentai.org/tag/artist:nanoless
dir: 
zip: 
type: exhen
artist: None
url: https://exhentai.org/tag/artist:nanoless
valid: False
done: True
range: None
range_p: None
single: False
time: 1597712326.9903011 (Aug 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://exhentai.org/tag/artist:nanoless

작가 태그로 검색해서 하니깐 안되네요

**Comment by KurtBestor** [comment]
개별 갤러리만 지원해요

**Comment by sksktl85** [comment]
답변 감사합니다 유튜브는 전체내려받기가 되던데 아쉽네요
