### ISSUE TITLE
겔부루 다운이 안되네요

### ISSUE THREAD

**Issue by Re0Ma** [KurtBestor/Hitomi-Downloader#2290]
https://gelbooru.com/index.php?page=post&s=list&tags=sesshouin_kiara
이 링크를 다운 받으려 했는데 안되네요
그 외에 다른 겔부루 링크도 해봤는데 안됬습니다

**Comment by Jprototypem** [comment]
저도 같은 오류입니다
로그를 보면
[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=iinuma_toshinori&pid=0&limit=100
stop
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=iinuma_toshinori

invalid; revert
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=iinuma_toshinori&pid=0&limit=100
stop
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=iinuma_toshinori

invalid; revert
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=iinuma_toshinori&pid=0&limit=100
stop
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=iinuma_toshinori

invalid; revert

라고만 떠있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Re0Ma** [comment]
잘되네요 감사합니다
