### ISSUE TITLE
과거에 올려놓은 목록이 Can not determine type으로 뜨면서 다운이 안되네요.

### ISSUE THREAD

**Issue by aghector** [KurtBestor/Hitomi-Downloader#2293]
수고하십니다.  그 동안 감사히 잘 쓰고 있습니다.
3.0 업데이트 이후 목록에 올린 것은 hitomi.la/galleries/ 숫자 .html 로 표기되고 있고, 정상적으로 다운로드 되는데 
전에 올려놓은 목록들은 can not determine type 으로 뜨면서 다운로드가 안되네요...
링크 복사해보면 파일 이름이 복사되고 실제 갤러리로 연결되지 않습니다.
파일을 검색해보면 삭제되거나 한건 아닌거 같은데....

예시)

Can not determine type: [Shibayuki] Raikou-san to ｜ 라이코 씨와 (1658290)

version: 2.8a (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 1967
group: False
input: [Shibayuki] Raikou-san to ｜ 라이코 씨와 (1658290)
dir: 
zip: 
type: hitomi
artist: None
url: [Shibayuki] Raikou-san to ｜ 라이코 씨와 (1658290)
valid: False
done: True
range: None
range_p: None
single: False
time: 1597764422.688 (Aug 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
갤러리 넘버: 1658290

제목: Raikou-san to ｜ 라이코 씨와

작가: shibayuki

그룹: shibayukiya

타입: doujinshi

시리즈: fate grand order

캐릭터: gudao, minamoto no raikou

태그: full color, mosaic censorship, female:big breasts, female:bikini, female:milf, female:sole female, female:swimsuit, male:sole male

언어: Korean

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: [Shibayuki] Raikou-san to ｜ 라이코 씨와 (1658290)

**Comment by KurtBestor** [comment]
아마 v3.0 때 오류일거예요. v3.0b 부터 추가한 건 괜찮을 거예요.

**Comment by aghector** [comment]
> 아마 v3.0 때 오류일거예요. v3.0b 부터 추가한 건 괜찮을 거예요.

답변 감사합니다.
 3.0 이전에 올려놓은 목록들은 목록에서 지우고 다시 올리는 방법밖에 없는건가요?

**Comment by KurtBestor** [comment]
3.0 이전에 검색기에서 추가했다가 3.0 버전에서 다운로드 시작한 작업은 지우고 다시 올려야 될거예요.
