### ISSUE TITLE
익헨 주소가 복사 붙여넣기가 안됩니다....

### ISSUE THREAD

**Issue by oalsi** [KurtBestor/Hitomi-Downloader#2294]
항상 잘쓰고 있는 사람입니다.
 어느 순간부터 익헨 주소를 주소창에 ctrl+v 으로 입력해도 붙여넣기가 안됩니다. 
옆에 클립을 누르면 가능하지만 전에는 ctrl+v를 누르면 주소가 넣어졌는데... 확인 부탁드립니다^^

**Comment by KurtBestor** [comment]
어떤 주소가 안 되나요?

**Comment by oalsi** [comment]
답장이 늦어 죄송합니다. 전체적으로 익헨 주소를 단축키로 붙혀넣기를 할 수가 없습니다. 좋은 앱 잘 쓰고 있습니다^^

**Comment by KurtBestor** [comment]
테스트해봤는데 잘 되는데 안 알려주시면 확인 할 수가 없어요.

**Comment by oalsi** [comment]
안되는 주소를 알려달라는 말씀인가요? 

https://exhentai.org/g/1713569/486afc366d/

이런 형식의 주소는 전부 단축키(ctrl+v)로 붙여넣기가 안됩니다.
대략적으로 1달 전 부터 이런 현상이 발생했습니다.

**Comment by KurtBestor** [comment]
어떤 버전인가요?

**Comment by oalsi** [comment]
도움말-정보에서 확인해보니 v3.0b 라고 적혀있네요

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by oalsi** [comment]
이 버젼도 붙여넣기가 되지 않습니다....ㅠㅠ

**Comment by oalsi** [comment]
선생님 원인을 알 거 같습니다. 제가 익헨을 들어갈 떄 닷지크롬을 이용해서 들어가는데 닷지크롬의 익헨 주소를 크롬으로 복사하여 다운로더의 주소창에 붙여넣기를 해보니 붙여넣기가 정상적으로 됩니다. 아마도 닷지크롬의 기능오류로 그러는 거 같습니다.

**Comment by KurtBestor** [comment]
다른 사이트 주소는 잘 되나요?

**Comment by oalsi** [comment]
네 아마도 닷지크롬 문제 인 거 같습니다. 근데 예전엔 닷지크롬에서도 잘 됐는데 갑자기 이러는 이유를 모르겠네요. 닷지크롬은 그만 써야 될 거 같네요...
