### ISSUE TITLE
갤부루 다운이 안되네요 ..

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#2297]
silence_girl

version: 3.0b (20-08-18 05:30:26 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://gelbooru.com/index.php?page=post&s=list&tags=silence_girl
dir: hitomi_downloaded_gelbooru\silence_girl
zip: 
type: gelbooru
artist: None
url: https://gelbooru.com/index.php?page=post&s=list&tags=silence_girl
valid: True
done: True
range: None
range_p: None
single: False
time: 1597819857.218815 (Aug 19)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://gelbooru.com/index.php?page=dapi&s=post&q=index&tags=silence_girl&pid=0&limit=100
stop
EOT: https://gelbooru.com/index.php?page=post&s=list&tags=silence_girl

일단 이거 작업정보창이구요 .

모든 겔부루 주소로 다운을 시도하면 
![image](https://user-images.githubusercontent.com/53850082/90602036-0b100f00-e234-11ea-84db-d65d0c5f992b.png)
이러고 끝납니다.

새로운거 있는데도 그냥 0장으로 끝나요

기존에 잠금으로 계속 목록에 띄워둔것은 약 2일전 마지막으로 다운받은정보를 끝으로 새로운 이미지가 있어도 0장으로 끝납니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2290

**Comment by kenasis428** [comment]
확인완료 잘 작동합니다.!
