### ISSUE TITLE
트위터 다운 안되는 오래된 트윗이 있는데요

### ISSUE THREAD

**Issue by xel04** [KurtBestor/Hitomi-Downloader#2298]
https://twitter.com/thinkerstatus/status/983000730830123008

안녕하세요. v3.0b 업데이트 후에도 위 계정을 긁어보니 위 주소처럼 오래된 트윗 몇개가 다운로드가 안 됩니다. 개별 트윗은 이상없이 다운로드가 되고요. 무슨 문제일까요?

**Comment by KurtBestor** [comment]
업데이트 전에는 잘 됐나요?

**Comment by xel04** [comment]
3.0때에도 동일하게 최근 트윗만 다운됐었습니다. 업데이트 이력에 "Twitter 오래된 트윗 다운로드 안 되는 문제 해결 (#2244, #2263)"이 있는걸 보고 다시 해봤는데도 변함이 없어서 드린 말씀입니다.

**Comment by KurtBestor** [comment]
다른 계정은 검색이 되는데 이 계정은 검색이 안 되네요. 뭔가 특별한 거라도 있나요?

![image](https://user-images.githubusercontent.com/14768120/90772182-42171b00-e32f-11ea-912a-5153d1cd5e5a.png)

**Comment by xel04** [comment]
제가 로그인한 계정으로는 검색결과가 잘 나오는데 이상하네요. 로그아웃하고 문제 계정에 접속해보니 "민감한 콘텐츠를 포함할 수 있는 프로필"이라고 나오는데 혹시 이거 때문일까요?

**Comment by xel04** [comment]
@92M 계정같은 경우에는 민감한 프로필도 아닌데 마찬가지로 검색결과가 안 나오네요. 그 이유는 아닌 것 같습니다.

**Comment by xel04** [comment]
from:92M 같은 경우에는 민감한 프로필도 아닌데 마찬가지로 검색결과가 안 나오네요. 그 이유는 아닌 것 같습니다.
