### ISSUE TITLE
Avgle 다운로드 중 invalid 현상에 대해

### ISSUE THREAD

**Issue by Phantom156** [KurtBestor/Hitomi-Downloader#2300]
언제나 잘 사용하고 있음에 감사부터 드립니다.

어떤 영상은 되고, 어떤 영상은 안되는 것 같습니다.
로그 참고로 확인 부탁드려요.

Invalid: [avgle] https://avgle.com / video / kOsNaNyRBNG / 素人ゆり-本物リアルｏｌに中出し-連発-2

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://avgle.com/video/kOsNaNyRBNG/素人ゆり-本物リアルｏｌに中出し-連発-2
dir: 
zip: 
type: avgle
artist: None
url: https://avgle.com/video/kOsNaNyRBNG/素人ゆり-本物リアルｏｌに中出し-連発-2
valid: False
done: True
range: None
range_p: None
single: True
time: 1597841964.9858332 (Aug 19)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-31-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-32-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-33-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-34-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-31-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-32-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-33-v1-a1.ts
https://ip107311891.cdn.qooqlevideo.com/key=P9wt2SgZbpXqZxiXNKanCw,s=,end=1597885107,limit=2/data=1597885107/state=Xz0hhsog/reftag=56109644/media=hlsA/ssd3/177/3/202114263.mp4/seg-34-v1-a1.ts
'M3u8_stream' object has no attribute 'referer_seg'
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\avgle_downloader", line 35, in read
File "<decorator-gen-64>", line 2, in get_video
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "extractor\avgle_downloader", line 63, in get_video
File "<decorator-gen-8>", line 2, in __init__
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "m3u8_tools", line 76, in __init__
AttributeError: 'M3u8_stream' object has no attribute 'referer_seg'

Invalid: fail=True
EOT: https://avgle.com/video/kOsNaNyRBNG/素人ゆり-本物リアルｏｌに中出し-連発-2

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
