### ISSUE TITLE
히토미 다운중에 이미지가 몇개씩 빠집니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#2301]
1.히토미 다운이 잘 안 됩니다

2.예를 들어서 300개 링크 추가하면?
100개 정도가 제목이 오렌지색으로 변하고 중지되는데

폴더 열기로 들어가 보면 
이미지 100개 받아야 되는걸 
몇개만 받아놓고 있더군요

불완전한 작업? 다시시작? 해도
그냥 이미지 빠진 그상태 그대로 작업완료가 됩니다

3.이를 어찌하면 좋겠습니까? ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by q2343454** [comment]
음....테스트 버전으로 해결이 된거 같.....습니다 아직 확실하지 않으니 좀더 알아보겠습니다
