### ISSUE TITLE
주소 입력 방식과 이름 입력 방식?의 중복

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#2302]
www.pixiv.net/작가번호 이런 식으로 목록에 추가했을떄랑 pixiv_작가번호 이렇게 목록으로 추가했을때 서로 같은 작가라도 목록이 두 개가 중복으로 생기는데요, 같은 목록으로 합쳐지는게 낫지 않을까요?

예를 들어 평소에는 pixiv_숫자 이렇게 저장했다가 이전에 있던 같은 작가를 www.pixiv.net/숫자 이걸로 목록에 추가하면 이전 목록이 이미 있는걸 인식을 못하고 새로 목록에 추가해버리고 파일도 처음부터 다시 다 받아버립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
이미 추가한 것들은 [F3] 눌러서 필터 켜고 `dup:` 입력해서 확인할 수 있어요.
