### ISSUE TITLE
Is it possible to increase the download speed if hitomi.la is blocked in the country?

### ISSUE THREAD

**Issue by Tsumi15** [KurtBestor/Hitomi-Downloader#2304]
![image](https://user-images.githubusercontent.com/69927064/90694233-f7d76080-e280-11ea-92b1-f82c96933f1f.png)

**Comment by KurtBestor** [comment]
Which country do you live in?

**Comment by Tsumi15** [comment]
> Which country do you live in?

I'm from Russia

**Comment by KurtBestor** [comment]
Have you turned on `Options` - `Preferences` - `Advanced Setting` - `Bypass DPI`?

**Comment by Tsumi15** [comment]
> Have you turned on `Options` - `Preferences` - `Advanced Setting` - `Bypass DPI`?

Yes, activated

**Comment by KurtBestor** [comment]
Have you tried [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)?

**Comment by Tsumi15** [comment]
> Have you tried [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)?

I'll try, I hope I can figure it out

**Comment by Tsumi15** [comment]
> Have you tried [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)?

I turn on "GoodbyeDPI", but after that Hitomi Downloader turns off :(

"Hitomi Downloader offline*"

**Comment by Tsumi15** [comment]
> Have you tried [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)?

Hitomi Downloader for some reason and my vpn turns off
