### ISSUE TITLE
겔부르 다운 안된다고 해서 새로받은 프로그램 문제.

### ISSUE THREAD

**Issue by kenasis428** [KurtBestor/Hitomi-Downloader#2305]
중복이미지 찾기 기능중에서 삭제가 안되요 .

분명히 휴지통으로 보낸 이미지인데 정장 휴지통에는 없습니다 .

그리고 다시 중복 이미지 찾기를 하면 떡하니 다시 중복 이미지 찾기 목록에 떠있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kenasis428** [comment]
잘 작동합니다!

**Comment by KurtBestor** [comment]
어떤 오류 메시지 나오나요?

**Comment by kenasis428** [comment]
![image](https://user-images.githubusercontent.com/53850082/90728730-66a7ce80-e300-11ea-82ad-892b0636bf70.png)

![image](https://user-images.githubusercontent.com/53850082/90728845-98209a00-e300-11ea-8e59-082ee266bae1.png)


일단 전에 떳던 오류로 크게 저 두가지 입니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
