### ISSUE TITLE
replace_urls.hds 스크립트가 실행되지 않습니다.

### ISSUE THREAD

**Issue by danzang** [KurtBestor/Hitomi-Downloader#2306]
일단 최신 버전 스크립트를 다운로드 받아서 실행해 봤구요
바꿀 url대화상자까지는 나옵니다만 여기서 실행 버튼을 눌러도 대화 상자가 사라지지 않고 그대로 있습니다.
물론 url이 변경되었다는 메시지 박스도 나오지 않습니다.

**Comment by KurtBestor** [comment]
[이걸](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts#tool-scripts)로 시도해보세요.

**Comment by danzang** [comment]
잘 됩니다. 감사합니다 ^^;
