### ISSUE TITLE
읽고있다

### ISSUE THREAD

**Issue by lhj5426** [KurtBestor/Hitomi-Downloader#2307]
![image](https://user-images.githubusercontent.com/30548000/90749838-89d57c80-e306-11ea-8603-d301c0682d65.png)
 그림과 같이

동일한 네트워크 환경에서

브라우저 사용

그리고 당신이 개발하는 소프트웨어

같은 웹 사이트에서 함께 사진 다운로드

웹 사이트가 많이 다운로드되었습니다

그리고 당신의 소프트웨어는 여전히 읽고 있습니다

동일한 컴퓨터 및 동일한 네트워크 조건에서

네트워크 문제로 인해 발생할 수 없습니다.

이게 항상 읽는 이유

다운로드 주소를 추가 한 후 바로 다운로드를 시작할 수 없습니까?

소프트웨어 읽기는 무엇입니까?
![image](https://user-images.githubusercontent.com/30548000/90750138-fbadc600-e306-11ea-9687-1c6a25eff0de.png)
키보드로이 피드백 텍스트를 입력했을 때

이미 브라우저에 패키징되어 있습니다.

동안

소프트웨어 다운로드가 아직 시작되지 않았습니다 !!!!

**Comment by lhj5426** [comment]
이 웹 사이트를 지원합니까?

hitomi.la/

안좋아졌다?

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/90750807-ebe2b180-e307-11ea-9143-863f5be6cd5b.png)
다운로드를 다운로드 할 수 있습니다.

다운로드하는 데 너무 오래 걸렸습니다.

이 읽기 시간을 단축 할 수 있습니까?

**Comment by lhj5426** [comment]
저는 중국에 있는데 중국 인터넷의 특징을 알고 있습니다

하지만 네트워크를 디버깅했으며 일반 인터넷에 고속으로 액세스 할 수 있습니다.

웹 액세스 및 동일한 사진 다운로드는 문제가되지 않습니다.

내가 확신하는 것은 네트워크 문제가 아니라 동일한 주소 다운로더가 매우 느리게 읽습니다.

다운로드 속도는 빠르지 만 다운로드 전 읽기 속도가 매우 느립니다.

개발자는 다운로드하기 전에 읽기 시간을 최적화해야합니다.

**Comment by lhj5426** [comment]
![image](https://user-images.githubusercontent.com/30548000/90751588-eafe4f80-e308-11ea-8064-d05a300deac5.png)

또한 개발자의 문자를 보내주세요

여기는 중국식이 좀 안 좋네요 조금 불편 해 보여요

중국어를 만들고 싶다


수고 해주셔서 감사합니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by KurtBestor** [comment]
`옵션` - `고급 설정` - `프록시` 가 어떻게 되어있나요?
