### ISSUE TITLE
iwara.tv, ecchi.iwara.tv 기능 추가 가능할까요

### ISSUE THREAD

**Issue by thiswho3** [KurtBestor/Hitomi-Downloader#2309]
1.각 유저마다 채널이 따로 있는데 채널 주소 넣고 유저가 올린 영상 일괄 다운로드하는 것 가능할까요
사이트 자체가 영상 다운로드 기능을 제공하고 있어요.
제목에 유저명, 일자 표기가 되면 분류하기도 좋고, 
private 영상은 로그인해서 특정 조건 만족해야하니 쿠키 집어넣어서 하는 걸로 하면 편하겠네요
채널 중에서 사이트 영상이 아니고 자기 유투브 채널 영상만 올리는 사람은 그냥 다운로드에서 따로 제외시키면 좋겠네요

2.각 채널마다 video가 아니라 image 항목도 따로 있습니다.
이미지 항목도 일괄 다운로드 가능할까요

3.각 페이지마다 게시자 개인 링크나, mega link, mediafire링크를 걸어두는 사람들도 많습니다.
각 페이지 텍스트를 일괄 스크랩할 수 있는 기능은 추가 가능할까요

**Comment by KurtBestor** [comment]
1. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1882
1. 나중에 할게요.
1. 추가하지 않을 예정이에요.
