### ISSUE TITLE
네이버 웹툰 다운로드 불가 문제

### ISSUE THREAD

**Issue by JackWilliam00** [KurtBestor/Hitomi-Downloader#2313]
수고 많으십니다.
작년까지 감사한 마음으로 잘 이용중이었는데 오늘 실행해보니 네이버 웹툰을 다운로드 시도했을때 리스트는 불러오는듯하지만 다운로드가 되지 않는 문제가 있습니다. 혹시 GoodbyeDPI문제인가 싶어 켜고도 해보고 끄고도 해보았지만 동일하게 동작하지 않았습니다.

확인 부탁드립니다.

=========작업 정보=========

[랑또] 가담항설 (navertoon_670144)

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://comic.naver.com/webtoon/list.nhn?titleId=670144
dir: hitomi_downloaded_navertoon\[랑또] 가담항설 (navertoon_670144)
zip: 
type: navertoon
artist: None
url: https://comic.naver.com/webtoon/list.nhn?titleId=670144
valid: True
done: True
range: None
range_p: None
single: False
time: 1598020704.1449206 (Aug 21)
tags: []
goodbyedpi: False
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
EOT: https://comic.naver.com/webtoon/list.nhn?titleId=670144

**Comment by JackWilliam00** [comment]
관심가져주셔서 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by JackWilliam00** [comment]
수고 많으셨고 감사합니다.
정상 동작 확인했습니다.
좋은하루 되세요!
