### ISSUE TITLE
youtube video download not working

### ISSUE THREAD

**Issue by jessicachon** [KurtBestor/Hitomi-Downloader#2320]
Hello I was trying to download this video "https://www.youtube.com/watch?v=_9BwXOFCNPo&t" but it does not work even when I re downloaded hitomidownloader.  Help would be appreciated :)

**Comment by jessicachon** [comment]
I saw the #1766 but I can not read korean how do I make the cookies work for hitomi? thank you for your reply!

**Comment by KurtBestor** [comment]
Please see: `Options` - `Preferences` - `Advanced Setting` - `Cookies`

**Comment by jessicachon** [comment]
It works now but when it downloads it says "converting" and when I open it with vlc player it says "VLC could not decode the format "av01" (No description for this codec)" do you know how to get past this problem?

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
