### ISSUE TITLE
텍스트도 다운 받게 할 수 있을까요?

### ISSUE THREAD

**Issue by zjaaodRhddl** [KurtBestor/Hitomi-Downloader#2325]
예를 들면 픽시브 소설이나

트위터의 트윗 bdsmlr나 인스타의 미디어와 함께 올린 글도요 

가끔 썰이나 여러가지를 적어두신 분들이 있는데 

텍스트는 못 긁어가니까 좀 아쉽더라고요ㅠ

잘 부탁드립니다.

**Comment by KurtBestor** [comment]
소설 사이트 이외의 텍스트는 지원하지 않을 계획이에요.
