### ISSUE TITLE
히토미 다운안됨 + 매우 느림

### ISSUE THREAD

**Issue by narandcider** [KurtBestor/Hitomi-Downloader#2327]
에러 메시지가 너무 길어서 텍스트파일 첨부합니다
[error.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5124933/error.txt)

히토미 파일 전체 다 안받아지고 주황색으로 마무리됨

+

검색탭에서 검색 누르면 매우 느려지고 표지 이미지 대부분 안보임

**Comment by KurtBestor** [comment]
VPN 쓰는 게 있나요?

**Comment by narandcider** [comment]
> VPN 쓰는 게 있나요?

유니콘https만 쓰고 VPN은 안쓰고있습니다
유니콘 끄고 해도 똑같아요
