### ISSUE TITLE
카카오페이지 다운로드 질문좀 하겠습니다 ㅠ

### ISSUE THREAD

**Issue by Airmanrockman** [KurtBestor/Hitomi-Downloader#2328]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2249

여기 이슈에 나와있는 문장과 user agent를 '쿠키 추출한 브라우저의 User agent'을 콘솔에서 넣을려고 하면 자꾸 

Uncaught SyntaxError: Unexpected identifier <--이런 에러가 발생하는데 먼저 해야 하는게 있는건가요?

사용중인 브라우저는 SRWare Iron (64-Bit)을 사용중입니다.

**Comment by KurtBestor** [comment]
브라우저 말고 프로그램 콘솔에서 넣으세요

**Comment by Airmanrockman** [comment]
이런문제는 처음이라서.. 잘모르는데 

프로그램 콘솔이라는게 다운로더 콘솔 말씀하시는건가요?

그러면 ctrl+alt+c하면 콘솔창이 안뜨는데 ㅠㅠ
