### ISSUE TITLE
늘감사히 쓰고 있습니다. 기능건의 드릴게 있습니다. (중복파일 제외 검색)

### ISSUE THREAD

**Issue by parksu000** [KurtBestor/Hitomi-Downloader#2329]
지금으로도 충분히 잘 사용하고 있습니다.

이건 제 개인적인 바람뿐일 수도 있겠지만, 충분히 기능상으로 좋다고 생각되어 건의드립니다.

제목에서 언급한대로 검색기능 사용 시 

[메뉴] [옵션] 중

[옵션] 탭에서 [현재 저장하는 폴더 내의 자료들을 제외] 기능을 추가하는 것입니다.

저야 지금까지 자료들은 대부분 모아서 이제 크게 필요는 없지만, 

가끔 해당 기능이 있었으면 하는 아쉬움이 남았던 기억이 있어

이렇게 글을 남깁니다.

이상입니다.

늘 잘쓰고있습니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/91498272-70ca5e00-e8fa-11ea-871e-a8f41ad484ca.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by parksu000** [comment]
빠른 개선에 감사합니다.
아침에 보고 방금 실행해보았습니다.
일단 결과부터 말하자면 매우 만족스럽습니다.
기존에는 자료를 모으고자 했을때는 초록색 체크사항들을 스크롤로 뒤져가며 찾곤했으나, 지금은 그렇지가 않네요.
더불어 해당 검색기능을 옵션으로 사용자가 온오프를 조절가능하여, 최신 업데이트 자료를 찾는데도 어려움이 없을것 같습니다.
큰 고생감사하고 좋은 하루 되세요 😊 💕 😘

2020년 8월 28일 (금) 오전 6:48, Kurt Bestor <notifications@github.com>님이 작성:
