### ISSUE TITLE
이 사이트 추가 가능할까요? 늑대닷컴이라는 사이트입니다

### ISSUE THREAD

**Issue by Nanodoggy** [KurtBestor/Hitomi-Downloader#2330]
눈동자가 처음 나왔던 시기부터 몇년동안 잘 쓰고있는데
요새 몇몇 사이트 지원이 끊기거나 혹은 사이트가 없어져 다운을 못받는 자료들이 있더라구요..

https://wfwf106.com/
늑대 닷컴이라고 그런 자료를 좀 볼 수 있는 사이트가 있는데 접속 속도가 가끔 느려져서..
사이트 없어지기전에 자료를 내려받고 싶습니다.
추가해주시면 감사하겠습니다

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/1210
