### ISSUE TITLE
ani24 사이트가 터지면서 다른사이트 스크립트를 추가하려고하는데

### ISSUE THREAD

**Issue by sfassdwq** [KurtBestor/Hitomi-Downloader#2331]
애니24 스크립트에서 임의로 수정했더니 invaild로 실패하더군요.. 

스크립트수정하려는 사이트는 이곳입니다 https://panogas.com/

#coding: utf8
#title:  panogas 사이트 추가
#comment: https://panogas.com
#author: Kurt Bestor

import downloader
from utils import Soup, urljoin, Downloader, try_n, Session, get_print, LazyUrl, get_print
import json
import ree as re
from io import BytesIO
from fucking_encoding import clean_title
from translator import tr_
import os
import page_selector
from error_printer import print_error

class Video(object):
    def __init__(self, url, title, cw):
        self.cw = cw
        self.url = LazyUrl(url, self.get, self)
        self.title = clean_title(title, allow_dot=True)
        ext = '.mp4'#os.path.splitext(url)[1]
        self.filename = u'{}{}'.format(self.title, ext)
        
    def get(self, url):
        print_ = get_print(self.cw)
        session = self.cw.session if self.cw else None

        if 'panogas.' in url:
            html = downloader.read_html(url)
            soup = Soup(html)
            url = soup.find('video')['src']
        else:
            id = get_id(url).replace('ya_', '')
            
            html = downloader.read_html('https://fileiframe.com/panogas_video4/{}.html?player='.format(id), referer=url)
            soup = Soup(html)

            view = soup.find('div', class_='player_button')
            buttons = view.findAll('button', class_='link_button')
            print_(u'buttons: {} ({})'.format(len(buttons), self.title))

            if view.find('button', class_='link_video'):
                url = view.find('button', class_='link_video').attrs['data-link']
            elif view.find('button', class_='link_jplayer'):
                url = 'http://test.ani24image.com/ani/download.php?id={}'.format(id)
            else:
                raise Exception('No videos')
        
        return url
        

class Page(object):
    def __init__(self, url, title):
        self.url = url
        self.title = clean_title(title, allow_dot=True)

@Downloader.register
class Downloader_panogas(Downloader):
    type = 'ani24'
    URLS = [r'regex:panogas[^./]*\.(site|com|org|net|in)']
    icon = 'https://kurtbestor.github.io/res/ani24.png'
    MAX_CORE = 16
    pages = None

    def init(self):
        self.url = self.url.replace('panogas_', '')
        if self.url.isdigit():
            self.url = u'https://panogas.com/ani_list/{}.html'.format(self.url)

        if '/ani_view/' in self.url:
            html = downloader.read_html(self.url)
            soup_page = Soup(html)
            href = soup_page.find('a', class_='view_info_subject').attrs['href']
            text = get_title_page(soup_page)
            if self.customWidget.range_p is None:
                self.pages = [Page(self.url, text)]
            self.url = urljoin(self.url, href)

    @property
    def id(self):
        return get_id(self.url)

    def read(self):
        for try_ in range(4):
            session = Session()
            #session.cookies.set(name='good', value='1', path='/', domain='')
            self.customWidget.session = self.session = session
            try:
                html = downloader.read_html(self.url, session=session)
                soup = Soup(html)
                break
            except Exception as e:
                print(e)
        else:
            raise

        videos = get_videos(self.url, soup, self.pages, session, self.customWidget)

        for video in videos:
            self.urls.append(video.url)
            
        url_thumb = get_thumb(self.url, soup)
        if url_thumb:
            thumb = BytesIO()
            downloader.download(url_thumb, buffer=thumb)
            self.setIcon(thumb)

        self.title = get_title(soup)

def get_id(url):
    id = re.findall('/([0-9]+).html', url)[0]
    if 'panogas.' in url:
        id = 'ya_' + id
    return id

def get_title(soup):
    return soup.find('h1').text.strip()

def get_title_page(soup):
    return soup.find('title').text.split(u'다시보기  ')[0].strip()

def get_thumb(url, soup):
    try:
        url_thumb = soup.find('div', class_='ani_info_left_box').find('img').attrs['src']
        url_thumb =  urljoin(url, url_thumb)
    except:
        url_thumb = None
    return url_thumb

def get_pages(url, soup=None):
    if soup is None:
        html = downloader.read_html(url)
        soup = Soup(html)
        
    pages = []
    list = soup.find('div', class_='ani_video_list')
    for a in reversed(list.findAll('a')):
        href = a.attrs['href']
        href = urljoin(url, href)
        text = a.find('div', class_='subject').text.strip()
        page = Page(href, text)
        pages.append(page)

    return pages

@page_selector.register('panogas')
@try_n(4)
def f(url):
    if '/ani_view/' in url:
        #raise Exception(tr_(u'목록 주소를 입력해주세요'))
        url_old = url
        html = downloader.read_html(url)
        soup = Soup(html)
        href = soup.find('a', class_='view_info_subject').attrs['href']
        url = urljoin(url_old, href)
        print(u'redirect {} --> {}'.format(url_old, url))
    pages = get_pages(url)
    return pages

def get_videos(url, soup=None, pages=None, session=None, cw=None):
    print_ = get_print(cw)
    
    if soup is None:
        html = downloader.read_html(url, session=session)
        soup = Soup(html)

    title = get_title(soup)

    if pages is None:
        pages = get_pages(url, soup)
        pages = page_selector.filter(pages, cw)
        print_('pages: {}'.format(len(pages)))

    videos = []
    for i, page in enumerate(pages):
        video = get_video(page.url, page.title, cw)
        videos.append(video)
        s = u'{} {} - {}  ({}/{})'.format(tr_(u'읽는 중...'), title, page.title, i+1, len(pages))
        if cw is not None:
            #cw.setTitle(s)
            if not cw.alive:
                return []
        else:
            print(s)
            
    return videos
            

@try_n(4)
def get_video(url, title=None, cw=None):
    if title is None:
        html = downloader.read_html(url, session=session)
        soup = Soup(html)
        title = get_title_page(soup)
    
    video = Video(url, title, cw)
    
    return video

messageBox(u'{}: panogas'.format(tr_(u'사이트를 추가했습니다')))

**Comment by KurtBestor** [comment]
사이트마다 구조가 다르기 때문에 주소만 수정한다고 되는 게 아니에요.
