### ISSUE TITLE
Support for webtoons?

### ISSUE THREAD

**Issue by Lambik** [KurtBestor/Hitomi-Downloader#2332]
Hi,

Could you add support for webtoons.com?

Thanks!

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Lambik** [comment]
Cool, it still works, but how come it is a preview of 3 years ago and not in the main program?

**Comment by KurtBestor** [comment]
I've updated it 4 hours ago. It's updated frequently to the latest beta version.

**Comment by Lambik** [comment]
Oh cool :-)

Github is just being silly then: Technical Preview
@KurtBestor KurtBestor released this on 2 Dec 2017 · 32 commits to master since this release

**Comment by KurtBestor** [comment]
It shows the release date only. You can check the assets date by using the Github API: https://api.github.com/repos/KurtBestor/Hitomi-Downloader/releases/8743670

WEBTOON will be included in the next version.
