### ISSUE TITLE
어떤 GUI FRAMEWORK를 쓰셨는지 알 수 있을까요?

### ISSUE THREAD

**Issue by MOKKO94** [KurtBestor/Hitomi-Downloader#2333]
안녕하세요.

만들어주신 프로그램과 비슷하게
라이브러리를 관리하는 프로그램을 제작하고 싶은 대학생입니다.

히토미다운로더 수준의 GUI 기능으로 구현하고 싶은데,
어떤 GUI 프레임워크를 사용하셨는지 알 수 있을까요?

**Comment by KurtBestor** [comment]
[PyQt](https://riverbankcomputing.com/software/pyqt) 써요.

**Comment by MOKKO94** [comment]
> [PyQt](https://riverbankcomputing.com/software/pyqt) 써요.

답변 감사드립니다.
PyQt가 winform처럼 뭔가 허접해 보였는데 
이렇게 멋진 프로그램이 된다니 많이 신기하네요.ㅎㅎ
