### ISSUE TITLE
#2328 추가 질문 ㅠ

### ISSUE THREAD

**Issue by Airmanrockman** [KurtBestor/Hitomi-Downloader#2334]
이런쪽은 완전 생 초짜라... 죄송합니다 ㅠ

프로그램에 넣으라고 하셨는데 프로그램이 다운로더를 말씀하시는건가요?

그런데 다운로더에는 콘솔창이 따로 없는것 같은데.. 어디에서 넣는지 자세히 알려주시면 감사하겠습니다 ㅠ

**Comment by Yoon0618** [comment]
다운로더 창을 열고 컨트롤 + 알트 + C 를 누르면 콘솔창이 뜹니다
