### ISSUE TITLE
마리망 다운이 안됩니다

### ISSUE THREAD

**Issue by Heremon** [KurtBestor/Hitomi-Downloader#2336]
version: 3.0b (20-08-27 20:49:08 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://myreadingmanga.info/mazjojo-february-2020-reward/
dir: hitomi_downloaded_mrm\[Mazjojo] February 2020 Reward
zip: 
type: mrm
artist: None
url: https://myreadingmanga.info/mazjojo-february-2020-reward
valid: False
done: True
range: None
range_p: None
single: False
time: 1598600177.4722123 (Aug 28)
tags: []
goodbyedpi: True
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None

Fail : \\?\C:\Users\WORF\Downloads\hitomi_downloader_GUI_test\hitomi_downloaded_mrm\[Mazjojo] February 2020 Reward\1\0000.jpg
Traceback (most recent call last):
File "downloader", line 860, in download
Exception: 503

정보는 이렇게 뜨네요 ㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Heremon** [comment]
감사합니다 잘되네요!!
