### ISSUE TITLE
https://moeni.org/ 어떻게 다운로드 하는 거에요?

### ISSUE THREAD

**Issue by sopo9880** [KurtBestor/Hitomi-Downloader#2337]

**Comment by sopo9880** [comment]
moeni 주소를 복사 해서 붙여놓고 다운눌러 보았지만 안됩니다ㅠ ㅠ # #

**Comment by KurtBestor** [comment]
사이트가 죽었네요.

**Comment by sopo9880** [comment]
예? 안죽었는데요?

**Comment by KurtBestor** [comment]
지금은 살아있네요.

원래 [여기에서](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts) 스크립트 다운로드해서 프로그램에 넣으면 다운로드할 수 있었어요.

그런데 사이트 구조가 바뀌어서 작동하지 않네요.

**Comment by sopo9880** [comment]
방법이 없나요?

**Comment by KurtBestor** [comment]
보니까 일반 파일이 아니라 토렌트를 이용해서 영상 보여주던데 이건 좀 구현에 시간이 걸릴 것 같아요.

**Comment by sopo9880** [comment]
앗 감사합니당^^ 날이 점점 쌀쌀해 지는데 감기 조심하세용!
