### ISSUE TITLE
User Agent 넣는것까지는 했는데...

### ISSUE THREAD

**Issue by Airmanrockman** [KurtBestor/Hitomi-Downloader#2338]
첨부후에 목록 URL을 복사하여 붙여 다운 받아도 결재된거는 다운이 안되고 여전히 무료로 풀린것 까지만 다운이 되네요 ㅠ 

혹시몰라서 기존에 받았던 파일은 다 지우고 다시 받아도.. 기존에 무료로 풀린것만 다운이 가능하네요 ㅠ

결재된 화수만 들어가서 다운을 하려고 하니 에러문구가 뜨네요 ㅠ

일단 에러 문구 첨부하겠습니다. ㅠㅠ

Can not determine type: https://page.kakao.com / viewer?productId=55285141

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-7-6.1.7601-SP1
order: 0
group: False
input: https://page.kakao.com/viewer?productId=55285141
dir: 
zip: 
type: 
artist: None
url: https://page.kakao.com/viewer?productId=55285141
valid: False
done: True
range: None
range_p: None
single: False
time: 1598601457.6461983 (Aug 28)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://page.kakao.com/viewer?productId=55285141

**Comment by KurtBestor** [comment]
테스트 해봤는데 잘 되네요. 쿠키 제대로 넣었는지 확인해주세요.

다음과 같이 목록 주소만 지원해요: https://page.kakao.com/home?seriesId=55137641

**Comment by Airmanrockman** [comment]
쿠키를 넣는다는게 그 알려주신 UserAgent만 넣으면 되는게 아닌가요?

뭐 다른 작업을 또 해야 하는건가요?

**Comment by KurtBestor** [comment]
참고해주세요: `도움말` - `사용법 (F1)` - `쿠키 불러오기`
