### ISSUE TITLE
moeni 다운로드가 안되요.

### ISSUE THREAD

**Issue by glashear** [KurtBestor/Hitomi-Downloader#2340]
스크립트 적용 후 다운로드를 하려하니 이렇게 뜹니다.
![image](https://user-images.githubusercontent.com/39308750/91571157-3eb00f00-e981-11ea-8acd-ed84ab7f7a6a.png)

**Comment by glashear** [comment]
스크립트를 넣었는데 안된거에요.

**Comment by glashear** [comment]
![image](https://user-images.githubusercontent.com/39308750/91573946-ff35f280-e981-11ea-9709-685e50644faf.png)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2337
