### ISSUE TITLE
bestjavporn 다운로드 불가

### ISSUE THREAD

**Issue by ATGOS** [KurtBestor/Hitomi-Downloader#2341]
다운로드 했는데 하다가 지혼자 꺼지길래
전에 어떤분한테 말씀한것처럼 백신도 끄고 했습니다
그랬더니 Invalid 뜨네요
3개 다운했는데 다 떴습니다 하나만 보냈습니다
Invalid: [bestjavporn] https://bestjavporn.com / video / mdtm-562-new-after-school-beautiful-girl-sexual-healing-massage-vol-026-mitsuki-nagisa / %3E

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 1
group: False
input: https://bestjavporn.com/video/mdtm-562-new-after-school-beautiful-girl-sexual-healing-massage-vol-026-mitsuki-nagisa/%3E
dir: 
zip: 
type: bestjavporn
artist: None
url: https://bestjavporn.com/video/mdtm-562-new-after-school-beautiful-girl-sexual-healing-massage-vol-026-mitsuki-nagisa/%3E
valid: False
done: True
range: None
range_p: None
single: True
time: 1598626908.133344 (Aug 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
source: 2
source: 3
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\bestjavporn_downloader", line 32, in read
File "<decorator-gen-69>", line 2, in get_video
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "extractor\bestjavporn_downloader", line 61, in get_video
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://bestjavporn.com/video/mdtm-562-new-after-school-beautiful-girl-sexual-healing-massage-vol-026-mitsuki-nagisa/%3E

**Comment by KurtBestor** [comment]
주소가 잘못되었네요

**Comment by ATGOS** [comment]
아이고 그러네요
그런데 제대로된 주소로 백신도 끄고 했는데
로딩하다 그냥 혼자 꺼집니다

**Comment by KurtBestor** [comment]
다음 버전에서 뺄 예정이에요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2105#issuecomment-659819068
