### ISSUE TITLE
사이트 추가요청(manamoa 대체)

### ISSUE THREAD

**Issue by woghkstod** [KurtBestor/Hitomi-Downloader#2342]
해당사이트 폐쇄로 인해, 대체사이트 추가 요청드립니다.
https://wfwf107.com/cm
https://marumaru.sale/

**Comment by bhkim0115** [comment]
아래 사이트도 추가 요청드립니다.
https://newtoki73.net/page/update

**Comment by jinjins7** [comment]
참고로 https://marumaru.sale/는
manamoa랑 구조도 같아보입니다.
운영진도 동일한것으로 추정.
