### ISSUE TITLE
항상 감사히 잘 쓰고 있습니다. 개별링크별 다운로드 할 수 있게 해주실 수 없을까요?

### ISSUE THREAD

**Issue by woojien** [KurtBestor/Hitomi-Downloader#2345]
마나모아를 제외하고는 첫화부터 받아야하는데
이번에 마나모아가 터지면서 대체사이트를 찾아도 전부 첫화부터 받게 되어있더라구요
업데이트 된 신규목록만 다운로드 할수 있게 해주셨으면 감사하겟습니다.

항상 감사합니다

**Comment by jinjins7** [comment]
제목이랑 내부 폴더 제목이랑 파일들이 같으면 마나모아폴더의 만화를 그냥 해당 사이트폴더에 옮기고 다운실행하시면 최신것만 다운받아질겁니다.
파일은 같은데 폴더 이름이 좀 다르면 프로그램으로 폴더 이름 바꾸셔서 넣으시면 마찬가지로 최신것만 받아지실겁니다.
