### ISSUE TITLE
pawoo 다운로드가 작동되지 않습니다.

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#2350]
Invalid: [pawoo] https://pawoo.net / @IKZ97

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://pawoo.net/@IKZ97
dir: 
zip: 
type: pawoo
artist: None
url: https://pawoo.net/@ikz97
valid: False
done: True
range: None
range_p: None
single: False
time: 1598696342.7817924 (Aug 29)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'span'
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\pawoo_downloader", line 35, in read
File "extractor\pawoo_downloader", line 30, in name
AttributeError: 'NoneType' object has no attribute 'span'

Invalid: fail=True
EOT: https://pawoo.net/@IKZ97

로그는 이렇게 떠집니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by cocokakao** [comment]
정상 작동 됩니다 감사합니다.
