### ISSUE TITLE
유튜브 몇몇 영상이 다운로드가 안 됩니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#2354]
1.유튜브 몇몇 영상이 다운로드가 안 됩니다

2.계속 일정 %에서 노란 제목으로 바뀌고
불완전한 다운 다시 시작해도 계속 노란 제목으로 바뀝니다

3.이게 지금 테스트 버전 히토미랑
그냥 정식 버전 히토미 둘다 이러는 듯요?

![이미지 072](https://user-images.githubusercontent.com/51936970/91640937-1a753080-ea5c-11ea-9443-a527d573a7e6.jpg)

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
