### ISSUE TITLE
Hitomi에서 다운로드 한 폴더명 형식에서 [Lang] 의 변화

### ISSUE THREAD

**Issue by rlawls748** [KurtBestor/Hitomi-Downloader#2355]
Hitomi에서 다운로드를 받을 경우
폴더명 형식에 [Lang]을 넣을 경우 Korean 이나 Japanese 만 기재되었는데
이번에 Korean.html 이나 Japanese.html 처럼 html이 붙어서 나오게 되었습니다
원래대로 표시할 수 있는 방법이 없을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rlawls748** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

해결되었습니다 Korean, Japanese 로 표시됩니다
감사합니다
