### ISSUE TITLE
4K Video Downloader에 있는 기능인 브라우저에서 링크 열기가 추가되면 좋겠습니다.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#2359]
현재는 링크 주소 복사 후

브라우저 활성화

주소 붙여넣기 하여 이동 하고 있는데 기능이 있으면 좋을 것 같아서요.

이렇게 하는거 맞나 모르겠네요.

**Comment by jinjins7** [comment]
다운로드창에 있는 아이콘을 누르면 해당 링크가 바로 열립니다.

**Comment by DBdeepsleeper** [comment]
> 다운로드창에 있는 아이콘을 누르면 해당 링크가 바로 열립니다.

답변받고도 헤맸는데 이제 알았습니다. 유튜브 아이콘이 재생 버튼처럼 생겨서 더 헷갈렸네요. 고맙습니다.
