### ISSUE TITLE
대부분의 히토미파일이 다운이 안됩니다.

### ISSUE THREAD

**Issue by rkdlqrnlcksgsp** [KurtBestor/Hitomi-Downloader#2360]
[error.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5146705/error.txt)

간단하게 하나 상황을 보여 드립니다.
한두개 빼고 전부에 가깝게 한두개 혹은 무더기로 파일 누락이 되면서 0kb다운하다가 노란색으로 넘어가버립니다.
분명 히토미에서 전 파일이 있고 심지어 거기서 다운로드로 다운을 하는 경우는 문제없이 됩니다.
한 파일만 다운하는것도 되고 걍 zip파일 통채로 다운 받는것도 가능한데 히토미 다운로더만 작동이 불량합니다.
해결방법을 부탁드립니다. 안그러면 히토미에서 일일히 느릿하게 다운 받는 방법밖에 없습니다ㅜㅜ
서버 상태에 따라 하나 받는데도 십수분이 걸릴지도 모르기 때문에 절박합니다;;;

**Comment by KurtBestor** [comment]
최신 버전을 쓰거나 다음 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2235
