### ISSUE TITLE
혹시 네이버 블로그 다운로드가 안되는게 맞나요?

### ISSUE THREAD

**Issue by Yakamoz940** [KurtBestor/Hitomi-Downloader#2369]
일단 평소에 감사히 사용하고있습니다 정말로 감사합니다.

문의드리는것은 다름 아니라 네이버블로그의 다운로드의 문제에 대해서 입니다.
서로이웃이나 비공개 혹은 로그인을 요구하지않는 블로그인데도 다운로드가 되지않았습니다.
지원목록에 네이버블로그가 있는걸로 아는데 제가 혹시 잘못알았을까요?

Invalid format

version: 3.0b (20-08-30 04:13:43 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 1
group: False
input: https://blog.naver.com/jinho8895
dir: 
zip: 
type: naver
artist: None
url: https://blog.naver.com/jinho8895
valid: False
done: True
range: None
range_p: None
single: False
time: 1598806688.272071 (Aug 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
stop
Invalid: fail=False
EOT: https://blog.naver.com/jinho8895

**Comment by Yakamoz940** [comment]
블로그 전체에 다운걸어서 안되나해서 특정 카테고리만 특정지어도 뜨는 정보창은 다음과 같습니다.

Invalid format

version: 3.0b (20-08-30 04:13:43 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://blog.naver.com/PostList.nhn?blogId=jinho8895&from=postList&categoryNo=13
dir: 
zip: 
type: naver
artist: None
url: https://blog.naver.com/PostList.nhn?blogId=jinho8895&from=postList&categoryNo=13
valid: False
done: True
range: None
range_p: None
single: False
time: 1598807112.0446675 (Aug 31)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
stop
Invalid: fail=False
EOT: https://blog.naver.com/PostList.nhn?blogId=jinho8895&from=postList&categoryNo=13

**Comment by KurtBestor** [comment]
개별 포스트만 지원해요.

**Comment by Nyaanng** [comment]
블로그 태그나 전체 이미지 다운 가능한 기능을 추가해주실 의향이 있으신가요??

**Comment by KurtBestor** [comment]
@Nyaanng 아직 계획은 없어요
