### ISSUE TITLE
[해결 됨] 다른 에피소드 임에도 목록에 해당 작품이 있다면 중복처리가 되어 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#2371]
가정: 
목록 전체가 아닌 '선택'에서 일부의 에피소드를 추가하는 상황.
1. 선 작업으로 38화를 리스트에 추가.
2. 38화 다운로드 완료.
3. 후 작업으로 39화를 리스트에 추가.

오류:
 39화의 다운로드가 완료 되었음에도 해당 작품 폴더 내의 에피소드는 38화만 존재함.

해결:
38화의 다운로드를 마친 후, '완료 된 작업을 목록에서 해당 작품을 제거' (리스트에 동일한 제목이 없는 상황.)
리스트에 39화를 추가.
38화, 39화 모두 다운로드 되어 있음.

**Comment by KurtBestor** [comment]
테스트 해봤는데 재현할 수가 없네요.

**Comment by mita5549** [comment]
구 버전을 사용했을때의 문제였습니다.
여러 버전에서 작업을 하다보니 실수로 구 버전을 사용했었네요. ; 
신규 버전에서는 정상적으로 작동 합니다 : ) 
![image](https://user-images.githubusercontent.com/45882353/92119904-5b41c080-ee33-11ea-8476-eacb6453d34f.png)


![image](https://user-images.githubusercontent.com/45882353/92119763-33525d00-ee33-11ea-9006-2564526df6cd.png)
![image](https://user-images.githubusercontent.com/45882353/92119731-2897c800-ee33-11ea-9dd8-424b63861ec9.png)

위 상황에서 다시 한번 1-1 에피소드를 추가해도, 정상적으로 다운로드가 되지 않던 문제였습니다.
![image](https://user-images.githubusercontent.com/45882353/92119799-3ea58880-ee33-11ea-8792-17a4be6c8a7f.png)
![image](https://user-images.githubusercontent.com/45882353/92119871-52e98580-ee33-11ea-9e35-09eb422accd1.png)
