### ISSUE TITLE
마나모아싸이트가 타싸이트로 이전하였습니다

### ISSUE THREAD

**Issue by gbdkjd5** [KurtBestor/Hitomi-Downloader#2372]
안녕하세요 제작자님

이번에 마나모아관리자가 뉴토끼싸이트로 이전한다는 소식을 전했습니다
(https://gall.dcinside.com/board/view/?id=comic_new2&no=5279592)

 (9월 2일 기점으로 싸이트 주소변경)

https://manatoki73.net  (현재 주소)

현재 뉴토끼 싸이트는 스크립트를 적용하여야 다운로드 받을수 있습니다

혹시나 시간이 되신다면 마나모아처럼 스크립트 적용없이 바로 다운로드가 가능하도록 업데이트해주셨으면합니다

또한 뉴토끼싸이트에서 다운로드 할때 스크립트를 적용하여 다운로드해야하다보니 폴더명형식을 title로 바꿔놔도

[artist][title] 기본설정을 따라가는경우가 있습니다     예시로 이렇게 됩니다 ---- [N／A] 너를 먹어도 돼]

그리고 스크립트 적용을 해야 다운받을수있는점 때문인지 개별다운로드가 불가능하고 목록에서 통으로 다운로드해야한다는점이 있습니다

이 점 또한 업데이트해주시면 감사하겠습니다

이번에 뉴토끼 싸이트 두곳중  일본만화를 올리는곳이 https://manatoki73.net/ 로 변경되었습니다

업데이트하실때 이점 참고해주셨으면합니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

개별 다운로드는 다음 링크 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/348#issuecomment-446886631

**Comment by gbdkjd5** [comment]
잘됩니다 감사합니다

**Comment by gbdkjd5** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 개별 다운로드는 다음 링크 참고해주세요: [#348 (comment)](https://github.com/KurtBestor/Hitomi-Downloader/issues/348#issuecomment-446886631)

잘됩니다 감사합니다
