### ISSUE TITLE
사이트 추가 요청드립니다.

### ISSUE THREAD

**Issue by santamarias** [KurtBestor/Hitomi-Downloader#2373]
현재 마나모아 폐쇄상태이고, 제이마나는 화질저하 인코딩이 되어있어서 불편합니다.
뉴토끼가 가장 퀄리티가 좋은 상태이니 추가 요청 드려봅니다.

https://newtoki73.net/

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2372
