### ISSUE TITLE
32bit는 영원히 지원하지 않나요 이제 

### ISSUE THREAD

**Issue by 32bitman12345** [KurtBestor/Hitomi-Downloader#2374]
2.7버젼을 끝으로 영원히 지원하지 않나요 

개인 사정상 64비트로 업그레이드를 못 하고 있는데

64비트랑 업데이트 속도가 현저히 차이나도 되니까 

32비트 지원을 한 번이라도 해 주실 의향은 없으신가요

구버젼의 불편함이 꽤 큽니다

**Comment by thankuverymuch** [comment]
나도 물어봤더니 답변이 되게 까칠하던데, 지원 안 한다고 하니 포기하세요

**Comment by KurtBestor** [comment]
좀 오래 걸리는데 나중에 시간 나면 해 볼게요.

@thankuverymuch 님이 물어 본 건 이것 밖에 없는데 뭐가 까칠하단 건가요?: https://github.com/KurtBestor/Hitomi-Downloader/issues/1815#issuecomment-605390244

**Comment by mita5549** [comment]
32비트 환경에서 메모리 관련 문제가 있어서, 그 문제를 해결하기 위해 64 비트로 넘어온 것으로 기억합니다. ㅠㅠ
 저도 그때 노트북 구입으로 OS를 변경했던지라 기억이 나네요. ㅠㅠㅠ
 다른 환경에서도 종종 32비트가 걸림돌이 될 수도 있을 것 같은데, 이 참에 64비트로 변경 혹은 기기 추가를 검토해보시는 것도 좋을 것 같습니다. : )
