### ISSUE TITLE
네이버 다운로드 문제

### ISSUE THREAD

**Issue by 09284** [KurtBestor/Hitomi-Downloader#2375]
전부터 네이버에서만 다운로드 했다하면 화질 열화가 엄청 심하네요 다른 사이트는 멀쩡한 것 같은데 네이버만 유독 그럽니다 그리고 맞는 주소인데도 다운이 전혀 안 되는 웹툰도 있는데 특정 한 웹툰만 그런 건지 아니면 드문드문 그런 경우가 있는지 모르겠네요 확인 부탁드립니다

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
