### ISSUE TITLE
[해결 됨] 뉴토끼에서, 마나모아에서처럼 다운로드 받을 수 있으면 합니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#2377]
마루마루에 이어서, 마나모아, 애니24가 터져버렸네요.ㅠㅠ
 프로그램의 본래 목적이 아닌, 번외격의 내용으로 매번 번거롭게 만들어서 죄송합니다.
 덕분에, 제 여가와 취미가 조금 더 간결해지고 편리해지게 되었습니다.
 늘 감사합니다.
 
 이번 제안은, 뉴토끼도 마나모아처럼 업데이트 목록에서 개별로 다운받을 수 있었으면 하는 생각에 건의를 드리게 되었습니다.
 사이트 자체에 작성 된 '우클릭 방지'를 뚫거나 우회하는 방법은 여러가지가 있었기에 스스로 처리하였지만, 제이마나때와 마찬가지로, 작품의 목록에서 에피소드를 선택해야 하는 순차는 여전히 번거로움으로 느껴집니다.

현재 적용 된 '목록'의 링크 주소는 https://newtoki73.net/bbs/board.php?bo_table=comic&wr_id=249871 이고
적용되길 원하는 '개별'의 링크 주소는 https://newtoki73.net/bbs/board.php?bo_table=comic&wr_id=4900402 입니다. 

혹시 코드 수정으로 간단히 해결할 수 있다면, 이 글에 답변 부탁드립니다.

=[스크립트]에서 내려받은 '09-01 뉴토끼 스크립트' 내용=======================
#coding: utf8
#title: 뉴토끼 사이트 추가
#author: Kurt Bestor

import downloader
from utils import Soup, try_n, Downloader, urljoin, get_print, Session, clean_url, clean_title
import os
from translator import tr_
import requests
import page_selector
import utils
from time import sleep
import clf2

class Image(object):
    def __init__(self, url, page, p):
        ext = os.path.splitext(url)[1]
        if ext.lower()[1:] not in ['jpg', 'jpeg', 'bmp', 'png', 'gif', 'webm', 'webp']:
            ext = '.jpg'
        self.filename = u'{}/{:04}{}'.format(page.title, p, ext)
        self.url = url

class Page(object):
    def __init__(self, title, url):
        self.title = clean_title(title)
        self.url = url

@Downloader.register
class Downloader_newtoki(Downloader):
    type = 'newtoki'
    URLS = [r'regex:newtoki[0-9]*\.com', r'regex:newtoki[0-9]*\.net']
    icon = 'https://kurtbestor.github.io/res/brotoon.png'
    MAX_CORE = 16
    _soup = None
    _session = None
    
    def init(self):
        self.url = self.url.replace('newtoki_', '')

    @property
    def id(self):
        return self.url

    @property
    def soup(self):
        if self._soup is None:
            self._session, self._soup = get_soup(self.url)
        return self._soup

    @property
    def session(self):
        if self._soup is None:
            self._session, self._soup = get_soup(self.url)
        return self._session

    @session.setter
    def session(self, value):
        self._session = value

    @property
    def name(self):
        soup = self.soup
        return get_title(soup)

    def read(self):
        soup = self.soup
        list = soup.find('ul', class_='list-body')
        if list is None:
            return self.Invalid(tr_(u'목록 주소를 입력해주세요: {}').format(self.url))
        self.title = tr_(u'읽는 중... {}').format(self.name)

        imgs = get_imgs(self.url, self.soup, self.session, self.customWidget)
        
        for img in imgs:
            self.urls.append(img.url)
            self.filenames[img.url] = img.filename

        self.title = self.name

def get_title(soup):
    title = soup.find('meta', {'name':'subject'}).attrs['content'].strip()
    rec = soup.find('ul', class_='recent-posts')
    if rec is None:
        artist = None
    else:
        artist = rec.find('span', class_=['label', 'btn-info'])
    if artist is None:
        artist = 'N/A'
    else:
        artist = artist.text.strip()
    title = u'[{}] {}'.format(artist, title)
    return clean_title(title)

def get_soup(url):
    session = Session()
    res = clf2.solve(url, session=session)
    soup = Soup(res['html'])
    
    return session, soup

def get_pages(url, soup):
    list = soup.find('ul', class_='list-body')
    pages = []
    for item in list.findAll('div', 'wr-subject'):
        for span in item.a.findAll('span'):
            span.decompose()
        title = item.a.text.strip()
        href = item.a.attrs['href']
        href = urljoin(url, href)
        page = Page(title, href)
        pages.append(page)
    return pages[::-1]

@page_selector.register('newtoki')
def f(url):
    session, soup = get_soup(url)
    list = soup.find('ul', class_='list-body')
    if list is None:
        raise Exception(tr_(u'목록 주소를 입력해주세요'))
    pages = get_pages(url, soup)
    return pages

def get_imgs(url, soup=None, session=None, cw=None):
    print_ = get_print(cw)
    
    if soup is None or session is None:
        session, soup = get_soup(url)

    pages = get_pages(url, soup)
    pages = page_selector.filter(pages, cw)

    title = get_title(soup)
    imgs = []
    for i, page in enumerate(pages):
        imgs_ = get_imgs_page(page, url, session, cw)
        imgs += imgs_

        s = u'{} {} / {}  ({} / {})'.format(tr_(u'읽는 중...'), title, page.title, i+1, len(pages))
        print_(u'{} {}'.format(page.title, len(imgs_)))
        if cw is not None:
            if not cw.alive:
                return
            cw.setTitle(s)
        else:
            print(u'read page... {}    ({})'.format(page.url, len(imgs)))

    return imgs

@try_n(4)
def get_imgs_page(page, referer, session, cw):
    #sleep(2)
    #html = downloader.read_html(page.url, referer, session=session)
    #soup = Soup(html)

    # 2183
    res = clf2.solve(page.url, session=session)
    soup = Soup(res['html'])
    
    views = soup.findAll('div', class_='view-content')
    
    imgs = []
    for view in views:
        if view is None:
            continue
        for img in view.findAll('img'):
            img = img.attrs.get('data-original') or img.attrs.get('content')
            if not img:
                continue
            img = urljoin(page.url, img)
            if '/img/cang' in img:
                continue
            if '/img/blank.gif' in img:
                continue
            img = Image(img, page, len(imgs))
            imgs.append(img)

    if not imgs:
        raise Exception('no imgs')

    return imgs

messageBox(u'{}: newtoki'.format(tr_(u'사이트를 추가했습니다')))

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
퇴근하고 바로 테스트 하겠습니다. 샤따 내리는게 너무 기다려지네요.ㅋㅋ

**Comment by mita5549** [comment]
멈춤 현상 없이 잘 작동합니다! : )
 업데이트 감사합니다. XD
