### ISSUE TITLE
5개 이상의 목록을 올렸을 때 (응답없음) 오류가 발생합니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#2378]
![image](https://user-images.githubusercontent.com/45882353/91746973-72489e80-ebf8-11ea-8bf2-81bcaa575e01.png)

**Comment by mita5549** [comment]
![image](https://user-images.githubusercontent.com/45882353/91748056-46c6b380-ebfa-11ea-8733-48f4a1d0a0f2.png)

**Comment by mita5549** [comment]
오류 발생 조건을 찾았습니다.
목록들 그 자체를 다운로드 할 시에는 여러 작업이더라도 (응답없음) 상황이 발생하지 않습니다.
여러 목록을 한번에 입력하고 '선택 화 다운로드'를 할 경우에 (응답없음)이 발생합니다. 
 ## 상황 예제)
https://newtoki73.net/comic/165331 https://newtoki73.net/comic/276467 https://newtoki73.net/comic/5146129 https://newtoki73.net/comic/233635 를 다음 그림과 같이 한번에 입력

![image](https://user-images.githubusercontent.com/45882353/91793901-8621ee00-ec54-11ea-84ee-903c53efc8ea.png)


****
혹시나 싶어서 목록을 싹 다 넣고 돌렸더니 문제가 발생하는 원인을 찾았네요..ㅋㅋ..
수정 부탁드립니다!ㅠㅠ

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by mita5549** [comment]
![image](https://user-images.githubusercontent.com/45882353/92115054-d18ef480-ee2c-11ea-96a2-33672d5fe1ea.png)

 수정 감사합니다.  하지만 [선택 화 다운로드] 기능을 통해 여러 링크에서 낱개의 만화를 받을 때,
 (응답없음) 현상이 발생하는 것은 여전히 해결되지 않은 것 같습니다.

[재현 상황]
1. 상술한 4개의 링크(이하 ①②③④)를 한번에 입력, 아래 이미지의 선택 화 다운로드 버튼을 누릅니다.
![image](https://user-images.githubusercontent.com/45882353/92115302-2b8fba00-ee2d-11ea-9556-f01bd785800d.png)
2. ① 목록에서 하나의 에피소드를 지정. 다운로드 시작.
3. 이어서 ② 목록에서 하나의 에피소드를 지정. 다운로드 시작.
4. 이어서 ③ 목록에서 하나의 에피소드를 지정. 다운로드 시작.
5. 이어서 ④ 목록에서 하나의 에피소드를 지정. 다운로드 시작. (응답없음) 에러 발생. 

[해결...?]
다만, 여러 시도 끝에 오류가 발생하지 않는 상황은 찾을 수 있었습니다.

1. ① 목록에서 하나의 에피소드를 지정. 다운로드 시작.
      ㄴ 이 때 ②의 목록은 팝업 된 상태로 유지, ①의 작업이 완료되기 전 까지 ②는 다운로드 목록에 추가하지 않음.
2. ① 목록의 다운로드 작업이 끝난 뒤에, ②의 목록을 추가.
...... 이하 6~10개의 목록을 추가하며 상황 검증 완료.
 
 이런 방식으로 선택 화 다운로드에서도, 다운로드를 하나 하나 실행하는 경우에는 응답없음의 상황이 발생하지 않습니다.
 앞 작품이 다운로드 되지 않은 상황에서, 뒷 순서의 작품을 추가하는 경우, 즉 리스트에 2개 이상의 다운로드가 작동하는 중에는 거의 대부분 (응답없음) 오류가 발생했습니다.

 문제가 참 어렵고 복잡하게 발생하네요.ㅠㅠ


사용 버전: 
![image](https://user-images.githubusercontent.com/45882353/92116361-b1f8cb80-ee2e-11ea-8926-d7158d43d0e5.png)

사용 기기: 
![image](https://user-images.githubusercontent.com/45882353/92116406-c046e780-ee2e-11ea-8ae5-2141a0ae9213.png)

**Comment by mita5549** [comment]
하지만 위와 같은 오류는, [선택 화 다운로드]에 한정 된 오류입니다!
 이번 업데이트 된 test 버전에서 아래의 작품들을 한번에 추가하여 실행했을 때는 오류가 발생하지 않았습니다.
 다시 한번 더 테스트 해보고 댓글 달도록 하겠습니다. 감사합니다.

https://manatoki73.net/comic/5246111
https://manatoki73.net/comic/5246042
https://manatoki73.net/comic/5245997
https://manatoki73.net/comic/5245885
https://manatoki73.net/comic/5245834
https://manatoki73.net/comic/5245828
https://manatoki73.net/comic/5245716
https://manatoki73.net/comic/5244384
https://manatoki73.net/comic/5244213
https://manatoki73.net/comic/5244088

![image](https://user-images.githubusercontent.com/45882353/92117065-a78b0180-ee2f-11ea-8462-c91a77bf5a69.png)

**Comment by mita5549** [comment]
https://manatoki73.net/comic/263740 https://manatoki73.net/comic/497413 https://manatoki73.net/comic/245114 https://manatoki73.net/comic/2786291 https://manatoki73.net/comic/251283 https://manatoki73.net/comic/199596

사용 링크는 다음과 같습니다.
[선택 화 다운로드]시에서는 문제가 발생하네요.ㅠㅠ.
