### ISSUE TITLE
익헨 다운로드 제한?

### ISSUE THREAD

**Issue by neuroring** [KurtBestor/Hitomi-Downloader#2379]
[e-hentai error.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5152639/e-hentai.error.txt)
하나 예시로 들고왔습니다.

사이트 안에 직접 들어가보면 
![509](https://user-images.githubusercontent.com/39030425/91769060-9d8fb580-ec19-11ea-9b7e-2ad362448651.gif)

이런 메세지가 뜨네요.
가입해도 어차피 2배까지 밖에 되지 않는거 같고 며칠째 똑같은데 혹시 방법이 없을까요?

**Comment by whatohyou** [comment]
이거는 헨버 자체에서 24시간에 볼 수 있는 양을 정해놔서 어쩔 수가 없어요. 그냥 HV오토스크립트로 gp벌어서 아카이브zip파일을 gp로 사서 보는 것이 좋아요. 아니면 gif같은 개당 용량많은 것은 gp를 많이 먹으니 그런건 zip말고 개별로 받는게 낫겠죠.

**Comment by KurtBestor** [comment]
참고해주세요: #1407
