### ISSUE TITLE
뉴토끼 가 마나토끼로 변경이되면서 ...다운로드가 안되게되었습니다.

### ISSUE THREAD

**Issue by thestreetdj** [KurtBestor/Hitomi-Downloader#2381]
newtoki73 에서..manatoki73 으로 바뀌어서

스크립트가 지원이 안되게 되었습니다.

**Comment by staropener** [comment]
단순한 URL 변경처럼 보이는데...  스크립트열어서  URL 부분만 수정하니깐 되는거 같네여..
알아서 고처서 씁시다. 여러운스크립트 도 아닌거 같구요.

**Comment by mita5549** [comment]
다행히도 사이트 구조가 바뀌지 않았으므로, 메모장으로 열어서 'newtoki'라는 단어를 'manatoki'로 바꿔주시면 됩니다.
 위와 같은 방법으로 스크립트 수정 후 정상 작동 확인했습니다.


![image](https://user-images.githubusercontent.com/45882353/91902672-0db33f80-ecdd-11ea-84cd-b90c8a0e47bb.png)

![image](https://user-images.githubusercontent.com/45882353/91902922-6387e780-ecdd-11ea-9107-267afa0b13ca.png)

**Comment by dave4720** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

여기엔 뉴토끼 스크립트가 없는것 같은데 뭘 다운 받으면 되는지 아시나요?

**Comment by magnert** [comment]
목록이 아니라 mita5549 님처럼 작품 한개로 받는 방법은 어떻게 하나요?

**Comment by thankuverymuch** [comment]
앞으로 마나모아가 살아날일은 없으니 마나모아탭을 마나토끼로 바뀌면 좋을거 같네요
스크립트 추가가 아니라... 마나모아 유저들이 엄청 많으니까요

**Comment by whatohyou** [comment]
마나토끼는 다운로드 속도가 몹시 빠르고 좋네요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2372

**Comment by mita5549** [comment]
우측 상단의 파란 다운로드 아이콘의 우측에 보면 드롭다운 (▼) 버튼이 있을겁니다.
링크를 쓰고, 그것을 누르면, 에피소드 목록이 나옵니다.
목록에서 원하는 에피소드 앞 체크박스에 체크를 하고 다운로드를 합니다.

**Comment by mita5549** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

09-03 지금은, 개발자님의 업데이트로, 개별 링크 다운로드가 가능해졌습니다. 위 주소에서 테스트 버전을 다운로드 받으세요.
만약 링크가 의심된다면, 각 건의 게시글의 개발자님의 답변에서 링크를 확인하시고 접속 바랍니다.
