### ISSUE TITLE
다운로드 된 리스트중 일부가 뭉쳐서 보입니다.

### ISSUE THREAD

**Issue by miraclehoshi** [KurtBestor/Hitomi-Downloader#2382]
https://i.postimg.cc/Qdy1F0Vy/image.png
https://i.postimg.cc/VLNJXXyQ/image.png

스크롤을 내리거나 올릴때 렉이 걸리는데, 속도가 못따라가서 그런지 리스트가 사라져있고
찾아보면 첫번쨰 사진처럼 뭉쳐 있습니다.
창 크기를 조절하면 원래대로 돌아옵니다.

**Comment by KurtBestor** [comment]
작업 수가 많으면 가끔씩 그러던데 위젯 툴킷 버그 같아요.
