### ISSUE TITLE
무슨 파일을 수정해야 할 지 모르겠어요

### ISSUE THREAD

**Issue by als0001** [KurtBestor/Hitomi-Downloader#2383]
뉴토끼를 마나토끼로 바꾸기 위해

hitomi_downloader_GUI (구성설정)

에 들어가서 newtoki를 검색하는데 안 나오네요

exe파일은 메모장으로 열면 완전 깨져나오고요.

무슨 파일을 메모장으로 열어 수정해야 할지 궁금합니다.

**Comment by whatohyou** [comment]
메모장으로 하는게 아니라 일괄 주소변환 스크립트로 해야되는게 아닐지. 아니면 웹페이지 이미지 주소 형식이 바뀌었으면 파싱을 수정해야 되는데 그건 프로그래머가 해야죠.

**Comment by whatohyou** [comment]
https://mega.nz/file/ov4DwTSR#4lz-8szJXYWctuuQaGA5r25FmGuJAcbka5nX-HHbt8A
개발자님이 바쁘신 거 같아서 일단 제가 임시로 만든 다운로더인데요.
아주 기초적인 기능 밖에 없습니다...
1)맨 위 주소텍스트박스에 목록 주소 넣고 
2) 아래에 search버튼 눌러서 하드에 저장할 곳 지정하고
3) download manatoki 버튼 누르면 쭈욱...받아집니다.
단, 1개의 에피소드만 받으려면 1개 에피소드 주소넣고 위에 다운로드 마나토끼 위에 download버튼 누르면 됩니다.
제가 쓸려고 대충 만들었는데 디자인 등 엉망입니다...마루마루, 호두툰, 프로툰, 마나토끼 현재 지원됩니다.

**Comment by als0001** [comment]
> https://mega.nz/file/ov4DwTSR#4lz-8szJXYWctuuQaGA5r25FmGuJAcbka5nX-HHbt8A
> 개발자님이 바쁘신 거 같아서 일단 제가 임시로 만든 다운로더인데요.
> 아주 기초적인 기능 밖에 없습니다...
> 1)맨 위 주소텍스트박스에 목록 주소 넣고
> 2) 아래에 search버튼 눌러서 하드에 저장할 곳 지정하고
> 3) download manatoki 버튼 누르면 쭈욱...받아집니다.
> 단, 1개의 에피소드만 받으려면 1개 에피소드 주소넣고 위에 다운로드 마나토끼 위에 download버튼 누르면 됩니다.
> 제가 쓸려고 대충 만들었는데 디자인 등 엉망입니다...마루마루, 호두툰, 프로툰, 마나토끼 현재 지원됩니다.

감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2372
