### ISSUE TITLE
폴더명 형식 적용에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by roseark** [KurtBestor/Hitomi-Downloader#2386]
마나토끼 다운 시에 설정에서 폴더명 형식을 바꿔도 적용되지 않는것 같습니다.
폴더명 형식에 맞추어서 다운되도록 해주실수 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
