### ISSUE TITLE
마나토끼 질문드립니다

### ISSUE THREAD

**Issue by OpenMinding** [KurtBestor/Hitomi-Downloader#2387]
처음 전편을 다운로드하면 폴더로 생성되어 다운됩니다

만약 전편 다운로드 후 만화가 없데이트 된후 다시 전편을 다운로드 하면 업데이트 된 화가 덧씌워지나요? 아니면 다운로드 되어있는 화만 다시 다운로드하고 끝나나요

**Comment by rlawls748** [comment]
> 처음 전편을 다운로드하면 폴더로 생성되어 다운됩니다
> 
> 만약 전편 다운로드 후 만화가 없데이트 된후 다시 전편을 다운로드 하면 업데이트 된 화가 덧씌워지나요? 아니면 다운로드 되어있는 화만 다시 다운로드하고 끝나나요

직접 해보면 아시겠지만 받았던건 그대로고 업데이트 된 것만 다운 받습니다
