### ISSUE TITLE
마나토끼 다운로드  질문점부탁합니다

### ISSUE THREAD

**Issue by yuhjyuhj** [KurtBestor/Hitomi-Downloader#2388]
마나토끼는 어떻게 받을수있나요?
https://manatoki73.net/comic/5226362 이렇게 하면안돼나요?
어떻게해야돼는지 좀 알려주세요

**Comment by rlawls748** [comment]
> 마나토끼는 어떻게 받을수있나요?
> https://manatoki73.net/comic/5226362 이렇게 하면안돼나요?
> 어떻게해야돼는지 좀 알려주세요

도움말에 사용법이 있으니까 좀 읽어주세요
마나토끼에서 만화 클릭해서 들어간 다음
다운로더에 URL 복사해서 붙여넣기 하고 다운로드 버튼만 클릭하면 됩니다

**Comment by yuhjyuhj** [comment]
![bandicam 2020-09-03 09-39-45-585](https://user-images.githubusercontent.com/70671298/92054438-049f9c80-edc9-11ea-99dd-f22b4aadac76.jpg)

**Comment by kimwansul** [comment]
뉴토끼 스크립트를 편집으로(메모장) 열어서 newtoki라고 되어 있는 모든 부분을 manatoki로 바꾸셔야 합니다

**Comment by yuhjyuhj** [comment]
어떻게하는건지 잘 모르겠습니다?
어떻게 교체하는건지 잘 모르겠어요

**Comment by mita5549** [comment]
1. 뉴토끼 스크립트 파일을 다운로드 받습니다.
2. 다운로드 받은 스크립트 파일을 우클릭하여 메모장으로 실행합니다.
3. ctrl + f 버튼으로 newtoki라고 작성되어있는 항목을 manatoki 로 수정해줍니다.(모두 다) 
4. 다운로더를 작동시키고 스크립트를 추가하여 원하는 작품을 실행해봅니다.

여담으로 09-03의 지금 시점에서는,
 TEST 실행기의 최신 버전에서 개별 링크 다운로드가 추가되어, 스크립트를 사용하지 않아도 다운로드가 가능합니다.
