### ISSUE TITLE
히토미 파일 다운로드시 순서 뒤바뀌는 문제

### ISSUE THREAD

**Issue by Tentailsahri** [KurtBestor/Hitomi-Downloader#2389]
히토미 다운로더 히토미 설정중 갤러리정보의 파일명 형식을 숫자로 할 경우

원본 파일들이 1 2 3 4 5 6 7 8 9 10 11 12 13 14 의 형태면

1을 맨 처음으로 인식하지 않고

10을 맨 처음껄로 인식합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2357
