### ISSUE TITLE
[기능 문의] 트위치 계정 내에 클립 전체 다운로드 받기 기능에 대해

### ISSUE THREAD

**Issue by tdi2020** [KurtBestor/Hitomi-Downloader#2396]
안녕하세요 존경하는 KurtBestor 선생님!

혹시 트위치 클립을 전체 다운로드 받는 기능을 추가할 수는 없을까 하여 여쭤봅니다.
현재로서는 클립이 많은 경우 자동으로 받을 방법이 없어서 일일이 수동으로 긁어 다운로드를 하고 있었습니다.

https://github.com/R3turn-Dev/TwitchClipDumper
여기 저와 비슷한 생각을 하신 분이 계신데.... 계정명을 입력하면 자동으로 긁는 것을 만들어두셨던것 같으나
저는 설치를 어떻게 하는지 몰라서 사용은 엄두도 못내겠네요ㅠㅠ 아마도 개발 언어같은데... 
방식은... 계정에 올려진 다시보기나 하이라이트를 제외하고 클립만 전체를 긁어오나봅니다.
(폰헙 계정에 올라온 영상을 긁도록 구현해주신게 생각나서 한 번 올려봅니다!)
혹시 기능 구현이 가능할까요?

항상 이 프로그램을 만들어주신데 마음 깊이 감사드립니다. 
건강하세요!

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

다음과 같이 clips 주소를 입력해주세요: https://www.twitch.tv/faker/clips

**Comment by tdi2020** [comment]
와... 이렇게 빨리요 선생님ㄷㄷㄷㄷ
우선 4개 정도의 채널을 테스트 결과 정상적으로 다운로드 되는것을 확인했습니다!
다만 채널에 날짜별 클립개수 조회해보면 실제 클립수는 더 많지만 최대 1000개 초반 언저리를 얼추 읽어왔고 
인터넷 서치결과 '1000~1100개가 트위치에서 제공하는 최대 갯수라 더 가져올 수는 없다' 라는 글이 있는걸로 보아선 
매우 정상인것 같아요! 
정말 감사드립니다ㅠㅠㅠㅠ

**Comment by tdi2020** [comment]
+추가문의+

https://www.twitch.tv/danielaazuaje_/clips

이 계정의 경우에는 무한 대기모드+읽지못해서 주소대로 가보니

**이 기간 동안에 생성된 클립이 없습니다.
대신 이 채널의 모든 인기 클립을 확인해 보세요.**

라고 출력되고 , 대신 전체클립을 보겠냐고 버튼이 있더라구요. (트위치는 7일->30일->전체 순 클립보기가 제공)
전체클립을 선택해보면 실제로는 전체클립이 많이 검색이 되는 걸 알수 있는데요,
아마 현재 설정은 인기7일 검색을 불러오게 되어있는것 같습니다.

그래서 혹시 트위치에서 제공하는 7일/30일/전체클립을 선택해서 받는 옵션이 가능할까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
선생님 테스트결과 너무 잘됩니다! ㅠㅠ 감사합니다!!

그런데 한가지 문제가 있다면 
테스트 버전에서는 클립은 되는데 원래 되던 twitch 다시보기 다운로드가 안되는 현상이 있어서 보고드립니다!

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by tdi2020** [comment]
Invalid: [twitch] https://www.twitch.tv / videos / 737811035

version: 3.0b (20-09-08 02:16:12 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://www.twitch.tv/videos/737811035
dir: 
zip: 
type: twitch
artist: None
url: https://www.twitch.tv/videos/737811035
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1599914080.3993106 (Sep 12)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
737811035
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\twitch_downloader", line 54, in read
NotImplementedError: 737811035

Invalid: fail=True
EOT: https://www.twitch.tv/videos/737811035

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
선생님 테스트결과 다시보기 파일은 이제 잘 다운로드 됩니다!
그런데 이번엔 본래 잘 다운되던 개별 클립이 다운로드 되지 않아서 보고드립니다.

로그에 사용된 개별클립 주소 : https://clips.twitch.tv/PleasantColorfulSkirretRuleFive

로그는 아래와 같습니다!

-------------------------------

Invalid: [twitch] https://clips.twitch.tv / PleasantColorfulSkirretRuleFive

version: 3.0b (20-09-12 17:37:06 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://clips.twitch.tv/PleasantColorfulSkirretRuleFive
dir: 
zip: 
type: twitch
artist: None
url: https://clips.twitch.tv/PleasantColorfulSkirretRuleFive
valid: False
done: True
range: ~4000
range_p: None
single: True
time: 1600391548.7772996 (Sep 18)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
videos
stop
Traceback (most recent call last):
File "utils", line 1007, in start
File "utils", line 1053, in start_
File "extractor\twitch_downloader", line 56, in read
NotImplementedError: videos

Invalid: fail=True
EOT: https://clips.twitch.tv/PleasantColorfulSkirretRuleFive

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tdi2020** [comment]
확인이 늦어 죄송합니다!
선생님 너무 잘됩니다T_T 감사합니다!!
