### ISSUE TITLE
마나모아 / 마나토끼에서 원본파일 압축시 기존에 있던 파일들도 같이 압축해버립니다.

### ISSUE THREAD

**Issue by Naked189** [KurtBestor/Hitomi-Downloader#2397]
2.8b버전까지는 압축을하면 기존까지 있던 페이지는 그대로 놔두고 새로 생긴 페이지들만 생성한뒤에 압축을 하여 보는데 무리가 없었습니다.

근데 그 뒤 버전부터는 기존까지있던 기존에 덮어쓰기 방식으로 압축되던게 새로 추가가 되버리면서 같은 페이지가 두개로 늘어나게되네요.

이해가 되셨는지 모르겠는데 압축내용으로 설명하자면 2.8b로 다운을 받을시 압축파일 내용이
0001.jpg
0002.jpg
0003.jpg~

이런식으로 되있는 반면 새로운 버전에서는
0001.jpg
0001.jpg
0002.jpg
0002.jpg
0003.jpg
0003.jpg~
식으로 같은파일이 다시 같이 압축하게됩니다.

항상 잘쓰고있습니다. 감사합니다.

**Comment by mita5549** [comment]
압축 된 파일의 내부의 데이터를 검토하지 않고 다시 다운로드 하는 것 같네요.
원본을 삭제하지 않는 경우에도 해당 문제가 발생합니다. 

![image](https://user-images.githubusercontent.com/45882353/92303130-104bb880-efad-11ea-965b-c80412372c8c.png)
![image](https://user-images.githubusercontent.com/45882353/92303142-2a859680-efad-11ea-82b2-15d59a8fdbaa.png)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Naked189** [comment]
해결되었습니다. 감사합니다 ^^
