### ISSUE TITLE
예약 다운로드 등 기능 문의 드립니다.

### ISSUE THREAD

**Issue by hnprcczufw5f4zr3** [KurtBestor/Hitomi-Downloader#2398]
나중에 다운로드 해야지 하고 잊어버리고 안하는 경우가 자주 있어서요.. ㅎㅎ

켜놓으면 일정 시간마다 다운로드 한다거나 하는 기능이 있을까요?

없으면 추가해주실 수 있으신가요?

그리고 다운로드 되어있는거 제외하고 최신것만 다운로드 하는 기능도 있을까요?

아니면 최신것 몇개만 다운로드 한다던가?

제가 사용법이 미숙해 여쭤봅니다.

감사합니다.

**Comment by KurtBestor** [comment]
일정 시간마다 다운로드 하는 기능은 넣지 않을 예정이에요.

현재도 새로 추가된 것만 다운로드해요.
