### ISSUE TITLE
사라진 마나모아랑 뉴토끼 스크립트

### ISSUE THREAD

**Issue by rmadud8** [KurtBestor/Hitomi-Downloader#2401]
만화 싸이트 스크립트가 만들고 싶은데 샘플로
마나모아랑 뉴토끼 스크립트가 필요합니다

**Comment by KurtBestor** [comment]
마나모아는 죽었고, 여기 마나토끼 스크립트 있어요: https://github.com/KurtBestor/Hitomi-Downloader/blob/master/src/extractor/manatoki_downloader.py
