### ISSUE TITLE
웨이보 다운로드 이슈가 있습니다.

### ISSUE THREAD

**Issue by cocokakao** [KurtBestor/Hitomi-Downloader#2407]
Invalid: [weibo] https://weibo.com / p / 1005055880438752

version: 3.0b (20-08-30 04:13:43 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://weibo.com/p/1005055880438752
dir: 
zip: 
type: weibo
artist: None
url: https://weibo.com/p/1005055880438752
valid: False
done: True
range: ~200000
range_p: None
single: False
time: 1599299804.8779218 (Sep 5)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
not f
clf Timeout
stop
Traceback (most recent call last):
File "utils", line 975, in start
File "utils", line 1021, in start_
File "extractor\weibo_downloader", line 47, in read
File "<decorator-gen-54>", line 2, in get_id
File "constants", line 817, in wrapper
File "constants", line 788, in wrapper
File "extractor\weibo_downloader", line 81, in get_id
File "clf2", line 71, in solve
Exception: clf Timeout

Invalid: fail=True
EOT: https://weibo.com/p/1005055880438752

쿠키를 넣어도 다운로드가 막히는 상황인데 제가 계정이 하나라서 다른 계정은 어떤지 검증은 못해봤습니다. 확인 부탁드립니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/92328847-8bd96280-f09e-11ea-8d27-5fac53807e1e.png)

테스트 해봤는데 재현할 수가 없네요.

**Comment by hellozhoco** [comment]
저랑 증상이 똑같네요... 계정벤인건가..ㅠ_ㅠ

**Comment by cocokakao** [comment]
> 저랑 증상이 똑같네요... 계정벤인건가..ㅠ_ㅠ

결국 다른 프로그램 쓰고 있습니다.

**Comment by hellozhoco** [comment]
> > 저랑 증상이 똑같네요... 계정벤인건가..ㅠ_ㅠ
> 
> 결국 다른 프로그램 쓰고 있습니다.
> https://chrome.google.com/webstore/detail/downalbum/cgjnhhjpfcdhbhlcmmjppicjmgfkppok

2번쨰 계정으로도 안되네요... 추천해주신걸로 해봐야게써영 ㅠㅠ

**Comment by hellozhoco** [comment]
> ![image](https://user-images.githubusercontent.com/14768120/92328847-8bd96280-f09e-11ea-8d27-5fac53807e1e.png)
> 
> 테스트 해봤는데 재현할 수가 없네요.

개발자분은 잘되시는데 왜 안될까요 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by cocokakao** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

정상작동 확인되었습니다. 신경써주셔서 정말 감사드립니다.

**Comment by hellozhoco** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

전왜 다운받기 누르면 그냥 강종이 되버릴까요...뭐가 문제지

**Comment by hellozhoco** [comment]
> > 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 테스크문의주신걸로 해봣는데
전왜 다운받기 누르면 그냥 멈췃다가 강종이 되버릴까요...뭐가 문제지 윗분 되시는거보면 개인적인 문제같은데...
별의별짓을 2시간동안해보았지만 별수없네용 확인된건 웨이보 말곤 다른사이트는 안멈추고 잘받아지네요...

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hellozhoco** [comment]
> 이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

깔끔하게 잘됩니다...항상 감사드립니다 (_ _) 꾸벅
