### ISSUE TITLE
다운로드 걸어놓으면 마나토끼측에서 밴때리는거같은데

### ISSUE THREAD

**Issue by qoqoqi** [KurtBestor/Hitomi-Downloader#2408]
어떻게 해결방법이 없나요?

**Comment by woghkstod** [comment]
403 Forbidden 뜨는군요.. 칼같이 밴해버리네요.

**Comment by mita5549** [comment]
예전에 다른 사이트 디도스 공격할 때 누군가 글을 썼었는데, 보통 쿨타임이 짧게는 4시간, 길면 12시간에서 하루 정도 되는거로 알고 있습니다. 서버 구축할때 보안 측에서 설정한 값이라 제각각 달라서 정확히 얼마라고는 답변 드리기 어렵네요;
 다른 사이트 이용해주시거나 숙면 바랍니다.ㅠㅠㅠㅠㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
