### ISSUE TITLE
추가된 사이트들은 어떻게 이용하나요?

### ISSUE THREAD

**Issue by weq123asd** [KurtBestor/Hitomi-Downloader#2409]
안녕하세요 마나모아 이후로 다른사이트를 처음 다운로드해보는 사람입니다 
https://wfwf108.com/
늑대닷컴이라는 사이트는 이미 예전에 추가가 되어있다고 표시되어있는대
https://wfwf108.com/list?toon=47
가정부 길들이기라는 만화를 다운로드 받고싶으면 어떻게 해야하나요?
그냥 주소 복사붙이기로는 다운로드가 안되서..(마나모아처럼)

**Comment by KurtBestor** [comment]
아직 추가되지 않은 사이트예요.
