### ISSUE TITLE
dpi 우회 기능이 정상적으로 작동하지 않거나, 특정 사이트에서 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#2413]
다운로더의 설정 체크도 확인했고, goodbyedpi-0.1.6 를 따로 사용해봤는데도 ip 차단이 풀리지 않는 것 같습니다.
 크롬에서도 열리지 않아 혹시나 싶어서 마루마루 시절에 쓰던 확장 프로그램을 사용 해 봤는데, 크롬에서 해당 페이지가 정상적으로 진입 되는 것을 확인했습니다. 
 혹시 크롬에 해당 vpn 우회 확장프로그램을 추가하면, 다운로더에서도 사용 가능하게 하거나, 새로 vpn에 관련 된 스크립트를 추가해 주실 수 있으신가요? 

https://chrome.google.com/webstore/detail/touch-vpn-secure-and-unli/bihmplhobchoageeokmgbdihknkjbknd

**Comment by KurtBestor** [comment]
DPI 우회만 할 뿐이지 IP 가 바뀌지는 않아요.

외부 데스크탑 VPN 을 쓰거나 설정에서 프록시를 설정하세요.

**Comment by mita5549** [comment]
ip 변조를 통해 해결했습니다.
답변 감사합니다!
