### ISSUE TITLE
마나토끼에서 저장 파일명 형식이 적용되지 않습니다

### ISSUE THREAD

**Issue by luku756** [KurtBestor/Hitomi-Downloader#2415]
옵션-설정에서 폴더명 형식을 바꾸어도 디폴트 형식대로만 저장되네요.
[artist] title (id) 로만 저장됩니다.

항상 감사합니다.

**Comment by lducjswo** [comment]
구버젼에 마나토끼 스크립트 넣어서 쓰면 되더라구요
https://github.com/KurtBestor/Hitomi-Downloader/blob/master/src/extractor/manatoki_downloader.py

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2386
