### ISSUE TITLE
페이스북 문제가 발생 했습니다

### ISSUE THREAD

**Issue by dkfle222** [KurtBestor/Hitomi-Downloader#2417]
Invalid: [facebook] https://www.facebook.com / sofia.dellecave

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://www.facebook.com/sofia.dellecave
dir: 
zip: 
type: facebook
artist: None
url: https://www.facebook.com/sofia.dellecave
valid: False
done: True
range: None
range_p: None
single: False
time: 1599367404.0064235 (Sep 6)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no name
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\facebook_downloader", line 109, in read
File "extractor\facebook_downloader", line 96, in name
File "extractor\facebook_downloader", line 130, in get_title
Exception: no name

Invalid: fail=True
EOT: https://www.facebook.com/sofia.dellecave

**Comment by snn001** [comment]
안녕하세요, 페이스북 관련 글 검색하여 Duplicate of #2417 타고 오게 되었습니다.


Invalid: [facebook] https://www.facebook.com/ChauNgocBichNguyen93/photos

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 390d110516e341c28a0f1c9bda8124db
input: https://www.facebook.com/ChauNgocBichNguyen93/photos
type: facebook
single: False
url: https://www.facebook.com/ChauNgocBichNguyen93/photos
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1641991817.8793275 (1월 12일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
Châu Ngọc Bích Nguyễn (facebook_ChauNgocBichNguyen93)
No photo div
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\facebook_downloader", line 122, in read
 File "extractor\facebook_downloader", line 169, in get_imgs
Exception: No photo div

Invalid: fail=True
EOT: https://www.facebook.com/ChauNgocBichNguyen93/photos  (5.6s)


특정 계정 다운이 안되는 경우가 있습니다...
(차이점은 페북 네임이 영어가 아닌 다른 국가 언어인 경우 다운 불가능한 것? 같기도 합니다)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by snn001** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

안녕하세요, 확인이 늦었습니다.

다운로드는 진행이 되나 사진첩 전체 다운로드가 아닌 일부 사진첩의 이미지만 다운이 되며, 사진의 원본 크기가 아닌 사진첩 상에서 사진 클릭 전에 보이는 팝업 이미지 (206x206, 작은 ​사이즈)로만 다운로드가 되는 것을 확인했습니다.

페이스북 사진 다운로드 작업이 많이 까다롭다는 이야기를 들었는데 번거롭게 해드려 죄송합니다.

나중에 시간이 되실 때 한번 더 살펴봐 주시면 감사하겠습니다.
