### ISSUE TITLE
트위터 미디어를 다운받을때 다운받는 범위가 오락가락 합니다

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#2421]
![animatekawanisi](https://user-images.githubusercontent.com/41049446/92327774-1322d800-f097-11ea-94e9-9eb123d0061b.PNG)
![animatekawanisi 다시한거](https://user-images.githubusercontent.com/41049446/92327776-14540500-f097-11ea-987f-d44374768b9f.PNG)

트위터 주소는 https://twitter.com/animatekawanisi 입니다.
[animatekawanisi 다시한거.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5179781/animatekawanisi.txt)
[animatekawanisi.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5179782/animatekawanisi.txt)

맨처음에 다운받을때는 만장 이하였는데 다시 다운받더니 2만장 이상이 되었습니다.

다운받아지는 기간이 오락가락한거같습니다.

**Comment by jaejunghan** [comment]
위하고는 다른 케이스입니다만.

![animateoakyama1](https://user-images.githubusercontent.com/41049446/92328139-a0ffc280-f099-11ea-8fc7-f18db8a5431d.PNG)
![animateokayama](https://user-images.githubusercontent.com/41049446/92328145-a8bf6700-f099-11ea-8c79-a0285c949ea7.PNG)
트위터 주소는https://twitter.com/animateokayama 입니다.

![animateoakyama](https://user-images.githubusercontent.com/41049446/92328128-90e7e300-f099-11ea-8a9d-01df0541d5dd.PNG)
https://twitter.com/search?q=(from%3Aanimateokayama)%20until%3A2017-07-26&src=typed_query&f=live

트위터다운로드를 몇번 반복한결과 2만장까지만 다운이됩니다. 그래서 다운받은 사진들중 가장 처음기간이 2017년 7월 27일 이길레, 그전에 생성된 미디어는 없나 검색을 하니 있었습니다. 근데 다운이  안돼있네요.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2145#issuecomment-664502069 때문에 생긴 문제예요.
