### ISSUE TITLE
유튜브 영상 다운받으면 소리만 나오는 현상

### ISSUE THREAD

**Issue by sasamarugun** [KurtBestor/Hitomi-Downloader#2424]
어떤 영상들은 잘되고 어떤 영상들은 소리만 나오는 현상이 있습니다

제가 잘못쓰고 있는건지도 모르겠지만ㅜㅜ;

안되는 영상 예시로

https://www.youtube.com/watch?v=uCQ7dCf8PyA 

동영상 플레이어는 다음팟을 쓰고 있습니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1701#issuecomment-590234822
