### ISSUE TITLE
마나토끼 다운 관련

### ISSUE THREAD

**Issue by RuPeo** [KurtBestor/Hitomi-Downloader#2426]
따른분들도 모르겠지만 마나토끼에서 파일을 다운하려고 하니까
몇분뒤에 403 Forbidden 이라고 뜨면서 사이트가 막히게 되는데
따른분들은 안뜨나요?

마나토끼쪽에서 질문하니까 
'해당 아이피는 자료를 수집해가는 크롤링 IP로 확인되어 차단되었습니다.'
라고 하면서 이 프로그램이 크롤링이라는 말인가요?

혹시 따른분들은 어떤지 알려주세요

**Comment by mita5549** [comment]
403 포비든 에러는 사이트에서 특정 ip를 차단한 경우에 발생합니다. 
아예 운영진 쪽에서 크롤링으로 체크했다면 잘 안풀어주지 싶은데..... 다른 ip를 사용하시면 사이트 접근은 가능합니다.
