### ISSUE TITLE
폴더명 형식이 변경되지 않습니다

### ISSUE THREAD

**Issue by lducjswo** [KurtBestor/Hitomi-Downloader#2428]
폴더 정렬을 이름순으로 해놔서 작품명을 기준으로 ㄱㄴㄷ순 정리를 하는데(작품명[작가])
지금 [작가]작품명순으로 폴더명형식에서 바뀌지 않아 일일이 수정중입니다 ㅠㅠ
어느부분을 고쳐야 할까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2386
