### ISSUE TITLE
뉴토끼 웹툰이 다운로드가 되지 않습니다.

### ISSUE THREAD

**Issue by yourkissme** [KurtBestor/Hitomi-Downloader#2429]
뉴토끼는 최근 https://newtoki102.com (웹툰) 과 https://manatoki102.net (일본만화) 로 도메인이 2개로 나뉘었습니다.
최근 올려주신 테스트 버전을 사용시 마나토끼 즉 일본만화의 경우 다운로드가 가능하지만 뉴토끼, 웹툰은 다운로드가 불가능합니다. 수정 또는 추가 부탁드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by yourkissme** [comment]
감사합니다. 적용 됩니다!!
