### ISSUE TITLE
https://imgur.com is not working anymore

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader#2430]
As the title suggest, we are not able to download images from https://imgur.com anymore, it was working fine before. I'm using the latest version of Hitomi Downloader v3.0b.

Hopefully you are able to fix this issue, thanks for all your hard work.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by xZabuzax** [comment]
> Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Hello, that version fixed the issue, I'm able to download from Imgur.com again.

Thanks!
