### ISSUE TITLE
제이마나 다운시 하단 이미지 반복 다운로드 문제

### ISSUE THREAD

**Issue by clue1234** [KurtBestor/Hitomi-Downloader#2431]
![image](https://user-images.githubusercontent.com/70927983/92426645-73179c80-f1c5-11ea-804b-f7a2f48369bb.png)

어제까지 아무문제없다가, 금일부터 갑자기 이미지와 같이 하단 이미지가 반복하여 중간중간 다운되는 현상이 발생하고 있습니다.
확인 부탁드려요~

**Comment by cancerogenic** [comment]
하도 다운받아대니까 제이마나쪽에서 막는답시고 저렇게 해놓은것같습니다. 모르고있다가 몇십개 다운받고 하나 열어보니 저딴식으로 되있어서 되게 빡치네요..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by clue1234** [comment]
앗 정상적으로 다운됩니다. 바쁘신 와중에도 감사합니다!

**Comment by sim01301** [comment]
죄송한데  해결하셨나요? 제이마나 다운받을시  저 제이마나 이미지들 안뜨시나요?

저 테스트 부탁드려요https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
이거 사용법이 어떻게 되나요?  파일세개 받아서 폴더에 놓고 다풀어둔다음
다운로더 켰는데 반응이 없어서요..
