### ISSUE TITLE
제목이 짤리는 경우, 같은 링크로 변조되어 다운로드가 중복 처리됩니다.

### ISSUE THREAD

**Issue by mita5549** [KurtBestor/Hitomi-Downloader#2432]
'마나토끼 다운로드시 버그 두개 제보합니다. #2422' 
https://github.com/KurtBestor/Hitomi-Downloader/issues/2422

맨 마지막 댓글에 자세한 내용을 작성 해 두었습니다. 

![image](https://user-images.githubusercontent.com/45882353/92461283-112a5780-f204-11ea-90ef-6e4dd56c27a3.png)

 제목이 너무 긴 경우에는 이런식으로 잘리는 것 같습니다.
 제목의 내용 중 후반부에 속하는 '에피소드의 넘버링'이 짤리는 경우에는 서로 다른 두 링크가 하나의 중복된 링크로 변경 처리되어서 차후 넘버가 다운로드 되지 않는 경우가 있습니다.
 
1. 두 작품을 동시에 다운로드하는 경우.
 1-1 서로 다른 두 링크를, 같은 링크로 간주하여 앞서 다운로드 한 링크를 따라감.

2. 앞 작품을 어딘가로 이동, 삭제, 이름 변경 등을 통해 먼저 다운로드 된 작품을 변조하는 경우.
 2-1 다운로드 목록에서도 해당 작품의 섬네일이 변경되지 않음. 
 2-2 차후 다운로드 되는 작품의 다운로드가 정상적으로 진행 됨.

**사용 링크**
https://manatoki102.net/comic/5305984?spage=1
https://manatoki102.net/comic/5310112?spage=1

![image](https://user-images.githubusercontent.com/45882353/92459329-8183a980-f201-11ea-8000-73691180cb44.png)
![image](https://user-images.githubusercontent.com/45882353/92459353-88122100-f201-11ea-97e9-431923fa9d3d.png)
![image](https://user-images.githubusercontent.com/45882353/92459357-8ba5a800-f201-11ea-9225-fe8021629e45.png)

**결과물:**
아래와 같이 서로 다른 두 링크가 하나의 링크(맨 앞의 작업)로 통일됩니다.
![image](https://user-images.githubusercontent.com/45882353/92460742-471b0c00-f203-11ea-92f2-f3afa45c02a5.png)

다만, 아래와 같이 먼저 다운로드 된 작품의 이름을 '2'로 변경하면
![image](https://user-images.githubusercontent.com/45882353/92460822-631ead80-f203-11ea-946b-415a93bc4330.png)

다음 에피소드의 다운로드 작업은 정상적으로 진행됩니다. 
![image](https://user-images.githubusercontent.com/45882353/92461004-a6791c00-f203-11ea-9072-be2d010d34c3.png)

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2422
