### ISSUE TITLE
마나토끼 '존재하지 않는 게시판입니다.' + 다른 화수가 다운로드 되는 현상

### ISSUE THREAD

**Issue by fujl1** [KurtBestor/Hitomi-Downloader#2434]
https://manatoki102.net/comic/5377081?spage=1로 148화를 직접 다운 받으려니 136화가 다운 되고

https://manatoki102.net/bbs//board.php?bo_table=comic&wr_id=113325인 목록주소로 148화를 [선택 화 다운로드]하면 
[존재하지 않는 게시판입니다]라는 에러가 뜹니다.

아래 정보는 [선택 화 다운로드]로 148화를 선택 했을 경우입니다.

---------------------

Invalid: [manatoki] https://manatoki102.net / bbs / / board.php

version: 3.0b (20-09-03 21:21:06 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki102.net/bbs//board.php
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki102.net/
valid: False
done: True
range: None
range_p: [157]
single: False
time: 1599651935.8635557 (Sep 9)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
File "utils", line 1007, in start
File "utils", line 1053, in start_
File "extractor\manatoki_downloader", line 73, in read
File "extractor\manatoki_downloader", line 70, in name
File "extractor\manatoki_downloader", line 88, in get_title
File "extractor\manatoki_downloader", line 96, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki102.net/bbs//board.php

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fujl1** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다 잘 되네요!

**Comment by cambioformas** [comment]
> > 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 감사합니다 잘 되네요!

실행이 안됩니다 ㅠㅠ 아래버전들은 정상적으로 실행되는데 이 버전만 실행이 안되네요

**Comment by PrivateI** [comment]
마나토끼 안되는거같아서 찾아보니 여기 테스트버전에서는 잘되네요
근데 10일전껀데 정식버전에는 언제반영되나요?
