### ISSUE TITLE
크롬 북마크에서 히토미 클립보드 자동복사가 안됩니다

### ISSUE THREAD

**Issue by dr1439** [KurtBestor/Hitomi-Downloader#2440]
크롬 북마크관리자에서 히토미 주소를 복사하면 원래 바로 클립보드에서 자동추가가 되어야 하는데 업데이트 이후에 이것을 하니까 반응이 없습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by dr1439** [comment]
테스트버전으로 해결됐습니다
