### ISSUE TITLE
다운로더가 가끔 작동하지 않습니다.

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#2442]
일단 예시의 사이트주소입니다 

https://twitter.com/mdf_an

해당 트위터를 6월 15일날 다운받고 어제 다시 다운받으려했습니다.

근데 트위터가 다운받는 모션만 취하고 다운이 안된상태였습니다, 나중에 확인하고나서 다시 돌리니 다운이 받아지긴하는데, 픽시브 또한 가끔 이런 경우가 있어서, 문의드립니다
[mdf_an.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5207187/mdf_an.txt)

다운받아야할 다른 링크들하고 같이 돌리면서, 다운로딩 완료후 제거하는옵션을 선택했는데, 작업이 완료되었음에도 제거안된 작업들의 공통점이 저렇더라고요. 가장 최근에 다운받은 상태로만 뜨고, 그이후에 올려진 사진이나 데이터들을 다운받지 않습니다.

**Comment by KurtBestor** [comment]
여기서 해결됐을거예요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2303
