### ISSUE TITLE
툰코.   Script 사용 + 32 Bit 버전

### ISSUE THREAD

**Issue by AidionTkPro** [KurtBestor/Hitomi-Downloader#2443]
툰코를 다운 받으려 합니다.

32bit 가능한 마지막 버전인 hitomi_downloader_GUI v2.7h 을 사용 중입니다.

https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
사이트 스크립트를 다운 받아 적용하는데 .. 
[ 올바르지 않는 스크립트 형식입니다. ]라는 오류가 납니다.
[자세히 보기
Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 4010, in exec_script
  File "dynamic_module_11", line 10, in <module>
ImportError: No module named page_selector
]

이슈 #1892를 참고하여.
주소를 변경하였는데도 오류가 납니다.

다른 사이트 스크립트는 적용이 됩니다. (예. Hikomi.la | https://hikomi.la )

어떻게 해야하는 지 아시는 분 알려주시길 바랍니다.

참고.
툰코 주소가 바뀌면서 다운로드가 안됩니다. #1892
https://github.com/KurtBestor/Hitomi-Downloader/issues/1892
https://github.com/KurtBestor/Hitomi-Downloader-issues/wiki/Scripts
에서 'Replace URLs' 스크립트 다운 받으신 뒤에 적용하셔서 주소 변경하시면 됩니다.

**Comment by KurtBestor** [comment]
다음 줄들 모두 지우면 작동하긴 할 거예요:
```
import page_selector
```
```
pages = page_selector.filter(pages, cw)
```
```
@page_selector.register('toonkor')
```

**Comment by erebuseyny** [comment]
> 줄들 모두 지우면 작동하긴 할 거예

관심 가져주셔서 감사합니다. 
윈도우 지우고, 새로 64bit으로 설치했습니다.
거의 대부분의 옛날 노트북도 64bit 지원더군요.
같은 문제 있으신 분들 미리포기 마시고, 확인 후 설치 권장합니다.
