### ISSUE TITLE
테이스터

### ISSUE THREAD

**Issue by dimolto312** [KurtBestor/Hitomi-Downloader#2444]
![테이스터](https://user-images.githubusercontent.com/65066146/92933990-e816fa80-f481-11ea-8e72-3e6a0503428e.PNG)

저장 실패가 뜨는데 어떻게 해야하나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2287

**Comment by dimolto312** [comment]
네 감사합니다
