### ISSUE TITLE
마나토끼 폴더명 [artist] 제거..

### ISSUE THREAD

**Issue by ciotte** [KurtBestor/Hitomi-Downloader#2446]
마나토끼 개별 다운로드 되는 테스트 버전 사용중입니다

현재 마나모아 다운로드시에 title 을 입력해놓으면
[artist] title 이렇게 되는것 같아요

스크립트를 받고 자체 수정해서 적용해봤을때 

title = '[{}] {}'.format(artist, title)

title = '{}'.format(title)

다음과 같이 수정해서 사용은 되는데

이러면 전체 다운로드만 가능하고 각각의 다운로드는 안되는 스크립트 같아요

다음 테스트 버전 파일에 title 과 artist 분리해 주시면 좋겠어요
감사합니다!!

**Comment by KurtBestor** [comment]
참고해주세요: #2386

**Comment by woghkstod** [comment]
> 참고해주세요: #2386

혹시 기존에 [artist][title] 로 받았던 작업을 반복할 경우, 새로 폴더가 형성되고 처음부터 작업을 하게 되는 게 맞나요?
전에 별 생각 없이 [title] 로 해놓고 업데이트 작업을 걸었는데, 다 [artist][title] 로 저장되어 있더라구요.
테스트버전 받아보니 잘 되긴 하는데, 기존 폴더는 체크 안하고 새로 받는 것 같아서요...

**Comment by KurtBestor** [comment]
네

**Comment by woghkstod** [comment]
> 네

아하... 혹시 제가 뭔가 잘못 건드렸나 했네요...
폴더명 일괄로 바꾸고 다시 테스트하니 제대로 읽어들입니다. 감사합니다~!
