### ISSUE TITLE
best javporn인데 다운이 안되서요 요것좀 테스트 부탁드리겠습니다

### ISSUE THREAD

**Issue by tiniti1109** [KurtBestor/Hitomi-Downloader#2452]
Invalid: [bestjavporn] https://bestjavporn.com / video / 200gana-930-bar-nampa-01 / 

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://bestjavporn.com/video/200gana-930-bar-nampa-01/
dir: 
zip: 
type: bestjavporn
artist: None
url: https://bestjavporn.com/video/200gana-930-bar-nampa-01/
valid: False
done: True
range: None
range_p: None
single: True
time: 1599964833.8685274 (Sep 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
no player
source: 2
no player
source: 3
no player
no urls
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\bestjavporn_downloader", line 32, in read
File "<decorator-gen-69>", line 2, in get_video
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "extractor\bestjavporn_downloader", line 115, in get_video
Exception: no urls

Invalid: fail=True
EOT: https://bestjavporn.com/video/200gana-930-bar-nampa-01/
수고하세요!!

**Comment by KurtBestor** [comment]
다음 버전에서 뺄 예정이에요. 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2105#issuecomment-659819068

**Comment by tiniti1109** [comment]
사이트 빼실정도면 정말 어렵게 해놨나보네요. 그렇군요. 네 알겠습니다. 감사합니다. 수고하세요.!!!
