### ISSUE TITLE
작가블랙리스트 건의

### ISSUE THREAD

**Issue by ONDR** [KurtBestor/Hitomi-Downloader#2453]
안녕하세요 제작자님 덕분에 프로그램을 잘 사용하고 있습니다. 항상 감사드립니다.

작가 전체 불러오기 기능을 사용할때 작가 블랙리스트를 추가해서 걸러 주는 기능을 만들어 주셨으면 해서 글을 써봤습니다.

다름이 아니라, 등록되있는 작가 전체 불러오기 기능을 애용하고 있습니다.  제가 보는 작가들 추가된것까지 한번에 등록되어 전작가들의 신규작품 검색에 유용하게 이용하고 있습니다.

문제가, 더이상 보고싶지 않거나, 잘못받아서 더 이상 보고 싶지 않거나, 여러 작가들이 쓴 작품의 다른 작가들 까지 넘어오면서,

불필요한 작가들이 섞여 들어옵니다. 

직접 추적해서 지워 반전도는 지우고 작품을 이동시키기도 해봤지만, 

여러 작가들이 등록된 작품같은경우 맨앞의 작가이름만 나오고 etc로 되있어서 추적이 어렵습니다. 

히토미 검색에서 작가 검색으로 찾아 지우려고해도 이미 지워진 작품이라 찾을 수 없는 경우 아에 추적이 안됩니다. 삭제된 검색에도 안나옵니다.

작가 전체 불러오기 기능에 작가 블랙리스트 등록을 추가해주시면 더 유용하게 쓸 수 있을 것 같아 건의드립니다.

**Comment by KurtBestor** [comment]
작가가 3명 넘는 작품은 `모든 작가 불러오기` 에 포함되지 않아요.

작가 A, B, C 를 검색하는데 작가 D 를 제외하고 싶으면 `(A + B + C), -D` 와 같이 검색하세요.
