### ISSUE TITLE
앞부분만 다운되고 그 이후엔 다운이 되지 않습니다 ㅜㅜ

### ISSUE THREAD

**Issue by flolucy** [KurtBestor/Hitomi-Downloader#2455]
히토미/히요비 다운로드 시 앞부분인 8~9페이지 까지만 다운이 되고 다운이 멈춰버립니다. 해결방법이 없을까요? ㅜㅜ

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.

**Comment by mac22222** [comment]
> 히토미/히요비 다운로드 시 앞부분인 8~9페이지 까지만 다운이 되고 다운이 멈춰버립니다. 해결방법이 없을까요? ㅜㅜ

저도요
내용이 길어서 파일로 옮립니다 ㅠ

[test.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5254509/test.txt)

**Comment by KurtBestor** [comment]
@mac22222 히토미 / 히요비가 아니네요. 다른 이슈에 올려주세요. 확인해보니 일시적인 서버 오류 같네요.

**Comment by mac22222** [comment]
> @mac22222 히토미 / 히요비가 아니네요. 다른 이슈에 올려주세요. 확인해보니 일시적인 서버 오류 같네요.

아! 감사합니다
