### ISSUE TITLE
user agent 실패

### ISSUE THREAD

**Issue by floygrasm** [KurtBestor/Hitomi-Downloader#2456]
f1 에서 나와있는 설명대로, cookie.txt 를 이용해서 카카오페이지 쿠키를 프로그램에 load 후, user agent 사이트에서 확인후, 프로그램 콘솔에서 추가

from extractor import kakaopage_downloader;kakaopage_downloader.UA='<Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36>' 

그 후 실험삼아 현재 소장중인 웹소설 1화를 선택후 다운로드를 시도하였으나 실패했습니다.

Invalid: [kakaopage] https://page.kakao.com / home?seriesId=54890179

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: https://page.kakao.com/home?seriesId=54890179
dir: 
zip: 
type: kakaopage
artist: None
url: https://page.kakao.com/home?seriesId=54890179
valid: False
done: True
range: None
range_p: [30]
single: False
time: 1600019048.6091955 (Sep 13)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
옥탑방 소드마스터 31화 0
no imgs
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\kakaopage_downloader", line 49, in read
File "extractor\kakaopage_downloader", line 163, in get_info
Exception: no imgs

Invalid: fail=True
EOT: https://page.kakao.com/home?seriesId=54890179

**Comment by KurtBestor** [comment]
User Agent 는 `<`, `>` 빼고 다음과 같이 입력해주세요:
```
from extractor import kakaopage_downloader;kakaopage_downloader.UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'
```

**Comment by floygrasm** [comment]
감사합니다
