### ISSUE TITLE
the project is full open source ?

### ISSUE THREAD

**Issue by CKS-ROC** [KurtBestor/Hitomi-Downloader#2458]
Dear Sir

i want try run  this project  --- python file 

but when i import project 

i lost 

utils  cut_pair, LazyUrl, Downloader, get_print, get_max_range, try_n, clean_title  m3u8_tools  ffmpeg... 

those library  i can not get !!

where i can find ?

THX

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2226
