### ISSUE TITLE
BILIBILI 고화질 동영상 다운 기능

### ISSUE THREAD

**Issue by OHHOHING** [KurtBestor/Hitomi-Downloader#2460]
비리비리는 유료회원에 한하여 60프레임 영상 고화질 영상을 시청할 수 있습니다.
유료 계정은 있지만 다운받을 방법은 막막합니다.
로그인 기능 등을 구현해서 고화질 영상을 다운 받을 수 있도록 고려해주시면 정말 감사하겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
