### ISSUE TITLE
질문은 아니고 스크립트 만든김에 올려봅니다.

### ISSUE THREAD

**Issue by rakukracha** [KurtBestor/Hitomi-Downloader#2461]
[히토미다운로더_스크립트.zip](https://github.com/KurtBestor/Hitomi-Downloader/files/5218957/_.zip)

위 파일이 다운로드가 되려나 모르겠네요.

히토미 다운완료 후, 폴더명이나 파일명 수정하는 히토미 스크립트입니다.
히토미에서 다운로드 받았을때
이름이 원하는 대로 되지 않을때가 있습니다.
혹은 추가로 뭔가 하고 싶을때가 있습니다.
(번역을 구분 못한다거나, 타입, 태그 등을 확인해서 처리하고 싶다거나, 멀티 작가명을 추가로 저장하고 싶다거나...)
그런걸 구현해본 스크립트입니다.

my_hitomi_rename2_0.hds 는 이것저것 구현한 것이고,
my_hitomi_rename2_1.hds 는 위에것이 번잡해서 그냥 기초적인 것만 남겨본 것입니다.

my_hitomi_rename2_0.hds 기능
1) 원하는 형식으로 파일명 새로 작성
2) 파일명 너무 길 경우 줄이기(원본명 TXT 저장)
3) 작가들 너무 많을 경우 추가 저장(전체 이름 TXT로 각각 저장)

my_hitomi_rename2_1.hds 기능
위에서 1)번만 남김
(다 만들고 보니 복잡해서 간단한 샘플 삼아서 2,3번 날려봄)

별것 아닌 내용이지만 이왕 만들어본거라 한번 올려보고 싶었습니다.
다시 말하지만, 다운로드 완료된 후에 완료된 폴더와 파일명을 처리하는 스크립트입니다.
(다운로드에 관여하진 않습니다.)

위에 있는 기능 외에 넣고 싶은 기능 있으면 넣으시면 됩니다.
물론 빼고 싶은 기능은 빼면 됩니다.(일부 필수인 부분도 있을수 있으므로 잘 확인할 것)
물론 파이썬 할줄 알아야 가능합니다.

수정,배포 자유입니다.
(허접코드라 기왕이면 KurtBestor님이 멋지게 수정해서 스크립트 게시판에 올려주시면 더 좋겠구요. ㅋ)

원래 이곳에 있던 hook_rename.hds 를 베이스로 작성했습니다.
https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

**Comment by SaidBySolo** [comment]
pytz 외부 라이브러리로 알고있는데

```py
datetime.timezone(datetime.timedelta(hours=9))
```로

내장모듈 쓰는게 더 효율적일거같아요

**Comment by KurtBestor** [comment]
오.. 근데 너무 개인적이고 특수한 기능이라 위키엔 올리지 않는 게 좋을 것 같아요.

폴더명 바꾸고 나서 `cw.dir = newPath` 해주면 더 좋을 것 같아요.
