### ISSUE TITLE
이상한 아이콘이 떠 있는데 이게 뭘까요?

### ISSUE THREAD

**Issue by bhfaker** [KurtBestor/Hitomi-Downloader#2467]
도움말 오른쪽에 무당벌레?같은 아이콘이 떠 있고

눌러보면

로그
스레드 현황
인터프리터
콘솔
이미지 뷰어
tablet test
pop
blurwidget
fluid
도구창

이렇게 창이 뜨더라구요.
이 메뉴가 어떨때 뜨는건가요? 프로그램을 껐다 키니까 다시 사라졌네요.

**Comment by Dumbisted** [comment]
딱 봐도 디버그 메뉴네요. 보통은 사용할 일이 없는 물건입니다.
