### ISSUE TITLE
기능 건의) 파일명에 특정 태그나, 언어를 추가할 수 있나요?

### ISSUE THREAD

**Issue by justlooko** [KurtBestor/Hitomi-Downloader#2472]
가령 예를 들어, 다운을 받을 때,

 [고급 검색]에서 특정 태그, 혹은 언어로 검색하는 데, 

이 경우 해당 [검색어]를 파일 뒤쪽에 붙일 수 있을까요?

다운을 받고 매번 태그/작가/한국어 별로 분류하고 있는데 생각보다 시간이 꽤 걸리네요.. 

모든 태그를 붙이는 건 현실적으로 오바고.
특정 검색어로 검색했을 경우, 해당 검색어만 파일명 뒤쪽에 붙일 수 있는 기능이 있으면 좋을 것 같습니다.

(가능한 경우 10달러 후원해드리겠습니다.) 불가능하면 어쩔 수 없지만요.

**Comment by justlooko** [comment]
확인결과... 설정에서 파일명에 [Lung] 추가하면 해당 언어가 추가적으로 붙네요. 다만 태그의 경우 그냥 tag. 라고 출력되네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/188
