### ISSUE TITLE
제이마나 싸이트 주소가 변경되었습니다

### ISSUE THREAD

**Issue by gbdkjd5** [KurtBestor/Hitomi-Downloader#2473]
안녕하세요 제작자님

이번에 제이마나 사이트 주소가 변경되어 다운로드가 불가능하게 되었습니다

http://jmana.xxxyyyzzz.art/ 으로 변경되었으며 시간이 되시면 업데이트해주시면 감사하겠습니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by gbdkjd5** [comment]
> 
> 
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

작동이 잘되네요 고쳐주셔서 감사합니다
