### ISSUE TITLE
윈도우 업데이트 이후 데이터 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by Haylien** [KurtBestor/Hitomi-Downloader#2474]
윈도우10 사용중이며

금일 갑자기 기본 데이터 다운로드가 안 되는 현상이 발생했는데

json파일들을 다운 받지 못하는 거로 보입니다.  0kb로 파일 생성만 되고 0/20에서 멈춰있다가 뻗네요.

변화가 있었던 게 아마 윈도우 업데이트 같아서 이게 원인이 아닐까 싶습니다..

혹시 해결법을 아시거나 해결이 가능하실까요?

**Comment by 123cmdcmd** [comment]
제가 생각하기에는 윈도우 업데이트 때문이 아니라 이헨 문제인거 같아요.
지금 이헨 로딩이 매우 느리고 히토미도 정상이 아니거든요.
히토미다운로더 문제는 아닌거 같아요.

**Comment by Haylien** [comment]
아하... 서버 자체의 문제인가 보네요. ㄷㄷ
