### ISSUE TITLE
itmtu.com 가 45mt.com 으로 바뀌여서 다운로드가 안됩니다

### ISSUE THREAD

**Issue by CMBHCMBH** [KurtBestor/Hitomi-Downloader#2477]
주소만바뀐게 아니라 내부도 많이 바뀐거같드라구요  

itmtu.com 검색해서 들어가면 자동으로 45mt.com으로 가지면서 없는 페이지라고 뜹니다

**Comment by KurtBestor** [comment]
itmtu 는 다음 버전에서 빠질 예정이에요.
