### ISSUE TITLE
기능 추가 건의드립니다.

### ISSUE THREAD

**Issue by gudwls5022** [KurtBestor/Hitomi-Downloader#2478]
안녕하세요, 항상 프로그램 감사히 쓰고 있습니다.

다름이 아니라 히토미 다운을 받을때 대량으로 받는편인데,한번 다운받고 나중에 자료를 업데이트하면서 히토미 검색기에 done:x를 입력하면 하드에 있는 중복자료를 제외하고 표시되는 자료를 받을수 있어서 그렇게 쓰고 있습니다.
문제는, 히토미 검색기는 1회 검색에 1000개의 결과를 출력하는데 이미 다 받은상태에서 추가, 변동된 자료만 받으려니 중복자료가 제외되고 한 50개 정도만 검색결과가 나오고, 그걸 다운로더에 추가하고, 다시 계속검색을 누르고 하는식으로 반복하면서 다운로더에 1000개 정도 올릴때까지 해야되는데 중복자료가 많을수록 반복과정이 길어지네요. 
혹시 검색할때 중복자료는 처음부터 결과에서 제외하고 중복되지 않은 자료만 1000개 출력하는 옵션같은 기능 추가가 된다면 매우 유용한 옵션이 아닐까 조심히 건의드려봅니다.

건강하시고 좋은 주말 되세요^^

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2329

**Comment by gudwls5022** [comment]
앗 먼저 여쭤본분이 계셨군요. 감사합니다. 잘쓰겠습니다 (_ _)
