### ISSUE TITLE
켜지는데 1분이 넘게 걸리는데 원래 이런가요? 

### ISSUE THREAD

**Issue by dool-dool** [KurtBestor/Hitomi-Downloader#2481]
말그대로 입니다.
해당 어플을 실행 후, 30초~1분이 지나서야, 권한 확인창이 뜨고, 창이 뜹니다.
https://github.com/KurtBestor/Hitomi-Downloader/issues/2355#issuecomment-683374461
해당 버전을 사용중이고, 혹시 제가 세팅을 잘못한건지 하드웨어 성능때문에 
느려질 수 있는건지 궁금합니다.

**Comment by KurtBestor** [comment]
처음에 임시 폴더에 압축을 풀고 시작하기 때문에 드라이브 속도가 느리면 오래 걸려요.

**Comment by kyusang13** [comment]
드라이브의 속도 문제라기엔 저역시도 같은 문제인데, m.2 nvme가 c드라이브고 프로그램파일이 있는 d드라이브도 ssd입니다. 
저 역시도 어떤 버전 이후부터 프로그램 실행속도가 엄청 느려졌는데 어느 버전부터였는진 기억이 나질 않네요.
그리고 m.2 nvme도 드라이브 속도 문제가 있는거라면 이슈가 좀 많아야 할 것 같은데 그렇지도 않은게 조금 의아하네요..
