### ISSUE TITLE
마나토끼와 뉴토끼 다운이 좀 이상합니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2483]
마나토끼와 뉴토끼  다운은 잘되는데요 
마나와뉴토끼 만화와 웹툰 다운 받으면 이미지 파일이 딴 만화 이미지도 들어가있습니다
확인 해주시고 수정 부탁드립니다ㅠㅠ 
항상 감사하고 있습니다^^

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2487

**Comment by geniussjt** [comment]
정말 잘됩니다ㅠㅠ 정말 감사합니다^^
