### ISSUE TITLE
마나토끼(뉴토끼) 사이트 밴 방지 기능이 필요할 것 같습니다

### ISSUE THREAD

**Issue by 1qazxc** [KurtBestor/Hitomi-Downloader#2484]
다중 다운로드 기록을 구분해서 매크로 유저로 판단, ip 차단을 하는 것 같습니다.
그에 대응하는 기능이 있으면 좋을 것 같습니다.
항상 감사합니다.

**Comment by OpenMinding** [comment]
그렇네요 방금 2400시간 밴먹고 왔습니다

**Comment by getsome23** [comment]
혹시 실례가 안 된다면 어느 정도 다운받으셨는지, 공유기 ip 쓰시는지 알 수 있을까요? 저도 많이 받는 편이라 좀 불안해서

**Comment by 1qazxc** [comment]
> 혹시 실례가 안 된다면 어느 정도 다운받으셨는지, 공유기 ip 쓰시는지 알 수 있을까요? 저도 많이 받는 편이라 좀 불안해서

보니까 접속로그를 보고 판단하더라구요
예를들어 어떤 한 만화를 통째로 다운받을 경우, 각 화수의 페이지에 접속하는 시간대와 횟수를 보고 비정상적이다 싶으면 밴하는 것 같습니다. 다운로더로 받으면 대략 3초에 한번씩 각 화수의 페이지에 접속하는 걸로 뜨는 거 같아요.
예전에 북마크만 해놨다가 마나모아 날아간 기억 때문에 보관해야겠다 싶은 완결작들 몇개 받다가 눈에 띈 것 같네요

**Comment by getsome23** [comment]
알려주셔서 감사합니다. 한동안 완결작을 받는 건 위험하겠네요. 저번에 오래 점검하더니 서버 과부하를 최대한 막아보려는 거 같네요. 근데 운영진이 접속로그를 보여주던가요? 그냥 접속로그 확인해보니 비정상적인 다중 접속이 확인되어~ 뭐 이런 식으로 통보했을 것 같긴 한데요. 어 근데 2400시간은 좀 많이 세네요-0-;;;

**Comment by OpenMinding** [comment]
아이피타임 사용중이고 평소에 여러개씩 다운받다가 오늘 그랑블루 하나 다운했는데 막혔습니다.
아이피타임은 설정페이지가서 맥주소 변경하니까 뚫리더라구요
그래서 더 다운했습니다 ㅎ

**Comment by OpenMinding** [comment]
막힐때는 뭐 원인도 없고 그냥  
귀하는 2400시간동안 접근 불가합니다. (2020-12-29 20:50:05 이후 접근 가능)
이렇게만 써져있고 아무것도 안보입니다

**Comment by getsome23** [comment]
엌ㅋㅋ가차없네요 저도 아이피타임 쓰는데 혹시 막히면 참고해야겠네요 감사합니다

**Comment by inki123** [comment]
전에도 밴 한번 이거 쓰는사람들 싹 먹었다가 풀렷는데 다시금 먹엿네요....저도 밴먹......
