### ISSUE TITLE
대체 왜 실행이 안되는 걸까요 ㅠ

### ISSUE THREAD

**Issue by cambioformas** [KurtBestor/Hitomi-Downloader#2486]
실행이 되는 버전은 마나토끼 순서가 뒤죽박죽 or 다운이 안되고

마나토끼 해결해주신 버전은 실행이 안되고..

9월 들어와서 한번도 다운 받지 못했네요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2486

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2445

**Comment by chbk256** [comment]
실행이 안 된다는 게 (응답없음) 상태로 계속 리스트가 안 뜨는 상태로 있다는 말씀이신가요?

저는 다운 리스트가 많은 다운로더에서만 이런 현상이 나타나는데 같은 문제인지..

**Comment by cambioformas** [comment]
> 실행이 안 된다는 게 (응답없음) 상태로 계속 리스트가 안 뜨는 상태로 있다는 말씀이신가요?
> 
> 저는 다운 리스트가 많은 다운로더에서만 이런 현상이 나타나는데 같은 문제인지..

다운로더 자체가 실행이 안됩니다
