### ISSUE TITLE
히토미 다운이 안됩니다

### ISSUE THREAD

**Issue by needhelp1223** [KurtBestor/Hitomi-Downloader#2491]
네이버 웹툰은 되는데 히토미는 주소 쳐도 다운이 안되요 ㅠㅠ 업데이트 이후로 그런 것 같은데  그래서 아예 지우고 새로 다운로드 해서 시도해봤지만 안되네요ㅠㅠ

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
