### ISSUE TITLE
만화를 압축시켜

### ISSUE THREAD

**Issue by mac22222** [KurtBestor/Hitomi-Downloader#2492]
#2356 여기에 부연설명를 하자면

![11](https://user-images.githubusercontent.com/70459484/93736424-3dd66a00-fc1b-11ea-8355-2f120f6bb1ee.jpg)

이렇게 말고

![12](https://user-images.githubusercontent.com/70459484/93736826-804c7680-fc1c-11ea-8365-bc847ce5a4fb.jpg)

이렇게 나왔으면 하는 ...

감사합나다

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/2356
