### ISSUE TITLE
아프리카 연령제한 걸린거를 받고 싶은데 방법을 알고싶습니다

### ISSUE THREAD

**Issue by pepper1995** [KurtBestor/Hitomi-Downloader#2493]
안녕하세요 

유튜브 연령제한은  잘되는걸 확인했는데요 아프리카 연령제한은 invalid라고 뜨면서 안되네요

혹시 제가  잘못하고 있는건지 알고 싶습니다 로그인 하고 재생 누르고 this tap으로 저장했습니다 (어떤 타이밍에 확장프로그램으로 텍스트 저장하면 되는거라던지요.. 컴퓨터를 잘 알지 못해서요 ㅜㅜ)

밑에건 테스트해봤는데 다른 영상 여러개로 해도 다 안되네요..

좋은프로그램 감사합니다!

Invalid: [afreeca] 

version: 3.0b (20-08-15 20:47:31 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: 
dir: 
zip: 
type: afreeca
artist: None
url: 
valid: False
done: True
range: None
range_p: None
single: True
time: 1600683952.7976155 (Sep 21)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'string'
stop
Traceback (most recent call last):
File "utils", line 981, in start
File "utils", line 1023, in start_
File "extractor\afreeca_downloader", line 46, in read
File "<decorator-gen-37>", line 2, in get_video
File "constants", line 834, in wrapper
File "constants", line 805, in wrapper
File "extractor\afreeca_downloader", line 78, in get_video
AttributeError: 'NoneType' object has no attribute 'string'

Invalid: fail=True
EOT:

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by pepper1995** [comment]
감사합니다! 잘 되는것 같습니다~!
