### ISSUE TITLE
마나토끼 뉴토끼 또 다시 다운이 안되네요ㅠㅠ

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#2494]
[아마] 유녀 라이프!

version: 3.0b (20-09-21 06:46:16 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 6
group: False
input: https://manatoki77.net/comic/5594874
dir: hitomi_downloaded_manatoki\[아마] 유녀 라이프!
zip: 
type: manatoki
artist: 아마
url: https://manatoki77.net/comic/279450
valid: True
done: True
range: None
range_p: [17]
single: False
time: 1600688593.610716 (Sep 21)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
None

[File Names]

[URLs]

[Messages]
dirFormat: [artist] title
유녀 라이프! 17화 0
stop
EOT: https://manatoki77.net/comic/5594874

dirFormat: [artist] title
유녀 라이프! 17화 0
stop
EOT: https://manatoki77.net/comic/5594874

dirFormat: [artist] title
유녀 라이프! 17화 0
stop
EOT: https://manatoki77.net/comic/5594874

또 갑자기 다운 안되네요

**Comment by cramere** [comment]
저두 똑같네요. 추가적으로 웹에서 작가이름 부분이 바뀌었는데 프로그램에서 새로시작하면 다시 처음부터 다 읽어들인 다음 저장되었던 폴더에 작가이름을 바꾸지 않고 그대로 그 폴더에 저장합니다.

**Comment by cancerogenic** [comment]
마나토끼 진짜 징글징글하게 막네요..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KurtBestor** [comment]
@cramere 작가 이름 바뀐 건 https://github.com/KurtBestor/Hitomi-Downloader/issues/2386 때문에 폴더명이 정해진 형식이 아니라서 고칠 수 없게 되었어요.

**Comment by cramere** [comment]
아하... 그런게 있었군요. 답글 감사합니다.

**Comment by geniussjt** [comment]
다시 잘됩니다 정말 감사합니다ㅠㅠ

**Comment by getsome23** [comment]
고생하십니다 서버 때문에 막는 거 이해는 하는데 예전에 비해 너무 빡세게 막네요..

**Comment by geniussjt** [comment]
운영자님 죄송하지만 또 뉴토끼와 마나토끼 다운 시 다른 만화가 몇장 섞여서 다운됩니다ㅠ_ㅠ순서도...
확인 부탁드리고 수정해주세요ㅠ_ㅠ죄송해요
아...진짜로 토끼x들 징글징글하게 하네요
죄송합니다T^T

**Comment by KurtBestor** [comment]
@getsome23 페이지를 빠르게 읽으면 그런 것 같아서 5초에 한 페이지 읽던 걸 10초에 한 페이지 읽는 걸로 바꿨어요. 또 밴 되면 알려주세요.

**Comment by geniussjt** [comment]
어제 나온 테스트도  또 다시 뉴토끼와 마나토끼가 다운이 막혔습니다 아예 다운로드가 안됩니다ㅠ_ㅠ아아..
토끼x 증말 징글징글하게 대단하네요... 
 
[요코야리 멩고] 최애의 아이

version: 3.0b (20-09-21 12:48:04 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki77.net/comic/5597267
dir: hitomi_downloaded_manatoki\[요코야리 멩고] 최애의 아이
zip: 
type: manatoki
artist: 요코야리 멩고
url: https://manatoki77.net/comic/1023378
valid: True
done: True
range: None
range_p: [18]
single: False
time: 1600702499.488537 (Sep 22)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
최애의 아이 19화 0
stop
EOT: https://manatoki77.net/comic/5597267

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by geniussjt** [comment]
운영자님 만세~정말 감사합니다
어제 오늘 정말 대단하십니다
정말 잘 되네요T-Tb척

**Comment by geniussjt** [comment]
![1](https://user-images.githubusercontent.com/47520785/93799955-da7c2480-fc7a-11ea-96d7-4ffecc4623b4.jpg)
이렇게 나오네요...
이런...토끼X~ 새벽에도 다운 막아버렸네요ㅋㅋㅋㅜㅜ
이번이 세번째인가요 또 다시 다운이 안됩니다...아우 증말 우리 토끼군 근성이 대단하네요
암튼 운영자님 화이팅입니다 그럼 안녕히 주무세요^^

**Comment by manassm** [comment]
테스트버전다운이 실패..해외라 그런가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

GitHub 서버인데 지역은 상관 없을 것 같네요.

**Comment by esulbitea** [comment]
> 
> 
> 테스트버전다운이 실패..해외라 그런가요?

아마도 백신프로그램에서 막은걸 겁니다.
최근 며칠 사이 테스트버전을 어베스트에서 바이러스로 인식하고 자꾸 다운도 막고 실행도 막아서 
프로그램 끈 후 다운 받고 백신프로그램에서 예외로 설정하고 사용 중입니다

**Comment by esulbitea** [comment]
> 
> 
> > 테스트버전다운이 실패..해외라 그런가요?
> 
> 아마도 백신프로그램에서 막은걸 겁니다.
> 저도 최근 며칠 사이 나온 테스트버전을 어베스트에서 바이러스로 인식하고
> 자꾸 다운도 막고 실행도 막아서
> 프로그램 끈 후 다운 받고 백신프로그램에서 예외로 설정하고 사용 중입니다

**Comment by geniussjt** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> GitHub 서버인데 지역은 상관 없을 것 같네요.
지금 방금 테스트 해봤는데..요 마나토끼 다운 시 다른 만화가 몇장이 또 섞여서 다운됩니다...
흠..어제 보니... 조금 이따가 또 다운 막아놓은것 같은 생각이 듭니다ㅠ_ㅠ

**Comment by cramere** [comment]
Invalid: [manatoki] https://manatoki77.net / comic / 503775

version: 3.0b (20-09-21 23:07:47 GMT+0)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki77.net/comic/503775
dir: 
zip: 
type: manatoki
artist: 세리노 유나
url: https://manatoki77.net/comic/503775
valid: False
done: True
range: None
range_p: None
single: False
time: 1600752935.7112799 (Sep 22)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None


[Gallery]
None


[File Names]



[URLs]



[Messages]
dirFormat: [artist] title
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 1-1화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 1-2화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 2-1화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 2-2화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 3화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 4화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 5화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 6-1화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 6-2화
Skip: 잠시 컨셉 캐릭터로 하려다가 이세계 소환 ~유랑자는 여성의 적으로 인정 받았습니다~ 7화
hash: yb84ea25fb0
hash: i3d565b3bee
hash: nb21f7c61a6
hash: ae13588faa7
'data-ae13588faa7'
stop
Traceback (most recent call last):
File "utils", line 1014, in start
File "utils", line 1060, in start_
File "extractor\manatoki_downloader", line 87, in read
File "extractor\manatoki_downloader", line 159, in get_imgs
File "<decorator-gen-77>", line 2, in get_imgs_page
File "constants", line 835, in wrapper
File "constants", line 806, in wrapper
File "extractor\manatoki_downloader", line 206, in get_imgs_page
File "bs4\element", line 1401, in __getitem__
KeyError: 'data-ae13588faa7'

Invalid: fail=True
EOT: https://manatoki77.net/comic/503775

일부에서 이런 내용이 뜨네요. 되는 것도 안되는 것도 있는 듯 합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by getsome23** [comment]
ㄴ확인해보니 현재는 다운 가능, 페이지 추가/섞임 문제 없습니다. 토끼가 또 막을 것 같긴 하지만요..
