### ISSUE TITLE
제이마나는 한 편을 바로 다운로드는 못하나요?

### ISSUE THREAD

**Issue by getsome23** [KurtBestor/Hitomi-Downloader#2496]
개발자님 참 고생이 많으신데 마나토끼 또 막았네요 -0-... 어차피 제이마나랑 올라오는 거 다 똑같은 상황인데

예를 들어 마나토끼는 어떤만화 35화 링크가 있으면 이걸 다운로더에서 바로 35화를 다운받는데

제이마나는 어떤만화 35화 링크를 붙이면 다운을 못하고 꼭 만화 전체 목록 링크를 붙인 다음 거기서 35화를 선택해서 받아야 하더라구요. 

조금일 땐 괜찮은데 많을 때는 시간 차이가 꽤 나서요.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1799

**Comment by getsome23** [comment]
감사합니다! 잘 됩니다.
