### ISSUE TITLE
AV 자막 사이트 하나 추가 건의 드립니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#2501]
보통 야동에는 자막이 없는 편인데

일본 AV 자막 애동이 한 4천개 내외로 있는 사이트가 하나 있더군요
자막이 달려서 내용을 좀 알게되는게 새로운 매력이라고나 할까요?
히토미 다운로더로 다운 가능하다면 참 좋겠습니다

https://kr18.sogirl.co/category/jpsub/

**Comment by KurtBestor** [comment]
다음 링크에서 `sogirl.hds` 다운로드해서 스크립트 적용해주세요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
