### ISSUE TITLE
업데이트 이후 프로그램을 실행하면 _mei12334 같은 폴더가 생성됩니다.

### ISSUE THREAD

**Issue by cokasss** [KurtBestor/Hitomi-Downloader#2511]
기존에는 프로그램을 실행한다고 딱히 임시 폴더가 생성되고 그렇지는 않았던 것 같은데, 업데이트 이후로는 프로그램을 실행하면 _mei12345같은 임시 폴더가 생성되었다가 프로그램 종료시 없어집니다.

매번 쓰기 지우기를 반복한다면 혹시나 SSD의 수명에 영향을 주지 않을까 해서 해당 현상이 정상인지 문의드립니다.

**Comment by KurtBestor** [comment]
임시 폴더에 압축 풀고 시작하는데 원래 `%temp%` 위치였다가 이것 때문에 바뀌었어요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2445
