### ISSUE TITLE
다운로드시 폴더에 작가명을 안붙일수는 없나요?

### ISSUE THREAD

**Issue by ghost** [KurtBestor/Hitomi-Downloader#2517]
사이트가 바뀌거나 할때 작가명이 붙을때가 있고 안붙을때가 있어서 정리하기가 좀 힘드네요.

**Comment by floygrasm** [comment]
설정에서 변경할수 있는걸로 알고있습니다.

**Comment by justlooko** [comment]
히토미 다운로더 > 옵션 > 일반 > 폴더명 형식 에서 '아티스트' 삭제하시면 되요
