### ISSUE TITLE
Old twitter search API doesn't work anymore.

### ISSUE THREAD

**Issue by nisehime** [KurtBestor/Hitomi-Downloader#2534]
It seems that search link you use (https://twitter.com/i/search/timeline) doesn't work now. The new api that used by twMediaDownloader is `https://api.twitter.com/1.1/search/universal.json`. The GET variables are also bit different now, you should check.

**Comment by nisehime** [comment]
Bump.

**Comment by nisehime** [comment]
@KurtBestor please.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by nisehime** [comment]
Works fine so far.
