### ISSUE TITLE
네이버 웹툰 다운시 이미지 압축 문의

### ISSUE THREAD

**Issue by kimhomo** [KurtBestor/Hitomi-Downloader#2550]
네이버 웹툰 다운로드시 다른 프로그램들과 다르게 자동으로 jpg 압축이 80%정도 된 상태로 다운이 되는데
jpg 압축 없이 받을 수는 없나요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1337
