### ISSUE TITLE
FC2블로그 부탁드립니다

### ISSUE THREAD

**Issue by Act-20** [KurtBestor/Hitomi-Downloader#2563]
https://blog.fc2.com/

아시다시피 많은 그림들을 볼 수 있고 

링크에 caution/을 붙이면 성인 작품들도 볼 수 있는 곳이죠.

https://video.fc2.com/ 마찬가지로 fc2video 라는 곳은 여러 동영상들을 볼 수 있고

링크에 a/를 붙이면 adult로 넘어가는 괜찮은 곳입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

현재 동영상만 지원해요.
