### ISSUE TITLE
다운로드한 것들이 검색목록에서 녹색체크가 표시되지 않아요

### ISSUE THREAD

**Issue by com5082** [KurtBestor/Hitomi-Downloader#2575]
우선 앞서서 진심으로 이 다운로더를 사용하게 해주시는 자비와 노고에 감사하다는 말을 하고 싶어요

정말 감사합니다

얼마 전까지만 해도 검색란에서 이미 다운로드 했던 것들은 

이미 다운로드했다는 표시가 되어 있었는데요

어제쯤부터 검색란에 표시가 되지를 않습니다

확인 한 번만 해주시면 안될까요?

읽어주셔서 감사합니다

**Comment by KurtBestor** [comment]
체크해봤는데 재현할 수가 없네요.

**Comment by com5082** [comment]
> 우선 앞서서 진심으로 이 다운로더를 사용하게 해주시는 자비와 노고에 감사하다는 말을 하고 싶어요
> 
> 정말 감사합니다
> 
> 얼마 전까지만 해도 검색란에서 이미 다운로드 했던 것들은
> 
> 이미 다운로드했다는 표시가 되어 있었는데요
> 
> 어제쯤부터 검색란에 표시가 되지를 않습니다
> 
> 확인 한 번만 해주시면 안될까요?
> 
> 읽어주셔서 감사합니다
