### ISSUE TITLE
다운로드 속도 제한 적용이 늦게 들어가는 거 같습니다

### ISSUE THREAD

**Issue by hwahyang1** [KurtBestor/Hitomi-Downloader#2591]
저거 설정에서 바꾸고 저장하고 한 5초 조금 더 지나야 적용되는데 혹시 더 앞당길 수는 없을까요?

**Comment by hwahyang1** [comment]
지금 본건데 제한거니까 속도가 왔다갔다 하는것도 있네요 (디스크 사용량은 무관합니다)

![image](https://user-images.githubusercontent.com/40535405/96000943-6d6f3f80-0e72-11eb-9a22-db7891b60760.png)

**Comment by KurtBestor** [comment]
속도 제한은 곧바로 들어가요.
