### ISSUE TITLE
특정 작가 제외 기능 추가 건의

### ISSUE THREAD

**Issue by ZetabS** [KurtBestor/Hitomi-Downloader#2593]
히토미 검색기를 뒤적거릴 때 대체로 그림체나 내용 때문에 특정 작가를 절대로 보고 싶지 않은 경우가 많을 겁니다.
고급 검색 기능을 이용해서 -작가명1, -작가명2 이런 식으로 블랙리스트를 구현해봤지만
블랙리스트에 작가를 추가하거나 제거할 때, 그리고 따로 한 작가만 정해서 검색을 할 때 일일히 북마크에서 제거하고 추가한다던가 하는 불편한 점이 많았습니다.

그래서 설정의 태그 제외 기능처럼 따로 작가 제외 기능을 추가해주셨으면 좋겠습니다.

**Comment by ZetabS** [comment]
아이디어가 더 떠올랐는데 검색기를 찾아보다가 눈갱당하면 바로 제외할 수 있게 작가명 옆에 따로 제외 버튼을 추가하는 것도 좋을 것 같습니다.

**Comment by KurtBestor** [comment]
최신 버전에서 검색기 검색 목록에서 `마우스 우 클릭` - `제외 태그 목록에 작가 추가` 누르면 돼요.
