### ISSUE TITLE
네이버웹툰

### ISSUE THREAD

**Issue by OpenMinding** [KurtBestor/Hitomi-Downloader#2613]
네이버 웹툰에서 완결난 작품중에 스토어 구매로 넘어간 작품들은 다운이 불가능한가요?
일반 웹툰 페이지에서는 목록이 전부 안뜨고 스토어나 네이버 시리즈 쪽으로 넘어가야만 다운이 되더라구요

다운할 수 있게 가능할 까요?

**Comment by lightnoveller** [comment]
유료화된 에피소드들은 불가능합니다. 유료화되기 전에 다운로드하세요.
