### ISSUE TITLE
히x미, 히x비 다운이 안됩니다

### ISSUE THREAD

**Issue by fuzzypurge** [KurtBestor/Hitomi-Downloader#2615]
익헨은 되는데 저 둘은 서버를 아무리 설정해봐도 invalid가 뜹니다
익헨은 이미지 리미트때문에 되다가도 안되는데 이부분 해결책이라도 없을까요

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631
