### ISSUE TITLE
히토미, 익헨은 여전히 작동이 안됩니다...

### ISSUE THREAD

**Issue by sony3818** [KurtBestor/Hitomi-Downloader#2619]
픽시브는 작동이 되는데 익헨, 히토미는 설정을 해봐도 작동이 안됩니다...ㅠ

그리고 익헨은 VPN 안 해도 이미지 보는 건 됬는데 2 ~ 3일 전부터는 VPN 사용하지 않으면

'you have temporarily reached the limit for how many images you can browse'

이런 문구와 나오면서 이미지가 안 보이던데 대충 너무 많이 받아서 그런건가 싶은데... 뭔가 연관이 있을까요?

**Comment by chrno8282** [comment]
그 문구는 너무 많이 다운받아서 그런것입니다.  e-hentai 가셔서 My Home 가시면 이미지 몇장 받을수있는지 표시됨니다.

**Comment by sony3818** [comment]
저 회원도 아니라 마이 홈 가도 로그인 해야되서 못봐요...ㅠ

**Comment by fuzzypurge** [comment]
비회원은 몇백장 제한이고, 회원은 기본 5천장으로 기억합니다. 가입이 어려우시면 임시방편으로 몇시간 뒤에 다시 시도해보시면 풀릴 듯 합니다

**Comment by chrno8282** [comment]
일단 회원기준이지만....1분에 3장 회복됨니다. 몇장이나 초과하신지는 모르겠지만...4320장씩 회복되니까...하루이틀이면 다시 받을수있읍니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631
