### ISSUE TITLE
[Hitomi.la] No download starts / ⚠Failed to retry; Reverted

### ISSUE THREAD

**Issue by sorielkobayashi** [KurtBestor/Hitomi-Downloader#2625]
today i tried to download from hitomi.la and no download starts. just create the "info.txt" file and it will stay as seen in the following attached image.

![Hitomi Downloader 22_10_2020 08_52_27](https://user-images.githubusercontent.com/73005257/96889646-0b02da00-1444-11eb-9adf-7d878572197a.png)

I tried changing the priority of the server both in automatic mode and in manual mode and always with

**Comment by sony3818** [comment]
저도 벌써 3일 째 인데 혹시 최근에 많이 받으셨나요?

**Comment by TimurYoung** [comment]
If you turn off bypass DPI, you can receive from Ex-hen. But it's slow..

**Comment by dhtpdud** [comment]
나만그런게 아니였구나

**Comment by neuroring** [comment]
c. f. #2629 . it's in Korean but won't be hard to understand.

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631

**Comment by sorielkobayashi** [comment]
> If you turn off bypass DPI, you can receive from Ex-hen. But it's slow..

I did what you told me and it worked ok, thank you very much for helping me

**Comment by sorielkobayashi** [comment]
> If you turn off bypass DPI, you can receive from Ex-hen. But it's slow..

I did what you told me and it worked ok, thank you very much for helping me
