### ISSUE TITLE
개발자님 무슨 일 있으신 건가요?

### ISSUE THREAD

**Issue by getsome23** [KurtBestor/Hitomi-Downloader#2626]
히토미 invalid 문제 때문에 들어왔는데

항상 빠르게 피드백해주셨는데

확인해보니까 약 한달째 활동이 없으시네요.

지금은 어떤 사이트는 되고 있지만 히토미는 안 되고 있고 경험상 언젠가는 사이트들이 막아버리니까

정말 유용한 프로그램인데 업뎃이 끊길까봐 불안하네요. 

활동 쉬신다는 이야기라도 있으셨는지..? 빨리 돌아와주시길ㅠ

**Comment by tdi2020** [comment]
딱히 아무 얘기도 올라오지 않았던것 같습니다.

그렇지만 저는 개발자 선생님께 무슨 일이라도 있진 않을까 걱정이 되네요.. 혼자 다 하시느라 혹시 건강 해치진 않으셨을지요.

무소식이 희소식이라고, 프로그램보다는 본인의 삶과 건강이 최우선이니 여기 꼭 건강한 근황이 올라오면 좋겠습니다..ㅠㅠ

**Comment by KurtBestor** [comment]
그냥 조금 바빠서요. 걱정해주셔서 고마워요! 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631

**Comment by getsome23** [comment]
> 그냥 조금 바빠서요. 걱정해주셔서 고마워요! 참고해주세요: #2631

다행이네요 감사합니다! 힘내세요 응원합니다
