### ISSUE TITLE
About Error on Downloading images from Hitomi.la

### ISSUE THREAD

**Issue by niflheimr07** [KurtBestor/Hitomi-Downloader#2627]
I think it's not the issue of this application.
We all got the errors because this app only fetch the images from side server which is now all offline.

I have seen some apps using the same ways to get the image like this app , they all are now unavailable to fetch image from hitomi.la
if you are using any app that are able to fetch image from the hitomi.la , they are getting image from main website , unlike this app.
It seems like the side servers are shared by community , it's not owned by this developer , so we can't expect the developer can fix it.
Unless the owner of side server finds out the problem and make them online , then we will be able to use this app to download from hitomi.la
I'm using other app to download from hitomi.la main website because I don't expect too much for the side servers go alive since it's been few days.

if you still want the image , you can set the server to e-hentai.org and download from there, but they have lower quality compared to hitomi.la.
It's the only one option right now , if you still want to use this app.
Otherwise, you can just go to find other apps.

**Comment by neuroring** [comment]
it looks like aa.hitomi.la, ba.hitomi.la, ca.hitomi.la side servers have gone off and ab.hitomi.la bb.hitomi.la cb.hitomi.la are working. They changed or turned off the severs for some reasons. c.f. #2629 to temporarily fix this problem

**Comment by KurtBestor** [comment]
Please see: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631

**Comment by niflheimr07** [comment]
Solved.
