### ISSUE TITLE
IP 주소 변경하니 정상적으로 작동합니다...

### ISSUE THREAD

**Issue by sony3818** [KurtBestor/Hitomi-Downloader#2628]
히토미 다운로더를 사용한지 얼마 안됬는데 2~3일 전에 하루죙일 다운 받아서 그런지 이헨 자체적으로 막혀서 다운로더도 사용이 안된것으로 보입니다... 저는 공유기를 사용중이라 공유기 IP를 변경해주니 바로 잘 됩니다... 적당히 다운 받아야 될 듯 싶습니다...ㅠ

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631
