### ISSUE TITLE
히토미 다운로드시에 서버 참조가 잘못되는거 같습니다.

### ISSUE THREAD

**Issue by kkr881** [KurtBestor/Hitomi-Downloader#2629]
아래 외국분 문의글 보고 확인해보니 실제 다운로드 요청은
aa.hitomi.la
ba.hitomi.la
ca.hitomi.la
위 세 서버를 통해 요청하고 있으나
실제 히토미 상에는
ab.hitomi.la
bb.hitomi.la
cb.hitomi.la
위 세 서버를 통해 파일을 가져오고 있습니다.
임시로 ab bb cb 서버의 ip base로 도메인명을 바꿔서 테스트해보니 정상 다운로드가 되네요.

**Comment by komujun** [comment]
혹시 소스 어케 까보신건지 물어봐도 될까요? 소스 까신게 아니라면 extractor에서 어느 부분에 있는지..

**Comment by rsef1234** [comment]
저 주소는 어떻게 알아내셨고 코드는 어떻게 까서 바꾸셨는지 알려주시면 감사하겠습니다.

**Comment by yks1977** [comment]
> 저 주소는 어떻게 알아내셨고 코드는 어떻게 까서 바꾸셨는지 알려주시면 감사하겠습니다.

윈도우 C:\Windows\System32\drivers\etc\hosts 파일에

23.237.107.212	aa.hitomi.la
23.237.36.204   	ba.hitomi.la
192.240.120.12	ca.hitomi.la

추가하시면 바로동작합니다.

**Comment by champion388** [comment]
진짜 감사합니다 ㅠㅠㅠㅠㅠ

**Comment by 123cmdcmd** [comment]
안녕하세요.
알려 주신 위 파일에서 추가를 하니 "이 위치에 저장할 권한이 없습니다." 라는데
혹시 편집기를 따로 사용해서 바꾸거나 따로 방법이 있나요?
추가하는 방법을 알려주시면 감사하겠습니다.

**Comment by yks1977** [comment]
> 안녕하세요.
> 알려 주신 위 파일에서 추가를 하니 "이 위치에 저장할 권한이 없습니다." 라는데
> 혹시 편집기를 따로 사용해서 바꾸거나 따로 방법이 있나요?
> 추가하는 방법을 알려주시면 감사하겠습니다.

메모장을 관리자 권한으로 실행해서 편집하세요

**Comment by 123cmdcmd** [comment]
감사합니다.

**Comment by RedRabbit7777** [comment]
감사합니다 
덕분에 해결했습니다

**Comment by fuzzypurge** [comment]
저는 여전히 invalid가 뜨네요ㅠㅠ
23.237.107.212 aa.hitomi.la
23.237.36.204 ba.hitomi.la
192.240.120.12 ca.hitomi.la
이걸 hosts에 붙여넣는거 맞나요?

**Comment by z09716** [comment]
host에 붙여넣는 곳이 메모장에서 정확히 어느 위치에다가 하면 되나요?
![어디에](https://user-images.githubusercontent.com/33984787/96953636-850e8e00-152c-11eb-935f-de36aede7806.PNG)

**Comment by yks1977** [comment]
> host에 붙여넣는 곳이 메모장에서 정확히 어느 위치에다가 하면 되나요?
> ![어디에](https://user-images.githubusercontent.com/33984787/96953636-850e8e00-152c-11eb-935f-de36aede7806.PNG)

![image](https://user-images.githubusercontent.com/68933053/96955309-3a8f1080-1530-11eb-8a97-7ea4a7045534.png)

**Comment by korithing** [comment]
말씀하신대로 hosts 파일 수정하니까 다른 다운로더들도 정상적으로 작동하네요! 감사합니다

**Comment by iamlokingforchange** [comment]
@yks1977 Thank you very much! It's working again!

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2631

**Comment by kkr881** [comment]
확인 감사합니다
