### ISSUE TITLE
다운로드 속도가 정상인지 궁금합니다.

### ISSUE THREAD

**Issue by tsi03136** [KurtBestor/Hitomi-Downloader#2632]
예전에 히토미 다운로더를 사용했을 때는 초당 1MB/s는 나왔던 걸로 기억합니다.

그리고 한동안 사용하지 않다가 다시 사용하는데 100KB/s 이하로만 나오고 가끔 0KB/s로 낮아지는 등 네트워크 상태가

많이 좋지 않아 보이기도 합니다.

다만 exhentai 쿠키를 넣으면 350KB/s 까지 상승하기도 합니다.

혹시 다운로드 서버가 바뀌었다거나 변경점이 있어서 그런 것인지 궁금합니다.

**Comment by getsome23** [comment]
방금 전 사용했는데 속도 잘 나왔습니다. 프로그램의 문제가 아닌 것 같아요.

**Comment by tsi03136** [comment]
> 방금 전 사용했는데 속도 잘 나왔습니다. 프로그램의 문제가 아닌 것 같아요.

죄송합니다. 최신 버전은 문제가 없었습니다. 코멘트 닫도록 하겠습니다
