### ISSUE TITLE
이런 레전드 프로그램을 만들어주셔서 감사합니다

### ISSUE THREAD

**Issue by rladlf556** [KurtBestor/Hitomi-Downloader#2637]
후원할수있으면 후원이라도 해드리고싶내요 정말감사합니다

**Comment by Yoon0618** [comment]
https://www.patreon.com/KurtBestor

개발자님 패트리온 입니다 🙃

**Comment by rladlf556** [comment]
> 후원할수있으면 후원이라도 해드리고싶내요 정말감사합니다
