### ISSUE TITLE
Sankaku Channel 다운로드가 안 됩니다.

### ISSUE THREAD

**Issue by Duo-S** [KurtBestor/Hitomi-Downloader#2652]
태그는 *** 입니다.

다른 태그는 대부분 잘 되지만 가끔가다 Invalid가 뜨는 태그가 있긴 합니다.

이 태그에서의 목록은 대충 600개 가량인데, 240개 정도 읽은 상태에서 Invalid로 바뀌는 것 같습니다.

혹시 로그인 문제인가 싶어서 쿠키도 따로 넣어봤지만 소용이 없는것 같네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
