### ISSUE TITLE
제목이 짤리는 것 같습니다

### ISSUE THREAD

**Issue by abc2344** [KurtBestor/Hitomi-Downloader#2682]
원래라면 한글도 출력되어야하는데 영어만 출력되는 것 같아 문의드립니다.

Akatsuki Usagi/[Amai Wakusei] Mou Danna no Chinpo ja Gaman Dekinai Tonari ni Hikkoshite Kita Shinkon Osananajimi o Netoru made ｜ (1597677)

version: 3.2a (20-10-31 05:00:31 UTC)
platform: Windows-10-10.0.18362-SP0
order: 0
group: False
input: 1597677
dir: hitomi_downloaded\Akatsuki Usagi[Amai Wakusei] Mou Danna no Chinpo ja Gaman Dekinai Tonari ni Hikkoshite Kita Shinkon Osananajimi o Netoru made ｜ (1597677)
zip:
type: hitomi
artist: akatsuki usagi
url: https://hitomi.la/cg/mou-danna-no-chinpo-ja-gaman-dekinai-~tonari-ni-hikkoshite-kita-shinkon-osananajimi-o-netoru-made~-|-이제-남편의-자지로는-참을-수-없어-옆집에-이사온-신혼-소꿉친구를-네토-한국어-1597677.html
valid: True
done: True
range: None
range_p: None
single: False
time: 1604370060.563609 (Nov 3)
tags: []
goodbyedpi: True
lock: False
color: done
paused: False
format: None
p2f: None
segment: None

[Gallery]
갤러리 넘버: 1597677

제목: Mou Danna no Chinpo ja Gaman Dekinai Tonari ni Hikkoshite Kita Shinkon Osananajimi o Netoru made ｜ 이제 남편의 자지로는 참을 수 없어-옆집에 이사온 신혼 소꿉친구를 네토라레할 때까지

작가: akatsuki usagi

그룹: amai wakusei

타입: artistcg

시리즈: N/A

캐릭터: N/A

태그: female:beauty mark, female:big breasts, female:blowjob, female:cheating, female:cunnilingus, female:masturbation, female:milf, female:nakadashi, female:netorare, female:rape, female:sex toys, female:sole female, female:x-ray, male:condom, mosaic censorship

언어: Korean

[Messages]
get_imgs server: hitomi
FINAL SERVER: hitomi
ehen_url: None
imgs: 143
get_title__

stop
EOT: 1597677

**Comment by hny2798** [comment]
이슈 검색이 잘 안되는데 그게 아마 뭔 이유로 폴더명인가 경로인가 압축파일인가  너무 길면 문제가 생겨서 줄인거로 기억합니다
링크 달아드리고 싶은데 해당 내용 못찾겠네요

**Comment by abc2344** [comment]
알려주셔서 감사합니다. 기술적 문제인가 보네요.
