### ISSUE TITLE
del

### ISSUE THREAD

**Issue by NBO4532** [KurtBestor/Hitomi-Downloader#2705]
del

**Comment by KurtBestor** [comment]
계정 디코나 메일로 주시면 테스트 해볼게요
후원은 프로그램 하단에 하트 누르시면 할 수 있어요

**Comment by KurtBestor** [comment]
로그인 쿠키 넣으면 유료컨텐츠도 다운로드 가능해요

**Comment by FORT-262** [comment]
답변을 늦게 봐버렸네요 로그인 쿠키 넣는방법을 잘 모르겠어서요 혹시 알려주실수 있으신가요 ?
