### ISSUE TITLE
[건의] 목록에서 휠 스크롤 시 썸네일이 하나라도 겹치면 좋겠어요. 외1건

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#2734]
로컬 폴더에서 삭제된 파일을 섬네일에서 삭제하는 기능 추가 건의

**Comment by KurtBestor** [comment]
무슨 의미인지 이해할 수가 없는데 좀 더 쉽게 설명해주실 수 있나요?

**Comment by DBdeepsleeper** [comment]
> 무슨 의미인지 이해할 수가 없는데 좀 더 쉽게 설명해주실 수 있나요?

1. 유튭 영상을 1, 2, 3 다운로드

2. 로컬 폴더에서 영상 3을 감상 후 삭제

3. 히토미 다운로더에는 3에 관한 정보 남아있음

 > 로컬 폴더에 없는 파일 삭제 옵션 (눌렀을 때 진행되는 토글이면 좋겠습니다.)

히토미 다운로더 목록에서 영상 3 삭제

**Comment by DBdeepsleeper** [comment]
![image](https://user-images.githubusercontent.com/68507771/99809793-23baf880-2b86-11eb-9a00-3231bdc98c6d.png)

![image](https://user-images.githubusercontent.com/68507771/99809818-303f5100-2b86-11eb-91f2-0b6921ff05ea.png)

![image](https://user-images.githubusercontent.com/68507771/99809847-38978c00-2b86-11eb-8dcf-898fe72085ba.png)

![image](https://user-images.githubusercontent.com/68507771/99809868-40573080-2b86-11eb-84c2-33be06d727fd.png)

제일 위 목록에서부터 스크롤을 4번 진행한 상황인데요. 제일 아래쪽이 조금씩 잘려서요. 한 번의 휠로 마지막 한 개의 영상

섬네일은 겹쳐서 스크롤 되면 어떨까 해서요.
