### ISSUE TITLE
[버그] 삭제시 휴지통으로 보냄 작동 안 됨

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#2735]

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2677

**Comment by DBdeepsleeper** [comment]
> 참고해주세요: #2677

아. 이미 업데이트 하셨군요. 정식 버전 기다리고 있을게요.
고맙습니다.
