### ISSUE TITLE
Pixiv Login Preference Issue

### ISSUE THREAD

**Issue by bostafu2006** [KurtBestor/Hitomi-Downloader#2758]
Hi,

Like the title said, I can't log in with my Pixiv account in the preference.
Is there someting I am doing wrong ?

Thank you for your help.
Bostafu.

![ScreenShot049](https://user-images.githubusercontent.com/74857358/99908592-d48ada00-2ce3-11eb-9a40-ca088cb4f2e7.jpg)

**Comment by callacall** [comment]
![Capture](https://user-images.githubusercontent.com/59549156/99905515-2c3d3b80-2d0c-11eb-8af7-5e5a20654c13.PNG)
I have the same problem aswell

**Comment by Retaik** [comment]
@bostafu2006, @callacall 
I read it somewhere here. There is a fairly simple solution. Go to your pixiv in a browser, log out, and login. Pixiv asks to change the password - change it and everything should work.

**Comment by bostafu2006** [comment]
Thank you Retaik ! Work like a charm :)
