### ISSUE TITLE
실행 파일 및 ini 파일 자체의 삭제

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#2760]
버그인지는 확실하지 않습니다.

다운로더는 19일 or 20일에 다운 받았던 것으로 기억합니다.
압축 풀기 귀찮아서 그냥 zip 파일 내에서 바로 exe 실행파일 실행 후 작업표시줄에 고정해놓았습니다.

21일에  (버그인지 확실하지는 않으나) 컴퓨터를 재부팅 해보니 그 이전에 다운받았던 것이 다운로더 내에서만 사라졌습니다. 다운된 동영상 등 자체는 사라지지 않았습니다. 이에 정보를 담아두는 폴더를 찾으면 되겠다는 생각으로 찾으려고 했고,, 한참 못찾다가 정말 우연하게 아무 관련없는 사이트에 있던 링크(C:\ 이런식으로 된)로 들어가게 되었고, 그 폴더를 담고 있던 폴더 내에서 폴더명이 Mm.....(확실하지 않음)인 폴더 총 2개에 각각 ini파일(메모장으로 열리더니 안에 저장 관련 내용이 있던), 실행파일이 있었고, 당연히 그냥 ini파일을 실행 파일 내에 복붙하여 사용하였습니다. 사용 시에는 작업표시줄에 고정하고 사용하였습니다.

오늘(22일) 컴퓨터를 재부팅하고 작업표시줄을 통해 실행 해보니 실행파일 자체가 없어졌다고 떴습니다;; ini파일 또한 사라져있었습니다.(정확히 사라진지는 모르겠으나 내 pc에서 C, D 드라이브를 대상으로 검색 시에는 나오지 않았고, 윈도우 버튼을 통해 검색해도 없었습니다.) Mm.. 이 폴더도 찾을 수 없습니다.(현재 상태에서는 못찾고 있습니다.)

아마 처음에 압축을 풀지 않고(따로 폴더를 만들지 않고) 바로 사용을 한 것이 문제인 것 같습니다. 확장 파일이 따로 폴더를 가지고 있지 않는 상황에서 ini 파일이 생성되는 위치를 알 수 있을까요? 그리고 이러한 현상이 발생한 이유 또한 알고 싶습니다. 복구 방법도 알고 싶습니다.(애초에 위에서도 말했듯이 ini 파일을 실행파일이 있는 파일에 '복사하여' 총 2개의 ini파일이 있으므로 적어도 21일에 저장한 내용 이전의 내용은 포함한 ini가 있어야 한다고 생각하는데(만약 21일에 저장된 ini가 사라졌다고 해도) 검색되지 않으니 제가 못찾아서 복구를 못하고 있는 상황이라고 저 자신은 예상하고 있기 때문입니다.)

**Comment by HwNnhji** [comment]
차근차근 찾아본 결과 다시 복구할 수 있었습니다. 일단 사실 먼저 말씀드리면 21일차에 나왔던 사이트는 홈페이지가 아니고 다운로더의 저장 위치에서 찾은 것입니다.(설정-일반-저장폴더) 이의 기본 설정 값이 실행파일만 들어있던 그 폴더였고, 그 폴더명은 'BNZ.5fb7e9f720a2e70a' 이와 비슷한 이름으로 이루어져 있습니다. 모두 BNZ.5fb로 시작하는 폴더입니다. 그리고 실행파일만 존재하던 그 폴더(ini를 복붙하여 넣은 폴더)는 exe파일만 사라지고, debug라는 메모장 파일과 ini파일 2개밖에 없었습니다.

문제 상황은 해결되었으니, 이 상황에 대한 이유를 알고 싶습니다. 실행 파일이 이유없이 사라질 수 있는 것인가요?
