### ISSUE TITLE
Pixiv Fanbox, Fantia, Patreon 등 다운로드 추가 건의

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader#2815]
혹시 후원 사이트들인 Pixiv Fanbox, Fantia, Patreon 등에 대해
로그인 기능 추가와 함께 해당 사이트들의 주소도 다운로드 가능하게 할 수 있을까요?

후원 중인 작가들이 각 후원 사이트에 공개한 이미지, 영상들을 일괄 다운로드하고 싶은데
현재 Hitomi Downloader GUI엔 관련 기능이 없는 듯 하여, 추후 추가하실 의향 있는 지 여쭤봅니다

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/1754

결제 전용 사이트 같은 경우는 봇 감지로 밴 당하면 위험하기 때문에 좀 꺼려지네요.

**Comment by nikin78** [comment]
파이썬이나 자바 기반 등 스크립트 형태로 비슷한 기능의 크롤러들이 몇 개 배포 중인 듯 해서 괜찮으리라 생각했는데, 봇 감지 문제가 있었군요...
고려라도 해주셔서 감사합니다 :)
