### ISSUE TITLE
다운로드 속도가 0KB/s에서 나왔다가 안나왔다가 합니다

### ISSUE THREAD

**Issue by rkdals0131** [KurtBestor/Hitomi-Downloader#2816]
한번에 다운로드 할 수를 8개에서 1개로 줄이니까 되긴 하는데 이마저도 계속 다운로드가 안 되고 0KB/s 였다가 가끔 다운로드되고 멈ㅊ고 다시 멈추고 반복합니다...

**Comment by KurtBestor** [comment]
해당 작업 <kbd>마우스 우 클릭</kbd> - <kbd>작업 정보... (I)</kbd> 눌러서 나온 내용 보여주세요.
