### ISSUE TITLE
xtube는 추가가 어려운건가요? ㅠ

### ISSUE THREAD

**Issue by KaD234** [KurtBestor/Hitomi-Downloader#2817]
https://www.xtube.com/

여기에만 있는것도 몇몇개 있어서 좀 있으면 좋겠다 싶네요.
추가가 될 수 있을지 안될지 답변해주실 수 있으신지 여쭤봅니다.
뭐 어려운거면 어쩔 수 없는거구요... 이미 다른거 다운로드 지원 잘되게 해주신거만드로도 감사드리는거니 ㅎㅎ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by KaD234** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

기능 추가 정말 감사드립니다... 이제 확인해서 써보려고 했는데
갑자기 저 사이트에서 뭐 약관변경 거지같이라도 했는지 다운받고싶었던것들이 죄다 사라졌네요...
저거 글 쓸때까지만 해도 다 살아있었는데...
멘붕이...
비록 써보진 못했지만 그래도 기능추가 감사드립니다...
