### ISSUE TITLE
Sankaku Plus (Sankaku 유료 요금제) 제한 걸린 이미지도 다운 가능할까요?

### ISSUE THREAD

**Issue by nikin78** [KurtBestor/Hitomi-Downloader#2854]
몇 달 전 Sankaku에서 일부 이미지는 유료 요금제인 Sankaku Plus를 결제해야지만 접근이 가능하게 정책을 바꾸었습니다
만약 로그인한 상태에서 Sankaku Plus를 결제해 제한된 이미지들을 해금한 뒤, Sankaku 사이트의 쿠키를 Hitomi-Downloader 에 넣으면 Hitomi-Downloader 에서도 Sankaku 사이트의 유료 이미지들이 다운로드가 가능할까요?
일단 유료 요금제를 결제하지 않는 상태에선 해당 이미지들만 다운로드가 막히는 것 같습니다

**Comment by KurtBestor** [comment]
플러스 결제한 계정의 쿠키를 프로그램에 넣으면 플러스 이미지도 다운로드 가능해요.

**Comment by nikin78** [comment]
답변 감사합니다
