### ISSUE TITLE
뉴토끼에서 일부 만화가 다운로드 되지 않습니다.

### ISSUE THREAD

**Issue by inspection96** [KurtBestor/Hitomi-Downloader#2860]
존경하는 KurtBestor 선생님 안녕하십니까

다름이 아니라 뉴토끼라는 마나토끼 대체 사이트에서 일부 만화들이 아래와 같은 오류로 다운로드가 되질 않아 글 남겨 봅니다.

코로나 조심하시구 항상 건강하시길 기원합니다.

PS. 혹시 몰라 가장 최근의 버전(테스트버전 포함)에서도 테스트를 해보았으나 동일한 문제가 발견되었습니다.

------------------------------------------------------------------------------------------------------------------------------------
Browser required; Use --safemode: https://newtoki91.com/webtoon/9624651/%EA%B3%A0%ED%96%A5-%EC%B2%98%EC%9E%90%EB%93%A4

version: 3.2b (20-12-10 00:57:22 UTC)
platform: Windows-10-10.0.19041-SP0
order: 1
group: False
input: https://newtoki91.com/webtoon/9624651/%EA%B3%A0%ED%96%A5-%EC%B2%98%EC%9E%90%EB%93%A4
dir: 
zip: 
type: manatoki
artist: None
url: https://newtoki91.com/webtoon/9624651/%EA%B3%A0%ED%96%A5-%EC%B2%98%EC%9E%90%EB%93%A4
valid: False
done: True
range: None
range_p: None
single: False
time: 1608215614.2575562 (Dec 17)
tags: []
goodbyedpi: False
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: None

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1020, in start
File "<decorator-gen-84>", line 2, in init
File "constants", line 833, in wrapper
File "constants", line 804, in wrapper
File "extractor\manatoki_downloader", line 39, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 111, in get_soup
File "clf2", line 34, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://newtoki91.com/webtoon/9624651/%EA%B3%A0%ED%96%A5-%EC%B2%98%EC%9E%90%EB%93%A4 (79.9s)

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2843
