### ISSUE TITLE
혹시 검색기 기능에서 페이지수 필터를 추가해주실수있을까요?

### ISSUE THREAD

**Issue by hjsg1010** [KurtBestor/Hitomi-Downloader#2865]
혹시 검색기 기능에서 페이지수 필터를 추가해주실수있을까요?

예를들면 100p이상만 본다던가..

요새 검색기 기능으로만 서칭하는데 제가 단행본충이라..ㅋㅋ;

페이지 수를 필터로 넣으면 정말 좋을거같아서요..

항상 좋은 프로그램 제공해주셔서 감사합니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/178

**Comment by hjsg1010** [comment]
> 참고해주세요: #178

감사합니다!

**Comment by hjsg1010** [comment]
답변 완료
