### ISSUE TITLE
3.2 버전에서 다운이 안 됩니다.-사용자 이름 한글 사용 중

### ISSUE THREAD

**Issue by boosubim** [KurtBestor/Hitomi-Downloader#2881]
3.1 버전에서는 마나토끼 등이 제대로 다운로드 되는데, 3.2* 버전들(3.2c 포함)에서는 빨간글씨가 되면서 다운이 되지 않습니다.
윈도우7, 윈도우10 모두 마찬가지입니다. 윈도우7과 윈도우10 모두 사용자 이름을 본명으로 써서 한글로 되어 있습니다.
비슷한 이슈(사용자 이름이 한글로 되어 있는 컴퓨터에서 3.2 버전 오류) 글에 링크된 테스트 버전을 써도 마찬가지입니다.

참고로 사용자 이름이 영어로 되어 있는 컴퓨터에서 잠시 써봤는데, 여기서는 3.2*버전이 정상적으로 됩니다.
그렇다고 컴퓨터 사용자 이름을 바꿀 수도 없어 답답합니다.

아래가 작업정보에 있는 내용입니다.
 
![image](https://user-images.githubusercontent.com/76654998/103174035-2950e000-48a2-11eb-9cdf-de26249b35dc.png)

Browser required; Use --safemode: https://manatoki91.net/comic/6339921

version: 3.2c (20-12-27 08:24:35 UTC)
platform: Windows-10-10.0.19041-SP0
order: 0
group: False
input: https://manatoki91.net/comic/6339921
dir: 
zip: 
type: manatoki
artist: None
url: https://manatoki91.net/comic/6339921
valid: False
done: True
range: None
range_p: None
single: False
time: 1609080236.999986 (Dec 27)
tags: []
goodbyedpi: True
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
ytdl: 2020.12.26

[Gallery]
None

[File Names]

[URLs]

[Messages]

stop
Traceback (most recent call last):
File "utils", line 1051, in start
File "<decorator-gen-86>", line 2, in init
File "constants", line 869, in wrapper
File "constants", line 840, in wrapper
File "extractor\manatoki_downloader", line 37, in init
File "ratelimit\decorators", line 113, in wrapper
File "ratelimit\decorators", line 80, in wrapper
File "extractor\manatoki_downloader", line 109, in get_soup
File "clf2", line 34, in solve
errors.BrowserRequired

Invalid: fail=False
EOT: https://manatoki91.net/comic/6339921 (10.0s)

**Comment by assstone** [comment]
저도 같은 증상입니다. 그리고 컴퓨터 이름과 계정까지 모두 영어로 바꿨는데도 다운이 안 됩니다.
고급설정의 내장 웹 브라우저가 아예 꺼져 있습니다. 
물론 3.1 에서는 잘 되고요.

**Comment by boosubim** [comment]
한글 사용자명의 윈도우7과 윈도우10에서는 3.1은 되고 3.2*는 안 되는데, 처음부터 영어 사용자명으로 되어 있는 윈도우10에서는 3.2*가 잘 되었습니다.
그런데 asstone님 글을 보니 컴퓨터 이름이 한글로 되어 있는 상태에서 영어로 바꾸는 것은 3.2* 버전에 소용 없는 모양이군요.

3.1 버전이 불완전해서 3.2 버전으로 바꾸고 싶기에 이 문제가 빨리 해결되기를 기다리고 있는 중입니다.

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/2843
