### ISSUE TITLE
트위터가 3.2c패치이후 또 다운받는 범위가 줄어들엇습니다.

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#2893]
3,2b패치이후로 오래된 트윗이라도 삭제만 안되면 미디어파일이 다운받아졋는데

3.2c패치가 생긴이후 3.2b에서 트위터 다운을 받으면 미디어 파일 다운받는 범위가 줄어들어집니다.

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3216
