### ISSUE TITLE
만화들을 한 번에 바꿨으면 좋겠습니다.

### ISSUE THREAD

**Issue by mac22222** [KurtBestor/Hitomi-Downloader#2896]
개편으로 인해서 xxx.yyy.com -> xxx1.yyy.com 할 때
저는 한 번에 하나씩 하고 있는데,
여러개가 묶어서 xxx.yyy.com -> xxx1.yyy.com 를 하고 싶어요...
개발자님 도와주세요~~

**Comment by alskdh** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/releases/download/Utils/replace_urls.hds 이 스크립트로 쓰고 있었는데 최근 업데이트 후에 안되서 개발자님께 리폿 했어요

**Comment by mac22222** [comment]
아 있군요..ㅋ
살펴보니까 표시만 (메인)그렇고 내용(스트립트)은 바꿨어요.. 감사합니다..
