### ISSUE TITLE
 제이마나 같은 사이트 압축을 각화별로 압축하게 해주시면 감사하겠습니다

### ISSUE THREAD

**Issue by ditmdhaos** [KurtBestor/Hitomi-Downloader#2898]
1~30권짜리 만화를 압축상태로 다운받으면
1권.zip, 2권.zip ... 30권.zip 이런식으로 압축될수있게요

지금은 1~30권.zip로 압축되서 조금 아쉽습니다

**Comment by mac22222** [comment]
개발자님이 안하신다고 말씀하셨어요..
