### ISSUE TITLE
픽시브 파일 폴더 이름 바꾸는 법을 알고 싶습니다.

### ISSUE THREAD

**Issue by hanjungee01** [KurtBestor/Hitomi-Downloader#2919]
픽시브 파일 폴더 이름에서 ID 부분의 괄호 안에 pixiv_가 들어가는데 저 pixiv_를 제거하고 싶습니다.
그런데 기본으로 제공되는 어떤 양식으로도 저 pixiv_가 제거가 되지 않는군요.
따로 없앨 수 있는 방법이 없을까요?
예전까지 다운 받아두었던 픽시브 파일 폴더(6500개 정도)와 호환이 안 되는 문제가 있어서 그럽니다.

**Comment by KurtBestor** [comment]
폴더명 형식을 하나로 통일해야할 이유가 있나요?

**Comment by hanjungee01** [comment]
알겠습니다 기존에 쓰던 프로그램 쓰겠습니다 감사합니다.

**Comment by KurtBestor** [comment]
이유를 물어본건데요
