### ISSUE TITLE
스크립트를 이용해서 작가명 등의 정보를 가져올 수 있나요?

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#2932]
올려주신 예시 스크립트 중에 hook_rename 이라는 스크립트를 사용하고자 합니다.

일부 사이트(iwara 등) 에서는 artist  이름이 폴더명(파일명)에 반영되지 않아 스크립트를 작성해보려 하였는데, 특정 변수명이나 API 등이 있는지 여쭤보고 싶습니다.
없다면 html 태그 등에서 가져온 값을 넣을 수 있는지 (그러니까 해당 파일을 다운받은 경로를 hook_rename에서 받아볼 수 있는지) 알려주시면 좋겠습니다.

항상 감사합니다.

**Comment by KurtBestor** [comment]
새로운 예제 추가했어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts#hooks

그런데 Iwara 는 artist 이름 따로 설정하지 않아서 `[None]` 으로 표기될거예요.

조금 수정해서 Python 스크립트로 HTTP 요청해서 파싱해서 넣을 수도 있어요.

**Comment by lakals** [comment]
라이브러리(BeautifulSoup) 를 이용해서 아티스트 이름 파싱하는 코드는 짰는데, 스크립트에서 해당 라이브러리를 import할 방법을 잘 모르겠네요...ㅠㅠ
단순하게 해당 코드를 스크립트에 넣으면 에러가 납니다. 파이참으로 스크립트를 열어서 라이브러리 인스톨 해봤는데 그렇게는 안 되는군요...


from urllib.request import Request, urlopen
from bs4 import BeautifulSoup

def find_artist_name(pageUrl):

    req = Request(pageUrl)
    res = urlopen(req)
    html = res.read().decode('utf-8')

    bs = BeautifulSoup(html, 'html.parser')
    tags = bs.findAll('a', attrs={'class': 'username'})

    artistTag = tags[0]
    return artistTag.text


이걸 어떻게 사용할 수 있을까요?
아니면 혹시 내부적으로 html 파싱된 데이터가 있나요?

**Comment by lakals** [comment]
로그를 찍어 보니 cw.gal_num 이 url 인 것 같아서(변수명이 미묘해서 맞는지 긴가민가하네요) 그 방식으로 구현했습니다.
일단 몇가지 테스트해본 것으로는 정상적으로 작동되네요. 좋은 프로그램을 만들어 주셔서 감사합니다.

혹시 여유가 되신다면 다음 업데이트에서 추가해주신다면 감사하겠습니다.

[hook_iwara_artist.zip](https://github.com/KurtBestor/Hitomi-Downloader/files/5802155/hook_iwara_artist.zip)

**Comment by KurtBestor** [comment]
`cw.url` 이 URL 이고, `cw.type` 이 사이트 타입이에요.

조금 고쳤어요: [hook_iwara_artist.zip](https://github.com/KurtBestor/Hitomi-Downloader/files/5802733/hook_iwara_artist.zip)

다른 사이트들도 채널명을 적지 않기 때문에 프로그램에는 넣지 않으려고 해요.

**Comment by lakals** [comment]
잘 사용하겠습니다! 항상 감사드려요
