### ISSUE TITLE
폰헙 다운 오류

### ISSUE THREAD

**Issue by jong6918** [KurtBestor/Hitomi-Downloader#2939]
밑에글꺼 테스트로해보니까 개별 다운은 되는데

사용자별 비디오 전체 다운은 안됩니다

수정 : 이게 여러개 시도해보니까 아예 새 영상들이 다운이 안되는게 아니라 마지막 영상 하나씩만 다운이 안되네요. 저만 나타나는현상인가

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by jong6918** [comment]
ㅇㅇ 해결됐네요 감사합니다

**Comment by hyunwook630** [comment]
폰헙 지금 다운로드가 불가능합니다. 개별 다운로드도 불가능한 것 같습니다. 확인 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
@hyunwook630 테스트해봤는데 잘 되네요
