### ISSUE TITLE
safemode로 켜지지 않습니다.

### ISSUE THREAD

**Issue by azf1664** [KurtBestor/Hitomi-Downloader#2940]
뉴토끼를 다운받아보려고 했더니 safemode로 켜야한다고 하더라구요.
그래서 여기 써놓으신 방법대로 테스트버전을 받아서 cmd로  safemode에 접속을 했더니 에러가 뜨면서 켜지지 않습니다...
해결 방법을 알고 계신다면 부디 알려주십시오... ㅜㅜ
![제목 없음](https://user-images.githubusercontent.com/51169720/103893404-9f6e0600-5130-11eb-82fa-093a0f36951a.png)

**Comment by KurtBestor** [comment]
`hitomi_downloader_GUI.exe --safemode --debug` 로 실행한 다음 생긴 `debug.txt` 보내주시면 분석해볼게요.

**Comment by azf1664** [comment]
[debug.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5786229/debug.txt)
여기 있습니다 선생님!

**Comment by KurtBestor** [comment]
`--safemode` 없이 켜도 똑같나요?

**Comment by azf1664** [comment]
그냥 켜면 정상적으로 켜집니다.

**Comment by KurtBestor** [comment]
`--safemode` 없이 켜진 상태에서 <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>C</kbd> 눌러서 콘솔 열고 다음 입력하고 <kbd>Enter</kbd> 눌러서 나온 내용 보여주세요:
```
__import__('importlib').resources.path('certifi', 'cacert.pem').__enter__()
```

**Comment by azf1664** [comment]
![제목 없음](https://user-images.githubusercontent.com/51169720/104120727-66c26c80-537c-11eb-8b50-d5e5e98ba8dd.png)
이렇게 나옵니다

**Comment by KurtBestor** [comment]
지금 cmd 실행한 경로가 `C:\Users\가족` 으로 되어있는데
실행파일 경로로 탐색기 들어가서 주소창에 `cmd` 입력하고 뜨는 cmd에서 다음과 같이 입력하고 <kbd>Enter</kbd> 누르세요:
```
hitomi_downloader_GUI.exe --safemode
```

**Comment by KurtBestor** [comment]
실행파일 C 드라이브로 옮겨서 실행해도 같나요?

**Comment by azf1664** [comment]
c드라이브로 옮겼더니 됩니다!!! 감사합니다!!!!!!!
