### ISSUE TITLE
밑에분이랑 비슷한의견 기능추가 건의드립니다.

### ISSUE THREAD

**Issue by ahruddid2** [KurtBestor/Hitomi-Downloader#2945]
....

**Comment by erebuseyny** [comment]
저도 작업-새 그룹 만들기. 
필터기능으로 검색 후, 
생성한 그룹에
작가나 완결여부를 기준으로 옮겨넣었는데...
최근에 필터기능을 켜면, 목록이동이 되지 않도록 업데이트 됨..OTL

**Comment by KurtBestor** [comment]
@erebuseyny 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2813
