### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by tom0034** [KurtBestor/Hitomi-Downloader#2950]
When download manga from lovehug (https://lovehug.net/801/) using technical preview (build 2021.01.08), it gives out OSError: [Errno 22] Invalid argument.

Here is a part of the error

> Fail : \\?\D:\hitomi\hitomi_downloaded_lhscan\DAIGAKU-CHAN x HIGH SCHOOL - RAW\DAIGAKU-CHAN xHIGH SCHOOL - RAW\Chapter 11\0014.jpg
Traceback (most recent call last):
File "downloader", line 867, in download
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\hitomi\\hitomi_downloaded_lhscan\\DAIGAKU-CHAN x HIGH SCHOOL - RAW\\DAIGAKU-CHAN x\x08HIGH SCHOOL - RAW\\Chapter 11\\0014.jpg'

I suspect it is the "x" in "DAIGAKU-CHAN × HIGH SCHOOL" that causing this problem, since it is not a valid english letter.
Maybe replacing the invalid letter with white space should fix the problem?

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tom0034** [comment]
Thanks for the quick fix!
I've tested it with ~500 download task, no such error happen again.
Thanks for your hard work!
