### ISSUE TITLE
(lovehug.net) manga exist on the website, but cannot download with hitomi

### ISSUE THREAD

**Issue by tom0034** [KurtBestor/Hitomi-Downloader#2962]
Hitomi version: Technical Preview build 2021.01.10

Example manga 1:
- link: https://lovehug.net/96/
- error quote: 
> Fail : \\?\D:\hitomi_2021.01.10\hitomi_downloaded_lhscan\DAYS - RAW\Chapter 202\0015.jpg
Traceback (most recent call last):
File "downloader", line 854, in download
Exception: 403
- full log: https://pastebin.pl/view/6b774a4f

Example manga 2:
- link: https://lovehug.net/226/
- error quote: 
> Fail : \\?\D:\hitomi_2021.01.10\hitomi_downloaded_lhscan\TOMODACHI TO SHITE DAISUKI - RAW\Chapter 1\0011.jpg
Traceback (most recent call last):
File "downloader", line 854, in download
Exception: 403
- full log: https://pastebin.com/kSqMnEpu

Both manga can view from its website, but cannot download using hitomi.

**Comment by tom0034** [comment]
more example
https://lovehug.net/348/
https://lovehug.net/335/

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/104300912-6657dc00-550a-11eb-8f7a-8cf291de2737.png)

Can't reproduce

**Comment by tom0034** [comment]
ok it seems to have some ip related issue.
I use korea ip (nordvpn -  South Korea #43 server 210.217.18.76), it successfully downloaded the abovementioned manga.
While my own ip (hong kong) cannot.

Thanks for your help though!
