### ISSUE TITLE
Considerations for English Users

### ISSUE THREAD

**Issue by hl2guide** [KurtBestor/Hitomi-Downloader#2965]
Please consider a clean up for the UI for English users.

Currently if I set the download folder for YouTube I get:

`C:\Downloads`

displaying the \ as a W with a horizonal line through it.

I suspect that's meaningful for Japanese users but it's confusing for everyone else.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hl2guide** [comment]
ok thanks 👍
