### ISSUE TITLE
스크롤 설정 개발 예정사항에 포함중이신지 여쭤보고싶습니다

### ISSUE THREAD

**Issue by spread5789** [KurtBestor/Hitomi-Downloader#2972]
목록에서 1회 스크롤 시 많은양이 스크롤다운 되어서 줄이고싶은데
윈도우 설정은 전역설정이라 모든 프로그램들의 스크롤 횟수가 감소되는 단점때문에
해당 프로그램만 변경할 수 있는 기능을 개발 사항에 포함 생각중이신지 여쭤보고싶습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

`옵션` - `설정` - `고급 설정` - `스크롤 속도` 에서 설정할 수 있어요.

**Comment by spread5789** [comment]
짧은시간에 편의성기능을 넣어주셔서 감사합니다.
