### ISSUE TITLE
토렌트에 관하여 질문이 있습니다.

### ISSUE THREAD

**Issue by ahruddid2** [KurtBestor/Hitomi-Downloader#2974]
다른분 토렌트 질문관련글을 봤습니다

토렌트 받을때만 업로드를 하고 다운을 다 받으면 업로드는 중단된다고 하셨는데..

따로 확인하는 방법이 있는지궁금합니다.

다운로드 받을때 어떤임시저장폴더에서 토렌트파일 저장과 동시에 업로드중 같은거요.

다운로드부분은 표시가 뜨는데 업로드부분도 혹시 확인할수있는방법이 있나요?

실시간으로 업로드 데이터 전송속도를 볼수가없어서 모든작업을 중단후에 

작업관리자(네트워크사용율)를 통해서 확인을 하긴하거든요.. 

작업관리자를 관찰해보면 토렌트파일 다운로드후 네트워크 사용율이 없어서 업로드는 하지않게 제대로 작동은 하고 있는거같은데

작업관리자말고 다운로드시 직접적으로 업로드를 공유하고 있는 파일폴더나? 그런 경로를 알수잇을까요? 

보통 U토렌트는 appdata 폴더에 시드가 남잖아요. 히토미 다운로더는 어떤방식인지 알려주시면 감사하겠습니다.

귀찮게해드려서 죄송해요 . 컴맹이라 ㅠㅠ

항상 업데이트 신경써주셔서 감사합니다. 새해복 많이받으세요 ^^

**Comment by KurtBestor** [comment]
다음과 같아요:
- 대기 중: 아무것도 안 함
- 다운로드 중: 다운로드 & 업로드
- 다운로드 완료 후: 아무것도 안 함
- 임시 파일: 없음

공유 폴더가 뭘 의미하는진 모르겠는데 다운로드 완료된 파일 조각 중에 요청이 있으면 업로드하는 거예요.

**Comment by ahruddid2** [comment]
답변감사합니다.
