### ISSUE TITLE
유튜브 재생목록 영상으로 다운로드시 번호를 붙일 순 없을까요?

### ISSUE THREAD

**Issue by spread5789** [KurtBestor/Hitomi-Downloader#2979]
[#1444](https://github.com/KurtBestor/Hitomi-Downloader/issues/1444) 

와 같은 내용인데..

라벨 달아놓으신 것 보니 기능은 있는 듯 한데 키워드를 알 수 없군요...
파이썬은 할 줄 모르는지라 여쭙습니다

**Comment by KurtBestor** [comment]
고려해봤는데, 순서가 조금만 바뀌어도 파일명이 바뀌어서 재생목록을 업데이트할 때 문제가 생겨서 넣지 않기로 했어요.
