### ISSUE TITLE
폰허브 썸네일, 동영상 지연 문제 보고

### ISSUE THREAD

**Issue by santory1** [KurtBestor/Hitomi-Downloader#2981]
항상 감사하게 잘 쓰고 있습니다.
v3.2b 까지는 파일에 썸네일이 자동으로 저장되고, 동영상에서 지연문제가 발생하지 않았는데
v3.2c 이후 버전부터는 다운로드 창 안에서 썸네일은 나오지만 파일 저장시에 썸네일이 저장되어 있지 않고,
         동영상을 틀어서 시간대를 옮기면 오디오는 바로 나오는데 영상은 2, 3초 정도 있다가 나옵니다.
물론 다운로드 받아지는 것만 해도 너무 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
