### ISSUE TITLE
사이트 추가 건의드립니다.

### ISSUE THREAD

**Issue by killeric** [KurtBestor/Hitomi-Downloader#3019]
https://tkor.mom/

웹툰/만화/동인지 등등 많아서 추가 건의드려봅니다.

**Comment by fpvmflzk** [comment]
이미 있습니다. 스크립트 다운로드 하셔서 도구탭에서 스크립트 가져오기로 추가하면 정상적으로 돼요

[https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts](url)

**Comment by killeric** [comment]
> 이미 있습니다. 아래링크에서 스크립트 다운로드 하셔서 도구탭에서 스크립트 가져오기로 추가하면 정상적으로 돼요
> 
> https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts

감사합니다!
