### ISSUE TITLE
실행할 때 저장된 설정 없다고 나옵니다

### ISSUE THREAD

**Issue by kndol** [KurtBestor/Hitomi-Downloader#3022]
테크니컬 프리뷰 최신 버전 사용 중인데, 실행할 때마다 저장된 설정이 없다고 나오네요.

하지만, 설정에 들어가 보면 설정 값을 제대로 불러온 것을 볼 수 있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by kndol** [comment]
고쳐졌습니다.
