### ISSUE TITLE
썸네일 유지 옵션 건의

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3073]
작업창에서 마음에 드는 이미지를 썸네일로 선택할수 있는 기능이 유용한데

새로운 이미지를 받으려고 작업을 다시 시작하면 이전에 선택한 썸네일이

가장 최근 다운받은 이미지로 변경이 되어 조금 불편한 면이 있습니다.

작업을 다시 시작해도 이전 썸네일을 유지하도록 옵션 추가가능한지 건의드려봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
잘 작동하는것 확인하였습니다!
