### ISSUE TITLE
트위터 미디어가 2000장까지만 다운이 됩니다.

### ISSUE THREAD

**Issue by jaejunghan** [KurtBestor/Hitomi-Downloader#3076]
[FASDFDSFW.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/5942109/FASDFDSFW.txt)

작업설정에 들어가서 페이지 제한돼있는것도 껏는데 이럽니다.

페이지제한 2000장까지 다운받도록 설정을 안햇음에도 이러네요

**Comment by jaejunghan** [comment]
전에 다운 받아봤던 트위터 주소라서 2천장 넘는것을 확실히 아는데, 2000장만 다운이 됩니다. 그래서 해당 주소만 이런가했는데, 다른 트위터도 마찬가지로 2000장까지만 다운로드가 됩니다

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3216
