### ISSUE TITLE
pixiv.net Stopped Working

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader#3085]
Hello, pixiv.net stopped working, I'm unable to download pictures because I can't login through Hitomi Downloader anymore, it's giving me an error, this issue started happening recently (today or yesterday), hopefully it gets fixed.

Thanks!

**Comment by Hyoros** [comment]
@xZabuzax   Happened to me before but first a preliminary question: Does your password use smallcase, uppercase and number?

**Comment by xZabuzax** [comment]
> @xZabuzax Happened to me before but first a preliminary question: Does your password use smallcase, uppercase and number?

My password doesn't use smallcase, uppercase and number, it uses symbols instead, the symbols are:     - and !

**Comment by Hyoros** [comment]
First a disclaimer: I’m a fellow user like you. This method worked the last December but it doesn’t work now.  so this app also doesn’t work for me. 
Go to 
https://accounts.pixiv.net/password/change?success=1
and re-enter your password
last time this happen I paste the error code and look to another pixiv downloader to see if they experience the same thing. The explanation is Pixiv change something to retrieve verification so they need to read that password change cookie in your computer. Again, this doesn’t work now.

**Comment by xZabuzax** [comment]
> First a disclaimer: I’m a fellow user like you. This method worked the last December but it doesn’t work now. so this app also doesn’t work for me.
> Go to
> https://accounts.pixiv.net/password/change?success=1
> and re-enter your password
> last time this happen I paste the error code and look to another pixiv downloader to see if they experience the same thing. The explanation is Pixiv change something to retrieve verification so they need to read that "password change" cookie in your computer. Again, this doesn’t work now.

I've tried it and it didn't work. Thanks anyways.

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/issues/3083#issuecomment-776586524

**Comment by bostafu2006** [comment]
> 
> 
> First a disclaimer: I’m a fellow user like you. This method worked the last December but it doesn’t work now. so this app also doesn’t work for me.
> Go to
> https://accounts.pixiv.net/password/change?success=1
> and re-enter your password
> last time this happen I paste the error code and look to another pixiv downloader to see if they experience the same thing. The explanation is Pixiv change something to retrieve verification so they need to read that "password change" cookie in your computer. Again, this doesn’t work now.
> 
> EDIT: 12 February the fix work. Thank you @KurtBestor

Hi ! so you succeed ? And it works ? Can you give more details please for a noob like me :) 

I think I missed a step somewhere because I can't find the "callback..." line ? It doesn't appear in my log in :(

Thank you for your help

**Comment by xZabuzax** [comment]
> Hi ! so you succeed ? And it works ? Can you give more details please for a noob like me :)
> 
> I think I missed a step somewhere because I can't find the "callback..." line ? It doesn't appear in my log in :(
> 
> Thank you for your help

The fix is located here: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Download the new version which contains the fix using another method to login through **Pixiv**, the new method involves using "**Cookies**" from your Browser. You need to install an extension in your Browser that allows you to get the "**Cookie**" from a website like **Pixiv**, once you have the "**Cookie**" file you will simply locate and open it through **Hitomi Downloader** and it will start working again.

**Hitomi Downloader** will explain you how to use the new "**Cookies**" method, it's pretty straight forward and easy, try to download a picture from **Pixiv** and once it fails it will explain you what you need to do.

Note: If you use the **Opera** browser (like I do) then you need to install first an extension called "**Install Chrome Extensions**" which allows you to install in **Opera** extensions developed for the **Chrome** browser.

**Comment by bostafu2006** [comment]
> 
> 
> > Hi ! so you succeed ? And it works ? Can you give more details please for a noob like me :)
> > I think I missed a step somewhere because I can't find the "callback..." line ? It doesn't appear in my log in :(
> > Thank you for your help
> 
> The fix is located here: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> Download the new version which contains the fix using another method to login through **Pixiv**, the new method involves using "**Cookies**" from your Browser. You need to install an extension in your Browser that allows you to get the "**Cookie**" from a website like **Pixiv**, once you have the "**Cookie**" file you will simply locate and open it through **Hitomi Downloader** and it will start working again.
> 
> **Hitomi Downloader** will explain you how to use the new "**Cookies**" method, it's pretty straight forward and easy, try to download a picture from **Pixiv** and once it fails it will explain you what you need to do.
> 
> Note: If you use the **Opera** browser (like I do) then you need to install first an extension called "**Install Chrome Extensions**" which allows you to install in **Opera** extensions developed for the **Chrome** browser.

Thank you for your reply ! It works at last :)

**Comment by xZabuzax** [comment]
Since it was fixed in the latest version I guess I will close this thread.

Thanks for your hard work KurtBestor, keep it up!
