### ISSUE TITLE
twitter_ 로 다운받기 작동 안 함

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3092]
예전엔 twitter_아이디 로 다운 가능했는데 최근 버전에서는 에러가 뜹니다.

twitter.com/아이디 이렇게 다운 받는건 가능합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
잘 작동하는것 확인하였습니다!
