### ISSUE TITLE
pixiv login error

### ISSUE THREAD

**Issue by desoftuni** [KurtBestor/Hitomi-Downloader#3134]
The app shows me a wrong credential message when I try to log in to my pixiv account. I tested my credentials on the page and it works. Does anyone know what's going on?
![Captura de pantalla 2021-02-20 011817](https://user-images.githubusercontent.com/58457048/108614883-0df6e280-73c4-11eb-8535-de5157c040a1.png)

**Comment by dimolto312** [comment]
Pixiv api is changed.
You need to update program to Technical Preview version.
[https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview) 
+ Pixiv download system is changed to using cookie.

**Comment by desoftuni** [comment]
Thanks a lot!.
