### ISSUE TITLE
invalid 작업을 자동으로 재시작하는 옵션을 추가해 주실 수 있을까요?

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#3140]
고급 옵션 중에 '불완전한 작업 자동으로 다시 시작' 옵션이 있습니다.
그런데 이 옵션의 경우 INVALID 가 나온 경우 재시작하지 않는 것 같습니다.

iwara 등 일부 사이트의 경우, 올바른 주소임에도 서버 문제 등으로 한번에 연결되지 않는 경우가 종종 있습니다.
실패했을 때 여러번 시도하다 보면 연결됩니다.

invalid 한 작업 또한 재시도할 수 있는 옵션이 있으면 좋겠습니다.
만약 이 기능이 스크립트로 가능하다면 알려주시면 감사하겠습니다.

항상 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by lakals** [comment]
잘 작동합니다! 감사합니다.
