### ISSUE TITLE
내장 웹브라우저 질문드립니다.

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3147]
내장 브라우저가 어떤 방식으로 구현되었고, 
어떻게 사용하는지 궁금합니다.

**Comment by KurtBestor** [comment]
[QtWebEngine](https://wiki.qt.io/QtWebEngine) 으로 구현되었고 주로 봇 감지 우회나 자바스크립트 렌더링을 위해 쓰여요.
