### ISSUE TITLE
사운드클라우드 관련입니다 죄송하지만 한번만 봐주세요

### ISSUE THREAD

**Issue by BOXHED1999** [KurtBestor/Hitomi-Downloader#3149]
사운드 클라우드 다운로드 하는데 작곡가분께서 묶음으로 올려두는 음악은 다운이 잘 안되는 것 같습니다.

낱개로는 다운로드가 잘 되는데 느낌표로 멈추거나 다운로드가 안되있는 걸 모면 거의 묶음으로 올려놓은 것들이더라고요. 어떤건 되는거같기도 하는데 어떤건 잘 안되기도 하고.

https://soundcloud.com/nathan-yu-38155546

이렇게 묶음으로만 놓으신 작곡가분도 계시는데 이런건 아예 다운이 안되는 것 같더라고요.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/109371465-652b1480-78e8-11eb-9865-334178a3899e.png)

트랙이 하나도 없는 유저네요

**Comment by BOXHED1999** [comment]
죄송합니다 제가 사운드클라우드를 이번에 접하는거라 잘 알지도 못하고 글을 썼군요...
번거롭게 해서 죄송합니다

**Comment by BOXHED1999** [comment]
제가 사운드클라우드를 이번에 접해서 잘 몰랐습니다... 번거롭게 해서 죄송합니다
