### ISSUE TITLE
내장 웹브라우저 예제

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3152]
같은 주제로 두 번 이슈 올려드려서 죄송합니다.
내장 웹 브라우저를 이용해서 JS가 필요한 사이트에서 다운로드를 해보고 싶은데,
혹시 간단한 사용 예제를 알려주실 수 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/blob/9eb4d8ac47ba47dda57647ba8598957882bb34d3/src/extractor/manatoki_downloader.py#L109-L110
