### ISSUE TITLE
[lovehug] cannot retrieve manga title

### ISSUE THREAD

**Issue by tom0034** [KurtBestor/Hitomi-Downloader#3162]
hitomi version: Technical Preview 2021.02.27
test url: https://lovehug.net/1123/
log: https://pastebin.com/g5i2kjUh

manga title cannot capture by hitomi.

![image](https://user-images.githubusercontent.com/11575182/109411836-b4a03c00-79df-11eb-815e-84f436995e7a.png)
![image](https://user-images.githubusercontent.com/11575182/109411851-c97ccf80-79df-11eb-8761-81134d466709.png)
![image](https://user-images.githubusercontent.com/11575182/109411856-d0a3dd80-79df-11eb-9c2a-2b371571313f.png)
![image](https://user-images.githubusercontent.com/11575182/109411862-d7325500-79df-11eb-8bb9-e3ab0d2ef1a4.png)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tom0034** [comment]
it ok now, thank you very much!
