### ISSUE TITLE
특정 Tumblr에 대한 Invalid 이슈

### ISSUE THREAD

**Issue by tekken6598** [KurtBestor/Hitomi-Downloader#3163]
Kurt Bestor님께서 만드신 Hitomi-Downloader 감사히 사용하고 있습니다. 최근 업데이트로 인해 크롤링하던 특정 Tumblr 블로그에 대해 Invalid 이슈가 발생해 로그를 첨부하고자 합니다. 어느 버전부터인지는 모르지만 3.0 버전에서는 발생하지 않습니다. 본 프로그램 개발에 감사드립니다.

### Invalid: [tumblr] https://arerab.tumblr.com/

version: 3.3 (21-02-04 08:00:03 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a43bfd7c744f4cce98fdfdbc73242d0d
input: https://arerab.tumblr.com/
type: tumblr
single: False
url: https://arerab.tumblr.com
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1614518029.625482 (Feb 28)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: None
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
('141238863413', {'type': 'audio', 'provider': 'tumblr', 'url': None, 'embed_html': '<iframe class="tumblr_audio_player tumblr_audio_player_141238863413" src="https://arerab.tumblr.com/post/141238863413/audio_player_iframe/arerab/tumblr_o47wnxxEUV1upbmwf?audio_file=https%3A%2F%2Fa.tumblr.com%2Ftumblr_o47wnxxEUV1upbmwfo1.mp3" frameborder="0" allowtransparency="true" scrolling="no" width="540" height="85"></iframe>', 'media': {'url': 'https://a.tumblr.com/tumblr_o47wnxxEUV1upbmwfo1.mp3?play_key=e6ba8f023e92bbb5aaf06052cd0c6551', 'type': 'audio/mpeg'}})
stop
Traceback (most recent call last):
File "utils", line 1077, in start
File "utils", line 1120, in start_
File "extractor\tumblr_downloader", line 41, in read
File "extractor\tumblr_downloader", line 164, in get_imgs
File "extractor\tumblr_downloader", line 112, in posts
File "extractor\tumblr_downloader", line 149, in __init__
NotImplementedError: ('141238863413', {'type': 'audio', 'provider': 'tumblr', 'url': None, 'embed_html': '<iframe class="tumblr_audio_player tumblr_audio_player_141238863413" src="https://arerab.tumblr.com/post/141238863413/audio_player_iframe/arerab/tumblr_o47wnxxEUV1upbmwf?audio_file=https%3A%2F%2Fa.tumblr.com%2Ftumblr_o47wnxxEUV1upbmwfo1.mp3" frameborder="0" allowtransparency="true" scrolling="no" width="540" height="85"></iframe>', 'media': {'url': 'https://a.tumblr.com/tumblr_o47wnxxEUV1upbmwfo1.mp3?play_key=e6ba8f023e92bbb5aaf06052cd0c6551', 'type': 'audio/mpeg'}})

Invalid: fail=True
EOT: https://arerab.tumblr.com/ (29.4s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by tekken6598** [comment]
프리뷰와 3.3a 모두 동작 확인했습니다. 빠른 조치 감사합니다.
