### ISSUE TITLE
안티바이러스인 비트디펜더와 상성이 안맞는거같습니다.

### ISSUE THREAD

**Issue by boutoron2685** [KurtBestor/Hitomi-Downloader#3169]
비트디펜더 쪽에서 조금이라도 클라이언트와 관련된 상호작용이라도 하면, 하는 행동 마다(Releases된 클라이언트 압축파일풀기, 클라이언트 클릭하기, 바로가기 만들기, 실행 후 딜레이 등) 모니터링에 들어가는지 클라이언트와 관련된 파일들이 전부 응답없음에 들어갔었습니다. 최근에 백신알고리즘이 업데이트 되었는지 아예 클라이언트 권한을 차단을 시키는거같았습니다. (실행시 - Error creating child process! CreateProcessW:엑세스가 거부되었습니다.) 그럼에도 불구하고 안티바이러스가 클라이언트파일을 검역소로 보내지않아, 원인을 꽤나 찾기 힘들었습니다.

**Comment by KurtBestor** [comment]
백신 오진 문제는 해당 백신에 오진이라고 리포트 부탁드려요
