### ISSUE TITLE
사이트 스크립트 추가 요청드립니다

### ISSUE THREAD

**Issue by fpvmflzk** [KurtBestor/Hitomi-Downloader#3175]
http://www.mangago.me/

영어 사이트기는 하지만 국내 사이트에는 미업로드된 웹툰, 만화가 많이 업로드 되어있어 스크립트 추가를 간절히 요청드립니다.

한국 아이피를 막은것 같긴한데 vpn 활성화하면 충분히 우회가능해서 문의드립니다.

**Comment by KurtBestor** [comment]
사이트 죽었네요
