### ISSUE TITLE
중복 이미지 찾기에 해상도 정보 추가

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3180]
중복 이미지 찾기에 이미지 가로세로 사이즈(해상도) 정보도 추가되면 좋을것 같습니다.

현재 이미지 용량만 나와있는데, 이미지 압축률에 따라 용량이 높아도 오히려 해상도는 낮은 경우가 있어서 구분하는데 용이할것 같아 건의드려봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
감사합니다!
