### ISSUE TITLE
중복 이미지 찾기 알고리즘 개선

### ISSUE THREAD

**Issue by githitoman** [KurtBestor/Hitomi-Downloader#3181]
중복 이미지 찾기 동작시 사실상 거의 같은 이미지인데도 불구하고 중복되는 이미지를 찾지 못하는 경우가 많습니다. '비슷한 이미지 포함' 옵션을 켜도 마찬가지인데, 가능하다면 이미지가 중복되는 기준을 좀 더 폭넓게 잡을 수 있었으면 합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by githitoman** [comment]
감사합니다!
