### ISSUE TITLE
작업 표시줄에서 활성화 할 때랑 트레이에서 활성화 할 때랑 활성화 속도가 달라요.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#3190]
트레이는 메인 모니터 오른쪽 끝이다 보니까 가끔 작업 표시줄에 고정해 둔 바로 가기를 누르기도 하는데요.

트레이로 최소화되어 있는 상태지만 작업 표시줄 바로 가기로 활성화하면 창이 뜨는 데까지 8초 정도 걸리더라고요.

혹시 작업 표시줄의 바로 가기를 눌러도 즉각적으로 반응하게 할 수는 없을까 해서 글 남겨봅니다.

항상 고맙습니다.

**Comment by KurtBestor** [comment]
다음과 같은 차이가 있어서 발생하는 현상이에요:
- 트레이 아이콘 누름
 자기 자신을 활성화함
- 바로가기 누름
 프로그램이 켜지고 이미 실행된 프로그램에게 활성화하라고 알리고 꺼짐
