### ISSUE TITLE
제이마나 다운로드시 엉뚱한 이미지가 섞여서 다운 됩니다

### ISSUE THREAD

**Issue by Orange6539** [KurtBestor/Hitomi-Downloader#3192]
제이마나의 만화를 다운로드시
엉뚱한 만화가 중간중간 섞여서 다운됩니다

웹브라우저로 직접 볼때는 멀쩡하게 잘 나오는데
다운로더로 다운 받을때만 엉뚱한 이미지가 중간 중간 섞여서 다운로드 되더군요
그것도 특정 이미지만 반복적으로 항상 나옵니다;; (제 경우는 BL 비빔 짤이 자꾸... --)

확인 부탁드립니다

제가 확인한건 이 만화 입니다
https://jmana2.iipython.net/book?bookid=1268

통째로 다 다운 시키거나, 한 화별로 개별 다운로드 해도 동일하게 발생합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by saydeicide** [comment]
저도 같은 증상이 있어서 피드백 드리려고 했는데 일단 잘되는 것 같습니다.
테스트 url 은

https://jmana1.net/comic_list_title?bookname=%EB%A1%9C%EB%93%9C+%EC%97%98%EB%A9%9C%EB%A1%9C%EC%9D%B4+2%EC%84%B8%EC%9D%98+%EC%82%AC%EA%B1%B4%EB%B6%80

입니다.

**Comment by Orange6539** [comment]
네 수정된 버전으로 확인 한 결과 잘 작동함을 확인 하였습니다
빠른 수정 매우 감사드립니다

매번 신세를 지고 있고, 언제나 응원 하고 있습니다
감사합니다
