### ISSUE TITLE
픽시브 다운시에 길이가 긴 그림파일은 원본이 안 받아지고 섬네일 파일이 받아지는것 같습니다.

### ISSUE THREAD

**Issue by hugepaper** [KurtBestor/Hitomi-Downloader#3208]
뭔가 이상하다 싶어서 확대해보니 섬네일 파일인거 같네요.

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3174
