### ISSUE TITLE
니코니코동화 다운로드 오류

### ISSUE THREAD

**Issue by trol1** [KurtBestor/Hitomi-Downloader#3215]
Invalid: [nico] https://www.nicovideo.jp/watch/sm36525256

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / c5e596be6d57450eab75f26531ceea43
input: https://www.nicovideo.jp/watch/sm36525256
type: nico
single: True
url: https://www.nicovideo.jp/watch/sm36525256
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1615878949.7035444 (Mar 16)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
nico retry...
nico retry...
No active exception to reraise
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\nico_downloader", line 71, in read
File "extractor\nico_downloader", line 96, in get_video
RuntimeError: No active exception to reraise

Invalid: fail=True
EOT: https://www.nicovideo.jp/watch/sm36525256 (6.3s)

이런  오류가 발생하는데 해결 방법이 궁급합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by trol1** [comment]
잘 됩니다.
