### ISSUE TITLE
제이마나 다운로드가 안됩니다

### ISSUE THREAD

**Issue by Orange6539** [KurtBestor/Hitomi-Downloader#3223]
어제부터 제이마나 다운로드가 안됩니다
웹브라우저에서 확인해보면 만화 잘보이는걸 보면 이미지 서버가 뻗은건 아닙니다
쿠키신공? 이것도 해보았는데 동일합니다
통째로 받기+한화만 받기 전부 안됩니다

오류 메세지 첨부합니다
-------------------------------------------
4분 59초 뒤 다시 시작: https://jmana2.iipython.net/book?bookid=4079

version: 3.3a (21-03-07 06:19:16 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 9050397bf38c4a3ca5203e9d44811c83
input: https://jmana2.iipython.net/book?bookid=4079
type: jmana
single: False
url: https://jmana2.iipython.net/book?bookid=4079
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616054087.0135434 (Mar 18)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.14
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
no title
stop
Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1127, in start_
File "extractor\jmana_downloader", line 85, in read
File "extractor\jmana_downloader", line 79, in name
File "extractor\jmana_downloader", line 99, in get_title
File "ree", line 15, in find
ree.NotFound: no title

Invalid: fail=True
EOT: https://jmana2.iipython.net/book?bookid=4079 (2.2s)

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3220

**Comment by Orange6539** [comment]
해당 이슝;

> 참고해주세요: #3220

해당 버전으로 확인한 결과 잘 작동합니다
매번 매우 감사합니다
