### ISSUE TITLE
일본 만화 원본 사이트 추가 건의드립니다.

### ISSUE THREAD

**Issue by gembleman** [KurtBestor/Hitomi-Downloader#3230]
https://www.hentaishark.com/ 이란 곳인데 익헨이나 히토미 비슷한 사이트입니다.

**Comment by STR-HK** [comment]
[hentaishark 스크립트 링크](https://cdn.discordapp.com/attachments/679367647300943878/830428984339595274/hentaishark.hds)
문제 생기면 공식 디스코드로 말씀해주시면 감사하겠습니다.
