### ISSUE TITLE
마리망 다시 막힌듯 합니다.

### ISSUE THREAD

**Issue by fpvmflzk** [KurtBestor/Hitomi-Downloader#3247]
지난번 업데이트 해주신 이후로 내장 브라우저에서 캡차 풀면 잘되었는데 이제는 안되네요... 조속한 수정 부탁드리겠습니다

Invalid: [mrm] https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng

version: 3.3a (21-03-01 06:45:57 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 7a73bfe88cc24cd79559226d9aa4a220
input: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
type: mrm
single: False
url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1616771922.782309 (Mar 27)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.03.25
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
cf protection
no html
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
stop
Traceback (most recent call last):
File "downloader", line 293, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\mrm_downloader", line 70, in read
File "extractor\mrm_downloader", line 66, in name
File "extractor\mrm_downloader", line 60, in soup
File "extractor\mrm_downloader", line 54, in soup
File "extractor\mrm_downloader", line 183, in read_html
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng

Invalid: fail=True
EOT: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng (9.0s)

cf protection
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
stop
Traceback (most recent call last):
File "downloader", line 293, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\mrm_downloader", line 70, in read
File "extractor\mrm_downloader", line 66, in name
File "extractor\mrm_downloader", line 60, in soup
File "extractor\mrm_downloader", line 54, in soup
File "extractor\mrm_downloader", line 183, in read_html
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng

Invalid: fail=True
EOT: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng (6.2s)

cf protection
no html
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng
stop
Traceback (most recent call last):
File "downloader", line 293, in read_html
Exception: session

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "utils", line 1078, in start
File "utils", line 1123, in start_
File "extractor\mrm_downloader", line 70, in read
File "extractor\mrm_downloader", line 66, in name
File "extractor\mrm_downloader", line 60, in soup
File "extractor\mrm_downloader", line 54, in soup
File "extractor\mrm_downloader", line 183, in read_html
File "downloader", line 344, in read_html
File "requests\models", line 941, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng

Invalid: fail=True
EOT: https://myreadingmanga.info/sakyo-aya-kuroneko-kareshi-aishikata-eng (8.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

**Comment by fpvmflzk** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview

정상적으로 다운되네요 해결 감사합니다^^
