### ISSUE TITLE
문제, 버그 제보

### ISSUE THREAD

**Issue by 2fdd096f55** [KurtBestor/Hitomi-Downloader#3266]
1. 작업목록에서 제목순으로 정렬할때 숫자가 이상하게 정렬되는 현상
9, 100, 5000 이 있으면 9 100 5000순으로 정렬되어야 하는데 100 5000 9 순으로 정렬됩니다

2. 작업목록에서 필터기능 이용시 공백이 들어가면 인식하지 못하는 현상(tag:female:big breast)

3. 플로팅이미지(섬네일)가 나와있을때 휠 스크롤이 안되는 현상

4. 환경설정에서 박스에 커서가 닿은채로 휠 스크롤을 하면 옵션이 변하는 현상

![c1](https://user-images.githubusercontent.com/81782841/113364087-230b4d80-9342-11eb-9f26-f8f5ad0d8a0e.gif)

5. 우측 스크롤바에 커서가 닿은채로 휠 스크롤을 하면 엄청 느리게 스크롤되는 현상

스크롤바에 닿았을때 속도
![sc1](https://user-images.githubusercontent.com/81782841/113364095-29012e80-9342-11eb-937d-ecfea6048097.gif)

일반 속도
![sc2](https://user-images.githubusercontent.com/81782841/113364097-2acaf200-9342-11eb-9742-9f5efeffbee2.gif)

**Comment by KurtBestor** [comment]
1. 수정했어요.
2. `tag:female:big tag:breast` 또는 `tag:female:big_breast` 와 같이 입력해주세요. `tag:female:big breast` 는 태그 `female:big` 을 포함하고있고 `breast` 가 제목에 들어간 작업을 필터링해요.
3. 재현할 수가 없네요
4. 기본 동작이에요.
5. 4번과 마찬가지로 1픽셀 씩 이동하는 기본 동작이에요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 2fdd096f55** [comment]
감사합니다!
1. 정렬문제 잘 해결 되었습니다.
2. 말씀해주신대로 언더바를 사용하니 잘 검색되네요.
3. 표지 그림에 커서를 대면 나오는 미리보기 이미지(4장까지 설정 가능)가 떠 있을때 스크롤이 되지 않습니다.
