### ISSUE TITLE
편의성 기능 건의

### ISSUE THREAD

**Issue by 2fdd096f55** [KurtBestor/Hitomi-Downloader#3267]
작업목록을 기반으로 한 자체적인 탐색기/뷰어로 활용하고 싶은데 몇몇 아쉬운점이 있어서 건의드립니다.

1. 필터 즐겨찾기 기능 개선

![p1](https://user-images.githubusercontent.com/81782841/113364449-09b6d100-9343-11eb-88f2-c51373773480.png)
클릭전

![p2](https://user-images.githubusercontent.com/81782841/113364451-0ae7fe00-9343-11eb-88f8-bca51c7ec76e.png)
클릭후

현재 색 즐겨찾기가 있지만 파일 자체에 지정해줘야하므로 지속적으로 자료가 추가된다면 일일히 지정해야 하므로 번거롭습니다.
필터 자체를 즐겨찾기로 등록할 수 있다면 좋아하는 태그로 바로 검색 가능하니까 훨씬 편리할것같네요.

/
/
/
/
/

2. 작업목록 검색기처럼 표시(태그 등 표시)

![d1](https://user-images.githubusercontent.com/81782841/113364323-b2b0fc00-9342-11eb-8c74-0a424b87f43f.png)
목록으로 표시

![d2](https://user-images.githubusercontent.com/81782841/113364324-b3e22900-9342-11eb-894e-2712fe93392e.png)
아이콘으로 표시

검색기 UI가 가독성과 편의성이 훨씬 좋아서 건의드립니다.
덤으로 표시된 태그를 클릭했을때 필터에 자동으로 입력되면 이용하기 편리할것같아요.

/
/
/
/
/

3. 검색기 목록 다운로드 빠른실행 버튼

![d4](https://user-images.githubusercontent.com/81782841/113364468-1d623780-9343-11eb-88f7-d8c4d63521a3.png)

두번 누르는것보단 원버튼이 편합니다

/
/
/
/
/

4. 정렬시 오름차순, 내림차순 추가

![d3](https://user-images.githubusercontent.com/81782841/113364520-4b477c00-9343-11eb-83e5-10c16af23b23.png)

/
/
/
/
/

5. 작업 일괄추가 기능 개선

![d5](https://user-images.githubusercontent.com/81782841/113364553-5e5a4c00-9343-11eb-9830-d1a3519bc46b.png)

현재 루트폴더를 지정하면 폴더별로 지정되지 않고 루트폴더 한개만 등록됩니다.

새폴더\100
새폴더\200
새폴더\300

이렇게 있을때 새폴더를 지정하면 폴더별로 등록되지 않고 새폴더 작업 하나로 등록되고
작업을 각각 등록하고싶으면 100,200,300을 따로 선택해줘야하는데 번거로움이 너무 큽니다.
루트폴더 선택하면 하위폴더 폴더명으로 각각 작업이 등록되면 좋겠네요.

그리고 수동으로 따로 등록해줘도 info.txt파일이 반영되지 않아서 태그기능을 쓸수 없는데
info파일에서 정보를 읽어와서 검색기로 다운받을때처럼 자동으로 정보가 등록되었으면 좋겠어요.

**Comment by KurtBestor** [comment]
작업 일괄 추가는 여러 폴더 한번에 선택해서 등록할 수 있어요.
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/2116

**Comment by 2fdd096f55** [comment]
미처 몰랐네요. 알려주셔서 감사합니다.

**Comment by KurtBestor** [comment]
검색기 `메뉴` - `저장 폴더에 있는 모든 작가 불러오기` 누르고 검색한 다음 검색기 필터에 다음과 같이 입력하면 현재 다운로드한 작품만 검색돼요:
```
done:o
```

오름차순 / 내림차순 추가했어요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
