### ISSUE TITLE
한글자막 사이트 추가를 요청드립니다..

### ISSUE THREAD

**Issue by test6010** [KurtBestor/Hitomi-Downloader#3296]
정말로 많은 사이트들을 지원해주셔서 감사하게도 잘 사용중에 있습니다.

그 중 현재는 지원하지 않는, 
무려 영상에 한글자막이 들어가 있는 사이트가 있어 혹 추가가 될까 싶어 문의드립니다.

https://kr19.sogirl.co/

로써 한글자막이 있는 귀한 사이트입니다..

확인하시어 가능하시다면 부탁 좀 드리겠습니다

**Comment by STR-HK** [comment]
이미 존재해요. 위키 -> 스크립트 확인해보세요.

**Comment by test6010** [comment]
감사합니다. 제가 무지했네요 감사드려요!
