### ISSUE TITLE
다운로더 3.0b보다 최신 버전들이 실행이 되질 않습니다.

### ISSUE THREAD

**Issue by rebish** [KurtBestor/Hitomi-Downloader#3336]
좋은 프로그램 정말 감사합니다. 그런데 문제가 생겨서 질문을 하게 되었네요.
최신버전 다운로더들이 실행이 되질 않습니다.

윈도우 10 프로 버전 64bit 이고 오늘 새 컴퓨터로 바꿨습니다.
실행 파일을 더블클릭하면 작업 관리자 프로세스 창에는 hitomi downloader 두 개가 뜨는데 프로그램은 뜨지 않고, 잠시후 프로세스 창에서도 저 두개가 사라져버립니다.

이벤트뷰어로 보니 이렇게 써있네요

오류 있는 응용 프로그램 이름: hitomi_downloader_GUI.exe, 버전: 3.3.1.0, 타임스탬프: 0x600854e0
오류 있는 모듈 이름: unknown, 버전: 0.0.0.0, 타임스탬프: 0x00000000
예외 코드: 0xc0000005
오류 오프셋: 0x0000000000000000

이것도 있고

오류 버킷 1464840785733062138, 유형 5
이벤트 이름: BEX64
응답: 사용할 수 없음
Cab ID: 0

이것도 있습니다.

호환 모드도 바꿔보고 비쥬얼 C++도 다 깔아보고, 이것저것해봤는데 해결이 되지를 않네요.....

신기한건 3.0b 버전 아래부터는 실행하면 정상적으로 프로그램이 뜹니다. 그 위 버전들 하나하나 다해봤는데 똑같이 창이 뜨지 않습니다.
하지만 3.0b 버전은 옛 버전이라 그런지 다운로드가 되질 않더군요.
혹시 문제 해결해주실 수 있으신지요.....

**Comment by biue1230** [comment]
저도 위같은 증상과 같습니다 윈10 pro 64bit 20H2(OS 빌드 19042.1052) 사용중이고 
3700x cpu 쓰고있습니다.

3.0버전 위는 그냥 압축풀다가 99퍼에서 오랫동안 멈춰있고
풀려도 실행안되고 응답없음이 뜨며 지우는것도 한참 걸립니다.

또한 실행되는 버전으로 최신업데이트를 하면 응답없음이 뜨고 실행되지 않습니다.
