### ISSUE TITLE
즐겨찾기 기능 건의

### ISSUE THREAD

**Issue by 2fdd096f55** [KurtBestor/Hitomi-Downloader#3353]
오름차순, 내림차순 기능 추가해주셔서 감사합니다.

![image1](https://user-images.githubusercontent.com/81782841/116476682-14de1d80-a86b-11eb-9196-93ca75e9cf8e.png)
그림1

![image2](https://user-images.githubusercontent.com/81782841/116476676-13145a00-a86b-11eb-8800-1b20da5bf01b.png)
그림2

검색할때도 이 기능이 매우 편리했는데
그림처럼 다운목록에서도 즐겨찾기 기능이 생기면 좋겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 2fdd096f55** [comment]
감사합니다! 잘 작동하네요. 편의성도 더할나위 없습니다.
그런데 조건을 여러개 걸려면 어떤식으로 적어야하나요?
검색기에서는 쉼표(,)로 and, 더하기(+)로 or 조건을 사용했는데 여기는 구문 적용방식이 다른것같아요

**Comment by KurtBestor** [comment]
검색기 필터와 같이 조건 `A`, `B` 를 동시에 만족시키는 결과를 얻으려면 `A B` 입력하면 돼요

**Comment by 2fdd096f55** [comment]
잘 되네요. 정말 감사합니다!

![ssss](https://user-images.githubusercontent.com/81782841/118565114-1f505080-b761-11eb-85c1-455c61e3cf81.png)
