### ISSUE TITLE
픽시브 다운 관련

### ISSUE THREAD

**Issue by momokoro1** [KurtBestor/Hitomi-Downloader#3355]
안녕하세요! 다운로더 언제나 잘 쓰고 있습니다.

이번에 3.3b로 버전을 올린 뒤로 복수의 작업 목록을 가지고 다운로드를 진행할 경우, 아이피 밴을 먹는 경우가 발생했습니다. 당시에 작업 목록에 올라가 있는 개수는 777개였으며, 63개의 작업을 완료했을 즈음에 작업이 실패하면서 아이피 밴 처리됨을 확인할 수 있었습니다. 

지금 이 글을 작성하면서 작업 속도를 5.0Mb/s 로 설정하여 진행을 하고 있습니다. 63/777 > 215/777의 작업을 진행하고 있으며, 아직까지 밴 처리되고 있지 않습니다.  혹여나 저와 비슷한 과정으로 인해 아이피 밴 처리 당하신 분들 참고해주셨음 합니다.

또, 작업 목록 중 GIF 파일이 섞인 작업 내용이 있습니다. 기존에 다운로드를 끝낸 GIF 파일도 다시 ZIP 형식으로 다운로드가 진행되는 것을 확인했습니다.  GIF 파일도 다른 이미지 파일과 같이 이미 있는 파일들은 스킵이 가능케 해주셨음 합니다. 

3.3a 버전보다 작업의 읽는 속도도 현저히 빨라짐을 느낍니다. 그리고 예전 버전에서는 일정 개수의 작업을 완료하고 나서 잠깐 작업이 멈추고 그랬는데, 지금은 그것마저 개선이 되어 다운로드의 만족도가 올랐습니다. 정말 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by momokoro1** [comment]
선생님, 작동 확인했습니다. 

제가 언급드렸던, GIF 파일의 스킵은 정상 작동합니다. 감사합니다. 
그리고 3.3a 버전에서 느꼈던 작업 파일의 읽는 속도가 다시 느려짐을 확인했습니다. GIF의 변환 속도는 올랐지만, 전체적인 작업 속도는 많이 줄은 것으로 보입니다. 
3.3a 버전이 5분에 20개 정도 진행하는데 반해, 테스트 버전은 동일 시간에 작업량이 10개 미만입니다.  테스트는 동일 조건으로 순차적으로 진행했습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by momokoro1** [comment]
이전과 동일하게 테스트 진행해봤습니다. 

GIF 스킵 정상 작동합니다. 작업 읽는 속도도 전의 테스트 버전보다 올라간 게 확연하게 보입니다. 약 6분 동안 23개의 작업이 진행되었으며, 큰 이상 없었습니다. 
늦은 시간에도 불구하고 바로바로 반영해주셔서 감사합니다!
