### ISSUE TITLE
인스타 관련문의

### ISSUE THREAD

**Issue by kzts97** [KurtBestor/Hitomi-Downloader#3358]
인스타  쿠키 다운후 불러오면 잘됐으나 
최근 똑같이 하여도 무한로딩 이라고 할지 스토리읽는중에서 (1/n) 에서 잘안넘어갑니다 1시간후에 봐도 (2/n) 이런식으로 
최근들어 다운이 잘안됩니다. 
그리고 인스타 들어가면 계정 일시정지 자 매일1번씩은 되는데(누가 로그인시도하여) 
이 거는 다른분들도 그런가요? 
그리고 해결할방법은 없는건가요
항상 잘쓰고 잇습니다 감사합니다!

**Comment by tdi2020** [comment]
너무 많은 사진이 있는 계정을 다운로드 할 경우 저도 동일하게 되더군요. 
트래픽이 많이 발생하면 인스타에서 자동으로 불법행동을 하는 계정으로 판단하고 계정을 잠궈버리는 것 같습니다..ㅠ 
어느정도 읽으면 일부 다운하고 잠시 쉬었다가 읽는다던지 하면 해결이 되지 않을지..ㅠ 딱히 현재 해결방법이 없습니다.

**Comment by kzts97** [comment]
그렇군요.. 답변감사합니다! 몇번껏다키면 어찌어찌 되긴하더라구요.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by kzts97** [comment]
> 인스타 쿠키 다운후 불러오면 잘됐으나 최근 똑같이 하여도 무한로딩 이라고 할지 스토리읽는중에서 (1/n) 에서 잘안넘어갑니다 1시간후에 봐도 (2/n) 이런식으로 최근들어 다운이 잘안됩니다. 그리고 인스타 들어가면 계정 일시정지 자 매일1번씩은 되는데(누가 로그인시도하여) 이 거는 다른분들도 그런가요? 그리고 해결할방법은 없는건가요 항상 잘쓰고 잇습니다 감사합니다!
