### ISSUE TITLE
히요비가 더 이상 운영하지 않으므로 해당 스크립트는 삭제되어야 합니다.

### ISSUE THREAD

**Issue by SaidBySolo** [KurtBestor/Hitomi-Downloader#3405]
https://github.com/KurtBestor/Hitomi-Downloader/releases/download/Utils/hiyobi_bookmark_downloader.hds

해당 스크립트는 히요비에 의존하고 있습니다.
하지만 더이상 히요비가 운영되지않으므로 해당 스크립트는 사용할수없습니다.

**Comment by KurtBestor** [comment]
수정했어요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts
위키는 필요하면 직접 수정하셔도 돼요.
