### ISSUE TITLE
한 계정의 이미지들을 2000개 한도를 넘어서 받을 방법은 없을까요?

### ISSUE THREAD

**Issue by MantisKnight** [KurtBestor/Hitomi-Downloader#3445]
픽시브든 트위터튼 파일들이 늘 2천개에서 다운로드가 멈춰서 어디서부터 이어서 수동으로 잡아서 받아야하는지 직접 찾아야 하는데... 트위터의 경우는 특성 상 이것도 힘들어서 어디서부터 다시 받아야하는지 확인이 거의 불가능하다보니 다소 불편함을 느끼고 있습니다.

혹시 파일을 2천개 한도 넘어서 받을 방법은 없는걸까요?

**Comment by STR-HK** [comment]
`옵션` -> `설정` -> `고급 설정` -> `페이지 지정 다운로드 기본값` 시도해 보시겠어요?

**Comment by MantisKnight** [comment]
> `옵션` -> `설정` -> `고급 설정` -> `페이지 지정 다운로드 기본값` 시도해 보시겠어요?

앗 이런 설정이 있었을 줄이야;; 정말 감사합니다 와 이제 속 시원하게 받을 수 있겠네요!
