### ISSUE TITLE
특정 만화가 무한 읽기됩니다 (모아/토끼 공통)

### ISSUE THREAD

**Issue by Orange6539** [KurtBestor/Hitomi-Downloader#3455]
특정 만화를 다운로드 시도 하면 무한 "읽는중..." 상태에 빠집니다
마나토끼, 마나모아 모두 공통으로 발생하는걸 보면
아무래도 만화 제목때문에 생기는 버그 같습니다

제목 : '공략본'을 구사하는 최강의 마법사 ~명령할 여지를 주지 않는 자기류 마왕토벌 최선 루트~

마나토끼
https://manatoki95.net/comic/255670

제이마나
https://jmana2.iipython.net/book?bookid=9214

![화면 캡처 2021-06-07 015405](https://user-images.githubusercontent.com/80187210/120933148-bb9fbe80-c733-11eb-8cd4-31a511f6f3d1.jpg)

**Comment by wheatflor22** [comment]
개발자는 아니고 다른 유저입니다.
다른 만화 신규다운은 잘되고, 저만화는 저도 받은적 있어서 다시시작해봤는데 잘되네요.

만약에 이름문제가 맞다고 한다면 해결법은 의외로 간단할겁니다.
첫번째는 D드라이브 자체를 혹은 D:\0 같이 짧은 경로로 만들어서 저장경로로 쓰면됩니다.
이름이 양심없이 긴 작품들이 주로 겪는 오류입니다.

근데 이래도 안되면 저도 모르긴하지만, 일단 윈업데이트, 다운로더 다운그레이드 정도를 시도해보는게 좋겠네요

**Comment by Orange6539** [comment]
오늘 다시한번 시도 해보니 오래 걸리긴 했으나 정상적으로 진행 되었습니다
일시적인 문제였던것 같습니다
이슈 닫습니다
