### ISSUE TITLE
가끔 프로그램 창이 간소화 되는 경우가 있는데 해결법 아시는분 있나요?

### ISSUE THREAD

**Issue by wheatflor22** [KurtBestor/Hitomi-Downloader#3472]
물론 껐다가 키면 되긴하지만, 작업중인 경우도 많고 애초에 종료 ㅡ> 재시작 딜레이가 큰편인 프로그램이다보니 망설여지더라고요.

뭔가를 잘못누른건지 아니면 다른게 문제인지..

이 상황을 뭐라고 표현해될지 몰라서 간소화라고 표현하긴 했지만, 기왕 비슷한건 작업관리자에서 간단히 버튼 눌렀을 때 변하는 모양처럼, 메뉴바, 새로운 항목 추가하는 칸이 사라지고 목록만 보이게됩니다.
![image](https://user-images.githubusercontent.com/83639232/121483661-6ac8e800-ca09-11eb-9c91-35254a38a77b.png)

**Comment by KurtBestor** [comment]
참고해주세요: `도움말 - 사용법 (F1) - 기타 단축키`

**Comment by wheatflor22** [comment]
아 감사합니다. 
Ctrl + Tab : 도구창 숨기기 기능이었군요.

번거롭게해서 죄송합니다.
막상 껐다키면 원상복구되고 잘쓰다가 저렇게 되면 도움말에 들어가야 된다는게 안떠오르고 F1누르면 된다는 것도 잊어버려서 질문하게됐네요.
