### ISSUE TITLE
다음 웹툰리그 다운 안되네요..

### ISSUE THREAD

**Issue by roEHdl** [KurtBestor/Hitomi-Downloader#3477]
Invalid: [daumtoon] http://webtoon.daum.net/league/view/10780

version: 3.4 (21-06-10 13:59:31 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / b20c6cd5d6624a20ae3bce3bdf2b555c
input: http://webtoon.daum.net/league/view/10780
type: daumtoon
single: False
url: http://webtoon.daum.net/league/view/10780
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1623456627.20182 (Jun 11)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
Expecting value: line 2 column 1 (char 2)
stop
Traceback (most recent call last):
File "utils", line 1069, in start
File "extractor\daumtoon_downloader", line 127, in init
File "extractor\daumtoon_downloader", line 65, in get_info
File "json\__init__", line 348, in loads
File "json\decoder", line 337, in decode
File "json\decoder", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

Invalid: fail=True
EOT: http://webtoon.daum.net/league/view/10780 (3.0s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by roEHdl** [comment]
잘됩니다 감사합니다!!
