### ISSUE TITLE
무한 반복되는 작업 & 썸네일 관련 질문

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3482]
![image](https://user-images.githubusercontent.com/78652371/121775429-9a6f2000-cbc2-11eb-8408-f12b32615166.png)

위 사진과 같이 다운로드가 완료되지 않고 무한 반복되는 작업이 있는데요,
이런 작업은 `Right Click` -> `Edit Task` 기능을 이용하여 강제로 완료 상태로 만들 수도 없어 어떻게 해결할 방법이 없습니다.
진행 중인 작업을 강제로 완료로 만들 수 있는 방법이 있었으면 좋겠습니다.

그리고 궁금한 점이 있는데요, 썸네일 이미지는 어떻게 구현되는 건가요?
프로그램 시작시에 특정한 영상에서 특정한 시간대의 이미지를 가져오는 건지 TEMP 경로에 저장되어 있는 건지,
어떤 식으로 썸네일이 지정되는지 궁금합니다
관련된 이슈인 #3320를 읽어보았지만 해결되지 않았습니다
+ 가능하면 직접 동영상에서 썸네일을 추출하는 기능이 내장되면 굉장히 좋을 것 같네요

말이 길어졌네요
정리해보면

1. 진행 중인 작업의 강제 완료 가능하게 하는 것이 가능할지
2. 썸네일은 어떤 방식으로 추출되는지
3. 썸네일을 프로그램 내부에서 설정하게 하는 것이 가능할지
가 궁금합니다

**Comment by KurtBestor** [comment]
1. 일시정지 후에 수정하면 돼요.
1. 썸네일 이미지는 설정 파일 `(*.INI)` 에 저장되어있어요.
1. `작업 수정... (F2)` - 썸네일 클릭하면 수정할 수 있어요.

**Comment by STR-HK** [comment]
1. 일시정지 후에도 `Edit Task... (F2)`가 활성화되지 않습니다
![image](https://user-images.githubusercontent.com/78652371/121778812-a7483f80-cbd3-11eb-9545-b6b3e585b62c.png)

2. SQLite를 이용하여 데이터를 열고 확인하였습니다
str_pixmap이라고 되어있는 부분 Base64로 확인하니 잘 보이네요

3. 제 어휘 선택이 잘못되었네요.
`Edit Task... (F2)`에서의 썸네일 변경은 추가 프로그램을 이용하여 동영상에서 직접 이미지를 추출 후 저장하여
프로그램 내에서 불러와야 하기 때문에 번거로워, 프로그램 내에 직접 추출하는 기능의 추가가 가능한지 여쭤본다 라는 의미였습니다

**Comment by KurtBestor** [comment]
<font></font>1. 일시 정지 후 `완료됨으로 표시` 할 수 있게 수정했어요.
3. 다운로드 시 첫번 째 파일이 동영상일 때 자동으로 캡쳐만 하고 동영상에서 직접 추출하는 건 불가능해요. 너무 마이너한 기능.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
