### ISSUE TITLE
클립보드 자동추가 문의

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#3495]
이슈에 검색을 해봤는데 제가 못 찾는 걸 수도 있는데요..

주로 마나토끼에서 만화 다운받는 용도로 사용을 하고 있고, 가끔 유튜브에서 노래를 다운받을 때 사용하는데
친구들에게 노래를 공유할 때 유튜브 링크를 복사하게 되니까 자동으로 다운이 받아지더라구요,,

클립보드 자동 추가가 만화 다운받을 때 굉장히 유용하게 사용 중이라서 클립보드 자동 추가 자체를 끄지 않고 유튜브만 자동추가 되지 않게 하는 방법은 없을까 문의드립니다.

혹시 제가 못 찾은 거라던가,, 그런거면 죄송합니다...

**Comment by STR-HK** [comment]
클립보드 자동추가를 키시면 적용할 사이트 선택창이 떠요
결론 : 클립보드 자동추가를 껐다 켜보세요
