### ISSUE TITLE
사이트 지원 추가 부탁드립니다.

### ISSUE THREAD

**Issue by chiminkim** [KurtBestor/Hitomi-Downloader#3507]
항상 다운로더 잘쓰고 있습니다.

VPN 사용하지 않고도 접속 가능한 사이트가 있는데, 해당 사이트 URL도 추가 부탁드립니다.

요청 사이트 주소: https://javtiful.com/

아니면 혹시 개인PC에 사이트별 다운로드 소스를 수정&반영이 가능하다면 방법을 알려주시면 감사하겠습니다.

**Comment by STR-HK** [comment]
[위키](https://github.com/KurtBestor/Hitomi-Downloader/wiki) 가보시면 직접 추출기 스크립트 만들어서 사용하시는 방법 나와 있어요.

**Comment by chiminkim** [comment]
> [위키](https://github.com/KurtBestor/Hitomi-Downloader/wiki) 가보시면 직접 추출기 스크립트 만들어서 사용하시는 방법 나와 있어요.

죄송하지만 현재 github에 있는 wiki에는 아무런 글도 안보이는데, 나무위키나 다른 위키를 지칭하신거라면 url공유를 부탁드려도될까요?

**Comment by STR-HK** [comment]
링크해놓은 위키 들어가보시면 목차가 있을 건데
제목 클릭하시면 읽으실 수 있어요
