### ISSUE TITLE
E(x)Hentai 갤러리 아카이브 다운로드 지원

### ISSUE THREAD

**Issue by aeongdesu** [KurtBestor/Hitomi-Downloader#3513]
[Ehwiki](https://ehwiki.org/wiki/Archives)

충분한 GP/크레딧이 있거나 [무료 아카이브](https://ehwiki.org/wiki/Archives#Free_Archives)가 가능하신 분들을 위해 옵션으로 아카이브 다운로드를 지원해줬으면 좋겠습니다.

https://github.com/mikf/gallery-dl/issues/886
https://github.com/mikf/gallery-dl/issues/146#issuecomment-543740015

**Comment by KurtBestor** [comment]
충분한 GP 가 있다면 그냥 다운로드하고 압축 옵션을 하면 되지 않나요?

무료 아카이브가 가능하면 그냥 웹사이트에서 다운로드 누르면 될 것 같아요

**Comment by KeepSOBP** [comment]
@KurtBestor 음.. 생각해보니 그러겠네요, 과연 제한?량 초기화 GP량보다 아카이브로 다운하는 GP량 차이는 잘 모르겠지만요..

제가 멘션한  gallery-dl # 846 이슈처럼, 크게 서버간의 대한 부담이 없고, 자동으로 압축(zip)해서 요청자에게 보내주기 때문에 괜찮을것 같아요
