### ISSUE TITLE
작업별 일시정지 기능은 없어진건가요?

### ISSUE THREAD

**Issue by Elements8** [KurtBestor/Hitomi-Downloader#3518]
예전에는 작업별로 일시정지 버튼이 있었던 것 같은데 어느 버전부터인지 일시정지 버튼이 없어졌네요

가끔 목록에만 올려놓고 나중에 다시 받으려고 일시정시 시켜놓거나 다양하게 썼던 버튼인데 없어져서 아쉽네요... ㅠㅠ

릴리스 노트나 이슈들을 봐도 개별 일시정지 버튼에 대한 이야기가 없어서 질문드립니다!

![캡처](https://user-images.githubusercontent.com/54109451/123460019-fe153680-d621-11eb-8b71-cd18e8556a0a.PNG)

**Comment by KurtBestor** [comment]
단일 파일은 일시정지 할 수 있었던 적이 없어요

**Comment by Elements8** [comment]
아... 맞네욬ㅋㅋㅋ 채널 묶음 파일은 되네요 제가 착각했나 봅니다. ㅋㅋㅋㅋㅋ

항상 감사합니다.

**Comment by Elements8** [comment]
> 단일 파일은 일시정지 할 수 있었던 적이 없어요

아... 맞네욬ㅋㅋㅋ 채널 묶음 파일은 되네요 제가 착각했나 봅니다. ㅋㅋㅋㅋㅋ

항상 감사합니다.
