### ISSUE TITLE
#3511 폰허브 프리미엄 관련

### ISSUE THREAD

**Issue by li4ac1212** [KurtBestor/Hitomi-Downloader#3530]
premium 페이지에서 Channel 다운로드는 진행되는 것처럼 보였으나,
실제로 채널 내의 일반 비디오만 인식하고
프리미엄 비디오는 인식을 하지 못하는 상황입니다.
또, 프리미엄 비디오만 따로 다운할 수 있는 방법은 없을까요?

계정은 DM으로 보내져 있습니다.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/3511
