### ISSUE TITLE
감사합니다^^

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#3541]
정말 감사합니다
잘됩니다^^

**Comment by wheatflor22** [comment]
그러게요 개별다운/일괄다운 둘다 안되네요.

**Comment by versk1** [comment]
운영자님 덕분에 코로나 시대 그나마 낙을 즐기고 있습니다ㅎ
네이버 관련 동일한 증상 해결 가능하면 좋겠습니다.
언제나 진심 감사드립니다^^
