### ISSUE TITLE
Downloader keeps multiple connections active forever

### ISSUE THREAD

**Issue by rktfier** [KurtBestor/Hitomi-Downloader#3543]
After downloading any content from any site, downloader does not close the connections, instead it keep them open even after the download is finished, basically forever. Also it makes connections to localhost ports and never closes the connection. This is no problem for general user but people who is using connection analyzers doesn't like 20 connections from downloader that is open for 34 hours.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rktfier** [comment]
> 
> 
> Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Seems to work, connectşons get made and closed quickly after.
