### ISSUE TITLE
Duplicate 줄 것 같은데 정확히 하고 싶어서요

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#3548]
크기 고정은 전혀 하고싶으신 생각이 없으신건가요? 전 내용 보니 단순 의도가 원래 그렇다고 말씀하셔서

**Comment by KurtBestor** [comment]
다음과 같은 상황에서 창이 밖으로 나가버린다던가 잘못된 위치에 되는 문제, 어떤 모니터를 기준으로 DPI 를 정할지 같은 문제 등이 있어서 보류했어요:
1. 모니터 해상도가 바뀌는 경우
2. DPI Scaling 이 바뀌는 경우
3. 주모니터가 바뀌는 경우
4. 다중모니터 배열이 바뀌는 경우
5. 저장된 창 위치가 있는 모니터를 제거한 경우
6. 차후에 프로그램 레이아웃이 바뀌는 경우
7. 기본 크기로 돌아가는 기능을 어떻게 추가할지

애초에 실행해서 드래그 한두번으로 위치 & 크기 조정이 가능하니까 크게 중요한 기능은 아닌 것 같아요.

**Comment by KurtBestor** [comment]
다음과 같이 해결했어요:
1. 창 위치 크기 그대로 둠
2. 창 크기 그대로 둠
3. 주 모니터의 DPI Scaling 을 따라감
4. 기존 창 위치가 모니터 범위를 넘어가면 걸쳐있는 모니터 쪽으로 옮기고, 걸쳐있는 모니터가 없을 경우 주 모니터로 옮김
5. 4번과 같음
6. 나중에 생각
7. `옵션 - 설정 - 창 위치 크기 저장` 으로 설정 가능

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
감사합니다.
