### ISSUE TITLE
Invisible program password box in dark theme

### ISSUE THREAD

**Issue by rktfier** [KurtBestor/Hitomi-Downloader#3549]
Closed program properly, and opened it again. Password box working normally : 
![image](https://user-images.githubusercontent.com/75695425/125091382-04eb8100-e0d9-11eb-9d55-a3d98fead97c.png)

After i unlock the program and press the boss key, downloader minimizes as usual, but when i use the boss key to get it showing again 

![image](https://user-images.githubusercontent.com/75695425/125091609-3c5a2d80-e0d9-11eb-9799-a86c205ed3ac.png)
 (note that i wrote my password like the first image) the password becomes invisible, while this might be a useful feature it should be bound to a settings switch.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rktfier** [comment]
Password box now stays in light theme all the time instead of switching to dark theme. Seems to fix the problem.
