### ISSUE TITLE
xvideos 제목 중복시 덮어쓰기되는 문제, 제목 길어서 안받아지는 문제

### ISSUE THREAD

**Issue by irina-petrovna** [KurtBestor/Hitomi-Downloader#3580]
일단 #233 이건 읽어봤는데 pornhub 쪽은 개선하신거 같은데 xvideos쪽은 제목 겹치면 여전히 안받아지더라구요
https://www.xvideos.com/profiles/leakedjp
이사람이 동일한 제목으로만 영상을 올려서 하나도 저장을 못하고 있습니다 ㅠ
채널 전체를 받아봐도 마지막 하나만 저장되더라구요

==========================================================

그리고 제목길어서 안되는거 같긴한데
https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2
이거 저장이 안되네요

아래 로그입니다

52분 52초 뒤 다시 시작: https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2

version: 3.5 (21-07-11 04:31:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / d0746a6bfb3b4d6c8c9ae683831967ec
input: https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2
type: xvideo
single: True
url: https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2
dir: hitomi_downloaded_xvideo
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1626883866.5139115 (Jul 22)
tags: []
lock: False
color: invalid_done
paused: False
format: None
p2f: None
segment: None
goodbyedpi: True
ytdl: 2021.06.06
pinned: False
extras: {}
changed: False

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_xvideo\Sexo ORAL Entre Amigas! Estudiantes LESBIANAS Adolescentes Mexicanas! Un Amigo les Hace una ENTREVISTA a DOS AMIGAS de la ESCUELA, se CALIENTAN y Hacen un TRO CASERO por Primera Vez Despus d la Escuela y Comparten VERGA d su COMPA,PARTE 2.mp4

[URLs]
[0001] LazyUrl(https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2) ---> M3u8_stream(https://cdn77-vid.xvideos-cdn.com/bfgeu2Nw8OQtz1R-3fdCLQ==,1626894667/videos/hls/7b/4b/95/7b4b952317f99e737f6efdbf39f8bda6/hls-360p-4fcae.m3u8)

[Messages]
Convert: E:\hitomi\hitomi_downloader_GUI\hitomi_downloaded_xvideo\Sexo ORAL Entre Amigas! Estudiantes LESBIANAS Adolescentes Mexicanas! Un Amigo les Hace una ENTREVISTA a DOS AMIGAS de la ESCUELA, se CALIENTAN y Hacen un TRO CASERO por Primera Vez Despus d la Escuela y Comparten VERGA d su COMPA,PARTE 2.mp4

Fail m3u8 pp : Sexo ORAL Entre Amigas! Estudiantes LESBIANAS Adolescentes Mexicanas! Un Amigo les Hace una ENTREVISTA a DOS AMIGAS de la ESCUELA, se CALIENTAN y Hacen un TRO CASERO por Primera Vez Despus d la Escuela y Comparten VERGA d su COMPA,PARTE 2.mp4
Traceback (most recent call last):
File "downloader", line 704, in download
File "m3u8_tools", line 209, in _pp
File "ffmpeg", line 230, in convert
File "ffmpeg", line 132, in rename
Exception: No file

stop
valid=False 1
EOT: https://www.xvideos.com/video61506329/sexo_oral_entre_amigas_estudiantes_lesbianas_adolescentes_mexicanas_un_amigo_les_hace_una_entrevista_a_dos_amigas_de_la_escuela_se_calientan_y_hacen_un_trio_casero_por_primera_vez_despues_d_la_escuela_y_comparten_verga_d_su_compa_parte_2 (29.0s)

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `YouTube 설정` - `파일명 형식` 이 어떻게 되어있나요?

**Comment by irina-petrovna** [comment]
> `옵션` - `설정` - `YouTube 설정` - `파일명 형식` 이 어떻게 되어있나요?

헉 유튜브 제목설정이 전역 설정으로 들어가는 거였네요. #233 글을 잘못 이해했습니다. 유튜브 설정을 title(id)로 바꿔줘야 하는 거였군요. 해결했습니다.
같은 방법으로 아래 제목 긴놈도 그냥 id로 해서 받았습니다. 감사합니다.
