### ISSUE TITLE
일단 검색해서 안나오길래 올려봅니다

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#3586]
다운로더에 있는 사용법에 읽어봐도, 깃헙에서 검색해봐도 안보이길래 질문합니다만 
f3 눌러서 검색? 할 때 오늘 다운로드 한 것만 안볼 수 없나요? 분명히 다운로더가 다운목록을 날짜 별로 분류한다는 건 설정에서 날짜를 보이게 할 수 있다는 걸 생각하면 당연히 알 수 있다고 생각했기에, 언제 다운로드 한 것만 본다던가... 언제 이전에 다운 받은 건 안보이게 한다던가 할 수 있을 거라고 생각했는데 찾아도 안보이더라구요... 혹시 duplicate 넣으실거면 링크라도 좀...

**Comment by KurtBestor** [comment]
좌측하단 정렬 기준 눌러서 날짜순으로 정렬할 수 있어요
