### ISSUE TITLE
다음 웹툰이 카카오 웹툰으로 개편되었습니다.

### ISSUE THREAD

**Issue by jinjins7** [KurtBestor/Hitomi-Downloader#3604]
다음 웹툰이 카카오 웹툰으로 개편되었습니다.
그래서 더이상 다운로더로 다운이 안되는 상황입니다.
당장 링크부터가 싹다 바뀌었습니다.
구 : http://webtoon.daum.net/webtoon/view/weeklyboys
신 : https://webtoon.kakao.com/content/주간소년열애사/1262

현재 구 링크들은 개편된 신 링크로 바로 다이렉트로 연결되는데 개편되면서 구조가 바뀌어서 링크가 연결되어도 프로그램에서는 다운을 하지 못합니다.

**Comment by lightnoveller** [comment]
파일들이 암호화되어 있습니다. 더이상 지원하지 않을 것 같네요.
