### ISSUE TITLE
그룹만 있을 경우 작업이 없다고 뜹니다

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3607]
![image](https://user-images.githubusercontent.com/78652371/127778347-ee1600b2-afbf-462b-a326-322aaf04dfee.png)
단일 항목은 전혀 없고 그룹만 있는 상태에서는 작업이 없다고 떠버리네요

**Comment by KurtBestor** [comment]
작업이 없기 때문에 없다고 뜨도록 했어요
