### ISSUE TITLE
트위터 팔로우 계정 지속 다운로드

### ISSUE THREAD

**Issue by peesan** [KurtBestor/Hitomi-Downloader#3608]
안녕하세요.

언제나 프로그램을 잘 사용하고 있습니다.
유저들의 요구사항을 계속 업데이트 해 주시는 것을 보면, 정말 대단하다는 생각이 듭니다.

저도 눈팅만 하며 프로그램만 쓸 것이라 생각했는데.. 최근 트위터 계정을 다운받다보니, 약간 불편한 점이 있어 연락드려봅니다.

현재 히토미 다운로더에서 트위터 계정을 다운로드 하면, 트위터 계정을 '트위터 다운로디드' 폴더에 다운로드 하는 것을 알 수 있습니다. 며칠 뒤에 해당 계정을 다운로드 하면, 중복 내용을 빼고 다시 다운로드를 하더군요.

이 다운로드 폴더 안에 있는 트위터 계정을 다시 불러들여서, 다운로드 하는 기능을 구현할 수 있을지요?
(신규로 올라와 있는 트위터 미디어를 다운받기 위함입니다.)

계정이 10~20개 정도 되었을 때는, 일일이 하나씩 복사>붙여넣기를 통해서 다운로드 해왔는데..
계정이 많아지고 나니, 도저히 수동으로 다운로드를 할 수 없더군요.

문돌이라서, 다른 분들처럼 스크립트를 만들 방법도 없고..  

예전에 모 팬덤에서 지속적으로 팔로잉하고있는 계정의 미디어를 다운로드 하는 프로그램을 작성한 바 있으나,
(https://lovelyyoojiae.tistory.com/13)
현재는 업데이트가 끝나서, 오류를 뱉어내고 다운로드가 안 되고 있는 실정입니다. (물론 되는 팔로잉 계정도 있긴 합니다만.. 느낌상으로 구독이 많아지면 이것도 오류를 뱉더군요)

많은 사람들이 동일한 어려움을 겪을 것이라 생각했지만, 아직 이에 대한 질문은 없더군요. 한 번 확인 부탁드리겠습니다.
감사합니다.

**Comment by STR-HK** [comment]
다운로더 내에 항목을 다시 다운받고 싶으신 거라면,
목록에서 다시 다운받고 싶으신 항목들을 선택하신 다음
`우클릭` -> `재시작` 하시면 될 것 같습니다.

( `Ctrl` + `A` 단축키로 전체 선택 하셔서 다운로드 하셔도 되겠네요. )

ps. 제가 이해력이 부족하여 잘못된 답변을 드렸을 수도 있습니다. 양해해 주시면 감사하겠습니다.

**Comment by peesan** [comment]
너무 늦게 봤네요.
이런 방법도 있네요. 확인 감사합니다!
