### ISSUE TITLE
완료되지 않은 작업의 수정

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3609]
![image](https://user-images.githubusercontent.com/78652371/127778491-2d51e369-ada1-450f-a2e0-4e4bff887c42.png)
위 사진과 같이 완료되지 않은 작업을 일시 정지하고 수정하려고 해도 메뉴가 활성화되지 않네요.
#3482 에서는 일시 정지 후에 시도해 보라고 하셨는데 그래도 활성화되지 않는 것 같습니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3482#issuecomment-890723585
