### ISSUE TITLE
목록 불러오기

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3613]
다운로드 목록을 불러올 때, 최신 버전에서는 보이는 부분만 불러오는 것 같습니다.
이를 프로그램 시작시 모든 작업 불러오기 / 보이는 부분만 순차적으로 불러오기 옵션으로 선택할 수 있으면 좋겠습니다

**Comment by KurtBestor** [comment]
초기 로딩 시간을 줄이기 위해 필요한 부분만 레이지로딩 하도록 했어요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3539
모두 읽으면 좋은 점이 있나요?

**Comment by STR-HK** [comment]
음.... 레이지로딩으로 하니 목록 빨리빨리 내리면서 작업들을 보기가 어렵습니다
그래서 좋은 점이라고 하면 빠른 응답속도가 되겠네요

스크롤을 할 때마다 천천히 보여지니 너무 느린 것 같아서
현재는 프로그램 시작시에 전체 목록을 쭈욱 한번 내려 모든 항목을 불러오는 방법을 사용하고 있습니다만....
이걸 컴퓨터 재부팅할 때 마다 해줘야 해서 불편한 감이 있어서 의견드립니다

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `빠른 시작을 위한 작업 레이지 로딩` 으로 끌 수 있어요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by STR-HK** [comment]
확인했습니다. 잘 작동합니다.
감사합니다
