### ISSUE TITLE
링크 복사 시 이벤트 인식하여 자동으로 다운로드 대기 목록에 추가 기능 요청

### ISSUE THREAD

**Issue by DreamerKMP** [KurtBestor/Hitomi-Downloader#3614]
크롬으로 웹 링크를 복사하여 일일이 복사하여 다운로드 창에 포커스를 준 후 엔터를 쳐 붙여넣기를 하고있습니다.

웹 링크 복사 이벤트를 감지하여 자동으로 대기 목록에 추가할 수 있으면 매우 편할 것 같군요.

**Comment by STR-HK** [comment]
`옵션` -> `클립보드에서 자동 추가` 활성화하시면 되겠네요

**Comment by DreamerKMP** [comment]
> `옵션` -> `클립보드에서 자동 추가` 활성화하시면 되겠네요

아.. 그런 기능이 있었군요. 확인해보고 잘 동작하면 이 이슈는 닫아보
