### ISSUE TITLE
레이지로딩 사용하지 않을시 파일목록 불러와지지 않음

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#3629]
`빠른 시작을 위한 작업 레이지 로딩` 옵션을 고급 설정에서 키니
다운받은 파일 목록 (작업 목록 X) 이 하나도 불러와지지 않아서 정상적인 이용이 불가능합니다.
말로 설명이 어려우니 사진 첨부합니다.

![image](https://user-images.githubusercontent.com/78652371/128623343-6ddb8bb4-2fca-447c-a4b6-147c2a49048d.png)

위의 현상이 모든 작업에서 동일하게 발현됩니다

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by STR-HK** [comment]
정상적으로 작동합니다
감사합니다
