### ISSUE TITLE
픽시브 다운로드에서 파일명 형식 처리에 대한 건의

### ISSUE THREAD

**Issue by cknblue** [KurtBestor/Hitomi-Downloader#3636]
![09_235905_hitomi_downloader_GUI_VCN5NDSJ6x](https://user-images.githubusercontent.com/14037695/128727755-35b629be-816e-4bce-8712-1f36dc7d6bb0.png)

픽시브 다운로드에서 파일명 형식을 지정할때 id_artist 이런식으로 작가 고유번호로 저장할 수 있도록 하는것이 가능할까요?

다운로드를 해놓은후 새롭게 북마크를 추가할때 마다 다시시작을 눌러서 다운로드를 받을때
파일숫자가 이상하게 늘어나 확인해보니 작가가 자꾸 작가명칭을 바꾸어서 중복 다운로드가 일어납니다.
(예를 들어 ㅇㅇ -> ㅇㅇ .fanbox 08.10 open)

파일명 형식에
지금은 id_ppage [artist] title 이 3가지로만 파일명 형식 처리가 가능한것 같은데요.
거기다 id_artist를 추가해서 작가 고유번호로 저장이 가능했으면 합니다.

고유번호는 "https://www.pixiv.net/users/33076135" 이런식으로 주소창에 같이 표시됩니다.
artist = "SOLar @ fanbox"
id_artist = "33076135"

이런식으로 추가적으로 처리가능 하도록 건의해봅니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by cknblue** [comment]
파일명 형식에 "artistid"가 추가된것을 확인했습니다.
파일명 형식으로 다양하게 조합해서 테스트 해봤는데요. 올바르게 작동합니다.
감사합니다.
