### ISSUE TITLE
토렌트 파일이나 마그넷 링크시 이미 실행중인 프로그램에 자동으로 항목 추가할 수 있도록 할수 있을까요?

### ISSUE THREAD

**Issue by blazepsyki** [KurtBestor/Hitomi-Downloader#3696]
현재에서는
-파이어폭스에서 magnet 링크에 대해서 동작 실행을 프로그램 경로의 exe 파일로 설정하거나
-윈도우 기본앱에서 *.torrent 형식의 파일의 기본 여는 프로그램을 exe파일로 설정해도
새로운 프로그램이 켜지려는듯 하다가 이미 실행중이기 때문에 그냥 꺼지는거 같네요.
(옛날 버전에서는 이미 실행되고 있습니다라고 경고창이 뜬 기억이 있는데  요즘은 없어졌는데 패치내역에는 잘 못찾겠네요.)

따로 토렌트 프로그램 쓰다가 이 프로그램도 토렌트 지원하길래 쓰던거 지우고 이걸로 통일하려고 하는데 마그넷 링크 눌러서 하는게 안되니까 조금은 귀찮은 절차가 되어서요. 어려운 기능일지도 모르겠는데 혹시 가능하시다면 검토 한번 부탁드립니다.

**Comment by STR-HK** [comment]
`옵션` -> `클립보드에서 자동 추가` 에서 `Torrent`를 선택해 활성화하고,
브라우저에서 마그넷 링크를 `우클릭` -> `링크 주소 복사` 방법을 한번 시도해보시겠어요?

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `Torrent 설정` - `토렌트 파일 연결` 로 연결 할 수 있어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by blazepsyki** [comment]
Fatal error detected
Failed to execute script hitomi_download_GUI
라는 알림창이 뜹니다.
따로 debug.txt 같은건 생성되지 않네요.

**Comment by blazepsyki** [comment]
> 
> 
> `옵션` -> `클립보드에서 자동 추가` 에서 `Torrent`를 선택해 활성화하고,
> 브라우저에서 마그넷 링크를 `우클릭` -> `링크 주소 복사` 방법을 한번 시도해보시겠어요?

해당 방법은 알고 있는데 파일 클릭이나 링크 클릭이면 더 편하지 않을까 싶어서 기능추가가 쉽다면 이쪽이 낫다 싶어서 기능 추가를 요청드렸습니다. 해당 방법에 대해서는 인지하고 있습니다. 알려주셔서 감사합니다.

**Comment by blazepsyki** [comment]
추가로, 해당버전은 두어번 재실행 된 후에는 이미 실행중이라면서 재실행이 되지 않습니다.

**Comment by KurtBestor** [comment]
두어번 재실행 된 후에는 이미 실행중이라면서 재실행이 되지 않는다는 게 무슨 뜻인가요?

**Comment by KurtBestor** [comment]
혼자서 에러가 뜨면서 두어번 재실행 된다는 건가요?

**Comment by blazepsyki** [comment]
혼

> 
> 
> 혼자서 에러가 뜨면서 두어번 재실행 된다는 건가요?
기본 앱 연결을 해놓고
1) 처음에 프로그램을 실행해놓은 상태에서 토렌트 파일을 클릭해서 실행하려고 했는데 오류
2) 프로그램을 종료한 상태에서 토렌트 파일을 클릭해서 실행하려고 했는데 오류
이후에 한번 더 프로그램을 껐다 켰고, 그 다음에 다시 프로그램을 켜려고 하니(모두 테스트 빌드입니다)
에러가 뜨면서 (downloader is already running! 비스무리한 창) 실행이 되지 않습니다.

**Comment by KurtBestor** [comment]
다음과 같이 실행해서:
```
hitomi_downloader_GUI.exe --debug
```

생긴 `debug.txt` 파일 보내주시면 분석해볼게요

**Comment by blazepsyki** [comment]
![image](https://user-images.githubusercontent.com/22346903/129356760-473af990-af63-4a88-980f-e80b418b99ac.png)

재부팅 후, 이전에 쓰던 v3.6 버전 다운로드받은 파일만 남기고 다 지운다음에 다른 폴더에서 실행 시도했는데 두번 다 똑같이 뜨고, debug.txt는 생성되지 않네요.

**Comment by KurtBestor** [comment]
이걸로 다시 실행해서: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

생긴 `debug.txt` 보내주세요

**Comment by blazepsyki** [comment]
C:\Users\pc\AppData\Local\Temp\35c99175f3294cc0ce6cad7f818ba09b44f474d4
not single
C:\Users\pc\AppData\Local\Temp\35c99175f3294cc0ce6cad7f818ba09b44f474d4
not single
import browser start
import browser end
Hitomi Downloader v3.6
DEBUG
debug message handler
<class 'str'> 42686
fix value (zh): 토렌트 파일 연결
fix value (fr): 토렌트 파일 연결
fix value (es): 토렌트 파일 연결
C:\Users\pc\AppData\Local\Temp\_MEI126482\bs4\element:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
['C:\\Users\\pc\\AppData\\Local\\Temp\\WinDivert.dll', 'C:\\Users\\pc\\AppData\\Local\\Temp\\WinDivert64.sys']
no goodbye_dpi

이상이 debug.txt 내용입니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by blazepsyki** [comment]
1) 프로그램을 이미 실행한 상태에서 토렌트 파일 및 마그넷 링크 실행할 때
2) 그냥 윈도우 탐색기에서 토렌트 파일 실행 / 웹페이지(Firefox 91.0 기준) 마그넷 링크 클릭시 프로그램 실행할 때

두 가지 시나리오에서 모두 정상적으로 항목 추가되어 다운로드 시작되는 것 확인했습니다.
감사드립니다!
