### ISSUE TITLE
토렌트 다운로드 관련 질문

### ISSUE THREAD

**Issue by Lanizin** [KurtBestor/Hitomi-Downloader#3697]
토렌트 관련 설정에 대한 내용을 찾아보지 못해 질문드립니다.
본 프로그렘으로 토렌트 다운로드시 시딩이 다운로드 종료후에도 계속 유지되나요?

**Comment by STR-HK** [comment]
참고해주세요 : #2974, #1988

**Comment by Lanizin** [comment]
답변 감사드립니다
