### ISSUE TITLE
소설가가 되자 다운로드 추가 건의 드립니다.

### ISSUE THREAD

**Issue by qj8x67s33a44** [KurtBestor/Hitomi-Downloader#3717]
[작가 이름] 소설 제목 으로 저장되는 파일명에 ncode 도 추가가 가능할까요?

예) [작가 이름] 소설 제목 (ncode)

[愛七ひろ] デスマーチからはじまる異世界狂想曲（ web版 ） (n9902bn)

https://ncode.syosetu.com/n9902bn/

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/759

**Comment by qj8x67s33a44** [comment]
설정에 소설가가 되자 폴더명 형식은 [artist] title (id) 로 되어 있습니다

하지만, 저장은 [artist] title 만 됩니다, 따로 설정을 어떻게 해야 하는지 알려주실 수 있으실까요?

**Comment by KurtBestor** [comment]
소설가가 되자 폴더명 형식은 설정할 수 없는데 어떻게 설정하셨나요?

**Comment by qj8x67s33a44** [comment]
설정은 건들거나 한 것은 하나도 없습니다. 

설정 누르면 일반탭에 저장 폴더 목록을 누르면 쫙 뜨는 것 중에서 小説家になろう 클릭해보면 [artist] title (id) 로 되어 있다고 말씀드린 거 였습니다. 오해하게 해드려 죄송합니다.

[작가 이름] 소설 제목 (ncode) 이렇게 저장할 수 있는 방법이 없을까요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/130307202-ad514922-a027-466c-a854-8476a193e133.png)

이건 저장 폴더 설정이에요

**Comment by qj8x67s33a44** [comment]
참고해보라고 위에 링크 주신 것을 확인해봐도 잘 모르겠네요 ㅠ...

**Comment by qj8x67s33a44** [comment]
번거롭게 죄송합니다.

[작가 이름] 소설 제목 (ncode) 이렇게 저장할 수 있는 방법이 없을까요?
