### ISSUE TITLE
다음웹툰 관련문의

### ISSUE THREAD

**Issue by wheatflor22** [KurtBestor/Hitomi-Downloader#3767]
다음웹툰이 카카오웹툰으로 바뀌었다는건 여기 이미 글이 하나 있는건 인지하고있습니다.

그런데 이미지 파일이 암호화 되어있다라고 누가 리플을 달아줬고요.

그런데 그냥 확장자만 이미지로 바꾸면 정상적으로 이용가능한 파일이더라고요.
해당 프로그램에서 다운 ㅡ> 확장자 변경을 하는게 안되면 당연히 지원예정이 없으시겠지만 된다면 지원예정이 있으신가요?

**Comment by KurtBestor** [comment]
해당 글에 코멘트 달아주세요
