### ISSUE TITLE
유튜브 다운로드 후 변환 중에 컴퓨터가 꺼집니다

### ISSUE THREAD

**Issue by altair823** [KurtBestor/Hitomi-Downloader#3878]
유튜브 영상이 다운로드가 다 되면 변환 중이라면서 작업을 하는데
이 과정에서 갑자기 모든 cpu코어를 최대한으로 씁니다. 
온도도 엄청 올라가고요. 그렇게 10분 정도 후에는 과부하가 걸려서 그런지
컴퓨터가 꺼지고 재부팅됩니다. 

![캡처](https://user-images.githubusercontent.com/46125008/136663573-d493d3ce-b423-4902-a99c-b695a5ebb645.PNG)

사진은 옵션에서 1개 작업에 1개 스레드만 설정한 상태로 다운받는 모습입니다. 
제 컴퓨터가 문제라면 시간이 좀 더 걸리더라도 이렇게 과부하를 주지 않고 
다운 받을 수 있는 방법을 알고 싶습니다. 

영상 길이는 한 시간에서 세 시간짜리들 입니다.

**Comment by KurtBestor** [comment]
`옵션` - `설정` - `고급 설정` - `저사양 모드` 켜시면 코어를 하나만 사용해요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by altair823** [comment]
원래 받으려던 영상이 2시간짜리라 그런지 몰라도 시간이 정말 오래 걸렸습니다. 거의 4~5시간 정도?
그래도 결과적으로 받아지긴 합니다. 
근데 화질을 설정에서 720p로 낮췄음에도 불구하고 평균 3~4기가짜리였던 파일이 7기가 가까이 용량이 크게 받아지네요. 
같은 영상을 받아본게 아니기 때문에 확실하진 않지만 영상 화질은 육안 상 다른 점이 없었습니다. 
느리지만 일단 사용할 수 있으니 감사하게 쓰겠습니다. 👍
