### ISSUE TITLE
X hamster 사이트 주소 변경

### ISSUE THREAD

**Issue by YSL20S** [KurtBestor/Hitomi-Downloader#3913]
안녕하세요! X햄스터 주소가 변경 된거 같습니다.
기존  https://xhamster23.com/ 에서

변경  https://xhwebsite.com/ 

추가 부탁 드립니다. 현재 Unknown site로 뜨면서 다운이 안되네요 ^^

**Comment by lklk98** [comment]
https://ko.xhtime5.com/videos/korean-slut-cumtribute-xh9Ll4u
