### ISSUE TITLE
f3 중 end, home

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#3974]
f3을 켜놓은 상태일 때 end와 home이 정상 작동하지 않습니다.
또한 f3중 방향키를 사용하면 보이지 않는 작업까지 전부 방향키를 사용해야 하는게 불편합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
