### ISSUE TITLE
I'm often getting a "Fail fast exception error" when exiting, regardless of whether I saved it or not

### ISSUE THREAD

**Issue by TheWAVs** [KurtBestor/Hitomi-Downloader#3975]
Hi, I downloaded the latest version of this Downloader but I still having this annoying error message every time that (Most of the time) I try to close it:

**_"A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately."_**

![YMMp5cpHYU (2)](https://user-images.githubusercontent.com/10777531/139594839-594c5daf-737d-43a9-92e3-0379bd5de2fe.png)

Also, It seems I'm the only one with this issue.

My OS: Windows 10 20H2 (19042.985)

May you fix this?, Please.

**Comment by KurtBestor** [comment]
How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by TheWAVs** [comment]
> How about this?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Same, it still happens.

More specifically, that annoying error message show up if I don't save the tasks.

Why is it still happening? Do you have any explanation for this?
