### ISSUE TITLE
11

### ISSUE THREAD

**Issue by eggrollmaster** [KurtBestor/Hitomi-Downloader#3980]

**Comment by helpmepls08** [comment]
잘 들어가집니다.
저는 히토미 다운로더에 있는 dpi우회를 키고 들어가집니다
히요비는 문닫았다가 임시로 다시 연걸로 압니다.
그리고 사이트보단 다운로더에 있는 도구 검색기를 많이 사용하네요.

**Comment by eggrollmaster** [comment]
> vpn이나 dpi 우회를 해도 깨진 사이트가 나오고 모든 이미지가 표시되지않는 상태로 들어가집니다.
> 
> 물론 그 이상의 진행은 불가능하구요
> 
> 다들 어떻게 이용중에 계시는지 궁금합니다.
