### ISSUE TITLE
유튜브 멤버십 영상 다운로드 속도 저하 관련의 건

### ISSUE THREAD

**Issue by johnpac88** [KurtBestor/Hitomi-Downloader#3984]
저번에 답해주신 (https://github.com/KurtBestor/Hitomi-Downloader/issues/3931#issuecomment-950503604)
방법을 통해 yt-dlp 를 이용해서 다운로드를 잘 받고 있는데요

아직 히토미 다운로더를 통해서 하는 유튜브 멤버십 전용 컨텐츠는 다운로드 속도가 안나오네요..
혹시 히토미 다운로더에는 멤버십 다운로드 속도 개선 계획이 어떻게 되나요?
제가 쓰는 yt-dlp 커맨드라인은
yt-dlp --cookies cookies.txt --merge-output-format mp4 https://youtu.be/XXXXXXX
입니다

**Comment by KurtBestor** [comment]
이것도 내부적으로 `yt-dlp` 를 이용하는데 왜 속도가 다른지 모르겠네요. 계속 시도해도 같나요?

**Comment by johnpac88** [comment]
계속 시도해보았는데 이제 속도가 잘 나옵니다!
