### ISSUE TITLE
다운로더가 마그넷,토렌트 파일을 못읽습니다

### ISSUE THREAD

**Issue by CLANK0624** [KurtBestor/Hitomi-Downloader#3998]
Invalid: [torrent] C:\Users\chess\Desktop\[JAV] [Uncensored] FC2 PPV 2273321 [1080p].torrent

version: 3.7c (21-11-05 11:01:05 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 0 / False / 34b2a36438754664bc020538f9e8babf
input: C:\Users\chess\Desktop\[JAV] [Uncensored] FC2 PPV 2273321 [1080p].torrent
type: torrent
single: True
url: C:\Users\chess\Desktop\[JAV] [Uncensored] FC2 PPV 2273321 [1080p].torrent
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1636205431.3625162 (6 Nov)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.10.22
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
DLL load failed: 지정된 모듈을 찾을 수 없습니다.
stop
Traceback (most recent call last):
File "utils", line 1128, in start
File "extractor\torrent_downloader", line 38, in init
File "torrent", line 13, in init torrent
ImportError: DLL load failed: 지정된 모듈을 찾을 수 없습니다.

Invalid: fail=True
skip convert_imgs
EOT: C:\Users\chess\Desktop\[JAV] [Uncensored] FC2 PPV 2273321 [1080p].torrent (0.3s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by CLANK0624** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

해결됐습니다!
