### ISSUE TITLE
작업의 우선순위를 정할 수 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4011]
작업이 하나가 오래 걸릴 것 같다면 그 작업 우선순위를 마지막으로 미룬다던가, 아니면 하나를 지금 당장 다운받고 싶다던가, 이거를 지금 하는 작업 바로 다음에 하고 싶다던가 이런식으로 정할 수 있으면 좋겠습니다.

저는 cpu 우선순위 정하듯이 정할 수 있으면 좋을 것 같다고 생각합니다만...

**Comment by HwNnhji** [comment]
![image](https://user-images.githubusercontent.com/74286087/141480592-1c38fc84-bce2-4300-8203-5b30b6bbbdbb.png)

**Comment by KurtBestor** [comment]
우선순위는 줄 순이고 높이고 싶으시면 드래그해서 아래로 내리시면 돼요.
