### ISSUE TITLE
f3 필터에서 or 검색(?)도 됐으면 좋겠습니다.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#4046]
artist:1|artist:2 / **북마크** artist:1|artist:2

이런 식으로 됐으면 좋을 것 같습니다.

유튭 다운해서 더 많이 보게 됐는데 같은 사람이

채널을 분리하는 경우가 많아서 묶어 놓고 싶어서 그렇습니다.

그리고 아이콘 눌렀을 때 해당 링크로 이동을 팝업 없이 열 수 있는 옵션이 있으면 좋겠습니다.

다운로드해서 광고는 안보도 있지만 광고는 나오게 해놓고 있는데 이동하시겠습니까에서 한번 더 누르기 번거롭더라고요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

다음과 같이 하면 돼요: `artist:1 OR artist:2`

**Comment by DBdeepsleeper** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> 
> 다음과 같이 하면 돼요: `artist:1 OR artist:2`

오. 잘 됩니다. 베타에 적용된 거 몰랐다가 오늘 우연히 확인했네요.

고맙습니다.
