### ISSUE TITLE
제목 길이가 길면 잘라주는 기능이 있으면 좋을것 같습니다.

### ISSUE THREAD

**Issue by gudwls5022** [KurtBestor/Hitomi-Downloader#4059]
히토미에 굉장히 길게 제목이 올라온건 다운로드가 안되는 증상이 있습니다. 아마 윈도우 경로 255자 제한 떄문인거 같습니다..
히토미에서 다운로드로 받아보면 긴 파일 제목은 물결표시로 자동으로 생략이 되서 받아지는 식이더군요. XXX~식으로요.

참고해주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by gudwls5022** [comment]
확인해보니, 윈도우에서는 레지스트리 수정을 통해서 255자 제한을 풀수 있어 다운로드가 가능한데 리눅스는 255제한을 풀 방법이 없는거 같네요. 제가 nas로 다운로드 한 자료를 저장중인데 거기서 생기는 문제 같습니다. 윈도우 다운로드 후 전송도 파일길이 초과로 되지 않습니다.

혹시 추후에 제목길이 조정 같은것이 옵션 등으로 추가되면 매우 좋을 것 같습니다.
프로그램 항상 잘 쓰고 있습니다. 감사합니다.

[로그.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/7593983/default.txt)

**Comment by KurtBestor** [comment]
113 자이고 255 자 안 넘네요.

255 자 넘으면 자르는 기능은 이미 적용되어있어요.

**Comment by gudwls5022** [comment]
그렇군요. 파일이름만 줄여서 수정해서 넣어주면 되긴 하는데.. 한 50개 정도 파일정도가 이 증상으로 에러가 나있길래 다 수정해서 넣어줬거든요..
뭔가 다른문제가 있는건지... 괜히 귀찮게 만들어드려 죄송합니다.
