### ISSUE TITLE
몇 개의 영상은 다운 받았을 때 2시간만 다운 받아집니다

### ISSUE THREAD

**Issue by rudestar12** [KurtBestor/Hitomi-Downloader#4102]
다른 2~4시간 영상이나 길이가 긴 영상들은 다운 받아도 괜찮은데
특정한 영상(길이 2시간 22분)을 다운 받았을 때 2시간만 다운받아집니다

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by rudestar12** [comment]
최신버전으로 다시 깔고 쿠키 직접 따니까 해결되었네요 쿠키 문제 였던거 같아요 감사합니다
