### ISSUE TITLE
혹시 프로그램에 매크로 방지 처리가 되어있나요?

### ISSUE THREAD

**Issue by lakals** [KurtBestor/Hitomi-Downloader#4168]
자작으로 만든 검색 프로그램과 붙여서 자동화를 하려고 했는데, 계속 막히네요.

메모장이나 기타 프로그램에는 잘 입력되는 매크로 코드가 이 프로그램상에서는 전혀 입력이 되지 않습니다.
pyautogui, pywinauto 등을 사용해서 자동화를 시도했습니다만 전부 안되네요.

혹시 막아놓으신 것인가 해서 질문드립니다.
매크로 등의 사용을 원치 않으셔서 막아놓으신 것인가요?

**Comment by lakals** [comment]
아 예전 이슈를 미처 확인 못했네요. 매크로 프로그램을 관리자 권한으로 해야 실행되는군요....?
어... 원리가 전혀 짐작이 안가는데, 혹시 괜찮으시다면 어떤 원리인지 (보안 라이브러리?) 알려주신다면 정말 감사하겠습니다.

이슈는 해결되었는데 기술적으로 너무 궁금해서요

**Comment by KurtBestor** [comment]
윈도우 UAC 정책이에요
