### ISSUE TITLE
기본 데이터 다운로드를 해도 검색 범위가 오르질 않습니다.

### ISSUE THREAD

**Issue by 123cmdcmd** [KurtBestor/Hitomi-Downloader#4180]
안녕하세요.
항상 프로그램을 운영해 주셔서 감사합니다.
다름이 아니고 기본 데이터 다운로드를 해도, 2090799에서 머물러, 새로 나온 작품들이 검색 되지 않고 있습니다.
고쳐 주시길 부탁드리고 항상 건강하세요. ㅅㅅ

**Comment by pupil1223** [comment]
저도 최신 베타 클라이언트에서 동일한 문제 발생 중이네요

**Comment by Drillmurata** [comment]
저도 검색기 기본 데이터 갱신이 안되네요

**Comment by 123cmdcmd** [comment]
해결됬습니다.
