### ISSUE TITLE
히토미 다운이 안 됩니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#4226]
1.히토미 다운이 안 됩니다

2,그간 1초에 1장?만 다운된다는 소릴 어디서 듣고
동시 다운로드도 1개씩만 되게 해놨는데
안 되고 있습니다

파일정보는 너무 길어서 붙여넣기를 못 했습니다 ㅠㅠ

3.아래 게시글 보니까 6시간 전에는 되었다고 뜨는데...
히토미에서 막은건지 모르겠습니다

**Comment by Shrimpizza** [comment]
저도 또 무한로딩이네요

**Comment by mastaer88** [comment]
한시간 전쯤엔 정삭 다운로드 했어요 
아무래도 히토미 자체에 문제가 있는거 같아요 
그냥 페이지 들어가서 다운로드 클릭해도 로딩만하지 다운로드는 하지 않더라고요

**Comment by NULL7889** [comment]
코믹마켓 열리고 히토미 서버가 폭주했다는 소식을 들었네요. 지금은 잘 되요.

**Comment by q2343454** [comment]
또 안 되고 있습니다
