### ISSUE TITLE
베타 버전 다운이 어렵게 되어있습니다

### ISSUE THREAD

**Issue by q2343454** [KurtBestor/Hitomi-Downloader#4239]
1.릴리즈 페이지에는 정식 버전만 보이고

2.Technical Preview ? 기술 미리보기? 베타버전?
이건 노출이 안 되고 있습니다;;

3.링크가 지금
https://github.com/KurtBestor/Hitomi-Downloader/releases
이게 정식 버전들이고

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
이게 베타버전인거 같은데

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag
여기까지는 찾아 가겠는데?

tag/Technical-Preview
태그에서 기술 미리보기까지는 어찌 가는지 버튼 하나도 없는거 같습니다;;

4.그러니까 제작자님이 열심히 댓글에 테스트 부탁드려요~ 하고 달고다니는 링크를
그냥 공지에 때려? 박으시고
최신 베타 버전은 여기로 올라옵니다! 정식에서 안 되면 베타 버전 받아보세요!
이렇게 알기 쉽게 공지에 때려? 박으시면

5.여러사람이 편하지 않을까요...?

**Comment by KurtBestor** [comment]
테스트 버전은 말 그대로 정식 버전이 아니기 때문에 따로 노출시키지는 않고 있어요. 대부분의 소프트웨어가 따르는 정책이에요
