### ISSUE TITLE
방금 업데이트 했는데 막히네요

### ISSUE THREAD

**Issue by donato-alpa** [KurtBestor/Hitomi-Downloader#4258]
Fatal error detected
Failed to execute scrift hitomi_dowloader_GUI

다운로드 하고 나면 상기한 문구가 뜨면서 실행이 안돼요.

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by donato-alpa** [comment]
> 매매법?
백신 목록에는 microsoft defender만 떠요

**Comment by KurtBestor** [comment]
마지막으로 실행되는 버전이 몇인가요?

**Comment by KurtBestor** [comment]
실행되는 가장 최신 버전이 어떤 건가요?

**Comment by donato-alpa** [comment]
> 가장 최근에 실행되는 최신 버전의 주문이 있습니까?
마지막으로 실행 했던 게 3.7e 이에요.

**Comment by KurtBestor** [comment]
[v3.7f](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.7f), [v3.7g](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.7g) 는 어떤가요?

**Comment by donato-alpa** [comment]
> [v3.7f](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.7f) , [v3.7g](https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/v3.7g) 는 어떤가요?

3.7g에서 상기한 문구가 뜨는 문제가 있고요, 3.7f는 어떻게 실행하는지 몰라서 확인이 안돼요.

**Comment by KurtBestor** [comment]
그냥 링크 클릭하고 압축 풀고 실행하면 돼요

**Comment by donato-alpa** [comment]
> 링크를 클릭하면 풀고가 됩니다.

3.7f는 실행이 되요.

**Comment by donato-alpa** [comment]
> 링크를 클릭하면 풀고가 됩니다.

그래도 프로그램은 실행되지만 히토미 다운은 안돼네요.
