### ISSUE TITLE
카쿠요무 다운로드 불가

### ISSUE THREAD

**Issue by Im-IKAROS** [KurtBestor/Hitomi-Downloader#4262]
다운로드가 가끔 불가할때가 있습니다. 왜 그런건가요?
https://kakuyomu.jp/works/1177354054886705922 이사이트가 다운로드가 테스트 버전에서도 안되고 정식에서도 다운이 안됩니다.
Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354054886705922

version: 3.7d (21-11-23 09:35:28 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 7 / False / d47af95eac724ac789f4e2a1e5f2303a
input: https://kakuyomu.jp/works/1177354054886705922
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354054886705922
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1641293696.316034 (1월 4일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 105, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354054886705922  (9.5s)

'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1140, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 105, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354054886705922  (1.2s) 작업정보 긇어보았습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Im-IKAROS** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다. 매우 감사합니다.
