### ISSUE TITLE
DPI 우회가 작동하지 않는 것 같습니다.

### ISSUE THREAD

**Issue by Coniglio17854** [KurtBestor/Hitomi-Downloader#4281]
// 다른 비슷한 이슈에서 해결 사례가 있는지 찾아보고 있는데 없는 것 같아 올립니다.

폰허브에 접속 및 다운로드가 되지 않고 있습니다.
내장되어 있는 DPI 우회를 사용하거나 GoodbyeDPI GUI를 사용해도 마찬가지인 상태입니다.

다른 프로그램인 Secret DNS 를 사용해도 접속이 되지 않고 있네요.
정부의 차단과 관련된 내용이 강화되어 DPI 우회가 안되는 것일까요?

아래는 작업 정보입니다.

Invalid: [pornhub] https://www.pornhub.com/view_video.php?viewkey=ph61c44f99cbe1b

version: 3.7h (22-01-08 05:26:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / a674ee7e48ef4c78a55107e53fbce20b
input: https://www.pornhub.com/view_video.php?viewkey=ph61c44f99cbe1b
type: pornhub
single: True
url: https://www.pornhub.com/view_video.php?viewkey=ph61c44f99cbe1b
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1641699344.1677825 (1월 9일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2021.12.27
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
id: ph61c44f99cbe1b
Video
id: ph61c44f99cbe1b
Video
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\pornhub_downloader", line 400, in read
 File "utils", line 781, in __call__
 File "<decorator-gen-33>", line 2, in get
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "extractor\pornhub_downloader", line 126, in get
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://www.pornhub.com/view_video.php?viewkey=ph61c44f99cbe1b  (46.0s)

**Comment by KurtBestor** [comment]
GoodbyeDPI 문제는 [여기](https://github.com/ValdikSS/GoodbyeDPI/issues)에 보고해주세요

**Comment by Coniglio17854** [comment]
DPI를 사용하지 않고 VPN을 킨 상태에서는 사이트 접속, 영상도 재생이 되는데 다운로더로 다운이 되지 않는데 이 부분도 도움을 받을 수는 없나요?

**Comment by KurtBestor** [comment]
먼저 GoodbyeDPI 에 묻는 게 맞지 않을까요?
