### ISSUE TITLE
히토미 다운로더 기능 추가 건의(검색범위 개선)

### ISSUE THREAD

**Issue by ddt5244** [KurtBestor/Hitomi-Downloader#4306]
전에 검색기 히토미 작품 업로드 날짜 표시 건의했던 사람입니다.

검색기 맨 위에 검색범위가 있는데 숫자가 페이지수를 의미하는거 같은데 이러면 특정 날짜가 어느 페이지인지

알기가 힘들어서 사실상 기능의 의미가 크게 없는거 같습니다. 그래서 검색범위를 년월일을 기입해서 검색하게 된다면

정말 편하고 좋을거 같습니다. 이 생각을 하게 된 이유는 예로 1달전 작품을 검색하려면 하루에 약 30개씩 작품이 나오다보니까

900개나 검색해야 하는데 이러면 컴퓨터 자원을 상당히 잡아먹는거 같고 컴퓨터가 안좋으면 렉이 걸리는 현상이 나와서 1달전 

작품을 검색하기가 굉장히 불편하거나 불가능할거 같아서 건의드려봅니다. 감사합니다.

**Comment by hny2798** [comment]
제가 제작자님은 아니고 제가 못 찾은걸수도 있지만 히토미 검색하는 데이터 json 보시면 
검색 리스트에 날짜가 없어서 체크가 불가능할것 같아요
이건 핸드폰 번호 가지고 생년월일 알려달라는거랑 비슷한거거든요

**Comment by ddt5244** [comment]
아 그런가요 불가능하다면 검색범위에 있는 숫자가 정확히 무엇을 의미하고 내가 원하는 날짜의 작품이 대략 어느정도의 위치에 있을지 알수있게만 해주시면 좋을거 같습니다.

**Comment by ddt5244** [comment]
> 전에 검색기 히토미 작품 업로드 날짜 표시 건의했던 사람입니다.
> 
> 검색기 맨 위에 검색범위가 있는데 숫자가 페이지수를 의미하는거 같은데 이러면 특정 날짜가 어느 페이지인지
> 
> 알기가 힘들어서 사실상 기능의 의미가 크게 없는거 같습니다. 그래서 검색범위를 년월일을 기입해서 검색하게 된다면
> 
> 정말 편하고 좋을거 같습니다. 이 생각을 하게 된 이유는 예로 1달전 작품을 검색하려면 하루에 약 30개씩 작품이 나오다보니까
> 
> 900개나 검색해야 하는데 이러면 컴퓨터 자원을 상당히 잡아먹는거 같고 컴퓨터가 안좋으면 렉이 걸리는 현상이 나와서 1달전
> 
> 작품을 검색하기가 굉장히 불편하거나 불가능할거 같아서 건의드려봅니다. 감사합니다.

**Comment by hny2798** [comment]
> 아 그런가요 불가능하다면 검색범위에 있는 숫자가 정확히 무엇을 의미하고 내가 원하는 날짜의 작품이 대략 어느정도의 위치에 있을지 알수있게만 해주시면 좋을거 같습니다.

이미 닫으시긴했지만 사족 달아봅니다
저 id번호가 그냥 게시글 번호 같은걸겁니다
따로 의미있는 숫자가 아니라요
예를 들어 가장 최근에 올라간 게시글의 번호가 12345라면 새로 자료 올라오면 12346이 붙는거죠
거기엔 날짜라던가 아무 정보가 없어서 
 만약 꼭 필요하다면 가능할지는 모르겠지만
앞으로는 기본 검색 데이터를 다운로드 할때 따로 날짜값(date)를 가져와야 할겁니다 
전에 어디 글에서 히토미 검색용 데이터 그대로 가져온거라고 들은거 같은데
만약 그렇다면 날짜가 없기때문에 날짜값을 줄지는 모르겠지만
검색 데이터 다운로드 할때마다 
백만단위의 모든 자료를 한번씩 다운로드 시도나 시그널을 보내서 날짜 값을 받아와야 할겁니다
그러면 검색데이터 다운로드시 42개 파일을 받는걸로 끝나는게 아니라 작성 기준 2,113,508까지 매겨진 번호(지워진거 감안하더라도 100만개 이상)를 기반으로 날짜 값 가져오고 검색데이터에 매칭해서 12345번 작품에는 2022년 1월1일 01:23분에 작성한거라고 붙여줘야 합니다
그나마 검색 데이터를 다운로드 하고 나면 검색 알고리즘은 같고 항목만 늘어난거니 검색 자체야 엄청 큰 차이가 없겠지만
기본 검색 데이터 다운로드만 해도 1~2분이 아니라 십수분이상의 어마어마한 시간이 걸릴것같네요
