### ISSUE TITLE
j마나 주소 바뀌고 다운이 안되네요

### ISSUE THREAD

**Issue by elina7** [KurtBestor/Hitomi-Downloader#4326]
제이마나 주소가 바뀌고 다운이 안됩니다
현재 주소는 https://3.jjmana.net/ 네요
수정 부탁드려요

**Comment by KurtBestor** [comment]
해당 작업 내용 보여주세요

**Comment by elina7** [comment]
> 해당 작업 내용 보여주세요

9분 56초 뒤 다시 시작: https://3.jjmana.net/book?bookid=16577

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 0 / False / 1854db56067f497c81f610e10afb4a20
input: https://3.jjmana.net/book?bookid=16577
type: jmana
single: False
url: https://3.jjmana.net/book?bookid=16577
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643025105.1363628 (1월 24일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1175, in start
 File "utils", line 1245, in start_
 File "extractor\jmana_downloader", line 87, in read
 File "extractor\jmana_downloader", line 81, in name
 File "extractor\jmana_downloader", line 104, in get_title
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://3.jjmana.net/book?bookid=16577  (14.6s)

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 누르고 해당 링크 들어가면 어떻게 뜨나요?

**Comment by elina7** [comment]
> 

This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

**Comment by elina7** [comment]
> This site can’t be reachedThe connection was reset. Try:
> 
> Checking the connection Checking the proxy and the firewall ERR_CONNECTION_RESET



> `옵션 - 설정 - 고급 설정 - 내장 웹브라우저 - 보기` 누르고 해당 링크 들어가면 어떻게 뜨나요?

This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

**Comment by KurtBestor** [comment]
옵션에서 `DPI 우회`를 켜세요

**Comment by elina7** [comment]
> 옵션에서 `DPI 우회`를 켜세요

유니콘https 쓰고있었는데 이젠 그걸론 안되나보네요...
유니콘 끄니 되네요 감사합니다

**Comment by elina7** [comment]
> 옵션에서 `DPI 우회`를 켜세요

일단 저 게시물은 다운로더 우회만 켜면 되긴 하는데 다른것들 더 받아보니 둘다 켜야하는것도 있고 유니콘만 켜야하는것도 있고 혼파망이네요... 이건 사이트 문제이려나...
