### ISSUE TITLE
추가 요청입니다

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4328]
1. f1 통계 들어가면 작업 용량 볼 수 있는데, 총 용량도 볼 수 있게 해주실 수 있으십니까?

2. 토렌트 다운받을 때 utorrent같은 다운로더에서 특정 파일만 다운받을 수 있던게 기억나서 요청드립니다만 다운 받기 전 어떤 파일 다운받을지 선택하게 해 주실 수 있으십니까?

**Comment by KurtBestor** [comment]
일단 1번만 구현했어요.

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
감사합니다. 잘 작동 합니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/200625341-252a77dc-d8d2-4a09-b924-8dd3948639ed.png)


테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
감사합니다.
