### ISSUE TITLE
스크롤바 활용

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4331]
다운받을 걸 옮길 때 컨트롤 사용해서 end나 home으론 옮길 수 있는데 그 중간 지점은 마우스 휠을 사용하거나 끝쪽으로 걸치는 식으로 옮기는 거로는 조금 시간이 오래 걸려서 애매하기에 질문드립니다.

옮길 걸 순서변경으로 드래그 하여 대강 옮기고 싶은 위치에 가까운 스크롤바 지점 위에 올린 후, 그 상태로 몇초 정도 있으면 그곳으로 이동하게 해주실 수 있으신가요?

**Comment by KurtBestor** [comment]
다음과 같이 하면 돼요:

1. 옮기고 싶은 위치에 있는 작업과 옮길 작업들에 임시로 태그 닮

1. F3 눌러서 그 태그로 필터링

1. 드래그해서 옮김

**Comment by hwnnhji** [comment]
그럼 태그의 개수를 늘려주실 수 있으신가요? 사용자가 직접 색깔을 정해서 사용할 수 있게 하시면 7개 이상으로 늘릴 수 있을 것 같습니다. 저는 이미 7개가 부족할만큼 태그를 활용하고 있어서...

**Comment by KurtBestor** [comment]
태그를 사용할 수 없다면 코멘트를 쓰시면 돼요

**Comment by hwnnhji** [comment]
아우 감사합니다
