### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4333]
저사양 모드로 켤 때, 다운로더가 최소 800 최대 1500메가 정도 램을 먹습니다. 작업을 한두개 정도 한다고 하면 평균 900메가 정도 먹는 것 같습니다.

궁금한 건 작업을 많이 돌려서 1500메가 정도까지 먹었을 때 작업이 모두 완료되면 다시 900메가 정도로 떨어져야 당연히 이치에? 맞는 것 같은데 1500을 계속 유지한 상태로 갑니다. 작업관리자에서 확인을 하였습니다. 
하던 작업이 다 끝나서 크게 메모리 잡아먹을 게 없는 것 같은데 왜 메모리가 떨어지지 않는 건가요?

**Comment by KurtBestor** [comment]
재현할 수가 없네요. 저사양 모드에서만 발생하는 현상인가요?

**Comment by hwnnhji** [comment]
아뇨 저사양 끄고 해도 작업을 많이 실행한 이후엔 적어도 1.5기가를 유지합니다.

**Comment by hwnnhji** [comment]
아무래도 메모리를 많이 먹기에 라소로 메모리 트림을 한 상태인데, 괜찮을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/4285#issuecomment-1008572542

**Comment by hwnnhji** [comment]
프로그램 용량 많이 먹는 게 스트레스 받길래 지금은 그냥 메모리를 64기가로 올려서 사용중이긴 합니다만, 

https://github.com/KurtBestor/Hitomi-Downloader/issues/4285#issuecomment-1008572542

이거 참고한다고 해도 딱히 해결되는 건 없지 않나요,,?

얼마전에 엄청 다운로드 하면서 이 프로그램 하나가 램을 13기가를 먹었던 기억이 있는데 램을 엄청 많이 먹는 건 어떻게 해결하야 하지 않나 싶어서요. 파이썬으로 짜신 거 같은데 해결은 가능할까요?

**Comment by KurtBestor** [comment]
재현할 수 없는데 해당 설정 파일 보내주세요
