### ISSUE TITLE
제목 오류?

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4359]
xvideo에서만 이런건 진 모르겠지만, 다운을 받았을 때 제목 내 apostrophe,, 따옴표 라고 하나요? ' 이 표시가 있으면 ≈os; 이렇게 제목을 인식합니다만..

사소한거라 상관 없나 싶긴 했는데 문제 생길수도 있나 싶어서 올립니다.

![image](https://user-images.githubusercontent.com/74286087/150788978-28718ccf-5118-489c-8896-43f048287908.png)

**Comment by KurtBestor** [comment]
해당 작업 내용 보여주세요

**Comment by hwnnhji** [comment]
I≈os;m looking for an uncensored version of this Gonzo.

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko
order / group / uid: 4579 / False / d91fccb872414ab78fd9736389bec297
input: https://www.xvideos.com/video48140963/_
type: xvideo
single: True
url: https://www.xvideos.com/video48140963/_
dir: hitomi_downloaded_xvideo
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1642702741.4520044 (1월 21일)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]
[0001] hitomi_downloaded_xvideo\I≈os;m looking for an uncensored version of this Gonzo. (48140963).mp4


[URLs]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
