### ISSUE TITLE
[Feature] Personalize path for each artisit

### ISSUE THREAD

**Issue by ZorroGuevara** [KurtBestor/Hitomi-Downloader#4361]
Hello, I'd like to personalize some folders. My user case is pretty basic for example:
* R18: C:\R18
* SFW: C:\SFW

**Comment by KurtBestor** [comment]
Can you provide more detail?

**Comment by ZorroGuevara** [comment]
Sure.  Right now my files are saved into D:\\Pixiv\Artist however I'd like to *choose* for particular artist where to save them, this means I'd like be asked where to save stuff or have option to say: save it to path 1 / save it to path 2.

Not sure if it's clear.

**Comment by KurtBestor** [comment]
You can change the path manually by `Right click on the task` - `Edit task... (F2)` - `Folder`

**Comment by KurtBestor** [comment]
You can change the path manually by editing `Right click on the task` - `Edit task... (F2)` - `Folder`

**Comment by ZorroGuevara** [comment]
Good lord I'm so stupid, thanks.
