### ISSUE TITLE
Error : Artist name is numeric

### ISSUE THREAD

**Issue by mukapa** [KurtBestor/Hitomi-Downloader#4363]
This case is artist name is numeric.
And Hitomi-Downloader can't start download.
Please check and update.
If it is difficult, in case of input artist name manually,
skip the artist name check.
Thank you.

한국어를 하시는 분이었네요.
혹시 영작이 잘못되었을까 하고 적어봅니다.
작가 이름이 숫자면 다운로드가 안되네요.
작가 이름을 수동으로 입력하면 작가명 확인을 하지 않게 수정해주시면 좋겠습니다. 
(혹은 숫자도 인식해서 넘어가면 좋겠네요..)
고맙습니다.

--- Error log ---

Invalid: [navertoon] https://comic.naver.com/webtoon/list?titleId=729563

version: 3.7h (22-01-04 07:19:22 UTC)
platform / locale: Windows-10-10.0.18362-SP0 / ko
order / group / uid: 0 / False / 17d4ca65779d4a0bab8216317924734c
input: https://comic.naver.com/webtoon/list?titleId=729563
type: navertoon
single: False
url: https://comic.naver.com/webtoon/list?titleId=729563
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1643097320.0887403 (1월 25일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
artist not found
stop
Traceback (most recent call last):
 File "extractor\navertoon_downloader", line 104, in get_pages
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1161, in start
 File "extractor\navertoon_downloader", line 45, in init
 File "<decorator-gen-22>", line 2, in get_pages
 File "constants", line 927, in wrapper
 File "constants", line 898, in wrapper
 File "extractor\navertoon_downloader", line 112, in get_pages
Exception: artist not found

Invalid: fail=True
EOT: https://comic.naver.com/webtoon/list?titleId=729563  (1.8s)

**Comment by KurtBestor** [comment]
19세 제한 작품은 쿠키를 넣어야 작동해요

**Comment by mukapa** [comment]
쿠키 문제가 맞네요. (작가 이름 문제 아님.)
히토미 다운로더에서 F1 누르고 스크롤 내리면 사용법 쭉 있습니다. 다른분들 참고요..
(스크롤 없는줄 알았어요.)
