### ISSUE TITLE
테마 옵션.

### ISSUE THREAD

**Issue by sb2941** [KurtBestor/Hitomi-Downloader#4376]
테마를 실수로 바꿔버렸는데 기본값으로 다시 못돌아가나요?
시스템, 클래식은 바뀌어지는데 기본값은 선택은 되지만 안바뀝니다.
재시작하면 기본 테마가 잠깐동안 비춰지다가 곧바로 시스템이나 클래식 테마로 바뀝니다.

사소한 문제지만 일단 남겨봅니다.

언제나 감사합니다.

**Comment by KurtBestor** [comment]
해당 설정 파일 (*.ini) 보내주시면 분석해볼게요

**Comment by sb2941** [comment]
아, 그거 이전버전 입축 푼 폴더에 ini파일 남아있어서 덮어씌워서 해결했는데 때문에 해당 문제의 ini 파일 날아가버렸네요. 지금은 괜찮습니다 ㅎ... 번거롭게 해서 죄송합니다.
