### ISSUE TITLE
업데이트 이후로 응답 없음이 자주 보입니다

### ISSUE THREAD

**Issue by fpvmflzk** [KurtBestor/Hitomi-Downloader#4377]
주로 처음 실행할때 나타나고 실행 시간도 더 오래 걸리는듯 합니다.

**Comment by KurtBestor** [comment]
어떤 백신 쓰시나요?

**Comment by fpvmflzk** [comment]
> 어떤 백신 쓰시나요?

카스퍼스키를 쓰고 있습니다

**Comment by KurtBestor** [comment]
처음 실행할 때 임시 파일을 생성하는데 백신이 그걸 검사하느라 오래 걸릴거예요
