### ISSUE TITLE
how to install hitomi into a drive, file?

### ISSUE THREAD

**Issue by casey866** [KurtBestor/Hitomi-Downloader#4380]
HI,

hitomi downloader is a good software , works go on windows 7.

but it intalled into a temp file, no option to a specify location, such as  D:/hitomi

thanks

**Comment by KurtBestor** [comment]
You don't need to install, it's a standalone exe file.

**Comment by casey866** [comment]
> You don't need to install, it's a standalone exe file.

many thanks
