### ISSUE TITLE
Luscious invalid 다운로드 불가

### ISSUE THREAD

**Issue by BLUECE** [KurtBestor/Hitomi-Downloader#4386]
Invalid: [luscious] https://www.luscious.net/albums/ryuus-world-of-warcraft_107966/

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / e3502283913849d9ba8a91624c3df57f
input: https://www.luscious.net/albums/ryuus-world-of-warcraft_107966/
type: luscious
single: False
url: https://www.luscious.net/albums/ryuus-world-of-warcraft_107966/
dir: 
zip: 
artist: None
valid / done: False / False
range / range_p: None / None
time: 1643408308.525885 (1월 29일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.01.21
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
retry...
retry...
retry...
retry...
retry...
retry...
retry...
retry...
No active exception to reraise
stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\luscious_downloader", line 58, in read
RuntimeError: No active exception to reraise

Invalid: fail=True

이런 식으로 갑자기 invalid 뜨고 다운로드가 불가능합니다. 최신버전 업데이트 되어도 똑같네요 ㅠ

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by BLUECE** [comment]
잘 됩니다. 감사합니다.
