### ISSUE TITLE
건의) 네이버 블로그 전체 다운로드

### ISSUE THREAD

**Issue by heonchul** [KurtBestor/Hitomi-Downloader#4391]
네이버 블로그 각 게시글을 다운하는 기능은 있지만, 
블로그 전체의 모든 게시글을 다운하는 기능은 현재 없습니다.
대체 가능한 다른 프로그램도 찾아봤으나 없었습니다.
유튜브의 채널의 모든 영상을 다운하듯 블로그도 전체다운이 가능했으면 좋겠습니다.

1. 블로그 전체의 게시글 (혹은 적어도 카테고리 전체)
2. 첨부파일, 영상, 이미지 (최소한 이미지는 꼭)

프로그램 정말 잘 사용하고 있고
언제나 빠르고 꾸준한 버그수정 감사드립니다.

**Comment by dadawwa** [comment]
안녕하세요.
네이버 블로그 전체 다운로드 or 카테고리별 다운로드 기능은 아직 추가하실 예정은 없으실까요?
