### ISSUE TITLE
카쿠요무 다운로더가 안됩니다.

### ISSUE THREAD

**Issue by Im-IKAROS** [KurtBestor/Hitomi-Downloader#4445]
https://kakuyomu.jp/works/1177354054935284889 이사이트를 다운로드 받으려고 했더니 다운로드가 진행이 되질 않습니다.
예전에 만들어 주신 3.7h ver으로 테스트 해보아도 똑같습니다. 어떻게 고치면 되는걸까요?
Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354054935284889

version: 3.7h (22-01-08 05:26:06 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko
order / group / uid: 1 / False / 80f822c47a594199869ab5a69c5747a3
input: https://kakuyomu.jp/works/1177354054935284889
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354054935284889
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1644155124.9912467 (2월 6일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "extractor\kakuyomu_downloader", line 38, in init
 File "extractor\kakuyomu_downloader", line 106, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354054935284889  (29.2s)

이런문제가 뜹니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Im-IKAROS** [comment]
감사 매움 감사 합니다.
