### ISSUE TITLE
틱톡 영상 다운로드가 30개까지 밖에 안됩니다

### ISSUE THREAD

**Issue by FiitCoolShot** [KurtBestor/Hitomi-Downloader#4454]

**Comment by KurtBestor** [comment]
`옵션 - 설정 - 고급 - 내장 웹브라우저 - 보기` 누르고 해당 페이지 들어가서 스크롤 아래로 내려보세요

**Comment by FiitCoolShot** [comment]
> `옵션 - 설정 - 고급 - 내장 웹브라우저 - 보기` 누르고 해당 페이지 들어가서 스크롤 아래로 내려보세요

되네요 감사합니다!
