### ISSUE TITLE
트위터 페이지 개별 다운로드 안되는 문제

### ISSUE THREAD

**Issue by wnfflsskf** [KurtBestor/Hitomi-Downloader#4460]
https://twitter.com/*** 이런 식의 전체 다운로드는 문제가 없는데

https://twitter.com/***/status/숫자 이런 형식의 개별 페이지 다운로드는 몇몇개가 열린 계정인데도 쿠키를 요구하며 다운로드가 되지 않고, 쿠키를 업데이트해줘도 마찬가지입니다.

Login required; Update your cookies
https://twitter.com/kank06020602/status/1489966724154036225/photo/1

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / da95dc93a0c048619fe6a36f3ba709df
input: https://twitter.com/kank06020602/status/1489966724154036225/photo/1
type: twitter
single: False
url: https://twitter.com/kank06020602/status/1489966724154036225/photo/1
dir: 
zip: 
artist: らす
valid / done: False / True
range / range_p: None / None
time: 1644387185.1010687 (2월 9일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.02.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
single tweet
id: 1489629330041110532

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
quality: 100%
EOT: https://twitter.com/kank06020602/status/1489966724154036225/photo/1  (4.7s)

single tweet
id: 1489629330041110532

stop
Traceback (most recent call last):
 File "utils", line 1176, in start
 File "utils", line 1246, in start_
 File "extractor\twitter_downloader", line 89, in read
 File "extractor\twitter_downloader", line 466, in get_imgs_single
errors.LoginRequired

Invalid: fail=False
quality: 100%
EOT: https://twitter.com/kank06020602/status/1489966724154036225/photo/1  (6.6s)

**Comment by hwnnhji** [comment]
나만 그런게 아니었구나...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
