### ISSUE TITLE
webp 파일 이외의 형식 jpg gif 으로 다운로드 하는 방법은 없나요?

### ISSUE THREAD

**Issue by Gunter-Dw-Jung** [KurtBestor/Hitomi-Downloader#4463]
한참동안 안쓰다가 업데이트 이후 처음 써봤는데 모든 파일이 webp로 다운로드 되어버려서 저장후 감상이 힘듭니다

**Comment by ddt5244** [comment]
옵션 > 설정 > 고급에서 이미지 포맷 변환이라는 탭이 있습니다. 그걸 사용하시면 됩니다.

**Comment by Gunter-Dw-Jung** [comment]
> 옵션 > 설정 > 고급에서 이미지 포맷 변환이라는 탭이 있습니다. 그걸 사용하시면 됩니다.

감사합니다 맨 첨에 건드려보고 바로 안바뀌길레 효과 없는줄 알았는데 webp로 받아놓고 나중에 jpg로 바뀌는 군요
