### ISSUE TITLE
썸네일 안뜨는 문제

### ISSUE THREAD

**Issue by whrqkfqkf** [KurtBestor/Hitomi-Downloader#4469]
안녕하세요.언제나 프로그램 잘 이용하고 있습니다.
다운로더에서 다운 자체는 잘 되는데 썸네일이 뜨기까지 시간이 매우 오래 걸립니다.
예전에도 몇 번 이런적이 있었을 때는 테스트 버전을 써서 해결한 적이 있었는데 이번 건은 테스트 버전도 소용이 없네요...
조속히 해결 방안을 요구하는 바입니다.

**Comment by KurtBestor** [comment]
Duplicate of https://github.com/KurtBestor/Hitomi-Downloader/issues/4444
