### ISSUE TITLE
픽시브 움짤 관련

### ISSUE THREAD

**Issue by sosoeun** [KurtBestor/Hitomi-Downloader#4534]
파일을 이동시키고 다시 다운 받을 때 이동된 파일은 다시 다운 받아지지 않는게 정상인데 gif는 다시 받더라고요 원래 이런 건가요?

파일 변환 속도를 더 빠르게 할 수 있는 방법이 있을까요?

감사합니다..

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by sosoeun** [comment]
완벽합니다 감사합니다🍕
