### ISSUE TITLE
Software get banned by korean site

### ISSUE THREAD

**Issue by SAOJSM** [KurtBestor/Hitomi-Downloader#4546]
I already tried Afreecatv、Kakao、Naver, and found that the site will response not safe and can't access it when open this software. So download will unsuccess. Please check this issue and respond, thank you.

**Comment by SAOJSM** [comment]
I fixed some error and Naver still get banned after send download request, Afreecatv only download failed when download korea ip only video, Kakao is ok.
![Screenshot_20220307-140302-397](https://user-images.githubusercontent.com/46414240/156977502-308fb138-88da-44ed-a861-afc9149210fb.png)
![Screenshot_20220307-140201-193](https://user-images.githubusercontent.com/46414240/156977505-85415855-9a33-474c-97c3-82d6cb5351be.png)

**Comment by KurtBestor** [comment]
Please post your task info. You can find it on `Right click on the task - Info...`

**Comment by SAOJSM** [comment]
I tried the newest version and try to change settings. It works now, thank you.
