### ISSUE TITLE
갑자기 Err이라고 뜨더니 다운로더가 안열리다가 이후 작업내용이 사라졌습니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4596]
순간 캡쳐할 생각을 못해서 캡쳐는 못했습니다만, 다운로더를 실행하고 아무 작업 하지 않은채로 30분? 1시간 정도 방치하였습니다. 이후 그냥 한번 확인했을 때 빨간색 X표가 뜨면서 'Err'이라고 뜨길래 자세히보기 눌러서 오류상황을 복사해 놨습니다. 이후 혹시 문제생길 까봐 바로 ini파일은 복사 해놓은 상황입니다. 또한

![image](https://user-images.githubusercontent.com/74286087/160429052-686d9df0-4a4c-4fe9-9a22-cfc000736eb6.png)

처음에는 사진처럼 계속 켜지지 않다가 이후 계속 껐다 켜길 반복하니 켜지긴 했습니다만

![image](https://user-images.githubusercontent.com/74286087/160430067-182e773c-f1fc-4d5a-9b48-7af6bcf00118.png)

![image](https://user-images.githubusercontent.com/74286087/160430103-e46f5df0-d36d-4882-8780-29e4ac3b2447.png)

만화랑 유튜브를 제일 많이 다운받는 편인데, 작업 대부분이랑 다른 작업내용 수백개가 지워진 상황입니다.
실제 파일은 삭제되지 않았으며, 작업목록에서만 사라졌습니다.  사라진 개수는 잘 모르겠습니다만 그룹으로 모아놓았던 유튜브 와 만화, 따로 파일 추가한 것 포함 3000개는 넘을거라 생각합니다. 

제발 작업내용을 복구할 수 있었음 합니다.

이후 따로 확인해본 결과 시간 순서대로 지워진 건 아니고, 단순히 작업 순서가 위쪽에 있던 것(혹은 위에 모아놓은 것)들이 지워졌습니다. 위쪽에 작업 정리를 해놨었는데 그거 포함해서 쭉 사라졌네요.

오류 문장은 아래 3개 문장 반복인걸로 확인했습니다. 첫번째랑 세번째꺼가 주로 반복됩니다.

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 3897, in append_datas_
Exception: No data

  File "MyConfigParser", line 78, in get
IndexError: list index out of range

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 1559, in foo
  File "MyConfigParser", line 78, in get
IndexError: list index out of range

https://github.com/KurtBestor/Hitomi-Downloader/issues/3557#issue-941470375

이분 상황이랑 비슷한 것 같습니다. 단지 저는 업데이트를 하지는 않았고, 걸리는 일을 생각해보면 다운로더가 열려있을 때 저장되어 있는 다운로더를 강제종료 한 이후 껐다 키니 이런일이 생기고 있습니다만 강제종료는 가끔 실수로라도 수십 번 해본 일이라 문제가 될진 모르겠습니다.

ini파일은 필요하시면 디스코드로 보내드리겠습니다만 용량이 700메가라 안될 시 구글 드라이브로 공유하겠습니다.

제발 부탁드립니다. 덮어쓰여지지 않게 일부러 바로 ini를 뺀 상황입니다. 복구해주시면 정말 감사하겠습니다.

**Comment by hwnnhji** [comment]
일단 Err 뜬거 확인하고 바로 ini파일을 따로 복사한 이후에 껏다 키기를 반복했는데, 복구할 수 있을까요?

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/163308878-2bbdb39d-eb4b-4bbd-a598-e740be67c6eb.png)
![image](https://user-images.githubusercontent.com/14768120/163308889-240f889d-84ff-4eb8-b40b-401f4806ce9f.png)

확인해봤는데 제 쪽에선 제대로 뜨네요
