### ISSUE TITLE
백그라운드에서만 실행됨

### ISSUE THREAD

**Issue by fpvmflzk** [KurtBestor/Hitomi-Downloader#4612]
ㅈㄱㄴ입니다. 다운로더를 실행하면 백그라운드에서만 실행이 되며 관리자 권한으로 해도 같은 증상이 나타납니다. 이전 문의를 참고해서 백신에서 예외 처리를 하거나 베타 버전으로 해도 똑같네요.

![20220403_231246](https://user-images.githubusercontent.com/73017003/161432851-9413c583-78d2-4384-b82b-e12c49692d7d.png)

**Comment by KurtBestor** [comment]
프로세스 두 개여야 정상인데 Kaspersky `보호 일시 중지` 하고 다시 시도해보세요
