### ISSUE TITLE
Tumblr: Exception: HTML: None

### ISSUE THREAD

**Issue by bog4t** [KurtBestor/Hitomi-Downloader#4645]
When trying to download from tumblr, I'm recieving the error `Exception: HTML: None` for the following blogs:
```
https://botaa.tumblr.com
https://aimf0324.tumblr.com
https://urasanz.tumblr.com
https://natsukusa-mikan.tumblr.com
https://halfmoonstruck.tumblr.com
https://michinoku800.tumblr.com
https://rebelband.tumblr.com
https://aueua.tumblr.com
https://kauzara.tumblr.com
https://09zakka.tumblr.com
https://ggdgart.tumblr.com
https://absoliutely.tumblr.com
https://botaa.tumblr.com
https://daruma-owl.tumblr.com
https://higaaaaaa.tumblr.com
```
I've attached the task info for `https://botaa.tumblr.com`:
 [botaa task info.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/8466640/botaa.task.info.txt)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by bog4t** [comment]
It works now, thank you.
