### ISSUE TITLE
마나토끼 다운이 안 되네요

### ISSUE THREAD

**Issue by getsome23** [KurtBestor/Hitomi-Downloader#4660]
오늘 새벽까진 됐는데 지금은 안 되네요.

Invalid: [manatoki] https://manatoki128.net/comic/11979144

version: 3.7i (22-01-27 02:22:04 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 2ce2931008cf4319aabb61ae8a001c8b
input: https://manatoki128.net/comic/11979144
type: manatoki
single: False
url: https://manatoki128.net/bbs/captcha.php
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1650278421.1113536 (4월 18일)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1162, in start
 File "<decorator-gen-94>", line 2, in init
 File "constants", line 932, in wrapper
 File "constants", line 903, in wrapper
 File "extractor\manatoki_downloader", line 61, in init
 File "utils", line 577, in __get__
 File "extractor\manatoki_downloader", line 77, in name
 File "extractor\manatoki_downloader", line 99, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
EOT: https://manatoki128.net/comic/11979144  (13.5s)

항상 감사드립니다 개발자님

**Comment by midgard104** [comment]
저도 안됐었는데 마나토끼에 로그인한 후에 Get cookies.txt로 쿠키 추출하고 다운로더에 쿠키 넣어주니 정상적으로 다운됨니다.

**Comment by hohoe** [comment]
> 저도 안됐었는데 마나토끼에 로그인한 후에 Get cookies.txt로 쿠키 추출하고 다운로더에 쿠키 넣어주니 정상적으로 다운됨니다.


말씀하신대로 하니 잘 되네요. (평소 가입안하고 봤었는데 결국 가입했네요^_^:)

설명 감사합니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hohoe** [comment]
잘됩니다! 감사합니다!

**Comment by getsome23** [comment]
항상 감사합니다 이슈 닫겠습니다

**Comment by kog200** [comment]
저는 여러분들이한 쿠키도 넣어보고 프리뷰 버전도 해봤는데 다 안되더군요
