### ISSUE TITLE
다운로드 할 폴더 내에 이미 폴더가 있을 시 다운로드 하게 되는 목록 + 알파

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#4682]
얼마 전에 절반 사라진 사람입니다. 디코로 주로 대화했었죠. 기억하실 거라 봅니다.

아무래도 다운로더 내에서의 작업이 사라진거라 실제 사진파일이나, 폴더는 남아있습니다.

일단 1년동안 모아온 것들이기에 여기서 멈추고 다시 다운받지 않을 이유는 없어서 1달만에 다시 프로그램을 키려고 합니다만 이전에 다운받은 것들이 이미 있다면 이걸 활용하면 되지 않나 생각이 들어 질문 드립니다.

일단 첫번째로 작업에 로컬 파일로 부터 새 작업 만들기에 단일 파일을 선택하면 진짜로 파일 하나만 선택할 수 있을텐데, 이거를 파일 여러개를 선택해도 각각 개별 작업으로 생성될 수 있게 해주시면 합니다. 이건 불편한 상황이 꽤나 생길 수 있다고 생각하기에 해주셨음 합니다. 부탁드립니다.

 두번째로 이게 본론입니다. 특정 작업을 할 시에, 그 작업의 다운로드 파일이 어느정도 있는 상태라면 다운로드 폴더 내에 다운로드 파일이 들어 있을 시에, 어디부터 다운로드가 시작됩니까?

가령 히토미 같은 경우는 현재 히토미 기준 webp로 20장 다운로드인데 1~10페이지만 있다던가, 웹툰 같은 경우는 100화 까지 있는데 90화 까지만 다운받아져 있다던가 하는 상황에서입니다.

지금까지의 경험으로는 히토미 같은 경우는 나머지 10페이지를 그냥 다운받고 말지만, 
만화는 작업만 삭제했다 다시 다운받아 본 적이 없기에 알고 있는 사실만 말하자면 이미 다운로드 된 파일이 있음에도 다시 1화부터 100화까지 스캔을 하고 나머지 없는 파일들을 다운받더군요. 예전엔 안이랬는데 어느순간부터 1화부터 다시 스캔을 한다고 생각했었습니다.

스캔은 필요한 작업이라고 봅니다. 하지만 이미 다운로드 된 파일이 있음에도 다시 1화, 2화, 3화, 4화,,, 하루종일 다운로드 받는 것은 사양입니다. 그래서 질문드립니다. 이미 있는 작업은 건너뛰고 다운로드 되는 겁니까? 어디부터 다운로드가 시작됩니까?

**Comment by KurtBestor** [comment]
단일 파일 여러 개 고를 수 있도록 했어요.
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

여러 화가 한 링크에 들어있는 경우라면 필요한 화만 다운로드해요

**Comment by hwnnhji** [comment]
항상 감사드립니다.
