### ISSUE TITLE
ArtSastion 질문 드립니다 

### ISSUE THREAD

**Issue by keroberos-s** [KurtBestor/Hitomi-Downloader#4690]
폴더명 형식을 **[artist][group][series] title (id)** 로 지정하고 다운로드를 하였으나
결과물이 **[날짜]아이디.jpg**로만 나타나는것 같습니다. 고쳐주실 수 있으신가요?
![제목 없음](https://user-images.githubusercontent.com/71687755/164975717-595c3833-c0f9-4237-b049-6c107659dec4.jpg)
[log.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/8549616/log.txt)

**Comment by KurtBestor** [comment]
`파일명 형식`이 아니라 `폴더명 형식`이고 ArtStation 파일명은 고정이에요

**Comment by keroberos-s** [comment]
아! 픽시브랑 헷갈렸네요 답변 감사합니다..

**Comment by keroberos-s** [comment]
아! 픽시브랑 헷갈렸네요 답변 감사합니다..
