### ISSUE TITLE
노벨피아 쿠키문제가 다시 생겼습니다

### ISSUE THREAD

**Issue by lmn999** [KurtBestor/Hitomi-Downloader#4737]
지속적인 업데이트 감사드립니다 항상 잘쓰고있습니다

#4713  의 스캔 짤리는 문제는 정상적으로 해결돼서 스캔은 끝까지 되는것같은데 
이전에 테스트버전에서 해결됐던 쿠키업뎃하라는 에러가 다시 생겼습니다
테스트버전을 받은 페이지는 어디였는지 잊어버려서 다시 찾을수 없었습니다;
버전은 3.7i로만 표기되어있었습니다

작업내용 첨부합니다

Login required; Update your cookies
https://novelpia.com/novel/50356

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 13 / False / 2b2df90ba4d244619fb4de05ec1a5562
input: https://novelpia.com/novel/50356
type: novelpia
single: False
url: https://novelpia.com/novel/50356
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
time: 1651851941.7950578 (22-05-06 15:45:41 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.04.08
pinned: False
extras: {}
live: False
changed: False

[Gallery]
None

[File Names]

[URLs]

[Messages]
Ignored because the next item could not be fetched because there was no logged in cookie: 1193571
Ignored because the next item could not be fetched because there was no logged in cookie: 1196878
Ignored because the next item could not be fetched because there was no logged in cookie: 1200333
Ignored because the next item could not be fetched because there was no logged in cookie: 1218713
Ignored because the next item could not be fetched because there was no logged in cookie: 1242545
Ignored because the next item could not be fetched because there was no logged in cookie: 1245614

stop
Traceback (most recent call last):
 File "utils", line 1183, in start
 File "utils", line 1253, in start_
 File "extractor\novelpia_downloader", line 207, in read
errors.LoginRequired

Invalid: fail=False
EOT: https://novelpia.com/novel/50356  (27.7s)

**Comment by KurtBestor** [comment]
@SaidBySolo

**Comment by SaidBySolo** [comment]
해당 작업 다시시도시 ``Exeption: Rate limit``이 발생하나요?

**Comment by lmn999** [comment]
아뇨 Messages 이후가 다시한번 반복될뿐입니다

**Comment by SaidBySolo** [comment]
한번 확인해볼게요.

노벨피아를 제가 사용해본적이 없어서 재현하는데 어려움이 있을수도있을것같네요
