### ISSUE TITLE
ini 파일 경로를 따로 지정하는 방법이 없을까요?

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader#4750]
ini 파일을 따로 네트워크 드라이브에 보관하고 싶은데
물론 exe파일도 네트워크에 보관해서 실행하면 되긴합니다만
실행속도에 차질이 있기에

**Comment by KurtBestor** [comment]
그렇다면 그 경로를 어딘가에 저장해야하는데 이건 설정 파일을 위한 설정 파일을 만드는 꼴이라서 지저분하기 때문에 하지 않으려고 해요
