### ISSUE TITLE
Malware detected by DrWeb from VirusTotal

### ISSUE THREAD

**Issue by SaberAkiyama** [KurtBestor/Hitomi-Downloader#4756]
I've checked for a virus detection from VT and it's detected. Screenshot below. By the way, Hitomi version is v3.7k

![Screenshot (9)](https://user-images.githubusercontent.com/48464326/167792427-bee8cbb1-42a6-45f8-b9ea-55f587f4d424.png)

**Comment by KurtBestor** [comment]
Only 1 AV detects it as malware while 98.4% AVs are not. Please report the false positive to DrWeb.

Here is the link: https://vms.drweb.com/sendvirus
