### ISSUE TITLE
Serial number + original file name as file name (e-hentai)

### ISSUE THREAD

**Issue by tglsf** [KurtBestor/Hitomi-Downloader#4762]
Sometimes raw filenames are useful, but they are not conducive to sorting. I had to use Excel for renaming and sorting. Is it possible to add a feature to use Serial number + original file name as filename?

(Sorry, I don't speak English or Korean, so I'm sorry if the question is repeated.)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
