### ISSUE TITLE
Chrome Error

### ISSUE THREAD

**Issue by Mortalit** [KurtBestor/Hitomi-Downloader#4768]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{
  "name": "Hitomi Downloader",
  "description": "Hitomi Downloader extension",
  "version": "0.3",
  "homepage_url": "https://github.com/KurtBestor/Hitomi-Downloader-issues",
  "permissions": [
    "tabs","<all_urls>","declarativeContent","cookies"
  ],
  "content_scripts": [{
    "all_frames": true,
    "matches": ["*://*/*"],
    "js": ["content.js"],
    "run_at": "document_start"
    }
  ],
  "background": {
    "scripts": ["background.js"],
    "persistent": true
  },
  "web_accessible_resources": [
    "extractors/*"
  ],
  "page_action": {
    "default_popup": "popup.html",
    "default_icon": {
      "64": "images/main_64.png"
    }
  },
  "icons": {
    "64": "images/main_64.png"
  },
  "manifest_version":2
}

**Comment by KurtBestor** [comment]
Fixed: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Chrome-Extension
