### ISSUE TITLE
리눅스에서 wine 실행시 버그가 발생합니다.

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader#4781]
![화면 캡처 2022-05-19 073955](https://user-images.githubusercontent.com/24527825/169168128-49948bcc-48be-449d-8c82-36cc4ab85209.png)
![화면 캡처 2022-05-19 075106](https://user-images.githubusercontent.com/24527825/169168133-81823ab3-b11a-460b-86d8-e01380b1dd04.png)
맨 위에 사진은 현 상황에서 해결이 안되는걸로 알고있습니다.
그 다음 사진은 권한 문제인데 암만 손대봐도 해결책이 없더군요 c++ 2015 재설치를 해봐도 똑같았습니다.
제일 쉬운 방법은 가상으로 윈도우 돌리는 거지만 자원 소모가 생각보다 심하기에
각각 다른 wine 로더로 실행한 겁니다 
해당 wine은 https://github.com/bottlesdevs/Bottles 로 실행했습니다.
실행 환경은 ubuntu 22.04 64bit 입니다
wsl로 윈도우에서 와인깔고 해봐도 와인 버전에 따라 첫번째 두번째 사진 오류가 뜨네요
2.8a 버전까지는 실행이 되네요 3.0 버전부터는 다른 오류가
![화면 캡처 2022-05-20 050522](https://user-images.githubusercontent.com/24527825/169395442-c19d2820-1504-494b-982f-75c9b768bc09.png)
뜨다가 최신버전부터는 2번째 사진 오류가 뜨네요

**Comment by YTOAA** [comment]
음...이걸 정확하게 어떤 버그라고 해야할까요>?

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
오호...새로운 오류가 뜹니다.
![화면 캡처 2022-05-21 185654](https://user-images.githubusercontent.com/24527825/169646308-0256194a-1857-4528-bf95-a41c375618f7.png)
일단 wine 에 보고하긴 했습니다
https://bugs.winehq.org/show_bug.cgi?id=53022
다른 게시물에서 말씀하신 것처럼 와인에서 실행이 안되면 와인 버그가 맞으니까요

**Comment by KurtBestor** [comment]
다음과 같이 실행하면 어떻게 되나요?
```
hitomi_downloader_GUI.exe --no-browser
```

**Comment by YTOAA** [comment]
오오...일단 실행은 정상적으로 됩니다. 기능상에 문제가 있는지는 좀더 조작해 봐야 알거 같습니다.

**Comment by KurtBestor** [comment]
Wine 에서 내장 웹브라우저를 로드할 때 필요한 DLL 을 읽지 못하고 에러메시지 띄우고있어요
`--no-browser` 는 내장 웹브라우저 기능을 끄는 옵션이에요

<kbd>Ctrl</kbd> + <kbd>L</kbd> 눌러서 나온 내용 보여주시면 분석해볼게요

**Comment by YTOAA** [comment]
C9Sq5Sv638Vz06l9Pv2Ry4GP+zYnN1Y7WjkZdg1McumfSahUcoaB+ePNhEKfhsTzYh396F0HeZqOTB=LY4tGip7B8bmjwDpJXNwxPSL3VnIVX4dhEeUrfZTuNQMj+YyW7lxPWjobN=sxnyXUupQUFQYM5lssjvM5LOFM5k=K8yJ8eFmJ6lbqiUGIl31lW8mi90i7ssXC0qIkk8OHQYopcFi2ewL+TK0VetAZi5ecjBOAKpUr0Wz7Tjsge01Zd1loVqSvhQkjkacmMTGserGsaUka=MmviC4DQJah6d173chvJbK3Ua2TxOjprs69P0fh

pyi: 4.10
PrefixPath: C:/users/timi/Temp/_MEI2482/PyQt/Qt
LibraryExecutablesPath: C:/users/timi/Temp/_MEI2482/PyQt/Qt/bin
BinariesPath: C:/users/timi/Temp/_MEI2482/PyQt/Qt/bin

Failed to init goodbye_dpi
Traceback (most recent call last):
  File "psutil\_common", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI", line 221, in <module>
  File "goodbye_dpi", line 45, in init
  File "psutil\__init__", line 617, in name
  File "psutil\_pswindows", line 750, in name
  File "psutil\_pswindows", line 681, in wrapper
  File "psutil\_pswindows", line 671, in convert_oserror
  File "psutil\_pswindows", line 679, in wrapper
  File "psutil\_common", line 450, in wrapper
  File "psutil\_pswindows", line 766, in exe
OSError: [WinError 87] 잘못된 매개변수: '(originated from NtQuerySystemInformation)'

webp: True
webp_anim: True

Font: MS Shell Dlg 2 -> Hitomi Font
System: Windows
Temp: C:\users\timi\Temp
Qt 5.14.1 / PyQt 5.14.1 / SIP 6.1.0.dev2104271705
{'debug': False, 'disable-gpu': True, 'no-browser': True, 'tray': False, 'no-admin': False, 'cache-disk': False, 'manual-gc': True, 'safemode': False, 'experimental': False, 'auto-scale': False, 'scale': 1, 'round-menu': True}

C:\users\timi\Temp
Z:\home\timi\ext\a\me\TEMPDOWNLOAD\PROGRAM\EXE\ht
[strip path] %TEMP%

winId: 196732
handle: <PyQt.QtGui.QWindow object at 0x0000000010E09798>
Supported Image Formats: [b'bmp', b'pbm', b'pgm', b'png', b'ppm', b'xbm', b'xpm']
v3.7k (latest: v3.7k)
Encodings: ['cp949', 'utf-8', 'ascii', 'utf-8', 'utf-8']
download yt_dlp
yt-dlp-2022.5.18.tar.gz#sha256=3a7b59d2fb4b39ce8ba8e0b9c5a37fe20e5624f46a2346b4ae66ab1320e35134
Saved: not exists
[append_datas] size: 0, elapsed time: 0.00835728645324707
db: True
GoodbyeDPI activated

Styles:
    windowsvista
    Windows
    Fusion

start GoodbyeDPI
import youtube-dl
youtube-dl version: 2022.05.18
close GoodbyeDPI
GoodbyeDPI activated
start GoodbyeDPI
close GoodbyeDPI

로그내용 입니다.
추가로 테스트 버전이 아닌 기존 버전에서는 안되던 이유도 혹시 동일한 이유인가요?

**Comment by KurtBestor** [comment]
네, 아마 Wine 에서 고칠 때 까지는 불가능할 거예요
정식 버전에서 안 되는 이유는 [이것](https://bugs.winehq.org/show_bug.cgi?id=49334) 때문이에요

**Comment by YTOAA** [comment]
그러면 와인측에 말할때 정식 빌드 기준으로 말해야 할까요 아니면 테스트 빌드 기준으로 말해야 할까요?

**Comment by KurtBestor** [comment]
테스트 버전으로 부탁드려요

**Comment by YTOAA** [comment]
정상작동 합니다.  빨리 와인에서  버그 처리해줬으면 하네요

**Comment by YTOAA** [comment]
dpi 우회를 제외한 나머지 기능이 대부분 정상작동 하는듯 합니다. 픽시브 같은 gif 변환도 정상작동 합니다.
와인측에서는 해당 버그가 고쳐진 7.10버전이 약 2주후에 나온다고 해서 이후 문제는 2주후에 다뤄야 할듯 합니다.

**Comment by YTOAA** [comment]
6월 2일자 테스트 버전 실행시 
Traceback (most recent call last):
  File "psutil\_common.py", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 204, in <module>
  File "goodbye_dpi.py", line 45, in init
  File "psutil\__init__.py", line 617, in name
  File "psutil\_pswindows.py", line 750, in name
  File "psutil\_pswindows.py", line 681, in wrapper
  File "psutil\_pswindows.py", line 671, in convert_oserror
  File "psutil\_pswindows.py", line 679, in wrapper
  File "psutil\_common.py", line 450, in wrapper
  File "psutil\_pswindows.py", line 766, in exe
OSError: [WinError 87] 잘못된 매개변수: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 206, in <module>
NameError: name 'print_error' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hitomi_downloader_GUI.py", line 211, in <module>
NameError: name 'print_error' is not defined
![화면 캡처 2022-06-03 012451](https://user-images.githubusercontent.com/24527825/171678190-31ac5d67-4521-47c6-8f42-f96f3e3a5a47.png)
오류가 뜨네요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by YTOAA** [comment]
정상실행 됩니다. 그리고 내일중으로 아마 wine이 업데이트 되면 못해도 월요일쯤은 테스트 가능하지 않을까 합니다.

**Comment by YTOAA** [comment]
후...7.10에서 실행은 정상적으로 되는데 내장 브라우저 기능이 정상적으로 작동을 안하네요
와인 터미널에서 
0b30:err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x248079
[1992:40:0604/220516.549:ERROR:ssl_client_socket_impl.cc(941)] handshake failed;
 returned -1, SSL error code 1, net_error -100
오류가 나오네요
다시 와인측에 문의를 넣은....
산넘어 산이네요

**Comment by KurtBestor** [comment]
다음 사이트들이에요:
```
bdsmlr
facebook
hentaicosplay
instagram
jmana
kakaopage
kakao webtoon
kissjav
lhscan (welovemanga)
manatoki
myreadingmanga
naverpost
nhentai
pixiv comic
pornhub
tiktok
weibo
```

**Comment by YTOAA** [comment]
감사합니다.

**Comment by aeg225** [comment]
> 감사합니다.
> 그 와인 정식버전 다시 빌드하고 세팅하니까 브라우저 기능 정상작동 합니다.
> 내장 브라우저로 가면 폰트가 깨지는 문제는 있지만 이건 설정 만져주면 되는거 같다고 어디서 들어서
> 아무튼 됩니다.

안녕하세요. 저는 와인7.15버전 사용중인데 브라우저 기능에 오류가 발생해서 몇몇 사이트들을 다운로드하지 못하네요..
 혹시 와인버전과 설정하신 세팅들을 알 수 있을까요?

**Comment by YTOAA** [comment]
> aeg225

다운로더 프리뷰 버전으로 시도해 보셨나요?

**Comment by aeg225** [comment]
> > aeg225
> 
> 다운로더 프리뷰 버전으로 시도해 보셨나요?

넵 이런 크래시가 발생하네요

> `Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x0000000393a1d3).
> Register dump:
>  rip:000000000393a1d3 rsp:000000000021ea90 rbp:0000000000000000 eflags:00000246 (   - --  I  Z- -P- )
>  rax:0000000000000000 rbx:000003cdcb22a080 rcx:0000000000000000 rdx:0000000000000000
>  rsi:000003cdcb22a2a8 rdi:00000112cd0c1970  r8:0000000000000001  r9:0000000000000000 r10:0000000000000009
>  r11:0000027076f81b10 r12:00000000003722b0 r13:00000000085f3b00 r14:000003cdcb22a1d8 r15:0000000000000000
> Stack dump:
> 0x0000000021ea90:  0000013c02021b10 000003cdcb22a2a8
> 0x0000000021eaa0:  00000112cd0c1970 0000000000000000
> 0x0000000021eab0:  00000000063dbe10 000000000021eb08
> 0x0000000021eac0:  0000000000000000 0000000000000270
> 0x0000000021ead0:  000000000021eb20 000000000021edb0
> 0x0000000021eae0:  0000000002b6cc9c 0000000000000000
> 0x0000000021eaf0:  0000000000000000 000000000021edb0
> 0x0000000021eb00:  0000000000000001 0000000000000001
> 0x0000000021eb10:  0000000000000001 000000000393c7aa
> 0x0000000021eb20:  00000112cd0c1970 0000000008788160
> 0x0000000021eb30:  0000000000000000 0000000008788160
> 0x0000000021eb40:  0000000000000000 000000000021edb0
> Backtrace:
> =>0 0x0000000393a1d3 in qt5webenginecore (+0x2cba1d3) (0000000000000000)
> 0x0000000393a1d3 qt5webenginecore+0x2cba1d3: movq	(%rax),%r8
> Modules:
> Module	Address					Debug info	Name (69 modules)
> PE	0000000000c80000-000000000694c000	Export          qt5webenginecore
> PE	0000000006950000-00000000071df000	Deferred        qt5gui
> PE	00000000071e0000-0000000007367000	Deferred        qt5network
> PE	0000000007370000-00000000073c4000	Deferred        qt5positioning
> PE	00000000073d0000-00000000077d1000	Deferred        qt5qml
> PE	00000000077e0000-0000000007c85000	Deferred        qt5quick
> PE	0000000007c90000-0000000007d13000	Deferred        qt5qmlmodels
> PE	0000000007d20000-0000000007d44000	Deferred        qt5webchannel
> PE	0000000010000000-0000000010002000	Deferred        usp10
> PE	000000006afc0000-000000006afc4000	Deferred        opengl32
> PE	000000007b000000-000000007b28e000	Deferred        kernelbase
> PE	000000007b600000-000000007b65b000	Deferred        kernel32
> PE	0000000140000000-0000000140082000	Deferred        qtwebengineprocess
> PE	0000000170000000-000000017009f000	Deferred        ntdll
> PE	0000000180000000-0000000180663000	Deferred        qt5core
> PE	00000001c4ee0000-00000001c4f10000	Deferred        winspool
> PE	00000001c69e0000-00000001c72f7000	Deferred        shell32
> PE	00000001c8b40000-00000001c8b60000	Deferred        msacm32
> PE	00000001c8db0000-00000001c8e46000	Deferred        msvcrt
> PE	00000001cfdf0000-00000001cfe13000	Deferred        dxva2
> PE	00000001dd3f0000-00000001dd4bb000	Deferred        crypt32
> PE	00000001ec2b0000-00000001ec2d7000	Deferred        ws2_32
> PE	00000001f51e0000-00000001f51f0000	Deferred        hid
> PE	0000000201cf0000-0000000201d10000	Deferred        secur32
> PE	0000000215e60000-0000000215f23000	Deferred        msvcr120
> PE	000000021ff70000-00000002201cb000	Deferred        wined3d
> PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4
> PE	000000023d820000-000000023d9c9000	Deferred        user32
> PE	0000000240030000-000000024005d000	Deferred        iphlpapi
> PE	000000024f470000-000000024f48f000	Deferred        mpr
> PE	000000025d740000-000000025d74e000	Deferred        dwmapi
> PE	000000026b4c0000-000000026b53b000	Deferred        gdi32
> PE	000000026ed50000-000000026ed5c000	Deferred        vcruntime140
> PE	00000002739c0000-0000000273af1000	Deferred        oleaut32
> PE	0000000274a50000-0000000274a5e000	Deferred        kerberos
> PE	000000028dfa0000-000000028dfac000	Deferred        nsi
> PE	00000002967b0000-00000002967e4000	Deferred        d3d9
> PE	00000002998f0000-000000029992e000	Deferred        dxgi
> PE	000000029cfc0000-000000029cfd5000	Deferred        dnsapi
> PE	00000002a4090000-00000002a409e000	Deferred        wtsapi32
> PE	00000002bb750000-00000002bb88e000	Deferred        comctl32
> PE	00000002cd450000-00000002cd4b8000	Deferred        d3d11
> PE	00000002d4d40000-00000002d4d56000	Deferred        bcrypt
> PE	00000002e3540000-00000002e3591000	Deferred        shlwapi
> PE	00000002e8f10000-00000002e902a000	Deferred        ole32
> PE	00000002f1fa0000-00000002f1fae000	Deferred        version
> PE	00000002f7230000-00000002f7265000	Deferred        uxtheme
> PE	000000030a950000-000000030a9c3000	Deferred        dwrite
> PE	00000003126f0000-0000000312709000	Deferred        shcore
> PE	000000031d960000-000000031d989000	Deferred        winemac
> PE	000000031f800000-000000031f8fb000	Deferred        comdlg32
> PE	0000000327020000-0000000327073000	Deferred        combase
> PE	000000032a700000-000000032a729000	Deferred        sechost
> PE	0000000330260000-000000033029f000	Deferred        advapi32
> PE	00000003422e0000-000000034237b000	Deferred        urlmon
> PE	0000000346ba0000-0000000346bc1000	Deferred        jsproxy
> PE	0000000358120000-0000000358165000	Deferred        winhttp
> PE	0000000360e10000-0000000360eef000	Deferred        msvcp140
> PE	00000003673d0000-00000003673f5000	Deferred        netapi32
> PE	0000000375610000-0000000375649000	Deferred        win32u
> PE	00000003871c0000-00000003871e6000	Deferred        concrt140
> PE	0000000388e20000-0000000388e2e000	Deferred        userenv
> PE	00000003a0440000-00000003a04c1000	Deferred        wininet
> PE	00000003a19e0000-00000003a19f0000	Deferred        ncrypt
> PE	00000003aa4c0000-00000003aa4cc000	Deferred        dhcpcsvc
> PE	00000003af670000-00000003af72f000	Deferred        ucrtbase
> PE	00000003afd00000-00000003afd19000	Deferred        imm32
> PE	00000003b8f00000-00000003b8fc1000	Deferred        winmm
> PE	00000003be590000-00000003be604000	Deferred        dbghelp
> Threads:
> process  tid      prio    name (all IDs are in hex)
> 00000020 hitomi_downloader_GUI.exe
> 	00000024    0     
> 00000038 services.exe
> 	0000003c    0     
> 	00000040    0     
> 	0000004c    0     
> 	00000090    0     
> 	000000bc    0     
> 	000000d8    0     
> 	000000f8    0     
> 00000044 winedevice.exe
> 	00000048    0     
> 	00000054    0     
> 	00000058    0     
> 	0000005c    0     
> 	00000060    0     
> 	00000064    0     
> 	000000e4    0     
> 00000088 winedevice.exe
> 	0000008c    0     
> 	00000094    0     
> 	00000098    0     
> 	0000009c    0     
> 	000000a0    0     
> 	000000b4    0     
> 	000000b8    0     
> 000000a4 explorer.exe
> 	000000a8    0     
> 	000000d4    0     
> 	000000e8    0     
> 000000ac plugplay.exe
> 	000000b0    0     
> 	000000c0    0     
> 	000000c4    0     
> 	000000c8    0     
> 	000001cc    0     
> 	000001d0    0     
> 000000cc svchost.exe
> 	000000d0    0     
> 	000000dc    0     
> 	000000e0    0     
> 000000f0 rpcss.exe
> 	000000f4    0     
> 	000000fc    0     
> 	00000100    0     
> 	00000104    0     
> 	00000108    0     
> 	0000010c    0     
> 00000114 hitomi_downloader_GUI.exe
> 	00000118    0     CrBrowserMain
> 	0000011c    0     
> 	00000120    0     
> 	00000124    0     
> 	00000128    0     
> 	0000012c    0     
> 	00000130    0     
> 	00000134    0     
> 	00000138    0     
> 	0000013c    0     
> 	00000140    0     
> 	00000144    0     
> 	00000148    0     
> 	0000014c    0     
> 	00000150    0     
> 	00000154    0     
> 	00000158    0     
> 	0000015c    0     
> 	00000160    0     
> 	00000164    0     
> 	00000168    0     
> 	0000016c    0     
> 	00000170    0     
> 	00000174    0     
> 	00000178    0     
> 	00000180    0     
> 	00000184    0     BrokerEvent
> 	00000188    0     ThreadPoolServiceThread
> 	0000018c    0     ThreadPoolForegroundWorker
> 	00000190   -2     ThreadPoolBackgroundWorker
> 	00000194    0     Chrome_IOThread
> 	00000198    0     
> 	0000019c    0     
> 	000001a0    0     ThreadPoolSingleThreadCOMSTASharedForeground0
> 	000001a4    0     ThreadPoolForegroundWorker
> 	000001b0    0     CompositorTileWorker1
> 	000001b4    0     VizCompositorThread
> 	000001b8    0     AudioThread
> 	000001bc    0     
> 	000001c0    0     
> 	000001c4    0     
> 	000001c8    0     VideoCaptureThread
> 	000001d4    0     CacheThread_BlockFile
> 	000001e0    0     
> 	000001e4    0     
> 	000001e8    0     
> 	000001ec    0     
> 	000001f0    0     
> 	000001f4    0     
> 	000001f8    0     
> 	000001fc    0     
> 	00000200    0     
> 	00000204    0     
> 	00000208    0     
> 	0000020c    0     
> 	00000210    0     
> 	00000214    0     
> 	00000218    0     
> 	0000021c    0     
> 	00000220    0     
> 	00000224    0     
> 	00000228    0     
> 	0000022c    0     
> 	00000230    0     
> 	00000234    0     
> 	00000238    0     
> 	0000023c    0     
> 	00000240    0     
> 	00000244    0     
> 	00000248    0     
> 	0000024c    0     
> 	00000250    0     
> 	00000254    0     
> 	00000258    0     
> 	0000025c    0     
> 	00000260    0     
> 	0000064c    0     
> 	00000650    0     
> 	00000654    0     
> 	00000764    0     
> 	00000768    0     
> 	0000076c    0     
> 	00000770    0     
> 	00000774    0     
> 	00000784    0     ThreadPoolSingleThreadForegroundBlocking1
> 	00000788   -2     ThreadPoolSingleThreadSharedBackgroundBlocking2
> 	0000079c    0     
> 0000078c (D) C:\users\hikarigusa\Temp\_MEI323\PyQt5\Qt\bin\QtWebEngineProcess.exe
> 	00000790    0 <== CrRendererMain
> 	000007a4    0     ThreadPoolServiceThread
> 	000007a8    0     ThreadPoolForegroundWorker
> 	000007ac   -2     ThreadPoolBackgroundWorker
> 	000007b0    0     Chrome_ChildIOThread
> 	000007b4    0     
> 	000007b8    0     
> 	000007bc    0     GpuMemoryThread
> 	000007c0    0     Compositor
> 	000007c4    0     CompositorTileWorker1
> 	000007c8    0     CompositorTileWorker2
> 	000007cc    0     CompositorTileWorker3
> 	000007d0    0     CompositorTileWorker4
> 	000007d4   -2     CompositorTileWorkerBackground
> 	000007ec    0     
> 000007e0 conhost.exe
> 	000007e4    0     
> System information:
>     Wine build: wine-7.15
>     Platform: x86_64
>     Version: Windows 7
>     Host system: Darwin
>     Host version: 22.1.0
> `

**Comment by YTOAA** [comment]
> > > aeg225
> > 
> > 
> > 다운로더 프리뷰 버전으로 시도해 보셨나요?
> 
> 넵 이런 크래시가 발생하네요
> 
> > `Unhandled exception: page fault on read access to 0x0000000000000000 in 64-bit code (0x0000000393a1d3). Register dump: rip:000000000393a1d3 rsp:000000000021ea90 rbp:0000000000000000 eflags:00000246 (   - --  I  Z- -P- ) rax:0000000000000000 rbx:000003cdcb22a080 rcx:0000000000000000 rdx:0000000000000000 rsi:000003cdcb22a2a8 rdi:00000112cd0c1970  r8:0000000000000001  r9:0000000000000000 r10:0000000000000009 r11:0000027076f81b10 r12:00000000003722b0 r13:00000000085f3b00 r14:000003cdcb22a1d8 r15:0000000000000000 Stack dump: 0x0000000021ea90:  0000013c02021b10 000003cdcb22a2a8 0x0000000021eaa0:  00000112cd0c1970 0000000000000000 0x0000000021eab0:  00000000063dbe10 000000000021eb08 0x0000000021eac0:  0000000000000000 0000000000000270 0x0000000021ead0:  000000000021eb20 000000000021edb0 0x0000000021eae0:  0000000002b6cc9c 0000000000000000 0x0000000021eaf0:  0000000000000000 000000000021edb0 0x0000000021eb00:  0000000000000001 0000000000000001 0x0000000021eb10:  0000000000000001 000000000393c7aa 0x0000000021eb20:  00000112cd0c1970 0000000008788160 0x0000000021eb30:  0000000000000000 0000000008788160 0x0000000021eb40:  0000000000000000 000000000021edb0 Backtrace: =>0 0x0000000393a1d3 in qt5webenginecore (+0x2cba1d3) (0000000000000000) 0x0000000393a1d3 qt5webenginecore+0x2cba1d3: movq	(%rax),%r8 Modules: Module	Address					Debug info	Name (69 modules) PE	0000000000c80000-000000000694c000	Export          qt5webenginecore PE	0000000006950000-00000000071df000	Deferred        qt5gui PE	00000000071e0000-0000000007367000	Deferred        qt5network PE	0000000007370000-00000000073c4000	Deferred        qt5positioning PE	00000000073d0000-00000000077d1000	Deferred        qt5qml PE	00000000077e0000-0000000007c85000	Deferred        qt5quick PE	0000000007c90000-0000000007d13000	Deferred        qt5qmlmodels PE	0000000007d20000-0000000007d44000	Deferred        qt5webchannel PE	0000000010000000-0000000010002000	Deferred        usp10 PE	000000006afc0000-000000006afc4000	Deferred        opengl32 PE	000000007b000000-000000007b28e000	Deferred        kernelbase PE	000000007b600000-000000007b65b000	Deferred        kernel32 PE	0000000140000000-0000000140082000	Deferred        qtwebengineprocess PE	0000000170000000-000000017009f000	Deferred        ntdll PE	0000000180000000-0000000180663000	Deferred        qt5core PE	00000001c4ee0000-00000001c4f10000	Deferred        winspool PE	00000001c69e0000-00000001c72f7000	Deferred        shell32 PE	00000001c8b40000-00000001c8b60000	Deferred        msacm32 PE	00000001c8db0000-00000001c8e46000	Deferred        msvcrt PE	00000001cfdf0000-00000001cfe13000	Deferred        dxva2 PE	00000001dd3f0000-00000001dd4bb000	Deferred        crypt32 PE	00000001ec2b0000-00000001ec2d7000	Deferred        ws2_32 PE	00000001f51e0000-00000001f51f0000	Deferred        hid PE	0000000201cf0000-0000000201d10000	Deferred        secur32 PE	0000000215e60000-0000000215f23000	Deferred        msvcr120 PE	000000021ff70000-00000002201cb000	Deferred        wined3d PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4 PE	000000023d820000-000000023d9c9000	Deferred        user32 PE	0000000240030000-000000024005d000	Deferred        iphlpapi PE	000000024f470000-000000024f48f000	Deferred        mpr PE	000000025d740000-000000025d74e000	Deferred        dwmapi PE	000000026b4c0000-000000026b53b000	Deferred        gdi32 PE	000000026ed50000-000000026ed5c000	Deferred        vcruntime140 PE	00000002739c0000-0000000273af1000	Deferred        oleaut32 PE	0000000274a50000-0000000274a5e000	Deferred        kerberos PE	000000028dfa0000-000000028dfac000	Deferred        nsi PE	00000002967b0000-00000002967e4000	Deferred        d3d9 PE	00000002998f0000-000000029992e000	Deferred        dxgi PE	000000029cfc0000-000000029cfd5000	Deferred        dnsapi PE	00000002a4090000-00000002a409e000	Deferred        wtsapi32 PE	00000002bb750000-00000002bb88e000	Deferred        comctl32 PE	00000002cd450000-00000002cd4b8000	Deferred        d3d11 PE	00000002d4d40000-00000002d4d56000	Deferred        bcrypt PE	00000002e3540000-00000002e3591000	Deferred        shlwapi PE	00000002e8f10000-00000002e902a000	Deferred        ole32 PE	00000002f1fa0000-00000002f1fae000	Deferred        version PE	00000002f7230000-00000002f7265000	Deferred        uxtheme PE	000000030a950000-000000030a9c3000	Deferred        dwrite PE	00000003126f0000-0000000312709000	Deferred        shcore PE	000000031d960000-000000031d989000	Deferred        winemac PE	000000031f800000-000000031f8fb000	Deferred        comdlg32 PE	0000000327020000-0000000327073000	Deferred        combase PE	000000032a700000-000000032a729000	Deferred        sechost PE	0000000330260000-000000033029f000	Deferred        advapi32 PE	00000003422e0000-000000034237b000	Deferred        urlmon PE	0000000346ba0000-0000000346bc1000	Deferred        jsproxy PE	0000000358120000-0000000358165000	Deferred        winhttp PE	0000000360e10000-0000000360eef000	Deferred        msvcp140 PE	00000003673d0000-00000003673f5000	Deferred        netapi32 PE	0000000375610000-0000000375649000	Deferred        win32u PE	00000003871c0000-00000003871e6000	Deferred        concrt140 PE	0000000388e20000-0000000388e2e000	Deferred        userenv PE	00000003a0440000-00000003a04c1000	Deferred        wininet PE	00000003a19e0000-00000003a19f0000	Deferred        ncrypt PE	00000003aa4c0000-00000003aa4cc000	Deferred        dhcpcsvc PE	00000003af670000-00000003af72f000	Deferred        ucrtbase PE	00000003afd00000-00000003afd19000	Deferred        imm32 PE	00000003b8f00000-00000003b8fc1000	Deferred        winmm PE	00000003be590000-00000003be604000	Deferred        dbghelp Threads: process  tid      prio    name (all IDs are in hex) 00000020 hitomi_downloader_GUI.exe 00000024    0      00000038 services.exe 0000003c    0      00000040    0      0000004c    0      00000090    0      000000bc    0      000000d8    0      000000f8    0      00000044 winedevice.exe 00000048    0      00000054    0      00000058    0      0000005c    0      00000060    0      00000064    0      000000e4    0      00000088 winedevice.exe 0000008c    0      00000094    0      00000098    0      0000009c    0      000000a0    0      000000b4    0      000000b8    0      000000a4 explorer.exe 000000a8    0      000000d4    0      000000e8    0      000000ac plugplay.exe 000000b0    0      000000c0    0      000000c4    0      000000c8    0      000001cc    0      000001d0    0      000000cc svchost.exe 000000d0    0      000000dc    0      000000e0    0      000000f0 rpcss.exe 000000f4    0      000000fc    0      00000100    0      00000104    0      00000108    0      0000010c    0      00000114 hitomi_downloader_GUI.exe 00000118    0     CrBrowserMain 0000011c    0      00000120    0      00000124    0      00000128    0      0000012c    0      00000130    0      00000134    0      00000138    0      0000013c    0      00000140    0      00000144    0      00000148    0      0000014c    0      00000150    0      00000154    0      00000158    0      0000015c    0      00000160    0      00000164    0      00000168    0      0000016c    0      00000170    0      00000174    0      00000178    0      00000180    0      00000184    0     BrokerEvent 00000188    0     ThreadPoolServiceThread 0000018c    0     ThreadPoolForegroundWorker 00000190   -2     ThreadPoolBackgroundWorker 00000194    0     Chrome_IOThread 00000198    0      0000019c    0      000001a0    0     ThreadPoolSingleThreadCOMSTASharedForeground0 000001a4    0     ThreadPoolForegroundWorker 000001b0    0     CompositorTileWorker1 000001b4    0     VizCompositorThread 000001b8    0     AudioThread 000001bc    0      000001c0    0      000001c4    0      000001c8    0     VideoCaptureThread 000001d4    0     CacheThread_BlockFile 000001e0    0      000001e4    0      000001e8    0      000001ec    0      000001f0    0      000001f4    0      000001f8    0      000001fc    0      00000200    0      00000204    0      00000208    0      0000020c    0      00000210    0      00000214    0      00000218    0      0000021c    0      00000220    0      00000224    0      00000228    0      0000022c    0      00000230    0      00000234    0      00000238    0      0000023c    0      00000240    0      00000244    0      00000248    0      0000024c    0      00000250    0      00000254    0      00000258    0      0000025c    0      00000260    0      0000064c    0      00000650    0      00000654    0      00000764    0      00000768    0      0000076c    0      00000770    0      00000774    0      00000784    0     ThreadPoolSingleThreadForegroundBlocking1 00000788   -2     ThreadPoolSingleThreadSharedBackgroundBlocking2 0000079c    0      0000078c (D) C:\users\hikarigusa\Temp\_MEI323\PyQt5\Qt\bin\QtWebEngineProcess.exe 00000790    0 <== CrRendererMain 000007a4    0     ThreadPoolServiceThread 000007a8    0     ThreadPoolForegroundWorker 000007ac   -2     ThreadPoolBackgroundWorker 000007b0    0     Chrome_ChildIOThread 000007b4    0      000007b8    0      000007bc    0     GpuMemoryThread 000007c0    0     Compositor 000007c4    0     CompositorTileWorker1 000007c8    0     CompositorTileWorker2 000007cc    0     CompositorTileWorker3 000007d0    0     CompositorTileWorker4 000007d4   -2     CompositorTileWorkerBackground 000007ec    0      000007e0 conhost.exe 000007e4    0      System information: Wine build: wine-7.15 Platform: x86_64 Version: Windows 7 Host system: Darwin Host version: 22.1.0 `

음 Lutris 설치해보셔서 한번 시도해 보시겠어요?
실행환경을 윈도우10 64bit 환경으로 해보시고
wine을 실행하고 있는 하드웨어가 어떤건가요?

**Comment by ipiiia** [comment]
> 음 Lutris 설치해보셔서 한번 시도해 보시겠어요? 실행환경을 윈도우10 64bit 환경으로 해보시고 wine을 실행하고 있는 하드웨어가 어떤건가요?

하드웨어는 M1맥북입니다, 윈도우10으로 해봤지만 해결되지 않는군요ㅠ Lutris는 리눅스용 와인일까요 맥용으로 찾아보니 나오지가 않네요:D

**Comment by YTOAA** [comment]
> 

아 m1 같은 arm 계열은 테스트를 안해봐서 모르겠네요.
M1이면 패러럴즈가 있지 않나요?

**Comment by YTOAA** [comment]
> > 아 m1 같은 arm 계열은 테스트를 안해봐서 모르겠네요.
> > M1이면 패러럴즈가 있지 않나요?
> 
> 와인이라도 아키텍쳐따라 오류가 다른걸까요ㅠ 패러렐즈가 있지만 윈도우처럼 바로 실행되는 와인에 비해서 번거롭고 느린거같아서 와인만 사용하고 있네요😅

해당 오류코드 복사후 wine  포럼에 한번 문의하는게 좋을듯 합니다.
