### ISSUE TITLE
파일을 4천개 이상 다운로드 받는건 막혀있나요? 

### ISSUE THREAD

**Issue by 132132132135** [KurtBestor/Hitomi-Downloader#4794]
luscious에 5007개의 사진, 1개의 gif 파일을 다운로드 받으려고 프로그램을 이용했는데 앞의 4천개는 성공했으나 뒤의 1008개가 다운로드 되지 않고 있습니다. 정확히는 아예 인식이 되지 않는다에 가까운거 같습니다. 4천개까진 확실히 인식되나 그 이상은 아래와 같은 방법을 시도해 보았으나 실패하였습니다.

1. 페이지 지정 다운로드를 통해 ~5008, ~ 5008, ~ 6000등으로 시도해 보았으나 4천개까지만 인식이 됩니다.
2.  같은 원리로 -2000 ~ , -2000~, -1008~등 반대 방향으로도 시도해 보았으나 그냥 아예 처음부터 4천개만 인식이 되는거 같습니다.

3. 옵션 - 설정 - 고급 - 페이지 지정 다운로드 기본값을 ~6000, ~ 6000등으로 시도해보았으나 역시 4천개까지만 인식이 됩니다.

혹시 다른 방법 or 해결 방법이 있을까요?

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by 132132132135** [comment]
> 해당 작업 정보 보여주세요

이게 4천개나 되다보니 그대로 복붙하니 너무 렉이 심해져서 파일 리스트 제외한 것만 올립니다.

アへ顔

version: 3.7k (22-05-06 09:53:24 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 2d1572c75b574777bca6533e2db7e324
input: https://www.luscious.net/albums/aheyan_297975/
type: luscious
single: False
url: https://www.luscious.net/albums/aheyan_297975/
dir: E:\개인정보 생략\11111_luscious\アへ顔
zip: 
artist: None
valid / done: True / True
range / range_p: ~6000 / None
time: 1653206844.1395118 (22-05-22 08:07:24 UTC)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.05.18
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]
[0001] E:\개인정보 생략\11111_luscious\アへ顔\18508286.jpg

0001~4000까진 같은 형식으로 쭉 그대로 이어져있습니다. 중간에 특이한 문구 없음. 

[4000] E:\개인정보 생략\11111_luscious\アへ顔\18512481.png


[URLs]

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by 132132132135** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

1차 시도 : 기본값이 2천개까지로 지정되어있는거 같아 취소했습니다.

2차 시도 ; 페이지 지정 다운로드로 ~6000으로 해놓고 다운로드 시도하니 파일 갯수 5007개까지 정상 인식 되었습니다.
다운로드 시도 결과 다운로드 되고 있고 성공했습니다.

정상적으로 됩니다. 감사합니다. 

p.s. 5008개 파일인줄 알았는데 gif가 사진 갯수에 포함되어있어서 5007개 정상 맞는거 같습니다.
