### ISSUE TITLE
v 3.7I : (Hitomi.la / ExHentai) Auto uncheck "Download original images" and show "No cookies"

### ISSUE THREAD

**Issue by tglsf** [KurtBestor/Hitomi-Downloader#4857]
1. Update to v3.7I
2. restart the software and open "Preferences -> Hitomi.la ExHentai" again, "Download original images" is automatically unchecked and "No cookies" is displayed.
3. My cookies (e-hentai / exhentai) were already imported, and I tried importing them again, but I still had the same problem after restarting the application.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
