### ISSUE TITLE
기본 보기에서 숨김 기능이나 지정 사이트 숨김 메뉴가 있었으면 좋겠어요.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#4878]
잠금, 고정과 같은 메뉴로요.

다운로드한 트위터 라거나 xvideo 라거나

다운로드하고 목록에서 지우는 편인데 숨김 기능이 있으면

바로 삭제 안 해도 될 것 같아서요.

**Comment by KurtBestor** [comment]
좌측 하단 `필터 (F3)` 눌러서 필터 켜고 다음과 같이 입력해주세요:
```php
NOT type:twitter
```

다음과 같이 여러 개도 가능해요:
```php
NOT type:twitter NOT type:xvideo
```

**Comment by DBdeepsleeper** [comment]
> 좌측 하단 `필터 (F3)` 눌러서 필터 켜고 다음과 같이 입력해주세요:
> 
> ```
> NOT type:twitter
> ```
> 
> 다음과 같이 여러 개도 가능해요:
> 
> ```
> NOT type:twitter NOT type:xvideo
> ```

필터가 첫 실행 시에도 이전 필터 보기로 켜지면 이렇게 하겠지만

컴퓨터 켜고 처음 실행하면 기본 보기 상태인지라...

건의했던 사항입니다.

답변 고맙습니다.

**Comment by DBdeepsleeper** [comment]
새 이슈로 가야 할지 고민하다 여기에 적어봅니다.

필터 가독성을 위해서 "일반인"이라는 단어를 먼저 검색 후에 추가로 아티스트들을 필터링해서 북마크 했는데요. (ex.1)

"일반인"이라는 단어에 다른 영상들이 함께 필터링 돼서 NOT으로 제외를 하려면 ex.2와 같이 NOT을 앞에 적어야 하더라고요. (ex.2)

ex.1 ) 일반인 OR artist:"Just Walk" OR artist:"Minos Travel" OR artist:"Walk Essentials" OR artist:"Seoul Travel Walker"

ex.2 ) NOT artist:"육체미 빅터" NOT artist:"채윤쓰 Chaeyun's" NOT artist:"라이징 보이스 | RISING VOICE" 일반인 OR artist:"Just Walk" OR artist:"Minos Travel" OR artist:"Walk Essentials" OR artist:"Seoul Travel Walker"

현재는 제외부터 하고 필터가 되는 거 같은데 검색을 먼저하고 제외하는 방법은 없을까요?

**Comment by KurtBestor** [comment]
Logical AND 가 Logical OR 보다 연산 우선순위가 높기 때문에 둘은 다른 필터예요:
```php
NOT A B OR C = (NOT A AND B) OR C
```
```php
B OR C NOT A = B OR (C AND NOT A)
```

`NOT A` 와 `B OR C` 를 동시에 만족하는 필터는 다음과 같아요:
```php
NOT A (B OR C) = NOT A AND (B OR C)
```

필터링 문법은 윈도 탐색기와 같아요: https://docs.microsoft.com/en-us/windows/win32/lwef/-search-2x-wds-aqsreference#boolean-operators

**Comment by DBdeepsleeper** [comment]
아. 안되는 건가 보네요.

답변 고맙습니다.
