### ISSUE TITLE
Can it be made not to request administrator privileges when not necessary

### ISSUE THREAD

**Issue by tglsf** [KurtBestor/Hitomi-Downloader#4934]
My computer starts up regularly for downloads and I have Hitomi Downloader set to run at startup. Every time the program starts, it is suspended by "User Account Control", can you add the option not to request administrator privileges when not necessary?
(I don't use goodbyeDPI)

**Comment by doppler56** [comment]
Yes it is bothersome but since you can trust Hitomi Doawnloader.  Try this approach.  I have used this many times before, with great success. https://www.digitalcitizen.life/use-task-scheduler-launch-programs-without-uac-prompts/

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

![image](https://user-images.githubusercontent.com/14768120/175849199-31f695de-722c-450d-8c68-8ad407e0ab7b.png)

**Comment by doppler56** [comment]
I try not to use bleeding edge software, unless there is a need.  Here there is a need.  And I will take it.

Bypassing UAC via the task scheduler is a proven cheat.  And safe to use when deemed required.  re: Sloppy programming.
Thanks, and I guess this issue can be close too.
