### ISSUE TITLE
틱톡 영상이 30개 밖에 다운이 안됩니다...

### ISSUE THREAD

**Issue by space789521** [KurtBestor/Hitomi-Downloader#4941]
https://github.com/KurtBestor/Hitomi-Downloader/issues/4454
이 링크 들어가서 봤는데 무슨소린지 전혀 모르겠더라고요

틱톡 계정의 모든 영상은 다운이 불가능 한 건가요..?

**Comment by tdi2020** [comment]
혹시 그 문제가 아닐 수도 있지만 저는 그런 경험이 있어서 달아둡니다.

틱톡 주소 다운로드 시도하면 작은 창이 하나 떠서 자동으로 계정에 있는 모든 게시물을 스크롤 해줍니다.
근데 그 창을 바로 꺼버리면 30개만 읽어지더라구요.
창을 놔두면 알아서 스크롤 한 뒤 전체 게시물을 다운받으니까 혹시 닫지 않았는지 그 부분도 체크해보시면 좋을것 같아요.

**Comment by space789521** [comment]
아 감사합니다!! 한번 시도해 볼게요

**Comment by space789521** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/107837343/175618119-3ef70f58-d293-48ba-bdd8-f24a2608d889.png">
이렇게 밖에 안나오네요...
틱톡 창을 안꺼도 그렇게 되더라고요... 몇번 시도해봤더니 틱톡 창 자체가 하얀색이 될 떄도 있고요...
어떻게 해결해야 할까요?

**Comment by qj8x67s33a44** [comment]
급하시면 일단 다운 받으시려는 유저 주소 들어가서 목록을 수동으로 복사해서 다운로드 하셔야 할 듯?

**Comment by space789521** [comment]
목록을 어떻게 복사하나요??

**Comment by space789521** [comment]
@qj8x67s33a44 목록을 어떻게 복사하나요??

**Comment by qj8x67s33a44** [comment]
> @qj8x67s33a44 목록을 어떻게 복사하나요??

말 그대로 하나 하나 들어가서 복사해서 수동으로 붙여넣어야겠죠

**Comment by tdi2020** [comment]
혹시나 해서 저도 해보니 30개밖에 안되네요..  전 최신 테스트버전으로 했는데 혹시 어떤 버전으로 해보셨나요?

**Comment by KurtBestor** [comment]
다음과 같이 실행하면 어떤가요?:
```
hitomi_downloader_GUI.exe --disable-gpu=False
```

**Comment by space789521** [comment]
@KurtBestor hitomi_downloader_GUI.exe --disable-gpu=False 이거 실행은 어떻게 하는 건가요?

**Comment by space789521** [comment]
@tdi2020 저도 최신 테스트 버전입니다 내용 추가된 것도 다 똑같게 나오고요

**Comment by space789521** [comment]
와 되네요
cmd에서 어찌저찌 실행해보니까 전체 다운로드가 되네요..

**Comment by tdi2020** [comment]
아! 저도 해보니 정상적으로 받아졌습니다.
그런데 제 기분탓이면 좋겠지만.. 이걸 한 번 설정하니까
이전에는 텀블러 받을때 다운속도 표시되면서 받았던거 같은데 아무 표시가 안되는 그런 느낌으로 답답하길래
다시 끌려고 했더니 방법을 모르겠어요. 다운로드 속도계에 0.0MB 상태로 계속 받아는 지는 그런 느낌이더라구요

혹시 --disable-gpu=False 부분에서 False를 True 라고 다시 입력하면 이전처럼 실행 되는건가요? 
(만약 그렇다면 틱톡 받을때 항상 이걸 껐다 켰다 cmd로 해야할지도 궁금합니다.)

그리고 저처럼 어떻게 하는지 모르는 분들이 계실테니 재가 검색해서 해본 방법을 여기 적어둘게요.

1. 윈도우 검색에서 cmd 치신 후 -> 다운로더 설치된 폴더의 드라이브로 이동 (c 드라이브면 c: 치시면 가짐)
2. 설치된 폴더로도 이동해야하는데 cd 폴더명 이렇게 입력하시면 폴더로 가짐
3. 그 상태에서 --disable-gpu=False 를 입력하시면 틱톡을 받을 수 있는 상태로 다운로더가 켜짐

**Comment by helpmepls08** [comment]
작은창이 왜 뜨나 했는데 두니까 잘되네요
