### ISSUE TITLE
세이프 모드 실행 이슈

### ISSUE THREAD

**Issue by mkccip** [KurtBestor/Hitomi-Downloader#4942]
C드라이브에 
hitomi_downloader_GUI.exe가 들어있는 폴더가 있습니다.
관리자 모드로 실행하여 
hitomi_downloader_GUI.exe --safemode
를 입력하니, 잠시 마우스가 돌아가다가 사라집니다. 실행 안됩니다.
혹시 몰라서 여러 번 거의 동시에 입력하니까, already running 
뜨면서 이미 실행중이라고 합니다..

**Comment by mkccip** [comment]
3.6 버전으로 실행하니까 세이프 모드 요구 없이 작동 잘 되네요.

**Comment by wotmd78519** [comment]
3.6으로 하면 되는데 3.7로 하면 실행이 안되죠......
