### ISSUE TITLE
마나토끼 또 차단하는 것 같은데 저만 걸리나요?

### ISSUE THREAD

**Issue by getsome23** [KurtBestor/Hitomi-Downloader#4970]
실험을 해보고 싶은데 해볼 수가 없네요. 캡챠 쿠키 그쪽에서 알고 밴 먹이는 거 같은데요

**Comment by KurtBestor** [comment]
해당 작업 정보 보여주세요

**Comment by getsome23** [comment]
> 해당 작업 정보 보여주세요

구글 크롬 통해 쿠키 추출하자마자 차단을 당했거든요. 다른 분들이 이야기가 없는 걸 보니 저만 걸린 것 같습니다. 프로그램에 문제가 있는 건 아닌 것 같고 쿠키 추출을 막나봐요.. 개발자님 고생하십니다 답변 감사드립니다
