### ISSUE TITLE
뉴토끼 메모리 점유 문제

### ISSUE THREAD

**Issue by YTOAA** [KurtBestor/Hitomi-Downloader#4976]
예를들어 https://newtoki144.com/webtoon/166985/%ED%97%AC%ED%8D%BC?stx=%ED%97%AC%ED%8D%BC
이걸 다운받으려고 합니다.
그런데 메모리를 3기가 이상씩 잡아먹네요
물론 mem reduct같은 툴을 쓰면 그때그때 메모리 정리를 한다고 치지만
원래 이런건가요?
테스트는 프리뷰 버전으로 했습니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/178088064-42c2b83d-c2a0-4ae0-912d-38c684a13512.png)

재현할 수가 없네요

**Comment by YTOAA** [comment]
7월9일자 프리뷰에서는 정상작동 됩니다.
