### ISSUE TITLE
업데이트 후 트위치 영상 다운로드가 안됩니다

### ISSUE THREAD

**Issue by 4e55** [KurtBestor/Hitomi-Downloader#5031]
항상 프로그램 잘 사용하고 있습니다.
오늘 업데이트한 이후로 트위치 영상 다운로드가 작동하지 않는데 혹시 확인해주실 수 있으신가요?
아래는 다운로드 실패한 작업정보입니다.

Invalid: [twitch] https://www.twitch.tv/videos/1535261692

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-7-6.1.7601-SP1 / ko_kr
order / group / uid: 0 / False / 7ebd5ac542b54dbd977a4c44cfe78931
input: https://www.twitch.tv/videos/1535261692
type: twitch
single: True
url: https://www.twitch.tv/videos/1535261692
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1658552549.647681 (22-07-23 05:02:29 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
[debug] [twitch:vod] 1535261692: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1535261692: Downloading video access token GraphQL
[debug] [twitch:vod] 1535261692: Downloading m3u8 information
[debug] [twitch:vod] 1535261692: Downloading storyboard metadata JSON
[warning] [twitch:vod] Unable to download JSON metadata: HTTP Error 403: Forbidden
[warning] No subtitle format found matching "vtt" for language rechat, using json
[debug] [twitch:vod] 1535261692: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1535261692: Downloading video access token GraphQL
[debug] [twitch:vod] 1535261692: Downloading m3u8 information
[debug] [twitch:vod] 1535261692: Downloading storyboard metadata JSON
[warning] [twitch:vod] Unable to download JSON metadata: HTTP Error 403: Forbidden
[warning] No subtitle format found matching "vtt" for language rechat, using json
[debug] [twitch:vod] 1535261692: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1535261692: Downloading video access token GraphQL
[debug] [twitch:vod] 1535261692: Downloading m3u8 information
[debug] [twitch:vod] 1535261692: Downloading storyboard metadata JSON
[warning] [twitch:vod] Unable to download JSON metadata: HTTP Error 403: Forbidden
[warning] No subtitle format found matching "vtt" for language rechat, using json
[debug] [twitch:vod] 1535261692: Downloading stream metadata GraphQL
[debug] [twitch:vod] 1535261692: Downloading video access token GraphQL
[debug] [twitch:vod] 1535261692: Downloading m3u8 information
[debug] [twitch:vod] 1535261692: Downloading storyboard metadata JSON
[warning] [twitch:vod] Unable to download JSON metadata: HTTP Error 403: Forbidden
[warning] No subtitle format found matching "vtt" for language rechat, using json
'creator'
stop
Traceback (most recent call last):
 File "utils", line 1196, in start
 File "utils", line 1266, in start_
 File "extractor\twitch_downloader", line 53, in read
 File "utils", line 797, in __call__
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\twitch_downloader", line 138, in get
KeyError: 'creator'

Invalid: fail=True
EOT: https://www.twitch.tv/videos/1535261692  (5.5s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Pinkhole** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

안녕하세요

원 글쓴이는 아니지만 동일한 증상을 겪고 있었습니다
해당 테스트 버전을 사용하니 정상적으로 다운로드 되었습니다
항상 고생하십니다

감사합니다

**Comment by 4e55** [comment]
당시에 코멘트남겼다고 생각했는데 다시와보니까 없네요. 
테스트버전 정상작동합니다.
금방 수정해주셔서 감사합니다!
