### ISSUE TITLE
인스타그램 스토리만 있는 계정

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#5033]
스토리만 있는 계정을 다운로드 할 경우 스토리를 다 읽고
게시물을 읽는 단계에서 `Exception: Too short: 0 / 0` 가 발생하며 작업이 중지되는데,
게시물이 없어도 읽은 스토리만 다운로드하게 할 수 있을까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by STR-HK** [comment]
잘 작동합니다. 감사합니다.
