### ISSUE TITLE
TV 아사히에서 m3u8 다운시 소리 없이 저장됩니다.

### ISSUE THREAD

**Issue by holdsnake** [KurtBestor/Hitomi-Downloader#5071]
수고 많으십니다.

Tv 아사히(douga.tv-asahi.co.jp/)에서 m3u8을 이용해 영상을 받으면 소리가 저장되지 않습니다.

팟플레이어는 최신으로 업데이트했으며 주소로 실행시 정상적으로 소리까지 출력됩니다.

혹시몰라서 쿠키까지 넣어봤으나 동일했습니다.

아래는 다운받은 파일 정보입니다.

-------------------------------------------------------------------------------------

master (6a3583e5)

version: 3.7n (22-07-28 02:04:55 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 2 / False / 1d72726100514c57b132ffcc41528a98
input: https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5490902212001/c9eb6834-a8b8-420c-a654-881444503fb9/10s/master.m3u8?behavior_id=efd814f9-917b-494b-a689-33b830191040&fastly_token=NjMwYTdmMzBfZDIzMGJlMGNlZDk2MjdkZDc1YjgwMzQ5NTgwMjA0YjdjMjI0Yzk0YzdkMjQwZTM4MzhkMzU0OTIyOTgzNWIxNA%3D%3D
type: m3u8
single: True
url: https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5490902212001/c9eb6834-a8b8-420c-a654-881444503fb9/10s/master.m3u8?behavior_id=efd814f9-917b-494b-a689-33b830191040&fastly_token=NjMwYTdmMzBfZDIzMGJlMGNlZDk2MjdkZDc1YjgwMzQ5NTgwMjA0YjdjMjI0Yzk0YzdkMjQwZTM4MzhkMzU0OTIyOTgzNWIxNA%3D%3D
dir: hitomi_downloaded_m3u8
zip: 
artist: None
valid / done: True / True
range / range_p: None / None
time: 1659211776.7440977 (22-07-30 20:09:36 UTC)
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.07.18
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]
[0001] hitomi_downloaded_m3u8\master (6a3583e5).mp4

[URLs]
[0001] LazyUrl(https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5490902212001/c9eb6834-a8b8-420c-a654-881444503fb9/10s/master.m3u8?behavior_id=efd814f9-917b-494b-a689-33b830191040&fastly_token=NjMwYTdmMzBfZDIzMGJlMGNlZDk2MjdkZDc1YjgwMzQ5NTgwMjA0YjdjMjI0Yzk0YzdkMjQwZTM4MzhkMzU0OTIyOTgzNWIxNA%3D%3D)    --->    M3u8_stream(https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5490902212001/c9eb6834-a8b8-420c-a654-881444503fb9/5da5fea9-6295-4dc9-a552-25dbcba4e1cf/10s/rendition.m3u8?behavior_id=efd814f9-917b-494b-a689-33b830191040&fastly_token=NjMwYTdmM2JfZjYyNTFlODVmMjI5MGE2NDUzZjc4NTMzYjIyZDkxNjlmYmQ0MmJlZDViNDFiY2UzY2JiNzJmNzIwZjMyNzRmZg%3D%3D)

[Messages]
n_thread: 2
Convert: Downloads\hitomi_downloaded_m3u8\master (6a3583e5).mp4
rename (1): Downloads\hitomi_downloaded_m3u8\master (6a3583e5).mp4 -> Downloads\hitomi_downloaded_m3u8\tmpeda7777aeeb042b8832597e43d7e7a6f_i.mp4
-i tmpeda7777aeeb042b8832597e43d7e7a6f_i.mp4 -acodec copy -vcodec copy -threads 0 tmpeda7777aeeb042b8832597e43d7e7a6f_o.mp4
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Input #0, mpegts, from 'tmpeda7777aeeb042b8832597e43d7e7a6f_i.mp4': 
 Duration: 00:06:14.94, start: 0.066733, bitrate: 1257 kb/s 
 Program 1 
 Stream #0:0[0x102]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn 
Output #0, mp4, to 'tmpeda7777aeeb042b8832597e43d7e7a6f_o.mp4': 
 Metadata: 
   encoder         : Lavf59.8.100 
 Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 90k tbn 
Stream mapping: 
 Stream #0:0 -> #0:0 (copy) 
Press [q] to stop, [?] for help 
frame=    1 fps=0.0 q=-1.0 size=       0kB time=-00:00:00.06 bitrate=N/A speed=N/A     frame=11237 fps=0.0 q=-1.0 Lsize=   55086kB time=00:06:14.84 bitrate=1203.9kbits/s speed=3.58e+03x     
video:54944kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.259618% 
[code]
0
rename (1): Downloads\hitomi_downloaded_m3u8\tmpeda7777aeeb042b8832597e43d7e7a6f_o.mp4 -> \\?\Downloads\hitomi_downloaded_m3u8\master (6a3583e5).mp4
-show_streams -print_format json -v error "master (6a3583e5).mp4"
-ss 74.98 -noaccurate_seek -i "master (6a3583e5).mp4" -vframes 1 "AppData\Local\Temp\tmpa9d18d569e014da29bfd951d71eebb60_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'master (6a3583e5).mp4': 
 Metadata: 
   major_brand     : isom 
   minor_version   : 512 
   compatible_brands: isomiso2avc1mp41 
   encoder         : Lavf59.8.100 
 Duration: 00:06:14.94, start: 0.000000, bitrate: 1203 kb/s 
 Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], 1200 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default) 
   Metadata: 
     handler_name    : VideoHandler 
     vendor_id       : [0][0][0][0] 
Stream mapping: 
 Stream #0:0 -> #0:0 (h264 (native) -> png (native)) 
Press [q] to stop, [?] for help 
Output #0, image2, to '\AppData\Local\Temp\tmpa9d18d569e014da29bfd951d71eebb60_o.png': 
 Metadata: 
   major_brand     : isom 
   minor_version   : 512 
   compatible_brands: isomiso2avc1mp41 
   encoder         : Lavf59.8.100 
 Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 29.97 fps, 29.97 tbn (default) 
   Metadata: 
     handler_name    : VideoHandler 
     vendor_id       : [0][0][0][0] 
     encoder         : Lavc59.12.100 png 
frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x     frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.03 bitrate=N/A dup=0 drop=26 speed=0.408x     
video:1158kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 
[code]
0
stop
EOT: https://manifest.prod.boltdns.net/manifest/v1/hls/v4/aes128/5490902212001/c9eb6834-a8b8-420c-a654-881444503fb9/10s/master.m3u8?behavior_id=efd814f9-917b-494b-a689-33b830191040&fastly_token=NjMwYTdmMzBfZDIzMGJlMGNlZDk2MjdkZDc1YjgwMzQ5NTgwMjA0YjdjMjI0Yzk0YzdkMjQwZTM4MzhkMzU0OTIyOTgzNWIxNA%3D%3D  (14.6s)

---------------------------------------------------------------------------------------------------

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by holdsnake** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

몇개 받아서 실행해보니 소리까지 제대로 출력됩니다. 피드백 감사합니다.
