### ISSUE TITLE
산카쿠 1000개 이상 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by artoargue** [KurtBestor/Hitomi-Downloader#5079]
며칠 전 까지는 잘 되었는데,

안되네요 레인지를 ~ 3000 이나 ~ 3333 이런식으로 넣어줘도 999 까지만 다운로드가 됩니다. 레인지 제한을 두지 않아도 999에서 끊겨버립니다.

[log.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/9242425/log.txt)

**Comment by KurtBestor** [comment]
50 페이지 이상은 로그인 쿠키를 넣어야 다운로드할 수 있어요

**Comment by artoargue** [comment]
쿠키 전부 초기화 후 새로 넣었는데도 동일 증상이 있네요. 작업 정보를 보니 딱 51페이지 까지 보입니다. 혹시 산카쿠 플러스를 해야 하는걸까요

**Comment by artoargue** [comment]
[log.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/9330919/log.txt)
쿠키 초기화 후 넣은 상태에서 로그입니다.

**Comment by KurtBestor** [comment]
당연한 얘기지만 웹브라우저에서 직접 보지 못하는 내용까지 다운로드할 수는 없어요

산카쿠 플러스가 아니면 50 페이지 이상은 볼 수 없어요

**Comment by artoargue** [comment]
아 그랬군요... 여태 잘 작동해서 플러스만 그렇게된지 몰랏네요 답변감사합니다 ㅎㅎ
