### ISSUE TITLE
마나XX 다운이 안됩니다ㅠ_ㅠ

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#5175]
Invalid: [manatoki] https://manatoki151.net/comic/13495692

version: 3.7n (22-07-22 05:55:05 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / e7b72db4464f405795c5ce218e85b2b4
input: https://manatoki151.net/comic/13495692
type: manatoki
single: False
url: https://manatoki151.net/comic/13495692
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1661741242.0981164 (22-08-29 02:47:22 UTC)
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2022.08.19
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1182, in start
 File "decorator", line 232, in fun
 File "constants", line 968, in wrapper
 File "constants", line 939, in wrapper
 File "extractor\manatoki_downloader", line 67, in init
 File "utils", line 592, in __get__
 File "extractor\manatoki_downloader", line 83, in name
 File "extractor\manatoki_downloader", line 105, in get_artist
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
quality: 75%
EOT: https://manatoki151.net/comic/13495692  (137.3s)
![thumb-vXYStQA4Pjqo_240x320](https://user-images.githubusercontent.com/47520785/187114097-df7b54b0-1700-4667-839d-deb9c4a5c565.jpg)

항상 감사합니다^^

**Comment by sb2941** [comment]
유니콘HTTP 깔고 1.1.1.1로 설정해서 키고 우회 프로그램 목록에 히토미 다운로더(현재 사용하는 버전)을 직접 추가로 추가해놓으면 어떨까요?

**Comment by geniussjt** [comment]
그냥 옵션 고급 우회 꼈다 켰다 하니까 다시 잘됩니다ㅠ_ㅠ사이트 문제인가요...영 모르겠습니다

**Comment by geniussjt** [comment]
방금까지 잘 되는데 또 다운이 안되네요...
