### ISSUE TITLE
기본으로 지원되는 사이트에 스크립트 파일을 구할순 없을까요?

### ISSUE THREAD

**Issue by healthy2553** [KurtBestor/Hitomi-Downloader#5236]
북토끼 스크립트를 만들려면 마나토끼 사이트에서 살짝만 바꾸면 된다고 들었는데 사이트에  많던 스크립트 파일들이 없어졌더라고요.. 혹시 구할수있는 방법이 있을까요? 항상 잘 사용하고 있습니다

**Comment by KurtBestor** [comment]
스크립트 없어지지 않았어요
