### ISSUE TITLE
네이버카페는 어떻게 사용하나요??

### ISSUE THREAD

**Issue by emtmin** [KurtBestor/Hitomi-Downloader#5240]
게시글 하나씩 링크를 추가하면 다운은 되는데
게시판이나 작성자 카페 전체 이런건 다운받을순없네요?
네이버카페를 사용하는 다른방법이 있나요????

**Comment by KurtBestor** [comment]
단일 게시물만 지원해요

**Comment by emtmin** [comment]
감사합니다~게시판이나 특정 사용자 작성글도 다운이 되었으면 좋겠습니다^^
항상 고생이 많으십니다~
