### ISSUE TITLE
스크립트 제작 질문 + 의뢰같은건 안받으시나요

### ISSUE THREAD

**Issue by healthy2553** [KurtBestor/Hitomi-Downloader#5244]
마니토끼껄로 북토끼 만드는데 문외한이라 그런지 empty url이라면서 안되는데.. 혹시 방법 아시나요... 진짜 돈받고 스크립트제작같은건 안받으시나 모르겠네요ㅋㅋㅋㅎㅎ...

**Comment by STR-HK** [comment]
한번 사용해 보실래요? : [booktoki.hds](https://raw.githubusercontent.com/STR-HK/hdl-stubs/main/booktoki.hds)

**Comment by healthy2553** [comment]
감사합니다!!!

**Comment by fade-out-0770** [comment]
> 한번 사용해 보실래요? : [booktoki.hds](https://raw.githubusercontent.com/STR-HK/hdl-stubs/main/booktoki.hds)



감사합니다. 정말 잘쓰고 있습니다!!


-----------------------------------------
혹시나 이 페이지에 들어와서 스크립트를 쓰시는 분이 계시다면 스크립트를 메모장으로 열어서 

        src = soup.find("div", class_="view-img").find("img")["src"]
        img = Image(src, "cover")
        self.urls.append(img.url)

이 부분을 지우시고 사용하시면 될듯합니다.
몇 개가 작동안해서 되는 거랑 비교해서 확인해봤는데 커버 이미지가 없는 것들만 다운이 안되었더라구요.
대신 저걸 지우시면 커버이미지는 없을겁니다.

**Comment by inki123** [comment]
> 한 번 사용하시겠습니까? : [booktoki.hds](https://raw.githubusercontent.com/STR-HK/hdl-stubs/main/booktoki.hds)

잘쓰고있습니다. 그런데 사이트문제인지 속도가 너무하네

**Comment by STR-HK** [comment]
커버 이미지 없으면 다운로드하지 않도록 수정했어요.: [booktoki_v2.hds](https://raw.githubusercontent.com/STR-HK/hdl-stubs/main/booktoki_v2.hds)
작동되지 않는 페이지 있을 경우 에러 메시지 남겨주세요.

**Comment by ervlinlake** [comment]
안녕하세여,, 
https://booktoki166.com/novel?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4
여기서 다운로드 하려고 하는데 스크립트를 넣어도 에러가 뜨더라구요... 혹시 어떤 문제가 있어서 그런 건지 궁금합니다...ㅠㅠ

**Comment by STR-HK** [comment]
> 안녕하세여,, https://booktoki166.com/novel?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4 여기서 다운로드 하려고 하는데 스크립트를 넣어도 에러가 뜨더라구요... 혹시 어떤 문제가 있어서 그런 건지 궁금합니다...ㅠㅠ

책 한 권만 다운로드 가능해요

**Comment by STR-HK** [comment]
스크립트 오류 아니에요 #4244

**Comment by inki123** [comment]
지금 마나토끼 만화하나 다운받으면서 방지숫자 적고 나니 북토끼 다운이 가능하게 되네

**Comment by YeonToon** [comment]
안녕하세요.

북토끼 완결 소설 메뉴에 등록된 소설들이 다운로드가 되지 않는 것 같습니다..

[Messages]
'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
File "utils", line 1260, in start
File "utils", line 1336, in start_
File "dynamic_module_0", line 30, in read
File "dynamic_module_0", line 131, in get_artist
File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki215.com/novel/7511375 (11.1s)

감사합니다

**Comment by STR-HK** [comment]
재현할 수 없어요
![image](https://user-images.githubusercontent.com/78652371/213967721-379b7faa-3d75-423b-a13b-792d338b68a5.png)

**Comment by YeonToon** [comment]
> 재현할 수 없어요 ![image](https://user-images.githubusercontent.com/78652371/213967721-379b7faa-3d75-423b-a13b-792d338b68a5.png)

오잉... 지금은 되네요 ㅠㅠ 빠른 확인 감사합니다.

**Comment by Homeo95** [comment]
잘 되던게 얼마 전부터 안되네요. 조언 부탁드립니다.

Invalid: [booktoki] https://booktoki301.com/novel/222?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / ko_kr
order / group / uid: 0 / False / 8c6a4a4cafbc45338b8ff31076d4ad51
input: https://booktoki301.com/novel/222?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4
type: booktoki
single: False
url: https://booktoki301.com/novel/222?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1691379078.322119 (23-08-07 03:31:18 UTC) - 276s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'NoneType' object has no attribute 'find_all'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "dynamic_module_0", line 30, in read
 File "dynamic_module_0", line 131, in get_artist
 File "dynamic_module_0", line 103, in get_info_list
AttributeError: 'NoneType' object has no attribute 'find_all'

Invalid: fail=True
EOT: https://booktoki301.com/novel/222?book=%EC%9D%BC%EB%B0%98%EC%86%8C%EC%84%A4  (9.3s)

**Comment by fenrir79** [comment]
처음에 커버 이미지를 없애기 위해
없애라는 3줄의 코드를 메모장에서 열고 삭제해봤으나
메모장으로 에디트한 파일은 정상적으로
열리지않는건지
그 3줄을 지우는 방식이 문제였는지 적용이 안되더라구요.

커버이미지 없는 링크도 다운로드되는 스크립트를 혹시 올려주실수있을지요.

**Comment by cjm091** [comment]
스크립트 추가했는데도 화(산)귀(환)이나 게임(속) 바(바)리(안) 같은 안 받아지는 애들이 있네여 ㅠㅠ

그리고 혹시 다운 받은 파일에

1화 | (소설제목)-1화

이렇게 들어가는걸 그냥

1화

이렇게만 표시되도록 할 수는 없을까요??

**Comment by yeorinhieut** [comment]
https://github.com/yeorinhieut/novel-dl

한번 사용해 보세요

**Comment by fade-out-0770** [comment]
> https://github.com/yeorinhieut/novel-dl
> 
> 한번 사용해 보세요

잘되네요 감사합니다!!

**Comment by bigmib** [comment]
> https://github.com/yeorinhieut/novel-dl
> 
> 한번 사용해 보세요

주소 치고 회차입력하고 다 했는데도 그냥 프로그램이 꺼지고 아무런 현상도 안일어나네요? 뭐가 문제일려나요

**Comment by yeorinhieut** [comment]
@bigmib
아무런 메세지 없이 꺼지나요?
북토끼에 정상적으로 접근되는 환경인지 체크 부탁드립니다.

혹은
시도하시는 소설 제목 부탁드립니다

**Comment by Chiron-KR** [comment]
> https://github.com/yeorinhieut/novel-dl
> 
> 한번 사용해 보세요

덕분에 잘 쓰고 있습니다. 감사합니다.
