### ISSUE TITLE
업데이트 하는데 문제가 생겼네요...

### ISSUE THREAD

**Issue by elina7** [KurtBestor/Hitomi-Downloader#5265]
자동업데이트 하니 카스퍼스키가 악성코드 감염됬다면서 다운로더 실행파일을 삭제하고 시스템 전체검사를 강제로 시행했습니다
최신버전 받아서 사용하면 문제 없는데 업데이트시에만 계속 악성코드라고 감지하네요
업데이트 서버에 바이러스 감염된거 아닌지 확인좀 부탁드려요...
버전에 상관없이 업데이트만 하면 그러네요

**Comment by KurtBestor** [comment]
카스퍼스키 설치해서 테스트해봤는데 재현할 수가 없네요

참고로 업데이트 체크는 여기서 하고: https://kurtbestor.github.io/res/version_check.txt

다운로드는 `###link_export` 사이에 있는 링크에서 받아요

**Comment by kjy72** [comment]
저도 자동업데이트 하니깐 카스퍼스키 Free에서 바이러스 메시지가 계속 뜨고(TEMP 디렉토리)
재부팅 해보니 hitomi_downloader_GUI.exe가 삭제됐더군요..

Hitomi Downloader v3.7p 직접 다운해서 실행파일을 기존 폴더로 옮기니 여기서는 바이러스 메시지가 안뜨내요..

**Comment by yabuki2** [comment]
네 오진문의 넣었어요
