### ISSUE TITLE
히토미 다운로더 북마크 관련

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#5298]
안녕하세요.

현재는 북마크 순서는 오래된 순서부터 정렬이 되는데요.

![image_2](https://user-images.githubusercontent.com/68507771/193450914-73a6336a-4037-4a10-99c0-eb7534d49c87.png)

OR로 많이 묶어놔서 가시성이 떨어집니다.

그래서 그나마 선호도가 높은 걸 최상단으로 올리려고 다른 북마크를

다 해제했다가 추가하는 걸로 최신화를 한번 시켜줘야만 순서를 변경할 수 있습니다.

그래서 드래그로 순서 정렬이나 한 10개 정도만 우선순위 번호를 부여하거나

아니면 가시성을 위해서 윈도우 이모지 (🎈✨)를 컬러로 지원할 수는 없을까 해서 글 남겨봅니다.

읽어주셔서 고맙습니다.

**Comment by KurtBestor** [comment]
asdf

**Comment by KurtBestor** [comment]
다음과 같이 내보내기 한 파일 텍스트 에디터로 수정해서 불러올 수 있어요:
![image](https://user-images.githubusercontent.com/14768120/197513043-d554c28e-58f4-4851-90a6-ba4f96147aa8.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by DBdeepsleeper** [comment]
혹시 quote reply로 안 하고 여기다 댓글 달아도 보이시나요?

고맙습니다. 잘 돼요.
