### ISSUE TITLE
.MKV Save on YouTube

### ISSUE THREAD

**Issue by Rsfinder** [KurtBestor/Hitomi-Downloader#5417]
YouTube 설정을 추가하여 mkv 파일을 저장할 수 있기를 바랍니다.

다른 다운로더를 사용하고 있습니다만, 개인적으로는 hitomi 쪽이 뛰어나다고 생각합니다.
mkv 형식으로 저장할 수 있으면 최고이므로 꼭 검토해 주십시오.

-------------

I would like to see the ability to save mkv files added to YouTube settings.

I use another downloader, but I personally think hitomi is superior.
It would be great if it could save in mkv format, so please consider this.

**Comment by KurtBestor** [comment]
MKV 는 코덱이 아니라 컨테이너이고 지원하는 곳도 더 적은데 필요한가요?

**Comment by Rsfinder** [comment]
다른 다운로더라면 mkv에서 밖에 8k비디오를 저장할 수 없었기 때문에, mkv는 mp4보다 품질이 좋은 것이라고 생각하고 있었지만, 그렇지 않은 것 같네요.
죄송합니다. 그 밖에 버그나 원하는 기능이 있으면 또 전합니다. 훌륭한 도구를 가져 주셔서 감사합니다.
