### ISSUE TITLE
f3 검색에 site type 중 히요비가 없지 않나요? + 건의사항

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5454]
site의 type에 히요비가 보이지 않습니다. hi로 시작하니 hitomi 근처에 있을 거라 보고 찾았는데도 없고, 전부 다 찾아봐도 보이지 않습니다. 추가해 주셨음 감사하겠습니다.

그리고 필터(f3)을 사용할 때 site 등을 여러개 동시에 선택하고 싶은데 현재 그렇게는 되지 않는 것 같습니다.
가령 type:youtube, type:hitomi 라던가 "type:youtube""type:hitomi"와 같이 작성하면 유튜브와 히토미 둘 다 선택되는 형식으로 만들어 주실 수 없으십니까? 
혹시 이런 기능이 있음에도 제가 모를 가능성도 있어 도움말의 사용법도 읽어봤으나 그런 기능은 적혀있지 않았습니다. 제가 모르는 거였다면 기능에 추가해 주셨음 감사하겠습니다.

**Comment by KurtBestor** [comment]
다음과 같이 검색하면 되고:
```sql
type:hiyobi
```

여러 사이트는 다음과 같이 검색하면 돼요:
```sql
type:hitomi OR type:ehen OR type:hiyobi
```
