### ISSUE TITLE
关于Artstation抓取问题

### ISSUE THREAD

**Issue by benaify** [KurtBestor/Hitomi-Downloader#5473]
你好
例子：https://www.artstation.com/daclakers75
在画师主页的作品能抓取到，但是处于分类中的作品无法抓取到。
![Snipaste_2022-12-01_07-57-35](https://user-images.githubusercontent.com/56367786/204933435-ed0eb0e8-b93e-412f-90ed-832aa09fd3a9.png)
顺便提一下，关于设置里的Artstation的文件夹命名规则好像无法生效。

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
