### ISSUE TITLE
Can't download from flickr

### ISSUE THREAD

**Issue by jaskgit** [KurtBestor/Hitomi-Downloader#5492]
after i authorized.. it takes me to this page...token unavailable...

unable to download... how to solve it?
![flickr](https://user-images.githubusercontent.com/119887295/205712129-bfdea992-8c0b-4577-bc42-cabbf05a9530.png)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by jaskgit** [comment]
Thanks for the help.. solved.. **Appreciated much!!**
