### ISSUE TITLE
프리징이 너무 심합니다

### ISSUE THREAD

**Issue by rybshgsd** [KurtBestor/Hitomi-Downloader#5510]
폰허브 채널 두세개, 영상 7개정도만 링크 긁어놔도 프리징됩니다
시퓨 2600x 램16기가에 크롬만 켜놨습니다
저사양모드도 켜놨습니다

**Comment by KurtBestor** [comment]
시간 지나도 풀리지 않고 계속 프리즈 되어있나요?

**Comment by rybshgsd** [comment]
한 30초정도 멈췄다가 띡 움직이고 무한반복
