### ISSUE TITLE
Enhancement - YouTube published date

### ISSUE THREAD

**Issue by TheGhost78** [KurtBestor/Hitomi-Downloader#5529]
Hi
Great program! There is one key thing missing in my opinion. Please could you include the **published date** in the filenames (at least for YouTube)?
The **YouTube Video and Audio Downloader (Dev Edt.)** extension for Firefox allows you to name files like this:
[author] - [published_date] - [file_name]
and it puts the published date in the format YYYY-MM-DD, which is the ISO standard. That way you can see a chronological list of videos per channel in your downloads folder.
![YT Settings](https://user-images.githubusercontent.com/97525552/208091627-e3bcd178-5134-49f9-b0df-bcb4ef135e22.png)
![YT Filename](https://user-images.githubusercontent.com/97525552/208091631-e3d1641b-9171-437a-9fe9-b84a57d8ea6a.png)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/14768120/de4d6025-6e05-4f89-bf85-b3cc76c1779d)
