### ISSUE TITLE
이미지 변환후 다시받기 질문드립니다.

### ISSUE THREAD

**Issue by himan250** [KurtBestor/Hitomi-Downloader#5541]
픽시브 같은경우는 짤들이 갱신되어 올라오기때문에 주기적으로 다시시작을 눌러 관리해주고 있습니다.

저는 받을때 옵션에서 webp로 변환기능을 쓰는데요
최초에 받고 webp로 변환되어 보관을하고 다시받기를 하면 jpg또는 png (픽시브 원본짤 종류에 따라)가 다시 받아지고 webp로 다시한번 변환이 됩니다.

픽시브 특성상 짤이 수천개 되는것들이 많은데 너무 비효율적이예요
새로 갱신된 짤 파일만 받고 변환되게 수정가능할까요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by himan250** [comment]
감사합니다.
잘됩니다!
