### ISSUE TITLE
F2 작업정보 수정에서 썸네일 변경 건의사항입니다.

### ISSUE THREAD

**Issue by himan250** [KurtBestor/Hitomi-Downloader#5559]
썸네일을 클릭하면 다른파일로 썸네일을 교체 가능한데 webp는 지원이 안되네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by himan250** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

감사합니다.
잘 작동 합니다
