### ISSUE TITLE
업데이트 이후 클립보드 자동추가 오류 

### ISSUE THREAD

**Issue by eleage8992** [KurtBestor/Hitomi-Downloader#5560]
본래 이용할때 1개 이상의 사이트 목록들을 한꺼번에 복사하면 일반 창 상태나 트레이 축소 상태 상관없이
즉시 전부 자동으로 추가가 되었는데

업데이트 이후에는 

목록의 첫번째 사이트만 인식되어 추가됩니다. 

그래서 수동으로 프로그램을 켜서 control + v  해야만 추가가 되네요

확인 부탁드립니다

**Comment by KurtBestor** [comment]
해당 기능을 켜고 문서나 웹페이지 전체를 복사했을 때 띄어쓰기나 줄바꿈으로 나누어진 모든 단어들을 분석하느라 응답없음 상태가 되거나 의도치 않게 모든 링크와 숫자들을 추가하는 문제가 있어서 수정했어요

**Comment by eleage8992** [comment]
답변 감사드립니다.
그렇다면 버그가 아니라 의도한 변경 사항이란 말씀이시죠?
그렇다면 이전처럼 돌아가거나 선택 할수있는 기능에 대한 계획이 있으실까요?
