### ISSUE TITLE
Remember size & position on exit

### ISSUE THREAD

**Issue by doppler56** [KurtBestor/Hitomi-Downloader#5571]
One of the biggest issue I have is resize and reposition every time I start.  Has to be an easy thing to fix.

**Comment by himan250** [comment]
![image](https://user-images.githubusercontent.com/94947106/209436324-219f7e6f-3957-4363-bc40-62cda786d0be.png)

**Comment by doppler56** [comment]
I don't know Korean language.  I use translate web pages plugin on Firefox.  But a picture is worth a thousand words.  I correctly applied your suggestion.  Thanks works as expected.

If this a new option since the last two releases, (I read the release notes).  I may have missed it.
Again thank-you for the pointer.
