### ISSUE TITLE
[Request] CLI argument support

### ISSUE THREAD

**Issue by iG8R** [KurtBestor/Hitomi-Downloader#5584]
Hi.
Could you, please, implement the possibility to pass arguments (URL, custom arguments for yt-dlp) from external sources to Hitomi-Downloader via command line, e.g. there is an addon for Firefox called "Open with...", it can pass the URL to external applications for opening or for any other actions with it. In this way it would be possible to use Hitomi-Downloader to download the videos the user liked without the need to use additional add-ons (extensions).

**Comment by KurtBestor** [comment]
Here is the CLI argument list: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Command-Line-Switches

Hitomi Downloader uses embedded `yt-dlp` for extraction only, not for downloading.

**Comment by KurtBestor** [comment]
Here is the CLI argument list: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Command-Line-Switches

Hitomi Downloader uses embedded `yt-dlp` for extraction only, not for download.

**Comment by iG8R** [comment]
Awesome, thank you.
