### ISSUE TITLE
&lt 로 인한 정보 추출 불가

### ISSUE THREAD

**Issue by kkomaya** [KurtBestor/Hitomi-Downloader#5597]
정보를 추출하려고 하는데, \&lt; 로 저장이 되서 findAll에서 찾지를 못하는 이슈가 있습니다.
(작업 정보의 내용을 붙여 넣으니 정상인 것 처럼 저장이 되어 캡쳐를 첨부 합니다.)
확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/94282707/210284301-be9d0c4f-4559-45ce-988d-b4a1fdd1bc99.png)

----------------------------------------------------------

2분 40초 뒤 다시 시작: https://18av.moe/asian-leaks/7565/

version: 3.8 (22-12-16 05:11:43 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 2ab50c4eea2744bd9a2372a8ebd297f9
input: https://18av.moe/asian-leaks/7565/
type: 18av
single: True
url: https://18av.moe/asian-leaks/7565/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1672700434.2223842 (23-01-02 23:00:34 UTC) - 150s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.01.02
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "dynamic_module_0", line 20, in read
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://18av.moe/asian-leaks/7565/  (9.5s)

'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1353, in start_
 File "dynamic_module_1", line 20, in read
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://18av.moe/asian-leaks/7565/  (9.3s)

<div class="container">
<div class="plyr plyr--full-ui plyr--video plyr--html5 plyr--fullscreen-enabled plyr--paused plyr--stopped plyr--pip-supported plyr__poster-enabled" tabindex="0"><div class="plyr__controls"><button aria-label="Play" class="plyr__controls__item plyr__control" data-plyr="play" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-pause"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="label--pressed plyr__sr-only">Pause</span><span class="label--not-pressed plyr__sr-only">Play</span></button><div class="plyr__controls__item plyr__progress__container"><div class="plyr__progress"><input aria-label="Seek" aria-valuemax="0" aria-valuemin="0" aria-valuenow="0" aria-valuetext="00:00 of 00:00" autocomplete="off" data-plyr="seek" id="plyr-seek-9867" max="100" min="0" role="slider" step="0.01" style="--value:0%;" type="range" value="0"/><progress aria-hidden="true" class="plyr__progress__buffer" max="100" min="0" role="progressbar" value="0">% buffered</progress><span class="plyr__tooltip" hidden="">00:00</span></div></div><div aria-label="Current time" class="plyr__controls__item plyr__time--current plyr__time">00:00</div><div class="plyr__controls__item plyr__volume"><button class="plyr__control" data-plyr="mute" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-muted"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-volume"></use></svg><span class="label--pressed plyr__sr-only">Unmute</span><span class="label--not-pressed plyr__sr-only">Mute</span></button><input aria-label="Volume" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" aria-valuetext="100.0%" autocomplete="off" data-plyr="volume" id="plyr-volume-9867" max="1" min="0" role="slider" step="0.05" style="--value:100%;" type="range" value="1"/></div><button class="plyr__controls__item plyr__control" data-plyr="captions" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-captions-on"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-captions-off"></use></svg><span class="label--pressed plyr__sr-only">Disable captions</span><span class="label--not-pressed plyr__sr-only">Enable captions</span></button><div class="plyr__controls__item plyr__menu"><button aria-controls="plyr-settings-9867" aria-expanded="false" aria-haspopup="true" class="plyr__control" data-plyr="settings" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-settings"></use></svg><span class="plyr__sr-only">Settings</span></button><div class="plyr__menu__container" hidden="" id="plyr-settings-9867"><div><div id="plyr-settings-9867-home"><div role="menu"><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Captions<span class="plyr__menu__value">Disabled</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Quality<span class="plyr__menu__value">undefined</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" role="menuitem" type="button"><span>Speed<span class="plyr__menu__value">Normal</span></span></button></div></div><div hidden="" id="plyr-settings-9867-captions"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Captions</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-9867-quality"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Quality</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-9867-speed"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Speed</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.5"><span>0.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.75"><span>0.75×</span></button><button aria-checked="true" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1"><span>Normal</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.25"><span>1.25×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.5"><span>1.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.75"><span>1.75×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="2"><span>2×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="4"><span>4×</span></button></div></div></div></div></div><button class="plyr__controls__item plyr__control" data-plyr="pip" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-pip"></use></svg><span class="plyr__sr-only">PIP</span></button><button class="plyr__controls__item plyr__control" data-plyr="fullscreen" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-exit-fullscreen"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-enter-fullscreen"></use></svg><span class="label--pressed plyr__sr-only">Exit fullscreen</span><span class="label--not-pressed plyr__sr-only">Enter fullscreen</span></button></div><div class="plyr__video-wrapper">&lt;video controls,="" allow-same-origin,="" widht="100%" ,="" data-poster="https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg" id="player"&gt;
         \&lt;source src="//cdn1.thepervs.com/videos/57120.mp4" type="video/mp4" ,="" size="576"\&gt;
<div class="plyr__poster" style='background-image: url("https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg");'></div></div><div class="plyr__captions"></div><button aria-label="Play" class="plyr__control plyr__control--overlaid" data-plyr="play" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="plyr__sr-only">Play</span></button></div>
<script src="https://cdn.plyr.io/3.7.2/plyr.js"></script>
</div>
No data found
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1368, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://18av.moe/asian-leaks/7565/  (9.4s)

<div class="container">
<div class="plyr plyr--full-ui plyr--video plyr--html5 plyr--fullscreen-enabled plyr--paused plyr--stopped plyr--pip-supported plyr__poster-enabled" tabindex="0"><div class="plyr__controls"><button aria-label="Play" class="plyr__controls__item plyr__control" data-plyr="play" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-pause"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="label--pressed plyr__sr-only">Pause</span><span class="label--not-pressed plyr__sr-only">Play</span></button><div class="plyr__controls__item plyr__progress__container"><div class="plyr__progress"><input aria-label="Seek" aria-valuemax="0" aria-valuemin="0" aria-valuenow="0" aria-valuetext="00:00 of 00:00" autocomplete="off" data-plyr="seek" id="plyr-seek-3136" max="100" min="0" role="slider" step="0.01" style="--value:0%;" type="range" value="0"/><progress aria-hidden="true" class="plyr__progress__buffer" max="100" min="0" role="progressbar" value="0">% buffered</progress><span class="plyr__tooltip" hidden="">00:00</span></div></div><div aria-label="Current time" class="plyr__controls__item plyr__time--current plyr__time">00:00</div><div class="plyr__controls__item plyr__volume"><button class="plyr__control" data-plyr="mute" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-muted"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-volume"></use></svg><span class="label--pressed plyr__sr-only">Unmute</span><span class="label--not-pressed plyr__sr-only">Mute</span></button><input aria-label="Volume" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" aria-valuetext="100.0%" autocomplete="off" data-plyr="volume" id="plyr-volume-3136" max="1" min="0" role="slider" step="0.05" style="--value:100%;" type="range" value="1"/></div><button class="plyr__controls__item plyr__control" data-plyr="captions" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-captions-on"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-captions-off"></use></svg><span class="label--pressed plyr__sr-only">Disable captions</span><span class="label--not-pressed plyr__sr-only">Enable captions</span></button><div class="plyr__controls__item plyr__menu"><button aria-controls="plyr-settings-3136" aria-expanded="false" aria-haspopup="true" class="plyr__control" data-plyr="settings" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-settings"></use></svg><span class="plyr__sr-only">Settings</span></button><div class="plyr__menu__container" hidden="" id="plyr-settings-3136"><div><div id="plyr-settings-3136-home"><div role="menu"><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Captions<span class="plyr__menu__value">Disabled</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Quality<span class="plyr__menu__value">undefined</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" role="menuitem" type="button"><span>Speed<span class="plyr__menu__value">Normal</span></span></button></div></div><div hidden="" id="plyr-settings-3136-captions"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Captions</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-3136-quality"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Quality</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-3136-speed"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Speed</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.5"><span>0.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.75"><span>0.75×</span></button><button aria-checked="true" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1"><span>Normal</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.25"><span>1.25×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.5"><span>1.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.75"><span>1.75×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="2"><span>2×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="4"><span>4×</span></button></div></div></div></div></div><button class="plyr__controls__item plyr__control" data-plyr="pip" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-pip"></use></svg><span class="plyr__sr-only">PIP</span></button><button class="plyr__controls__item plyr__control" data-plyr="fullscreen" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-exit-fullscreen"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-enter-fullscreen"></use></svg><span class="label--pressed plyr__sr-only">Exit fullscreen</span><span class="label--not-pressed plyr__sr-only">Enter fullscreen</span></button></div><div class="plyr__video-wrapper">&lt;video controls,="" allow-same-origin,="" widht="100%" ,="" data-poster="https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg" id="player"&gt;
         &lt;source src="//cdn1.thepervs.com/videos/57120.mp4" type="video/mp4" ,="" size="576"&gt;
<div class="plyr__poster" style='background-image: url("https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg");'></div></div><div class="plyr__captions"></div><button aria-label="Play" class="plyr__control plyr__control--overlaid" data-plyr="play" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="plyr__sr-only">Play</span></button></div>
<script src="https://cdn.plyr.io/3.7.2/plyr.js"></script>
</div>
No data found
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1368, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://18av.moe/asian-leaks/7565/  (9.5s)

<div class="container">
<div class="plyr plyr--full-ui plyr--video plyr--html5 plyr--fullscreen-enabled plyr--paused plyr--stopped plyr--pip-supported plyr__poster-enabled" tabindex="0"><div class="plyr__controls"><button aria-label="Play" class="plyr__controls__item plyr__control" data-plyr="play" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-pause"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="label--pressed plyr__sr-only">Pause</span><span class="label--not-pressed plyr__sr-only">Play</span></button><div class="plyr__controls__item plyr__progress__container"><div class="plyr__progress"><input aria-label="Seek" aria-valuemax="0" aria-valuemin="0" aria-valuenow="0" aria-valuetext="00:00 of 00:00" autocomplete="off" data-plyr="seek" id="plyr-seek-6819" max="100" min="0" role="slider" step="0.01" style="--value:0%;" type="range" value="0"/><progress aria-hidden="true" class="plyr__progress__buffer" max="100" min="0" role="progressbar" value="0">% buffered</progress><span class="plyr__tooltip" hidden="">00:00</span></div></div><div aria-label="Current time" class="plyr__controls__item plyr__time--current plyr__time">00:00</div><div class="plyr__controls__item plyr__volume"><button class="plyr__control" data-plyr="mute" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-muted"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-volume"></use></svg><span class="label--pressed plyr__sr-only">Unmute</span><span class="label--not-pressed plyr__sr-only">Mute</span></button><input aria-label="Volume" aria-valuemax="100" aria-valuemin="0" aria-valuenow="100" aria-valuetext="100.0%" autocomplete="off" data-plyr="volume" id="plyr-volume-6819" max="1" min="0" role="slider" step="0.05" style="--value:100%;" type="range" value="1"/></div><button class="plyr__controls__item plyr__control" data-plyr="captions" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-captions-on"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-captions-off"></use></svg><span class="label--pressed plyr__sr-only">Disable captions</span><span class="label--not-pressed plyr__sr-only">Enable captions</span></button><div class="plyr__controls__item plyr__menu"><button aria-controls="plyr-settings-6819" aria-expanded="false" aria-haspopup="true" class="plyr__control" data-plyr="settings" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-settings"></use></svg><span class="plyr__sr-only">Settings</span></button><div class="plyr__menu__container" hidden="" id="plyr-settings-6819"><div><div id="plyr-settings-6819-home"><div role="menu"><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Captions<span class="plyr__menu__value">Disabled</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" hidden="" role="menuitem" type="button"><span>Quality<span class="plyr__menu__value">undefined</span></span></button><button aria-haspopup="true" class="plyr__control plyr__control--forward" data-plyr="settings" role="menuitem" type="button"><span>Speed<span class="plyr__menu__value">Normal</span></span></button></div></div><div hidden="" id="plyr-settings-6819-captions"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Captions</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-6819-quality"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Quality</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"></div></div><div hidden="" id="plyr-settings-6819-speed"><button class="plyr__control plyr__control--back" type="button"><span aria-hidden="true">Speed</span><span class="plyr__sr-only">Go back to previous menu</span></button><div role="menu"><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.5"><span>0.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="0.75"><span>0.75×</span></button><button aria-checked="true" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1"><span>Normal</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.25"><span>1.25×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.5"><span>1.5×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="1.75"><span>1.75×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="2"><span>2×</span></button><button aria-checked="false" class="plyr__control" data-plyr="speed" role="menuitemradio" type="button" value="4"><span>4×</span></button></div></div></div></div></div><button class="plyr__controls__item plyr__control" data-plyr="pip" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-pip"></use></svg><span class="plyr__sr-only">PIP</span></button><button class="plyr__controls__item plyr__control" data-plyr="fullscreen" type="button"><svg aria-hidden="true" class="icon--pressed" focusable="false"><use xlink:href="#plyr-exit-fullscreen"></use></svg><svg aria-hidden="true" class="icon--not-pressed" focusable="false"><use xlink:href="#plyr-enter-fullscreen"></use></svg><span class="label--pressed plyr__sr-only">Exit fullscreen</span><span class="label--not-pressed plyr__sr-only">Enter fullscreen</span></button></div><div class="plyr__video-wrapper">&lt;video controls,="" allow-same-origin,="" widht="100%" ,="" data-poster="https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg" id="player"&gt;
         &lt;source src="//cdn1.thepervs.com/videos/57120.mp4" type="video/mp4" ,="" size="576"&gt;
<div class="plyr__poster" style='background-image: url("https://18av.moe/wp-content/uploads/2022/08/57120-1-640x360.jpg");'></div></div><div class="plyr__captions"></div><button aria-label="Play" class="plyr__control plyr__control--overlaid" data-plyr="play" type="button"><svg aria-hidden="true" focusable="false"><use xlink:href="#plyr-play"></use></svg><span class="plyr__sr-only">Play</span></button></div>
<script src="https://cdn.plyr.io/3.7.2/plyr.js"></script>
</div>
No data found
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1278, in start
 File "utils", line 1368, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://18av.moe/asian-leaks/7565/  (9.4s)

**Comment by KurtBestor** [comment]
스크립트가 어떻게 되나요?

**Comment by kkomaya** [comment]
기존 Sogirl의 Script를 변경했습니다.

#coding: utf8
#title: 18av.moe 사이트 추가 - 수정
#author: Kurt Bestor (이후 수정됨)
#discription: 12022-01-30 수정

import clf2
from utils import *
import json

@Downloader.register
class Downloader_sogirl(Downloader):
    type = '18av'
    URLS = ['18av.moe']
    single = True

    def read(self):
        html = self.get_page()

        soup = Soup(html)
        title = soup.find('meta', {'property': 'og:title'})['content'].strip()

        playlist = soup.find('div', class_='container')
        self.print_(playlist)                   <- 이부분을 통해서 출력했을때 '<' 을 제대로 인식을 못하는 거와 같이 출력이 됩니다.

        srcs = []                                   <- 동작성을 보기 위해 try에서 밖으로 빼본 코드 입니다. 
        for a in playlist.findAll('source'):
            self.print_(a)
            
        try:
            srcs = []
            for a in playlist.findAll('src'):
                data = a
                #.get('src')
                if not data:
                    continue
                data = 'https:' + data      <- https:가 누락되어서 안되는가 싶어 추가한 부분입니다.
                srcs.append(data)

            url_video = srcs[0]
            print_(srcs[0])
            self.urls.append(url_video)
            self.filenames[url_video] = '{}{}'.format(clean_title(title), get_ext(url_video))
            self.referer = self.url

            self.title = title
        except:
            self.print_('No data found')

    @try_n(16)
    def get_page(self):
        html = clf2.solve(self.url)

        if '502: Bad gateway' in html['html']:
            self.print_(f'Cloudflare Bad Gateway Error Occured')
            raise Exception('bad gateway')

        return html['html']

log('script loaded')

**Comment by KurtBestor** [comment]
```python
Soup(html)
```
를 다음과 같이 바꾸세요:
```python
Soup(html, 'lxml')
```

참고로 ```playlist.findAll('src')``` 가 아니라 ```playlist.findAll('source')``` 예요

**Comment by kkomaya** [comment]
코멘즈 주신대로 수정하니 정상적으로 동작을 하네요.
감사합니다.^^
