### ISSUE TITLE
3.8a Not following download limit for hitomi.la site

### ISSUE THREAD

**Issue by doppler56** [KurtBestor/Hitomi-Downloader#5621]
If you download more than 1 at a time on hitomi.la website your IP can get permanently banned.  My option preference setting is set to one down at a time and one thread.  I see two at a time downloading.

**Comment by doppler56** [comment]
Didn't repeat.  One off problem maybe ?

**Comment by doppler56** [comment]
Yes it did repeat again.  Not consistently failing.  I now must load only one download and wait.  Or risk getting IP banned.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
btw, You won't be blocked by downloading 2 at the same time. It's the same as opening 2 "Read Online" page tabs in a web browser.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
btw, You won't be banned by downloading 2 at the same time. It's the same as opening 2 "Read Online" page tabs in a web browser.

**Comment by doppler56** [comment]
I will give the TP a review.  Hopefully this is a fix.  Back in the day, when they changed from the 6 servers they were using.  And went to a BLOB download interface, with very funny filenames.  They were banning anybody doing two of more consecutive downloads in tabs.  They did not have there act together for the beginning.  So they cleared all the bans a couple of days later.  Until I found Hitomi-Downloader, I was regulated to one download tab at a time.

Nothing personal I just setup Hitomi-Downloader to only do a single thread and single download.  Didn't want to chance it.
