### ISSUE TITLE
다운로더 실행시 dc인사이드 사이트 먹통 

### ISSUE THREAD

**Issue by owlgaga** [KurtBestor/Hitomi-Downloader#5659]
다운로더를 키고 디시인사이드 사이트를 들어가면 
무한로딩이 걸리는데 이유가 뭘까요...

사이트를 들어가고 다운로더를 켜도
사이트 내부에서 뭘 하려고 클릭해도 무한로딩이 걸려요.
그러다가 '사이트에 연결할수 없음' 알림이 뜹니다.

다른곳은 안그러는데 꼭 디시인사이드 사이트만 그런 현상이 나타나요.
이유를 알 수 있을까요 ㅠㅠ

**Comment by wlskekrk** [comment]
저도 그랬는데 네트워크 설정에서 dpi 우회를 키면 그렇더라구요

**Comment by owlgaga** [comment]
> 저도 그랬는데 네트워크 설정에서 dpi 우회를 키면 그렇더라구요

감사합니다! 한번에 해결됐어요 👍
