### ISSUE TITLE
twitter.com과 mobile.twitter.com 간에 중복 체크가 되지 않음

### ISSUE THREAD

**Issue by depth221** [KurtBestor/Hitomi-Downloader#5687]
프로그램 잘 쓰고 있습니다.
다름이 아니라 mobile.twitter.com/AAA로 계정 이미지를 다운로드한 후 twitter.com/AAA를 입력하면 중복 처리가 되지 않고 동일한 항목이 새롭게 추가됩니다.
파일은 둘 다 동일한 폴더에 저장되기는 하지만, 일괄 다운로드를 돌렸을 때 한 계정을 두 번이나 다운로드 시도하는 문제가 있어 개선 건의드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by depth221** [comment]
정상적으로 작동합니다. 감사합니다!
