### ISSUE TITLE
혹시 유튜브 영상 다운로드시 썸네일은 추출이 안되나요?

### ISSUE THREAD

**Issue by SAKR7** [KurtBestor/Hitomi-Downloader#5697]
자료 수집 할 때 유용하게 쓰고 있습니다. 

그런데 유튜브 영상 추출 시에 썸네일까지 포함되서 추출 하는게 아니라 영상만 추출하는것 같아서요 

영상 모아놓고 어느 영상인지 빠르게 볼려면 썸네일 유무도 중요하게 생각해서 썸네일도 넣을 수 있으면 좋겠는데 기술적으로 어려운 부분인가요?

**Comment by KurtBestor** [comment]
같은 경로에 썸네일 파일까지 있으면 파일 갯수가 두 배 되어서 지저분할 것 같아서 기본 기능에 넣지는 않을 계획이고, [여기](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins) 에서 `Save YouTube thumbnails after task is finished` 의 `hook_save_thumb.hds` 스크립트 받아서 `옵션 - 플러그인` 에 추가해서 사용하세요

**Comment by SAKR7** [comment]
확인했습니다 바쁘실텐데 번거롭게 해드려 죄송합니다. 플러그인 쪽에 따로 있었네요 감사합니다! :D
