### ISSUE TITLE
리딩 속도를 더 빠르게 할 순 없을까요?

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5726]
제목그대로의 요청입니다... 1000화 정도 되는 것들은 읽는 데에만 시간이 엄청나게 걸려서 문제인 것 같습니다. 아무것도 하지 않고 사용만 하는 사람의 입장으로서는 이런 부탁을 드리는 것도 죄송합니다만, 리딩속도를 더 빠르게 하는 방법은 없을까요?

현재 python으로 만들어진 프로그램을 리딩이나 다운로딩 부분만 c로 작성한다던지요. 그런다고 얼마나 빨라질지도 전문가가 아닌 저로서는 잘 모르겠지만 혹시 꽤나 개선될 가능성이 있다면 부탁드립니다.

**Comment by depth221** [comment]
이런 크롤링 프로그램은 웹사이트 측에서 최대한 막으려고 혈안이 되어 있어서 프로그램이라는 것을 최대한 숨기기 위해 다운로드 속도를 일부러 지연시키는 걸로 알고 있습니다. 파일 다운로드가 CPU를 그렇게 많이 갈구는 것도 아니라서 파이썬과 C의 속도 차이는 적을 거예요.
