### ISSUE TITLE
앱체크 오진 있습니다

### ISSUE THREAD

**Issue by gaon12** [KurtBestor/Hitomi-Downloader#5752]
![image](https://user-images.githubusercontent.com/34927797/221752994-42407555-d49f-43b3-afd0-c239ce2bfca0.png)

사진과 같이 앱체크에서 다운로더에 대해 랜섬웨어 오탐지가 있습니다.

로그 파일을 첨부합니다.

[appcheck.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/10846579/appcheck.txt)

폴더 경로를 확인해 보니, 'goodbyedpi_64.exe', 'WinDivert.dll', 'WinDivert64.sys' 파일이 있는 경로네요.

일단 신뢰 프로세스로 등록해 놓았긴 했는데, 개발자 분께서도 아시면 좋을 거 같아서 이슈 등록합니다.

**Comment by KurtBestor** [comment]
[GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI) 에서 쓰는 [WinDivert](https://github.com/basil00/Divert) 를 오진하는 상황인데 해당 백신에 오진 보고 부탁드려요

**Comment by gaon12** [comment]
앱체크 쪽에 오진 문의를 보냈습니다. 차후 오진 해결되면 이슈 close해두겠습니다!

![Screenshot_20231216_102444_Gmail](https://github.com/KurtBestor/Hitomi-Downloader/assets/34927797/50523dd5-57f7-42a5-b207-2d1d8f1de961)

**Comment by gaon12** [comment]
![IMG_0962](https://github.com/KurtBestor/Hitomi-Downloader/assets/34927797/dfea7283-c6ce-424f-96e5-20fd6dc389d8)

앱체크 쪽에서는 사용자 측에서 수동으로 예외처리 하라고 답변을 받았습니다. 시그니처리스 방식이라 별도로 예외처리하기 어려워서 사용자에게 수동으로 예외처리 등록하라고 한 것 같습니다.

일단 이 이슈는 닫겠습니다. 나중에 예외처리 하지 않더라도 오진이 발생하지 않는다면 추가로 메시지 남겨놓도록 하겠습니다!
