### ISSUE TITLE
"Get cookies.txt" extension is malware, what other extension should I use?

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader#5811]
I was using the "Get cookies.txt" extension but since January 2023 the extension turned to malware so I deleted it, what other extension can I use to get the "cookie" file to use it with Hitomi Downloader?

Thanks.

**Comment by dkfle222** [comment]
Hello

https://chrome.google.com/webstore/detail/open-cookiestxt/gdocmgbfkjnnpapoeobnolbbkoibbcif
https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc
https://chrome.google.com/webstore/detail/get-cookiestxt-clean/ahmnmhfbokciafffnknlekllgcnafnie

**Comment by xZabuzax** [comment]
> Hello
> 
> https://chrome.google.com/webstore/detail/open-cookiestxt/gdocmgbfkjnnpapoeobnolbbkoibbcif https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc https://chrome.google.com/webstore/detail/get-cookiestxt-clean/ahmnmhfbokciafffnknlekllgcnafnie

Excellent, thanks mate!
