### ISSUE TITLE
Hitomi Downloader affected by the Twitter API? (& Request to folder name)

### ISSUE THREAD

**Issue by Rsfinder** [KurtBestor/Hitomi-Downloader#5841]
I’m still not using Hitomi to save my Twitter media. But now that they have announced their new API plan, I am thinking of switching to this one.

So I would like to know if this downloader uses the Twitter API.

Also, what precautions, if any, should I take when storing data?
I know this is a trivial question, but I would appreciate your response.

--------------------

One more feature request...

I would like to have the ability to change the folder name for saving Twitter accounts as follows.
"Account Name" (@Screen Name) -> "Account Name" (Account ID)

Screen names often change, so please consider implementing this feature.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
You can check the id at `Task info - extras - uids`
