### ISSUE TITLE
플레이리스트 순서대로 번호 매기기, 오름차순 내림차순 선택 가능하게 해주심 안될까요?

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5848]
보통 노래는 앨범을 다운받는다고 하면 플레이리스트를 위에서 아래로 내려가는 식으로 번호가 매겨져야 하지만, 유튜브 채널 하나를 통째로 다운받는다면 밑에서 위로 번호를 매기는 게 다음에 새로운 동영상이 올라왔을 때 번호가 바뀌었기에 다시 모든 동영상을 다운받는 불상사를 막을 수 있다고 생각합니다. 
현재 플레이리스트에 번호를 매기는 것은 오름차순, 내림차순 구분이 없는 걸로 알고 있습니다. 또한 제일 최근에 올라온 동영상, 즉 제일 위에 있는 동영상부터 1 2 3 4 5 6 7 8 9 10으로 번호를 매기는 오름차순으로 운영되고 있죠. 이를 내림차순으로도 가능하게 해주셨음 합니다.

항상 감사드립니다.

**Comment by KurtBestor** [comment]
`옵션 - 설정 - YouTube - 채널 영상 역순으로 다운로드` 에서 설정할 수 있어요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
넵 잘 작동하는 거 같습니다. 감사합니다.
