### ISSUE TITLE
동영상 중 playtime으로 검색할 수는 없나요?

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5886]
유튜브 동영상 중에 1분 미만인 동영상 중에서 찾고싶은 게 있습니다만, 다운 받아놓은 동영상을 전부 뒤지기는 그러니 1분 이하만 남겨서 찾으려고 합니다만, playtime으로 검색은 안되는 거 같더군요. 다른 분들도 이 기능 있으면 많이 사용하실 거 같아서 문의드립니다.

가령 playtime<60 하면 60초 이하의 동영상만 나온다거나 하는 식으로요. 물론 다운로더에 시간이 기록되어 있는 동영상에 한해서요.

기능 추가 가능할지 여쭙니다.

또한, 도움말에 type:youtube AND type:hitomi 이런식으로 여러개를 동시에 검색 가능하다는 걸 써놓아주실 수는 없으신가요? 구체적으로 설명되어 있지가 않으니 알기가 어려워서요. AND를 붙이면 된다는 것도 저번에 질문을 올려서 알게 되었거든요. 설명서가 상세하다면 질문 수도 줄어들 것이라 생각합니다.

**Comment by KurtBestor** [comment]
`OR` 를 `AND` 로 잘못 쓰신 것 같네요

"사용법 (F1) - 다운로더 작업 목록 필터링" 참고해주세요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
사용법은 추가가 된 것을 확인했습니다. 감사합니다. 혹시 동영상의 playtime을 갖고 검색기능을 만드실 생각은 아직은 없으신 겁니까? 후자만 추가되고 전자는 추가되지 않았음에도 아무 말씀도 안하시길래 질문합니다.

**Comment by KurtBestor** [comment]
사용법 다시 자세히 보세요

**Comment by hwnnhji** [comment]
감사합니다
