### ISSUE TITLE
Change of id in chan.sankakucomplex

### ISSUE THREAD

**Issue by rickmiron** [KurtBestor/Hitomi-Downloader#5890]
I have recently seen that the url of the images are not a number, they are the md5 hash of the image. Modify the sankaku file so that it can work as before
This is the file link: https://github.com/rickmiron/variado/archive/refs/heads/main.zip
the .py file is added in plugins

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/issues/5892

**Comment by rickmiron** [comment]
Thanks for waiting, here is the plugin: https://github.com/rickmiron/variado/blob/main/imhentai_downloader.py
