### ISSUE TITLE
엔터키의 활용

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5905]
이게 왜 안될까 싶은 부분이 있어서 질문드립니다. 그냥 귀찮아서 키보드로만 슥슥 조작하고 있을 때, 그룹을 펼치려고 그룹 위를 드래그? 선택?을 키보드 방향키로 한 다음에 엔터를 눌렀는데 그룹이 펼쳐지지 않더라구요? 엔터키 누르면 그룹 펼쳐지게 해주실 수 없으십니까?

**Comment by STR-HK** [comment]
일단 현재는 스페이스로는 열릴 거에요

**Comment by KurtBestor** [comment]
`도움말 - 기타 단축키` 에 설명되어있어요
