### ISSUE TITLE
혹시 설치 폴더 통채로 옮겨도 실행 정상적으로 가능한가요?

### ISSUE THREAD

**Issue by gkdldy2** [KurtBestor/Hitomi-Downloader#5950]
hdd에 설치하니 너무 느려서 ssd로 옮기려 하는데 방법 아시는분 계신가요?

**Comment by STR-HK** [comment]
네 됩니다

**Comment by DBdeepsleeper** [comment]
> hdd에 설치하니 너무 느려서 ssd로 옮기려 하는데 방법 아시는 분 계신가요?

프로그램 폴더 하위에 폴더 생기고 다운로드되니까 통째로 옮기시면 돼요.
