### ISSUE TITLE
직접 다운로드 관련해서 질문드려요!

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#5958]
다운로더가 지원하지 않는 링크를 추가해서 직접 다운로드하는 경우 그냥 사진 파일같은 겨면 그 파일이 받아지고, 홈페이지같은 경우는 html로 받아지더라구요? 이거 관련해서 질문드려요!

1. 직접 다운로드하기는 정확히 뭘 다운로드 하는 건가요? 저는 위에서 말한 대로 그냥 사진링크면 사진이 단순한 홈페이지면 홈페이지가 다운받아지는 줄 알았는데 나무위키같은 경우는
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/40c88e50-ed23-43ef-840b-5b42ac8d1985)
이렇게 이상한 파일로 다운되더라구요? 당연히 html로 받아질줄 알았는데 아니었어요, 이런 측면에서 보면 현재의 직접다운로드는 너무 직관적이지 않은 것 같다고 생각해요. 혹시 직접다운로드를 하는 경우는 반드시 html로 다운받게 해라~ 같은 기능을 만들어주실 수 없으신가요? 그래야 훨신 사람들이 직접 다운로드 기능을 직접적으로 활용하거나, 많이 사용하게 될 것 같아요.

2. html파일같은 경우 홈페이지를 구성하는 이미지같은 걸 따로 다운받아서 따로 폴더안에 저장해두고 html파일을 열면 그 폴더 안에서 사진 등을 갖고 와서 구성하는 식으로 작동하는 걸로 알고 있었는데요, 다운로더가 html 다운받은 걸 보니까 따로 폴더가 안생기던데 따로 폴더를 저장하는 곳이 있는 건가요? 작업 하나를 다운받는다 하면 파일 하나만 생기는 게 관리하기도 쉽고 깔끔하니까 그럼 단일파일인 mhtml로 받아졌으면 좋겠다~ 라고 생각하는 와중에 보니까 이미 html 파일이 추가적인 이미지 등을 저장하는 폴더가 없이 하나밖에 없길래 질문드려요.
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/b9ec6c17-e944-4156-bec3-3a3609b91b6a)
항상 html로 저장하면 따로 폴더가 같이 받아지던데 이건 없더라구요?

3. 그리고 단순히 html로 다운받는다고 하면! mhtml파일로 받아지게 해주실 수 없으신가요? 1번이랑 엮는다고 하면 mhtml로 다운받아라! 같은 기능이 있으면 단일파일이니까 복잡해지지 않을 거 같아서 말씀드려요.

4. 유튜브같이 다운로더가 지원하는 사이트의 경우도 직접다운로드를 통해서 html 등을 다운받을 수 있게 해주실 수 없으신가요? 가령 인스타에서 피드 하나를 다운받았다고 하면 사진이 다운받아지는데, 거기 글귀 같은 것도 저장해두고 싶다할 때 글귀만 따로 notepad에 저장해두기도 번거로우니까요... 그냥 html하나로 다운받았으면 하는데 이미 지원하는 사이트의 경우는 추가적으로 다운로드를 할 수가 없더라구요? 그래서 그런데 혹시 
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/f2707d77-c0ad-4797-b37d-7c07524c1f4c)
이런 부분이나 혹은 단축키를 사용하는 식으로 이미 다운로드 된 작업도 직접 다운로드를 가능하게 해주실 수 없으신가요? 그렇게 다운받은 파일은 동일한 폴더에 저장되거나 하는 식으로요.

추가된다면 직접다운로드 기능도 꽤나 유용하게 사용될 거라고 생각해요! 추가되었으면 합니다. 뭔가 엄청 길게 썼는데 뭔가 별로더라고 긍정적으로 검토해주셨음해요... 감사합니다

**Comment by STR-HK** [comment]
1. 직접 다운로드는 제공된 url에 GET요청을 날려서 받은 결과물을 저장해요
2. 1번 참고해주세요
3. 1번 참고해주세요

**Comment by limdongseop** [comment]
직접다운로드는 어떻게 하는 건가요?
