### ISSUE TITLE
루리웹 다운로드가 안됩니다.

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6038]
Invalid: [ruliweb] https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good

version: 3.8c (23-05-04 21:08:36 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 897 / False / 667c84a571f6425a8358e2ffde81394a
input: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good
type: ruliweb
single: False
url: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1686818219.5821903 (23-06-15 08:36:59 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True

[Gallery]
None

[File Names]

[URLs]

[Messages]
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.4s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (2.5s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.0s)

쿠키 새로 불러오기, 초기화, 프로그램 껐다 키기 등 시도해봤는데 안되는 거 같습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins

**Comment by hwnnhji** [comment]
Invalid: [ruliweb] https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good

version: 3.8c (23-06-21 11:48:38 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 1232 / False / 667c84a571f6425a8358e2ffde81394a
input: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good
type: ruliweb
single: False
url: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1687488928.602409 (23-06-23 02:55:28 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: False


[Gallery]
None


[File Names]



[URLs]



[Messages]
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.2s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.4s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (2.5s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.0s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.0s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1290, in start
 File "utils", line 1386, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.0s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1445, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.1s)

empty urls
stop
Traceback (most recent call last):
 File "utils", line 1349, in start
 File "utils", line 1445, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://bbs.ruliweb.com/etcs/board/300780/read/49031637?search_type=subject&search_key=%EB%8D%B0%EC%9D%B4%ED%84%B0&%EC%8A%A4%ED%8F%AC_%EC%A3%BC%EC%9D%98=&cate=519&page=33&view=thumbnail&orderby=good  (1.3s)


저만 안되는 건지는 모르겠으나 여전히 안됩니다.

**Comment by hwnnhji** [comment]
잘 작동합니다. 감사합니다.
