### ISSUE TITLE
작가추천 실행시 오류가 나옵니다

### ISSUE THREAD

**Issue by KFromage** [KurtBestor/Hitomi-Downloader#606]
![20190303_002714](https://user-images.githubusercontent.com/46770150/53693478-5e926100-3de4-11e9-8571-2188079c406e.jpg)

다음과 같은 오류가 뜨더군요
무슨 오류인가요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader-issues/issues/588
