### ISSUE TITLE
트로이목마 감지되었다고 뜨네요

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6081]
카스퍼스키 사용중입니다. 3.8d 업데이트가 떠서 그냥 자동 업데이트로 눌렀는데, 카스퍼스키에서 exe_old 파일에서 트로이목마를 발견했다고 하더라구요. 

이벤트: 개체 삭제
애플리케이션: Hitomi Downloader
사용자: DESKTOP-
사용자 유형: 개시자
구성 요소: 시스템 감시기
결과 설명: 삭제됨
유형: 트로이목마
이름: PDM:Trojan.Win32.Generic
위험도: 높음
개체 유형: 처리
개체 경로: E:\ㅇ\hitomi_downloader_GUI (1)\tmp_update
개체 이름: hitomi_downloader_GUI.exe_old
MD5: 

트로이목마가 심어져 있을거라고는 당연히 생각하지 않습니다. 지금까지도 아무렇지 않게 사용해왔으니까요. 혹시 exe_old파일이 프로그램 구동에 필수적인 것인지가 궁금합니다. 또한 exe_old에 실질적으로 문제가 있는 것인지 확인 부탁드립니다.

**Comment by hwnnhji** [comment]
old파일 계속 문제있다고 뜨길래 zip파일로 받아서 넣었습니다만, 구동엔 아무런 문제 없는 거 보면 그냥 이대로 쓰면 되겠거니 싶기는 합니다만, 혹시 싶어서 질문 드립니다.

**Comment by KurtBestor** [comment]
업데이트할 때 기존 실행 파일을 `tmp_update/hitomi_downloader_GUI.exe_old` 로 옮겨두고 업데이트 된 실행 파일을 원래 실행파일에 옮겨놓고 실행하는데 그 과정에서 오진이 나는 것 같네요. 기존에 쓰던 버전이 뭔가요?

**Comment by teatralatinae** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/6053

여기 올라와있던 zip파일 그대로 풀어 사용 중이었습니다.

**Comment by hwnnhji** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/6053

여기 올라와있던 zip파일 풀어서 사용 중이었습니다.
