### ISSUE TITLE
MAX_COUNT 상수 수정내역 고정

### ISSUE THREAD

**Issue by hny2798** [KurtBestor/Hitomi-Downloader#6091]
새로키고 매번 검색할때마다 MAX_COUNT =1000 치는거 귀찮은데 혹시 수정값  고정 안될까요

**Comment by KurtBestor** [comment]
[이걸](https://github.com/KurtBestor/Hitomi-Downloader/releases/download/Utils/change_MAX_COUNT.hds) 플러그인에 넣으세요

**Comment by hny2798** [comment]
덕분에 잘 쓰고 있습니다
