### ISSUE TITLE
Request headers for Hitomi Downloader

### ISSUE THREAD

**Issue by comdigi** [KurtBestor/Hitomi-Downloader#6108]
[Run translator]
How should I set request headers for Hitomi Downloader?
If the option is not there, please add it in the next version.

**Comment by comdigi** [comment]
> You mean HTTP headers?
맞아요
ffmpeg라는 프로그램 같은경우는 -headers 'Origin: http://www.xxxx.xxx' 이런식으로 옵션을 주면 되는데
히토미는 요청 헤더값을 넣을 방법이 없는것 같네요

**Comment by KurtBestor** [comment]
헤더를 넣어야할 경우가 있나요?

**Comment by comdigi** [comment]
> 헤더를 넣어야할 경우가 있나요?

네 있어요
