### ISSUE TITLE
HTTP API 관련

### ISSUE THREAD

**Issue by STR-HK** [KurtBestor/Hitomi-Downloader#6165]
현재 HTTP API를 활성화할 경우 WebUI나 엔드포인트를 이용해 작업을 추가하거나 삭제할 수 있는데, 외부와 포트가 연결된 환경(DMZ 등)의 경우 보안상으로 취약해 보여서 혹시 추가 / 삭제 / 열람 기능별로 권한 설정이 가능하도록 하거나 스크립트로 조작할 수 있는 방안을 마련해 주실 수 있을까요?

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/5668

**Comment by STR-HK** [comment]
프로그램 패스워드와 연동되는거 확인했습니다. 감사합니디ㅏ.
