### ISSUE TITLE
English help file still has Korean text and images in Korean

### ISSUE THREAD

**Issue by Blueberryy** [KurtBestor/Hitomi-Downloader#6211]
https://github.com/KurtBestor/Hitomi-Downloader/blob/1de0682bc45e954f4cbd711e44974b3db3a9ec48/translation/help_en.html#L112

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/commit/4dda65781d71b924a281a7e9f6121d98e9d4efd0

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/commit/b803266985e9718ef82298eaf942f8c959b9c7f8

**Comment by Blueberryy** [comment]
Thank you for updating translation files.
