### ISSUE TITLE
When I want to move the location of a saved folder, is there a way to change the folder path all at once?

### ISSUE THREAD

**Issue by Rsfinder** [KurtBestor/Hitomi-Downloader#6218]
Hitomi has always help me. Thank you.
This is a minor request (or question). Is there a good way to change folder paths all together?

ex.
E:Folder A/Folder B
↓↓
D:Folder A'/Folder B'

I want to move them to another drive, is there any other way but to change them one by one? 
If you have any other suggestions, please let me know.
If not, I'd like you to implement a new one... Well, it's not something I need right now, so I'd be glad if you would consider it.

I liked the new ver. Please let me continue to support you!

**Comment by KurtBestor** [comment]
If folders are relative to the executable, see: https://github.com/KurtBestor/Hitomi-Downloader/issues/6126#issuecomment-1621367933
Otherwise, you can use a SQLite editor, such as https://github.com/KurtBestor/Hitomi-Downloader/issues/5867

**Comment by Ikkoru** [comment]
Is it possible to use something like Notepad++ instead of an SQLite editor?
