### ISSUE TITLE
Download from "nhentai" times out

### ISSUE THREAD

**Issue by tatuta630** [KurtBestor/Hitomi-Downloader#6224]
A timeout occurs when downloading from "nhentai" and the download fails.
How to attach the log.

Invalid: [nhentai] https://nhentai.net/g/340747/

version: 3.8e (23-07-28 02:47:14 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ja_jp
order / group / uid: 66 / False / 8630949cb37b44f2a2ea64d368393a5d
input: https://nhentai.net/g/340747/
type: nhentai
single: False
url: https://nhentai.net/g/340747/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1690466108.383183 (23-07-27 13:55:08 UTC) - 89168s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...
wait clf...

stop
Traceback (most recent call last):
 File "utils", line 1339, in start
 File "extractor\nhentai_downloader", line 26, in init
 File "clf2", line 168, in solve
clf2.Timeout

Invalid: fail=True
EOT: https://nhentai.net/g/340747/  (293.6s)

**Comment by KurtBestor** [comment]
Can you visit the nhentai using the built-in browser? It's in `Options - Preferences - Network - Built-in web browser - View`

**Comment by tatuta630** [comment]
When you display "nhentai" in the built-in browser, the CAPCHA authentication screen is displayed and the download starts when you pass the authentication!
Thanks for letting me know how to fix it.
