### ISSUE TITLE
How to download youtube video covers rather than thumbnails

### ISSUE THREAD

**Issue by codiy1992** [KurtBestor/Hitomi-Downloader#6244]
I found there is a plugin which can download Youtube thumbnails when the main process was done!
But I can't find't a way to download full cover image, 
Is there any way or plugin that I can use for cover downloading?

**Comment by codiy1992** [comment]
```
#coding: utf8
#title: Save YouTube thumbnails after task is finished
#author: Kurt Bestor

from utils import Hook
import os


@Hook.task_finished('save_thumb')
def hook_rename(cw):
    if cw.type != 'youtube' or not cw.valid:
        return
    fn = os.path.splitext(cw.names[0])[0]+'.png'
    with open(fn, 'wb') as f:
        f.write(cw.str_pixmap)
    cw.setNameAt(len(cw.names), fn)


messageBox('Hooked!')

```
code shown above is from an existing plugin called 'hook_save_thumb.hds',  It's obviously that the `cw.str_pixmap` hold the data stream of thumbnail, I want to know, Is cover infomation accessble via cw.xxxx ?

**Comment by rickmiron** [comment]
Modify the plugin to display a higher resolution thumbnail:

    #coding: utf8
    #title: Save YouTube thumbnails after task is finished
    #author: Kurt Bestor
    
    from utils import Hook
    import os
    import requests
    
    @Hook.task_finished('save_thumb')
    def hook_rename(cw):
        if cw.type != 'youtube' or not cw.valid:
            return
        fn = os.path.splitext(cw.names[0])[0] + '.jpg'
        iid = fn[fn.rfind('(') + 1:-5]
        iex = '2' if 'orts/' in cw.url else 'default'
        response = requests.get(f"https://i.ytimg.com/vi/{iid}/maxres{iex}.jpg")
        if response.status_code == 404:
            response = requests.get(f"https://i.ytimg.com/vi/{iid}/hq{iex}.jpg")
        with open(fn, 'wb') as f:
            if response.status_code < 400:
                f.write(response.content)
            else:
                f.write(cw.str_pixmap)
        cw.setNameAt(len(cw.names), fn)

**Comment by codiy1992** [comment]
> Modify the plugin to download a higher resolution thumbnail:
> 
> ```
> #coding: utf8
> #title: Save YouTube thumbnails after task is finished
> #author: Kurt Bestor
> 
> from utils import Hook
> import os
> import requests
> 
> @Hook.task_finished('save_thumb')
> def hook_rename(cw):
>     if cw.type != 'youtube' or not cw.valid:
>         return
>     fn = os.path.splitext(cw.names[0])[0] + '.jpg'
>     iid = fn[fn.rfind('(') + 1:-5]
>     iex = '2' if 'orts/' in cw.url else 'default'
>     response = requests.get(f"https://i.ytimg.com/vi/{iid}/maxres{iex}.jpg")
>     if response.status_code == 404:
>         response = requests.get(f"https://i.ytimg.com/vi/{iid}/hq{iex}.jpg")
>     with open(fn, 'wb') as f:
>         if response.status_code < 400:
>             f.write(response.content)
>         else:
>             f.write(cw.str_pixmap)
>     cw.setNameAt(len(cw.names), fn)
> ```

It works, very thanks!
