### ISSUE TITLE
Add "Twitter", "Torrent" and keyboard shortcuts to translation file

### ISSUE THREAD

**Issue by Blueberryy** [KurtBestor/Hitomi-Downloader#6253]
I know not many languages has Twitter translated but in Russian version it's transliterated so i want to change it if it will be in translation file.
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/36592509/fd03d887-3de0-4142-89c7-246e8cff9aea)

UPD; also it would be amazing if you can add some keyboard shortcut names to translation file like "SPACE"

**Comment by KurtBestor** [comment]
See: https://github.com/KurtBestor/Hitomi-Downloader/commit/b266ace57c0496d326ab256c6cf1c332242bd46e

**Comment by Blueberryy** [comment]
> See: https://github.com/KurtBestor/Hitomi-Downloader/commit/b266ace57c0496d326ab256c6cf1c332242bd46e

Thanks! I hope shortcuts will be added next
