### ISSUE TITLE
xhamster 크리에이터 다운로드

### ISSUE THREAD

**Issue by samsugo** [KurtBestor/Hitomi-Downloader#6257]
크리에이터 링크
https://ko.xhamster2.com/creators/***/exclusive
일반유저링크
https://ko.xhamster2.com/users/***/videos

크리에이터도 다운로드 가능 하도록 개선은 불가능한가요?

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
