### ISSUE TITLE
mp4파일에 유튜브 동영상 썸네일 추가 관련 질문

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6273]
모든 사이트에서 다운로드하는 모든 파일이 다 그렇지는 않겠지만, 다운로더를 통해 유튜브에서 음원파일을 다운로드 할 시, 다운로드 된 mp3 파일엔 당연히 그 mp3파일 자체에 그 mp3의 동영상 썸네일이 추가 되더라구요. 애초에 노래 파일은 소리 중심이니, 그를 상징할 대표적인 시각정보가 필요하기도 하고, 그래서 음반 커버가 중요하기도 하고, 그에 따라 mp3파일에는 자연스럽게 그 앨범 아트가 자연스럽게 삽입되는 형태로 발전했다고 생각합니다.

유튜브 동영상 같은 경우에도 이와 마찬가지로 단순히 동영상으로만 소비되는 것이 아니라 그 동영상을 상징하는 썸네일로써 어그로를 끌기도 하고 동영상에 더욱 큰 재미를 줄 수 있다고 생각합니다. 
또한 단순히 이 다운로더를 통해 동영상을 다운받을 때도, 단순히 '동영상'을 다운받는단 느낌보단 거기서 얻을 수 있는 재미나, 정보 등의 다양한 다른 것들도 포함하여 동영상을 다운받아, 오랜 기간 내지는 내 수중에 두기 위해서 이 다운로더를 사용하는 사람이 저 말고도 꽤 있을 거라 생각하기도 하구요.

그래서 요청드립니다만, 혹시 mp4파일 자체에 그 동영상의 유튜브 썸네일을, 그 다운받는 동영상 파일의 대표 썸네일로 다운로드 되게 해주실 수는 없으십니까? 

그나마 단일 동영상만 다운로드 하면 다운로더에 썸네일 기록이 남기에 그 기억을 되짚어볼 수 있습니다만, 하나의 채널을 전부 다운로드 해버리면 가장 처음 다운받는 동영상의 썸네일만 다운로더에 남기에 동영상이 유튜브에서 삭제되는 경우라던가는 썸네일을 찾아볼 수도 없게 되어버립니다. 물론 다운로더를 정말 다운로드만 하게 사용하는 사람도 많다고 생각하구요.

정리하자면, mp3의 앨범아트가 mp3파일 자체에 적용되듯이, mp4파일도 동영상을 볼 때의 기억을 남기기 위해서라도 유튜브 썸네일을 mp4파일 자체에 대표 썸네일로서 적용시켜주실 수 없으신지 여쭙니다.

**Comment by Hot-IcedTea** [comment]
저기 실례지만...
유튜브 동영상 말고 컴퓨터 안에 저장된 동영상 확인할 때
썸네일 보여지던가요??
