### ISSUE TITLE
xhamster 다운로드 불가 및 채널 다운로드 건의

### ISSUE THREAD

**Issue by samsugo** [KurtBestor/Hitomi-Downloader#6312]
요청 링크
https://ko.xhamster2.com/channels/(채널명)
+현재
https://ko.xhamster2.com/creators/(크리에이터 명)/exclusive(탭)(필수X)
https://ko.xhamster2.com/users/(크리에이터 명)/videos(탭)(필수X)

오류내역
-------------------------------------------------------------
Invalid: [xhamster] https://ko.xhamster2.com/videos/000

version: 3.8e+ (23-08-23 02:00:38 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 1111 / False / 7c7ddf38804a4f5ea4bf42e4faa38d7c
input: https://ko.xhamster2.com/videos/000
type: xhamster
single: True
url: https://ko.xhamster2.com/videos/000
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1693417217.1377866 (23-08-30 17:40:17 UTC) - 83s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: {'chunk': 524288, 'n_threads': 4, 'overwrite': False}
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: False

[File Names]

[URLs]

[Messages]
'videoModel'
stop
Traceback (most recent call last):
 File "utils", line 1358, in start
 File "utils", line 1437, in start_
 File "extractor\xhamster_downloader", line 55, in read
 File "utils", line 858, in __call__
 File "decorator", line 232, in fun
 File "constants", line 929, in try_
 File "constants", line 898, in try_
 File "extractor\xhamster_downloader", line 73, in get
 File "extractor\xhamster_downloader", line 111, in get_info
KeyError: 'videoModel'

Invalid: fail=True
EOT: https://ko.xhamster2.com/videos/000  (1.7s)

다운로드 불가인 이유는 사이트 구조 변경인지 잘 모르겠습니다. 쿠키도 업데이트했지만…. 수고 많으십니다.

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/6318
