### ISSUE TITLE
네이버 카페 다운로드 기능이 작동하지 않습니다

### ISSUE THREAD

**Issue by hoon050824** [KurtBestor/Hitomi-Downloader#6358]
네이버 카페 다운로드 기능이 정상적으로 작동하지 못하는 듯 합니다
아래는 오류 로그 입니다

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/46698298/107fa3d8-47bf-464e-b1bc-4ba8e86ac20b)

`Invalid: [navercafe] https://cafe.naver.com/looksamfancafe/79241

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 7 / False / 68facacb29c94125bdb107c4a46c02dc
input: https://cafe.naver.com/looksamfancafe/79241
type: navercafe
single: False
url: https://cafe.naver.com/looksamfancafe/79241
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1695077687.0379899 (23-09-18 22:54:47 UTC) - 16154s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
https://cafe.naver.com/ArticleRead.nhn?articleid=79241&clubid=30189661
https://cafe.naver.com/ArticleRead.nhn?articleid=79241&clubid=30189661
https://cafe.naver.com/ArticleRead.nhn?articleid=79241&clubid=30189661
https://cafe.naver.com/ArticleRead.nhn?articleid=79241&clubid=30189661
'article'
stop
Traceback (most recent call last):
 File "utils", line 1354, in start
 File "utils", line 1433, in start_
 File "extractor\navercafe_downloader", line 18, in read
 File "decorator", line 232, in fun
 File "constants", line 928, in try_
 File "constants", line 897, in try_
 File "extractor\navercafe_downloader", line 44, in get_info
KeyError: 'article'

Invalid: fail=True
EOT: https://cafe.naver.com/looksamfancafe/79241  (6.2s)
`

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hoon050824** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

쿠키가 적용되지 않는 것 같습니다

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/46698298/7642be2d-63a9-417c-8e5d-aafb8012b19b)

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/46698298/85dd3fc4-bc7a-40f7-b6a3-66ef2d4dcd8f)

`Login required; Please login
https://cafe.naver.com/looksamfancafe/79214

version: 3.8e+ (23-09-20 02:08:58 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / ko_kr
order / group / uid: 0 / False / c9245d65952e475c9bb411ede3855f65
input: https://cafe.naver.com/looksamfancafe/79214
type: navercafe
single: False
url: https://cafe.naver.com/looksamfancafe/79214
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1695179218.8599095 (23-09-20 03:06:58 UTC) - 106s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.07.06
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]

stop
Traceback (most recent call last):
 File "utils", line 1359, in start
 File "utils", line 1438, in start_
 File "extractor\navercafe_downloader", line 22, in read
 File "decorator", line 232, in fun
 File "constants", line 874, in try_
 File "constants", line 872, in try_
 File "extractor\navercafe_downloader", line 38, in get_info
extractor.navercafe_downloader.LoginRequired

Invalid: fail=False
EOT: https://cafe.naver.com/looksamfancafe/79214  (1.1s)`

**Comment by KurtBestor** [comment]
만료된 쿠키인 것 같네요

**Comment by hoon050824** [comment]
> 만료된 쿠키인 것 같네요

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/46698298/bcd718d4-5621-460e-9ea7-3287fe0826ac)

쿠키 갱신 후에도 같은 문제가 반복되어 일단 내부 브라우저로 로그인하고 시도했습니다
정상 작동 확인되었습니다. 감사합니다.
