### ISSUE TITLE
필터된 목록 선택 시에 버그

### ISSUE THREAD

**Issue by SevenArks** [KurtBestor/Hitomi-Downloader#6377]
필터된 목록에서 여러 개를 선택하여 삭제하려고,
하단에서 클릭 후에 Home 버튼을 누르면 필터된 항목 외에 것도 선택됩니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by SevenArks** [comment]
제가 확인했던 문제가 없어졌습니다.
