### ISSUE TITLE
Stucked at waiting with any download

### ISSUE THREAD

**Issue by Emagelle** [KurtBestor/Hitomi-Downloader#6389]
I've tried downloading youtube, hitomi, instagram, but none of them works, and logs doesn't tell much. It just stucked at waiting. Tried multiple version, but no luck. I had a working 3.8e last month. I think something has messed up after win11 updates.
proxy setup working, and internal browser working.

等待... https://hitomi.la/doujinshi/kouryaku-shippai-2-%E4%B8%AD%E6%96%87-389849-2126134.html#1

version: 3.8e (23-07-25 02:44:56 UTC)
platform / locale: Windows-10-10.0.22000-SP0 / zh_cn
order / group / uid: -378 / False / 8d83a012fbb24600bba75bfe49266f64
input: https://hitomi.la/doujinshi/kouryaku-shippai-2-%E4%B8%AD%E6%96%87-389849-2126134.html#1
type: hitomi
single: True
url: https://hitomi.la/doujinshi/kouryaku-shippai-2-%E4%B8%AD%E6%96%87-389849-2126134.html#1
dir: 
zip: 
artist: None
valid / done: True / False
range / range_p: None / None
time: 1695695135.497961 (23-09-26 02:25:35 UTC) - 1102s elapsed
tags: []
lock: False
color: wait
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.06.22
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/49598414/b3484bdc-6a6f-46a5-b815-c1e3bc17a45f)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/49598414/826cabf2-09ad-47e7-806d-f731479d52f8)

**Comment by 826065523** [comment]
open clash option: allow LAN

**Comment by Emagelle** [comment]
I've tried to toggle "allow LAN" on or off; the problem remains.

**Comment by KurtBestor** [comment]
What about after turning "绕过 DPI" off?

**Comment by Emagelle** [comment]
I did try to turn it on or off, but it didn't help. Though after I uninstall/install KB5030217 and KB5031042, it seems to work now.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/49598414/eb0898e6-87a0-4abb-8a5b-54b74f262999)
