### ISSUE TITLE
갑자기 실행파일이 사라지고 새로 받아서 실행하면 액세스가 거부되었다며 다시 실행파일이 사라져요

### ISSUE THREAD

**Issue by 10pointstogryffindor** [KurtBestor/Hitomi-Downloader#6436]
며칠전에 다운로드중 강제종료가 되고 그냥 잊어먹고 살다가 오늘 폴더에 들어가보니까 exe 파일이 사라져 있었어요
그래서 다시 다운로드를 받아서 원래 쓰던 폴더에다가 실행파일을 옮기는데 몇번 권한이 없다면서 거부하다가 어찌어찌 넣고 실행하니까 다시 실행파일이 사라지고 아예 경로도 다른 새폴더에서 zip 파일 풀고 실행해봐도 에러가 나더니 실행파일이 사라져요

https://imgur.com/a/01XJnIr

실행이라도 되면 모르겠는데 그냥 바로 에러창뜨고 사라지니까 로그같은것도 안남고 그나마 건진게 이겁니다
대체 무슨 원인일까요

**Comment by rickmiron** [comment]
바이러스 백신을 확인하세요
