### ISSUE TITLE
업데이트 후 다운로드 중인 작업이 있을 때 프로그램 종료 후 다시 프로그램을 켜면 실행 안되는 현상

### ISSUE THREAD

**Issue by byeoriabba** [KurtBestor/Hitomi-Downloader#6465]
제가 작업 개수가 1294개 입니다 

hitomi_downloader_GUI.ini 용량도 800mb가 넘습니다

이번 업데이트 후 다운로드 중인 작업이 있을 때 프로그램 종료 후 다시 프로그램을 켜면 실행 안되는 현상이 일어 납니다 

3.8e 버전으로 열면 무리없이 열립니다 

3.8f 버전에서는 그러나 다운 중이던 작업이 있을 때 프로그램을 종료 한 후 다시 프로그램을 실행하면 실행이 되다가 갑자기 종료 되어 버립니다 

물론 다운로드가 전부 완료 된 후에는 무리 없이 열립니다 

작은 hitomi_downloader_GUI.ini로 확인하면 무리없이 열리긴 합니다

감사합니다

**Comment by KurtBestor** [comment]
해당 설정 파일 (hitomi_downloader_GUI.ini) 보내주시면 분석해볼게요

**Comment by byeoriabba** [comment]
> 해당 설정 파일 (hitomi_downloader_GUI.ini) 보내주시면 분석해볼게요

메일로 보내었습니다

**Comment by KurtBestor** [comment]
어디로 보내셨나요? 안 보여요

**Comment by byeoriabba** [comment]
아 메일로 답변이 오길래 거기로 답장으로 보냈네요 어디로 보내드리면 될까요?

**Comment by KurtBestor** [comment]
그냥 여기에 드래그 & 드롭해서 올려주시거나 디코 DM 으로 보내주시면 돼요

**Comment by byeoriabba** [comment]
https://we.tl/t-Y3k2o0XDLH
용량이 너무 크다고 올라가지 않아서 이렇게 보냅니다

**Comment by KurtBestor** [comment]
다음과 같이 cmd에서 실행해서 생기는 `debug.txt` 보내주실 수 있나요?
```
hitomi_downloader_GUI.exe --debug
```

**Comment by byeoriabba** [comment]
[debug.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/12911413/debug.txt)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by byeoriabba** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

잘 되네요 감사합니다
