### ISSUE TITLE
每个版本都无法下载视频

### ISSUE THREAD

**Issue by r2bec3a** [KurtBestor/Hitomi-Downloader#6469]
3.8f之前的版本提示【AttributeError: type object 'YoutubeDL' has no attribute '_setup_opener'】
3.8f版本提示【[warning] Deprecated Feature: 5upport for Python version 3.7 has been deprecated. See htps//github.com/yt-dlp/yt-dlp/issues/7803 for You may stop receiving updates on this version at any time! Please update to Python 3.8 or above】
测试了【bilibili.com】【pornhub.com】【youtube.com】，都无法下载，请问是什么原因呢，谢谢
![001](https://github.com/KurtBestor/Hitomi-Downloader/assets/147575673/d6cd1160-d782-434d-ac82-d6bfc42de64b)
![002](https://github.com/KurtBestor/Hitomi-Downloader/assets/147575673/85b2cb2b-d2ab-42e0-bfa4-85413a5aa800)

**Comment by 179798071** [comment]
同样的问题啊老哥，怎么解决

**Comment by Aprilday** [comment]
升级了 Python 版本也没用。

**Comment by r2bec3a** [comment]
测试版完美解决了

**Comment by Aprilday** [comment]
> 测试版完美解决了

哪个测试版？求教！

**Comment by r2bec3a** [comment]
> > 测试版完美解决了
> 
> 哪个测试版？求教！

已经解决的问题里面，关于ph站下载的那个

**Comment by Aprilday** [comment]
> > > 测试版完美解决了
> > 
> > 
> > 哪个测试版？求教！
> 
> 已经解决的问题里面，关于ph站下载的那个

找到了，感谢，哥们挺重口呀^^!

**Comment by r2bec3a** [comment]
> > > > 测试版完美解决了
> > > 
> > > 
> > > 哪个测试版？求教！
> > 
> > 
> > 已经解决的问题里面，关于ph站下载的那个
> 
> 找到了，感谢，哥们挺重口呀^^!

哈哈哈

**Comment by 179798071** [comment]
> > > > > 测试版完美解决了
> > > > 
> > > > 
> > > > 哪个测试版？求教！
> > > 
> > > 
> > > 已经解决的问题里面，关于ph站下载的那个
> > 
> > 
> > 找到了，感谢，哥们挺重口呀^^!
> 
> 哈哈哈

测试版这个下载过来要怎么安装啊

**Comment by HenrySun1010** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/6529#issuecomment-1790345850 对于3.8f，这个好像也可以解决

> > Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
> > You can ignore those yt-dlp warnings
> 
> Finally figure it out, yt-dlp wont work with https proxy anymore, and I set proxy to socks5://xxx.xxx.xxx.xxx, works well, thank you anyway, the great developer.
> 
> BTW, the dpi issue is fixed, THX.
