### ISSUE TITLE
Doubt about the resquest module

### ISSUE THREAD

**Issue by rickmiron** [KurtBestor/Hitomi-Downloader#6515]
Is the **resquest** module different in hitomi downloader?
on my pc using **response.status_code** I get 200 and in hitomi downloader I get 403 when using:
import requests
heade = {'User-Agent': 'test'}
response = requests.head(url, headers=heade)

**Comment by KurtBestor** [comment]
No, it's the same as the original [Requests](https://github.com/psf/requests) module.

requests==2.26.0
urllib3==1.25.11

**Comment by rickmiron** [comment]
Do you have an alternative function for this code?

    url = 'https://rule34video.com/get_file/16/2718abe172f7249f3079e75d6a1f24a5620362b6db/3143000/3143533/3143533_720p.mp4/?br=2518&rnd=1698533434073'
    response = requests.head(file,headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'})
    print(response.status_code) #The correct thing is 302 and 403 if the headers fail
    print(response.headers)


works 1 out of 4 times

    downloader.real_url(url, session=session())

**Comment by KurtBestor** [comment]
That's strange, it seems to behave differently depending on the Python version. I got the following results:
| Version | Status code |
|:-- | :--: |
|Python 3.7|403|
|Python 3.8|403|
|Python 3.9|403|
|Python 3.10|302|
|Python 3.11|302|
|Python 3.12|302|

**Comment by rickmiron** [comment]
Will you update the python version? 
Optionally I made this function for hitomi downloader that uses python 3.11 on my pc

    def pythonexter(url):
        comans = [
            "python",
            "import requests",
            f"u = '{url}'",
            "r = requests.head(u,headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'})",
            "if r.status_code == 302:",
            "   print(r.headers['Location'])",
            "elif r.status_code < 300:",
            "   print(u)",
            "exit()"
        ]
        proceso = subprocess.Popen(["cmd"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
        for line in comans:
            proceso.stdin.write((line + "\n").encode("utf-8"))
        proceso.stdin.close()
        output, _ = proceso.communicate()
        output = output.decode("utf-8", errors="ignore")
        return output.splitlines()[-3]
