### ISSUE TITLE
최근 검색기에 Image set가 나옵니다.

### ISSUE THREAD

**Issue by guest0034** [KurtBestor/Hitomi-Downloader#6534]
검색기 타입에 gamecg manga doujinshi artistcg anime 만 있으니 제외가 안되네요
뭘 검색하든 imageset가 같이 나오는데 imageset 업로드 수가 엄청 많으니 다른게 제대로 보이질 않네요
설정에 제외태그 사용해봤지만 Type들은 제외가 안되구요
제가 뭔가 설정을 잘못만진걸까요

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by guest0034** [comment]
정상작동 합니다. 감사합니다.
