### ISSUE TITLE
Bug: program continues to run after exiting

### ISSUE THREAD

**Issue by TheGhost78** [KurtBestor/Hitomi-Downloader#6535]
After right-clicking on the tray icon and selecting **Quit (Q)**, Hitomi Downloader continues to run, as can be seen in Task Manager.

![Hitomi Downloader Task](https://github.com/KurtBestor/Hitomi-Downloader/assets/97525552/504166fd-ece4-483c-b28b-c741083af6d8)

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by TheGhost78** [comment]
Great, that works - thanks!
