### ISSUE TITLE
폴더 이동 기능 오류 발생

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6562]
https://twitter.com/lunamoth/status/1687394066131234816
위 트위터 링크를 다운받은 후 이를 타 폴더로 옮기기 위해 f2에서 폴더 이동을 시도했습니다.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/40f44aa3-ca44-405d-98ac-5d0b34edb8f3)
위와 같은 오류가 발생합니다. hitomi_downloaded_twitter 폴더에서 hitomi_downloaded_computerscience 폴더로 파일을 옮기려 했습니다.

오류 내용을 보면 지정된 경로를 찾을 수 없다는 식으로 뜨는데

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/bb75d9c6-8de5-4c1b-a28c-b40e406435c9)

지정된 경로에 제대로 있음을 확인하였습니다. 

무엇이 문제인지 확인 부탁드리겠습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
감사합니다.
