### ISSUE TITLE
Question about self.enableSegment()

### ISSUE THREAD

**Issue by rickmiron** [KurtBestor/Hitomi-Downloader#6567]
Is it possible to activate self.enableSegment() for some files yes and other files no?

**Comment by KurtBestor** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/blob/7e68b3cb39935f2d73628e50f9a5bd7e1aeeca10/src/extractor/coub_downloader.py#L28-L46

This is equivalent to:

```python
 def read(self): 
         video = Video(self.url, cw=self.cw) 
         video.url()# 
  
         self.urls.append(video.url) 
         self.setIcon(video.thumb) 
  
         self.title = video.title 
  
  
  
 class Video: 
     _url = None 
  
     def __init__(self, url, cw=None): 
         self.url = LazyUrl(url, self.get, self, pp=self.pp) 
         self.cw = cw
         self.segment = True
```

Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rickmiron** [comment]
Thanks, the segment itself worked.
One last question.
if self.enable Segment() is equal to self.segment = True
So what does self.enableSegment(n_threads=8) equal?

**Comment by KurtBestor** [comment]
```python
self.segment = {'chunk': 2**20, 'n_threads': 8, 'overwrite': False}
```

**Comment by rickmiron** [comment]
Thanks, the segment worked.
