### ISSUE TITLE
기능 건의

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6570]
현재의 코멘트 기능은 약간만 길이가 길어져도 화면에서 확인이 불가능하니 정말 간단한 메모용도로 보입니다.
조금 더 긴 메모를 추가할 수 있도록 기능을 건의드려도 되겠습니까?

가령
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/335a71fa-bd10-4609-a28f-00da5f94c195)
현재의 f2 창은 오른쪽의, default size로 보면 27줄 정도 들어가는 목록을 통해 해당 프로젝트가 다운받은 목록을 설정하능한 것으로 보입니다.
이 부분의 하단의 창을 분할하여 코멘트를 확인하고 수정할 수 있게 해주실 수 있으십니까?

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/94a2211b-e358-40d2-9765-a29caf347cda)
이와 비슷한 느낌으로 창을 분할해놓고, 필요하다면 한쪽의 창을 더 늘리거나 하는 식으로 코멘트를 수정할 수 있으면 좋을 거라고 생각힙니다.
이 방법으론 f2 탭에서 대부분의 분들이 사용하지 않을 거라고 예상되는 list 부분을 조금 더 활용 가능할 것으로 생각됩니다.

단순히 제 의견이고, 좀 더 긴 코멘트도 직관적으로 확인이 가능했으면 할 뿐이라 개발자님 나름 이와 관련된 기능만 추가 해주신다면 감사드리겠습니다.

**Comment by KurtBestor** [comment]
코멘트 여러 줄 가능하게 수정했어요
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
감사합니다
