### ISSUE TITLE
유튜브 다운로드 화질 추가 관련 질문

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6586]
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/862defae-4494-4d1e-bc27-1581c5f4d01e)

유튜브 프리미엄을 쓰면 1080p premium이란 화질이 추가됩니다. 아무래도 육안으로만 봤을 땐 좀 더 부드러워지는 것 같은데 아마 사진에 적힌 그대로 비트 전송의 간격을 줄이는 게 아닐까 싶습니다.

현재 유튜브를 다운로드 하면 최대 8K로 설정해놓아도 1080이 최대면 당연히 1080으로 다운받아지는 것으로 보입니다. 혹시 1080 premium이 있다면 이것으로 다운받아질 수 있도록 추가해주실 수 있으십니까?

**Comment by keroberos-s** [comment]
이거 저도 예전에 문의 해봤는데 쓰루 당한거보면 안되나봐요...

**Comment by KurtBestor** [comment]
참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/6350

**Comment by hwnnhji** [comment]
미리 찾아보고 올린 건데, 사진으로 올라와있어 못찾았는듯 하네요. 감사합니다.
