### ISSUE TITLE
[질문] 사이트 다운로드 스크립트를 만들거나 수정 후  적용방법

### ISSUE THREAD

**Issue by korhentai** [KurtBestor/Hitomi-Downloader#6587]
1. py 로 작성후 빌드 새로 안하고 임포트만 해도 되나요 기존에 있는 경우에는 어떻게 하나요 ? 
(_4chan_downloader.py 를 수정하여 작성했다 치면 새로 빌드 안하고 임포트만 해도 되는지요?)

**Comment by KurtBestor** [comment]
빌드가 무엇을 의미하나요?

**Comment by korhentai** [comment]
git 허브에 있는 소스코드 로 빌드 하는거요 ?

**Comment by korhentai** [comment]
어쨌든 그럼 원래있는 소스 코드 수정해서 임포트 해도 상관없는건가요 ?

**Comment by KurtBestor** [comment]
네
