### ISSUE TITLE
Pixiv stopped working

### ISSUE THREAD

**Issue by xZabuzax** [KurtBestor/Hitomi-Downloader#6603]
Hello, **https://www.pixiv.net** is not working anymore, it hasn't worked for a couple of days, if possible, may you please resolve this issue?

Thanks!

**Comment by TheConfusedlol** [comment]
same

**Comment by suzukioha** [comment]
> Hello, **https://www.pixiv.net** is not working anymore, it hasn't worked for a couple of days, if possible, may you please resolve this issue?
> 
> Thanks!

TRY 
#6593 

https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by xZabuzax** [comment]
> > Hello, **https://www.pixiv.net** is not working anymore, it hasn't worked for a couple of days, if possible, may you please resolve this issue?
> > Thanks!
> 
> TRY #6593
> 
> https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

Thank you, this one works, however, the Cookies are not saved, I need to load the Cookies manually every time I open the program for it to work. Hopefully, this issue can be resolved as well =)

**Comment by Asylum0** [comment]
https://github.com/KurtBestor/Hitomi-Downloader/issues/6607#issuecomment-1835413489

Try.
I solved with this.

**Comment by xZabuzax** [comment]
Thank you, the issue is fixed with the latest version so I will close this thread =)
