### ISSUE TITLE
Downloading only missing files?

### ISSUE THREAD

**Issue by AutumnalFox** [KurtBestor/Hitomi-Downloader#6609]
Let's say I download a Pixiv profile and then after a month passes I want to download the new files this Pixiv artist uploaded since my last download, is there a way to tell the downloader to not download again the already existing files in my gallery so it only downloads the new ones that are missing?
Sorry if the program already does this and I'm too stupid to notice.

**Comment by koushitw** [comment]
It's substantial!

**Comment by AutumnalFox** [comment]
Sorry, but I don't understand what you mean.

**Comment by rickmiron** [comment]
The program reads all the URLs that are going to be downloaded and assigns a name to each file. If the file already exists, it is not downloaded.

**Comment by AutumnalFox** [comment]
I see now, thank you :)
