### ISSUE TITLE
업데이트 후 카쿠요무 다운 불가 kakuyomu

### ISSUE THREAD

**Issue by ppg13** [KurtBestor/Hitomi-Downloader#6620]
2023년 11월 07일 기준으론 잘 되었습니다.
오늘 다시 해보니 안되는데 다운로더 업데이트 후 문제가 생겼거나, 카쿠요무 소설 목차 페이지의 디자인이 바뀐게 관련있는건가 싶습니다.

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055463848325

version: 3.8f (23-10-05 11:50:20 UTC)
platform / locale: Windows-10-10.0.19041-SP0 / ko_kr
order / group / uid: 0 / False / 3a5534e91b9141eea612fb56dfb36eed
input: https://kakuyomu.jp/works/1177354055463848325
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055463848325
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1701150763.9595764 (23-11-28 05:52:43 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'NoneType' object has no attribute 'text'
stop
Traceback (most recent call last):
 File "utils", line 1352, in start
 File "extractor\kakuyomu_downloader", line 38, in init
 File "extractor\kakuyomu_downloader", line 98, in get_info
AttributeError: 'NoneType' object has no attribute 'text'

Invalid: fail=True
quality: 75%
EOT: https://kakuyomu.jp/works/1177354055463848325  (1.5s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ppg13** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

10개를 테스트 해봤는데 처음 드렸던 링크 포함 3개는 됩니다만 나머지 7개는 안됩니다.

=테스트 되는 것
https://kakuyomu.jp/works/1177354055463848325 <처음 질문할때 시도했던 링크
https://kakuyomu.jp/works/1177354055230498225
https://kakuyomu.jp/works/16817330654192579465


=테스트 안되는 것 테스트 링크 모음
https://kakuyomu.jp/works/1177354055504974517
https://kakuyomu.jp/works/16816700426129496803
https://kakuyomu.jp/works/16817139558069889100
https://kakuyomu.jp/works/16817330659885128990
https://kakuyomu.jp/works/16817330661875567537
https://kakuyomu.jp/works/16816700427571912894
https://kakuyomu.jp/works/16817139556071887300

=안되는 것 작업정보 7가지
----------1번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055504974517

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 6 / False / 15ffce6e591b456eb03ef5bf5d5a57df
input: https://kakuyomu.jp/works/1177354055504974517
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055504974517
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702014908.5834856 (23-12-08 05:55:08 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055504974517  (2.5s)

'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055504974517  (2.1s)

----------2번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16816700426129496803

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 5 / False / 6e4872035d43409189320a9f1d65fe36
input: https://kakuyomu.jp/works/16816700426129496803
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16816700426129496803
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702014774.9261186 (23-12-08 05:52:54 UTC) - 156s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: False


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16816700426129496803  (2.9s)

----------3번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817139558069889100

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 3 / False / c3fd88ea568f4e708e9243214fa41e2b
input: https://kakuyomu.jp/works/16817139558069889100
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817139558069889100
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702014774.9436083 (23-12-08 05:52:54 UTC) - 188s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817139558069889100  (1.4s)

----------4번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817330659885128990

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / 8d3d54186c684cd6b0321ac8168aa83f
input: https://kakuyomu.jp/works/16817330659885128990
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817330659885128990
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702014774.9556127 (23-12-08 05:52:54 UTC) - 202s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817330659885128990  (1.2s)

----------5번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817330661875567537

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / fc6c6783baa64c2b811dfe638f85a0ca
input: https://kakuyomu.jp/works/16817330661875567537
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817330661875567537
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702014774.9616184 (23-12-08 05:52:54 UTC) - 243s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817330661875567537  (1.2s)

----------6번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16816700427571912894

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / cd0e6ae20d394b8298063f0ce776c005
input: https://kakuyomu.jp/works/16816700427571912894
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16816700427571912894
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702015373.6622255 (23-12-08 06:02:53 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16816700427571912894  (1.4s)

----------7번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817139556071887300

version: 4.0+ (23-12-07 13:53:26 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 868ad1908c9e43bb981b2e5873b0c165
input: https://kakuyomu.jp/works/16817139556071887300
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817139556071887300
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702015373.677239 (23-12-08 06:02:53 UTC) - 36s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'TableOfContentsChapter:'
stop
Traceback (most recent call last):
 File "utils", line 1360, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 111, in get_info
KeyError: 'TableOfContentsChapter:'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817139556071887300  (1.9s)


여러가지 처리하시고 계실텐데 수고 많으십니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ppg13** [comment]
제가 7개 더 추가해서 테스트 해봤는데 잘 됩니다. 감사합니다!
나중에 소설 관련 사이트 중에 뭔가 문제가 생기면 죄송하지만 다시 문의 드리겠습니다!!
크리스마스 잘 보내세요!!!

**Comment by ppg13** [comment]
안녕하세요! 전에 카쿠요무 관련으로 문의 드렸었는데 전에 링크 주셨던 테스트 프로그램으로 다시 해보니 또 막히네요.
디자인이 또 바뀌었는지 모르겠지만 부탁드립니다...!

----------1번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055504974517

version: 4.0+ (23-12-16 15:00:40 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 9 / False / 6b80e0b294464f208d542b3b6b846777
input: https://kakuyomu.jp/works/1177354055504974517
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055504974517
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702825947.6965158 (23-12-17 15:12:27 UTC) - 127s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055504974517  (2.3s)

----------2번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16816700426129496803

version: 4.0+ (23-12-16 15:00:40 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 8 / False / 1faed247d6054716bb1ef947f7c60fe8
input: https://kakuyomu.jp/works/16816700426129496803
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16816700426129496803
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702825947.7085266 (23-12-17 15:12:27 UTC) - 189s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16816700426129496803  (1.6s)

----------3번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055463848325

version: 4.0+ (23-12-16 15:00:40 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 4b406895403f4c3d81956efea362dafd
input: https://kakuyomu.jp/works/1177354055463848325
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055463848325
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702826361.3275087 (23-12-17 15:19:21 UTC) - 62s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055463848325  (0.9s)

----------4번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817330654192579465

version: 4.0+ (23-12-16 15:00:40 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 7e0fe424d7604c16ac8792bc13ef2ad8
input: https://kakuyomu.jp/works/16817330654192579465
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817330654192579465
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702826488.666121 (23-12-17 15:21:28 UTC) - 2s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817330654192579465  (0.8s)

연말이라 바쁘실텐데 죄송합니다...
