### ISSUE TITLE
Is there any way to add uid (User ID) to Twitter filenames?

### ISSUE THREAD

**Issue by Rsfinder** [KurtBestor/Hitomi-Downloader#6624]
I use it all the time. Thanks so much for providing us with a great tool.
I noticed (recently) that I can change the format of Twitter filenames.

- date (%Y %m %d)
- id
- ppage
- @username

I know these can be used, but can 'uid' or date (HH:mm:ss) be added?

If there is no way to add them, I would really appreciate it if you could implement them.
I tried with hook but it didn't work...

I am hoping to be able to make the following file name. Anyway, it would be great if we could add uid...!
(id=uid id) yyyymmdd HHMMSS (page)

Also, I'll be supporting you on Patreon starting in December.
Thanks to Hitomi Downloader, I was able to save valuable works in 2023.
I will support you again next year as much as I can😌🙏

**Comment by finalxcode** [comment]
@Rsfinder do you know how to install project dependent? i can't find a doc

**Comment by Rsfinder** [comment]
@finalxcode
Sorry, I'm not an English speaker so I don't know the exact meaning of 'install project dependent', 
but if you mean 'hook', I tried the following URL.
https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins#hooks

But I'm not familiar with scripting, so I couldn't implement a solution to this Issue.

**Comment by finalxcode** [comment]
@Rsfinder i try to run this project locally, but i don't know how to run this project, maybe you can give me some steps

**Comment by Rsfinder** [comment]
@finalxcode 
Options→Preferences→plugins→+→Import

＋:(Import Script) －:(Delete Script)

Edit the Script yourself if necessary.
I'm not a programmer, so I cannot explain about scripts.
https://github.com/KurtBestor/Hitomi-Downloader/wiki/How-to-write-a-script

**Comment by finalxcode** [comment]
@finalxcode thanks, i will try myself

**Comment by finalxcode** [comment]
@Rsfinder  thanks, i will try myself

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by rickmiron** [comment]
KurtBestor posts the Twitter plugin so that he can make his modifications

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Rsfinder** [comment]
@KurtBestor 
Thaaaaaaasaaanks!!!🙏🙏🙏🙏🤝👍👍 I have nothing more to say
I should have told you all together first. my apologies.

Today is my internet anniversary. 
I'm off to save the artists' works before Elon Musk destroy Twitter.


Everyone should use this syntax. Super useful.

Twitter：`(ID=uid id)  date:%Y%m%d; date:%H%M%S; (page:+1;) `

**Comment by Rsfinder** [comment]
@KurtBestor 
Um, sorry......
If you could... I'd be happy if you could...
it would be great if you could add a spec to not put a page on a single image/mp4....

ex. twitter.com/NASA/status/1729938953699033278

> (ID=uid id)  date:%Y%m%d; date:%H%M%S; (page:+1;) **←add xxxx**
↓
>✖  (ID=11348282 1729938953699033278)  20231130 040241 **(1)**.jpg 
>◎ (ID=11348282 1729938953699033278)  20231130 040241.jpg 

I don't mind having a page on sequentially numbered images...but I'd prefer not to have a page on a single file.
(I'm fine with the way it is now if the post is a set of video and images)

I don't know what the script is to get that format...but it would be nice if you could.
And I don't have any other requests. I will support you with Patreon tomorrow. 

I'm really sorry...🙇‍♂️😢(and the implementation doesn't have to be right now

**Comment by KurtBestor** [comment]
You could do that by using the [hook](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins#hooks)

**Comment by Rsfinder** [comment]
@KurtBestor ok, I will try.
Thank you for being so selfish with me🙇‍♂️

**Comment by Rsfinder** [comment]
@rickmiron 
> KurtBestor posts the Twitter plugin so that he can make his modifications

Sorry for the late reply.
You mean Hitomi Downloader has a Twitter plugin? 

Sorry if I'm misunderstanding the nuance.
but if you mean I can use the plugin, I'd appreciate it if you could give me the details.
