### ISSUE TITLE
사이트 추가가 안 되는 문제.

### ISSUE THREAD

**Issue by supersweetsh** [KurtBestor/Hitomi-Downloader#6642]
4.0 업데이트 이후 다운로드 추가가 안 됩니다. 
특별한 메시지는 안 나옵니다.
exe파일 받아서 새로운 폴더에서 시작해도 마찮가지 입니다.
로그 파일 등도 생성 안 되서 올리지도 못하네요.
동영상 캡쳐하여 첨부합니다. 

https://youtube.com/shorts/qeRM6f3Gn5s?feature=share

**Comment by KurtBestor** [comment]
다음과 같이 cmd에서 실행하고 해당 동작 시도한 후에 생기는 `debug.txt` 보내주실 수 있나요?
```
hitomi_downloader_GUI.exe --debug
```

**Comment by supersweetsh** [comment]
@KurtBestor 
안녕하세요. 요청하신 debut.txt 첨부드립니다.

[debug.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/13546725/debug.txt)

설정 -> 일반 -> 유튜브 저장 폴더 확인하였을 때 기본 값이었고 폴더 만들고 지정하여도 동일한 증상입니다.

감사합니다.

**Comment by KurtBestor** [comment]
이건 어떤가요?: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by supersweetsh** [comment]
@KurtBestor 
정상 작동 확인하였습니다.
빠른 조치 감사합니다.
