### ISSUE TITLE
듀얼 모니터 사용 시, 메뉴가 다른 모니터에 갇히는 문제

### ISSUE THREAD

**Issue by Ooooool** [KurtBestor/Hitomi-Downloader#6666]
항상 업데이트하느라 고생 많으십니다. 최근 v4.0 업데이트 후부터 듀얼 모니터 사용 시, 작업 / 도구 / 옵션 / 도움말을 눌렀을 때 밑에 생기는 하위메뉴들이 1번 모니터에 갇히는 증상이 발생합니다. 베타 버전의 경우도 동일한 증상이 생기며, 구버전인 v3.8f에서는 발생하지 않습니다.

![메뉴 버그](https://github.com/KurtBestor/Hitomi-Downloader/assets/35823330/d5b103a6-c421-44ce-97c2-18407ffbf13a)

제 경우 좌측 모니터가 2번이고 우측 모니터가 1번이라 지금처럼 오른쪽에 하위메뉴들이 갇혀버리네요.

**Comment by Ooooool** [comment]
감사합니다.

**Comment by arong7895** [comment]
이거 어떻게 해결하나요?
