### ISSUE TITLE
이헨/익헨 info파일 정보 누락

### ISSUE THREAD

**Issue by unowenenigma** [KurtBestor/Hitomi-Downloader#6669]
이헨/익헨에서 받을 때 other 태그들은 info.txt에서 누락되는 것 같습니다. ex)ai generated, uncensored, groups, etc...

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by unowenenigma** [comment]
잘 작동 됩니다. 감사합니다.
