### ISSUE TITLE
하드웨어 가속기능 문의

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6672]
항상 감사합니다 개발자님.

프로그램을 에전부터 사용하면서 전부 너무 좋았지만 하나 아쉬운게 렉이 자주 걸리는 것이었습니다.
다운로드를 하거나, 히토미 검색을 하거나 하면서 cpu를 너무 많이 잡아 먹기에, 다른 프로그램에 영향이 가지는 않지만, 프로그램 자체가 렉을 먹는다는 것이 문제라고 생각합니다.

### 렉 걸리는 목록
1. 히토미 찾기 기능 사용 시
2. 다운로드 작업 시
3. (다운로드된 작업이 꽤 많은 상황에서) 스크롤을 빠르게 내릴 시에 작업 로딩 속도가 스크롤 속도를 따라오지 못하고 5초 정도 기다려야 로딩되는 경우가 있음.

제가 해당 프로그램을 분석해본 것도 아니고 어떻게 구체적으로 작동되는 것인지는 모르지만 작업의 일부분에서 하드웨어 가속 기능을 활용할 수 있을 것으로 생각합니다.

따라서 조금이라도 렉을 줄이고자, 혹시 프로그램에 gpu를 이용한 하드웨어 가속 기능을 추가해주실 수 있으신지 여쭙니다.

**Comment by KurtBestor** [comment]
1. 검색기에서 렉이 걸리는 이유는 크게 두 가지예요:
    1. QWidgetItem이 많아지면 생기는 [Qt](https://www.qt.io) 문제
    2. WebP 파일을 읽을 때 생기는 [Pillow](https://github.com/python-pillow/Pillow) 문제 (아마 GIL 때문)
2. [Requests](https://github.com/psf/requests) ([urllib3](https://github.com/urllib3/urllib3)) 라이브러리에서 생기는 렉 (아마 GIL 때문)
    [urllib](https://docs.python.org/3/library/urllib.html), QNetworkRequest 등에서는 발생하지 않음
3. 프로그램 시작 시간과 메모리를 절약하기 위해 필요할 때마다 작업의 썸네일을 읽는데, 멀티스레딩을 하면 읽기 속도가 느려지므로 조금 느리더라도 메인 스레드에서 동작하도록 만들었어요
    시작 시 모두 읽으려면 여기를 참고하세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/3613

GPU 가속은 병렬 작업에서 성능 향상을 기대할 수 있는 기술이지만 위의 문제에는 적용되지 않아요

**Comment by hwnnhji** [comment]
넵 감사합니다.
