### ISSUE TITLE
완료 작업 자동 잠금 기능 및 아이콘 위치 문의

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6676]
## 잠금 기능 / 아이콘 위치 관련 문의

항상 감사드립니다. 프로그램을 사용하면서 있었음 하는 기능이 있어 문의드립니다.

### 잠금 기능 관련
설정에서 다운로드 완료 후 자동 제거 기능은 있습니다만, 자동으로 잠궈 삭제하거나 다시시작을 방지하는 기능은 안보여서요. 자동 잠금 기능 만들어 주실 수 있으십니까?
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/e2388eb9-c7b8-4444-8106-443d610d3299)

#### 작업은 pin하거나 lock할 시에 너무 상대적으로 너무 큰 아이콘이 왼쪽 상단에 박혀 작업 썸네일의 가시성 저하가 발생합니다.
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/69b44e1c-c181-463f-9229-1e8b77ed1195)

따라서 아래와 같은 방안을 제시합니다.

1. 우측 하단
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/2191ff1b-5c67-48a6-b4ba-6ca158359630)

2. 우측 상단 (이 경우는 폴더 열기, 파일 삭제 등의 위치가 있으니 그 옆에 아이콘을 붙여 작업 위에 마우스를 올릴 시에 나타나도록 하는 편이 UI가 훨신 깔끔할 것으로 생각됩니다. 내지는 가장 오른쪽 끝에 붙여 항상 나타낼 수도 있을 것으로 보입니다.)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/ef703b7a-1555-464b-8b69-22c88966da81)
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/ba7fed3c-ee8e-4412-b2a2-a7127c3e68d1)

#### 다만
위와 같은 2가지 경우엔 배경이 회색으로 있어 직사각형으로 보이는 아이콘을 사용하는 것이 아닌, 배경 없이 상대적으로 반투명한 아이콘을 사용하는 것이 좋아 보입니다. 
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/5fb366dd-f625-4340-a01b-20860efa843e)
현재 사용되고 있는 아이콘들과 마찬가지로요.

선처하여주시면 감사하겠습니다.

**Comment by KurtBestor** [comment]
아이콘을 다른 곳으로 옮기는 건 부적절한 것 같고, 조금 더 가장자리로 옮겨서 썸네일이 잘 보이게 했어요

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
용량이 갑자기 늘었네요. 더 많은 기능이 생기고 있는 거 같아 왠지 기쁩니다.
감사합니다.
