### ISSUE TITLE
Is it possible to add a channel ID (channel URL or custom URL) in the YouTube Supported Token?

### ISSUE THREAD

**Issue by Rsfinder** [KurtBestor/Hitomi-Downloader#6688]
Sorry for sending so many similar requests every time.
Right now it supports abr~widt, but I propose to implement Channel URL(ID) or Custom URL to it.

Example https://www.youtube.com/@NintendoAmerica
> Channel URL=UCGIY_O-8vW4rfX98KlMkvRg
> Custom URL=@NintendoAmerica

Channel URL is well... it is necessary for me
but Custom URL would be useful.

It would be like username in Twitter.

I suggested this because I don't think Hooks can handle it, but please let me know if this can already be done.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

New tokens have been added: `channel_id`, `uploader_id`

**Comment by Rsfinder** [comment]
Thanks!! I've been waiting for this😂
i tried it immediately, but it seems to cause an error that the file name is incorrect when the download is completed
it was named according to the two new tokens until the download was complete, so there may be another problem

Whatever the token is, it will have the following name
ex. https://www.youtube.com/channel/UCWIezv87lOLKzNcxHCaKGBg

```
tmp080fccd2ce8f455fb2ea6acea9aa89c2_a.weba
tmp080fccd2ce8f455fb2ea6acea9aa89c2_v.mp4
tmp459f10dad9684440a262a5a61e48a26c_a.weba
tmp459f10dad9684440a262a5a61e48a26c_v.mp4
tmp468b55f3d055492587cd1db141d43c15_a.weba
tmp2a33bfb4745944409e968a623f9905dc_a.weba
```

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
