### ISSUE TITLE
트위터에서 동영상을 받을 시 깨지는 현상

### ISSUE THREAD

**Issue by SoulDeskPhone** [KurtBestor/Hitomi-Downloader#6689]
안녕하세요,
프로그램을 만들어 주신 덕분에 유용하게 사용 중입니다. 그런데, 트위터에서 동영상을 받을 경우, 깨진 동영상을 받는 경우가 생깁니다. 이 현상은
1. 삭제 후 다시 받아도 동일하게 깨져있고
2. 다른 디바이스에서 받으면 괜찮습니다,

그러한 파일 중 하나의 작업 로그는 아래와 같습니다:
Yちゃん (@___Ycancan)

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / en_us
order / group / uid: 0 / False / 0ceb565bc4bf445a85d8b434cca0b890
input: https://twitter.com/___Ycancan/status/1733817392860631176
type: twitter
single: True
url: https://twitter.com/___Ycancan/status/1733817392860631176
dir: hitomi_downloaded_twitter
zip: 
artist: Yちゃん
valid / done: True / True
range / range_p: None / None
time: 1702664697.2942936 (23-12-15 18:24:57 UTC) - 18s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {uids: ['1573249164917362689']}
live: False
changed: True

[File Names]
[0001] hitomi_downloaded_twitter\Yちゃん (@___Ycancan)\[23-12-10] 1733817392860631176_p0.mp4

[URLs]
[0001] File_twitter(https://twitter.com/___Ycancan/status/1733817392860631176/video/1)    --->    https://video.twimg.com/amplify_video/1733817318097195009/vid/avc1/720x960/0WMTWCqpXGF5iQE_.mp4?tag=14

[Messages]
format: None
type: single
call... TweetDetail
rid: 1733817392860631176
uid: 1573249164917362689
single tweet
call... TweetDetail
rid: 1733817392860631176
-show_streams -print_format json -v error "[23-12-10] 1733817392860631176_p0.mp4"
-ss 1.39 -noaccurate_seek -i "[23-12-10] 1733817392860631176_p0.mp4" -frames:v 1 "C:\Users\jwpark\AppData\Local\Temp\tmp1c5e4f37a652452192ac0c048675c9b7_o.png"
【ffmpeg】 load...
【ffmpeg】 loaded
[out]
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '[23-12-10] 1733817392860631176_p0.mp4': 
 Metadata: 
   major_brand     : iso5 
   minor_version   : 512 
   compatible_brands: iso6mp41 
 Duration: 00:00:06.99, start: 0.000000, bitrate: 918 kb/s 
 Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 720x960, 794 kb/s, SAR 1:1 DAR 3:4, 30 fps, 30 tbr, 60k tbn (default) 
   Metadata: 
     handler_name    : Twitter-vork muxer 
     vendor_id       : [0][0][0][0] 
 Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default) 
   Metadata: 
     handler_name    : Twitter-vork muxer 
     vendor_id       : [0][0][0][0] 
Stream mapping: 
 Stream #0:0 -> #0:0 (h264 (native) -> png (native)) 
Press [q] to stop, [?] for help 
Output #0, image2, to 'C:\Users\jwpark\AppData\Local\Temp\tmp1c5e4f37a652452192ac0c048675c9b7_o.png': 
 Metadata: 
   major_brand     : iso5 
   minor_version   : 512 
   compatible_brands: iso6mp41 
   encoder         : Lavf60.3.100 
 Stream #0:0(und): Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 720x960 [SAR 1:1 DAR 3:4], q=2-31, 200 kb/s, 30 fps, 30 tbn (default) 
   Metadata: 
     handler_name    : Twitter-vork muxer 
     vendor_id       : [0][0][0][0] 
     encoder         : Lavc60.3.100 png 
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A     [image2 @ 0000027a61344b00] The specified filename 'C:\Users\jwpark\AppData\Local\Temp\tmp1c5e4f37a652452192ac0c048675c9b7_o.png' does not contain an image sequence pattern or a pattern is invalid. 
[image2 @ 0000027a61344b00] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image. 
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A dup=0 drop=37 speed=   0x     
video:958kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown 
[code]
0
stop
EOT: https://twitter.com/___Ycancan/status/1733817392860631176  (9.9s)

해당 문제의 해결이 가능할까요?

동영상 플레이어는 vlc media player 사용중입니다.

**Comment by KurtBestor** [comment]
다른 미디어 플레이에서도 동일한가요?

**Comment by KurtBestor** [comment]
다른 미디어 플레이어에서도 동일한가요?

**Comment by SoulDeskPhone** [comment]
네, 윈도우의 media player 와 movies & tv 로 실행을 하여도 동일합니다.

**Comment by KurtBestor** [comment]
해당 파일 보내주시면 분석해볼게요

**Comment by SoulDeskPhone** [comment]
discord DM 으로 보내드렸습니다
