### ISSUE TITLE
2주전 카쿠요무 다운불가 문의 및 해결 후 다시 다운 불가 kakuyomu

### ISSUE THREAD

**Issue by ppg13** [KurtBestor/Hitomi-Downloader#6708]
안녕하세요! 약 2주전에 카쿠요무 관련으로 문의 드렸었는데 그때 해결해 주시면서 링크를 주셨던 테스트 프로그램으로 12월 17일에 다운 시도를 했으나 실패하였습니다.
시도한 링크는 2주전과 똑같은 10개였으나 다 안되었고 그 중에서 4가지를 가져왔습니다.
테스트 프로그램 버전 문제인가 싶어서 12월 18일자 테스트 프로그램으로 오늘 다시 해봤습니다.
그래도 실패하면서 작업 정보 마지막 부분이 똑같이 뜨는데 올 연말 해당 사이트 페이지를 리뉴얼 하면서 버그 수정을 또 한 것 같습니다. 혹시나 해서 같은 소설 사이트인 [小説家になろう](https://syosetu.com/)도 봤으나 문제는 없었습니다.

연말이라 바쁘실텐데 죄송하고 부디 부탁드리겠습니다..!

시도한 링크:
https://kakuyomu.jp/works/1177354055504974517
https://kakuyomu.jp/works/16816700426129496803
https://kakuyomu.jp/works/1177354055463848325
https://kakuyomu.jp/works/16817330654192579465

----------1번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055504974517

version: 4.0+ (23-12-18 14:46:45 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 3 / False / 4e09e05646394f1fb497c5b2e3b14dc2
input: https://kakuyomu.jp/works/1177354055504974517
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055504974517
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702915463.2116036 (23-12-18 16:04:23 UTC) - 63s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055504974517  (2.8s)

----------2번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16816700426129496803

version: 4.0+ (23-12-18 14:46:45 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 2 / False / 181e6aa6957a482291ad7735cd35acfc
input: https://kakuyomu.jp/works/16816700426129496803
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16816700426129496803
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702915483.910921 (23-12-18 16:04:43 UTC) - 63s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16816700426129496803  (1.6s)

----------3번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/1177354055463848325

version: 4.0+ (23-12-18 14:46:45 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 1 / False / acf00a4d1d89460cadf868056224bc68
input: https://kakuyomu.jp/works/1177354055463848325
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/1177354055463848325
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702915489.2316427 (23-12-18 16:04:49 UTC) - 70s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/1177354055463848325  (1.1s)

----------4번째----------

Invalid: [kakuyomu] https://kakuyomu.jp/works/16817330654192579465

version: 4.0+ (23-12-18 14:46:45 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / f340cac9cd624fdfbd94fac150bd0836
input: https://kakuyomu.jp/works/16817330654192579465
type: kakuyomu
single: False
url: https://kakuyomu.jp/works/16817330654192579465
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1702915498.0369885 (23-12-18 16:04:58 UTC) - 74s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
'episodes'
stop
Traceback (most recent call last):
 File "utils", line 1361, in start
 File "extractor\kakuyomu_downloader", line 37, in init
 File "extractor\kakuyomu_downloader", line 112, in get_info
KeyError: 'episodes'

Invalid: fail=True
EOT: https://kakuyomu.jp/works/16817330654192579465  (0.7s)

소설 일괄 다운 프로그램이 없어서 항상 감사하고 있습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by ppg13** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview
넵 다운로드 시작 잘 됩니다! 다른 것들로 시도해봐도 에러 안뜨고 시작 잘되네요.
이후 소설 사이트에 뭔가 문제가 생기면 다시 연락드리겠습니다! 감사합니다.
