### ISSUE TITLE
산카쿠에서 다운로드할 수 없습니다

### ISSUE THREAD

**Issue by hyt3570** [KurtBestor/Hitomi-Downloader#6728]
Invalid: [sankaku] https://chan.sankakucomplex.com/?tags=algerie_%28azur_lane%29

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: -17 / False / b902b148dacc441a8027f47199a664d7
input: https://chan.sankakucomplex.com/?tags=algerie_%28azur_lane%29
type: sankaku
single: False
url: https://chan.sankakucomplex.com/?tags=algerie_%28azur_lane%29
dir: 
zip: 
artist: None
valid / done: False / False
range / range_p: None / None
time: 1703348237.0534027 (23-12-23 16:17:17 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/?tags=algerie_%28azur_lane%29
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True

2~3일전부터 산카쿠에서 다운로드를 시도하면 오류가 생겨서 재설치나 쿠키 업데이트 등을 해보았지만 해결되지 않았습니다

**Comment by rickmiron** [comment]
plugin: https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

**Comment by hyt3570** [comment]
> plugin: https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

It works Thanks!
