### ISSUE TITLE
파일 다중 선택 시 '해당 링크로 이동합니다' 기능도 다중으로 됐으면 좋겠습니다.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#6732]
유튜브를 다운로드해서 동영상 플레이어로 보고

유튜브 영상은 광고 나오게 크롬으로 띄워두는데요.

현재는 아이콘 눌러서 하나씩 띄우다 보니 아쉬운 마음에 글 남겨봅니다.

메리 크리스마스 🎄✨

**Comment by KurtBestor** [comment]
[여기](https://github.com/KurtBestor/Hitomi-Downloader/wiki/Scripts-&-Plugins#tool-plugins) 에서 **Open multiple task links** 플러그인 다운로드해서 넣어주세요

`도구 - 선택되 작업 링크 열기` 로 실행할 수 있어요

**Comment by DBdeepsleeper** [comment]
설정 - 플러그인에 추가하면 되네요.

딱 제가 원하던 기능이네요.

고맙습니다.
