### ISSUE TITLE
hitomi artist 다운 기능

### ISSUE THREAD

**Issue by Zinki06** [KurtBestor/Hitomi-Downloader#6757]
.

**Comment by rickmiron** [comment]
Plugin: https://github.com/rickmiron/variado/blob/main/hitomiartist.py

**Comment by Zinki06** [comment]
정말 감사합니다! 어떻게 이렇게 빠르게 하신지 정말 신기하네요
혹시 다음과 같은 식으로 태그를 단 링크에 있는 작품들을 다운받을 수 있게 해줄 수도 있을까요?
https://hitomi.la/search.html?korean%20artist%3Apochi.

**Comment by rickmiron** [comment]
https://hitomi.la/artist/kidmo-korean.html
예, 검색이 아닌 한 가능합니다.

https://hitomi.la/tag/female%3Aangel-all.html
추천하지는 않습니다. 거의 3000개 항목이지만 시도해 보세요.

**Comment by Zinki06** [comment]
어라.. 처음꺼 링크를 어제 넣었을 때는 안돼서 여쭤본거였는데 지금은 또 되네요..? 감사합니다!!
