### ISSUE TITLE
성능 개선 관련 질문

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#6766]
안녕하십니까 개발자님. 좋은 프로그램 풀어주셔서 항상 감사드립니다.

설정(f2) - 네트워크 탭에서 최대 동시 작업을 선택할 수 있는 것으로 보입니다. 저는 최대인 16으로 설정하고 사용중입니다.
제가 프로그램을 사용하면서 느낀 것이, 하나의 사이트는 최대 4개의 동시 작업만이 가능한 것으로 보인다는 것입니다.

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/74286087/93d368c9-3fa2-48c5-b180-02ba84b69c20)
가령 위처럼 마나토끼 사이트를 다운받는다고 할 때, 읽고, 다운로드 하는 것은 어떤 경우에도 최대 4개의 작업만 동시에 작동되는 것으로 보입니다.

다른 사이트까지 이런식으로 작동하는지는 모르겠으나, 혹시 이런식으로 작동하는 이유가 있는 것인지, 딱히 특정한 이유가 없다면 이것을 늘릴 수도 있는 것인지 여쭙니다.

**Comment by KurtBestor** [comment]
각 사이트에는 과도한 트래픽으로 인한 차단 혹은 봇 감지를 방지하기 위해 기본 최대 동시 작업 수가 제한되어 있어요
대부분의 사이트는 최대 4개, yt-dlp 지원 사이트는 8개, 일부 사이트는 최대 1개이고 Torrent 는 제한이 없어요
설정의 "최대 동시 작업" 수를 올려도 해당 기본 최대 동시 작업 수보다 높게 적용되지는 않아요

**Comment by hwnnhji** [comment]
그런 이유가 있었네요,, 감사합니다.
