### ISSUE TITLE
How do i login my sankaku account?

### ISSUE THREAD

**Issue by Plegmatis** [KurtBestor/Hitomi-Downloader#6796]
there's a lot of "sankaku logo" images downloaded when i download by tags.
my best guess is i need to login my account because it always opened when i logged in
the question is how do i login my account on hitomi? i tried to edit the pyton file pluggin but i dont know where to edit it

additional info: already added the cookie

**Comment by Plegmatis** [comment]
> Options -->Preferences --> Network --> Cookies --> Load...

hi, ty for the answer, I already did that but still has "logo" images downloaded, the images loaded fine in my browser(chrome) or hitomi built-in browser

**Comment by rickmiron** [comment]
post a test url

**Comment by Plegmatis** [comment]
https://chan.sankakucomplex.com/en/?tags=partemis
all images opened up for me in browser

**Comment by rickmiron** [comment]
Ttry this plugin:
https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

**Comment by Plegmatis** [comment]
it works now, thank you very much
