### ISSUE TITLE
로컬 파일로 부터 새 작업 만들기 / 폴더 기능이 작동하지 않습니다

### ISSUE THREAD

**Issue by testcatme** [KurtBestor/Hitomi-Downloader#6804]
![11](https://github.com/KurtBestor/Hitomi-Downloader/assets/157008665/8456864b-a1ba-47c3-a0d1-1b4fa91d161e)

이런 오류가 뜨면서 작동 되지 않습니다.
파일 기능은 창이 열리지만 폴더기능은 작동하지 않고 있습니다

버전은 최신 버전입니다.

**Comment by suzukioha** [comment]
test preview 버전으로 해보시면 됩니다
