### ISSUE TITLE
Sankaku "Logo" images downloaded instead the actual images

### ISSUE THREAD

**Issue by Plegmatis** [KurtBestor/Hitomi-Downloader#6807]
Hello, based on my previous issue [#6796](https://github.com/KurtBestor/Hitomi-Downloader/issues/6796), the problem still persist with the downloaded "logo" images

- I'm using Hitomi beta (13 Jan 2024) 
- using plugin https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py
- loaded cookies (using txt file, because import directly from chrome gives me "err" error)

I tried to downloading this site https://chan.sankakucomplex.com/en/?tags=partemis
it gives me 3 out of 151 "sankaku logos" 
when i tried my next download list https://chan.sankakucomplex.com/en/?tags=alios_arvin
it gives me almost half of it (the tag has 167 images on it)
which is weird because all tags opened fine for me from my browser (Chrome)

**Comment by rickmiron** [comment]
Shows task info

**Comment by Plegmatis** [comment]
[Task.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/13999150/Task.txt)

**Comment by rickmiron** [comment]
I made new changes, try it:
https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

**Comment by Plegmatis** [comment]
> I made new changes, try it: https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

it still downloading lot of "logo" but i think it improving because the logo usually at the 26th image, now 30th
thank you for the reply
[Task.txt](https://github.com/KurtBestor/Hitomi-Downloader/files/14008226/Task.txt)

**Comment by rickmiron** [comment]
Delete the folder E:\Pictures\Hitomi\Sankaku\[chan]alios_arvin, try it again and send me the task information

**Comment by Plegmatis** [comment]
it works now, thank you!
