### ISSUE TITLE
md5 hash db, how to not download files?

### ISSUE THREAD

**Issue by kifchan** [KurtBestor/Hitomi-Downloader#6855]
Is this possible? I want to download only files that have not been downloaded before. For example, I downloaded an entire youtube channel, deleted the videos from folder and only want to download new videos that will appear in the future

**Comment by KurtBestor** [comment]
This is not feasible because it is impossible to know the MD5 hash of a file without downloading it. Instead, restarting the task by pressing `Right-click - Restart (S)' will not re-download files once they have been downloaded

**Comment by KurtBestor** [comment]
This is not feasible because it is impossible to know the MD5 hash of a file without downloading it. Instead, restarting the task by pressing `Right-click - Restart (S)` will not re-download files once they have been downloaded

**Comment by kifchan** [comment]
Thank you for answer, i just want feature like here https://github.com/Bionus/imgbrd-grabber
for auto-downloading every hour new pictures from https://danbooru.donmai.us/posts?page=1&tags=animal_ears
then i watch files, delete them all and waiting for new
i dont know how it works, but even if files downloads before check md5 this is fine >_<
![Screenshot 2024-02-13 133935](https://github.com/KurtBestor/Hitomi-Downloader/assets/34883354/751e49e3-f012-412f-a7cd-92890b3914b7)
