### ISSUE TITLE
sankaku complex invalid 오류(다운 시작이 안됨)

### ISSUE THREAD

**Issue by krocksname** [KurtBestor/Hitomi-Downloader#6856]
혼자 해결하려고 시도해봤는데 번번히 실패했습니다 사이트 질문 사항들을 다 읽어보았어도 답이 안나오네요

1. 산카쿠 로그인 된 쿠키 중에서 export / export all cookies 둘 중에서 뭐로 쿠키로 넣을지 감이 안잡혔습니다. 일단 all cookies를 넣어도 보고 그냥 export 를 넣어봐도 똑같이 다운 자체가 안됩니다. (invalid 가 떠요)

Invalid: [sankaku] https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 3d58dcf61f154c52bb2b27f50f9e8b85
input: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1706765415.8261216 (24-02-01 05:30:15 UTC) - 502s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated  (13.0s)

**Comment by rickmiron** [comment]
plugin:
https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

**Comment by krocksname** [comment]
답변 감사합니다 근데 이렇게 다시 오류가 뜨네요.

downloader.py 실행하고 다시 쿠키 넣고 해도 안됩니다. 어디가 문제인지 모르겠습니다..

Invalid: [sankaku] https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated

version: 4.0 (23-12-02 05:25:00 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 9e58ce5a34804b5d841c3f5ed10c2925
input: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
type: sankaku
single: False
url: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1706942313.4056466 (24-02-03 06:38:33 UTC) - 9s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: True
ytdl: yt_dlp 2023.10.07
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated
'title'
stop
Traceback (most recent call last):
 File "utils", line 1375, in start
 File "utils", line 1454, in start_
 File "extractor\sankaku_downloader", line 146, in read
 File "extractor\sankaku_downloader", line 272, in get_imgs
KeyError: 'title'

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/ko/posts?tags=shiranui_mai+animated  (8.2s)

**Comment by rickmiron** [comment]
글쎄, 오류를 보내는 줄 번호에 따르면 내가 보낸 플러그인에는 해당 줄 번호가 존재하지 않습니다.
플러그인을 다시 추가해 보세요.

**Comment by krocksname** [comment]
아 해결되었습니다 감사합니다
