### ISSUE TITLE
Enhancement: duplicate download currently prevents new downloads

### ISSUE THREAD

**Issue by TheGhost78** [KurtBestor/Hitomi-Downloader#6862]
If you add a link that is already on the list of downloads, the program comes up with a dialogue box that says "The task is already on the list. Do you want to download it again?". This is fine, however until you clear the dialogue box by clicking either 'OK' or 'Cancel', any **new** download links will not be added to the list.

Could this behavious be changed to still allow new downloads to be added and begin downloading, because the dialogue box only applies to that one file and shouldn't prevent/delay downloads where there is no conflict.

**Comment by rickmiron** [comment]
I don't know which version you use but if you copy all the links from a list and paste them, it will analyze everything and ask you once if you want to download the repeated ones again

**Comment by TheGhost78** [comment]
That's not how it is typically going to be used - I'm going to right click on videos and copy the link as and when I find them; occasionally this may result in me copying the same link more than once.

I've tried it with the last few pre-releases: 2024-01-13, 2024-01-09, 2024-01-07, 2024-01-06, 2024-01-04 (two releases on this day).

**Current situation:**
Add link A: added to list of downloads and begins downloading
Add link B: added to list of downloads and begins downloading
Add link A again: dialogue box pops up
Add link C: _not_ added to the list of downloads
Clear diaglog box related to link A being added a second time by clicking OK or Cancel: link C is then added to the list of downloads and begins downloading.

**What I am asking for:**
Add link A: added to list of downloads and begins downloading
Add link B: added to list of downloads and begins downloading
Add link A again: dialogue box pops up
Add link C: added to the list of downloads and begins downloading
Add link D: added to the list of downloads and begins downloading
Add link E: added to the list of downloads and begins downloading
Clear diaglog box related to link A being added a second time by clicking OK or Cancel.

**Comment by TheGhost78** [comment]
Will this be implemented?

**Comment by TheGhost78** [comment]
The way that I am asking for it to work is how it worked in v4.0. However, in subsequent technical previews it has changed to what I described in the 'current situation' above. Can it go back to how it was in v4.0?

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by TheGhost78** [comment]
Thanks, Kurt - that works!
