### ISSUE TITLE
Only download 20 images on some tags in Sankaku

### ISSUE THREAD

**Issue by Plegmatis** [KurtBestor/Hitomi-Downloader#6875]
I tried to download by author like https://chan.sankakucomplex.com/en/?tags=azasuke and https://chan.sankakucomplex.com/en/?tags=odd_%28kisuu%29 but Hitomi only read 20 images and immediately download it even though in Sankaku site they have more than that. 

for another reference I downloaded
- https://chan.sankakucomplex.com/en/?tags=raikageart 940 images
- https://chan.sankakucomplex.com/en/?tags=xtermination 2371 images 
without any problem

**Comment by rickmiron** [comment]
plugin:
https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py
