### ISSUE TITLE
Instagram filename format settings are using Twitter filename settings instead

### ISSUE THREAD

**Issue by Orudeon** [KurtBestor/Hitomi-Downloader#6892]
The Instagram module has been naming things as e.g. `username 24-01-24 093132 (1).jpg` (as in, the word username, not their actual username). My Twitter filename setting is `username date:%y-%m-%d; date:%H%M%S; (page:+1;)` and when I removed the username from it, Instagram downloads started being named e.g. `23-11-09 064919 (1).jpg`.

**Comment by KurtBestor** [comment]
Try this: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by Orudeon** [comment]
That fixed it. That was really fast, thank you!
