### ISSUE TITLE
북마크 내보내기, 가져오기 관련

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#6960]
북마크 내보내기
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/68507771/166e271a-8f5a-4f78-85aa-151cab867b53)
창 이름이 **북마크 가져오기라고 표시**되고 파일 이름 bb 입력 후 저장

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/68507771/6e042221-4c03-4ac0-838b-562e84a00fce)
북마크 내보내기 한 파일 hdfb 확장자 없이 지정한 이름(bb)으로만 파일 생성

북마크 가져오기
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/68507771/bcf0ab09-704e-4b3f-acd9-71e5307ad8a8)

북마크 내보낸 파일인 bb가 보이지 않아 선택할 수 없지만 파일 이름을 입력(bb) 후 열기로 가져오기 가능

단순히 내보내기, 가져오기가 정상 작동하지 않는다는 글을 작성했었는데  글을 수정하여 다시 올립니다.

내보내기, 가져오기 창에서 선택할 수 없지만 작동은 합니다.

읽어주셔서 고맙습니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by DBdeepsleeper** [comment]
테스트 버전에서 내보내기 파일에 확장자가 잘 붙고 가져오기에서 파일 확인이 잘 됩니다.

고맙습니다.
