### ISSUE TITLE
유튜브에서 기본 제목이 아닌 다른 언어로 번역된 제목으로 영상 다운로드

### ISSUE THREAD

**Issue by depth221** [KurtBestor/Hitomi-Downloader#7004]
안녕하세요. 다운로더 잘 쓰고 있습니다.

한국 사람이지만 해외를 주로 타켓하는 유튜버들 중에는 기본값으로 적용되는 제목을 영어로 지어 놓고 한국어 환경에서 보이는 제목을 따로 지정하는 경우가 있습니다. 이런 영상을 히토미 다운로더로 다운로드할 때는 기본 제목을 가져오기 때문에 유튜브 웹사이트에서 한국어로 제목이 보이더라도 영어 제목으로 다운로드하게 되더라고요.
yt-dlp에는 [`--extractor-args lang:(언어 코드)` 인자로 기본 제목이 아닌 다른 언어로 된 제목을 다운로드할 수 있는 옵션](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#extractor-arguments)이 있는데, 이 옵션을 활용해서 영상의 기본 제목이 한국어가 아니더라도 한국어로 번역된 제목이 있으면 그 제목을 가져올 수 있도록 해 주실 수 있으신가요?

https://github.com/yt-dlp/yt-dlp/commit/c26f9b991a0681fd3ea548d535919cec1fbbd430

읽어 주셔서 감사드립니다.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

`옵션 - 설정 - YouTube - 선호 언어` 에서 설정할 수 있어요

**Comment by depth221** [comment]
정상적으로 작동합니다. 감사합니다.

**Comment by depth221** [comment]
@KurtBestor 아까는 못 찾았는데, 선호 언어를 한국어로 설정하고 저장한 다음 프로그램을 껐다 켜면 선호 언어가 English (United Kingdom)로 바뀌는 버그가 있네요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by depth221** [comment]
버그 수정된 거 확인했습니다!
