### ISSUE TITLE
네이버 블로그 다운로드 불가

### ISSUE THREAD

**Issue by hwnnhji** [KurtBestor/Hitomi-Downloader#7062]
https://blog.naver.com/unesco1128/220597495745

해당 링크가 다운로드가 안되네요. 이외에도

https://blog.naver.com/unesco1128/220589453755
https://blog.naver.com/unesco1128/220588613069
https://blog.naver.com/unesco1128/220587357766

이것들도 전부 다운로드가 안됩니다. 브라우저로 접속하면 잘 들어가집니다.

아래에 로그를 첨부해두겠습니다. 감사합니다.

Invalid: [naver] https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745

version: 4.0+ (24-03-25 01:52:36 UTC)
platform / locale: Windows-10-10.0.22631-SP0 / en_us
order / group / uid: 13231 / False / 71893fba07ac4612a1979c8b90049bd9
input: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745
type: naver
single: False
url: https://blog.naver.com/unesco1128/220597495745
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1711381444.0048373 (24-03-25 15:44:04 UTC) - 106s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1392, in start
 File "utils", line 1488, in start_
Exception: empty urls

Invalid: fail=True
stop_live: False
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (0.4s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1392, in start
 File "utils", line 1488, in start_
Exception: empty urls

Invalid: fail=True
stop_live: False
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (0.5s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1392, in start
 File "utils", line 1488, in start_
Exception: empty urls

Invalid: fail=True
stop_live: False
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (0.4s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1392, in start
 File "utils", line 1488, in start_
Exception: empty urls

Invalid: fail=True
stop_live: False
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (0.3s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1392, in start
 File "utils", line 1488, in start_
Exception: empty urls

Invalid: fail=True
stop_live: False
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (0.3s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1491, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (1.4s)

pairs: []
empty urls
stop
Traceback (most recent call last):
 File "utils", line 1396, in start
 File "utils", line 1501, in start_
Exception: empty urls

Invalid: fail=True
EOT: https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=unesco1128&logNo=220597495745  (1.8s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by hwnnhji** [comment]
전부 정상적으로 작동합니다. 감사합니다.

**Comment by kkecall** [comment]
네이버가 주기적으로 관리하는 건가??
베이버 블로그 다운로드가 다시 안 되어 글 남겨봅니다.






Invalid format: https://blog.naver.com/skp1659

version: 4.2 (24-10-27 08:22:47 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / e6a80868747849e0bccf1311d1b4154c
input: https://blog.naver.com/skp1659
type: naver
single: False
url: https://blog.naver.com/skp1659
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1735911925.381489 (25-01-03 13:45:25 UTC) - 3s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 2160
goodbyedpi: True
ytdl: yt_dlp 2024.12.13+
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
Invalid format: https://blog.naver.com/skp1659
stop
Traceback (most recent call last):
 File "utils", line 1387, in start
 File "extractor\naver_downloader", line 34, in init
errors.Invalid: Invalid format: https://blog.naver.com/skp1659

Invalid: fail=False
EOT: https://blog.naver.com/skp1659  (0.0s)
