### ISSUE TITLE
히토미 다운로더내에 작가, 그룹 즐겨찾기 한 것을 살릴 수 있는 방법은 없나요?

### ISSUE THREAD

**Issue by ghkdqofjr1122** [KurtBestor/Hitomi-Downloader#7082]
다운로더 하나에  작가 이름이나 그룹명을 다운로더 ctrl + f 누르면 나오는

탐색기능에 즐겨찾기를 약 1-2년 정도 해놨었는데

ssd가 고장나는 바람에 모든 데이터가 다 사라졌습니다.

이걸 어떻게 살릴 수 있는 방법은 없나요?

히토미다운로더 기능 중에 이미 받은 작품들은 로컬에서 탐색해서 있는 작품들은 스킵하는 기능이 있던데

혹시 하드드라이브에 폴더가 있거나 [작가명] or [그룹명] 이 있는 폴더가 있는경우

로컬을 탐색하여 자동으로 즐겨찾기에 등록되게 해주는 기능은 없나요??

**Comment by KurtBestor** [comment]
`검색기 - 메뉴 - 저장 폴더에 있는 모든 작가 불러오기` 를 써보세요
