### ISSUE TITLE
Add a script into the program

### ISSUE THREAD

**Issue by Nytkuu** [KurtBestor/Hitomi-Downloader#7088]
I've created the following script: [Script Link](https://github.com/Nytkuu/Metadata-to-metadatafiles-Hitomi-Downloader/releases/download/v2/ComicInfo.xml_After_Task_Finished_v12.hds)
The script generates a ComicInfo.xml file in the downloaded task's folder (Hitomi, E-Hentai)

1. I would like to integrate the script into the program, similar to the "Create a gallery info file (info.txt)" feature, and also compress it with the images if the compression option is active.

2. It would be great if you could include the original artist name, group name, and tags in the "cw.gal", like it's on the Hitomi page and not in lowercase as it is now

Can you put the script in the "Scripts & Plugins" section or is it reserved?

**Comment by rickmiron** [comment]
I am ignorant, but in what situations can you use that xml file?

**Comment by Nytkuu** [comment]
It is used for programs that read metadata in that format, such as ComicRack for managing comics, in this case manga, I heard that komga also uses it

**Comment by Nytkuu** [comment]
Sorry, I didn't do a proper investigation, I put the tags in <genre> because I read a comment saying that ComicRack didn't save the tags in .xml, but it does, I'll correct that and ask again later
