### ISSUE TITLE
Sankaku links invalid

### ISSUE THREAD

**Issue by Aniconomics** [KurtBestor/Hitomi-Downloader#7090]
Nothing much to say besides the fact pasting any links from the sankaku website doesn't work. It just says its invalid. I have all the plugins installed, including gallery-dl which is capable of downloading from the sankaku website, admittedly in a limited capacity. I can only download up 369 images using Gallery-dl. I was hoping Hitomi didn't possess this limitation. But I cant seem to download any images despite sankaku being listed as one of the supported sites.

**Comment by Aniconomics** [comment]
Ok. see what your talking about.

nvalid: [sankaku] https://chan.sankakucomplex.com/en/?tags=chiwino

version: 4.1 (24-02-28 04:49:54 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / en_us
order / group / uid: 0 / False / b13416a3b5eb4af597e3f4448918caec
input: https://chan.sankakucomplex.com/en/?tags=chiwino
type: sankaku
single: False
url: https://chan.sankakucomplex.com/en/?tags=chiwino
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1712179336.9542747 (24-04-03 21:22:16 UTC) - 19s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: False
goodbyedpi: None
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {}
live: False
changed: True


[File Names]



[URLs]



[Messages]
types: img, gif, video
https://chan.sankakucomplex.com/en/?tags=chiwino
'NoneType' object is not subscriptable
stop
Traceback (most recent call last):
 File "utils", line 1395, in start
 File "utils", line 1474, in start_
 File "C:\Users\georg\AppData\Local\Temp\_MEI109482\ytdl_84bbdafe\yt_dlp\yt_dlp\sankaku_downloader", line 144, in read
   info = get_imgs(self.url, self.name, cw=self.cw, types=types, session=self.session)
 File "C:\Users\georg\AppData\Local\Temp\_MEI109482\ytdl_84bbdafe\yt_dlp\yt_dlp\sankaku_downloader", line 269, in get_imgs
   tags = article.find('img', class_='preview')['data-auto_page'].split() #6718
TypeError: 'NoneType' object is not subscriptable

Invalid: fail=True
EOT: https://chan.sankakucomplex.com/en/?tags=chiwino  (2.5s)

**Comment by rickmiron** [comment]
Try this plugin:
https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py

**Comment by Aniconomics** [comment]
> Try this plugin: https://github.com/rickmiron/variado/blob/main/sankaku_downloader.py
> 
> 328 is the total number of images, there are no more in that tag

For that specific tag, yes. But I want to download from tags exceeding 1000 uploads and Gallery-dl doesn't work. The plugin you linked me has helped significantly. I am no longer receiving the invalid error. The only issues I am having now is the amount of images Hitomi is registering. If I use a tag with over 1900 uploads, Hitomi registers 1530 images and promptly begins downloading. I don't know why this inconsistency exists. But its a lot better than Gallery-dl

**Comment by Aniconomics** [comment]
There are 1900 uploads listed on the tag. Hitomi registers 1900 uploads and begins downloading.  For some reason, Hitomi stops downloading at 1535 images. Is this caused by the websites API or is this an issue with hitomi? What's the deal?

**Comment by rickmiron** [comment]
Show the tag to verify the total number of images

**Comment by Aniconomics** [comment]
![Captkkkkure](https://github.com/KurtBestor/Hitomi-Downloader/assets/65483331/b1828d2a-70cc-4404-913b-69947c7a8e91)

The number is roughly 1900+

 ![Captjjjjure](https://github.com/KurtBestor/Hitomi-Downloader/assets/65483331/3220c56a-0742-4c1c-a8c3-b8f6be4b3033)

Strongly enough, it lists down 2000 results. More than what is listed on Sankaku but its close enough. It stops at 1535 downloads every time. I lowered the downloads speed  to see if that was the issue. But it didn't work.

**Comment by rickmiron** [comment]
I tried it and a total of 1930 was downloaded,it loads cookies, sankaku does not show some images if you are not logged in.
options-->preferences-->network-->cookies-->load
In addition, you must also increase the limit of 2000
options-->preferences-->advanced-->maximum page limit
