### ISSUE TITLE
No module named 'downloader_v3'  in pyCharm

### ISSUE THREAD

**Issue by WeiMao33** [KurtBestor/Hitomi-Downloader#7100]
Sorry, I am new to Python, now I use pyCharm to run python. When i import the Hitomi-Downloader to pyCharm, it give me the error like this:"No module named 'downloader_v3'".
Where can I find 'downloader v3'?
<img width="597" alt="image" src="https://github.com/KurtBestor/Hitomi-Downloader/assets/104118173/1fa4fe9f-1428-463a-be3e-670422c7c601">

**Comment by rickmiron** [comment]
As far as I know, those modules are customized from Hitomi Downloader, so the only thing you can do is write the code and pass it as a plugin and test it in Hitomi Downloader.

**Comment by WeiMao33** [comment]
thanks @rickmiron
