### ISSUE TITLE
치지직 실시간 60프레임 녹화 시 에러 발생합니다.

### ISSUE THREAD

**Issue by AIRoom529** [KurtBestor/Hitomi-Downloader#7137]
25일 부터 치지직 60프레임 라이브 방송이 녹화가 안됩니다. 

30프레임 쪽은 문제 없이 되는데 60프레임 방송만 안되네요(파트너 상관없음)
아래와 같은 로그가 나옵니다.
---------------------------
[아리사Arisa] 2024-04-25 23:43 슬레이 더 스파이어 처음해요 (!vpn)

version: 4.1+ (24-04-13 01:21:04 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 0 / False / 3a5fef32dbfc423e91cbe43bab49c566
input: https://chzzk.naver.com/live/4de764d9dad3b25602284be6db3ac647
type: chzzk
single: True
url: https://chzzk.naver.com/live/4de764d9dad3b25602284be6db3ac647
dir: _chzzk
zip: 
artist: 아리사Arisa
valid / done: True / True
range / range_p: None / None
time: 1714056220.7977126 (24-04-25 14:43:40 UTC) - 206s elapsed
tags: []
lock: False
color: done
paused: False
format: None
p2f: None
segment: None
admin: False
res: 4320
goodbyedpi: None
ytdl: yt_dlp 2024.03.20.232704
pinned: False
extras: {seg_err: 0, seg_all: 33}
live: True
changed: True

[File Names]
[0001] _chzzk\[아리사Arisa] 2024-04-25 23：43 슬레이 더 스파이어 처음해요 (!vpn).mp4

[URLs]
[0001] Video(https://chzzk.naver.com/live/4de764d9dad3b25602284be6db3ac647)    --->    M3u8_stream(https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/hls_chunklist_1080p.m3u8?hdnts=st%3D1714055396~exp%3D1714086006~acl%3D%2A%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F%2A~hmac%3D593af0013f7a4ec6ec5eaa89cc6b1b66f5d7a4c6a943c5c6466774b3079317e8)

[Messages]
status: OPEN
media: 0
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1079395074_1714056208605_17022_0_8286.m4v?type=hls&bitrate=1115773&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_3320592624_1714056210605_17024_0_8287.m4v?type=hls&bitrate=1042210&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_748501250_1714056212605_17026_0_8288.m4v?type=hls&bitrate=1041690&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_4107110357_1714056218605_17032_0_8291.m4v?type=hls&bitrate=1054881&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2103492792_1714056220605_17034_0_8292.m4v?type=hls&bitrate=682969&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2167830630_1714056222605_17036_0_8293.m4v?type=hls&bitrate=1187838&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_453438879_1714056228605_17042_0_8296.m4v?type=hls&bitrate=962331&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_281795145_1714056230605_17044_0_8297.m4v?type=hls&bitrate=765768&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2607733629_1714056232605_17046_0_8298.m4v?type=hls&bitrate=1278042&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2156409879_1714056238605_17052_0_8301.m4v?type=hls&bitrate=884307&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2004921087_1714056240605_17054_0_8302.m4v?type=hls&bitrate=1194955&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_680989316_1714056242605_17056_0_8303.m4v?type=hls&bitrate=911412&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1880239832_1714056248605_17062_0_8306.m4v?type=hls&bitrate=1221008&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_3890158626_1714056250605_17064_0_8307.m4v?type=hls&bitrate=750004&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_4156120620_1714056252605_17066_0_8308.m4v?type=hls&bitrate=937000&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2844581858_1714056258605_17072_0_8311.m4v?type=hls&bitrate=1028012&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1093597056_1714056260605_17074_0_8312.m4v?type=hls&bitrate=1021720&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_3144229353_1714056262605_17076_0_8313.m4v?type=hls&bitrate=1027608&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1685235241_1714056268605_17082_0_8316.m4v?type=hls&bitrate=935538&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_501638205_1714056270605_17084_0_8317.m4v?type=hls&bitrate=1277988&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_140329433_1714056272605_17086_0_8318.m4v?type=hls&bitrate=1023791&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_3179782150_1714056278605_17092_0_8321.m4v?type=hls&bitrate=1013176&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_109945230_1714056280605_17094_0_8322.m4v?type=hls&bitrate=1028399&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_3226872220_1714056282605_17096_0_8323.m4v?type=hls&bitrate=998551&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2173668369_1714056288605_17102_0_8326.m4v?type=hls&bitrate=985440&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1849553832_1714056290605_17104_0_8327.m4v?type=hls&bitrate=1043493&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_525135076_1714056292605_17106_0_8328.m4v?type=hls&bitrate=1054520&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_784320880_1714056298605_17112_0_8331.m4v?type=hls&bitrate=1031534&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_4039931063_1714056300605_17114_0_8332.m4v?type=hls&bitrate=1000729&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1984040764_1714056302605_17116_0_8333.m4v?type=hls&bitrate=1033609&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_2548908331_1714056308605_17122_0_8336.m4v?type=hls&bitrate=1027898&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_410661592_1714056310605_17124_0_8337.m4v?type=hls&bitrate=1017658&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1729462722_1714056312605_17126_0_8338.m4v?type=hls&bitrate=1031243&filetype=.m4v' for reading
Opening 'https://livecloud.pstatic.net/chzzk/lip2_kr/cflexnmss2u0053/y7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg/hdntl=exp=1714086006~acl=*%2Fy7fgarozf9lsmdcfebo9wcfd6bk0x4w9yg%2F*~data=hdntl~hmac=098bc54433242e98365cc2d02018292f50c047752254a8cdfcc1e5d3b4037756/1080p_1316071405_1714056318605_17132_0_8341.m4v?type=hls&bitrate=994188&filetype=.m4v' for reading
Err: 0 / 33  (0.00%)
stop
-show_streams -print_format json -v error "[아리사Arisa] 2024-04-25 23：43 슬레이 더 스파이어 처음해요 (!vpn).mp4"
{

}
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002889b7b1b00] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002889b7b1b00] error reading header
[아리사Arisa] 2024-04-25 23：43 슬레이 더 스파이어 처음해요 (!vpn).mp4: Invalid data found when processing input
Traceback (most recent call last):
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

Traceback (most recent call last):
 File "utils", line 2021, in finish
 File "ffmpeg", line 876, in get_info
 File "ffmpeg", line 873, in get_info
Exception: Failed to convert; exit code: 1

EOT: https://chzzk.naver.com/live/4de764d9dad3b25602284be6db3ac647  (120.4s)
------------------

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by AIRoom529** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

30f, 60f 녹화 잘 됩니다. 감사합니다.

**Comment by AIRoom529** [comment]
녹화 잘 되는 거 확인하였습니다.
