### ISSUE TITLE
소설가가 되자 공백 오류

### ISSUE THREAD

**Issue by ppg13** [KurtBestor/Hitomi-Downloader#7148]
안녕하세요 오랜만에 찾아뵙습니다.
다름 아니라 소설을 받았던 4월 11일에는 괜찮았고 그 다음 받은 4월 23일경에 문제가 생겨서 문의하러 왔습니다.
문제란 다운은 끝까지 잘 되는데 소설 내용이 공백인 채 다운을 받고 있다는 것입니다.
그래서 해당 오류에 실험했던 소설은 일단 과거와 똑같은 4개와 같이 운영 중인 녹턴 연간 best 중 1개도 가지고 왔습니다.

버전: 4.1 (24-02-28 04:49:54 UTC) 과 4.1+ (24-04-26 23:09:49 UTC)

확인 방법은 첫 페이지부터 내용이 빈 것도 있으나 중간부터 빈 것도 있기에 회차별 txt 파일 크기 작은 순서대로 1KB부터 확인 했습니다.

https://ncode.syosetu.com/n2273dh/
http://ncode.syosetu.com/n3289ds/
https://ncode.syosetu.com/n8206dh/
https://ncode.syosetu.com/n5542gs/
https://novel18.syosetu.com/n8333im/

작업 정보는 내용이 비었지만 페이지는 전부 다운이 되기에 너무 길어서 기입을 안했습니다.
항상 감사하고 여름감기 조심하세요.

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by idskuld** [comment]
오우 잘 작동합니다!!
감사합니다!!
덕분에 오랜만에 볼수있네요. 감사합니다!!

**Comment by ppg13** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

전부 확인했습니다. 잘 됩니다!
정말 감사합니다.
