### ISSUE TITLE
토끼 무한 캡챠가 걸리는 문제가 있습니다ㅠ_ㅠ

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#7166]
캡챠가 도입되어 무한으로 캡챠가 걸리는 문제가 있습니다
캡챠가 통과가 안됩니다
수정해주세요ㅠ_ㅠ
![24-02-13  1757223063811232226_p0](https://github.com/KurtBestor/Hitomi-Downloader/assets/47520785/8294359a-94d9-4f2f-9006-58166c243420)
항상 감사합니다^^

**Comment by winniguy** [comment]
저도 3일째 고통받다가 어제 잠깐 풀렸었는데 한나절뒤에 다시 시도하니까 다시 무한캡챠네요 ㅜㅜ

**Comment by voskj** [comment]
다운목록에 넣고 저장후 종료후 다시 실행하면 통과 되긴 하네요

**Comment by wlskekrk** [comment]
전 쿠키 초기화하니까 되던데...

**Comment by systembest** [comment]
https://chromewebstore.google.com/detail/%ED%86%A0%EB%81%BC-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%8D%94/ohldgfmhhadhcemnbepnciaoanbbaeba

수정될때까지 이거라도 쓰심이

**Comment by geniussjt** [comment]
토끼 다운로더 
아예 다운 안됩니다ㅠ_ㅠ

**Comment by lsh4711** [comment]
@geniussjt 
토끼 다운로더 잘됩니다.
당시에 다운로드 가능해지실 때까지 하루종일 문제를 해결해드린거로 기억하며
문의 주실때마다 최대한 친절하게 대응해드린 것으로 기억합니다.
