### ISSUE TITLE
뉴토 사이트이 안들어가집니다

### ISSUE THREAD

**Issue by geniussjt** [KurtBestor/Hitomi-Downloader#7170]
![24-02-13  1757223063811232226_p0](https://github.com/KurtBestor/Hitomi-Downloader/assets/47520785/a9ecb774-f2c6-4d51-88d4-062aa57e835e)
컴퓨터 아이폰 다 잘 들어가는데요 눈동자만 안 들어가집니다 그리고 토끼 무한 캡챠가 걸리는 문제도 있습니다
캡챠가 통과가 안됩니다ㅠ_ㅠ엉어

**Comment by Orange6539** [comment]
이건 마나토끼에 너무 과한 네트워크 부하(마나토끼 사이트에 과다하게 접속하거나 여러개를 동시에 다운받는 등)를 줬을경우
해당 브라우저가 차단되면 저렇게 뜹니다
일정 시간 지나면 다시 접속 됩니다

다운로드 동시작업 갯수를 2 이하로 설정하시고 최대연결도 낮게 설정해야 차단 안당합니다

**Comment by geniussjt** [comment]
3일이 지나는데..요...아직도 그대로입니다ㅠ_ㅠ

**Comment by Orange6539** [comment]
그러면 남는 수단은 한가지 입니다
지금 접속되는 본인 IP 체크하시고(공유기 ip 말고 192.168....이런거 X)
공유기 말고 인터넷 모뎀 전원을 뽑고 몇분 있다가 다시 꼽아 IP 주소를 바꿔야 합니다
꼭 IP 변경 됐는지 확인 하세요

**Comment by SemteulGaram** [comment]
동일 이슈
처음부터 동시 다운로드 2개 이상 건적도 없고
다른 나라, 다른 지역 쪽 컴퓨터에서 원격으로 접속해도 동일하게 무한 클플 캽차 뜨거나 겨우 한번 정도 됩니다.
