### ISSUE TITLE
Bug or site change: codec priority no longer working

### ISSUE THREAD

**Issue by TheGhost78** [KurtBestor/Hitomi-Downloader#7182]
The program downloaded the VP9 codec version of the video despite an H264 version being available.

https://www.youtube.com/watch?v=3t5N4npZKb0

**Comment by TheGhost78** [comment]
Same with this video:
https://www.youtube.com/watch?v=YNSxNsr4wmA

**Comment by KurtBestor** [comment]
I can't reproduce it on my end

**Comment by TheGhost78** [comment]
It's definitely happening with the two links above, and other videos on YouTube.

**Comment by TheGhost78** [comment]
Here's another one:
https://www.youtube.com/watch?v=TZqzu34sUYo

**Comment by TheGhost78** [comment]
I downloaded this channel using the link below:
https://www.youtube.com/@Mylunchbreak/featured

49 videos were VP9, and 28 were AVC.

**Comment by TheGhost78** [comment]
Any update on this? It's still happening.

**Comment by TheGhost78** [comment]
Will this be fixed in an update?

**Comment by TheGhost78** [comment]
I just deleted the .ini settings file and it now appears to work fine again. So, there must have been some corruption there? The new ini file, created fresh by opening the program, is 84kb whereas the old one was 756kb.
