### ISSUE TITLE
what does the button on the left of the input field with the tooltip "Download Pause / Resume" do ?

### ISSUE THREAD

**Issue by jack652** [KurtBestor/Hitomi-Downloader#7307]
what does the button on the left of the input field with the tooltip "_**Download Pause / Resume**_" do ?

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/48365199/078a800a-2ad3-4227-9955-dc1845917655)

**Comment by rickmiron** [comment]
If disabled, prevents new tasks from starting

**Comment by jack652** [comment]
> If disabled, prevents new tasks from starting

I see
I think it would be cool to have the possibility to prevent specific tasks / groups from starting too
