### ISSUE TITLE
Youtube Option now Not Available.

### ISSUE THREAD

**Issue by gwashark** [KurtBestor/Hitomi-Downloader#7314]
You can't use the Youtube option as Google has released a ban hammer on using their api.

403 - Unauthorized

![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/150717581/24be5b59-d580-462e-abe5-5999905b43df)

[View the Logs Here](https://pastebin.com/w47yY0T0)

# Other People Experiencing the Issue:
[Node YTDL Core - Issue #1295 - 403 Error](https://github.com/fent/node-ytdl-core/issues/1295)

**Comment by jack652** [comment]
works fine on my end
![image](https://github.com/KurtBestor/Hitomi-Downloader/assets/48365199/2fb53641-6635-48c9-ad72-7d60862440e7)

**Comment by gwashark** [comment]
@jack652 proxy or no proxy?

**Comment by gwashark** [comment]
Well… I’m gonna close this if it does.

**Comment by jack652** [comment]
> @jack652 proxy or no proxy?

no proxy

**Comment by gwashark** [comment]
> > @jack652 proxy or no proxy?
> 
> no proxy

Yeah it worked again.
