### ISSUE TITLE
최대 페이지 제한 옵션이 저장이 안 되요

### ISSUE THREAD

**Issue by Summertoohot** [KurtBestor/Hitomi-Downloader#7466]
최대 페이지 제한을 50으로 저장하고

 다운로더를 껐다가 키면

최대 페이지 제한이 2000으로 다시 돌아갑니다

**Comment by fdsa1538** [comment]
저는 업데이트 하기 전엔 제대로 됐는데 업데이트 하고 나니까 이런 증상이 생기네용

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by fdsa1538** [comment]
테스트 버전은 최대 페이지 제한 설정이 프로그램을 종료했다가 다시 실행해도 제대로 저장되어 있습니다

**Comment by Summertoohot** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

적용이 정상적으로 저장됩니다! 감사합니다

**Comment by LazyLoding** [comment]
> 테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

똑같네요 해당파일로 하여도 레이지로딩 기능을 껐음에도 불구하고 화면에 보이는부분만 로딩이됩니다 ㅎㅎ;
