### ISSUE TITLE
목록을 익스포트 가능할까요 ? 

### ISSUE THREAD

**Issue by korhentai** [KurtBestor/Hitomi-Downloader#7517]
항목이 많아지니 관리가 거의  안되서요 3 달 이상된 애들만 목록에서 지우고 따로 저장해서 관리하려고 하는데... 

.hdt 는 텍스트 뷰어나 다른걸로 안열리던데 

혹시 url / 폴더 제목 / 받은파일 경로 ? 정도로 CSV 나 txt, 를 저장할수 있을까요 ? 

ex) "www.server.com/comic/33014/67", "디씨코믹스 67화", "[0001] https://n4.server.com/data/df/67/df6774bdf2e7954a25e13801acada8355a92041af769f65bc3fc4d2720829f06.png"

**Comment by KurtBestor** [comment]
메모장 등 텍스트 에디터로 열 수 있고 포맷은 JSON 이에요

**Comment by korhentai** [comment]
> 메모장 등 텍스트 에디터로 열 수 있고 포맷은 JSON 이에요

아... 파일이 열리고 내용이 없어서 문의 드린거였는데 파일사이즈가 커서 그랬네요 ㅎㅎ ;;; 
500MB 쯤 되니까 안열리는군요 ;;;; 

감사 합니다.
