### ISSUE TITLE
치지직 쿠키는 넣을수가 없나요?

### ISSUE THREAD

**Issue by rudoia** [KurtBestor/Hitomi-Downloader#7519]
언령제한 영상이 녹화가 끝나고 어떤 동영상 프로그램으로 실행을 하던 재생할수없음 이라는 알림이 뜨고 0xc00d36c4 라는 코드가 뜨면서 재생조차 할수가 없네요 파일 클릭시 영상용량은 나오는데...
사이트 업데이트를 하면서 쿠키가 초기화 된듯한데 이 쿠키를 재설정하는데 문제가 생긴것 같습니다 사이트에 들어가서 로그인 하고 확장프로그램을 클릭해도 반응이 없고 No cookies found for chzzk.naver.com 라는 문구만 있습니다
이를 해결할 방법은 없을까요?

**Comment by KurtBestor** [comment]
쿠키와는 상관이 없는 것 같고, 프로그램 실행하자마자 녹화했을 때 깨지는 증상은 다음 참고해주세요: https://github.com/KurtBestor/Hitomi-Downloader/issues/7399#issuecomment-2274028386
