### ISSUE TITLE
핀터레스트 다운로드 오류

### ISSUE THREAD

**Issue by eleage8992** [KurtBestor/Hitomi-Downloader#7541]
일반적으로 핀터레스트 보드들은 잘 작동 하는것으로 보이는데 가끔 이런 식으로 안되는 보드들이 있습니다.
언제나 잘 사용하게 해주셔서 감사합니다.

Invalid: [pinter] https://kr.pinterest.com/chdjs54785210/ai-variadas-3/

version: 4.1+ (24-10-03 18:33:51 UTC)
platform / locale: Windows-10-10.0.19045-SP0 / ko_kr
order / group / uid: 2250 / False / a1fd9e15fc224b46aba5c863c8bd44ac
input: https://kr.pinterest.com/chdjs54785210/ai-variadas-3/
type: pinter
single: False
url: https://kr.pinterest.com/chdjs54785210/ai-variadas-3/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1728463481.5733743 (24-10-09 08:44:41 UTC) - 879s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
res: 1080
goodbyedpi: False
ytdl: yt_dlp 2024.09.27
pinned: False
extras: {}
live: False
changed: True

[File Names]

[URLs]

[Messages]
type: board
live
stop
Traceback (most recent call last):
 File "utils", line 1400, in start
 File "utils", line 1490, in start_
 File "extractor\pinter_downloader", line 65, in read
 File "extractor\pinter_downloader", line 229, in get_imgs
 File "extractor\pinter_downloader", line 201, in __init__
Exception: live

Invalid: fail=True
EOT: https://kr.pinterest.com/chdjs54785210/ai-variadas-3/  (523.4s)

**Comment by KurtBestor** [comment]
테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader/releases/tag/Technical-Preview

**Comment by eleage8992** [comment]
정상적으로 잘 작동하네요 감사합니다.
