### ISSUE TITLE
chzzk replay video

### ISSUE THREAD

**Issue by rudoia** [KurtBestor/Hitomi-Downloader#7570]
Hello developer, when I download a replay of chzzk, the video quality is not downloaded at 1080p. What should I do about it?

**Comment by ELSecretos** [comment]
chzzk's replay video takes quite a while to be encoded. In my experience, if you wait for similar hours of the replay video after the broadcast ends and try again, you can successfully download it in 1080p.

**Comment by rudoia** [comment]
Ah... it was just as I thought. Thank you for teaching me.
