### ISSUE TITLE
ohli24 다운받는법은 알아냈는데 코드작성하는법을 몰라서 고수분들한테 부탁드립니다!

### ISSUE THREAD

**Issue by Psychopath7** [KurtBestor/Hitomi-Downloader#7576]
알고 계실 수도 있지만 일단 제가 찾아낸 방법으로는

애니24에서 보고싶은 애니메이션 접속( _https://a24.ohli24.com/e/Re:%20%EC%A0%9C%EB%A1%9C%EB%B6%80%ED%84%B0%20%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%84%B8%EA%B3%84%20%EC%83%9D%ED%99%9C%203%EA%B8%B0%201%ED%99%94_ )해서 개발자 모드에 네트워크 탭에 들어가면 master.txt파일이 뜸. 
그 파일을 다운받으면 URL( _https://cdndania.com/m3/MmdHN3dzVFFtNXNBZUMvRGJrYnplRVFzK0lzeG9lak92NnpGZUkzSjZXYldkcUZkUlJvT1psdHZrVTFHWjl1OTA0YmdtZGN0V0lkNTFKaVdkWVNVMnVOeFZuUUdYUnRGS3MvanZRdHNuZUdUWldKeWtQT1dheEdmZGtrTENBVEFqelZqOURzQnJGQUo4eTdzSTNTbTZlemNZU2FidnY1QWJNeDZOcEVPSWtuTWZzbG9Jd2NVdk1JeE1scVRsK2hHRmpuNkcrZWNIQUFoTHBIRDd6SytpcDNnQVNsRW9oeE8wWWVXQnJBK1FXNnE4eEl0OTN5NGlvdDc5RHpFdTVWYndacy9SR1MzVXhnYi80amxaYzZ0WllvMksrR2xxTkgyRXgxRGxZdHdQQnAranRuTWs2UlZta05wWTZVZ3hwa0g%3D_ )이 있는데
이걸 _ffmpeg -f hls -i "https://cdndania.com/m3/ODVnYlpHdG9WMEJ2V3VHOWJZVFl1ODY4OCtSUVJZT1dRVTB0UDN0T1dFSkN1ajd4amVCKzlGcFFBaGtUYnhVUTkyTmZ2ckRJazJCRmZVc0ZLcTZpcm1CcnRKbUVoNHZPTDVocVpGbG5iRVZMTnppdUlROWEvQ1dRNjVFYk5oY0x1VUlINnd1TmN6ekhrVytzWHFZN21ZY2lXTW1TQ2FLbUVjSVprcUg3YlVWTlREQXRUKzlNV092ZFVFQXFJMVowUDY5Wlg5RzhBdTZFQTF5bmtVRUNVWXlzOEYzcWJpN1lyTkFyZ0VmbU9qM3hCZU1GekMrekxYbk1JOVFxazJvREhLbk1MaTVleE1qTGVSNVpBcnNkVWdFVEFKUHZSOFN5WDdxR3dKWHBnd2JCWFVZQjBvRldiVk84TUVyZlUydTc%3D" -c copy Re: 제로부터 시작하는 이세계 생활 3기 1화.mp4_ 실행하면 다운이 가능합니다.

이건 하드코딩된 자막영상이여서 이것만 다운받으면 되는데 영상과 자막이 따로인 영상도 존재합니다. 이럴때는 thumbnails.vtt라는 파일이 자막 파일입니다. 하드코딩된 자막영상도 thumbnails.vtt이 있긴한데 열어보면 자막이 아닙니다. thumbnails.vtt은 영상과 자막이 분리된 영상에만 자막파일 역할을 하는걸로 보입니다. 이후에는 ChatGPT 써가면서 코드를 만들어봤는데 전혀 진전이 없습니다ㅜ
저는 여기까지인 것 같으니 이를 토대로 hitomi downloader에 적용할 수 있는 코드를 작성해주실 고수분들께 부탁드립니다ㅠ
hitomi downloader에 적용이 안되더라도 단독으로 exe파일을 만드셔도 괜찮습니다:)

만약 가능하면, 필요한 기능은 굳이 하나씩 접속 안 해도
_https://a24.ohli24.com/c/Re:%20%EC%A0%9C%EB%A1%9C%EB%B6%80%ED%84%B0%20%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%84%B8%EA%B3%84%20%EC%83%9D%ED%99%9C%203%EA%B8%B0_ 
접속 시, 목록에 있는 영상들과 자막들을 선택 혹은 일괄로 다운받을 수 있으면 좋겠고, 파일 이름이 e/ 뒷부분을 URL 디코딩한 이름으로 자동변경 됐으면 좋겠습니다.
_(https://a24.ohli24.com/e/Re:%20%EC%A0%9C%EB%A1%9C%EB%B6%80%ED%84%B0%20%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%84%B8%EA%B3%84%20%EC%83%9D%ED%99%9C%203%EA%B8%B0%201%ED%99%94_ 에서 e/ 뒷부분인 _Re:%20%EC%A0%9C%EB%A1%9C%EB%B6%80%ED%84%B0%20%EC%8B%9C%EC%9E%91%ED%95%98%EB%8A%94%20%EC%9D%B4%EC%84%B8%EA%B3%84%20%EC%83%9D%ED%99%9C%203%EA%B8%B0%201%ED%99%94_ 이 부분을 URL로 디코딩한 _'Re: 제로부터 시작하는 이세계 생활 3기 1화'_ 이런 식으로 자동으로 이름이 변경됐으면 좋겠습니다.)
감사합니다.

수정 : vtt파일이 자막파일이 아니었습니다..

**Comment by rickmiron** [comment]
이 가이드를 사용하세요
https://github.com/rickmiron/variado/blob/main/testwiki_downloader.py

**Comment by rickmiron** [comment]
내 인턴십 시즌이 끝났어.
원하신다면 해당 페이지에 대한 코드를 구성하는 방법을 안내해 드리겠습니다. 먼저 Python에 익숙해지세요.

**Comment by Psychopath7** [comment]
ChatGPT의 도움을 받아 단독으로 다운로드할 수 있는 코드는 작성했는데, hitomi downloader에서 스크립트로 작동하도록 바꾸지 못하겠어요.
[ohli24_downloader.zip](https://github.com/user-attachments/files/17609203/ohli24_downloader.zip)

**Comment by rickmiron** [comment]
Hitomi Downloader 포맷에 맞춰 정렬했습니다
[ohli24_downloader.zip](https://github.com/user-attachments/files/17611350/ohli24_downloader.zip)

**Comment by Psychopath7** [comment]
감사합니다!! 정상적으로 작동해요! 근데 목록URL을 입력했을 때 각 영상을 개별적으로 다운로드 되게 할 수 있을까요? 지금은 목록URL을 입력하면 모든영상을 한번에 다운로드가 해요.

**Comment by rickmiron** [comment]
시도해 보세요 
[ohli24_downloader.zip](https://github.com/user-attachments/files/17625388/ohli24_downloader.zip)

**Comment by Psychopath7** [comment]
목록URL을 넣었을 때 개별로 다운로드가 되긴하는데 기존주소가 남아있어요.
![캡처](https://github.com/user-attachments/assets/eeb35479-9341-422d-bd29-84dda8d41503)

또한 자막있는 영상은 다운로드가 되긴하는데 %가 안떠요.
![캡처1](https://github.com/user-attachments/assets/c7eaa7e5-3dbb-43ee-b93c-3b5eca82aba6)

rickmiron님의 linkkf_downloader 스크립트는 자막과 영상이 같이 있어도 %가 보이던데 이런 식으로 작동했으면 좋겠습니다!
![캡처2](https://github.com/user-attachments/assets/b6b243f7-30aa-46bf-9d3c-b900db86aa5d)

아 그리고 '읽는 중'이 오랫동안 뜨다가 다운로드가 진행이 되는데, 기존코드의 디버깅 메세지와 로그 메시지 때문이라면 코드에서 필요없는 부분은 삭제해서 깔끔하게 부탁드리겠습니다!

항상 감사합니다!

**Comment by rickmiron** [comment]
이제 자막이 있을 때 백분율이 표시됩니다.
[ohli24_downloader.zip](https://github.com/user-attachments/files/17635703/ohli24_downloader.zip)

삭제할 코드를 모르므로 선택적으로 메뉴 상단에 버튼을 만들고 모든 링크를 캡처한 다음 실행하여 다운로드할 수 있습니다.
읽기 시간에는 지연이 있습니다. 먼저 장의 html, 자막의 html, 비디오 게시, 비디오 스트림을 요청하고 각 요청에 최대 2초가 걸릴 수 있기 때문입니다. 이 프로세스는 순차적이므로 시간이 더해집니다.

**Comment by Psychopath7** [comment]
자막파일 영상은 정상적으로 작동합니다! 감사합니다!!
음.. 목록URL을 입력해서 추출된 개별URL 중 하나로 목록URL이 변환되고 변환되지 않은 나머지 개별URL은 그대로 다운로드하게 하면 깔끔해지지 않을까요?

**Comment by Psychopath7** [comment]
모두 해결이 되었어요!
영상 덮어쓰기는 아직 안되지만 그래도 나머지는 전부 해결이 되었습니다!
너무 감사합니다!♡

**Comment by Psychopath7** [comment]
해결이 되었어요!
파일 덮어쓰기는 아직 안되지만 그래도 나머지는 전부 해결이 되었습니다!
지금도 만족하니 괜찮습니다! 너무 감사합니다!♡♡

아이콘과 제작자를 추가했습니다:) 다시 한번 너무 감사드리고 다음에 또 봬요!♥
[ohli24_downloader.zip](https://github.com/user-attachments/files/17663260/ohli24_downloader.zip)

**Comment by Psychopath7** [comment]
https://ohli24.com/c/%EC%9D%BC%EA%B3%B1%20%EA%B0%9C%EC%9D%98%20%EB%8C%80%EC%A3%84:%20%EB%AC%B5%EC%8B%9C%EB%A1%9D%EC%9D%98%204%EA%B8%B0%EC%82%AC%202%EA%B8%B0

목록이 한 개인 사이트에서는 '이미 추가한 작업입니다. 계속하시겠습니까?' 라는 메세지가 뜹니다. '확인'을 하든 '취소'를 하든 다운로드는 진행이 되지만 이 메시지가 뜨지 않았으면 좋겠습니다.

![캡처](https://github.com/user-attachments/assets/962645e2-68cd-491c-bf3e-95431d0775f8)
