### ISSUE TITLE
익헨 사이트 내의 "타입:Cosplay" 카테고리 검색 필터링 옵션 추가 건의

### ISSUE THREAD

**Issue by eleage8992** [KurtBestor/Hitomi-Downloader#7615]
사용에 버그와 같은 큰 지장이 없으나 편의를 위한 건의를 하고 싶습니다. 

![다운로드](https://github.com/user-attachments/assets/5e27ad07-f051-447b-8aa8-959a866bb8b3)
위 첨부된 사진의 익헨 사이트 내부의 Cosplay 카테고리와 같은 익헨 내부 타입별 검색필터가 있었으면 좋겠습니다.

추가됐으면 하는 이유는 예를 들어
https://exhentai.org/g/2997433/719429421a 페이지를 다운받아 작업정보창을 확인하면

[Gallery]
갤러리 넘버: 2997433

제목: Tina Kinz - Fia

작가: N/A

그룹: N/A

**타입: cosplay**

시리즈: elden ring

캐릭터: N/A

태그: non-nude, female:big breasts, female:makeup, female:very long hair

언어: N/A

처럼 작가, 그룹, 언어, 캐릭터, 시리즈와 같은 태그에서는 불규칙적으로 N/A라고 표기가 되므로 
직접적으로 cosplay 검색을 통해서는 제목에 cosplay가 포함된 목록만 필터링 되고

현재 히토미 다운로더 내 검색필터링의 "Type:" 필터링은 사이트를 필터링 하는 기능으로 보이며
위의 익헨 내부의 **타입: cosplay**로 검색하고자 검색이 불가능합니다.

편의를 위해 익헨의 타입 카테고리만을 필터링하는 다운로더 작업 목록 필터링 기능이 추가되었으면 합니다.
부탁드리겠습니다.

**Comment by KurtBestor** [comment]
다음과 같이 필터링하면 돼요:
```python
script:"item.gal.type=='cosplay'"
```

**Comment by eleage8992** [comment]
이런 방법이 있었네요 너무 감사합니다.혹시 이런 필터링방법도 도움말 F1 사용법에 추가해주실수 있을까요?
