### ISSUE TITLE
어제부터 유튜브 영상이 360p로 다운로드 됩니다.

### ISSUE THREAD

**Issue by DBdeepsleeper** [KurtBestor/Hitomi-Downloader#7725]
옵션은 2k로 설정되어 있고요.

그제 받은 거 까지는 괜찮은데 어제부터 360p로 다운이 돼서 보고합니다.

**Comment by BeBe2023** [comment]
Have you logged into your YouTube account using the built-in browser? 
I can log out of my YouTube account in the browser and it will return to normal.

**Comment by DBdeepsleeper** [comment]
> Have you logged into your YouTube account using the built-in browser? I can log out of my YouTube account in the browser and it will return to normal.

thank you bro.

![image](https://github.com/user-attachments/assets/261b9fc9-8341-4a02-bc3f-967ae44f393c)

내장 웹브라우저 켜는 방법

활성화 후 브라우저 실행 - youtube.com 접속 - 로그 아웃

**Comment by KurtBestor** [comment]
고쳤어요
