### ISSUE TITLE
중복 이미지 찾기에서 일괄 삭제 기능이 추가되었으면 합니다

### ISSUE THREAD

**Issue by NewBe1446** [KurtBestor/Hitomi-Downloader#994]
안녕하세요 개발자님 프로그램 잘 사용중인 한 유저입니다.
gamecg 카테고리에서 같은 제목인 파일을 여러개 다운받아서
파일을 정리하는데 중복인 사진이 너무나 많아서
중복 이미지를 편하게 삭제하는 방법을 찾아봤지만
프로그램들이 하나같이 비싸거나, 무료 프로그램은 인식률이 떨어져 서로 다른 파일을
똑같은 파일로 인식하기도 합니다.
히토미 다운로더 내에서 어떤 원리로 중복 이미지를 찾아내는지는 모르겠지만
비싼 전용 프로그램보다 검색 속도도 빠르고, 중복인 사진을 정확하게 찾아내는 성능도 훨씬 좋습니다.
저번에 같은 주제로 건의가 한번 올라온적이 있었으나 개발자님이 해당 기능은 필요없을거 같다고 하셨던 적이 있습니다만, 혹시 이런 기능 추가를 해주실 여유가 있으시다면 해당 기능 추가를 다시 한번 건의 드리고 싶습니다.
좋은 프로그램 잘 사용하고 있으며, 답변 기다리겠습니다.

**Comment by NewBe1446** [comment]
이슈 리스트 다시 찾아보니 #274 여기에 저와 같은 의견 남겨주신 분 계신데,
중복 파일일 경우 파일 하나만을 남기고 나머지를 일괄 삭제하는 기능 추가를 건의드린겁니다.

**Comment by KurtBestor** [comment]
![image](https://user-images.githubusercontent.com/14768120/76601051-7d751880-654b-11ea-8758-b0a9756ae2fa.png)

테스트 부탁드려요: https://github.com/KurtBestor/Hitomi-Downloader-issues/releases/tag/Technical-Preview
